SourceX/miniwin.cpp
=> implement itoa

Source/sound.cpp, SourceS/miniwin_dsound.h, SourceX/dx.cpp, SourceX/miniwin.cpp, SourceX/miniwin_io.cpp, SourceX/sound.cpp, SourceX/storm.cpp
This fixes
- Menu sounds being cut short
- Spartial sound in game
- Memory leaks
- Sound volume
=> Implement most of sound.cpp

SourceX/DiabloUI/diabloui.cpp, SourceX/DiabloUI/diabloui.h, SourceX/dx.cpp, SourceX/miniwin/misc.cpp
[devilutionx]
scaling quality=2  // see SDL_HINT_RENDER_SCALE_QUALITY
fullscreen=1
grab input=1
=> Make graphics modes configurable

README.md
=> Add instructions to build on Fedora

Xcode/devilutionX.xcodeproj/project.pbxproj
This fix the macOS build for x86
=> Updating Xcode project with new files

Xcode/devilutionX.xcodeproj/project.pbxproj
Adding the new files to the xcode project.
=> update Xcodeproj with *dat files

3rdParty/StormLib/src/FileStream.cpp
=> Start fix for Haiku

SourceX/DiabloUI/diabloui.cpp
Continuing the changes in devilution
=> Replace ROW_PITCH with BUFFER_WIDTH in dX

SourceX/DiabloUI/selconn.cpp, SourceX/dvlnet/udp_p2p.cpp
Can someone confirm the change to `udp_p2p::join`, please?
=> Use MAX_PLRS (dX part)

README.md
Since there's a package for Haiku, may as well add instructions for it.
=> readme: Add build instructions for Haiku

Source/loadsave.cpp
=> Fix typo in LoadPremium, SavePremium.

3rdParty/StormLib/src/FileStream.cpp, 3rdParty/StormLib/src/SBaseCommon.cpp, 3rdParty/StormLib/src/StormPort.h, SourceS/miniwin/misc_macro.h
* Add Amiga platform
* Add some big endian swap functions for non-Mac platforms
=> StormLib Big Endian additions

Source/capture.cpp
Fixes #63. I basically just implemented what @galaxyhaxz outlined [here](https://github.com/diasurgical/devilutionX/issues/63#issuecomment-513590422), and also changed the path to the one given by SDL.
I can only test on Windows, cross-compiling from Linux using MinGW. If there are any problems with other OSs, please let me know.
Also, I couldn't figure out how to do it without changing Source/capture.cpp. If anyone knows a way that doesn't involve changing the original source files, again, please let me know.
=> Fix screenshot paths

CMake/Findsodium.cmake
https://github.com/facebookincubator/fizz/blob/master/fizz/cmake/FindSodium.cmake
This appears to fix build issues for some Mac users.
=> Use facebookincubator findflindsodium cmake helper

Source/msg.cpp, Source/nthread.cpp, Source/nthread.h, SourceX/dvlnet/frame_queue.cpp, SourceX/dvlnet/frame_queue.h, structs.h
=> 64-bit multiplayer

SourceX/DiabloUI/diabloui.cpp
Profiling the menu, DrawArt goes from 94% to 86%, though it's hard to measure with any reasonable precision.
=> [performance] Make DrawArt faster

SourceS/sdl2_to_1_2_backports.h, SourceX/storm/storm.cpp
1. Implements audio support for SDL1 (via a callback)
2. Implements blit scaling and correct video rendering for SDL1 (backport of `SDL_BlitScaled` plus copying the palette on every change).
Fixes #263 
Audio plays clear, no clicking / noise.
=> SDL1: Audio and video support

.editorconfig, CMakeLists.txt, SourceX/DiabloUI/diabloui.cpp, SourceX/DiabloUI/title.cpp, SourceX/miniwin/misc.cpp, SourceX/miniwin/misc_msg.cpp, touch/touch.cpp, touch/touch.h
Makes #271 build with USE_SDL1
=> switch-next: Make it build with USE_SDL1

CMakeLists.txt, SourceX/miniwin/dsound.h, SourceX/sound.cpp
Also link ASAN for devilutionx
=> Fix memory leak in sound.cpp

CMakeLists.txt, SourceX/dvlnet/abstract_net.cpp, SourceX/dvlnet/base.cpp, SourceX/dvlnet/packet.h, SourceX/dvlnet/tcp_client.cpp, SourceX/dvlnet/tcp_server.cpp
std::make_unique is only available in C++17 and above
=> Make SourceX/dvlnet C++11 compatible

SourceX/storm/storm_net.cpp
Those information could be accessed by pressing tab key in multiplayer
Fix #260
Server Game name will be 0.0.0.0 or the address in the .ini file
=> Fill GAMEINFO for name and password

SourceX/dvlnet/tcp_client.cpp, SourceX/dvlnet/tcp_client.h
So you can join another game latter
fix #251
There is still issue if you start a server, then leave, then try to join another game
=> tcp_client: close connections when leaving

.editorconfig, CMakeLists.txt, SourceX/.clang-format, SourceX/DiabloUI/art.cpp, SourceX/DiabloUI/art.h, SourceX/DiabloUI/diabloui.cpp, SourceX/DiabloUI/diabloui.h, SourceX/DiabloUI/dialogs.cpp, SourceX/DiabloUI/mainmenu.cpp, SourceX/DiabloUI/selconn.cpp, SourceX/DiabloUI/selgame.cpp, SourceX/DiabloUI/selhero.cpp, SourceX/DiabloUI/selyesno.cpp, SourceX/DiabloUI/title.cpp, SourceX/DiabloUI/ui_item.h
Makes the code easier to understand.
Also makes building lists easier.
Also fixes focus indicator in SELLOAD_DIALOG (this type of bug is impossible with the new structs).
=> DiabloUI: Refactor UI_Item to tagged unions

SourceS/miniwin/misc.h, SourceX/miniwin/misc_io.cpp, SourceX/miniwin/thread.cpp
Correct memory leak after creating a network party
=> Correct memory leak

SourceX/DiabloUI/diabloui.cpp, SourceX/DiabloUI/selconn.cpp, SourceX/DiabloUI/selgame.cpp, SourceX/DiabloUI/selhero.cpp, SourceX/DiabloUI/selyesno.cpp, SourceX/DiabloUI/ui_item.h
No scrollbar yet, keyboard scrolling only
Refs #62
=>  Make hero selection list scrollable 

SourceX/DiabloUI/selyesno.cpp
=> Make the Yes/No dialog list wrap

CMakeLists.txt, SourceX/DiabloUI/diabloui.cpp, SourceX/DiabloUI/diabloui.h, SourceX/DiabloUI/scrollbar.cpp, SourceX/DiabloUI/scrollbar.h, SourceX/DiabloUI/selhero.cpp, SourceX/DiabloUI/ui_item.h
Has the same weird behaviour as the actual Diablo scrollbar but without the subtle mouse interaction bugs.
Fixes #62
=> DiabloUI: Add a scroll bar to hero selection

Packaging/debian/changelog, Packaging/debian/devilutionx.install, Packaging/debian/rules
=> Debian Package update

CMake/FindSDL2_ttf.cmake
=> FindSDL2_ttf.cmake: Fix header check

Source/engine.h
```
runtime error: load of misaligned address 0x632000363773 for type 'WORD', which requires 2 byte alignment
0x632000363773: note: pointer points here
7f  7f 7f 3e 0a 00 02 01 50  04 00 00 00 00 7f 7f 7f  7f 7f 7f 7f 7f 7f 34 bc  ac ff bc 5b f9 fc dc
```
It was actually out-of-bounds as well so I had to add a bounds check.
=> Fix UB: Misaligned access in GetCelFrameClipped

SourceX/miniwin/misc.cpp
This "just works" now, not sure which of the commits fixed it.
=> SDL1: Support fullscreen

Source/diablo.h, SourceS/sdl2_backports.h, SourceX/miniwin/misc_msg.cpp, SourceX/storm/storm.cpp
RG350 and GCW0 devices have an ancient version of SDL2.
=> Compatibility with SDL v2.0.3

SourceX/DiabloUI/selconn.cpp
UDP was not displayed in the menu but using down key show the details
associated to UDP
=> Fix display of Connection menu

SourceX/miniwin/misc_msg.cpp
Implements all the keys asked for by devilution(x) code (including the Switch branch).
=> GetAsyncKeyState: Implement more keys

3rdParty/StormLib/src/StormPort.h
Upstream: https://github.com/ladislav-zezula/StormLib/pull/160
Refs: #384 https://github.com/diasurgical/devilutionX/issues/378#issuecomment-544471019
=> StormLib: Backport #include <strings.h> for unknown platforms

Source/control.cpp, Source/engine.cpp
Simplify code and may produce better performances
=> Simplify few loops by using memcpy

Source/engine.cpp, Source/missiles.cpp, Source/monster.cpp, Source/objects.cpp, Source/palette.cpp, Source/pfile.cpp, Source/scrollrt.cpp, SourceX/sound.cpp
This will also slightly improve performance for release builds
=> Enable assertions

Source/render.cpp
Few code simplification that should also improve the performances
=> More memcpy memset

Source/drlg_l1.cpp
=> Fix OOBs in DRLG_L5Subs

Source/drlg_l1.cpp
=> Fix multiple OOB in L5tileFix

Source/monster.cpp
I'm not entirely sure what `_meflag` is but this seems like the right fix. Thoguhts?
=> Fix OOB in M_CheckEFlag

Source/interfac.cpp, SourceX/DiabloUI/art_draw.cpp, SourceX/DiabloUI/diabloui.cpp, SourceX/DiabloUI/text_draw.cpp
It's a bit hacky but got few loc :)
=> Center gui

CMakeLists.txt, SourceS/miniwin.h
Now as a PR instead of a diff attach to an issue (#413).
=> Upstream support for OpenBSD.

README.md
Pointed out by @AJenbo in #413.
=> Compiling instructions for OpenBSD

Source/lighting.cpp
=> Fix OOB in lighting

CMakeLists.txt, Source/diablo.cpp, Source/palette.cpp, SourceX/dvlnet/abstract_net.cpp, SourceX/dvlnet/abstract_net.h, SourceX/dvlnet/base.cpp, SourceX/dvlnet/base.h, SourceX/dvlnet/cdwrap.cpp, SourceX/dvlnet/cdwrap.h, SourceX/dvlnet/tcp_client.cpp, SourceX/dvlnet/tcp_client.h, SourceX/dvlnet/tcp_server.cpp, SourceX/dvlnet/tcp_server.h
Fixes https://github.com/diasurgical/devilutionX/issues/132
=> Fix network: creating and joining

SourceX/controls/plrctrls.cpp
This deals with most of the auto-aim parts of #418
- Prioritize targets based on the orientation
- Access and detect all parts of large objects
- Prioritize targets based on the orientation
- Accurate prioritize the closest enemy when using melee only
- Multiple corrections to target selection logic
=> Improve controller autoaim

structs.h
=> declare _SNETVERSIONDATA before use in structs.h

SourceX/controls/plrctrls.h
=> set name of belt_item_type typedef

Source/loadsave.h
=> remove unused SaveItem function signature in loadsave.h

README.md
=> Add note for X64 version

Packaging/OpenDingux/build-rs90.sh, Packaging/OpenDingux/build.sh, README.md
That device only has a 2-inch screen and doesn't have X/Y so I don't
think there is a point in porting to it.
=> OpenDingux: Remove RS90 stuff

SourceX/controls/plrctrls.cpp
=> Fix typos in plrctrls.cpp comments

SourceX/dx.cpp, SourceX/miniwin/ddraw.h, SourceX/miniwin/misc.cpp
- Most refresh rates aliging poorly with integer ms
- Adaptive frame limit for low spec devices
=> Better frame delay precision

SourceX/controls/plrctrls.cpp
Moves struct inside the function.
Groups initial state setup together.
Marks variables that are not mutated as `const`.
=> FindMelee: Minor cleanup

SourceX/controls/game_controls.cpp, SourceX/controls/plrctrls.cpp
Previously it was possible to open the panels, drop items, consume potions, and probably more, while the game was paused over over.
=> Controler enhancments

CMake/retrofw_defs.cmake, Packaging/OpenDingux/build.sh
Fixes load time issues on RG300
https://github.com/glebm/devilutionX/releases/download/0.5.0.300/devilutionx-retrofw.ipk
=> RetroFW: Disable networking

Packaging/OpenDingux/devilutionx-retrofw.man.txt, Packaging/OpenDingux/readme.gcw0.txt, Packaging/switch/readme-switch.md, README.md, SourceX/controls/game_controls.cpp
This is more like the original PSX port, and maps better to devices with
only one set of triggers.
=> [controller] Move healing/mana to L1/R1

Packaging/OpenDingux/devilutionx-retrofw.man.txt, Packaging/OpenDingux/readme.gcw0.txt, Packaging/nix/README.txt, Packaging/pi/README.txt, Packaging/switch/readme.txt, Packaging/windows/README.txt, README.md
Here is a small contribution to clean up some of the language in the `README.md` file. There were some typos, some awkward phrasing, etc. I made corrections in the How To Play, Controller support, and F.A.Q. sections.
=> Fix typos in README.md and tighten up language use

Source/encrypt.cpp, Source/loadsave.cpp, Source/mpqapi.cpp, Source/pack.cpp, Source/sha.cpp, SourceS/miniwin/misc.h, SourceX/miniwin/misc_io.cpp
This should make the game fully functional on big-endian CPUs, paving the way for Amiga, PS3, Xbox 360 support, and let's not forget the original PowerPC Mac that got official support in 1998.
=> Big endian support

Source/capture.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/21
=> Fix screen shots on big-endian

Source/control.cpp
SDL_itoa doesn't exist in Amiga SDL
https://github.com/diasurgical/devilutionX/pull/397#discussion_r371039612
=> Source/control.cpp: snprintf instead of SDL_itoa

.circleci/config.yml
=> Add unit tests and codecoverage

SourceX/DiabloUI/credits.cpp
Fixes #585 though I'm not sure why
=> Fix credit lines pop-in

SourceX/DiabloUI/credits.cpp, SourceX/DiabloUI/diabloui.cpp, SourceX/DiabloUI/mainmenu.cpp, SourceX/DiabloUI/progress.cpp, SourceX/DiabloUI/selconn.cpp, SourceX/DiabloUI/selgame.cpp, SourceX/DiabloUI/selhero.cpp, SourceX/DiabloUI/selok.cpp, SourceX/DiabloUI/selyesno.cpp, SourceX/DiabloUI/title.cpp
=> Fix flashing menu transitions

SourceX/DiabloUI/dialogs.cpp
1. The palette fade level wasn't set, resulting in black on Amiga.
2. Rendering cleared `pal_surface` instead of `GetOutputSurface()`,
resulting in mouse trails.
Also improves performance by only loading the background / palette once.
=> DiabloUI: Fix dialog rendering issues

CMakeLists.txt, SourceT/codec_test.cpp, SourceT/dead_test.cpp, SourceT/diablo_test.cpp, SourceT/doom_test.cpp, SourceT/drlg_l1_test.cpp, SourceT/drlg_l2_test.cpp, SourceT/drlg_l3_test.cpp, SourceT/drlg_l4_test.cpp, SourceT/effects_test.cpp
Add some simple test for a function in each file to take care of creating the files to begin with
=> Create test files

SourceX/controls/game_controls.cpp
This was requested several times and I myself keep trying to use B to close panels.
=> Controls: B button closes currently active panel

Packaging/amiga/prep.sh
Clean up unnecessary CMake flags
Make CPU and FPU choice more maintainable
=> Update prep.sh for Amiga

README.md, docs/mods.md
Updates #616. (leaving the issue open for a while longer, so the list becomes known).
=> readme: add list of known mods

Source/render.cpp
Thanks to @imperialsecond for providing a test case for world_draw_black_tile
=> Fix world_draw_black_tile not taking buffer borders in to account

Source/mpqapi.cpp
Fixes MSVC compatibility, where `__VA_ARGS__` is not implemented correctly.
=> mpqapi: Replace macro with template function

Source/mpqapi.cpp
Testing if this builds on VS 2017
=> mpqapi: Use format macros instead of literals

Source/inv.cpp
As per the information found on this topic: https://www.reddit.com/r/Diablo/comments/4kdh3u/diablo_1_deserves_some_love_introducing/d3eel0k/
=> Fix for item dupe bug.

Source/mpqapi.cpp, Source/mpqapi.h, structs.h
@lenoil98 can you please test this?
Refs #633
=> Ensure _HASH/BLOCKENTRY are 16-bytes and aligned

SourceX/display.cpp
=> Bugfix: allows resize when fullscreen is toggled

Source/.clang-format, SourceS/.clang-format, SourceX/.clang-format
These files are YAML, changes to a more idiomatic YAML syntax
=> Reformat the .clang-format files

CMakeLists.txt, README.md
https://github.com/diasurgical/devilutionX/issues/686
compiling out of order SDLmain
=> MinGW SDLmain fix

.travis.yml
Accidentally broke it by adding the build directory back last-minute in #692
=> .travis.yml: Fix ppc64le script

translations/it.po
First draft of Italian translation
=> Introducing Italian translation

3rdParty/Storm/Source/storm.h, Source/effects.cpp, SourceX/storm/storm.cpp
SFileChunk was not been released.
=> Fix memory leak with audio stream not been released

.travis.yml, CMakeLists.txt
Build is now green. Ref https://travis-ci.org/github/runlevel5/devilutionX/builds/674886620
* Fix deployment condition
* Do not set version for `PROJECT` directive if `VERSION_NUM` is in `untagged-<git-sha>` format - this addresses the issue of cmake configuration
=> Fix Travis CI build

translations/pt-br.po
Translation for brazilian portuguese.
=> PT-BR Translation

SourceX/DiabloUI/dialogs.cpp, SourceX/DiabloUI/mainmenu.cpp, SourceX/DiabloUI/selconn.cpp, SourceX/DiabloUI/selgame.cpp, SourceX/DiabloUI/selhero.cpp, SourceX/DiabloUI/selok.cpp, SourceX/DiabloUI/selyesno.cpp, SourceX/DiabloUI/title.cpp
Vectors were not been freed outside the loops...oops. Copy paste error using the same block each time without checking
=> Correct UI vectors been cleared

CMake/switch/devkita64-libnx.cmake
Fixes #763 (dirty hack, but not much dirtier than before)
=> Fix compilation on Switch

.gitignore
Should I conclude I'm the only vim user out here? ;)
=> Adding vim .swp files to gitignore

SourceX/DiabloUI/art_draw.cpp, SourceX/DiabloUI/button.cpp, SourceX/DiabloUI/button.h, SourceX/DiabloUI/credits.cpp, SourceX/DiabloUI/diabloui.cpp, SourceX/DiabloUI/diabloui.h, SourceX/DiabloUI/dialogs.cpp, SourceX/DiabloUI/dialogs.h, SourceX/DiabloUI/mainmenu.cpp, SourceX/DiabloUI/progress.cpp, SourceX/DiabloUI/scrollbar.h, SourceX/DiabloUI/selconn.cpp, SourceX/DiabloUI/selgame.cpp, SourceX/DiabloUI/selhero.cpp, SourceX/DiabloUI/selhero.h, SourceX/DiabloUI/selok.cpp, SourceX/DiabloUI/selyesno.cpp, SourceX/DiabloUI/text_draw.cpp, SourceX/DiabloUI/title.cpp, SourceX/DiabloUI/ttf_render_wrapped.cpp, SourceX/DiabloUI/ttf_render_wrapped.h, SourceX/DiabloUI/ui_item.h, SourceX/platform/switch/keyboard.cpp, SourceX/platform/switch/keyboard.h
Refactor DiabloUI to dynamic C++03 compatible code
This will help with porting the game to the original Xbox, and also make it easier to implement dynamic resolutions and translations.
=> Ui refactor

Source/gendung.cpp
unnecessary checks eliminated, frequently used values are stored in (constant) locals.
=> simplified theme room creation

CMakeLists.txt, README.md
May be not desirable to merge before the devilutionx ui get update for it too
=> Add hellfire cmake target

Source/diablo.cpp, SourceS/paths.cpp, SourceS/paths.h, SourceX/storm/storm.cpp
Solves https://github.com/diasurgical/devilutionX/issues/927
=> specify path to diablo.ini

Source/scrollrt.cpp, Source/scrollrt.h, SourceX/controls/controller_motion.cpp, SourceX/controls/controller_motion.h, SourceX/controls/game_controls.cpp, SourceX/controls/plrctrls.cpp, SourceX/controls/plrctrls.h, SourceX/miniwin/misc_msg.cpp
* Fixes Right Stick cursor movement
* Fixes cursor flicker when moving the cursor while moving the character
* Fixes START + SELECT menu
* Makes SELECT also close the in-game menu
Fixes #930
=> Fix various controller issues

SourceS/sdl2_to_1_2_backports.h, SourceX/DiabloUI/diabloui.cpp, SourceX/controls/controller.cpp, SourceX/controls/controller.h, SourceX/controls/controller_motion.cpp, SourceX/controls/devices/game_controller.cpp, SourceX/controls/devices/game_controller.h, SourceX/controls/devices/joystick.cpp, SourceX/controls/devices/joystick.h, SourceX/controls/game_controls.cpp, SourceX/display.cpp, SourceX/miniwin/misc_msg.cpp
Handle events from all connected controllers.
A minor issue: START+SELECT combo doesn't work at all on the external controller in batocera.linux.
Fixes #931
=> Multiple controllers support

SourceX/platform/switch/docking.cpp
Renamed in https://github.com/switchbrew/libnx/commit/ccec5bd36c26f9ddd5b6a894f3270d562c8a61ff
=> switch: AppletOperationMode_Docked -> Console

Source/drlg_l3.cpp
=> fix vs2019 release builds

Source/automap.cpp
Added feature to show all players on automap.
=> 	modified:   Source/automap.cpp

Source/monster.cpp, Source/player.cpp, enums.h
There's a lot of duplicated code in movement code for players and monsters (the DoWalk and StartWalk functions), so I merged a bunch of functions. I did this for players and monsters, though I left the StartWalk functions for monsters untouched as those have almost no duplicated code.
I also added comments for parts of the functions (basically, the parts I fully understand).
=> Refactoring of walk functions for players and monsters

Source/player.cpp
no need to check for 'negative' stats from values which come from a static table.
the 'negative' values are not negative anyway...
=> remove unnecessary (and wrong) stat value checks

Source/inv.cpp, Source/player.cpp
This leaves just one bit of Hellfire to deal with!
=> Unify the gold

Source/monster.cpp
fallenfear direction fixed to use the position of the correct monster
+ some minor code cleanup
=> correct fallenfear direction

SourceS/miniwin/misc.h, SourceX/miniwin/misc_msg.cpp
This lets you drink potions/write numbers on chat with numpad if numlock is enabled
=> numpad potions + chat

Source/diablo.cpp, Source/gamemenu.cpp, Source/palette.cpp, Source/quests.cpp, Source/quests.h
Fixes #593
This also fixes the issues with lave/water not animating when behind something that is using transparency
=> Fix loading order of poison water palette

.circleci/config.yml, 3rdParty/StormLib/src/FileStream.cpp, 3rdParty/StormLib/src/StormPort.h, CMakeLists.txt, README.md, SourceX/display.cpp, docs/manual/platforms/vita.md
This updates vita port to the current state of vita scene (retirement of dolcesdk) and libs (support for L2/R2 on Playstation TV gamepads in sdl2)
=> Vita port updates

CMakeLists.txt, Source/items.cpp
=> Correct printing multiple requirements

Source/stores.cpp
=> You can leave pepin now :P

Source/items.cpp
Fixes #441
_iCreateInfo was not cleared for unique items, given the right garbage
value this would cause them to morph. To fix existing save games we
check for CF_UNIQUE before recreating useful or town items.
Thanks to @galaxyhaxz for helping with debugging this issue.
=> [diablo] Fix unique item items morphing on new game

Source/engine.cpp
Follow-up to #964
#1070 may get fixed with this
=> Fix CelBlitLightBlendedSafeTo

Source/engine.cpp, Source/inv.cpp
=> Fix two-handed weapons in inventory

SourceX/soundsample.cpp
Fixes wrong scroll speeds for very long texts
=> fix text scroll speed

Source/automap.cpp, Source/engine.cpp, Source/engine.h, Source/init.cpp, Source/render.cpp, Source/scrollrt.cpp, Source/scrollrt.h
Minor cleanup:
1. Remove `ENG_set_pixel` function.
2. Remove `gpBufStart`.
=> Minor cleanup of the rendering functions

Source/automap.cpp, Source/automap.h, Source/engine.cpp, Source/engine.h, Source/error.cpp, Source/help.cpp, Source/help.h, Source/items.cpp, Source/minitext.cpp, Source/minitext.h, Source/render.cpp, Source/render.h, Source/scrollrt.cpp, Source/stores.cpp, Source/stores.h
Moves `trans_rect` to `engine` as `DrawHalfTransparentRectTo` and makes it operate on `CelOutputBuf`.
=> Enginify `trans_rect`

Source/automap.cpp, Source/control.cpp, Source/control.h, Source/engine.cpp, Source/engine.h, Source/error.cpp, Source/error.h, Source/help.cpp, Source/inv.cpp, Source/inv.h, Source/items.cpp, Source/items.h, Source/plrmsg.cpp, Source/plrmsg.h, Source/quests.cpp, Source/quests.h, Source/scrollrt.cpp, Source/stores.cpp, Source/stores.h, SourceS/thread.h, SourceX/controls/modifier_hints.cpp, SourceX/controls/modifier_hints.h
Migrates various game text printing functions to accept CelOutputBuffer.
=> Pass CelOutputBuffer to game text printing

Source/control.cpp, Source/control.h, Source/doom.cpp, Source/doom.h, Source/engine.cpp, Source/engine.h, Source/gmenu.cpp, Source/gmenu.h, Source/interfac.cpp, Source/inv.cpp, Source/inv.h, Source/scrollrt.cpp, Source/scrollrt.h, Source/stores.cpp
Removes non-buffer versions from engine.h and migrates all remaining engine.h functions to accept a buffer.
=> Migrate all engine.h functions to accept a buffer

Source/inv.cpp
This change introduces automatic equipping of items picked up in the ground when nothing is currently equipped in the corresponding body slots.
This standardizes this behavior for all items instead of only allowing weapons to be auto-equipped.
=> Autoequip all items on pickup

CMakeLists.txt
Missed that doing dolcesdk->vitasdk migration
=> Fix dolce->vitasdk vars

SourceX/DiabloUI/selhero.cpp
Names taken from the Monks of Ivgorod lore
=> PREFILL_PLAYER_NAME for the Monk class

SourceX/DiabloUI/selhero.cpp
The last name in each list was never selected
=> Fix off-by-one in selhero_GenerateName

Source/textdat.cpp
Sentence borrowed from:
https://diablo.fandom.com/wiki/Kael_Rills
=> Add transcription of deadguy

Source/textdat.cpp
Transcriptions borrowed from: https://diablo-evolution.net
TSFX_DRUNK9 and TSFX_DRUNK16 were my attempts.
=> Add transcriptions for the drunk guy

.editorconfig
Comment blocks are auto-generated when inserting /**
=> :hammer: Standardize comment format to Doxygen-style

Source/diablo.cpp, Source/diablo.h, Source/quests.cpp, Source/quests.h
Removes --allquests and makes ini toggle instead.
=> 🚩 Add ini toggle for All Quests for Single Player. Disabled by default.

Source/diablo.cpp, Source/diablo.h, SourceX/dx.cpp
Add toggle for the FPS Limiter.
=> 🚩 Add ini toggle for FPS Limit. Enabled by default.

Source/scrollrt.cpp
The code there previously implicitly relied on `BORDER_LEFT/TOP` being large enough.
=> Don't rely on BORDER_LEFT/TOP in cursor rendering

Source/capture.cpp
Broken by https://github.com/diasurgical/devilutionX/commit/afa3a6bf27ac82cc3e288d5fe24a3613ff87d641
=> Fix screenshotting

SourceX/DiabloUI/selhero.cpp
Barbarian names taken from later Diablo lore.
Bard simply reuses Rogue names.
=> Add default names for Bard and Barbarian

.editorconfig, CMakeLists.txt, Source/init.cpp
1. Installs devilutionx.mpq on Linux.
2. Falls back to finding it in the install location.
=> Install devilutionx.mpq on Linux

CMakeLists.txt, SourceS/miniwin/misc.h, SourceX/sound.cpp, SourceX/storm_sdl_rw.cpp, SourceX/storm_sdl_rw.h
RAM usage (my beefy desktop):
* Town: 176 MiB -> 121 MiB
* Cathedral: 191 MiB -> 138 MiB
Performance: 1170 FPS -> 1150 FPS
=> Stream music instead of loading it all at once

Source/sync.cpp
To improve (a little bit) the code & begin to work on DevilutionX, I remove a strange hexa thing. Not a big deal, compile & test on multiplayer game, still work correctly.
PS: Sorry for bad english, it's not my native language.
=> Rename sync_word_6AA708 to sgnMonsterPriority in Source/sync.cpp for clarity

Source/automap.cpp, Source/capture.cpp, Source/control.cpp, Source/engine.h, Source/gmenu.cpp, Source/help.cpp, Source/interfac.cpp, Source/inv.cpp, Source/items.cpp, Source/minitext.cpp, Source/palette.cpp, Source/plrmsg.cpp, Source/quests.cpp, Source/render.cpp, Source/scrollrt.cpp, Source/stores.cpp, SourceX/dx.cpp, SourceX/qol.cpp, defs.h
GlobalOutputBuffer() now returns a clipped subregion
=> Get rid of SCREEN_X / SCREEN_Y

Source/init.cpp
=> Look for all MPQs in PWD and global share

Packaging/debian/control, Packaging/debian/rules
Now we can use git to obtain commit version and app version
=> Debian package build problem #1218

SourceX/controls/game_controls.cpp
=> Controller: Move stick click handlers out of !game_menu

SourceX/controls/plrctrls.cpp
1. Moves right stick movement handler to run on every frame.
2. Changes hi-res accumulators to `float` to ensure they're always
incremented.
3. Avoid calling `SetCursorPos` within the same SDL tick:
this caused SDL to process all controller events before mouse events
(out-of-order).
=> Fix right stick motion with the FPS limiter off

.circleci/config.yml, CMakeLists.txt
Builds are now working correctly without optimization on Switch
=> :construction_worker: Build Switch test builds as nightly

Source/gmenu.cpp, SourceX/controls/controller.cpp, SourceX/controls/controller.h, SourceX/controls/controller_motion.cpp, SourceX/controls/controller_motion.h, SourceX/controls/devices/game_controller.h, SourceX/controls/devices/joystick.h, SourceX/controls/devices/kbcontroller.cpp, SourceX/controls/devices/kbcontroller.h, SourceX/controls/game_controls.cpp, SourceX/controls/menu_controls.cpp, SourceX/controls/plrctrls.cpp, SourceX/display.cpp
This is another step toward Couch co-op. It's an attempt to make all controller implementations similar, I created a `KeyboardController` class so it could be treated the same as the other implementations.
My C++ skills are a bit rusty so feel free to suggest improvements/modifications.
The next step will be having a single vector handling all the controllers so would be easier to assign each controller to a player.
I am trying to keep the PRs short so it's easier to review.
Comments are welcome!
=> Unify controller implementations

Source/diablo.cpp, Source/diablo.h, Source/items.cpp, Source/pack.h, SourceX/DiabloUI/selgame.cpp, SourceX/controls/controller_motion.cpp, SourceX/controls/game_controls.cpp, SourceX/controls/game_controls.h, SourceX/controls/modifier_hints.cpp, SourceX/controls/touch.cpp, SourceX/display.cpp
This exposes all options clearly in the ini file and makes things a bit
more manageable
Fixes #1238
=> Load and save all ini values the same way

Source/gmenu.cpp, SourceX/controls/controller.cpp, SourceX/controls/controller.h, SourceX/controls/controller_motion.cpp, SourceX/controls/controller_motion.h, SourceX/controls/devices/game_controller.cpp, SourceX/controls/devices/game_controller.h, SourceX/controls/devices/joystick.cpp, SourceX/controls/devices/joystick.h, SourceX/controls/devices/kbcontroller.cpp, SourceX/controls/devices/kbcontroller.h, SourceX/controls/game_controls.cpp, SourceX/controls/menu_controls.cpp, SourceX/controls/plrctrls.cpp, SourceX/display.cpp
This PR reverts all the changes I made for controller related classes because after those changes, left sticks stopped working.
I tested it! The left stick works again.
=> Rollback joystick changes

Source/diablo.cpp, Source/options.h
Typo fixes.
I'm not sure what to type here, so here's a picture showing how I've been improving graphics in my DevilutionX fork:
=> :cow: Minor typo fixes for options struct

SourceX/DiabloUI/selhero.cpp
=> Fix --diablo new hero stats pane with Bard/Barb

Source/diablo.cpp, Source/gamemenu.cpp, Source/gamemenu.h, Source/mainmenu.cpp, Source/multi.cpp, Source/multi.h, Source/options.h, Source/player.cpp, SourceX/DiabloUI/selgame.cpp
This will probably be a popular option in 1.2.0.
Let's give it a self-explanatory name.
=> diablo.ini: Rename "Fast Walk" to "Run in Town"

Source/items.cpp, SourceX/DiabloUI/selhero.cpp
=> Allow Bard starting items in `--diablo`

Source/player.cpp, Source/player.h
It was tracking each type of graphics individually but they're always allocated together.
=> Simplify InitPlrGfx

3rdParty/Storm/Source/storm.h, 3rdParty/StormLib/README, 3rdParty/StormLib/src/.editorconfig, 3rdParty/StormLib/src/FileStream.cpp, 3rdParty/StormLib/src/FileStream.h, 3rdParty/StormLib/src/SBaseCommon.cpp, 3rdParty/StormLib/src/SBaseFileTable.cpp, 3rdParty/StormLib/src/SBaseSubTypes.cpp, 3rdParty/StormLib/src/SCompression.cpp, 3rdParty/StormLib/src/SFileExtractFile.cpp, 3rdParty/StormLib/src/SFileFindFile.cpp, 3rdParty/StormLib/src/SFileGetFileInfo.cpp, 3rdParty/StormLib/src/SFileOpenArchive.cpp, 3rdParty/StormLib/src/SFileOpenFileEx.cpp, 3rdParty/StormLib/src/SFileReadFile.cpp, 3rdParty/StormLib/src/StormCommon.h, 3rdParty/StormLib/src/StormLib.h, 3rdParty/StormLib/src/StormPort.h
Updates StormLib to https://github.com/ladislav-zezula/StormLib/commit/0a9057a09f083eb4791a55eb3d9538cea9822e37
Removes all DevilutionX changes except the `#ifdef FULL` functionality trimming.
This means we lose the Xbox changes but they'll likely need to be adjusted for the new Xbox SDK anyway.
=> StormLib: Update to upstream

Source/inv.cpp, Source/inv.h, Source/items.cpp, Source/items.h, Source/msg.cpp, Source/player.cpp, Source/stores.cpp
This PR cleans some of the inventory logic by reusing existing methods, adding comments, and cleaning up function signatures, and then leverages those changes in stores.cpp to avoid code duplication.
No behavior change should be observed with these changes.
Review per commit is recommended.
=> Inventory and Stores cleanup

.github/workflows/cmake.yml
Taking a crack at https://github.com/diasurgical/devilution/issues/2192
=> Generate Mac build artifact

SourceX/display.cpp
=> Fix audio distortion on Windows (default to winmm)

Source/items.cpp
VS2019 was crying about "using uninitialized variable"
=> small griswold cleanup

SourceX/dvlnet/packet.h
Not sure why this worked on Linux without this stub
=> Fix MSVC build with -DNONET=1

Source/diablo.cpp, Source/pfile.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/1367
=> Fix hellfire save games corrupting the game state

Source/items.cpp
resolves https://github.com/diasurgical/devilutionX/issues/1478
turns out wirt had the same bug so fixed it too + changed the stat ifs into max
+wirt price bug
resolves https://github.com/diasurgical/devilutionX/issues/1480
=> fix vanilla premium items going over 140k

Source/items.cpp
it wasn't being set only for brain and brain doesn't care so whatever
resolves https://github.com/diasurgical/devilutionX/issues/1490
=> fix uninitialized onlygood

Source/loadsave.cpp, Source/loadsave.h, Source/pfile.cpp, Source/pfile.h
I've tested this a bit but it needs to be tested further.
=> Only write to the file once when saving

Source/lighting.cpp, Source/player.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/1493
=> fix gharbad and vision

DiabloUI/diabloui.h, Source/control.cpp, Source/effects.cpp, Source/inv.cpp, Source/items.cpp, Source/loadsave.cpp, Source/missiles.cpp, Source/monster.cpp, Source/objects.cpp, Source/pack.cpp, Source/player.cpp, Source/player.h, Source/quests.cpp, Source/spells.cpp, Source/towners.cpp, Source/trigs.cpp, SourceX/DiabloUI/diabloui.cpp, SourceX/DiabloUI/selhero.cpp, SourceX/controls/plrctrls.cpp, SourceX/miniwin/misc_msg.cpp, test/writehero_test.cpp
This PR converts the plr_class enum to a scoped enumeration and renames both the enum itself as well as its members.
Adjustments are made to ensure every place accessing the enum for indexing into arrays and converting into other values are handled appropriately.
=> 'plr_class' enum cleanup

Source/init.cpp
No longer necessary as of https://github.com/diasurgical/devilutionX/pull/1314
=> init_test_access: Remove platform workarounds

Source/inv.cpp, Source/inv.h
Slightly altered RemoveInvItem() so a mostly identical code snippet could be replaced with a call to that function. Also added some documentation to the function.
=> Minor code cleanup in inv.cpp

CMake/vita_defs.cmake
Refs #1526
Seems to be affected by a similar issue as the Switch and the 3DS: https://github.com/diasurgical/devilutionX/pull/1264
=> Disable streaming audio on the Vita

Source/items.cpp, Source/player.h
This PR moves and centralizes the logic for checking the player's most valuable item (used in store calculations) as a new method in the `PlayerStruct` struct.
=> ♻️ Unify most valuable player item logic on new method

Source/scrollrt.cpp
The original code went out of viewport bounds on every line copy (doesn't crash only because of the buffer padding).
It also did not handle odd viewport dimensions (the original game didn't have to).
This is a new version of the function that handles both and in a more obvious way.
=> Zoom: Fix off-by-1 and handle odd dimensions

Source/init.cpp
The log looks like this:
VERBOSE: MPQ search paths
1. '/home/gleb/devilutionX/build/'
2. '/home/gleb/.local/share/diasurgical/devilution/'
3. '/usr/share/diasurgical/devilutionx/'
4. '/usr/local/share/diasurgical/devilutionx/'
5. ''
VERBOSE: Missing: DIABDAT.MPQ
VERBOSE:   Found: diabdat.mpq in /home/gleb/.local/share/diasurgical/devilution/
VERBOSE: Missing: patch_rt.mpq
VERBOSE: Missing: patch_sh.mpq
VERBOSE:   Found: hellfire.mpq in /home/gleb/.local/share/diasurgical/devilution/
VERBOSE:   Found: hfmonk.mpq in /home/gleb/.local/share/diasurgical/devilution/
VERBOSE: Missing: hfbard.mpq
VERBOSE: Missing: hfbarb.mpq
VERBOSE:   Found: hfmusic.mpq in /home/gleb/.local/share/diasurgical/devilution/
VERBOSE:   Found: hfvoice.mpq in /home/gleb/.local/share/diasurgical/devilution/
VERBOSE: …
=> Log MPQs on load (with --verbose)

Source/stores.cpp
Earlier unique items were displayed blue
=> make unique items display gold in stores

Source/DiabloUI/mainmenu.cpp, Source/DiabloUI/progress.cpp, Source/DiabloUI/selconn.cpp, Source/DiabloUI/selconn.h, Source/DiabloUI/selhero.cpp, Source/DiabloUI/selhero.h, Source/DiabloUI/selyesno.cpp, Source/DiabloUI/selyesno.h, Source/DiabloUI/title.cpp
* Provides clearer separation between what's internal and what isn't.
* Reduces the chances of symbol conflicts (e.g. selhero.cpp had a global named just `title`)
=> 🧹 DiabloUI: Move most code to an anonymous namespace

Source/error.cpp
=> fix typo in Shimmering Shrine

Source/stores.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/1559
=> remove unique item line from shops

Source/control.cpp, Source/effects.cpp, Source/inv.cpp, Source/items.cpp, Source/missiles.cpp, Source/monster.cpp, Source/multi.cpp, Source/palette.cpp, Source/pfile.cpp, Source/player.cpp, Source/scrollrt.cpp, Source/stores.cpp, Source/towners.cpp
Fixes `unused-variable` and `unused-but-set-variable` compiler warnings.
=> 🧹 Cleanup unused variables

Source/monster.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/1589
=> Stops golems from fighting each other

Source/appfat.cpp, Source/automap.cpp, Source/automap.h
The good news, this marks the first point in the process where I need to adjust the clang-tidy config before progressing.
=> 🎨 Apply agreeable part of clang-tidy to appfat and automap

Source/spells.cpp
fix for https://github.com/diasurgical/devilutionX/issues/1611 now with better order of checks
=>  Apply Sorcerer's mana cost reduction bonus only in Hellfire

Packaging/windows/README.txt
Fix discord link, add link to manual (github wiki), mention how to run Hellfire, changelog link
=> Updated readme.txt for Windows release

Source/objects.cpp
Clicking secluded shrine crashed the game 🙄
=> fix secluded crash

Source/DiabloUI/diabloui.cpp, Source/DiabloUI/selhero.cpp, Source/controls/controller_motion.h, Source/controls/game_controls.cpp, Source/controls/game_controls.h, Source/storm/storm_sdl_rw.cpp, Source/storm/storm_svid.cpp, Source/utils/thread.cpp
Commit 191d982 and def7ba5 missed some SDL1 ifdefs.
=> Fix SDL1 Builds

Source/inv.cpp, Source/missiles.cpp, Source/objects.cpp, Source/player.cpp
this is a lot easier to read if you set the diff to ignore white space
=> ♻️ Clean up direction related code

Translations/es.po, Translations/zh_cn.po
Add Spanish translation by @hiperiondev
Add Chinese translation by @muziling
=> Spanish and Chinese

.circleci/config.yml
Works around https://github.com/devkitPro/docker/issues/16
=> 🔨 Switch CI: Fix pkgconfig support

Source/capture.cpp, Source/control.cpp, Source/control.h, Source/engine.cpp, Source/engine.h, Source/gmenu.cpp, Source/interfac.cpp, Source/inv.cpp, Source/items.cpp, Source/minitext.cpp, Source/qol/common.cpp, Source/qol/common.h, Source/render.cpp, Source/render.h, Source/scrollrt.cpp, Source/stores.cpp, Source/stores.h
Fixed CelOutputBuffer::pitch() to be const, and then spread the constant love around.
=> Adding more const&

Source/init.cpp, Source/miniwin/misc_msg.cpp, Source/mpqapi.cpp
=> Fix a few remaining C-style format in Log calls

CMakeLists.txt
Fixes imported target aliasing on CMake versions < 3.18
=> CMake < 3.18 fix

Source/control.cpp, Source/error.cpp, Source/gamemenu.cpp, Source/gmenu.cpp
Use translation for some in game items.
This may need to look at each translation to make sure they fit in the required space.
If we do not want to translate thoses items, we could modify devilutionx.pot template to remove associated string
=> More translation

docs/building.md
See commit messages for rationale.
=> 📝 building.md: A few changes

Source/sound.cpp
Follow-up to #1651
Issue reported by @inukaze in https://github.com/diasurgical/devilutionX/issues/516#issuecomment-827755326
=> 🎶 Loop the music

Source/sound.cpp, Source/utils/soundsample.cpp
Extracts `LoadMusic` and `CleanupMusic` functions.
=> ♻️  Cleanup DISABLE_STREAMING_MUSIC handling

Source/engine.cpp
1. Introduce a couple of constants.
2. Extract a helper function for getting the light table pointer.
=> ♻️  engine.cpp: Minor cleanup in draw functions

Source/dead.cpp, Source/dead.h, Source/missiles.cpp, Source/monster.cpp, Source/monster.h, Source/msg.cpp, Source/player.cpp, test/dead_test.cpp
The only outright intrusive change is the use of an std::array for the animation data.
=> Slight cleanup of dead{.h,.cpp}

3rdParty/SDL_audiolib/CMakeLists.txt
https://github.com/realnc/SDL_audiolib/commit/0fa26cf4e48ed21e696e60ffc88a586ced9fd6fe
=> Update SDL_audiolib to fix mono->stereo conversion

Source/effects.cpp, Source/effects.h, Source/monster.h, Source/sound.cpp, Source/sound.h
There's also a bit of cleanup, but that's beside the point of this commit
=> Use automatic memory management for sound stuff

Source/effects.h, Source/sound.h, Source/sound_stubs.cpp
=> Fix missing <memory> includes

Source/items.cpp
Follow-up to https://github.com/diasurgical/devilutionX/commit/4408ddc127e3bb74e98a740305361b739d88b575, based on https://github.com/diasurgical/devilutionX/commit/e47d80f8df799c0635f6a317f956c9f244efcac4 by @mmaret
=> 🌍 Add some missing /*xgettext:no-c-format*/ annotations

Source/engine.cpp, Source/engine.h
Adds a function to measure the X-coordinates of the solid (non-transparent) bounding box of a CEL.
@qndel @AJenbo Refs #1345
=> Add `MeasureSolidHorizontalBounds`

Translations/it.po
=> Update Italian localization

Source/controls/devices/game_controller.cpp
=> Fix fmt issue with a nullptr controller mapping

CMakeLists.txt, Source/effects.cpp, Source/sound.cpp, Source/sound.h, Source/sound_stubs.cpp, Source/utils/push_aulib_decoder.cpp, Source/utils/soundsample.h
It immediately detects some data races
=> 🔨 CMake: Add ThreadSanitizer via `-DTSAN=ON -DASAN=OFF`

Translations/es.po
Correct and complete Spanish Translation
=> Correct Spanish Translation

Source/items.cpp, Source/items.h, Source/scrollrt.cpp
Also made GetOutlineColor param const, and made gold outline golden again... because the white outline made me sad.
=> Fixed outline drawing for item on cursor to match rest of game

Source/DiabloUI/fonts.cpp, Source/DiabloUI/fonts.h, Source/DiabloUI/text.cpp, Source/DiabloUI/text_draw.cpp, Source/automap.cpp, Source/diablo.cpp, Source/drlg_l1.cpp, Source/drlg_l1.h, Source/drlg_l2.cpp, Source/drlg_l3.cpp, Source/drlg_l4.cpp, Source/engine.cpp, Source/engine.h, Source/gendung.cpp, Source/gendung.h, Source/lighting.cpp, Source/missiles.cpp, Source/monster.cpp, Source/monster.h, Source/objects.cpp, Source/objects.h, Source/palette.cpp, Source/quests.cpp, Source/setmaps.cpp, Source/town.cpp, Source/towners.cpp, Source/towners.h
Tthis gives us the option to specify what type a file should be loaded
as, avoidng the need to case it and does some automatic checks on the
fitness of the data, while making the process simpler.
If no type is given then the type will be set to std::byte which limit
what operations can be performed on the data.
=> ♻️Typed file loading

3rdParty/SDL_audiolib/CMakeLists.txt, Source/sound.cpp
=> 🐞 Update SDL_audiolib

Source/diablo.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/1855
=> Keymapper: fix triggering actions twice

Translations/ru.po
Fix Book of the Blind verse and make more translations.
=> Update RU translation

Translations/it.po
=> 🌐 Fix punctuation in Italian localization

Translations/ru.po
Update previous strings based on critique from Iniquitatis
Changed some "е" to "ё" where it is applicable, not all of them found yet.
Resolve some inconsistencies in characters naming.
Add translations to some quest items, monsters, options, etc.
=> Update RU translation, part 2

Source/utils/file_util.cpp
=> 🐞 Fix Windows UTF-8-to-16 conversion

Source/DiabloUI/text.cpp, Source/cursor.cpp, Source/diablo.cpp, Source/diablo.h, Source/engine/render/text_render.cpp, Source/inv.cpp, Source/multi.cpp, Source/objects.cpp, Source/palette.cpp, Source/towners.cpp, Source/towners.h
This changes one bavious. Previously walking away from the dead guy
would interupt the "Your death shall be reveanged", the interuption
seamed un natural and the code didn't seam to have been specifically
made for this case (TownCtrlMsg).
=> Remove redundant code from towners.cpp

Source/engine/render/cl2_render.cpp
Fixes a regression introduced in #1934
=> 🐞 CL2 outline: Skip color index 0

docs/profiling-linux.md
Add a heap profiling guide for Linux. Follow-up to #1387.
=> 📝 Heap profiling guide on Linux

Source/engine/render/cl2_render.cpp
Fixes a regression introduced in #1940
=> 🐞 CL2 outline: Fix left clip

Source/controls/modifier_hints.cpp
Fixes a regression introduced in #1897
Reverts the layout calculation changes from that PR and simply adapts the previous code to the `DrawString` API.
After reverting the changes, I've adapted the code to the current style and documented the constants.
Issues fixed:
* Wrong hint layout
* Hint text wrapping
* Reversed left and right hints
Fixes #1931. Fixes #1933
=> 🐞 Fix controller modifier hints

Source/control.cpp, Source/engine/render/text_render.cpp, Source/engine/render/text_render.hpp
=> :bug: Implement letter spacing in new font rendering

Source/engine/render/cel_render.cpp, Source/engine/render/cl2_render.cpp
A simpler structure based on the CL2 implementation.
=> 🧹 Clean up CEL outline clipping

Source/engine/render/text_render.cpp, Source/help.cpp, Source/stores.cpp, Source/stores.h
This also corrects some minor alignment issues, like the margin being wider on the right then on the left:
=> ♻️Use common text rendering for store menus

Source/track.cpp
=> Change Multiplier if RunInTown Enabled to Fix Stuttering.

Translations/it.po
Hereby some fixes here and there
Regards
=> 🌐 Italian localization enhancements

Source/player.cpp
=> CheckNewPath: Use correct player for repeated attack check

Source/player.cpp
Alternative to #1980
https://user-images.githubusercontent.com/25415264/118938508-07d6ba80-b94f-11eb-9b11-cbae3eb06383.mp4
</details>
Notes:
- Starts new stand animation for every cast in town
- Relies on stand animation number of frames * (delay+1) > spell animation number of frames
=> Use stand animation for cast in town

Translations/devilutionx.pot, Translations/it.po
As in title.
Thanks for the help text splitting. Very appreciated.
Regards
=> 🌐 Update Italian localization

Source/controls/plrctrls.cpp, Source/dead.cpp, Source/dead.h, Source/engine.cpp, Source/engine.h, Source/inv.cpp, Source/loadsave.cpp, Source/missiles.cpp, Source/monster.cpp, Source/monster.h, Source/msg.cpp, Source/msg.h, Source/objects.cpp, Source/player.cpp, Source/player.h, Source/scrollrt.cpp, Source/scrollrt.h, Source/spells.cpp, Source/sync.cpp, Source/themes.cpp, Source/towners.cpp, test/player_test.cpp
This PR introduces a new addition operator to `Point` instances allowing one to sum them with a `Direction`. This eliminates several manual computations of direction + points, simplifying the code considerably.
=> Direction + Point logic refactoring

Source/controls/plrctrls.cpp, Source/dead.cpp, Source/diablo.cpp, Source/drlg_l3.cpp, Source/lighting.cpp, Source/lighting.h, Source/loadsave.cpp, Source/missiles.cpp, Source/monster.cpp, Source/msg.cpp, Source/multi.cpp, Source/objects.cpp, Source/player.cpp, Source/player.h, Source/portal.cpp
This PR replaces raw int coordinates passed separately to various functions with `Point` instances.
=> Leverage 'Point' in Lighting and Player functions

Source/gmenu.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2062
=> fix pause font and centering

CMakeLists.txt, Source/cursor.cpp, Source/diablo.cpp, Source/engine.cpp, Source/engine/render/cel_render.cpp, Source/items.cpp, Source/items.h, Source/qol/itemlabels.cpp, Source/qol/itemlabels.h, Source/scrollrt.cpp
Rewrite of https://github.com/diasurgical/devilutionX/pull/1345
=> alt highlighting

Source/control.cpp, Source/inv.cpp, Source/items.cpp, Source/items.h, Source/qol/itemlabels.cpp
old vs new
+pixel perfect label targetting
+fixes labels appearing red for no reason
=> margins and tweaks

Source/control.cpp, Source/inv.cpp, Source/items.cpp, Source/items.h, Source/qol/itemlabels.cpp, Source/stores.cpp
This is a bit more readable than using a bool argument.
=> ♻️ Split getTextColor(bool) into 2 functions

Source/control.cpp, Source/control.h, Source/doom.cpp, Source/engine/render/cel_render.cpp, Source/engine/render/cel_render.hpp, Source/engine/render/text_render.cpp, Source/error.cpp, Source/gmenu.cpp, Source/interfac.cpp, Source/inv.cpp, Source/items.cpp, Source/minitext.cpp, Source/quests.cpp, Source/scrollrt.cpp, Source/stores.cpp, Source/utils/stdcompat/cstddef.hpp
Honestly, I'm not good with naming schemes. I tried to get the sense from the previous code coordinates naming and some of the contexts, but I might have understood something wrong, so if you have any suggestions, I'm all "ears¨.
=> Using Point for Control functions

Source/monster.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2085
=> fix line clear after refactor

Source/controls/keymapper.cpp, Source/controls/keymapper.hpp, Source/diablo.cpp
=> Keymapper: fix being able to save/load in multiplayer and actions working while entering a message

Source/inv.cpp, Source/inv.h, Source/msg.cpp
This PR replaces usages of individual X and Y coordinates in `inv.h`/`inv.cpp` functions with the `Point` structure.
=> ♻️ Leverage 'Point' struct on inventory functions

Source/loadsave.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2082
=> fix invalid width2

Source/items.cpp, Source/items.h, Source/monster.cpp, Source/objects.cpp, Source/player.cpp, Source/towners.cpp
This PR replaces usages of individual X and Y coordinates in `items.h`/`items.cpp` functions with the `Point` structure.
=> ♻️ Leverage 'Point' struct on items functions

Source/diablo.cpp, Source/engine/render/automap_render.cpp, Source/options.h
Draw black drop shadow for the automap to improve the visibility.
This could resolve #1659.
=> Draw black drop shadow for automap

Source/controls/plrctrls.cpp, Source/diablo.cpp, Source/engine.h, Source/inv.cpp, Source/missiles.cpp, Source/monster.cpp, Source/msg.cpp, Source/sync.cpp, Source/towners.cpp, Source/utils/stdcompat/abs.h
I've also applied them non-exhaustively in the source code.
=> Point API improvements

Source/scrollrt.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2108
=> fix magic rock highlight

3rdParty/asio/CMakeLists.txt
latest asio changes break mac builds, this is a working asio build + my fix for double windows errors
=> fix mac builds

Translations/ko_KR.po
=> Update Korean localization

docs/building.md, docs/installing.md
[ci skip]
Adds building and installation instructions for Android
Fixes #2167 
Suggestions and corrections welcome, English is not my first language
=> Android building and installation instructions

android-project/build.gradle
Fix https://github.com/diasurgical/devilutionX/issues/2170
=> Android - Replace JCenter repos

Source/control.cpp, Source/engine.cpp, Source/engine.h, Source/interfac.cpp, Source/inv.cpp, Source/utils/sdl_geometry.h
Here it is at 480x480:
Not particularly useful but allows for easier experimentation without crashing.
=> Clip UI draw calls

3rdParty/asio/CMakeLists.txt
This update fixes crashes on Windows when playing TCP and enables 3DS support in ASIO.
=> Update ASIO to diasurgical fork

Source/scrollrt.cpp
1. Only copy the outline if the cursor is an item.
2. Deduplicate clipping math.
=> ♻️ Cleanup `DrawCursor`

Source/dead.cpp, Source/dead.h, Source/missiles.cpp, Source/missiles.h, Source/monster.cpp, Source/monster.h, Source/scrollrt.cpp
Notes:
- Similar to #2043
- Only refactoring. No behavior or animation changes.
- First Step to get ADL for Monsters
=> Leverage `CelSprite` for `MonsterStruct`

Source/control.cpp, Source/control.h, Source/controls/plrctrls.cpp, Source/cursor.cpp, Source/cursor.h, Source/engine.h, Source/hwcursor.cpp, Source/inv.cpp, Source/inv.h, Source/miniwin/misc_msg.cpp
This PR updates inventory-related functions to use `Size` and `Point` when possible in favor of raw values or `std::pair` instances.
=> Leverage 'Size' and 'Point' in inventory-related functions

Source/inv.cpp
=> 🐞 Fix inventory manipulation

Source/inv.cpp, Source/inv.h
This was part of the duplicate item found message
=> :fire: Remove unused code DrawInvMsg

Source/missiles.cpp
About 1/3 of the changes are simply indentation so might want to play with the "ignore white space" option, also i split the most intrusive changes in to a second commit.
=> Cleanup missiles

Source/monster.cpp, Source/multi.cpp, Source/player.cpp, Source/sha.cpp
With this `readability-implicit-bool-conversion` will be fully applied :)
=> Cleanup all implicit bool conversions

CMakeLists.txt, Source/diablo.cpp, Source/drlg_l1.cpp, Source/drlg_l2.cpp, Source/drlg_l3.cpp, Source/drlg_l4.cpp, Source/effects.cpp, Source/engine.cpp, Source/engine.h, Source/engine/random.cpp, Source/engine/random.hpp, Source/gendung.cpp, Source/items.cpp, Source/loadsave.cpp, Source/missiles.cpp, Source/monster.cpp, Source/msg.cpp, Source/multi.cpp, Source/objects.cpp, Source/pack.cpp, Source/palette.cpp, Source/player.cpp, Source/quests.cpp, Source/spells.cpp, Source/stores.cpp, Source/themes.cpp, Source/town.cpp, Source/towners.cpp, test/random_test.cpp
Depends on #2226. Only the second commit is relevant to this request, I opened this as a separate PR to hopefully make it easier to review.
This is in preparation for documenting the existing RNG functions, how they  are used, and providing more suitable alternatives for modders/where repeatable sequences are not necessary.
=> Split RNG functions to dedicated source files

Source/engine/random.cpp, Source/engine/random.hpp
=> Expand comments for vanilla RNG functions

Source/capture.cpp, Source/dx.cpp, Source/dx.h, Source/interfac.cpp, Source/msg.cpp, Source/scrollrt.cpp
This should deal with about half of the cases, there is some changes to indentation so "ignore white space changes" is recommended (no large charges to code)
=> ♻️Clean up variable initialization

Source/automap.cpp, Source/automap.h, Source/control.cpp, Source/controls/modifier_hints.cpp, Source/controls/plrctrls.cpp, Source/cursor.cpp, Source/effects.cpp, Source/engine/actor_position.hpp, Source/engine/displacement.hpp, Source/engine/point.hpp, Source/gendung.h, Source/inv.cpp, Source/items.cpp, Source/loadsave.cpp, Source/missiles.cpp, Source/missiles.h, Source/monster.cpp, Source/objects.cpp, Source/player.cpp, Source/scrollrt.cpp, Source/scrollrt.h, Source/spells.cpp, Source/towners.cpp, test/automap_test.cpp
This PR adds a new `Displacement` abstraction to the codebase for use with deltas/offsets instead of using `Point`s for that purpose.
The name was chosen to avoid any confusion with the native `vector`, but this is conceptually the exact same: a vector with deltas for X and Y displacement.
=> Introduce 'Displacement' abstraction

Source/effects.cpp, Source/items.cpp, Source/lighting.cpp, Source/mpqapi.cpp, Source/msg.cpp
... again half of the remaining, at this rate it will take infinite time to finish.
=> More init clean up

Source/cursor.cpp, Source/engine/render/cel_render.cpp, Source/engine/render/cel_render.hpp, Source/inv.cpp
=> pass item to CelDrawItem

Source/drlg_l1.cpp, Source/drlg_l2.cpp, Source/drlg_l3.cpp, Source/drlg_l4.cpp, Source/engine.h, Source/monster.cpp, Source/objects.cpp
This has a funny side effect - visual studio 2019 doesn't get the "internal compiler error" anymore
Rewrote most of the big ifs using nice new functions from @glebm 
A bunch of bugfix comments
Some small rewrite
=> If cleanup + bugfixes

Source/inv.cpp, Source/inv.h, Source/stores.cpp
https://github.com/diasurgical/devilutionX/pull/2119 without changes to sorting algos
=> inv cleanup

Source/objects.cpp
This might still be a bit rough as I haven't had time to go over it myself yet. After this only monster.cpp remains.
Almost half of the changes are just indentation changes, so ignore white space is advised.
=> Clean up objects var init

Source/monster.cpp
=> Clean up var init in monster.cpp

docs/building.md
=> Fixed typo

Source/control.cpp, Source/control.h, Source/diablo.cpp, Source/loadsave.cpp, Source/player.h, Source/scrollrt.cpp
These can be combined into a pair of functions now but I was gonna do that as a separate PR.
=> Align Life/Mana flask drawing routines

Source/missiles.cpp
Rename methods with "Get"-Prefix and side-effects to "Update"-Prefix.
Follow-up from #2310
=> missiles.cpp: Rename GetMissilePos/MissileVel/VileMIssPos -> UpdateMissilePos/MissileVel/VileMIssPos

Source/objects.cpp
Addresses https://github.com/diasurgical/devilutionX/issues/2278
=> Refactor tear fountain logic; remove GenerateRnd loop

Source/objects.cpp
See https://github.com/diasurgical/devilutionX/issues/2278#issuecomment-874363045
=> Check for negative random values in tear fountain logic

.github/workflows/Linux_x86.yml, .github/workflows/Linux_x86_64_SDL1.yml, .github/workflows/MacOSX.yml, .github/workflows/Windows_x64.yml, .github/workflows/Windows_x86.yml
@glebm does it make sens to cache all of `/build` or should I limit it to `/build/_deps` or something else ?
=> Cache GitHub Action build folders

Source/qol/common.cpp, Source/qol/common.h, Source/qol/xpbar.cpp
Also take translation in to account when printing XP info
=> Fix MSVC C4477 warning

CMakeLists.txt
All but 2 issues have been fixed for w2
=> Bump warning level on MSVC to w3

Source/objects.cpp
Really not sold on the name of the check function or even if it's necessary. Feel free to chop and change.
=> Object by reference for BreakCrux

Source/drlg_l3.cpp, Source/drlg_l4.cpp
I still haven't bought hellfire so can't test this myself using the original save from #2340, hoping someone can check this for me.
=> Restore dropped cases for fence fix and vertical wall checks

Source/loadsave.cpp, Source/objects.cpp, Source/objects.h, Source/setmaps.cpp
This really is a work in progress, trying to document small chunks to the best of my understanding so this can be split into specialised object classes or components in the future.
=> Extract common Book object initialisation logic

Source/monster.cpp
@obligaron GCC told me you might have missed this one
=> Fix MAI_Warlord direction

Source/drlg_l4.cpp
Turns our horizontal/vertical wall functions can modify dungeon so this block of code can execute more than once, moved to a loop
=> fix dungeon

Source/missiles.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2382
=> fix guardian

Source/player.cpp
This tries to clean things up a bit in regards to locating the various targets from the globals, there is still a lot that could be done to clean up the function as a whole, and I'm not even sure if this is the right first step, feedback appreciated.
=> Clean up CheckNewPath target loading

Source/monster.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/2412
=> Fix monster sync on kill

Source/options.cpp
I often change the game speed directly in the diablo.ini
But every time I leave the game my editor reminds me that the file is changed, cause we save the ini at every exit.
With this pr the ini is only saved if there are changes.
Tested:
- No .ini exists, default ini is created
- New entry doesn't exist, ini should be saved with default value
=> Only save diablo.ini if there are changes

Source/automap.cpp
The last missing positioning update? 😉
=> Enable ADL (GetOffsetForWalking) for automap

Source/diablo.cpp, Source/quests.cpp, Source/scrollrt.cpp, Source/scrollrt.h, Source/setmaps.cpp, Source/sha.cpp, Source/sound.cpp, Source/spells.cpp, Source/stores.cpp, Source/sync.cpp
This should be the last of shuffling functions around in the the files :sweat_smile:
=> Move remaning symbols in to anonymous namespaces

Source/monster.cpp
Fixes #2429 
Pumps Zhars courage with some mystical essence (bugfix).
But hero be prepared, I hope you can handle his mighty anger.
=> Fix DirOK for unique monsters

Source/monster.cpp, Source/spells.cpp, Source/sync.cpp
These are the last of the more trivial player by reference clean ups :)
=> Remaning player by refernce clean up

Source/monster.cpp
Fixes #2441
Bug was introduced with #2283
Thanks @Chance4us for finding the correct commit that helped a lot 🙂 
The problem was that a [branch was removed](https://github.com/diasurgical/devilutionX/pull/2283/files?diff=split&w=1#diff-d46585089d315b53630b1035442b3d490d7b422cb05ceee76cf9041de3e39179L4178-L4180), the pr restores it.
=> Fix Counselor always hiding

Source/controls/plrctrls.cpp, Source/cursor.cpp, Source/diablo.cpp, Source/diablo.h, Source/objects.cpp, Source/player.cpp, Source/player.h, Source/track.cpp, Source/track.h
Fixes #2431
Also:
- Track spell targets
- Merge repeat walk in to the new repeat action code
- Avoid time based repeats (use action frame instead)
=> Fix edge cases in mouse action tracking code

Source/scrollrt.cpp
=> ADL GetOffsetForWalking: remove diagonal special

Source/controls/keymapper.cpp, Source/controls/keymapper.hpp, Source/diablo.cpp
Context: https://github.com/diasurgical/devilutionX/pull/1368#issuecomment-869031314
=> Keymapper: remove now useless INI access functions

docs/installing.md
This is needed because of #2453
=> [Documentaion] Update path for copying MPQs on Android

Translations/de.po, Translations/de.pot
I opened this PR so that all people who want to help with the German translation can pitch in. I've just added 3 translations of my own for now, but will add more every now and then when I find the time. For submissions please create PRs to my branch and I will merge them asap.
As all who had contact with the German language know, it's a bit complicated when it comes to genders and the endings of adjectives. This is most noticeable with item prefixes, e.g. if there was a prefix "Small" there would be more than one German translation depending on the item's gender (female: "Kleine", male: "Kleiner", neutral: "Kleines"). At the moment gendered translations are not supported so I'm proposing to use the base form of the adjectives (e.g. "Klein" which is almost always wrong) and marking the …
=> German translation by Baracudus

Source/diablo.cpp, Source/diablo.h
=> Remove unused LastMouseButtonTime

Source/player.cpp
Fixes #2061
Alternative solution #1980 (my favorite 😉)
=> Towncast: Fix character changes direction for casting

android-project/app/build.gradle, android-project/app/src/main/res/values-ko-rKR/strings.xml, android-project/build.gradle, android-project/gradle/wrapper/gradle-wrapper.properties
Good news, the build no longer fails under the latest version of gradle and it's android plugin
=> [android] Update gradle build system

android-project/app/src/main/res/values-ru/strings.xml
As requested, here is russian strings.xml for android.
I tried to keep "shareware" and "spawn" words intact, since none one in modern world knows what "shareware" is, with the word "spawn" things are even worse.
=> Russian strings.xml for android.

Translations/ru.po
100% translation.
Please, to keep the review as simple as possible, suggest only grammatical and mistranslation fixes.
Keep your upper/lower chars changes to other PRs.
=> Russian translation

Source/DiabloUI/selhero.cpp
it didn't work at all before
this makes it work and limits to multi - like in vanilla
=> fix name check and limit to multi

Source/movie.cpp
=> 🐞 Disable hardware cursor during video playback

Source/options.cpp
=> Disable hardware cursor on Android by default

Translations/pt_BR.po
@altiereslima @maristane
I changed "version" back to "versão", despite not speaking Portuguese I feel that "shareware" was probably not the correct translation.
@julealgon would you be willing to give this a quick look (preferably just for things that are completely broken). I aligned the file to create a minimal amount of diff.
=> Update Portuguese translation from @maristane

CMakeLists.txt, Translations/zh_TW.po
Initial commit, I will make further improvements.
=> Initial commit for Traditional Chines translation

3rdParty/asio/CMakeLists.txt
=> Update asio to 1.19.2

Source/control.cpp
1) Open quest panel
2) Open character panel by click level up (+) button
=> Fix attribute up (+) button doesn't work in special case

Source/automap.cpp
I ended up implementing the suggestions I made while testing if they'd actually work, so here we go :D
=> Automap: Scoped enums and wrappers to minimise bitwise operations

Source/automap.cpp
=> Cleanup magic numbers in automap.cpp

CMakeLists.txt, android-project/.gitignore
Note this does not yet include translations with the non-Android ports, if you maintain one of the ports or know how to do so then please feel free to help out :)
=> Build and include translations

Source/monster.cpp
=> move lightsource along with monster when monster does teleport

Translations/zh_CN.po, Translations/zh_TW.po
Minor update for Traditional Chinese in the Credits part, and correct Simplified Chinese.
=> Update Chinese translation

Source/drlg_l1.cpp, Source/drlg_l2.cpp, Source/drlg_l4.cpp, Source/gendung.cpp, Source/gendung.h
=> refactor 3 versions of FindTransparencyValues in: drlg_l1.cpp, drlg_l2.cpp, drlg_l4.cpp

Source/drlg_l1.cpp, Source/drlg_l2.cpp, Source/drlg_l4.cpp, Source/gendung.cpp, Source/gendung.h
- related to #2348 , #2554
- addresses https://github.com/diasurgical/devilutionX/pull/2554#discussion_r685753643
=> fix parameter name and order in FindTransparencyValues

Source/options.cpp
Add some checks and default values just to be safe.
=> Vita locale detection: safety precautions

Source/control.cpp
=> cleanup manual value clamping: control.cpp

Source/cursor.cpp
=> cleanup manual value clamping: cursor.cpp CheckCursMove()

Source/stores.cpp
=> cleanup manual value clamping: stores.cpp

Source/inv.cpp
=> cleanup manual value clamping: inv.cpp

Source/spells.cpp, Source/spells.h
copy/pasted the part from DoHealOther
Resolves https://github.com/diasurgical/devilutionX/issues/2576
int rid would never reach -1 because
=> fix resurrect

Source/monster.cpp
=> cleanup manual value clamping: monster.cpp

Source/stores.cpp
=> cleanup manual value clamping: stores.cpp 2

Source/lighting.cpp
=> cleanup manual value clamping: lighting.cpp

Source/utils/sdl2_to_1_2_backports.cpp
=> cleanup manual value clamping: sdl2_to_1_2_backports.cpp

docs/building.md
It's no longer needed as project has switched to SDL_audiolib
=> Remove SDL_mixer dependency metions

Source/lighting.cpp
=> #2435 Reduce use of globals: VisionList

Source/player.cpp, test/player_test.cpp
CreatePlayer -> CreatePlrItems -> CalcPlrItemVals which recalculates resistances and damage modifier
Same in modify/set stat functions - they call CalcPlrInv and then redo the stuff
=> some useless code removal

Source/monster.cpp
LoadGFX is already a no-op if the stuff has been loaded.
=> monster.cpp: get rid of MissileFileFlag

Source/items.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2107
After this gets merged,
all
```cpp
Items[x]._iSeed = AdvanceRndSeed();
SetRndSeed(Items[x]._iSeed);
```
blocks should be turned into a function
=> fix shop items morphing

Source/towners.cpp
fixes https://github.com/diasurgical/devilutionX/issues/2590
=> Make farmer not wondering about explosion forever 

Source/towners.cpp
fixes https://github.com/diasurgical/devilutionX/issues/2578
=> No More Tears

Source/capture.cpp
In C++17 you can return uncopyable and unmoveable stuff.
Let's see if it builds :)
=> Make CaptureFile return ofstream

Source/DiabloUI/diabloui.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/2629
=> fix menu click offset

Source/cursor.cpp, Source/missiles.cpp
- related to #2435 
- part 1 of refactor Missiles
- remove global variable `Missiles` in function `UpdateMissileVelocity`
=> 2435 refactor Missiles part 1

Source/msg.cpp
this is so dumb
Fixes https://github.com/diasurgical/devilutionX/issues/2507
=> fix incorrect golem removal

Source/drlg_l1.cpp, Source/drlg_l2.cpp, Source/drlg_l3.cpp, Source/drlg_l4.cpp, Source/items.cpp, Source/monster.cpp, Source/objects.cpp, Source/quests.cpp, Source/quests.h, Source/themes.cpp
this pull request is related to below feedback 
@ephphatha https://github.com/diasurgical/devilutionX/pull/2602#issuecomment-899023688
@AJenbo https://github.com/diasurgical/devilutionX/pull/2602#issuecomment-899108179
=> 2602 add IsAvailable in QuestStruct and remove QuestStatus()

Source/controls/plrctrls.cpp, Source/missiles.cpp, Source/missiles.h, Source/monster.cpp, Source/msg.cpp, Source/portal.cpp
related to #2435 
Based on @AJenbo comment in https://github.com/diasurgical/devilutionX/pull/2634#issuecomment-901493966
```
UpdateMissilePos()
SetMissAnim()
SetMissDir()
SetMissAnim()
MissilesFoundTarget()
UpdateVileMissPos()
AddLightningWall()
```
=> 2435 refactor missiles part 2

android-project/app/src/main/res/values-bg/strings.xml
Fix text and add optional hellfire requirements to text.
=> Fix some expressions and inconsistencies

Source/control.cpp, Source/debug.cpp, Source/debug.h, Source/diablo.cpp, Source/diablo.h, Source/gendung.cpp, Source/items.cpp, Source/missiles.cpp, Source/monster.cpp, Source/mpqapi.cpp, Source/multi.cpp, Source/player.cpp, Source/quests.cpp, Source/scrollrt.cpp, Source/spells.cpp, Source/trigs.cpp
- Clean up god mode (the debug command was actually switching god+tools)
- Fix changing to regular levels when in a quest map
- Add command for loading quest maps
- Remove arguments that are now available as commands
- Remove chat buttons, it was largely hardcoded to specific keys and not easy to understand or remember
=> Debugmapcmd

Source/monster.cpp, Source/player.cpp
=> 2435 refactor missiles part 4

Source/items.cpp, Source/loadsave.cpp
- related to #2435
- this pull request simply put `auto &item = Items[...omit]` at the top of functions so it is easier to refactor in subsequent pull requests.
=> 2435 refactor global variable Items part 1

Source/debug.cpp
Without this, gold appeared red
=> stop gold from displaying red

Source/debug.cpp, Source/items.cpp, Source/items.h
Refill - refills hp/mana
dropitem - tries to find an item that matches the name
dropunique - tries to find a unique item that matches the name
=> New debug commands

Translations/es.po
A lot of comments about translation (missing contexts or unknown correct translations)
=> Spanish translation 56% corrected. All non corrected marked for revision.

Source/debug.cpp, Source/diablo.cpp
visit - let you visit someone in town
exit - exits the game
arrow - change arrow effect
=> More debug commands

Source/towners.cpp
See [comment](https://github.com/diasurgical/devilutionX/pull/2613#issuecomment-901532997)
https://user-images.githubusercontent.com/25415264/130349200-ac2274dd-23fd-49d7-b5f7-cb7b7b592ecd.mp4
https://user-images.githubusercontent.com/25415264/130349211-4339971b-cc49-4bf0-89fe-47e05ae9f7db.mp4
https://user-images.githubusercontent.com/25415264/130349219-49120b49-3d7f-4b52-886e-79b57de1243e.mp4
=> Remember last frame when animation is changed for towners (girl & cow farmer)

Source/towners.cpp
=> fix hellfire/cows crash

Source/missiles.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2683
=> fix missiles without dmg

Source/monster.cpp
also moved duplicated reflect code into a function
=> share info about expiring reflect

Translations/es.po
=> Spanish translation: Finished first pass translation. 

doxygen.config
- remove MAX_DOT_GRAPH_DEPTH in doxygen.config
- include the subfolders in Source (work in progress)
@AJenbo says
> we can now increase the nodes in the graphics since we split up all.h
> can just remove it now
=> update doxygen configuration

Translations/bg.po
Remove fuzzy stuff + fixes. Used the latest available pot file to update the translation, but seems the last version seems to be based on a more recent version that isn't available.
=> Update Bulgarian translation

Source/missiles.cpp
Ok I think I'm ready to move on from missiles.cpp now :D
Runes cannot be learned so will never use mana, MissilesFoundTarget might have been used in some dead code, but now AddRune is the only consumer and merging the two makes more sens as some of the input is always the same.
=> Clean up AddRune

Translations/ko_KR.po
=> #2071 Korean translation part 1

Translations/ko_KR.po
=> #2071 Korean translation part 2

Source/inv.cpp, Source/inv.h, Source/inv_iterators.hpp, Source/objects.cpp
Implements external iterators for player items.
/cc @mewmew
=> External iterators for player items

Translations/ko_KR.po
=> #2071 Korean translation part 3

Source/diablo.cpp
With this you can add debug commands to the command line.
This commands will be executed when you start/load the first game.
Notes:
- `+` signal the start of a debug command in command line. It ends when we find a command that starts with a `-` in the command lines.
- No command or command parameter is allowed to start with `-`, cause this would signal a normal command line argument.
- The commands are only executed for the first started/loaded game, cause some debug commands are global toggles (like god mode).
- The commands are executed at the second game tick, cause the first game tick is special (for example the `changelevel` command would generate level with errors).
=> Allow debug commands from command line (with + prefix)

Source/engine/demomode.cpp
See [comment](https://github.com/diasurgical/devilutionX/issues/2733#issuecomment-907831791).
This could be done better, but before #2733 isn't decided. I wouldn't take that extra step. 😉
=> Demo: Fix rendering jittering

Source/panels/charpanel.cpp
Since I was drawing all static stuff into the panel itself, coords there don't need an offset like the panel itself. All labels were off on resolutions different than 640x480.
=> fix panel at higher resolutions

Source/town.cpp, Source/town.h
Moved the documentation comments from town.cpp to town.h .
Please review it and give your valuable feedback.
=> Move documentation from implementations to declarations #2735.

Translations/es.po
compared against Italian translation
=> Spanish translation: some corrections

android-project/app/src/main/AndroidManifest.xml
This is still broken in Android 7.1.1+
=> [Android] Fix input not being in view for 5.1 - 7.0

Source/monster.cpp
the code does
```cpp
if (RandomWalk(i, Players[i]._pdir))
return;
```
so check for < MAXMONSTERS is not enough
=> golem assert fix

Source/missiles.cpp
- Player cannot TP to current location
- Cannot teleport to any object location (including doors)
- Can teleport to void locations
- Cannot teleport to dead monsters
=> :bug: Fix teleport not working in all locations

Source/missiles.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2833
=> fix golem spawning on top of player

Source/scrollrt.cpp, Source/scrollrt.h
Fuctional doc of scrollrt.cpp moved to scrollrt.h
=> Move documentation from implementations to declarations #2735

Source/debug.cpp, Source/lighting.cpp, Source/lighting.h, Source/missiles.cpp, test/lighting_test.cpp
Improved version of #2799 
New pr cause @qndel doesn't want o cherry pick 😜 
Allows to spawn a monster per debug command (for example `spawn fall` or `spawn 4 skeleton`.
<details><summary>Sample</summary>
https://user-images.githubusercontent.com/25415264/132944116-3f39968a-d911-45fb-8f39-0edb5bdfec2d.mp4
</details>
=> Debug spawn command

Source/quests.cpp, Source/quests.h
Replaces some low-level X/Y offset checks for quest entrance check with some higher level abstractions.
=> Quest entrance check refactoring

Source/debug.cpp, Source/debug.h, Source/scrollrt.cpp
lets you display values from many internal arrays (works best combined with grid)
For example dMonster in action
=> tiledata debug command

Source/pack.cpp, Source/pack.h
Functional documentation  of pack.cpp moved to pack.h
=> Move documentation from implementations to declarations.

Source/mpqapi.cpp, Source/options.cpp, Source/utils/file_util.cpp, Source/utils/file_util.h
It saves one memory allocation.
=> Make CreateFileStream return optional, rather than unique_ptr

Source/engine/render/text_render.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/2848
=> fix chat line wrapping

Source/debug.cpp, Source/debug.h, Source/scrollrt.cpp
Small refactoring
- Less code in scrollrt.cpp and more in debug.cpp
- Combine tiledata and coords/cursorcoords in one command
=> Refactore debug command tiledata

Source/control.cpp
Just a minor code cleanup pointed out by @AJenbo in his review of the virtual gamepad PR. See https://github.com/diasurgical/devilutionX/pull/2599#discussion_r707812496
=> Merge logic from InitControlPan() and ClearPanBtn()

Source/objects.cpp
Fixes #1352
Similar [code](https://github.com/diasurgical/devilutionX/blob/master/Source/objects.cpp#L4224) exists for cruxes in Skeleton King's Lair.
=> Fix opening Diablos chamber with only one lever

Source/control.cpp, Source/control.h, Source/miniwin/misc_msg.cpp
Fixes #1195
Works only with SDL2.
=> Use SDL Textinput for ingame chat

Source/inv.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2920
=> fix wrong armor display in multiplayer

Source/inv.cpp
Merged the previous one a bit too fast since it was a oneliner and "fixed" the issue, haven't realized it's the wrong variable 😅 
https://github.com/diasurgical/devilutionX/pull/2922
=> proper fix for multiplayer item sync

Translations/fr.po
Some fuzzy translation are still remaining after this
=> Update french translation

Source/control.cpp, Source/controls/plrctrls.cpp, Source/inv.cpp, Source/inv_iterators.hpp, Source/items.cpp, Source/items.h, Source/player.cpp
=> Refactor: Use item iterators for scroll checks

Source/debug.cpp, Source/items.cpp, Source/items.h
Makes all uniques droppable with "dropu" command in singleplayer. Optimizes for speed.
=> Drop unique tweak

Translations/ko_KR.po
=> #2071 Korean translation part 4

Source/control.cpp
=> Better text alignment in spell book

Source/inv.cpp
Fixes #856
Initially I didn't want to fix this, cause it's a good first issue for newcomers. But someone added it to 1.3.0 milestone and time is running out. So now one less issue. 😁
=> Draw belt item number for unusable scrolls

Translations/ko_KR.po
=> #2071 Korean translation part 5

Translations/ko_KR.po
Translated 32 vocabs into Korean
=> Korean translation 01

Translations/ko_KR.po
- part of #2071
- also contains @british-choi 's translation suggestion https://github.com/diasurgical/devilutionX/issues/2071#issuecomment-927532627
=> #2071 Korean translation part 6

android-project/app/src/main/res/values-pl/strings.xml
Simple translation for android strings.
=> Polish strings translation for Android

Translations/zh_CN.po
Update template from source code.
Fix some {:s} and {:d} format.
Fix missing translation for demo record.
Review most of the MapObj, Help, UI, Item and Spell locale.
Fix a Combat hotkey tip in Help. ($M to $C)
Change some block to half character.
Import D3CN locale for monster.
Fix some NPC name.
It is time to focus on proofreading the NPC dialog. 😉
=> Update zhCN translations.

Source/control.cpp
Hi there, I changed the quick spell book to be dynamic.
I tried to use the colors as close as possible.
~~The translations are not actually working, I probably missed something.~~
Closes #2972
=> Makes spell highlight translatable

Source/player.cpp
Quater damage is a negative value and so would be dealing damage based on garbage values...
=> Fix quater damage in Hellfire

Source/automap.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/3000
=> fix jumping arrow

Source/engine/render/text_render.cpp
=> WordWrapString: Also break on `，`  U+FF0C (FULLWIDTH COMMA)

Translations/pl.po
First part of translation. Lets review it together and see if we can make it better. 
Calling @qndel for help.
Please add others reviewers if you know they can contribute.
=> Polish translation update part1

3rdParty/SDL_image/CMakeLists.txt, Brewfile, android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java, docs/installing.md
There is still one left [here](https://github.com/diasurgical/devilutionX/blob/master/Packaging/windows/mingw-prep.sh#L4), but last I tried to remove that one the linker was unable to locate zlip :shrug:
=> Delete most remaning references to SDL_ttf

Translations/ru.po
This is an update that unfuzzes all translation strings and makes them available in-game, while fixing some bad translations, and shortening some words to fit UI
PR is also made to have a place for discussion, that's why it is currently in draft
Comments and commits to fork are welcome!
=> Update Russian translation

Translations/fr.po
A few corrections, mostly added quests texts
=> Added some translation to French

Source/monster.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/3025
=> fix anvil monsters placement

Source/scrollrt.cpp
The check if the object position is offset is not strictly necessary as a displacement of {0, 0} remains the same after the world/screen transform.
(Splitting this out from #3324 to make that PR a little more focused)
=> Refactor DrawObject to avoid repeated Objects lookup

docs/installing.md
Also update devilutionx.mpq, and mention fonts.mpq and pl.mpq
=> Improve Android install instructions

Source/controls/plrctrls.cpp, Source/diablo.cpp, Source/objects.cpp, Source/objects.h
While it does reference a global configuration option it's mainly concerned with the properties of the object itself, so makes sense (at least I think it does :D) to be a member of the object class.
=> Move objectIsDisabled to a member function

Source/inv.cpp, Source/inv_iterators.hpp, Source/items.cpp, Source/objects.cpp, Source/player.cpp
=> Refactor: Use item iterators in 7 more places

Source/control.cpp, Source/objects.cpp, Source/objects.h
A couple of functions where raw indexes were not necessary (main aim was putting that monster variable declaration back  into the correct scope... but when in rome).
=> Take Object by reference when updating the info box on hover

Translations/ru.po
Before change - text on the border and cut off
=> shorten russian game speed translation

Translations/ko_KR.po
=> Update Korean Translation

Source/objects.cpp
If this has any side effects I'll be amazed 😂
=> Remove no-op assignment

Packaging/OpenDingux/package-opk.sh
Please also cherry-pick to master
=> OpenDingux/package-opk.sh: Fix devilutionx.mpq path

Source/engine/render/cel_render.cpp
Generates same results for all items as the old one = I think it works ;)
=> shorter & better MeasureSolidHorizontalBounds

Translations/sv.po
There were a couple translations already, but most seemed out of date or referred to the wrong thing entirely, so I changed them.
=> translated most lines except dialogue to swedish

Source/controls/plrctrls.cpp
=> Fix build error in plrctrl.cpp

Translations/zh_CN.po
Translate new text
Fix some monster name
Fix Tristram -> 崔斯特姆
Review quest dialog text for "The Butcher" and "Lachdanan"
=> Update zhCN translation

Source/sound.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/3402
=> fix sound crashes

.circleci/config.yml, .github/workflows/Linux_x86.yml, .github/workflows/Linux_x86_64_SDL1.yml, docs/manual/platforms/n3ds.md, docs/manual/platforms/switch.md
Since we no longer use SDL-TTF. I have removed all the references and dependencies to ttf
=> remove ttf references and dependencies

Source/effects.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/3400
=> fix hellfire shareware monk

Source/missiles.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/3166
At least I hope so
=> dont allow casting berserk on berserked monster

Source/debug.cpp, Source/debug.h, Source/scrollrt.cpp
=> add megatiles to tiledata

Source/msg.cpp, Source/msg.h, Source/sync.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/3109
Resolves https://github.com/diasurgical/devilutionX/issues/3110
Resolves https://github.com/diasurgical/devilutionX/issues/3111
Resolves https://github.com/diasurgical/devilutionX/issues/3115
I'm not sure if all this code is necessary, but together it resolves all these issues 🤷
=> sync monster mWhoHit / monster hitpoints on entering/leaving level

Source/sound.cpp
=> Open music assets with threadsafe=true

Source/engine/render/text_render.cpp
Before:
After:
Also removes a redundant copy of the input string.
Fixes #3420
=> Don't line-break in the middle of a punct sequence

Packaging/OpenDingux/build.sh, Packaging/OpenDingux/lepus-manual.txt, Source/utils/sdl_compat.h
=> OpenDingux: Minor fixes

Source/controls/plrctrls.cpp, Source/cursor.cpp, Source/debug.cpp, Source/inv.cpp, Source/items.cpp, Source/missiles.cpp, Source/scrollrt.cpp
Been wanting to do this for a while now :)
=> Clean up id normalization

.github/workflows/Android.yml, .github/workflows/Linux_x86.yml, .github/workflows/Linux_x86_64_SDL1.yml, .github/workflows/Windows_x64.yml, .github/workflows/Windows_x86.yml, .github/workflows/opendingux_release.yml, .github/workflows/retrofw_release.yml
1. Adds act support. https://github.com/nektos/act
2. Fixes OpenDingux workflows
OpenDingux workflows tested with act:
act -W .github/workflows/retrofw_release.yml -j retrofw
=> GitHub workflow fixes

docs/manual/platforms/n3ds.md
=> Update platform manual for 3DS

Source/engine/render/text_render.cpp, Source/minitext.cpp
=> Text rendering/wrapping fixes

Translations/uk.po
Continuing my Ukrainian TL when time permits, reviews welcome
Known issues:
* On debug builds, going to a new game or "Support" menu hits an assert
TL notes:
* I am fully committing to TL "Spell" as "Чари"
* IMO, "Rogue" should stay as "Пройдисвітка" because of DnD class origins
=> Ukrainian: TL support strings and some status bar msg

Source/monster.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/3451
I guess it'd be nice to clean berserk to not reuse golem flag like this, what a mess lol
=> make berserked monsters fight each other

Source/diablo.cpp
=> do not allow quickload while talking to towner

Translations/zh_CN.po
Fix missing store npc name.
Fix npc name Adria -> "艾德莉亚"
Fix some item prefix and unique item name.(base on newest D2R)
=> Update zhCN translations

android-project/app/src/main/AndroidManifest.xml, android-project/app/src/main/res/xml/backup_descriptor.xml
Google allows for a max of 25MB so leave out all the MPQ files
=> [Android] Define file to back up

Translations/ja.po
Adjust translation wording.
(Mainly Farmer, Little Girl, Complete Nut, Defiler)
Changed command line options back to English.
(I think you can still understand it in English)
Fixed minor mistranslations.
=> Update Japanese translations

Source/items.h, Source/msg.cpp
Quick and dirty fix for #3510. I was gonna look at this more if #2932 got merged as this is a bit of an odd use case of the dItems array, this PR is not as clean as it could be.
=> Check the item at the target position before searching all items

Translations/uk.po
Full TL of Credits screen!
Contains punctuation fixes for Help screen
Changed "Скасувати" to "Відміна" since it's shorter
=> UK TL: Credits

Source/DiabloUI/selgame.cpp, Source/DiabloUI/selhero.cpp
=> Increase some DiabloUI buffer sizes

Source/stores.cpp
=> Fix the divider line position in the help menu

Source/player.cpp
Fixes #1525
Thanks to @burned42 and @EduardBaer
=> Monk blocking with staff should cause staff to lose durability

Source/items.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/3565
=> fix displaying unique stats

Translations/ja.po, Translations/ko_KR.po, Translations/zh_CN.po, Translations/zh_TW.po
=> Update CJK translations from source

Translations/uk.po
@SourceCodeDeleted please review and provide help.
I have marked TLs where I need help as `#, fuzzy`
Best reviewed per commit, starting for 2nd one.
Most of the item stuff except for Uniques
TL decisions:
- Club - Палиця
- Cleaver - Сікач
- Ring - Перстень
- Potion - Зілля
- Great - Величезн(ий/а)
- Large - Велик(ий/а)
Need to file issues:
- Gendering for item prefixes: https://github.com/diasurgical/devilutionX/issues/3563
- Using `drop` debug command results in xstring assert: https://github.com/diasurgical/devilutionX/issues/3562
=> UK TL: Items

Source/control.cpp, Translations/ja.po, Translations/zh_CN.po
Previous | English | Chinese | Japanese
------|------|------|------
Fixes #3547
/cc @bubio @tytannia
=> Improved spell book layout (CJK-compatible)

.github/workflows/opendingux_release.yml, .github/workflows/retrofw_release.yml
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
=> GitHub CI: Allow triggering release actions manually

Source/panels/spell_list.cpp
This makes hotkeys always show up in the spell bar, as well as for the selected spell. It mimics DIablo 2.
We could also add an INI option for this.
=> Always draw hotkeys

Translations/ko_KR.po
=> Update Korean Traslation

Source/options.h
=> options.h fix reorder warnings

Source/engine/render/text_render.cpp, Source/engine/render/text_render.hpp
A way to color parts of the string differently while keeping the color information outside of the string contents.
This is an alternative to #3546.
Example:
```c++
DrawStringWithColors(out, "Test {1} {0}", {{"blue", UiFlags::ColorBlue}, {"red", UiFlags::ColorRed}}, ...);
```
=> Add `DrawStringWithColors`

Source/control.h, Source/diablo.cpp, Source/miniwin/misc_msg.cpp, Source/panels/spell_list.hpp
=> Move DoSpeedBook to the right header

Source/DiabloUI/ui_flags.hpp, Source/DiabloUI/ui_item.h, Source/control.cpp, Source/control.h, Source/controls/modifier_hints.cpp, Source/controls/plrctrls.cpp, Source/controls/touch/renderers.cpp, Source/debug.cpp, Source/engine/render/text_render.cpp, Source/engine/render/text_render.hpp, Source/error.cpp, Source/gmenu.cpp, Source/help.cpp, Source/inv.cpp, Source/items.cpp, Source/items.h, Source/minitext.cpp, Source/miniwin/misc_msg.cpp, Source/objects.cpp, Source/options.cpp, Source/panels/charpanel.cpp, Source/panels/spell_book.cpp, Source/panels/spell_list.cpp, Source/panels/ui_panels.hpp, Source/plrmsg.cpp, Source/quests.cpp, Source/scrollrt.cpp, Source/stores.h, Source/utils/enum_traits.h, Source/utils/language.cpp
Assortment of fixes for #3608 
/cc @obligaron
=> DrawStringWithColors fixes

Source/inv.cpp, Source/monster.cpp, Source/objects.cpp, Source/options.cpp, Source/options.h, Source/qol/autopickup.cpp, Source/qol/monhealthbar.cpp, Source/quests.cpp, Source/stores.cpp
Add all (boolean) options in `Game` category to Settingsmenu / convert to `OptionEntry`.
=> Add all (boolean) Game Settings to Settingsmenu

Source/diablo.cpp, Source/dx.cpp, Source/engine.cpp, Source/engine/demomode.cpp, Source/engine/render/cel_render.cpp, Source/engine/render/dun_render.cpp, Source/options.cpp, Source/options.h, Source/palette.cpp
Add more options to `Graphic` category that don't require renderer/window recreation.
=> Add some Graphic Settings to Settingsmenu

Source/DiabloUI/selhero.cpp, Source/help.cpp
=> Fix a couple of build warnings

Source/options.cpp, Source/options.h
See [comment](https://github.com/diasurgical/devilutionX/pull/3634#discussion_r757872587).
=> Move OptionEntry::operator*() to header

Source/plrmsg.cpp
=> Fix chat messages overlap in CJK

3rdParty/SDL2/CMakeLists.txt, android-project/app/build.gradle, android-project/app/src/main/AndroidManifest.xml, android-project/app/src/main/res/xml/backup_rules.xml
@tsunamistate I think the issue you where hitting was probably with the deprecated migration code which has now been removed.
=> Upgrade Android builds to SDK 31

docs/installing.md
FYI, the QR code points to https://github.com/diasurgical/devilutionX/releases/latest/download/devilutionx-3ds.cia so it shouldn't need to be updated for new releases unless we change the name of the file.
=> Add QR code for 3DS remote install

Source/options.cpp
Lets see if this builds on CI...
=> Try load the translation in the users language on windows

Source/controls/plrctrls.cpp, Source/controls/plrctrls.h, Source/diablo.cpp, Source/options.cpp, Source/options.h, Source/player.cpp, Source/player.h
This patch lets you cast spells with the push of a hotkey, rather than swapping out the readied spell.
Something similar has recently been introduced to D2R.
=> Quick cast

Source/options.cpp
- Fixed that  "Define what language to use in game." is not included in the translation.
=> Add text to translate

Translations/cs.po
Updated Czech translation with story lines (used already existing translations from Adam Rambousek [Diablo 1] and René "Raptor" Spišák [Hellfire])
=> Updated Czech translation

Source/DiabloUI/settingsmenu.cpp
For option entries with type `OptionEntryType::List` we now show a browsing with all selected values for this option.
This avoids to reset the UI every time we browse to the desired value. When adding resolution selection this is especially important (not part of this pr).
Sample Video:
https://user-images.githubusercontent.com/25415264/144754148-9e5308ca-1084-4164-8cfc-2d764f306e03.mp4
=> Settingsmenu: Add list browsing

.github/workflows/opendingux_release.yml, .github/workflows/retrofw_release.yml, .github/workflows/src_dist_release.yml
Not sure if this will works but would be nice
Uses https://github.com/ncipollo/release-action
=> GitHub CI: Automatically add files to the release

CMakeLists.txt, Source/engine/assets.cpp, Source/init.cpp
alternative to #3674
I have no way of testing this, so it may require further tweaking
=> macOS/iOS: Add resources to the bundle

Source/options.h
See related [comment](https://github.com/diasurgical/devilutionX/pull/3688#discussion_r763371204).
=> options.h: remove redundant virtual

.github/workflows/iOS.yml
=> Parallel build of iOS port

Source/DiabloUI/selgame.cpp
Fixes #3567
https://user-images.githubusercontent.com/25415264/145669856-99a7ac4d-effa-4275-a9fc-20c2948cb4f1.mp4
=> Add scrollbar to selgame

Source/DiabloUI/diabloui.cpp
Fixes #3723
@glebm please take a look 🙂
=> Fix page down/up don't wrap in settingsmenu

Source/DiabloUI/diabloui.cpp, Source/controls/menu_controls.cpp
1.  Handle mouse back button in menus.
2.  Handle mouse wheel in SDL 1.2.
=> DiabloUI: Mouse handling improvements

Translations/sv.po
=> Update Swedish Translation.

Source/monster.cpp
Fixes #3527 (hopefully)
I couldn't reproduce the issue locally. So this pr is only a educated guess.
In `M_GetKnockback`:
`DirOk` previous checked if the dir + `monster.position.tile` is free.
When the check is successful the monster will be set on dir + `monster.position.old` (see end of `M_GetKnockback` and `StartMonsterGotHit`).
This can only differ if the monster is currently moving. In #3527 the monster was perhaps retreating.
This pr fixes changes the check to dir + `monster.position.old` is free.
Also we don't forbid knock back if the monster is part of a pack.
=> Fix Knockback checks wrong position when a monster is moving

3rdParty/SDL_image/CMakeLists.txt, CMake/Dependencies.cmake, CMake/functions/dependency_options.cmake
Follow-up to https://github.com/diasurgical/devilutionX/commit/75222ccef804a2e1e1d43eb6ed8b60ba93c03cc5
=> CMake: Remove upgrade code

Source/diablo.cpp, Source/monster.cpp, Source/monster.h
=> Initialize golems before objects

docs/building.md
- Correct the path of CMAKE_TOOLCHAIN_FILE to the correct one.
=> Update iOS Build Descriptions.

docs/building.md
=> Fixed iOS build description

Source/options.cpp, Source/options.h, Source/qol/autopickup.cpp, Source/sound.cpp, Source/storm/storm_svid.cpp, Source/utils/soundsample.cpp
Notes:
- Add new simple int-list based `OptionEntryInt`.
- If a value in the `ini` is specified that is not in the list, it will be added dynamically to the list.
- Added Audio options
- Added Pickup options
@glebm and @joewis ptal, especially if the default list entries are good. Thanks in advance. 🙂
=> Settings: Add Audio & Pickup

Source/towners.cpp
I was playing around with the cow facings and noticed that the sprites for ordinal facing cows are aligned along the edge of the tiles vanilla considers they occupy. I think this might've been discussed in a prior issue/PR but I couldn't find it from a search.
While it's a minor change compared to vanilla I reckon getting rid of the CowOffsets array is worthwhile since it means we can treat cows the same no matter what direction they're facing.
This also resolves a slight visual inconsistency where the player can clip through the cow sprite by walking north/south past an ordinal-facing cow.
Vanilla:
Proposed change:
Loading a save means the player can walk off the newly occupied tile but will not be able to walk back onto it, beyond that there's no impact.
=> Remove CowOffsets, always treat cows as 4 tile sprites

Source/utils/paths.cpp, Source/utils/paths.h
=> paths.cpp: Remove `AppPath`

Source/utils/display.cpp
This works around a bug in DX9 on Win11.
=> Prefer DX11 renderer if running on windows with vsync active

CMakeLists.txt, docs/building.md
Also do not build tests when cross-compiling
=> building.md: Add googletest

Source/DiabloUI/settingsmenu.cpp
=> settingsmenu: In list selection show option description

test/main.cpp
See [comment](https://github.com/diasurgical/devilutionX/issues/3778#issuecomment-997288942).
Introduced in #3777.
=> Fix compiling tests with sdl 1

Source/options.cpp
=> Show Hardware Cursor only if supported

android-project/build.gradle
Done on recommendation of Android Studio.
This is a point release, no code changes were required.
Play tested on Google Pixel 2, Android 10, no issues during gameplay
=> Android: Upgrade Gradle plugin version to 7.0.4

Translations/es.po
Add missing translations in settings menu
=> Add missing translations

Source/debug.cpp, Source/debug.h, Source/gendung.cpp, Source/gendung.h, Source/inv.cpp, Source/items.cpp, Source/missiles.cpp, Source/missiles.h, Source/objects.cpp, Source/objects.h, Source/path.cpp, Source/scrollrt.cpp, Source/setmaps.cpp, Source/setmaps.h, Source/themes.cpp
This already existed but had limited usage (and also only handled known positions). This PR expands the functionality and adds helpers to allow using position based tests.
=> Use helper function for Object by position lookups

Source/automap.cpp, Source/diablo.cpp
Adds difficulty display as well as capitalizing Game and Password.
=> Implement Difficulty in Automap

Source/scrollrt.cpp
=> move FPS display down due to new display of difficulty

Source/dvlnet/tcp_server.cpp
This prevents malicious connections crashing a game by sending null bytes, but might still allow errors when packets are manually crafted.
fixes #3789 - that particular error is thrown in `PacketReady()` when a packet with length 0 is received. No error is thrown when sending an oversize header but it doesn't appear to cause any crashes or odd behaviour, so I didn't investigate further.
=> Drop connections when a packet with length 0 header is received

Translations/es.po
- Shorten texts to accommodate the settings menu
- Actualize translation from source
=> Actualize Spanish translation

Translations/uk.po
Now that I'm on vacation, I get more time to TL, so expect more PRs
Reviewers: Ignore first commit
@SourceCodeDeleted please review when time permits
P.S. Merry Christmas and happy New Year to all DevilutuionX contributors!
=> UK TL: New Settings + items descriptions

Source/loadsave.cpp
It's safer and easier to rebuild this as we load each item.
=> Skip loading item locations from file

Source/controls/touch/event_handlers.cpp, Source/controls/touch/renderers.cpp
=> Disable stand button when in town

.github/workflows/translations.yml, Translations/cs.po, Translations/de.po, Translations/fr.po, Translations/it.po, Translations/ja.po, Translations/pl.po, Translations/pt_BR.po, Translations/ro.po, Translations/ru.po, Translations/uk.po, Translations/zh_CN.po, Translations/zh_TW.po, tools/validate_translations.py
Fixes #3360
Not the most advanced thing, but it was able to catch a bunch of issues in the translations:
=> Translation validation

Source/missiles.cpp
Cleans up missiles.cpp variables
=> Cleanup missiles.cpp

Source/diablo.cpp, Source/init.cpp, Source/init.h, Source/options.cpp
Remember when I said there's no dependency from the mpq loading code on options? I was blind 😂 
fixes #3919
=> Split loading of MPQs to handle translations and voice packs

Translations/uk.po
@SourceCodeDeleted please take a look
=> UK TL: More new options

tools/build_and_install_smpq.sh
Includes https://github.com/ladislav-zezula/StormLib/commit/a5ef7a850aac844abf2e3859e26617ed596d4624, which should fix issues on some platforms. Refs #3930
=> tools/build_and_install_smpq.sh: Bump StormLib

Source/player.cpp
Fixes the animation frames for medium and heavy armor Warrior.
=> Fix death animation frames for Warrior/Barbarian

Source/missiles.cpp
Fixes collision detection for the fire/lightning sprite that causes element base damage on collision with players and monsters, and removed Damage Mod on items from changing elemental damage.
=> Fix Elemental Arrow Behavior

Source/controls/modifier_hints.cpp, Source/panels/spell_book.cpp
Added spell icons to spell bindings circle.
=> changed spell circle ui

Source/msg.h
=> msg: add documentation of cmd_id enum

Source/controls/plrctrls.cpp, Source/engine/displacement.hpp, Source/engine/points_in_rectangle_range.hpp, Source/engine/rectangle.hpp, Source/engine/size.hpp, Source/inv.h, Source/objects.cpp, Source/themes.cpp, test/CMakeLists.txt, test/drlg_common_test.cpp
This addresses a todo comment, though not in the way that was originally intended as we no longer use Direction::Omni
=> Use Point/Displacements when searching the area centered on a tile

Translations/es.po
Updated from code and added missing translations
=> Add missing Spanish translations

docs/building.md
I just ran through with a clean VM with Win11 and VS2022 and it worked with these instructions perfectly.
=> Improve Visual Studio Instructions

Translations/pt_BR.po
Portuguese (BR) translation 100% complete.
=> Update portuguese translation

Translations/sv.po
=> update swedish translation

Source/control.cpp, Source/control.h, Source/options.cpp, Source/options.h, Source/scrollrt.cpp
=> Display hp/mana values on life/mana orbs

Source/player.cpp
Fixes #4005
Alternative fix #1980 (my favorite 😜)
=> Preview Frame: Disable for towncast

Source/diablo.cpp, Source/stores.cpp, Source/stores.h
Bug introduced a few commits ago in 1519e995cffeaa0d7bdfe93d2ad08ad09c2a9b4b
Fixes #4036
=> Fix premium items reroll on level change

Source/drlg_l2.cpp
Notes:
- Removes old vanilla bugfix
=> Adjust dungeon reroll bugfix
