diasurgical/DevilutionX

Source/player.cpp

Solves the issue where a player can remove another's mana shield by taking damage.
https://user-images.githubusercontent.com/9203145/146689642-01c4e867-a01f-49d8-a398-aea6b72eb616.mp4

Do not send CMD_REMSHIELD when another player runs out of mana

---

Source/utils/console.cpp

This is kind of invaluable when debugging against SDL1 on Windows.

[Windows] printInConsole() calls OutputDebugString()

---

Source/diablo.cpp

This is a result of checking that the translation specified in diablo.ini actually exists:
https://github.com/diasurgical/devilutionX/blob/cacf55bb34c1c314d2b39868826f63f732cbfdf6/Source/options.cpp#L932-L937
I found the check useful when I was switching between branches with different translations available, but another fix for # 3821 could be to always assume the ini value is correct and bail early if the value exists (remove the HasTranslation call in that block).
For now I think it's safe to load the MPQs before the ini, there's no circular dependency (yet 😂 )
fixes #3821

Load MPQ archives before reading options so translations can be detected

---

Source/DiabloUI/credits.cpp
Source/DiabloUI/diabloui.cpp
Source/DiabloUI/dialogs.cpp
Source/DiabloUI/progress.cpp
Source/DiabloUI/title.cpp
Source/controls/controller.cpp
Source/controls/controller.h
Source/controls/devices/game_controller.cpp
Source/controls/devices/game_controller.h
Source/controls/input.h
Source/miniwin/misc_msg.cpp

It came up in #3825 that the once-per-input-event restriction related to the idempotency of `ToControllerButtonEvent()` is a bit unhandy. This doesn't exactly make the function idempotent, but it moves the restriction to another function so the state can be repeatedly queried without issue.

Improve behavior of ToControllerButtonEvent()

---

Source/panels/spell_book.cpp
Translations/bg.po
Translations/es.po
Translations/it.po
Translations/ja.po
Translations/sv.po
Translations/uk.po
Translations/zh_CN.po

Removes the display of mana and damage for unusable spells and moves the "Unusable" text onto the second line, fixing the overlap.
Before | After
---|---
Fixes #3846

Spell book: Fix "Level 0 - Unusable" overlap

---

Source/DiabloUI/credits.cpp
Source/DiabloUI/diabloui.cpp
Source/DiabloUI/title.cpp
Source/movie.cpp

Keypresses still occur on keydown to allow for repetition (e.g. when scrolling)
fixes #3850

Consistently trigger menu/movie transitions on mouse up instead of down

---

Source/inv.cpp

This more closely matches vanilla behaviour until more intelligent dropping item behaviour is implemented (see #3489)
https://user-images.githubusercontent.com/357684/142081709-e36114d7-c309-48fe-8c64-868c615b215c.mp4

Restrict dropping items to adjacent tiles

---

Source/cursor.cpp
Source/path.cpp
Source/player.cpp

Allows for a bit of a cleanup where it was previously used. The only remaining uses for lookup are internal to objects.cpp and the one in plrctrls.cpp which has been added to #3336
dObjects is referenced in debug.cpp, loadsave.cpp, gendung.cpp purely for setting/clearing/viewing indexes directly, that can be changed but I'll do it as part of the cleanup of how objects.cpp works internally.

Replace uses of dObject with position-based lookup

---

Source/options.cpp
Source/utils/language.cpp

This allows the settings menu to display the expected value
fixes #3858

Replace en_US code with en when searching for user preferred languages

---

Source/CMakeLists.txt
Source/options.cpp
Source/platform/ctr/locale.cpp
Source/platform/locale.cpp
Source/platform/locale.hpp

As AJenbo mentioned in https://github.com/diasurgical/devilutionX/pull/3663#pullrequestreview-831049564 options.cpp isn't really the best place for platform specific language lookup code to live. Given `n3ds::GetLocale()` already existed in platform/ctr/locale.cpp I figure creating a matching platform/locale.cpp as a generic wrapper is suitable.
I was also playing with an approach where each platform provides a definition for `GetLocales()`, however this requires having a "default" platform library or a way to have multiple definitions for a function and some method to pick the specialisation at compile time... seemed overly complex compared to just using the `#ifdef` chain.

Move platform specific locale lookup code to platform directory

---

Source/objects.cpp
Source/objects.h

Doors really threw me in this one. They involve setting a lot of other state and it's not really clear what it does or whether it's necessary. I ended up combining catacombs/caves as they are identical apart from the piece number used and whether the workaround for what I assume is rendering issues caused by overlapping tiles is needed on the level type.
Does this approach look reasonable? I can drop the last commit and leave the init functions duplicating a bit of code if it makes it clearer to read.

Use Object references when initialising objects from template and second init for crypts/doors

---

Source/player.cpp

Applies the commented bugfix to allow the game to play the level 16 audio message when the player enters the level for the first time.

Bugfix: Level 16 Dungeon Message

---

CMakeLists.txt
Source/platform/locale.cpp
Source/platform/locale.hpp

Adapts the sample code provided by @bubio in #3641 so GetLocales() returns a list of POSIX language codes on apple devices (hopefully... I don't have an environment set up to cross-compile this, lets see if the build works).
Co-authored-by: Bubio <bubio66@gmail.com>

Get user preferred languages on apple devices

---

Source/options.cpp

Without fonts.mpq:
With fonts.mpq:
Requires fonts.mpq in order to display options with extended scripts like korean/japanese/chinese. ~Also not sure the strings chosen are appropriate in all cases, e.g. I think "Limba română" literally translated means "language of romania"? "Român" might be better there.~
fixes #3881 
~Also note the line for Portugese (Brazil) is affected by the bug described in #3834. It's long enough that if wrapping was calculating the correct bounds it'd take up two lines. I'd rather fix that bug than shorten these lines as a workaround.~

Use native script for translated language names

---

Source/DiabloUI/selgame.cpp
Source/dvlnet/abstract_net.h
Source/dvlnet/base_protocol.h
Source/dvlnet/cdwrap.h
Source/storm/storm_net.cpp
Source/storm/storm_net.hpp

Notes
- Make `DvlNet_SendInfoRequest` non blocking / doesn't wait for zero tier to be running. This allows to enter the multiplayer menu faster
- Adds "Public Games" category to UI, with "Loading... ", "None" or game list info.
- Would be nice if someone else could test this.
https://user-images.githubusercontent.com/25415264/148372555-b2f5b638-a4a6-42b1-b5a2-ef3da2377887.mp4
</details>

Improve ZeroTier public game menu

---

Source/diablo.cpp
Source/options.cpp
Source/options.h

Notes:
- This PR only reorder the options. No options are changed in anyway (Category, Key, Name, ...).
- Thoughts:
- Language is first option, cause it's the most important if it's wrong. 😉 (see also [comment](https://github.com/diasurgical/devilutionX/pull/3634#issuecomment-981061793)).
- Start Up is second, cause under it the game mode (diablo/hellfire) can be selected.
- Graphics: VSync & FPS are grouped together,
- Gameplay: Quests got grouped together and QoL Features. Autopickup options is last. They could be moved to it's own category (not part of this pr).
- Keymapping: Keys for "normal" gaming are grouped first, then panel options (charachter, inventory, ...) and last everything else (Quick messages, zoom, help).
- I don't have a strong opinion on the exact order, so I'm happy …

Reorder options in settingsmenu

---

Source/DiabloUI/diabloui.cpp
Source/DiabloUI/settingsmenu.cpp

Fixes #3834
Notes:
- If an option is too long to display, it will be manually separated in two lines. Similar how the first version of the settings menu handled this.
- After each change to a option this need to be rechecked, cause the value description text can be longer or shorter.
- `UiFlags::NeedsNextElement` didn't work correctly when a item is preselected or with the changed up/down logic. Didn't occur in master, cause in master no one uses `UiFlags::NeedsNextElement`
<details><summary>Sample Video</summary>
https://user-images.githubusercontent.com/25415264/148422581-ba118c30-65a4-40b7-a792-006a3e49ddef.mp4
</details>

Settingsmenu: Handle long text

---

Source/codec.cpp
Source/sha.cpp
Source/sha.h

1. Switches to 32-bit based calculation throughout. This is faster and less error-prone as we only byte-swap once when reading and writing.
2. Removes global state from Diablo-SHA implementation.

Cleanup Diablo-SHA and codec.cpp

---

Source/DiabloUI/selgame.cpp
Source/multi.cpp
Source/multi.h

Prior to this change, game init info would only be initialized at the same time the multiplayer menu is initialized. Joining a game will overwrite game init info, but if you fail to join the game, you will never leave the multiplayer menu and so game init info would never be reinitialized. This can lead to some really unhappy situations if you create a new game right after failing to join one.

Reset game info after failing to join game

---

3rdParty/libpng/CMakeLists.txt

The only new commit is https://github.com/diasurgical/libpng/commit/3fe9510f01748b8c706550974e23b09166e5a42d
Fixes #3851

Bump libpng

---

Source/items.cpp
Source/player.cpp
Source/player.h

This is very similar to the code used when casting heal other, except for how the amount to heal is chosen. Could potentially reuse it there as well with a bit of work.
fixes #3923

Dedupe code which determines how much life/mana to restore for potions

---

Source/missiles.cpp
Source/monster.cpp

For review/discussion. Fixes from @SoundChaser83's Apocrypha mod.
> ... it looks like Hellbats and Torchants do absurdly low damage because their fireballs aren't reading damage from the monster data table, and also all monster melee/missile hits do up to + or - 63/64ths points of damage over and above their usual damage range because of a parentheses/order of operations issue.
> Regarding that Torchant/Hellbat fireball fix, those things will hit like an absolute truck if you go through with that fix, so it may be surprising to people.

Apocrypha fixes

---

Source/engine/animationinfo.cpp
Source/engine/animationinfo.h
Source/items.cpp
Source/msg.cpp
Source/player.cpp
Source/player.h
Source/scrollrt.cpp

PR#2322
The [missiles](https://github.com/diasurgical/devilutionX/pull/2322) and [monsters](https://github.com/diasurgical/devilutionX/pull/2230) got faster, But our mighty hero seems sometimes slow... like his is thinking too much. This is now gone! We got instant reflexes.
This PR tries to address input lag. This was done in the same way some other (multiplayer) games handle it.
We decouple shown animation in some cases from game logic.
If the player does nothing (stand animation) and we got an input we analyse the input.
We will anticipate what animation the game logic will show for this input.
Then we will show this preview animation until the next game tick (game logic run).
<details><summary>Example Video (1% game speed)</summary> …

ADL: Introduce preview Frame (reduce input lag feeling)

---

Source/diablo.cpp
Source/options.cpp
Source/options.h

Fixes #2832
Notes:
- Adds Item Highlighting (Default key ALT & RCONTROL)
- Adds Screenshot (Default key PRINT)
- Adds Pause (Default key PAUSE)
- Adds Automap Toggle (Default key TAB)
- Adds Hide info Screen (Default key SPACE)
- With this PR all "normal" actions are mappable. Only menu and store Interactions, Automap movement and "ESC" is still hard coded. But imho these are fine.
- Still missing is mapping the mouse based actions. But this is another topic/issue.
- Also not implemented are modifier keys `SHIFT` or `ALT`.
Open question: currently left and right control are different keys for the keymapper, cause Item Highlighting only used right control. But the alt keys are combined, cause Item Highlighting also used to do this. Should we stay with this old logic or separate all keys or …

Keymapper: Add more Actions

---

Source/objects.cpp

The item generation loops until the item cursor graphic matches what we pass in so the original logic would loop until it found an item that uses the Long War Bow graphic. Long War Bow drops from objects starting on dlvl 10 so this could only have dropped a Long Battle Bow, at least so long as it was using the Long War Bow graphic. However, the graphic was changed recently in bb9a20f.
Incidentally, this brings up another non-obvious side effect of changing the graphic. It seems Nakrul was scripted to always drop an item with the Long War Bow graphic which, prior to bb9a20f, probably could have produced a Long Battle Bow instead.
This resolves #826

Fix item cursor graphic for Rogue's Slain Hero reward

---

CMakeLists.txt

Disables tests by default in MSVC LTO configurations. Refs #3778

Work around MSVC+CMake+LTO bug

---

Source/engine/animationinfo.cpp
Source/player.cpp

Fixes a reported issue from @FitzRoyX
> Another issue is that obligaron's prediction algo thing is causing some slight wierd abruptness when coming to a stop walking horizontally. It feels like the camera is shifting, I don't know how to explain it
In #2457 (last commit) the time the preview frame was shown was added to the animation distribution to smooth the animation better. But this resulted in a small stuttering, cause `GetOffsetForWalking`/`GetAnimationProgress` is also based on this time.
Workaround is to not add preview frame time for the walking animation. Also fixes some casting warnings.

Fix walk stuttering with Preview Frame

---

Source/DiabloUI/settingsmenu.cpp
Source/diablo.cpp
Source/miniwin/miniwin.h
Source/miniwin/misc_msg.cpp
Source/options.cpp

Adds support in the keymapper to bind and use the additional mouse buttons
- middle mouse button
- x1 button (extra button 1)
- x2 button (extra button 2)
They can be bind like any keyboard button and so be used for any action (like item highlighting).

Keymapper: Add middle/x1/x2 mouse button support

---

Source/msg.cpp
Source/multi.cpp
Source/player.cpp

This fix revises the death animation, so that a death resulting in no equipped items being dropped will allow your death animation to match your current armor tier, instead of defaulting to light armor. If your equipped items are dropped, you will continue to use the light armor animation.

Show correct death animation

---

Source/player.cpp

Fixes a reported issue from @FitzRoyX
> @obligaron found another issue probably related to your latest commits, if you try to melee attack an enemy on the other side of a gate (like in leo's chamber), the character sprite goes crazy.
Thanks for reporting 🙂

Fix preview frame when player can't walk to desired location

---

Source/items.cpp
Source/multi.cpp
Source/pack.cpp
Source/pack.h
Source/pfile.cpp
test/pack_test.cpp

This fixes an error where converting Multiplayer save files from Diablo to Hellfire can cause a remote player's game to crash.
When converting save files from Diablo to Hellfire, the Diablo items are remapped to Hellfire item indexes in memory. When saving the file, the game leaves these indexes alone so they match the game type with which the save was generated. If there are any issues with the item when recreating it using the wrong index, the game resolves these by reading from the `heroitems` section of the file.
However, when transmitting the items over the network, there is no `heroitems` file the game can use to fix errors during item recreation. Therefore, the logic for `UnpackItem()` was changed to use the item's `dwBuff` value to tell the client where the item originated from so …

Resolve game crash when syncing Diablo items in Hellfire games

---

Source/DiabloUI/diabloui.cpp
Source/diablo.cpp
Source/diablo.h
Source/miniwin/misc_msg.cpp
Source/sound.cpp
Source/storm/storm_svid.cpp
Source/storm/storm_svid.h

* Mute cinematics when the window is not in focus
* Mute music/cinematic audio when menu state transitions while the window is not in focus
* Fix the error that causes multiplayer games to start paused
* Add SDL1 window focus logic
This resolves #3119

Clean up window focus handlers

---

Source/platform/locale.cpp

Appears some implementations don't support unknown locales and throw errors instead, causing the language detection to error and not complete.
Fixes a crash reported by Linerd in discord (by working around a potential misconfigured environment).

Handle runtime_errors thrown by std::locale constructor

---

Source/sync.cpp

From @kphoenix137 on Discord...
> I had a rogue outside diablos room, the warrior killed diablo, and all monsters died on warrior side 
> Rogue teleported in, and there were blood knights attacking the warrior
Testing reveals this is a vanilla issue, and it's caused by the `CMD_SYNCDATA` network message trying to fix positions for monsters despite them having already entered the death animation state.
I suspect this could help fix some more general desync edge cases as well, considering `M_SyncStartKill()` is already using effectively the same conditional.
https://github.com/diasurgical/devilutionX/blob/3bc2eb8471dba8693c6c7f83f83057f33ab0604e/Source/monster.cpp#L4042-L4049

Don't sync position on dead monsters

---

Source/player.cpp
Source/player.h

This is a bugfix for the vanilla 1.06 and earlier Mana Shield logic. In 1.07 Blizzard North "fixed" the Mana Shield logic since the damage reduction would decrease in effectiveness with increased spell level instead of increase. As a fix, they set the damage reduction to a flat value regardless of spell level. Originally, damage reduction started at 1/3 and capped at 1/21 at spell level 7. This fix reverses the order and gives 1/21 damage reduction at spell level 1, and caps at 1/3 damage reduction at spell level 7.
End result damage reduction values (based on 100 incoming damage):
SLvl 0 = 0
SLvl 1 = 4
SLvl 2 = 5
SLvl 3 = 6
SLvl 4 = 8
SLvl 5 = 11
SLvl 6 = 16
SLvl 7+ = 33

Mana Shield 1.07 bugfix revision

---

Source/controls/plrctrls.cpp
Source/controls/touch/renderers.cpp
Source/cursor.cpp
Source/loadsave.cpp
Source/misdat.h
Source/missiles.cpp
Source/missiles.h
Source/monster.cpp
Source/msg.cpp
Source/player.cpp
Source/portal.cpp
Source/scrollrt.cpp

Fixes #768
<details><summary>Example Videos</summary>
https://user-images.githubusercontent.com/25415264/149675676-175df2c0-1ab8-498a-8c4b-4cdd78f2f2ae.mp4
https://user-images.githubusercontent.com/25415264/149675685-49e35c77-0ee3-451d-95a5-25603c5bb16a.mp4
</details>
Notes:
- Technically the limit is not "removed" but only enhanced from 125 to 2147483648. But for the dungeon size this is the same as unlimited? 😜 
- Change is backwards-compatible (see Example Videos). This is achieved by adding the first 125 the normal way and the rest is added to a new `addtionalMissiles` "file" in the save game. Vanilla ignores `addtionalMissiles` and only loads the first 125 missiles.
- `AddMissile` checks from 0 upwards if a missile id is free. If we think this is performance wise not a good move, …

Remove missile/sprite limit

---

Source/multi.cpp

This fixes an issue where a remote player's sprite blinks back and forth after their position desyncs during east/west movement.
---
The following video demonstrates the issue. The remote player casts Teleport in the middle of walking eastward, but the local game client doesn't see the spell because the `CMD_SPELLXY` command is received while their sprite is in-between tiles. When their position inevitably desyncs the sprite begins to blink back and forth.
https://user-images.githubusercontent.com/9203145/150460171-15171ce7-6614-4aa2-aeb8-18ef34542f6a.mp4
---
If a remote player's position desyncs by more than 3 tiles, `multi_process_network_packets()` will use position data from packet headers to force the player into the correct position. …

Fix blinking when position desyncs during E/W movement

---

Source/msg.cpp

Just a case of using the wrong enum value for the comparison.
This resolves #3979

Fix comparison checking for invalid quest state in DeltaSyncJunk

---

Source/loadsave.cpp
Source/missiles.cpp
Source/missiles.h
Source/monster.cpp
Source/portal.cpp

Addresses a few warnings about truncating conversions between types, unused variables, and potentially allows changing the container type without throwing as many errors.

Missiles tidy-up/max-size check

---

Source/controls/plrctrls.cpp
Source/diablo.cpp
Source/inv.cpp
Source/inv.h
Source/items.cpp
Source/msg.cpp
Source/msg.h
Source/player.cpp

Fixes #1437
I think this is working acceptably, I was able to see quest items drop for all players in a multiplayer game no matter who triggered the item to spawn and also see the item if a player joined late. I didn't notice monster loot or chest loot getting duplicated, I was worried that might need more care to prevent. I would definitely appreciate more eyes to make sure I haven't missed anything.
Main thing was sending the DROPITEM message when quest rewards are spawned, and refactoring the Sync*Item code so it doesn't assume that a player is always dropping an item from hand.

Sync quest items in multiplayer games

---

Translations/ru.po

Fix #3570 
- Overlaps now fixed.
- Character menu looks almost neat.
- Translation of character menu is now closer in meaning to original.

Fix russian translation stats labels overlap

---

.circleci/config.yml

The recent CI build failure made me realize that our attempts to download makerom are being redirected because jakcron's repo for Project_CTR has been transferred to the 3DSGuy account. The issue that caused the build failure itself seems to have been transient, but I figured we may as well fix the URL and upgrade to the latest version while we're at it.

[3DS] Use latest version of makerom

---

Source/dead.cpp
Source/engine/load_file.hpp
Source/misdat.cpp
Source/misdat.h
Source/missiles.cpp
Source/scrollrt.cpp
Source/utils/file_name_generator.hpp
Source/utils/static_vector.hpp

Previously, the memory for each frame was allocated separately.
Changes it to allocate a single buffer for all the frames.
This has the following advantages:
1. Less bookkeeping overhead in the allocator.
2. Less alignment overhead (allocator results are max-aligned by default).
We can follow this up with a similar treatment for other multi-file animations.

Load missile frames into a single buffer

---

Translations/devilutionx.pot

Since 1.4.0 release in on the horizon, it would be good to keep POT file up-to-date in case any translator uses it as reference, instead of POEdit's "Update from source"
POT file was missing some new strings from "Settings" menu

Update POT to include new strings

---

android-project/build.gradle
android-project/gradle/wrapper/gradle-wrapper.properties

* Upgrades Gradle from 7.3 to 7.3.3. This includes patched log4j library and log4shell mitigations. [This is a recommended upgrade from Gradle team](https://docs.gradle.org/7.3.3/release-notes.html)
* Upgrades Gradle plugin to 7.1.0
Locally built and play tested, everything works

Android: Upgrade Gradle build tools

---

Packaging/windows/mingw-prep.sh
Source/options.cpp
Source/utils/display.cpp

With the SDL 2.0.18 change to use the built-in WASAPI audio resampler (libsdl-org/SDL@ac32c52) and the recent vcpkg update to move from SDL 2.0.16 to SDL 2.0.20 (microsoft/vcpkg@9eb76eda), this seems like a pretty good time to reintroduce WASAPI.
While testing various audio settings, we found that resampling quality can have a pretty significant impact on game performance. Therefore, I'd also like to propose reducing the default resampling quality from 5 to 3 based on guidelines found in the Speex resampler documentation.
> https://speex.org/docs/manual/speex-manual/node7.html#SECTION00760000000000000000
> Usually, a quality of 3 is acceptable for most desktop uses and quality 10 is mostly recommended for pro audio work. Quality 0 usually has a decent sound (certainly better than using …

Restore default Windows audio driver (WASAPI)

---

Source/monster.cpp
Source/msg.cpp
Source/msg.h
Source/objects.cpp
Source/towners.cpp

This fixes an issue where the items dropped by Hork Demon and Nakrul will disappear from the floor if you exit the dungeon level without picking them up.
---
There are some really unintuitive things going on here so strap in while I try to explain them.
There are three functions the game uses to manipulate item deltas.
* `DeltaAddItem()` is called when an item is placed on the floor by dungeon generation (aka "floor items")
* `DeltaPutItem()` is called when players drop items on the dungeon floor or when spawning loot from monsters or chests
* `DeltaGetItem()` is called when players pick up items from the dungeon floor
The intent here is to reconstruct level state when "warping" via stairs or portals. The dungeon gets regenerated from its seed, and then `DeltaLoadLevel()` uses the level …

Fix Hork Demon and Nakrul drops in multiplayer

---

Source/dvlnet/tcp_client.cpp
Source/engine/demomode.cpp
Source/gamemenu.cpp
Source/menu.cpp
Source/multi.cpp
Source/options.cpp
Source/options.h
Source/palette.cpp
Source/sound.cpp
Source/storm/storm_svid.cpp

Only a refactoring.
Doesn't change any behavior.
Simply moves more options to `OptionEntryBase` usage, so that the code is less inconsistent.
Didn't touch float and string based options.
If someone is willing to test controller settings I could also move `Swap Shoulder Button Mode`, `Dpad Hotkeys` and `Enable Rear Touchpad` to `OptionEntryBase` (and include them in the settings menu).

Move more options to OptionEntryBase

---

Source/DiabloUI/selgame.cpp

Currently Public Games Browsing is only supported on ZeroTier.
PR fixes that "Public Games" (in `selgame.cpp`) are shown when TCP and Loopback is selected.

Show public games only on zero tier

---

Source/drlg_l2.cpp

Fixes #1506
`CreateRoom` [remembers](https://github.com/diasurgical/devilutionX/blob/2d6c602ef54cd84b6287a3b8af16bfc40183c761/Source/drlg_l2.cpp#L1990-L1995) the room coordinates in some variables.
This only happens if the room is [reserved for a quest](https://github.com/diasurgical/devilutionX/blob/2d6c602ef54cd84b6287a3b8af16bfc40183c761/Source/drlg_l2.cpp#L2688-L2714).
It doesn't happen if the level has no active quest.
The problem is that these variables are never reset when generating the level. They only get set when space is reserved for a quest set piece.
in issue #1506 Arkaine's Valor is not available, so level 5 has no quest set piece.
But level 6 has a quest room for Chamber of Bone.
That means level 6 sets these variables and when loading level 5 again you get another …

Fix dungeon reroll - Initialize special Room coordinates

---

Source/player.cpp

This fixes a problem related to shrines. When a player with a base Magic or Vitality stat of 0 has their respective stat reduced below 0, they lose Mana/Life, and their stat is corrected to 0 without refunding them the lost Mana/Life. This will prevent stats from being modified to a value less than 0 in the first place.

Fix Stat Adjustment

---

Source/loadsave.cpp

This was a cleanup function to handle converting saves between Hellfire <-> Diablo, mainly when a hellfire specific item was dropped and should be removed from a Diablo game. This had an off by one with the way it iterated backwards over the active items list which meant it always called DeleteItem at least once (since it uses an invalid item past the end of the active items range). DeleteItem then always decremented the ActiveItems count. When saving the game after converting the items we then end up with a dropped items array containing an index to an item that is no longer considered active.
However the code in LoadDroppedItems already checks that the conversion was successful before considering it active, so this function doesn't need to be called. Instead we can just save if we …

Get rid of RemoveEmptyLevelItems

---

Source/objects.cpp

Have seen this bug for years but never knew it was a bug until looking into it. When the game places down wall traps, it doesn't consider whether an object is already there. Therefore it overwrites whatever is in the object map array, but not the existing object. The result is that multiple objects can exist in the same place the trap does.
In the screenshot below, you see how the trap was placed on top of a torch and therefore has lighting when it shouldn't. Traps may also spawn multiple times on top of each other. The fix is to skip placing the trap if an object already exists on the wall.

Add vanilla trap bugfix

---

Source/track.cpp

Similar to [`RightMouseDown`](https://github.com/diasurgical/devilutionX/blob/db9a7c7cba1f957546b117b4cf1fd4bdb0317e66/Source/diablo.cpp#L374).

Fix flash infinite casting: Add check for _pInvincible to RepeatMouseAction

---

Source/CMakeLists.txt
Source/control.cpp
Source/dead.cpp
Source/engine/render/cel_render.cpp
Source/engine/render/cl2_render.cpp
Source/engine/render/cl2_render.hpp
Source/engine/render/common_impl.h
Source/engine/trn.cpp
Source/engine/trn.hpp
Source/lighting.cpp
Source/lighting.h
Source/missiles.cpp
Source/monster.cpp
Source/monster.h
Source/scrollrt.cpp

Old TRN system was pretty poo - the game could only handle 8 unique monsters with it - now unlimited.
I've also noticed a bug while doing the rewrite - TRNs for missiles never worked, except for rhino.
I think they forgot to plug the system for the rest of the missiles.
Here's bloodlust before and after fix. (notice blue color baked into first frames of the animation)
The goal of this PR is to make future modding easier - adding custom TRNs to missiles etc.
Deathspit:
Plaguewrath:
Screenshot from Crucible as a bonus:

TRN rewrite + bugfix

---

android-project/build.gradle

Another update to point release of Gradle plugin, 7.1.1 at the recommendation of Android Studio
Build play-tested, no issues found

Update Gradle plugin version

---

Source/debug.cpp
Source/effects.cpp
Source/monster.cpp
Source/monster.h

allows spawning unique monsters
makes sound work for spawned monsters
improves name matching - earlier first partial match would take priority over a full match
Split into two commands to avoid a situation where having a match in unique monsters will always be prioritized 
(skeleton would spawn skeleton king instead of a skeleton)

fix spawning unique monsters

---

Source/inv.cpp

From a practical standpoint, this change should be both pointless and benign. The only place where `player.HoldItem` is not passed as the `item` parameter is `DoPickup()` in `autopickup.cpp`, which passes `false` for `persistItem`.
https://github.com/diasurgical/devilutionX/blob/d3995736b97fd97dfa2ce5744fca2b691b9eca06/Source/qol/autopickup.cpp#L47
However, there are at least a couple good reasons to make the change. It seems to me that this assignment is only correct under the assumption that `item` and `player.HoldItem` are the same, which will cause issues if the function is called with `persistItem == true && item != player.HoldItem`. Furthermore, it already caused me plenty of confusion when reading the code.

Persist the placed item in AutoPlaceItemInInventorySlot()

---

Source/diablo.cpp
Source/menu.cpp
Source/sound.h

Fixes #799
- When the same track is played on both levels the music isn't restarted.
- When a different track is needed the music will change when the loading screen is shown (the music will stop after 20% finished). This feels a little bit like fade out / in.
- The music will not stop when quick-loading (if the saved level uses the same track).
- Music in menus continues playing.

Don't restart music if the same track is played

---

Source/menu.cpp

Regression introduced by #4100
The main loop handler should close music, cause this also closes diablo.
If the music doesn't stop the destructor of `Aulib::Stream` would be called when memory is cleaned up and this can result in a deadlock.
Sorry for the inconvenience. 😞

Stop music on diablo exit

---

Source/items.cpp

Change to use MAXRESIST instead of hardcoded 75 when printing resists to panel, in case someone were to change the MAXRESIST number.

Max Resist Item Panel Description fix

---

Source/dvlnet/base_protocol.h

This change should reduce ZT errors due to erroneously interpreting random network traffic as an in-game packet. In cases where the player index is included as the packet source, this merely validates that the endpoint of the client who sent the packet matches the one that we would send packets to when communicating with the player at that index. FYI, this means that packets cannot be sent on behalf of another player, but that sort of delegation shouldn't be necessary since all players should have a direct channel to communicate between each other.
I believe this should help to address crashes similar to the one reported in #3263.

Filter out ZeroTier packets that do not come from an expected source

---

Source/CMakeLists.txt
Source/controls/plrctrls.cpp
Source/diablo.cpp
Source/help.cpp
Source/multi.cpp
Source/plrmsg.cpp
Source/qol/chatlog.cpp
Source/qol/chatlog.h
Source/scrollrt.cpp

After right margin change:
Disadvantages vs old ver:
No spinner
No scrollbar
Improvements:
`Chat History (Messages: {:d})` turns red if there's a new message and you haven't scrolled to top yet
page up / page down scroll to top / bottom of the chatlog
Clock in upper left corner - that's why I allow opening chat log in single player, it takes care of a request to have an ingame clock :D

chatlog 2.0

---

Source/dvlnet/base_protocol.h

This resolves #4120
... I have no explanation for how I didn't catch this.

[ZeroTier] Treat firstpeer as a recognized source of packets

---

Source/control.cpp
Source/debug.cpp
Source/gendung.cpp
Source/gendung.h
Source/inv.cpp
Source/items.cpp
Source/items.h
Source/missiles.cpp
Source/msg.cpp
Source/objects.cpp
Source/player.cpp

This is part of the ongoing cleanup for #2586. #2932 has effectively got `DeleteItem` to the point where it can be replaced by an STL container's `erase` method, the aim with this branch is to get `AllocateItem` ready to be replaced with a `push_back` equivalent.
To make it easier to reason about how items are spawned and dropped on the ground I've started working through the code responsible for creating items in general. This set of commits is mainly cleanups for items.cpp, using `const Item &` for functions which do not modify the argument and renaming some initialisation functions to match their purpose better.

Initial clean up of code related to creating items

---

test/player_test.cpp
test/writehero_test.cpp

These tests were asserting side-effects of the call to CreatePlayer leaving an initialised gold item in the held item slot.

Fix tests expecting unclean HoldItem uses

---

Source/inv.cpp
Source/inv.h
Source/player.cpp
test/inv_test.cpp

Split this into two commits so it's easier to see the changed variable reference.
The only reason GoldAutoPlaceInInventorySlot was forward declared (in the header) was due to the order those functions were defined, so I moved that into the anonymous namespace in the second commit.

Don't use holdItem as a temporary when auto-picking up gold

---

Source/dvlnet/base_protocol.h

@ephphatha made [a rather astute observation](https://github.com/diasurgical/devilutionX/pull/4116#issuecomment-1059844326) the other day. When filtering packets from unrecognized sources, players need to be made aware of each other by someone they recognize. Currently, when the third player joins the game and the first player handles the join request, the second player doesn't recognize the third player which causes the join to fail.
With this PR...
* When handling `PT_JOIN_REQUEST`, the host assigns the player number and implicitly trusts the joining player's packets
* The joining player receives the host's player number from `PT_JOIN_ACCEPT` and so only accepts `PT_JOIN_ACCEPT` packets from `firstpeer`
* When handing `PT_JOIN_REQUEST`, the host informs all players of each other via …

[ZeroTier] Send PT_CONNECT to all players when new player joins

---

Source/dvlnet/base.cpp
Source/dvlnet/base.h
Source/dvlnet/base_protocol.h
Source/dvlnet/packet.h
Source/dvlnet/tcp_client.cpp
Source/dvlnet/tcp_client.h

This PR attempts to resolve "frequent hourglass which is not seen in vanilla" reported as part of #4098.
The idea behind this PR is to modify the network provider to prevent "turn desync" that occurs due to the unpredictable timing of packet arrival on each client. I plan to follow up with a much more detailed description of what's happening and what the PR does to fix it. It's a big, long writeup so I thought it might be good to break it into separate posts this time.
FYI, I am a little worried that these changes may prevent players with very high latencies from joining each other's games because the guest's first turn may get skipped by the host. I'm thinking about a couple ways to fix that, but I'm not entirely sure if it's really a problem just yet.

Apply sequence number to net turns

---

Source/dvlnet/base.h
Source/dvlnet/base_protocol.h

This fixes the implementation of `base_protocol<P>::IsGameHost()`. This was just an unfortunate consequence of rebasing #4122 on #4131 that needed to be fixed up.

Fix IsGameHost() function for ZeroTier

---

Source/scrollrt.cpp

Fixes #4136
`DrawPlayerIconHelper` got a `Point` passed that has a adjusted x coordinate (subtracted `CalculateWidth2`).
But `DrawPlayerIconHelper` needed the original `Point` so it reverted the change (added `CalculateWidth2`).
Cause of preview Frame these two cases differed (first used preview frame, `DrawPlayerIconHelper` didn't).
This PR removes these change/revert logic for `DrawPlayerIconHelper` => cleaner & less calculation.

Use original position for DrawPlayerIconHelper

---

Source/monster.cpp

Fixes #4144
The TRN crash occurs cause `uniqueTRN` must be initialized if the monster is a unique (`monster._uniqtype != 0`).
`uniqueTRN` is only initialized in `InitMonsters`.
When we load a visited level all monsters that got generated by `InitMonsters` get removed and replaced by the monsters from the save.
But these new loaded monsters don't initialise `uniqueTRN`. That means they depend on the data set by `InitMonsters`.
This difference between generated and loaded monsters can cause the issue.
After #3744 this can happen much more often (cause when generating the level `InitMonsters` is called after `InitObjects`, but when loading a level `InitObjects` isn't called so we get different numbers).
But even without #3744 we don't generate always the exact same monsters for a dungeon …

Init monster TRN after monster load

---

.github/workflows/src_dist_release.yml

* Use apt-get instead of apt, since apt has a warning
* Add Gtest dependency since it's now required
@glebm please review

Update action for source tarball

---

android-project/app/build.gradle

This resolves the issue with the Android test build that's been reported a handful of times on Discord.

Adjust gradle task dependencies to ensure assets are included in the APK

---

.circleci/config.yml
.github/workflows/Android.yml
.github/workflows/Linux_x86.yml
.github/workflows/Linux_x86_64_SDL1.yml
.github/workflows/PS4.yml
.github/workflows/Windows_x64.yml
.github/workflows/opendingux_release.yml
.github/workflows/retrofw_release.yml
.github/workflows/translations.yml

Usage of `apt-get` instead of `apt` applied everywhere else.
For reasoning, see https://manpages.debian.org/buster/apt/apt.8#SCRIPT_USAGE_AND_DIFFERENCES_FROM_OTHER_APT_TOOLS

Use apt-get instead of apt in CI

---

Source/stores.cpp

When the healing option was removed from the menu the leave option was moved up. This is evidently not the right change since all stores have the leave option at at least the 18th position even when they have less options. It just happened that the healer had an option for all other lines.

Leave healer

---

Source/dvlnet/base.cpp
Source/dvlnet/base.h
Source/dvlnet/base_protocol.h
Source/dvlnet/packet.cpp
Source/dvlnet/packet.h
Source/dvlnet/protocol_zt.cpp
Source/dvlnet/protocol_zt.h
Source/dvlnet/tcp_client.h
Source/dvlnet/tcp_server.cpp
Source/dvlnet/tcp_server.h

Summary of changes:
* Add packet types for echo request and echo reply to calculate round-trip latency
* Use echo packets in ZeroTier client to implement a two-way handshake between peers
* Queue packets in ZeroTier client until the first packet has been received from the remote player, indicating that packets will not be ignored
* Add `protocol_zt::is_peer_connected()` to prevent race conditions when establishing TCP connections between peers
* Fix turn interactions by replacing `waitForTurns` flag with `awaitingSequenceNumber_` and `SendFirstTurnIfReady()`
* Send `PT_CONNECT` from TCP server to all TCP clients when a new player joins
So.. I must admit that part of the reason this ended up being so complicated is because of the packet validation I added the other day (#4116). 😓 
Because …

Fix network issues due to high-latency

---

Packaging/apple/Info.plist

- Redo PR #3764
- To run as an iPad app, the UIDeviceFamily key is required in Info.plist.
https://discord.com/channels/518540764754608128/518541192993046562/920602213901025300

Fixed an issue that caused the app to run as an iPhone app on iPad.

---

Source/diablo.cpp

This filters calls to `LoadStash()` so items get loaded from disk only on New Game and Load Game.
The game loads the stash from disk whenever the player changes levels, which causes some problems for Single Player. Kudos go to AJenbo for catching this so quick after merging.

Only load stash on New Game and Load Game

---

Source/inv.cpp
Source/qol/stash.cpp

Fixes a issue mentioned in stash pr #3853
> It's possible to open both gold input panels at the same time

Allow only one gold input panel to be open

---

Source/inv.cpp
Source/inv.h
Source/qol/stash.cpp
Source/qol/stash.h

With this pr we can fill the brand new stash faster. 😁
- If inventory is full the item is still dropped on the ground.
- If stash (unlikely) is full the item is still dropped on the ground.
- If a stash page is full the item will be placed on the next stash page. If we are on the last stash page the algorithm starts with page 1 again.
- Needs to be rebased if #4172 is merged before (cause of the usage of `Stash.page`).
https://user-images.githubusercontent.com/25415264/159096311-ae1f41e4-8e8b-43c9-95eb-d3619f46b2c8.mp4

Allow to swap items with ctrl+click between inventory and stash

---

Source/diablo.cpp
Source/items.cpp
Source/items.h

Fixes a issue mentioned in stash pr #3853
> It's not possible to use or cast spells on items in the stash

Allow identify/oil/repair/recharge on stash items

---

Source/diablo.cpp
Source/qol/stash.cpp

With this pr it is possible to use/consume items from stash (for example a potion).
Notes
- I tried to simplify `RightMouseDown` and removed a redundant call to `UseInvItem`. i would appreciate if someone could double check this.
- For now i disabled the use/consume of scrolls from stash. This would make fixing double cast bug harder. For more details see this [discussion](https://github.com/diasurgical/devilutionX/pull/3853#issuecomment-1072957281).

Allow to consume items from stash

---

Source/inv.cpp
Source/qol/stash.cpp

Instead play `HeroSpeech::IHaveNoRoom` and put the item in the hand/cursor.

Ctrl+click stash item swap: if there is no room left, don't drop the item on the ground

---

Source/control.cpp
Source/control.h
Source/inv.cpp
Source/inv.h
Source/qol/stash.cpp

I also found a really stupid feature that can be supported with auto-pickup which was only prevented by a minor bug with the gold pickup code, so the last commit addresses that bug. Now you can pick up items while walking with the inventory open and a held item :D
https://user-images.githubusercontent.com/357684/159118640-2a7fb953-13ff-4ee1-861e-a4458e2ae8f9.mp4

Remove the use of HoldItem in AutoGetItem

---

Source/DiabloUI/ui_item.h

These are the items that are always called with a string instance owned by the current translation dictionary. ~UiEdit was included even though hints are never referenced...~ Found what UiEdit hints are used for, that mess is being pulled out for a later attempt
`string_view` can be created from c-strings so this works fine with current master and `std::string &` as returned by `LanguageTranslate` in #4174

Use string_view for UiArtTextButton, UiButton, UiEdit hint

---

Source/sync.cpp

As observed in https://github.com/diasurgical/devilutionX/issues/4182 monsters health appears to get stuck and jitter in current master. This is probably caused by https://github.com/diasurgical/devilutionX/commit/b00feb4c3d85fca3fa7cf2cf1975a1629744b35a where monsters health is synced on every tick, which may well cancel out most damage dealt to the monster by a ranged player (since the closest player's data will overwrite the more distant one).
It also appeared that mWhoHit has not taking the ranged player in to account which would again be explained by `mWhoHit` being taken from the melee player. Instead this is now ored on to the local state.

Avoid resetting monster health and mWhoHit

---

Translations/uk.po

Yesterday, I only wanted to TL strings related to stash.
But then I had decided to pony up the cash for POEdit Pro licence. Machine translations from POEdit Pro provided the basis to start tackling the most fearsome beast - Shrine and dialogue text.
That helped me to reach 76% of translated entries in Ukrainian language, which I believe gets it inclusion in future release?
Note to self — DevilutionX ignores em-dashes

UK TL: Reach over 75% of translated entries

---

Source/msg.h
Source/multi.cpp

With this change mana is synchronized between clients/players.
Should help to get #4074 along, see this [comment](https://github.com/diasurgical/devilutionX/pull/4074#discussion_r830529747).
Tested with modified `control.cpp` (when selecting another player mana is shown instead of hp; not included in this pr).
Works even with debug `fill` command. 😉

Sync mana between clients

---

Source/controls/plrctrls.cpp
Source/diablo.cpp
Source/items.cpp
Source/qol/stash.cpp
Source/qol/stash.h
Source/stores.cpp

Fixes a issue mentioned in stash pr #3853
> If a player doesn't have the requirements of an item it is placed on the stash tinted as red, if another player opens the stash it will be still red. The opposite is also true, items show colored even if the player doesn't have the requirements
This pr updates `_iStatFlag` for the active page when opening the stash or changing the active page.
This pr also reduces the number of places where max stash pages are defined.

Update _iStatFlag for stash items

---

Source/multi.cpp

This removes the logic that attempted to determine which multiplayer client should be the one to resume a game session in the event of a network interruption. Instead, every client will individually determine which players need to be kicked so that the game session can resume locally.
After a bunch of testing and brainstorming with @AJenbo, we came to the conclusion that there's no compelling reason to try so hard to make sure that only one game session remains active in the event of a network disruption. On the contrary, it's not difficult to imagine legitimate scenarios where doing so would be undesirable for the entire party.
For more context regarding what this is all about, see https://github.com/diasurgical/devilutionX/issues/4182#issuecomment-1073078627.

Do not exit game on network timeout

---

.github/workflows/MacOSX.yml

This unconditionally uploads the artifact from the GitHub Actions workflow for MacOSX so test builds can be obtained for that platform.

Add artifact to MacOSX workflow

---

.github/workflows/opendingux_release.yml
.github/workflows/retrofw_release.yml
.github/workflows/src_dist_release.yml

1. Use `${{ }}` consistently. It is technically not required in `if` conditions but GitHub CI docs use it and it avoid certain pitfalls,  such as when the value starts with `!` (making it a YAML type declaration).
2. Fixes one of the `if`s.

Github CI: Fixup release actions

---

Source/engine/cel_sprite.hpp
Source/utils/pointer_value_union.hpp

Reduces the size of a `CelSprite` by taking advantage of the fact that 16-bit pointers are aligned, so the last bit is always 0.
Note: It'd be nice if in the future we separate multi-width sprites (sprite sheets) from single-width sprites (animations) in the type system.

CelSprite: Unify width storage

---

Source/engine/cel_sprite.hpp
Source/items.cpp

Conversion is already provided by the `CelSprite(const OwnedCelSprite &)` constructor.

Remove `OwnedCelSprite::Unowned` method

---

Source/capture.cpp
Source/dx.cpp
Source/dx.h
Source/interfac.cpp
Source/scrollrt.cpp

We do not seem to render from multiple threads, so these calls are unnecessary.

Remove `(un)lock_buf`

---

Source/inv.cpp

I didn't realise that AutoGetItem runs for all pickup logic now? I thought that InvGetItem would be running in this case which still copied the note before combining fragments. This would've been an issue for auto-pickup anyway so this change preserves the position and sets it on the reconstructed note.
fixes #4240

Restore position of dropped note when recombining fragments

---

Source/utils/display.h

Fixed issue #4217
Tested on:
MacBook Pro 2017 / macOS 12.3 / Retina
Note PC / Zorin OS / Non-Retina

DPI Scale is now included in the calculation.

---

Source/inv.cpp
Source/inv.h
Source/msg.cpp
Source/player.cpp

From #4182
> When auto equiping items the other player will sometimes not see that it has been equiped
This is caused by the fact that `NetSendCmdChItem()` uses `myPlayer.HoldItem` to populate the network message with item creation info. When auto-equipping items, the local client places the item in the appropriate equipment slot directly from the list of items on the ground. The network message ends up using whatever data is left over from the last item the player was holding.
The idea here is to change `NetSendCmdChItem()` to use data from `player.InvBody` instead. This means the item must be equipped locally before attempting to send the network message. The `ChangeEquipment()` function was introduced to ensure that the network message is only sent under the appropriate conditions. …

Fix multiplayer equipment synchronization

---

Source/quests.cpp
Source/towners.cpp

Fixes #4184
This turned out to be a vanilla hellfire bug. When loading level 8 the quest would be set as active, like for most other quests. But this quests should only be set active when the player is handed the rune bomb by the Nut in town. This would lead the logic to think the Nut had already given you the bomb and so the quest would be stuck in this state.
The solution is quite simple, simply do not enable this quest during loading of level 8.
Also I removed the specific dialog line for `QUEST_ACTIVE` as it is the same as the default dialog.

Fix cow quest getting stuck in multiplayer

---

Source/diablo.cpp
Source/diablo.h
Source/options.cpp
Source/options.h
Source/palette.cpp

… and remove command line parameter `--nestart`.
This enables platforms that can't use command line parameter (for example android) to use the alternative nest art.
It's also easier to access cause it's now part of the settings menu.

Add OptionEntry for alternative nest art

---

Source/diablo.cpp
Source/msg.cpp
Source/player.h
Source/spells.cpp
Source/spells.h

fixes #4252
> We have made changes that makes heal other/resurrect only trigger when a player is targeted (to avoid wasting the spell).
The cast spell code fires in `TryIconCurs()` for both left and right clicks (and cursor driven gamepad actions with the inventory open). In the current code these spells are "cast" with no target, then when the local client receives the message the cursor is changed back to the hand only if there was a valid target. In a roundabout way this leaves the spell readied unless the user does something else which triggers a cursor change (like interacting with an inventory cell).
This change restricts casting resurrect/heal other only with a valid target. This ends up making left mouse clicks progress through the fallback cases that allow moving with a readied …

Cancel heal other/resurrect on right-click

---

Source/utils/sdl_bilinear_scale.cpp

Fixes funky hardware cursor colors during fade transitions.
Refs #4206

Fix underflow in `BilinearScale32`

---

Source/loadsave.cpp
Source/qol/stash.cpp
Source/qol/stash.h

Most of this was centred around stash pages being saved/loaded as unsigned values but stored as signed values. Consistently used unsigned since it matches the intended usage.

Address type conversion warnings in loadsave.cpp

---

Source/utils/pointer_value_union.hpp

This triggers a bunch of warnings in MSVC because the conversion is potentially truncating, despite never being an issue in practice...

Address c4244 warning in PointerOrValue

---

Source/controls/game_controls.cpp
Source/options.cpp
Source/options.h

Previously the gamepad was hardcoded to send F5-F8, with this change it will press what ever button the first 4 quickspells are bound to.

[gamepad] Fix using quick spells with rebound keys

---

Source/controls/game_controls.cpp
Source/controls/plrctrls.cpp
Source/controls/touch/renderers.cpp
Source/cursor.cpp
Source/inv.cpp
Source/inv.h
Source/miniwin/misc_msg.cpp
Source/player.cpp
Source/qol/stash.cpp
Source/qol/stash.h

Resolves #4211 and an issue with the cursor not resetting correctly in the inventory (see `InvGetEquipSlotCoordFromInvSlot()`)
Optional:

Add gamepad support for stash

---

Source/stores.cpp

@ikonomov reported this issue on Discord.
> in Hellfire single player when I try to buy an item from Pepin the gold is spent, but no item is transferred to the inventory
> and at Gris and Adria when I buy an item it appears in the inventory, but when I try to interact with the newly bought item it disapears
The culprit here is the code introduced into `NewCursor()` by #4239. Or perhaps it would be more accurate to say it's the stores' abuse of the `Player::HoldItem` variable. Regardless, the calls to `NewCursor()` in each of the `*BuyEnter()` functions was clearing the item type of the hold item, causing the item to disappear after it was copied from there into the player's inventory.
I suspect that the reason the stores were setting the cursor in the first place was to populate the …

Remove calls to NewCursor() from store functions

---

Source/inv.cpp
Source/inv.h
Source/msg.cpp

Similar to the issue mentioned in #4274, dropping items on the ground causes the hold item to lose its item type. In this case, the game tries to use the hold item in the handler for the `CMD_PUTITEM` network message, but the cursor was cleared in the previous frame when generating the network message.
Of course, the game only uses the hold item on the local client because remote clients would not have access to that data. Instead, remote clients must recreate the item using the item information included in the network message, which was copied from the hold item when generating the network message. The idea behind this change is to go ahead and recreate the item on the local client as well instead of abusing the hold item as swap space.

Don't use HoldItem in CMD_PUTITEM handler

---

Source/cursor.cpp

The hourglass cursor should be an exception to the rule here. When the lag ends, the item cursor will be restored so the hold item is still valid.

Don't destroy hold item when setting cursor to hourglass

---

3rdParty/libzt/CMakeLists.txt

This fixes the issue where Mac players cannot play games with others on ZeroTier.

Disable LWIP_PROVIDE_ERRNO

---

Source/diablo.cpp
Source/loadsave.cpp
Source/miniwin/misc_msg.cpp
Source/qol/stash.cpp
Source/qol/stash.h

The first commit addresses a bug I introduced in #4265 and #4281 where the stash page counter can underflow allowing navigation from page 1 directly to page 50. Splitting the other helpers to a separate PR since they're independent.

Add helpers to change stash pages

---

Source/options.cpp

This constant is defined as 1 when building for iphone, 0 for MacOS, and undefined on other platforms.
fixes #4299

Use truthy test instead of ifdef for TARGET_OS_IPHONE

---

Source/utils/display.cpp

I think this is fundamentally an SDL issue.
However, I think this is fine, since the problem can be avoided by making the process the same as the options menu.
Tested on:
MacBook Pro 2017 / macOS 12.3 / Retina
Note PC / Zorin OS / Non-Retina

Fix #4251 macOS mouse grab issue

---

Source/diablo.cpp
Source/loadsave.cpp
Source/panels/spell_list.cpp
Source/player.cpp
Source/player.h

- Added 12 more QuickSpell hotkeys for a total of 16.
- Preserve compatibility with single player in LoadPlayer/SavePlayer by saving/loading only 4 hotkeys.
- The number of QuickSpells is hard coded now, but it's easy to change. The LoadHotkeys()/SaveHotkeys() functions already handles a different number of saved hotkeys by reading/writing the number of hotkeys at the beginning of the "hotkeys" file.
Note: when loading older save files, the LoadHotkeys() function will read offset data/garbage, in my tests this doesn't cause problems, but I might just have been lucky, this probably needs some more testing.

More QuickSpell Hotkeys

---

Source/control.cpp

Correctly center panel text when holding red item

---

Source/error.cpp

`message` was unused in `DrawDiabloMsg()`, only one use in `InitNextLines()` so inlined the call there.

Remove unnecessary string copies in error.cpp

---

Source/monster.cpp

Fixes #3869
Notes
- When a monster hits (`MonsterAttackPlayer`) first reflect is calculated. Reflect can kill a monster (`CheckReflect` -> `M_StartKill` -> `StartMonsterDeath`).
- After this thorn (`Attacker takes x Damage`) is calculated. Thorn can also kill a monster (`M_StartKill` -> `StartMonsterDeath`).
- If reflect already killed the monster (and set it's hp to less then 1). Then thorn also adds damage, sees the monster has hp less then 1 and also triggers the kill. When this happens we have the double kill.
- This is not specific to Na-Krul. It can happen with any monster.

Ensure Reflect + Thorn don't kill a monster twice

---

Source/controls/modifier_hints.cpp

Source/spells.h:53:14: runtime error: shift exponent -1 is negative
Fixes #4319

Fix a negative shift exponent sanitizer warning

---

Source/engine/render/text_render.cpp
Source/engine/render/text_render.hpp
Source/utils/utf8.cpp
Source/utils/utf8.hpp

A few warnings were being generated about potentially truncating conversions in this function and `DecodeFirstUtf8CodePoint()`. Consistently use `std::size_t` for calls relating to a string length or offset to address downcast warnings. Also changed the types for dealing with a pixel width to unsigned, given kerning is 8 bits and spacing is int this was giving potential overflow warnings.

Address type conversion warnings in WordWrapString

---

Source/diablo.cpp
Source/diablo.h
Source/gamemenu.cpp
Source/gamemenu.h

This partially implements #4181 but only for systems where NOEXIT is set. This should avoid at least some confusion for users that are unsure how to get back to the main menu from the game menu.

Make 'quit game' return to the main menu when NOEXIT is set

---

Source/controls/controller_motion.cpp
Source/controls/devices/kbcontroller.cpp
Source/controls/devices/kbcontroller.h
Source/controls/game_controls.cpp

Also fixes build with `HAS_KBCTRL=1`
Fixes #1977

Fix modifier + D-Pad triggering a D-Pad event

---

Source/monster.cpp
Source/monster.h

This restores Diablo to his original HP values of 833 for single player and 1666 for multiplayer in non-Hellfire games.
This resolves #4043
---
It was discovered by @ikonomov and reported on Discord that there are a couple places in the code where Diablo's HP is arbitrarily reduced by 2000 when it seemingly should have instead been reduced by half in `InitMonsterGFX()` and `PrintMonstHistory()`. These code blocks can be traced back to f05ae4c which doesn't really provide much context about where they came from. From what I can tell, it seems like a math error so that was my assumption when making these changes.
Note that the error by itself didn't actually modify Diablo's HP, which was still hardcoded in `InitMonster()` at the time. Eventually, the hardcoded logic was replaced in #1486. …

Fix Diablo's HP

---

Source/textdat.cpp
Translations/bg.po
Translations/cs.po
Translations/da.po
Translations/de.po
Translations/devilutionx.pot
Translations/el.po
Translations/es.po
Translations/fr.po
Translations/hr.po
Translations/it.po
Translations/ja.po
Translations/ko.po
Translations/pl.po
Translations/pt_BR.po
Translations/ro.po
Translations/ru.po
Translations/sv.po
Translations/uk.po
Translations/zh_CN.po
Translations/zh_TW.po

Fixes a typo in "Journal: The tirade"
A tab instead of space meant that this was rendered as "arefull"

Fix a typo in Hellfire book text

---

Source/pfile.cpp

Fixes #4356 for me.
Please verify again. I'm not mpq expert and perhaps I miss something 😉 
I could reproduce/test the issue with a empty data dir (no previous stash) and saving in singleplayer with the following modified code:
```cpp
void sfile_write_stash()
{
//if (!Stash.dirty)
//	return;
for (int i = 0; i < 4; i++) {
if (!StashWriter.Open(GetStashSavePath().c_str()))
app_fatal("%s", _("Failed to open stash archive for writing.").c_str());
SaveStash();
StashWriter.Close(false);
if (i % 2 != 0)
gbIsMultiplayer = !gbIsMultiplayer;
else
gbIsHellfire = !gbIsHellfire;
}
Stash.dirty = false;
}
```

clearTables when closing stash mpq

---

Packaging/windows/devilutionx.exe.manifest
Packaging/windows/devilutionx.rc

The resource file needs to reference the manifest file, and the manifest file had some errors.
This resolves #4358

Fix application manifest in MinGW builds

---

.circleci/config.yml
CMakeLists.txt
Source/init.cpp
Source/main.cpp
Source/platform/switch/CMakeLists.txt
Source/platform/switch/romfs.cpp
Source/platform/switch/romfs.hpp

Packs devilutionx.mpq into the nro so it won't have to be distributed separately.
Tested with Ryujinx.
Note that we will probably encounter issues similar to 3DS and MacOSX if the user has a leftover version of devilutionx.mpq on their SD card.

Use romfs on Switch for devilutionx.mpq

---

Source/controls/controller_motion.cpp
Source/controls/controller_motion.h
Source/controls/game_controls.cpp
Source/controls/game_controls.h
Source/controls/modifier_hints.cpp
Source/controls/plrctrls.cpp
Source/controls/plrctrls.h
Source/miniwin/misc_msg.cpp

1. Do not interrupt mouse mode on virtual clicks.
2. Handle virtual clicks directly instead of sending an SDL event.
3. Fix D-Pad mouse emulation state handling.
4. Hides the modifier hints during D-Pad mouse emulation.
Fixes #4369
@jimmiejoe, can you please check if this helps with #4368?

Controller mouse emulation fixes

---

CMake/platforms/ctr/modules/FindCITRO3D.cmake

Reported by @pionere (https://github.com/diasurgical/devilutionX/commit/0976278fb44a6c8abb8506481a79d89e78c980e0#r70871345)
Fixes the variable name in `FindCITRO3D.cmake` so that build environments which use `CMAKE_FIND_ROOT_PATH` will be able to locate Citro3D.

Fix variable name in FindCITRO3D.cmake

---

Source/controls/controller.cpp

Hat state is a collection of flags indicating which combination of directions is currently pressed. We only receive events when the hat state changes and we only generate button events if the corresponding flag is set for the hat direction. Therefore, this change just assumes the event indicates the button was pressed. For a more complete solution, we'd have to save state from the previous hat event so we can detect transitions that would indicate d-pad buttons were released.
This resolves #4368

Only query jbutton state for button events

---

Source/diablo.cpp
Source/qol/chatlog.cpp

This was necessary in the past due to stippled transparency but we use blended transparency now.
Fixes #4355

Don't hide the automap in Help and Chat Log

---

3rdParty/SDL2/CMakeLists.txt

SDL2 2.0.22 has just been released
We previously updated SDL2 only a week ago https://github.com/diasurgical/devilutionX/pull/4232

Update vendored SDL2 to latest upstream

---

Source/engine/assets.cpp
Source/init.cpp
Source/utils/paths.cpp
Source/utils/paths.h

Fixes #4007
Removes `MpqDir` as it's not very reliable (see #4375) and always uses `PrefPath` instead.
Another alternative to discuss. 😉

Remove MpqDir and use PrefPath instead.

---

Source/controls/plrctrls.cpp
Source/inv.cpp
Source/inv.h
Source/player.cpp
test/inv_test.cpp

When quick casting from gamepad, update the cursor position so the player can quick cast spells in front of them without targeting a player or monster.
When quick casting from staff charges and scrolls, these are now explicitly validated using the spell that was cast rather than `Player::_pRSpell`.
This resolves #4269

Quick cast fixes

---

Source/utils/display.cpp

How about the nuclear option? Inspiration taken from the OpenGL renderer.
Given how d3d11 essentially "poisons" the window so other renderers can't use it, I don't see how the d3d11 renderer and the Upscale option can coexist without this. I expect this should also allow us to use the default renderer instead of setting the render hint.
I'm not sure if recreating the window will actually solve the original issue in #3706 as I don't have Windows 11. Therefore, it would be helpful if someone who is able to reproduce that issue could test this. If we can't wait for that, it shouldn't hurt to go ahead and unconditionally set the render hint to request d3d11.
This resolves #3806

[Windows] Recreate the whole window if the renderer would otherwise freeze

---

Source/inv.cpp
Source/inv.h
Source/msg.cpp

This basically reverts #4276, but introduces a new variable to take the place of `Player::HoldItem` to be used when processing the message locally. This only requires space for one item if you assume that the player won't be able to drop multiple items in one frame. If we want to support dropping more than one item in one frame, we'd have to use something like `std::deque<Item>`.
This resolves #4386

Avoid recreating items in PutItem locally

---

android-project/app/src/main/java/org/diasurgical/devilutionx/DataActivity.java

Previously only the shareware download would trigger the download-compleate logic.
Since Russians will now get kicked to the data screen after upgrading while it was fetching the dub in the background, this needed to be adjusted so that they would automatically be returned to the game once the data transfer is complete (to avoid to much confusion).
Note: It looks like Polish/Chinese/Japanese/Korean users who downloaded the demo would have to manually trigger the game launch after the shareware finished downloading.

[android] Automatically start game after updating translations 

---

Source/controls/devices/joystick.cpp

Stops the game from crashing when using L2/left-trigger or R2/right-trigger on a gamepad mapped using the Joystick API.

Enable use of L2/R2 on joystick

---

Source/controls/menu_controls.cpp

Holding the `A` button down when skipping the intro video will skip straight to the character select screen for Single Player. I've often been inadvertently skipping the main menu on 3DS because of this. It also seemed like this was making it difficult to change the language selection on 3DS. This PR prevents all that behavior.

Do not process held events for action buttons in main menu

---

Source/diablo.cpp
Source/effects.cpp

We were previously setting `was_sound_init` to true unconditionally after calling `snd_init`.
However, `snd_init` can fail. Use `gbSndInited` instead.

Fix snd_deinit called even if snd_init failed

---

Source/engine/render/cel_render.cpp
Source/engine/render/cl2_render.cpp

This OOB happened when rendering a sprite outline where the sprite it is exactly off-screen (touching the border but not visible) on top/bottom while also being only partly off-screen on the left or right.
Fixes #4405

Fix an OOB in CEL/CL2 outline rendering

---

Source/controls/controller.cpp
Source/controls/controller.h
Source/controls/devices/joystick.h
Source/controls/game_controls.cpp
Source/controls/game_controls.h
Source/controls/input.h
Source/controls/menu_controls.cpp
Source/controls/plrctrls.cpp
Source/controls/plrctrls.h
Source/cursor.cpp
Source/miniwin/misc_msg.cpp
Source/track.cpp
Source/track.h

This reverts a large part of https://github.com/diasurgical/devilutionX/pull/4019 and instead reuses the mouse's logic for repeating the last action.
Fixes #4406
This still doesn't add the logic to the touch interface, but that should be relatively trivial at this point I think.

[gamepad] Reuse repeat logic from mouse

---

Source/controls/controller.cpp

Follow-up to https://github.com/diasurgical/devilutionX/pull/4414, which removed the `state` field.

Fix OpenDingux/RetroFW builds

---

Source/inv.cpp

It _should_ be this simple, but the original logic had a lot of branches so it's not really clear. Since this is just a cleanup, I would recommend pushing this to 1.5.0, unless someone feels significantly more confident about this than I do.

Clean up logic for 1-handed weapons in CheckInvPaste()

---

Source/DiabloUI/diabloui.cpp
Source/hwcursor.cpp

Set the palette at load time.
Since we only support hardware cursors in SDL2, we can take advantage of its reference-counted palettes.

Hardware cursor: Simplify initialization

---

Source/engine/size.hpp
Source/qol/stash.cpp

Cleaned up the logic for `FindSlotUnderCursor` while I was at it, the code was difficult to read and ended up being simple to express entirely in `CheckStashPaste` instead.

Remove use of SetICursor and related globals from CheckStashPaste

---

Source/controls/plrctrls.cpp

Be explicit about the cursor overlap checks when acting on inventory cells instead of relying on side-effects from the last NewCursor call.

Use explicit item/cursor size in PerformPrimaryAction

---

Source/inv.cpp

Also use mod for testing if item dimensions are even. Lets assume the release build can optimise this into a bitmask, probably wont need to do this anyway after a refactor.
It'd be real nice to use `Point` instead of `i, j` in this function however that's a massive effort given the way the inventory grid is structured. Future work if anyone is keen :D

Use GetInventorySize(Item) instead of SetICursor in inv.cpp

---

3rdParty/SDL_audiolib/CMakeLists.txt
Source/options.cpp
Source/sound_defs.hpp
Source/storm/storm_svid.cpp
Source/utils/aulib.hpp
Source/utils/soundsample.cpp

Speex resampler appears to have some issues (see the spectrograms in https://github.com/diasurgical/devilutionX/issues/1390#issuecomment-1100204992)
Use the new SDL_audiolib's native SDL resampler where available (SDL 2.0.7+).

Audio: Use SDL resampler where available

---

Source/spells.cpp

I don't think this ever comes up because no spells have an sManaCost of 255, however _pMaxManaBase is stored as fixed point, so it should be shifted before use.
But to be honest, I'm not even sure what it is trying to do here. Was sManaCost == 255 supposed to indicate that it was going to use all the player's mana? Why was it cast to a BYTE before using it? Did they intend to limit the manage usage to 255 and just screwed up? I originally saw this logic in Devilution, and found it because the Middle Earth mod had a slight change here, where it used pMana (maybe because they thought it was intended to be a spell that used all the player's mana?) Also, I saw that in 1.07, Ghidra saw `ma` as a byte, not an int as written in Devilution - I wonder if that's where the cast came from? In the ME …

GetManaAmount - fix usage of pMaxManaBase

---

Source/controls/plrctrls.cpp
Source/cursor.cpp
Source/cursor.h
Source/inv.cpp
test/cursor_test.cpp

Removes the last uses of the icursSize variables, and removes a fair chunk of duplicated code. A lot of the cursor positioning stuff appears to be because InvRect points aren't quite aligned to the actual position of the grid in the panel? The multiple uses of that array make it hard to change at the moment so gonna leave that for later.

Simplify logic when moving around the inventory with a controller

---

Source/DiabloUI/selgame.cpp

Selecting a public game would skip `gfnHeroInfo(UpdateHeroLevel)`, meaning that the game would sometimes mistakenly deny or permit entry into a Nightmare or Hell difficulty game based on whatever happened to be stored in that variable before.

Fix player level validation when joining ZT public games

---

Source/DiabloUI/selhero.cpp

Fixes a crash when clicking in a specific region on the hero selection menu.
The viewport size for the `UiList` was hardcoded to 6, meaning that the calculated size of that list was too large for the actual number of entries if you have fewer than 5 characters.
This resolves #4441

Fix viewport size of UiList on hero selection

---

Source/encrypt.cpp

explode() and implode() both have comments saying they expect the buffers to be zero-init, however new[] default initialises arrays which for char[] leaves them in an implementation defined state. On MSVC the memory is unitialised. To be safe use std::make_unique<T[]>(size_t) as this value-initialises each element of the array.

Ensure working buffers are zero-initialised for PKWareLib

---

Source/qol/stash.cpp

This adds a bit of audible feedback to help the player know that the action had an impact (along with the cursor changing and the count increasing).

Play gold sound effect when depositing in stash

---

Source/control.cpp
Source/controls/plrctrls.cpp
Source/controls/touch/event_handlers.cpp
Source/controls/touch/renderers.cpp
Source/cursor.cpp
Source/cursor.h
Source/debug.cpp
Source/diablo.cpp
Source/hwcursor.cpp
Source/inv.cpp
Source/miniwin/misc_msg.cpp
Source/player.cpp
Source/qol/stash.cpp
Source/scrollrt.cpp
Source/towners.cpp
test/cursor_test.cpp

This cleans up a bit of code and solves a few edge cases where an item
could be lost, the game be unresponsive, or miss fire an event during
lag cause of the cursor not reflecting the currently held item.
Depends on:
- https://github.com/diasurgical/devilutionX/pull/4304
- https://github.com/diasurgical/devilutionX/pull/4306
- https://github.com/diasurgical/devilutionX/pull/4308
- https://github.com/diasurgical/devilutionX/pull/4309
- https://github.com/diasurgical/devilutionX/pull/4310

Use HoldItem for determining if an item is held

---

Source/control.cpp
Source/cursor.cpp
Source/cursor.h
Source/inv.cpp
Source/qol/stash.cpp

The motivation for this was to allow setting the cursor directly from the held item after doing actions which could either swap the held item with another item or leave the held item empty. Ends up letting CheckInvPaste get simplified a fair bit (but splitting that into a separate PR as it blows out the line count).

Add NewCursor(Item&) for setting the cursor based on a held item

---

Source/inv.cpp
Source/inv.h
Source/msg.cpp

When auto-placing gold in the inventory there's no need to trample HoldItem.

Only use HoldItem in InvGetItem if necessary

---

Source/controls/plrctrls.cpp
Source/cursor.cpp
Source/inv.cpp
Source/inv.h
Source/items.cpp
Source/items.h
Source/loadsave.cpp
Source/pack.cpp
Source/player.cpp
Source/qol/stash.cpp
Source/stores.cpp
test/inv_test.cpp

Adds "shorthand" for resetting item when the space is going to be reused in the future. It does end up being a function call but every compiler should be able to inline this... I hope. If the amiga builds move to a more modern gcc this could use `constexpr` to be sure.
This becomes more useful with #4482. The `cn` variable can be removed from CheckInvPaste, then `SwapItem` can be fully inlined so it's just a call to `std::swap`.

Add helper to clear/quick-init an item

---

Source/cpp.hint
Source/items.h
Source/utils/attributes.h

Makes clang (and GCC) consider item.Clear() a reinitialisation of a moved variable - see https://clang.llvm.org/extra/clang-tidy/checks/bugprone-use-after-move.html#reinitialization
The cpp.hint file is something that MSVC/Visual Studio use to provide better intellisense hints. It needs to be in a parent directory of the file which uses the macro (not where it's defined). It only really needs to indicate whether a macro starts/ends a block, the contents of decorators like DVL_API_FOR_TEST doesn't actually matter in that file.

Add hint to avoid bugprone-use-after-move warnings

---

Source/controls/plrctrls.cpp
Source/inv.cpp
Source/items.h
Source/player.cpp
Source/qol/stash.cpp

Used when moving from one persistent variable to another where we want the old variable to be marked empty. Defining as a function instead of move constructor/assignment operator as we only really need to mark the source for xvalues. Detecting that in the constructor/assignment would be needlessly complicated.

Add helper for moving an item

---

Source/.clang-tidy
Source/control.cpp
Source/controls/plrctrls.cpp
Source/controls/touch/renderers.cpp
Source/cursor.cpp
Source/inv.cpp
Source/items.cpp
Source/items.h
Source/loadsave.cpp
Source/msg.cpp
Source/pack.cpp
Source/panels/spell_list.cpp
Source/player.cpp
Source/qol/stash.cpp
Source/stores.cpp
test/inv_test.cpp

Previously this was falling back to FunctionCase, leading to inconsistent casing of class methods throughout the codebase. Applied to Item as an example.
Using camelCase from the discussion in #4493 - https://github.com/diasurgical/devilutionX/pull/4493#discussion_r853613509

Set clang-tidy config for MethodCase option

---

Source/diablo.cpp
Source/msg.cpp
Source/msg.h

Workaround for #2681
Notes:
- This implements the [mentioned](https://github.com/diasurgical/devilutionX/issues/2681#issuecomment-932789249) workaround:
>Avoid sending multiple network messages in RepeatMouseAction (for one game tick).
- When the player should take a new action the logic checks if this command was the last sent action in this game ticks. If yes this is a redundant action and can be discarded. This helps to reduce the impact of #2681 significantly. For a detailed analysis see #2681.
- For local players this shouldn't make a difference, cause game ticks and network messages are always aligned.
- The logic is implemented in the `NetSendCmd` functions to work with normal clicks, repeated mouse actions, touch and gamepads.
- Hopefully this workaround can be removed in future …

Throttle send player commands to avoid desyncs

---

Source/engine/demomode.cpp

Found (while rebasing #2526) that the current (later replaced) demomode doesn't work anymore.
The reason is that `ControlMode` is never set, cause the demomode has a special message handling (`demo::FetchMessage` vs `FetchMessage_Real`).
Note: `ControlMode` can't change while playing the current format and the current format only supports mouse+keyboard. The new format hopefully doesn't even have to bother about this sort of difference. 😉

Demomode: Init ControlMode to KeyboardAndMouse

---

Source/DiabloUI/selhero.cpp
Source/DiabloUI/ui_item.h

Fixes a crash that occurs when clicking in a specific region on `UiList` elements that are made larger than their contents by resizing them automatically based on their contents.
Based on the following suggestion: https://github.com/diasurgical/devilutionX/pull/4510#discussion_r857054873
Alternative to #4510
This resolves #4476

Fix viewport size of UiList in constructor

---

Source/menu.cpp
Source/multi.cpp

When starting the game from scratch, going straight through the Single Player menus to play a new single player hero would cause potions in the player's belt to appear unusable.
More generally, the hero save data was being loaded into `Players[MyPlayerId]` before `InitSingle()` had the opportunity to set `MyPlayerId = 0` and `MyPlayer = Players[MyPlayerId]`. As a result, `CalcPlrInv()` was being called while `MyPlayer == nullptr` so it skips over the logic to set `_iStatFlag`. However, this issue actually causes an even more egregious error that requires a bit more setup, but could absolutely be stumbled on by accident.
1. Delete all single player heroes
2. Create two new single player heroes, making sure to remember which hero you created first
3. Join a multiplayer game in which you are …

Fix order of operations when reading from Single Player save

---

Source/utils/language.cpp

There is a missing conversion.
Tested on powerpc64 Linux (CPU: e5500) and powerpc MorphOS (CPU: G4).

Fix loading tranlations on big endian platforms

---

Source/controls/touch/renderers.cpp

Recent changes to frame indexes mixed up the graphics for the virtual gamepad a bit.
Before:
After:

Fix item graphics on potion buttons for virtual gamepad

---

Source/multi.cpp

This change rejects `PT_MESSAGE` packets from players that have not yet sent a valid player info packet to the local client. This prevents situations where an unannounced player can send `PT_MESSAGE` packets to other players, affecting their game without them knowing the rogue client was present.
The conditions for player validation were lifted from `UnpackPlayer()` because it's used by `recv_plrinfo()` to decode the player info data sent by the remote client. In addition, we also validate the player's name against empty string since this was recently confirmed to cause issues.
A new function was added to time out players that do not send their player info within 15 seconds of joining a game session. This prevents potentially malicious players from lurking in games for extended periods of …

Validate remote players in multiplayer games

---

Source/controls/plrctrls.cpp
Source/diablo.cpp
Source/inv.cpp
Source/inv.h

The way TryInvPut and DropItemBeforeTrig interacted was fragile, don't think this would've worked as expected at the best of times. Looks like it was added as part of controller support so guessing this isn't vanilla behaviour anyway.

Refactor TryDropItem to reduce use of globals

---

Source/stores.cpp

As pointed out by @StephenCWills, Diablo/Devilution included randomization of the store seed during setup, which may have  been removed to make the stores load the same items when loading a game in single player. This just adds randomization when setting up the stores only for multiplayer games.
Devilution code:
https://github.com/diasurgical/devilution/blob/f074a33cc13a87f2cd3e05ca3844ab3f659589c1/Source/stores.cpp#L108

Restore randomization of stores for multiplayer games

---

Source/diablo.cpp

@ikonomov reported on Discord that quick messages in the INI do not populate at startup. It seems the `sgOptions.Chat.szHotKeyMsgs` options are populated by `DiabloInit()`. This moves the call to `SaveOptions()` after the initialization functions so that any options initialized by these functions will be captured in the INI at startup.

Initialize options before first call to SaveOptions()

---

Source/monster.cpp
Source/qol/monhealthbar.cpp

This handles some hp/hp bar stuff
1. fixes vanilla bug where monsters could reach HP within a single regen tick above their max (was necessary because monsters regenerating over their max would show as having more than 1 health bar with this PR which was obviously not the goal)
2. fixes devx hp bar - it was inaccurate earlier because of using wrong width - was showing full bar when monster actually had 95% HP
3. People usually thought something was broken when Leo stole hp from them and they damaged him and his HP bar didn't budge - this solves the issue by borrowing the "boss hp bar" mechanic from some games - a number appears saying how many hp bars the boss actually has.
Recolored extra health bars blue

HP bar tweaks and fixes

---

Source/scrollrt.cpp

Resolves https://github.com/diasurgical/devilutionX/issues/4524
```cpp
const Displacement center { CalculateWidth2(player.AnimInfo.celSprite ? player.AnimInfo.celSprite->Width() : 96), 0 };
```
This part got moved to DrawPlayer already and removed from DrawPlayerHelper but not from DrawDeadPlayer which executed it twice while drawing a dead player.

fix displacement on death

---

Source/platform/locale.cpp

Subsumes https://github.com/diasurgical/devilutionX/pull/4485/
Upon next release, install instructions can be simplified since the is no longer a need to create diablo.ini with preferred language before first lunch.

ps4: avoid using std::locale to detect language, and fallback to en

---

Source/multi.cpp

Follow-up to address comments in #4500.
When joining a game, the game sets `gbBufferMsgs = 1` to indicate that `PT_MESSAGE` packets which are not deltas should be placed in a buffer to be processed later once all deltas have been received. If `CMD_ACK_PLRINFO` ends up getting buffered, the remote player's info won't be processed until all deltas are received, but deltas will be rejected because the player's info is still invalid. This means the joining player will be stuck on the loading screen.
This PR assumes that a client which is buffering packets must be joining a game and waiting for deltas so it should be safe to implicitly trust all incoming `PT_MESSAGE` packets until buffering is complete.

Accept all PT_MESSAGE packets when buffering messages

---

Source/DiabloUI/selhero.cpp
Source/diablo.cpp

Just for the sake of consistency. 🤷 
EDIT: I originally thought this might have caused `seedinfo` to report zeroes, but it seems that was something else entirely. So this change probably doesn't fix anything.

Use ifdef when checking for _DEBUG

---

Source/controls/touch/gamepad.cpp
Source/diablo.cpp
Source/diablo.h
Source/options.cpp
Source/platform/switch/docking.cpp
Source/utils/display.cpp
Source/utils/display.h

This variable is controlled/set by the code in that file, this also lets other files have more specific/relevant includes instead of the monolith that is diablo.h

Move definition of ghMainWnd to utils/display.cpp

---

Source/platform/switch/docking.cpp

Hopefully makes it a bit clearer to read. ~Also looks like the diablo.h include was unnecessary which seemed to be causing failing builds occasionally.~ Turns out the whole reason I ended up looking at this was based on a dodgy assumption 😂 . Moving that to a different PR.

Use enum instead of int as bool in Switch docking logic

---

Source/quests.cpp

This is a rather fun one: once you receive the Laz quest and go back down to level 15, the quest state is set to 3. When entering Laz's chamber it increases once you pop the seals and again after Laz finishes speaking. No problem right?
Well the devs didn't consider that you can portal out of Laz's chamber; and then walk back down to level 15 again, which sets the quest state back to 3. Going through the red portal would put you on the teleport pad thus fixing the quest state, but if you go back to town and through the original town portal instead, the dungeon will reset back to its initial state.

Vanilla bug: Fix Lazarus quest level resetting

---

Source/multi.cpp

Fixes the issue where the player character's name is erased upon entering a game.
Recent screenshots from Discord user myself600 have basically confirmed that the logic in `PlayerLeftMsg()` is the cause of this bug. You can see in the following screenshot where the game indicates that Eileen (myself600's character) left the game before stating that Hillstorm is already in the game, after which myself600's messages indicate that his character's name is now blank.
I am still completely unable to reproduce this issue, but this evidence strongly suggests that this change should resolve it.

Ignore leave requests if the player leaving is the local player

---

Source/objects.cpp

Resolves an issue reported by FireIceTalon on Discord.
> In hell, every barrel im breaking drops a small red potion.
> It’s happened 2 games in a row.
> I think the game treats them as dupes, when i go to town and come back down all but one are gone.
> I assume u can recreate with any class, on any difficulty, on any dungeon level that has barrels.

Pass object by reference to AddBarrel()

---

Source/diablo.cpp
Source/utils/console.cpp
Source/utils/console.h
Source/utils/sdl2_to_1_2_backports.cpp
Translations/bg.po
Translations/cs.po
Translations/da.po
Translations/de.po
Translations/devilutionx.pot
Translations/el.po
Translations/es.po
Translations/fr.po
Translations/hr.po
Translations/it.po
Translations/ja.po
Translations/ko.po
Translations/pl.po
Translations/pt_BR.po
Translations/ro.po
Translations/ru.po
Translations/sv.po
Translations/uk.po
Translations/zh_CN.po
Translations/zh_TW.po

Also print `\r\n` instead of `\n` on Windows.
This paves the way forward for returning a `string_view` from `_(...)`.

printInConsole: Add string_view support

---

Source/objects.cpp

Fixes an issue reported by NickGavran on Discord.
> ![image](https://user-images.githubusercontent.com/9203145/168406641-3b70507b-dee8-426b-9d1c-b0e79999e707.png)
> Is it normal that the halls of the blind can spawn with torches on its walls? Asking about vanilla and about devilx (Screenshot 
> was taken from a random stream I stumbled upon playing Devilx) 
> These torches are not there in the .dun file
> Watching several vanilla playthroughs of this, they do not produce any torches whatsoever 
The condition seems to have been mistakenly flipped by 099fad5.

Fix condition for set pieces in AddL2Torches()

---

Source/debug.cpp
Source/debug.h
Source/objects.cpp
Source/objects.h
Source/setmaps.cpp

Load a custom level `map path type x y`. Example `map Levels\L3Data\Foulwatr 3 31 83` will load the poison water level with the cave tiles and spawn position of 31x83
`map levels\l1data\vile1 6 35 36` will load you in to Lazarus' chamber but using the Crypt theme (partially compatible as it is based on Cathedral)
`map levels\l1data\vile1 4 35 36` also just for fun, Lazarus' chamber with Hell tiles
`map Levels\L3Data\Foulwatr 5 31 83` Poison water with the Hive tiles:
(note that loading a level with the incorrect theme is likely to result in crashes)
`map Levels\L1Data\Lv1MazeB 1 20 50` loads the unused maze level:
Be aware that you need to start a new/reload game between loading each level as else the game will try to transfer object and monster states from the previous level you had …

Add debug command for testing custom levels

---

Source/stores.cpp

Cursed items (with an item value of 0) will not be added to the list of items by AddStoreHoldRepair. This results in a situation where a player can try repair a null/invalid item because StartSmithRepair doesn't realise that no items are available to be repaired.
fixes #4575

Use the count of store items instead of repairOk flag

---

Source/inv.cpp

fixes #4326 
I haven't touched the logic that auto-places items while the inventory is closed since nothing there plays sounds currently. This is only to bring gold in line with other items as noted in the linked issue.

Provide sound cue when gold is auto-placed into the open inventory

---

Source/inv.cpp

If multiple items of the same type are on the belt and one is consumed, then the one further down the belt is used.  This change is in tandem with the AutoRefillBelt from inventory feature.  It's purpose is to reduce the amount of hunting for the correct hotkey on the belt so that items can be used hitting the same key.  It may help address the shock of no more potions available 
https://github.com/diasurgical/devilutionX/pull/983#issuecomment-765237425
Consider the case where the belt is full of full healing potion and the inventory is now out.  Player uses belt slot1, causing slot 8 to be used. Player can notice belt depleting, but can keep finger near the same hotkey, instead of hitting slot1 only to notice too late that it's empty.

slide belt items down when consumed

---

.github/workflows/Linux_x86_64_test.yml

Doesn't appear to be active by default? Maybe this is why the reports weren't being uploaded

Enable gcov support in codecov uploader

---

Source/engine/random.cpp

`abs(INT_MIN)` is [undefined behavior](https://en.cppreference.com/w/c/numeric/math/abs), so process this case without calling `abs()`
This problem manifestates itself on FreeBSD with clang 11.0 by breaking `QuestTest.SinglePlayerBadPools` and `RandomTest.ShiftModDistributionSignCarry`

Fix UB in random generator

---

Source/automap.cpp
Source/control.cpp
Source/control.h
Source/cursor.cpp
Source/diablo.cpp
Source/items.cpp
Source/player.cpp
Source/plrmsg.cpp
Source/qol/itemlabels.cpp
Source/qol/monhealthbar.cpp
Source/scrollrt.cpp

First commit fixes #4584
Second commit is a refactoring that should make future panels (inspect player) more easy to add.
The refactoring doesn't include the `controls` folder (touch and gamepad), cause I didn't want to refactor something that I didn't test. If someone is willing to test it, I can also change this part.

Fix item label text with open stash

---

Source/automap.cpp
Source/control.cpp
Source/controls/plrctrls.cpp
Source/diablo.cpp
Source/diablo.h
Source/lighting.cpp
Source/missiles.cpp
Source/msg.cpp
Source/msg.h
Source/multi.cpp
Source/pack.h
Source/player.cpp
Source/player.h
Source/track.cpp

- Manage friendly mode per player and sync state between clients
- Don't show hostile players in automap and don't share automap view
- Show hostile players red in talk panel. In master muted players are shown red. This pr changes the behavior.
https://user-images.githubusercontent.com/25415264/169593464-ef7605fb-9307-4227-8424-c4be9b9f2e5b.mp4

Don't show hostile players in automap and color there player name in talk panel

---

Source/monster.cpp

- This fixes a bug where Spiderlords would not leave behind an acid puddle when killed by monsters.
- Cleans up redundant logic by moving it to a shared function.
- Don't take short cuts when calculating the proper heading for the death animation

Monster death

---

android-project/app/build.gradle
android-project/build.gradle
android-project/gradle/wrapper/gradle-wrapper.properties

All changes were at recommendation of Android Studio, and were playtested on Pixel 2, Android 10
* Upgrade Gradle plugin version to 7.2.0, release notes: https://developer.android.com/studio/releases/gradle-plugin#7-2-0
* Upgrade Gradle to 7.4.2, release notes: https://docs.gradle.org/7.4.2/release-notes.html
* Upgrade `compileSdkVersion` and `targetSdkVersion` to 32 to coincide with Android 12L feature drop: https://developer.android.com/about/versions/12/12L

Upgrade Android build tool and target SDK versions

---

Source/DiabloUI/progress.cpp

Fixes an issue where the "Waiting for game data" dialog was not appearing when joining a game.
The issue was introduced by 52e0511. It seems we were (perhaps incorrectly) relying on the fact that this dialog was blitting directly to the output surface. This modifies the rendering loop to use `UiFadeIn()` instead of `RenderPresent()` like nearly all other UI rendering loops in the codebase.

Blit UI surface to game surface when waiting for game data

---

Source/missiles.cpp

Fixes #1679
Instead of using the current caster location, we can use the missiles start position to calculate if an explosion is blocked (for example by a wall).

Fireball/Elemental: Make explosion calculation line of sight independent

---

Source/engine/render/dun_render.cpp
Source/gendung.cpp

Only consider the relevant flags for block_lvid, and use it as a flag instead of integer values.

Cleanup block_lvid checks

---

Source/monster.cpp

Fix for bug introduced in https://github.com/diasurgical/devilutionX/commit/417c4c9ce23e99475f366450b4274a9f0ab30b81
Sorry for that mistake.
Golems, and Berserkered monsters swing without hit.
Problem was negation (!) in `isPossibleToHit` , but I just returned early in this PR.

fix for monster melee hit monster

---

Source/missiles.cpp

The multiplication by `1 << 21` was unnecessary, with the way the division is performed it doesn't add precision. Missile velocities are 16 bit fixed values so split out the normalisation step in order to make it clearer what the multiplication and use of `v` ends up doing.

Document/simplify the UpdateMissileVelocity logic

---

Source/missiles.cpp

Currently casting a guardian crashes the game, cause the fire check for the guardian access `Monsters` array with negative index.
A monster index check is missing.
Missed this when reviewing #4602 sorry. 😞
Thanks Constantine for reporting. 🙂

Fix GuardianTryFireAt missing monster index check

---

Source/dthread.cpp

Prevents crashes that can occur in the game's menus when receiving `PT_DISCONNECT` packets from other clients. This would be most commonly seen when receiving a late `PT_DISCONNECT` from a party member after defeating Diablo or in the situation described in #4626.

Check if dthread is running before locking mutex

---

Source/DiabloUI/selgame.cpp

When the game list refreshes, the cursor stays on the currently selected item by remembering the index of that item. However, when a game is added to the list, the indexes of all games after it are shifted by one. If another game is added to the list before the currently selected game, the selected game will spontaneously change. This code searches the game list for a game with the same name so that the selection is less likely to change when the list is refreshed.
This also includes some additional validation on `HighlightedItem` to ensure that it does not go out of bounds if the list shrinks. This should avoid crashes that can occur in the menu due to race conditions when a player cancels a join request while waiting for game data.

Improve refresh behavior in selgame

---

Source/dvlnet/base.cpp

ZeroTier code checks `plr_self != PLR_BROADCAST` when handling `PT_INFO_REQUEST` packets. Because `plr_self` isn't reset after leaving a game session, the client would continue sending `PT_INFO_REPLY` packets in response to requests so long as the player stayed in the ZeroTier menu. Game clients in this state would even handle `PT_JOIN_REQUEST` packets as normal, causing the remote player to end up in the progress dialog indefinitely while waiting for game data. If the remote client then cancels the progress dialog, it would trigger a `PT_DISCONNECT` packet which could either crash the game or cause the issue described in #4546.
This will likely help to resolve some of the crashes we've seen on Android.

Stop transmitting game info after leaving game

---

Source/options.cpp

Resolves an issue (introduced by #4544) where all keymapper settings, as well as a handful of other settings in various categories, were selecting the Boolean overload for `SetIniValue()` because they were not explicitly using the `string_view` type to represent section name, key name, and value.
I'm not sure if this is the best approach, but modifying all overloads to use `string_view` instead of `const char *` didn't seem to solve the problem so this is the best I could come up with. I guess C++ considers `bool` a better match for `const char *` than `string_view`, at least in MSVC.

Reintroduce c-str overload for SetIniValue()

---

Source/control.cpp

Only the top button uses a different graphic because the demon statue's wing overlaps the button. So only the middle and bottom buttons would attempt to use the last frame of the CEL, which is the depressed mute button.
It's really hard to tell what's going on with the CEL because we draw over the buttons so they can be translated. It's easiest to see if you focus on the part of the button that overlaps with the wing.
This resolves #4608

Use 0-based frame index for talk buttons

---

Source/engine/displacement.hpp
Source/missiles.cpp
test/math_test.cpp

The missile velocity calculation was bugging me, these helpers hopefully describe what the math is doing and also potentially allow changing the implementation (if we want to do it entirely in fixed point on platforms without an FPU for example).

Additional helpers for converting between world/screen space for missiles

---

Source/inv.cpp
Source/inv.h
Source/inv_iterators.hpp
Source/monster.cpp
Source/objects.cpp
Source/player.cpp
Source/player.h
Source/spells.cpp
Source/towners.cpp
test/inv_test.cpp

Introduces new functions to check for presence of and remove player items.
These functions do not rely on or expose item indices.
They're implemented as free functions instead of Player methods due to complicated include dependencies between `player.h`, `inv.h`, and `inv_iterators.h`. We should probably look into cleaning this up at some point.
Also fixes #4583 -- the mushroom quest potion check

Refactor inventory/belt item presence and removal

---

Packaging/ctr/template.rsf

Would suggest on using 3DS homebrew logo instead to avoid copyright infringement.

3DS use homebrew logo

---

Source/monster.cpp

This PR is proposition to fix bug that makes berserked melee monsters attacking other melee monsters do not wake up when hit.
Bug is also in original Hellfire.
Consider situation: Player cast berserserk on hidden-type behind the wall (which is always active), and that hidden starts to kill every monster behind the wall without waking them up.
It can be abused even with non-hidden ones - just put them at the room door (like with stone curse) and open door with telekinesis - and he will clear all room :)
But for sure hidden ones are the easiest to abuse.
Only ranged monsters will see golems and berserked monsters from far away and react immediately.
Melee monsters won't even wake up.
Fix wakes up melee monsters that are succesful hit.
You may consider to change it to other moment - like on …

[Original Hellfire bug] Fix for Berserked monsters hit don't wake up other meele monsters

---

Source/items.cpp
Source/loadsave.cpp
Source/msg.cpp
Source/pack.cpp
Source/player.cpp
Source/sync.cpp

For ears, store the player's name in the `_iIName` field of the `Item` struct so that the name data can be reliably copied regardless of how translations modify the phrase "Ear of PlayerName".
This resolves #4641

Fix issues with ears due to translation

---

Source/inv.cpp
Source/inv.h
Source/inv_iterators.hpp

Per clang-tidy config
Also fixes `RemoveBeltItemById` (follow-up to #4661)

Rename `inv_iterators` methods to `camelCase`

---

Source/controls/touch/renderers.cpp

Fixes the icon on the secondary action button when hovering over scrolls of Town Portal, Teleport, and Guardian.
This resolves #4505

Correctly indicate when scroll can be used on virtual gamepad

---

Source/objdat.cpp

Fixes an issue reported by Discord user ZeroContrast where the candles in front of Poisoned Water Supply had shown up as perpetually exploding barrels. Here is the savegame provided on Discord: [single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/8873313/single_0.sv.zip). The following is a video they shared that showcases the perpetually exploding barrels.
https://user-images.githubusercontent.com/9203145/172928707-d9a8e327-5f8a-44ee-a61e-a0aa381cd369.mp4
FYI, if you load the savegame on master and go straight to dlvl 2 (`changelevel 2`), the game will attempt to render a null CEL buffer and the candles simply won't show up. If you go through dlvl 1 instead, you probably still will not see the exploding barrels, but the game may crash because it will load some garbage into …

Load OFILE_CANDLE2 when the Poisoned Water Supply quest is available

---

Source/drlg_l4.cpp

Pushing an option then immediately popping it doesn't do much :D

Remove no-op GCC pragma instructions

---

Source/drlg_l4.cpp
test/drlg_l4_test.cpp

So that the function is more similar to other dungeon generation versions, and so that it's not doing unnecessary work.
This only applies to singleplayer so I didn't add to the multiplayer dlvl15 test.

Move Betrayer bugfix out of PlaceMiniSet

---

Source/spells.cpp

Fixes an OOB memory access that occurs when a spell has three missiles associated with it.
If the situation occurs, the MinGW build would raise an access violation exception that crashes the game. This was discovered in the ME mod when players tried to cast the "Thunder" spell. DevilutionX doesn't have any spells that would trigger this exception, but the logic here is clearly backwards so it may as well be fixed.

Fix order of loop conditions when adding spell missiles

---

Packaging/OpenDingux/build.sh

Saves 108 bytes in the binary size

OpenDingux: `strip` `.comment` and `.gnu.version`

---

Source/DiabloUI/progress.cpp
Source/interfac.cpp
Source/utils/display.cpp
Source/utils/display.h

Frees the background after blitting it once in the loading screen.
This gives the game more RAM for the actual loading.

Loading screen: Free the background early

---

3rdParty/libmpq/CMakeLists.txt

Includes https://github.com/diasurgical/libmpq/pull/5
> This introduces a 195 KiB cost to peak memory usage but greatly reduces temporary allocations during decompression.
>
> Before:
> ![libmpq-before](https://user-images.githubusercontent.com/216339/173821254-0fa0c656-dbc7-4ea6-a5d4-775a27252783.png)
>
> After:
> ![libmpq-after](https://user-images.githubusercontent.com/216339/173821274-bd4975b5-207c-4900-8617-d747afe62499.png)

Bump libmpq

---

Source/drlg_l1.cpp
Source/drlg_l2.cpp
Source/drlg_l3.cpp
Source/drlg_l4.cpp
Source/gendung.cpp
Source/gendung.h
Source/setmaps.cpp
Source/town.cpp

I think I managed to keep the change set relatively clean this time :cold_sweat: 
This also saves 2K of ram during most of the level generation which I'm sure @glebm will appreciate :D
One possible down side here is that it will load the .dun file for each attempt at generating a valid level.

Clean up how DRLG_L1 quest elements are placed

---

Source/drlg_l1.cpp
Source/drlg_l1.h
Source/drlg_l2.cpp
Source/drlg_l2.h
Source/drlg_l3.cpp
Source/drlg_l3.h
Source/drlg_l4.cpp
Source/drlg_l4.h
Source/gendung.cpp
Source/gendung.h
Source/lighting.h
Source/setmaps.cpp
test/drlg_l1_test.cpp

I'm not super happy about the relation of `LoadDungeonBase()` here, but it is still well worth it for the the amount of duplicate code that it replaces.
Fun fact, none of the original levels have the transparency info in the correct file, which is why `SetMapTransparency()` still exists.

Move shared dungeon level code to common function

---

Source/DiabloUI/diabloui.cpp
Source/miniwin/misc_msg.cpp
Source/platform/locale.cpp
Source/utils/utf8.cpp
Source/utils/utf8.hpp
test/CMakeLists.txt
test/utf8_test.cpp

1. The C++ `std::locale("")` constructor performs static initialization of all the facets on the first call.
For example, this includes things like currency formatting.
Avoid all of that by using the equivalent C locale call.
2. Replaces the deprecated `<codecvt>` machinery with a simple UTF-8 encoding function.

Remove uses of `<locale>`

---

Source/gendung.cpp
Source/town.cpp

Fixes wrong lightning with new created town level:
Town doesn't support lightning.
Regressed with 6fa681e5675cdee7c8dbf34cc328d53c4a511cfb
Before `dLight` was initialized with 0 (in `CreateTown`):
`memset(dLight, 0, sizeof(dLight));`
In master `dLight` is initialized with 15 (in `InitGlobals`):
`memset(dLight, DisableLighting ? 0 : 15, sizeof(dLight));`

Fix: Disable lightning in town

---

Source/monster.cpp

`PlaceUniqueMonsters` places unique monsters that are not active on the level (isnt preset in `LevelMonsterTypes`); and doesn't place unique monsters that are active on the level.
This results in a crash in `InitMonster` cause `MData` is not initialized.
Regressed with 4d6ff58c22b2195afc10e1072ec417b013241242

Fix PlaceUniqueMonsters when unique monster type is not active on the level

---

Source/monster.cpp

Regressed with 4d6ff58c22b2195afc10e1072ec417b013241242
Didn't spot this one in #4729
Only results in a crash, if last monstertype on the level supports the uniques that is placed.
the `!done` condition was moved in the for-loop condition.
This is nicer but has a side-effect, cause the increment logic (`mt++`) of the for loop happens [before](https://en.cppreference.com/w/cpp/language/for) the for-condition is tested (`mt < LevelMonsterTypeCount && !done`).
That means's `mt` is increased one more time, even if `done` is true.

Fix PlaceUniqueMonsters off by one monstertype

---

Source/control.cpp
Source/inv.cpp
Source/items.cpp
Source/panels/charpanel.cpp
Source/qol/itemlabels.cpp
Source/qol/stash.cpp
Source/qol/xpbar.cpp
Source/stores.cpp
Source/utils/format_int.hpp
Translations/bg.po
Translations/cs.po
Translations/da.po
Translations/de.po
Translations/devilutionx.pot
Translations/el.po
Translations/es.po
Translations/fr.po
Translations/hr.po
Translations/it.po
Translations/ja.po
Translations/ko.po
Translations/pl.po
Translations/pt_BR.po
Translations/ro.po
Translations/ru.po
Translations/sv.po
Translations/uk.po
Translations/zh_CN.po
Translations/zh_TW.po

With the introduction of the stash, players can hoard huge amounts of gold. The total amount of gold can become illegible in the absence of decimal separators.

Use decimal separators for gold and XP

---

Source/DiabloUI/diabloui.cpp
Source/DiabloUI/diabloui.h
Source/platform/locale.cpp
Source/utils/utf8.hpp
test/utf8_test.cpp

Now that I've been able to confirm this isn't causing #4723 might as well get some eyes on it 😂 
The use of `std::string` for `tempName` isn't necessary, this could be reverted to use a char array and CopyUtf8 again with a bit of boilerplate to then wrap it in a string view. Didn't feel it was worth avoiding the heap allocation but I can change this if there's a strong preference to put it back on the stack.
Edit: Oh hey, thanks to GCC6 I have to wrap std::string in a string_view to be able to use `find(string_view)` anyway 🙃

Use string_view for UiValidPlayerName

---

Source/dvlnet/frame_queue.cpp
Source/dvlnet/packet.cpp
Source/dvlnet/packet.h
Source/utils/attributes.h
Source/utils/log.hpp

Fixes the build with `-fno-rtti` and `-fno-exceptions`.
Building with these flags reduces the binary size by more than 200 KiB.

Fix build with NONET and no exceptions

---

Source/control.cpp
Source/control.h
Source/controls/plrctrls.cpp
Source/engine/points_in_rectangle_range.hpp
Source/inv.cpp
Source/items.cpp
Source/panels/spell_book.cpp
Source/qol/monhealthbar.cpp
Source/qol/stash.cpp
Source/scrollrt.cpp
Source/stores.cpp
Source/utils/display.cpp

Also extracted repeated redefinitions of the PointInRectangleRangeIterator to a common constexpr variable in stash.cpp. There are two uses in plrctrls.cpp that I didn't think were worth adding cruft to the stash.h header to support, maybe those functions can move into stash.cpp in the future?

Define sizes using Size type in control.cpp/stash.cpp

---

Source/debug.cpp
Source/diablo.cpp
Source/engine/render/dun_render.cpp
Source/gendung.cpp
Source/gendung.h
Source/lighting.cpp
Source/missiles.cpp
Source/monster.cpp
Source/objects.cpp
Source/path.cpp
Source/scrollrt.cpp
Source/themes.cpp
test/path_test.cpp

This also fixes some tiles along the walls in Hell incorrectly being marked as solid.
@glebm could you check memory usage in game before and after this PR, would be interesting to see if you prediction of ~40KiB holds true :)
Examples of tiles that are incorrectly marked as solid:
A good follow up to this would be to change dPiece to be zero-indexed so that the additional check and math isn't needed in the rest of the code. Doing so would require applying tile 218 as the default in town instead of 0.

Operate directly on SOL data

---

Source/diablo.cpp
Source/gendung.cpp
Source/gendung.h
Source/objects.cpp
Source/scrollrt.cpp
Source/town.cpp

So turned out that not only does reducing indexing MICROS by dPiece reduce the table size from 392KiB to 43KiB, it also means that the .min data is only needed at load time, saving an additional 9-44KiB (depending on the level). And as a bonus it remove the need to recompute the table as the level changes.
I also moved the call to `SetDungeonMicros()` before the call to `LoadLvlGFX()` to reduce peak memory usage.
DPieceMicros could be removed from runtime if SetDungeonMicros() instead computed a new CEL where the tiles are not split in to smaller chunks (see `DrawCell()`).
Doing so should also mean that we can drop much of the specialized render code and probably result in better CEL compression and render performance. But I feel this might be a bit more then I am able to do.
... also …

Index Minis by tile instead of by coordinate

---

Source/interfac.cpp

These files are lowercase when in a bundled filesystem.

Fix wide-screen background paths

---

Source/DiabloUI/selhero.cpp

Fixes #4723
The problem appeared when we started rendering backgrounds directly as PCX (it was OK before as we were reusing the same `ArtBackground` object)

Fix heap-use-after in hero selection

---

Source/DiabloUI/button.cpp
Source/DiabloUI/diabloui.cpp
Source/DiabloUI/settingsmenu.cpp
Source/engine/rectangle.hpp
Source/panels/spell_book.cpp
Source/utils/sdl_geometry.h

Please note there are three behaviour differences included in this PR.
UiEdit text drawing regions now have their vertical dimension shrunk by 2 pixels. I don't think this matters in practice as when text overflows the clip region bounds it doesn't actually get clipped.
Similarly, spell book descriptions have a vertical dimension applied to their clip area now meaning they shouldn't overflow into the area for the next spell description. They still will because of clip regions not being true clip regions (unless the font size lines up reasonably well).
The last column of pixels of the last spell book tab buttons (for both Diablo and Hellfire) is now included in the hit area. The detection for buttons 3 and 4 in Diablo has been adjusted to match the alignment changes applied in …

Add helpers for creating/using Rectangles in UI contexts

---

test/utf8_test.cpp

Most of the loops didn't risk overflow no matter what the underlying type of char is, the one that did is easy to reverse.

Restructure test conditions to avoid tautology warnings

---

Source/quests.cpp

Before https://github.com/diasurgical/devilutionX/pull/4698 the quest state was modified when spawning the portal to the unholy altar, I thought this was unused as the logic checking the triggers appeared to be looking at the portal position, but that was probably a wrong assumption 😂 
Haven't had time to test this actually works though, hoping Sieg can give it a shot? You'll need a save that hasn't advanced the quest to this stage yet.

Restore change to trigger position when advancing betrayer quest

---

Source/controls/plrctrls.cpp
Source/monster.cpp
Source/path.cpp
Source/path.h
Source/platform/locale.cpp
Source/player.cpp
Source/player.h
appveyor.yml
test/path_test.cpp
test/player_test.cpp
test/writehero_test.cpp

Reduces the size of the `PathNodes` array from 28 KiB to just 8 KiB.
Also reduces the size of `pnode_tblptr` from `300 * sizeof(void *)` to `300 * 2` bytes.

Make path finding index-based

---

CMakeLists.txt
test/animationinfo_test.cpp

Turns out gc-sections helps significantly even with LTO (-84 KiB for the MinSizeRel rg99 build).
Also adds options for disabling RTTI and exceptions.

CMake: gc-sections + no-rtti/exceptions options

---

Source/controls/plrctrls.cpp
Source/diablo.cpp
Source/inv.cpp
Source/inv.h

fixes #4763
Instead of using a function that only checks 6 or 7 tiles, extract the logic that checks all 9 tiles around a starting position which is used when dropping items and use it consistently.

Use the same function when checking and actually dropping an item

---

Source/drlg_l3.cpp
Source/engine/size.hpp
Source/gendung.cpp
Source/gendung.h
Source/objects.cpp

This was part of an attempt at a wider cleanup of the way theme room dimensions are set, pulling this out to make the future PR(s) smaller.
There's a lot of places where a theme room dimension is adjusted by some amount, a lot of these seem to be compensating for/undoing previous adjustments. Hoping that can be simplified throughout.

Rename SkipThemeRoom, use theme room attributes in PlaceThemeRoom

---

Source/stores.cpp
Source/stores.h

1. Reduces the sizes of variables in `STextStruct`.
2. `char[128]` -> `std::string`

Reduces `stext` static memory use (16K -> 4K)

---

Source/monster.cpp

- makes function check fear affected area tiles only instead of every monster in `ActiveMonsters`
- run distance based on Intelligence Factor instead of fallen type
to makes things equal to vanilla - adjusted for Carver with spear, which intelligenceFactor is higher than usual monster type streak (0,1,2,3) and is 2 instead of expected 1
as bonus - fixed fallen retreat direction bug introduced in https://github.com/diasurgical/devilutionX/pull/2354/commits/4c578c537843c7c9adb011941e0262b3d19ece56
now they will run properly away from killed monster

M_FallenFear refactor

---

Source/interfac.cpp

When dying in multiplayer quest/set maps and then using "Restart in town" the `setlevel` is not set correctly.
Discovered while working on quest and arena support.

Fix "Restart in Town" when dying on a quest/set map

---

Source/debug.cpp

When accessing a quest map with debug commands, the level where the quest can be entered is loaded first (so ReturnPosition is set).
But this is not needed if we are already on the dungeon level.

DebugCmdLoadQuestMap: Don't load entry quest lvl if the hero is already on this level

---

Source/msg.cpp

When `setlevel` is true, the correct level to use is `setlvlnum` not `currlevel`.
One step further for enabling singleplayer quests in multiplayer.

Fix automap not saved in multiplayer quest/set-maps

---

Source/monster.cpp

FallenFear retreat distance based on level
Previously (#4785) based on IntelligenceFactor would be off for Pukerat the Unclean and Bongo. (Thanks @AJenbo for noticing).
And this one is cleaner too.

FallenFear retreat distance based on level

---

Source/pfile.cpp

Call the destructor and closing the save file before reading from it.
Was introduced with #4688

Fix pfile_compare_hero_demo: Close MpqWriter before reading (for comparsion)

---

Source/msg.cpp

Found while testing singleplayer betrayer quest for multiplayer.

IsValidLevelForMultiplayer: Fix last set level is wrongly assumed as invalid

---

Source/inv.cpp
Source/monster.cpp

This also fixes a bug introduced in part 1, where `PlaceUniqueMonsters` uses a monster type that is off by 1.

Reduce reliance on `bool done` for control flow, part 2 of x

---

Source/engine/demomode.cpp

This makes the demo recording smaller and git doesn't recognize it as a text file 😉  (see [comment](https://github.com/diasurgical/devilutionX/pull/2490#discussion_r895181404))
Note:
- The format will change (see #2733).
- That's why I didn't try to make it endian safe for now.
- Perhaps we could later use a abstraction to write binary that is used in demo recording and loadsave. But one step at a time.

Use binaryformat for demofile

---

Source/missiles.cpp
Source/monster.cpp
Source/monster.h

I encountered an issue regarding when `pnum` can be `-1` in `MonsterMHit()`, turns out this can only happen the the case of the fire ring trap in Hellfire, because it's a trap but the logic in `CheckMissileCol()` assumes it to be fired by a player.
Solving allows us to remove the check for `-1` to determiner what should be triggered on hit, removing the need for some type juggling in #4754
In fixing this I also fixed a couple of other issues with missiles hitting monsters:
Monster unable to shoot a non-golem monster #4669
Monsters/traps can be unable to hit Petrified monsters (vanilla).
Ring of Fire traps do not damage monsters (hellfire).

Fix traps and monsters hitting monsters

---

Source/objects.cpp

The pnum is known at the same time as sendflag, so we can simply use that early on in stead of passing the check on to the end function. This gives a nice reduction in parameters and comparisons.

Clean up Operate Door

---

Source/msg.cpp
Source/objects.cpp
Source/objects.h

This splits the delta loading of objects from network sync of events and thus removes most usages of the `deltaload` global. It is still being used a bit in the door logic, but cleaning that up is a task in it self (something I'm working on in #4571) and doesn't directly contribute to to landing #4754 so I have left that out for now. The same goes for cleaning up `OperateShrine()`, since a lot of the bool logic is no longer needed there either.
The changes here lets us know that pnum will always be a valid player id which simplifies som logic.

Split delta sync from realtime sync

---

Source/objects.cpp

With `deltaload` out of the way we can now simplify the conditions in `OperateShrine()` and also clean the sub-function by taking the player by reference, by moving the stat calculations to the relevant shrines instead of always running them.
Additionally only close the gold dialog if the shrine is unused.

Clean up OperateShrine

---

Source/options.cpp
Source/options.h
Source/qol/itemlabels.cpp

Makes it so controller and mobile can have item labels on. Also convenient for not having to press right control every time you start the game.
Screenshot on iPhone which previously was very annoying to enable

show item labels toggle in menu

---

Source/diablo.cpp
Source/interfac.cpp

Loading the game from within the game calls `IncProgress` multiple times but we should not render the progress bar when that happens.
Fixes #4821

`IncProgress`: Do not render bar if not active

---

Source/diablo.cpp
Source/loadsave.cpp

This PR should
- fix delete player radius after kill berserked monster in singleplayer games. (fix https://github.com/diasurgical/devilutionX/issues/3166) 
- still fix https://github.com/diasurgical/devilutionX/issues/1588 
In the same time you may not be happy because it makes https://github.com/diasurgical/devilutionX/issues/1588 still occur (only 32 places for lights...)
Reproduce:
1. Save singleplayer dungeon level with berserked monster.
2. Quit Game
3. Run Game
4. Load SinglePlayer dungeon level with berserked monster.
There problem is already on load.
- It was introduced in https://github.com/diasurgical/devilutionX/pull/3121
To see it "in work":
5. Kill berserked monster (light id 0 will be deleted thanks to https://github.com/diasurgical/devilutionX/pull/3120 )
6. Wander around …

Berserk light fix

---

Source/levels/town.cpp

Hello,
I noticed that the town boundaries were a bit weird:
So I did a git bisect and I found that the issue was introduced at 4cc3a5264ce75511163081ee9372ca4f7fd1c1cc, this is how it was before:
I am not sure if the change was intentional or not, but I looked into the tiles and I found that 426 is a black tile, it looks like the original:

:bug: fix town boundaries

---

Source/dead.cpp
Source/debug.cpp
Source/effects.cpp
Source/engine/render/scrollrt.cpp
Source/monster.cpp
Source/monster.h
Source/msg.cpp
Source/multi.cpp
Source/player.cpp
Source/sync.cpp

Changed defines in files monster.cpp and monster.h to be constinit const int instead. Fixed some typos along the way. Changed passing the reference to the first element of an array to simply passing the array itself or its underlying data in the InitMonsterGFX.
Removing defines is good practice in modern C++. Other changes simplify code, or fix language errors in the comments.

Monster global constants cleanup

---

Source/DiabloUI/diabloui.cpp
Source/DiabloUI/diabloui.h
Source/DiabloUI/title.cpp

1. There is no small logo. Simply use 2 variables instead of an array with an enum.
2. The medium logo is much smaller as PCX:
* Hellfire (`ui_art\hf_logo2.pcx`): 1,591,816 bytes -> 195,850 bytes
* Diablo (`ui_art\smlogo.pcx`): 341,923 bytes -> 333,099 bytes

DiabloUI: Clean up logo handling

---

CMakeLists.txt
docs/CONTRIBUTING.md

Add clarification in CMakelists.txt regarding C++ standard, as well as add new section in CONTRIBUTING.md.
This should help to clear the confusion about which standard is being used.
The reasons behind using C++17 while setting standard to C++20 are probably not described correctly - they have been taken from Discord discussion. As such, it would be great if somebody knowing the ins and outs of standard situation could clarify this.

Clarification of C++ standard usage

---

CMake/functions/genex.cmake
CMakeLists.txt

1. Make the vcpkg hack minimal by only defining the options it needs before `include(Platforms)`.
Every dependent option needed by vcpkg has to be recalculated after `include(Platforms)`. This brings the count of such options down to 1 (`PACKET_ENCRYPTION`).
2. `include(Platforms)` before the rest of the options.
3. Group related options together into sections and add comments.
4. Fix `--gc-sections` for C files.
Note: `PIE` can now be `ON` even if `BUILD_TESTING` is `OFF`.
```
$ du -b build-rg99/devilutionx
1357720	build-rg99/devilutionx
```

CMake: Clean up option definitions

---

Source/CMakeLists.txt
Source/DiabloUI/diabloui.cpp
Source/DiabloUI/diabloui.h
Source/DiabloUI/selhero.cpp
Source/DiabloUI/ui_item.h
Source/engine/load_pcx.cpp
Source/engine/load_pcx.hpp
Source/engine/pcx_sprite.cpp
Source/engine/pcx_sprite.hpp

1. Load portraits as PCX (~30% smaller).
2. Simplify the portrait override logic.

DiabloUI: Clean up portrait loading

---

Source/engine/displacement.hpp

This doesn't trigger warnings on msvc, not sure about other compilers. Also added asserts to all functions performing rotations to match Rotate()

Avoid casting unnecessarily in worldToNormalScreen

---

Source/loadsave.cpp

clang-tidy config causes the linter to give a very helpful warning that `4*8` might overflow the range of `int` before being assigned to `size_t` 🙃 
we've got the template form of skip anyway so might as well use it.

Address int-arithmetic-overflow in loadsave.cpp

---

Source/missiles.cpp

Thanks to this change, berserking ranged monster's missiles will try to hit all monsters they will collide with, not only 1 monster that currently is on target.
This is modification of fix for #4669 introduced in #4800
(First introduced as original fix #4618 for #4669)

Missile from berserked monster try to hit every monster

---

Source/engine/render/scrollrt.cpp

Don't even need to initialise the buffer since the last update time is set when DiabloInit is called, then as long as the loading screen takes more than a second the threshold gets hit to call format_to on the first frame of gameplay.

Only call fmt::format_to when the FPS value updates

---

Source/engine/point.hpp

The `-` converts everything to unsigned if one of the operands is unsigned. Convert everything to int before calculating.
Fixes #4856

Fix `Point#*Distance` functions for unsigned types

---

Source/diablo.cpp
Source/engine/render/scrollrt.cpp
Source/missiles.cpp
Source/missiles.h
Source/msg.cpp
Source/objects.cpp
Source/objects.h
Source/player.cpp
Source/spells.cpp

Another set of cleanups to minimize the impact of https://github.com/diasurgical/devilutionX/pull/4754
Just 8 more files (84 lines) left to investigate after this one :sweat_smile: 
`TryDisarm()` was moved to player.cpp (only usage) to avoid circular references

Minimize propegation of global Players index

---

Source/engine/animationinfo.cpp
Source/engine/animationinfo.h
Source/items.cpp
Source/items.h
Source/loadsave.cpp
Source/monstdat.h
Source/monster.cpp
Source/monster.h
Source/player.cpp
Source/player.h

Fixes #4849
Notes:
- a signed type is need, cause
- since #4221 we have a zero-based animation index. That means the start value of a animation is -1 (it will increase to 0 in the same game tick where it's starts).
- in some cases the animation takes longer then we have animation frames (walking). So we could also end up with a negative index
- it's no breaking change to change the player death animation (first commit). the death animation is never stored in a save game, cause you can't save when you are dead and in multiplayer we don't save the world state.
- I changed all fields that hold a frame / tick per frame to `int8_t`, so that it's consistent over the codebase. This also reduces the size of `Player` even more.
- Reduces size of `AnimationInfo` by 16 bytes
- Reduces size of …

Change animation frames and tick per frame to int8_t

---

Source/.clang-tidy

Following the discussion in the chat

.clang-tidy: -misc-non-private-member-variables-in-classes

---

Source/control.cpp
Source/cursor.cpp
Source/dead.cpp
Source/debug.cpp
Source/engine/render/scrollrt.cpp
Source/items.cpp
Source/loadsave.cpp
Source/missiles.cpp
Source/monster.cpp
Source/monster.h
Source/msg.cpp
Source/player.cpp
Source/qol/monhealthbar.cpp
Source/quests.cpp

These pointers are redundant, replaces them with methods.
`Monster` is down to 176 bytes, `Monsters` down to 33,600 bytes.

Monster: Remove MType/MData pointers

---

Source/monster.cpp
Source/monster.h

Hello,
I was trying to figure out how to remove the `monsterId` from the `StartWalk` functions parameter but the only solution I could come up with was storing the `monsterId` inside the `Monster` struct itself.
I am not sure if this is a good approach, but I tested it on both single-player and multiplayer and looks like nothing broke.
Please let me know what you think 😄

:recycle: Stores the monsterId inside the monster struct

---

Source/automap.cpp
Source/inv.cpp
Source/monster.cpp
Source/player.cpp
Source/player.h

Both player and monster walking functions are now named WalkNorthwards, WalkSouthwards and WalkSideways.
Also renames the PLT_MODE enum to follow the same pattern and removes unnecessary comments.

Normalise the player and monster walking function naming

---

Source/DiabloUI/progress.cpp

First, this fixes an issue where `ArtBackground` is always `std::nullopt` because of a change made recently in diabloui.cpp.
https://github.com/diasurgical/devilutionX/blob/98a2fc53c9b99f8fcf8f85560f13cb019689f8bd/Source/DiabloUI/diabloui.cpp#L683-L684
Instead of checking for the existence of `ArtBackground`, I simply removed the code because `ProgressLoadBackground()` explicitly calls `UiLoadBlackBackground()` so there should never be any background to render here.
---
Second, the `ArtPopupSm` and `ArtProgBG` graphics have white and green areas that were not being rendered before the change to render backgrounds as PCX.
Since `RenderPcxSprite()` does not accept a width or height to exclude these regions, I referenced code that renders the filled-in progress bar in …

Fix errors rendering progress dialog

---

Source/multi.cpp
Source/player.cpp
Source/player.h

Unless someone fixes `RemovePlrFromMap()` then this may well be the last prep for https://github.com/diasurgical/devilutionX/pull/4754, once rebased I will change the remaining pnum from int to size_t to avoid the remaning static_casting.

Take player by reference in StartWalkStand and RemovePlrMissiles

---

Source/player.cpp

With this #2490 works again.
The following line overflows:
```cpp
player.position.offset2 = dirModeParams.offset * 256;
```
`ActorPosition::offset2` is defined as `int16_t`

Make DirectionSettings::offset match ActorPosition::offset2

---

.github/workflows/Windows_x64.yml

Will upload artifacts from every windows master build to https://github.com/artifacts-storage/devilutionx-artifacts
Should be pretty useful for bisecting in the future as builds take a pretty long time and after 1.4.0 a lot of them failed locally for me 
zip takes 9.45 mb, max github repo size is 10gb = artifacts from ~1k commits, let's worry about the limit when we get there :D
I've split exe and all other data - zip with exe takes 2.35mb, other data (DLLs, devilutionx.mpq, licenses) rarely changes so it shouldn't take much = we good for 4k commits? :D

upload windows artifacts to second repo

---

.github/workflows/Windows_x64.yml

Since there doesn't seem to be any limit on releases, this should be the best way atm :D (Thx @Trihedraf for the idea)
https://github.com/artifacts-storage/devilutionx-artifacts
The question is if we want to also have linux artifacts (if yes, I'll push it into this PR so we have both windows and linux artifacts from the same moment)

artifacts as releases

---

Source/loadsave.cpp

Remove assert to check if value is in bounds in NextLENarrow. The behaviour now is to fallback to either minimum or maximum a type can hold (it was there before, as std::clamp is used. It was not possible for clamp to fallback to min/max, since the assert to prevent this was present).
This fixes issue  #4871. It potentially will fix other issues with older saves, in case where a variable ranged has been changed between versions - the save will load and fallback per std::clamp.
The fallback to min/max means that variables may get unexpected values assigned - always valid though. I didn't see a case where it could break things, but such possibility exists. Nonetheless, this change will allow older saves alike to the one in issue #4871 load - and then maybe break.

Remove assert to check if value is in bounds in NextLENarrow.

---

Source/engine/animationinfo.cpp
Source/engine/animationinfo.h
Source/loadsave.cpp
Source/monster.cpp

When `MFLAG_ALLOW_SPECIAL` was set on a monster, the `tickCounterOfCurrentFrame` was increased but nothing more.
`MFLAG_ALLOW_SPECIAL` is set, when
- a the gargoyle sits on the ground
- or a mega (winged demon) sits on the ground and casts inferno
Both are specified to stop the animation from advancing.
The logic [exists in vanilla](https://github.com/diasurgical/devilution/blob/b86b8fd7c4966385e3a7dbcb29e6d7e05bdab95e/Source/monster.cpp#L5663).
This could result in overflowing the `tickCounterOfCurrentFrame` (for gargoyles, for mega the duration is too short).
With this pr `tickCounterOfCurrentFrame` isn't blindly increased anymore.
The logic is simplified by using the same approach as petrified.
Notes
- Backwards compatibility: A `tickCounterOfCurrentFrame` > `ticksPerFrame` is no …

Avoid overflow of tickCounterOfCurrentFrame

---

3rdParty/SDL_audiolib/CMakeLists.txt
3rdParty/libmpq/CMakeLists.txt
Source/levels/drlg_l2.cpp
Source/mpq/mpq_writer.cpp
Source/objects.cpp
Source/qol/chatlog.cpp
Source/restrict.cpp
Source/utils/attributes.h

The fixes from https://github.com/diasurgical/devilutionX/pull/4838 that are not specific to NXDK
Extract into a separate PR that can be merged first to make it easier to review #4838

Various non-Xbox-specific fixes from xbox-nxdk branch

---

Packaging/apple/Info.plist

On macOS/iOS, the text returned by the system will be localized.
https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleallowmixedlocalizations
Before:
After:

Localize the wording returned by the system on macOS/iOS.

---

Source/lighting.h

Fixes #4910 
To be strictly equivalent to vanilla behaviour we need to check the corner tiles of a radius 19 search area. This isn't really critical to any behaviour though so in the initial implementation I let FindClosestValidPosition continue to pretty much the entire dungeon area to ensure we at least cover the same search space eventually. Crawl can do the same thing, using larger radiuses is perfectly acceptable.

Remove unnecessary assert

---

Source/levels/drlg_l1.cpp
Source/levels/drlg_l2.cpp
Source/levels/drlg_l2.h
Source/levels/drlg_l3.cpp
Source/levels/drlg_l4.cpp
Source/levels/gendung.cpp
Source/levels/gendung.h

`L4dungeon[80][80]`, `L5dungeon[80][80]`, and `dung[20][20]` have been combined in to `Bitset2d<40, 40>DungeonMask` as they all served to generate a boolean layout at the start of the level generation. `dung` was used to generate a quarter and then copy it to `L4dungeon`, instead this now happens directly in `DungeonMask` which sped things up a bit as well. The same was the case with `L5dungeon`, but here `dungeon` was used as the temp buffer. Previously this lead me to think that walls where being added at this stage, which was incorrect.
Both `L4dungeon` and `L5dungeon` where upscaled to 2x the dungeon and then down sampled with an offset to determiner what side of the wall the tile prepresents. But this would be done cleaner by simply probing the next tile when scanning.
Also reuse …

Clean up initial room generation

---

Source/options.cpp
Source/options.h
Source/utils/language.cpp
Source/utils/language.h

1. Store all key data and all values data as 2 char arrays.
2. Change map keys to char pointers.
3. Change map values to offsets into the values array.
Example savings for Russian: 460 KiB -> 374.2 KiB (-85.8 KiB)
* Map: 68.5 KiB (with `string_view` keys it would be 101.5 KiB)
* Keys array: 108.7 KiB
* Values array: 197.0 KiB

Optimize translation RAM usage

---

Source/monster.cpp
Source/monster.h
Source/sync.cpp

- :fire: Removed DumbWalk
- :truck: Renames M_WalkDir to Walk
This integrates the DirOK check into M_WalkDir itself, that makes the DumbWalk function useless and most places that were calling DirOK before M_WalkDir can now be simplified.

:recycle: Refactor M_WalkDir

---

Source/player.cpp

Uses `gbIsHellfire` to restore vanilla Diablo behavior when using elemental damage on weapons in DevilutionX Diablo. This prevents the crash described in #4655 but does not fully resolve the issue in Hellfire. Rather, it's meant to be minimally invasive for inclusion in 1.4.1.

Restore vanilla Diablo behavior for elemental damage on weapons

---

Source/levels/drlg_l4.cpp
Source/player.cpp

One I missed and one introduced/moved in one of the GenerateRoom refactors.
targetHead is not negated as I flipped the cases in #4913 but somehow lost the actual change to the function...

Include leftover coinflips following conflict resolution

---

Source/levels/gendung.cpp

My brain is mush after looking at this code. It looks like it was intended to look for the largest/most balanced rectangular region within a given search area, but due to a weird way of picking when to use a particular bound it ended up getting smaller areas than strictly necessary if there were choices where both dimensions are over the minimum bound.
There's probably a way to make this even more straightforward but I have given up thought for today 😂 
The following are a few search spaces I dumped out so I could see what the old logic was doing and confirm this rewrite worked the same.
```
INFO: DebugCmd: changelevel 10 Result: Welcome to level 10.
DEBUG: +++++#####
DEBUG: +++++#####
DEBUG: +++++##-##
DEBUG: +++++--###
DEBUG: +++++--###
DEBUG: #-------##
DEBUG: ##------##
DEBUG: …
```

Simplify loops in WillThemeRoomFit, rename to match use

---

Source/monster.cpp
Source/multi.cpp
Source/player.cpp
Source/player.h

Untested, not sure if there's still situations where player positions can get so out of sync in multiplayer games that a player disconnecting leaves an invalid index in `dPlayers`

Take Player reference in FixPlrWalkTags

---

Source/engine/world_tile.hpp
Source/lighting.cpp
Source/lighting.h
Source/missiles.cpp

Opening this to highlight the odd targeting Guardians use more than anything. If we're happy to change behaviour this can be made way simpler by using `FindClosestValidPosition` instead of having guardians search for targets from far to near. Based off #4843 since it was the last remaining use of VisionCrawlTable outside of lighting.cpp

Pull distinct points from VisionCrawlTable used by guardians

---

Source/loadsave.cpp
Source/player.cpp

This resolves an issue where position desync when walking north would cause the player's position to warp out of bounds, leading to disconnects in multiplayer games. This also fixes some errors in loadsave.cpp related to the type change from `Point` to `PointOf<WorldTileCoord>`.

Use absolute coordinates for temp position when north-walking

---

Source/control.cpp
Source/controls/plrctrls.cpp
Source/cursor.cpp
Source/debug.cpp
Source/diablo.cpp
Source/engine/render/scrollrt.cpp
Source/inv.cpp
Source/items.cpp
Source/items.h
Source/loadsave.cpp
Source/missiles.cpp
Source/monster.cpp
Source/msg.cpp
Source/multi.cpp
Source/objects.cpp
Source/panels/spell_book.cpp
Source/panels/spell_list.cpp
Source/player.cpp
Source/player.h
Source/qol/autopickup.cpp
Source/spells.cpp
Source/spells.h
Source/stores.cpp

With https://github.com/diasurgical/devilutionX/commit/1fb45a7f2548663294fe6e6996963033e6c70407 solved it unlocked a few more methods to take the player by reference rather then as an ID.
It looks like the rest are pretty much tied up in needing the player ID, we can solve that the same way we did for monsters, but I think this is a good place to cut this PR. I also changed comparisons from `playerId == MyPlayerId` when the function already had the player pointer since this will also simplify https://github.com/diasurgical/devilutionX/pull/4754

Take player by references

---

Source/controls/game_controls.cpp
Source/cursor.cpp
Source/diablo.cpp
Source/diablo.h
Source/engine/render/scrollrt.cpp
Source/options.cpp
Source/options.h
Source/player.cpp
Source/qol/itemlabels.cpp
test/scrollrt_test.cpp

Replaces #4432 
This makes zoom a toggle in the menu and does it like #4509 did for the item labels. 
Also I flipped all the zoom flags to make the toggle be true for zoomed and false for not.

Make zoom a setting in the menu

---

.github/workflows/xbox_one.yml

`upload-artifact` preserves the least common ancestor of the directory tree but we actually want the zip file to be flat.

Fix Xbox One/Series CI build

---

Source/levels/gendung.cpp

This was a corner case where a boundary was determined by the edge of the search region. Not 100% sure it's correct in all cases, aiming to add some tests to try cover every possible case.
Fixes #4957 and doesn't break existing tests however the cases in the last loop could be expressed better for sure.

Fix incorrect size determination in GetSizeForThemeRoom

---

.github/workflows/opendingux_release.yml

We previously couldn't because Github Actions didn't have Ubuntu 22.04, which has the required version of libc, but GitHub Actions does have Ubuntu 22 now.
A shot in the dark to try to fix #4953

Update OpenDingux toolchains

---

.github/workflows/Windows_MinGW_x64.yml

When updating master in a fork, the github action `Windows MinGW x64` always fails in the following step;
> Upload artifacts as release in storage repo
In a fork this step shouldn't execute.
Fix: Only try to upload artifacts when running the github action in the diasurgical/devilutionX github repro.

Only upload artifacts to sotrage repo in diasurgical org

---

Packaging/OpenDingux/build.sh

The latest OpenDingux toolchains default to the `/__w/` ccache directory due to a bug.
Set the ccache directory explicitly to work around that.

OpenDingux: Set ccache directory explicitly

---

.github/workflows/Windows_MinGW_x64.yml

This reverts commit 7612fb4bb5636f993afbad9e15fffa09e204ff89.
and adds a check if it's devilutionX main repo from https://github.com/diasurgical/devilutionX/pull/4980
Storing artifacts as releases was no bueno.

Revert "artifacts as releases (#4892)"

---

CMake/MoldLinker.cmake
CMakeLists.txt

https://github.com/rui314/mold is quite stable these days and is insanely fast.
Let's use it by default if it's there.
Linking a debug `devilutionx` binary:
GNU ld: 1.82s
Mold: 0.03s
(mold 1.3.1 [installed from source](https://github.com/rui314/mold#compile-mold) on Ubuntu 22.04)

CMake: Use the mold linker where available

---

Source/automap.cpp
Source/effects.cpp
Source/loadsave.cpp
Source/miniwin/miniwin.h
Source/monster.cpp
Source/mpq/mpq_common.hpp
Source/mpq/mpq_writer.cpp
Source/pfile.cpp
Source/utils/language.cpp

Rather than using the Windows-like `MAX_PATH`, what we really want is 2 things:
1. Maximum path of a file in an MPQ. This is now `MaxMpqPathSize`.
2. Max size for the known monster paths. This is now 64 for sounds and TRNs, which is more than enough (picked arbitrarily).

Remove `MAX_PATH`

---

Source/engine/render/scrollrt.cpp
Source/miniwin/misc_msg.cpp
Source/objects.cpp

Version 9 of libfmt deprecates printing `enum` without casting it to an integral type explicitly (consistent with `enum class`).

Fix fmt v9 deprecation warnings

---

Source/levels/gendung.cpp
Source/levels/gendung.h
test/drlg_common_test.cpp

Double scan goes from `n^2` to just `n`. Resulting in a further 13% performance boost. Hope that makes it feel a bit more ideal :)
The remaining over scan comes from both loops starting from the same diagonal coordinates.
Given the following map and a max of 10x10:
Black = floor
Red = wall
Here is the scan patterns from the original:
Blue = vertical
Orange = horizontal
Green = overlapping scans
The version in this PR instead has this pattern:

Reduce double scans in GetSizeForThemeRoom

---

Source/DiabloUI/settingsmenu.cpp
Source/control.cpp
Source/control.h
Source/controls/game_controls.cpp
Source/controls/game_controls.h
Source/controls/menu_controls.cpp
Source/diablo.cpp
Source/diablo.h
Source/engine/demomode.cpp
Source/engine/render/dun_render.cpp
Source/engine/render/scrollrt.cpp
Source/gmenu.cpp
Source/gmenu.h
Source/miniwin/misc_msg.cpp
Source/miniwin/misc_msg.h
Source/movie.cpp
Source/options.cpp
Source/options.h
Source/qol/stash.cpp
Source/qol/stash.h
Source/utils/sdl2_to_1_2_backports.h

Removes one of the 2 redundant translation layers between SDL and the game.
We do 2 things to be compatible with the demo files:
1. Keymapper still uses uppercase latin characters (SDLK_a is lowercase, so we map to uppercase there).
2. Message `wParam` is still constructed in a special way instead of simply being `SDL_GetModState()`.
Mouse buttons are mapped in the key mapper by setting the highest bit of the key to 1.
Reduces rg99 binary size by 4 KiB.

Replace `DVL_VK` virtual key codes with `SDLK`

---

Source/diablo.cpp

Accidentally changed to ALT+m from SHIFT+m in #5023

Fix next debug monster key

---

Source/automap.cpp
Source/controls/plrctrls.cpp
Source/debug.cpp
Source/diablo.cpp
Source/levels/trigs.cpp
Source/loadsave.cpp
Source/missiles.cpp
Source/monster.cpp
Source/monster.h
Source/msg.cpp
Source/multi.cpp
Source/objects.cpp
Source/objects.h
Source/player.cpp
Source/player.h
Source/quests.cpp
Source/spells.cpp
test/player_test.cpp

A fresh load of prep for https://github.com/diasurgical/devilutionX/pull/4754
From what I see we should be done in about two more :)
I moved the logic for whoHit out of `MonsterDeath()` so that it no longer needs a reference for a player. Instead that now lives in `StartMonsterDeath()`, and a check for killer being a golem in `StartDeathFromMonster()`. This does make the slight difference that previously you would only get XP from a monster if it's death blow was caused by a player/golem. Now you will get XP as long as you tagged it (this could happen if you hit a monster, and then kill it by exploding a barrel).
CMD_BREAKOBJ was changed from 2 params to just 1, since the player id is part of all network messages so I don't think there is a need for having it there twice (CMD_BREAKOBJ is …

Use user by reference

---

Source/missiles.cpp
Source/missiles.h
Source/objects.cpp

This is a follow up from the discussions on #4994
Adds the helper methods `SourcePlayer` and `SourceMonster` to the `Missile` struct.
The end goal is to replace every direct access to `_misource` with calls to `SourcePlayer` and/or `SourceMonster`
`AddFlash` already converted to use the new methods.

:recycle: Adds Missile::SourcePlayer and Missile::SourceMonster

---

Source/engine/displacement.hpp
Source/lighting.cpp
Source/lighting.h

EDIT:
There's some stuff to unpack for `DoVision`:
- It apparently never gets called for a position outside of the dungeon bounds.
- [x|y][1|2]adj act as displacements, but 1 and 2 are interchangeable, as they receive the same treatment
- If the displacement from the `VisionCrawlTable` has one coordinate equal to 0, all **adj variables are 0, and the last innermost `if` ends up looking at nCrawl[x|y]

Refactor VisionCrawlTable & friends

---

Source/missiles.cpp
Source/missiles.h

This is a precursor to removing all _misource direct access from the AddTown function.

:sparkles: Adds isSameSource Missile method

---

Source/controls/plrctrls.cpp
Source/diablo.cpp
Source/inv.cpp
Source/missiles.cpp
Source/msg.cpp
Source/msg.h
Source/track.cpp

pcursobj was used as a pointer so might as well make it an actual pointer. This also allows cleaning up some of the network messages to work off a position instead of ignoring the passed info and relying on index instead

Use cursor position for position based network messages targeting objects

---

Source/control.cpp
Source/controls/plrctrls.cpp
Source/controls/touch/renderers.cpp
Source/cursor.cpp
Source/cursor.h
Source/diablo.cpp
Source/engine/render/scrollrt.cpp
Source/inv.cpp
Source/missiles.cpp
Source/objects.cpp
Source/track.cpp

This was mainly to remove uses of `Object::GetId` but with #4987 most uses are already gone. Maybe it's still worthwhile?
It's still used for two network messages and player.destParam1, need to refactor player actions and handle loading/saving before it can be completely removed.

Use object pointer for pcursobj

---

Source/objects.cpp

Chunking up #4571 with the eventual aim of migrating OperateObject messages over to position instead of ID.
Doors are gonna be the hard part, so aiming to group the other object types into smaller more focused PRs.

Take Object by reference when operating quest objects

---

Source/msg.cpp
Source/msg.h
Source/objects.cpp

These messages are handled almost identically, the only difference is the SyncBreakObject special case function. Prep to switch object messages over to position based instead of ID based.

Dedupe operate object message handlers, use position for break object

---

Source/objects.cpp

Bit of a monolith, it is possible to split this further but the use in `MonsterCheckDoors` ties them all together so that chunk gets changed in pretty much every commit. Next step is changing `CMD_OPENDOOR` and `CMD_CLOSEDOOR` to use position instead of ID in the network message, planning that for a followup so it's easier to test and be confident doors still work.

Take references in operate door functions

---

CMake/platforms/rg350.cmake

Thanks to @pcercuei we've learned that currently enabling LTO breaks the rg350 build.
Disable it for now.
Fixes #4953

OpenDingux rg350: Disable LTO

---

.github/workflows/opendingux_release.yml

Updates to ubuntu-22.04 because ubuntu-latest (20.04) fails with:
> version `GLIBC_2.33' not found (required by /opt/lepus-toolchain/bin/mipsel-lepus-linux-musl-gcc.br_real)

OpenDingux: Fix lepus GitHub Action

---

Source/monster.cpp

- Sending the monster by reference instead of id
- Changed the golem check to be equal to StartDeathFromMonster
- Changed the order of the parameters so that the attacker comes first

:recycle: pass monster by reference on MonsterHitMonster

---

Source/objects.cpp
Source/objects.h

No real need to loop over all level objects when we already check based on position, can just use ObjectAtPosition instead.
It could also use `considerLargeObjects = false` but doors are single tile objects anyway so I don't think it's necessary, makes the call simpler.

Simplify MonsterOperateDoor

---

Source/controls/plrctrls.cpp

Fixes #5103
Berserked monsters are also flagged as `MFLAG_GOLEM`, so instead check the monster AI

[gamepad/touch] Fix targeting berserked

---

Source/controls/plrctrls.cpp
Source/cursor.cpp
Source/loadsave.cpp
Source/missiles.cpp
Source/monster.cpp
Source/monster.h

Spawned from the discussion in #5072, but relevant to the chat in discord around berserked monsters as well?
Please note I haven't captured every use of MFLAG_GOLEM and/or MT_GOLEM as some contexts I think still need to handle garbage data (like saves with golems in slots 4-19 from before #2822 was fixed).

Add helper to check if a monster belongs to a player

---

Source/missiles.cpp

This merely copies the logic from `M_StartHit()` to the branch that runs when the monster resists the damage. This is a minimally invasive change for 1.4.1. For 1.5.0, I think it would be better to consolidate the logic between `HitMonster()`, `M_StartHit()`, and this branch of the logic.

Update mWhoHit and remote clients when hitting resistant monsters

---

Source/monster.cpp

- ♻️  [pass the Player reference to CheckReflect](https://github.com/diasurgical/devilutionX/commit/8c92bddf5fa57794b929dc086b9d9a8d93ca9e22)
- 🚚 [Rename attackingMonster to attacker](https://github.com/diasurgical/devilutionX/commit/8523f9468cfda9e6d713b961f856d38b9bc11ed9)
- 🚚 [Rename monster to target](https://github.com/diasurgical/devilutionX/commit/b873945d7860fd1fd7a8533a34e50188722139b9)
- ♻️  [pass the attacker and target as reference to MonsterAttackMonster](https://github.com/diasurgical/devilutionX/commit/7cb343f5f044a3a64098025cd498a9bcb7874e85)
- ♻️  [MonsterAttackPlayer only takes players as target](https://github.com/diasurgical/devilutionX/commit/ec4f4f124d589b31adb2d2784f5e2cf59e777350)
- ♻️  [MonsterAttackPlayer receives player and monster as …

:recycle: MonsterAttackPlayer receives monster and player as references

---

.github/workflows/Android.yml
CMake/platforms/android.cmake
android-project/app/build.gradle
android-project/gradle/wrapper/gradle-wrapper.properties

25 LTS gives SDL build errors (will be default in august).
24 gives a build error for one of our std polyfills.
23 works, but is not LTS.
21 LTS (current default) chokes on CMake 3.22 (which is now the version on Ubuntu, and also de latest in Android Studio).
Hopefully the SDL build errors for 25 will be solved in the not to distant future.

Bump NDK version

---

.github/workflows/miyoo_mini_release.yml
.github/workflows/opendingux_release.yml
.github/workflows/retrofw_release.yml
.github/workflows/src_dist_release.yml

1. Use the `release.published` event because `release.created` never triggers for releases that start off as drafts.
2. Use a simpler action to upload files (the defaults are more appropriate for what we need, which is just uploading the files and not doing anything else).

GitHub Actions: Maybe fix release uploading

---

Source/engine/demomode.cpp
Source/pfile.cpp
Source/pfile.h
test/timedemo_test.cpp

Example:
```
file "game" is different at byte 54251:
Expected: ... 00 00 00 00 00 00 00 00 30 00 00 00 50 00 00 00 ...
Actual: ... FF FF FF FF 00 00 00 00 30 00 00 00 50 00 00 00 ...
```

Improve demo test error message

---

Source/player.cpp

We always have `_pSpell` when this function is called.

`Player#getGraphic`: Remove `MyPlayer` check

---

Source/main.cpp

Before this fix trying to compile with -DDEVILUTIONX_SYSTEM_SDL2=OFF for MinGW would give a undefined reference to `WinMain'.

Fix Building SDL2 for MinGW

---

Source/controls/plrctrls.cpp
Source/cursor.cpp
Source/debug.cpp
Source/engine/path.cpp
Source/engine/render/scrollrt.cpp
Source/levels/setmaps.cpp
Source/levels/themes.cpp
Source/missiles.cpp
Source/msg.cpp
Source/objects.cpp
Source/objects.h
Source/player.cpp

There were enough cases that it felt like this was useful, even after removing the unchecked lookups from retrieving a newly created object for further initialisation.

Add function for unchecked Object lookups

---

Source/loadsave.cpp

Fixes #4954
Setting `leveltype` from `GetLevelType(currlevel)` is wrong if we are on a quest map (`setlevel` is true).
Was [introduced](https://github.com/diasurgical/devilutionX/commit/54cd839cf6c7b4647f3b1906275f9dcae225b7a8#diff-eb2db6084d42c0224b56a122152915d07d944c27040e427d6193bc382ca754b3R2267) in #4665 /  54cd839cf6c7b4647f3b1906275f9dcae225b7a8 .
Many thanks to @Chance4us for finding the buggy commit and the nice reproduction videos. 🙂👍

Don't recalculate leveltype (from currlevel) in SaveGameData

---

Source/engine/render/scrollrt.cpp

Fixes #4822
The renderer draws from left to right.
Left sideways walking monsters have a positive index to there target tile (left) and a negative index to there origin tile (right).
In master we only render the positive monster index.
But after that we render the (right) neighbor tile. This can override the drawn monster.
This pr now draws (for left side walking) the monster with the negative index. This ensures we the monster is not "overdrawn".
A similar check was removed by the broken commit (e62aaa562f12e50db62ee288c6c15c5d3aa9febf).
Thanks @qndel for finding the broken commit 🙂

Fix left sideways walking monsters draw order

---

Source/levels/drlg_l1.cpp

Can't seem to find an open issue for this, but I know it was reported and found long ago.

Fix broken dirt tile in cathedral/crypt

---

Source/options.h
Source/utils/language.cpp

If the language is set to one of the locales that requires extra fonts and `fonts.mpq` is missing, show an error dialog and fall back to English.
Fixes #5140

Missing fonts.mpq: Show an error, fall back to en

---

tools/make_src_dist.py

Explicitly set `-DDEVILUTIONX_SYSTEM_SDL_AUDIOLIB=OFF` and `-DDEVILUTIONX_SYSTEM_SIMPLEINI=OFF` because we now also support the system versions of these.

make_src_dist.py: Vendor simpleini SDL_audiolib

---

.github/workflows/miyoo_mini_release.yml
Packaging/miyoo_mini/build.sh

Add "miyoo-mini" to the release archive name to make it clear what device this is for.

Miyoo mini: Rename zip files

---

Source/monster.cpp
Source/monster.h
Source/player.cpp

I believe that most read access to the `dMonster` global could be replaced with calls to `MonsterAtPosition`, which should improve the code readability and reduce global variable usage.
But, some places are checking if the dMonster contains no monster at all (`== 0`) while other places are checking for moving monsters as well (`<= 0`) and the current version of `MonsterAtPosition` only supports `== 0`.
This PR adds a strict flag that allows the `MonsterAtPosition` caller to switch the function's behaviour.
~~Note: I don't think `strict` is a good name, if you guys like this proposal we should find a better name~~
The parameter was renamed to `ignoreMovingMonsters` thanks to the feedback

:sparkles: Adds ignoreMovingMonsters to MonsterAtPosition

---

Source/msg.cpp
Source/msg.h
Source/objects.cpp
Source/objects.h

Merge most of the high level door functions and split delta sync from the door functions. This revealed delta sync to be almost identical to `OpenDoor()`.
A bigger chunk of the door logic refactoring. Split in to a few logical commits. All in all this should still be mostly simple changes.
`OpenDoor()` now sets
```cpp
door._oPreFlag = true;
door._oVar4 = DOOR_OPEN;
```
This was done during delta sync/direct operation so setting it on network sync should be correct.
-----
`CloseDoor()` now set:
```cpp
door._oMissFlag = false;
door._oSelFlag = 3;
```
This was done each frame by `UpdateDoor()` so L3 setting `true` and synced doors setting `2` was pretty pointless.
-----
`DeltaSyncOpObject()` is no longer called for `CMD_CLOSEDOOR`, doors are closed on spawn so this was probably just there to …

Merge more Doors logic

---

Source/engine/world_tile.hpp
Source/msg.cpp

In the worst case this ends up increasing the size of the DLevel object by 127*2 bytes (since we now need to track object position in the delta) + map overhead. Having said that deltas are only really needed for objects which actually allow interaction. Decorations no longer get a delta since they never change. Actual network traffic is compressed so should end up about the same in practice.
Static memory usage increases by 127*2+1 bytes unfortunately due to the use of `sgRecvBuf`. Hard to tell if we even need this chunk of memory to be on the stack given the use in `OnLevelData()`.
fixes #5172

Use position for object delta messages

---

Source/msg.cpp
Source/objects.cpp
Source/objects.h

Fixes an issue reported by user Malignus on Discord.
> When you go in a level where there are traps, if you go to town and take back the town portal, all the traps will re-activate themselves upon entry of TP.
> 
> So if you opened all chests and doors with traps fireball and arrows will be sent through the rooms.
The issue was introduced by #4805, where the condition that checked for `deltaload` was removed.

Split delta trap operation from realtime trap operation

---

Source/msg.cpp

Doing `foo++` twice is a big no-no.

Prevent sequence-point warning in DeltaImportObjects when compiling with GCC

---

Source/engine/path.cpp
Source/objects.cpp
Source/objects.h
Source/player.cpp
Source/track.cpp

Besides removing a lot of redundant code the now shared logic means that some original inconsistencies are now fixed:
- Doors could be drawn in the wrong order if opened by other players
- Crypt doors made the wrong sound when blocked
And one that we had introduced
- Crypt doors looked wrong after closing them
In total the logic has been reduced by over 500 lines.

Unify and clean up door logic

---

Source/stores.cpp

fix adria's 'you have nothing to recharge' alignment

---

Source/interfac.cpp

Fixes: When saving while in a quest map and try to load the game in devX <= 1.4.1 or vanilla the player will stop responding.
The issue was introduced with #4738 and is only present in master (not 1.4.1).
Background:
For multiplayer support the `Player` class needed to correctly store the player level (including set maps)
That's why [this line](https://github.com/diasurgical/devilutionX/commit/ceb08d783f38a4773c3dbea3b39cfd0b6e236fee#diff-71461699ae2f94f652e6cba2136d3c696151ba3a6c0e357eaf55438a5c212ad3R3270) was introduced when entering a set map: `player.setLevel(setlvlnum);`
Previous `plrlevel` wasn't initialized correctly.
This compatibility issue with old saves was addressed with [this changes](https://github.com/diasurgical/devilutionX/commit/ceb08d783f38a4773c3dbea3b39cfd0b6e236fee#d …

Fix vanilla compatibility for saving in quest maps

---

Source/player.cpp

Fixes this error...
**To reproduce...**
1. On client 1, create a new warrior and start a TCP game
2. On client 2, create another new warrior and join the TCP game
3. On client 2, use the "New Game" option in the menu to leave the game
4. On client 2, immediately rejoin the game
5. You should see the error on client 1
---
The error was introduced with the recent CLX changes, but the conditions for the error existed long before that. This fix follows the pattern used in a handful of other places throughout the codebase that also load the `PM_DEATH` animation. For example...
https://github.com/diasurgical/devilutionX/blob/52780a37125452f9ac5cb5010af7071e0ecd10f1/Source/msg.cpp#L1836-L1838

Ensure valid animation state when loading death animation in InitPlayer()

---

Source/utils/cel_to_clx.cpp

When converting cel to clx with a graphic that has multiple groups the number of frames (per group) is not correctly written.
This results in an [assert error](https://github.com/diasurgical/devilutionX/blob/master/Source/engine/clx_sprite.hpp#L130) when going to the cows in town.

CelToClx: Fix writing frame count with multiple groups

---

Source/misdat.cpp

Fixes #5198 
The hork spawn missile has no animation associated (`MFILE_NONE`) but `MissilesData` says it should be rendered (`mDraw`).
This is incorrect (also in 1.4.1).
In 1.4.1 this doesn't result in a crash, cause of [checks in drawing](https://github.com/diasurgical/devilutionX/blob/1.4/Source/scrollrt.cpp#L312-L315). But we get a log warning:
> INFO: Draw Missile 2 type 95: NULL Cel Buffer
@glebm I'm unsure if we should change the behavior (in a separate pr) when drawing incorrect animations (change back to log instead of appfatal?).
Thanks @Chance4us for reporting. 🙂 
Side-Note:
When loading a original hellfire game and the missile is spawned this could still result in a crash, cause the incorrect `MissilesData` was used to initialize the `Missile::_miDrawFlag`.

Fix draw flag for MIS_HORKDMN (set to no drawing)

---

Source/dvlnet/packet.cpp

Fix the string for packet type PT_ECHO_REPLY. It seems somebody mistakenly typed "PT_ECHO_REQUEST" instead of "PT_ECHO_REPLY".

Fix the string for packet type PT_ECHO_REPLY.

---

Source/msg.cpp
Source/msg.h
Source/objects.cpp
Source/objects.h
Source/player.cpp

Also included some minor cleanups while in the area. PLROPOBJ and OPERATEOBJ are synonyms now so we only need one.
This doesn't change behaviour currently as CMD_CLOSEDOOR level delta messages will be dropped when replaying the state on (re)entering a level, this makes the effect explicit and moves it to a more relevant area.

Be explicit about effect of CLOSEDOOR command on multi level delta

---

Source/init.cpp

Fixes the hardware cursor not resizing in-game when changing the window size.

Reinitialize hardware cursor on window size change

---

Source/DiabloUI/diabloui.cpp
Source/DiabloUI/diabloui.h
Source/DiabloUI/selhero.cpp
Source/monster.cpp

Resolves https://github.com/diasurgical/devilutionX/issues/5031
```cpp
myPlayer.pDiabloKillLevel = std::max(myPlayer.pDiabloKillLevel, static_cast<uint8_t>(sgGameInitInfo.nDifficulty + 1));
```
this happens in PrepDoEnding  which means showing difficulty thingies works only in multiplayer - multi autosaves after outro so the value is preserved while in singleplayer you have no way to save after it got set.
That's why I've added 
```cpp
if (!gbIsMultiplayer) {
Player &myPlayer = *MyPlayer;
myPlayer.pDiabloKillLevel = std::max(myPlayer.pDiabloKillLevel, static_cast<uint8_t>(sgGameInitInfo.nDifficulty + 1));
}
```
to DiabloDeath to compensate for that - the variable will increase by 2 in singleplayer after outro, but since you have no way to save the second increase, it's all good. You can …

show difficulty indicator on multiplayer characters

---

Source/DiabloUI/button.cpp
Source/DiabloUI/button.h
Source/DiabloUI/diabloui.cpp
Source/DiabloUI/diabloui.h
Source/DiabloUI/scrollbar.h
Source/DiabloUI/selhero.cpp

1. Position them above portrait on top left.
2. Do not show for non-save portraits.
3. Remove `vecDifficultyIndicators`. Render the indicators on the fly instead.

Difficulty indicator improvements

---

Source/player.cpp

Found by pvp-community while testing #4599

StartNewLvl: Only update setlvlnum for the local player

---

Source/objects.cpp

Fixes #5230
`OBJ_SHRINEL` and `OBJ_SHRINER` wasn't updated when delta loading (multiplayer) a level.

DeltaSyncOpObject: Add handling for shrine

---

Source/missiles.cpp

This resurrects `SyncPositionWithParent` that was removed in #3957 / ed5a3b3dcbe5455f5f423b15b63d92e512bbfe8a
This is only a visual difference change and doesn't affect gameplay (cause lightning and inferno flames don't move)
The changes is most notable with lightning, cause now we have more fragmentation and a spawned lightning isn't always shown exactly on a line.
Thanks galaxyhaxz for reporting, AJenbo for bisecting and qndel for the gifs 🙂

Resurrect SyncPositionWithParent

---

Source/restrict.cpp
Source/utils/file_util.cpp
Source/utils/file_util.h

It looks like this is mostly a left over from when file handeling was migrated to SDL

Use SDL for creating file during RW test

---

3rdParty/SDL2/CMakeLists.txt

Required for PS2 support, and probably Android NDK 25 (default version by November)

Update SDL2 to versoin 2.23.2

---

Source/inv.cpp
Source/inv.h
Source/msg.cpp
Source/msg.h
Source/player.cpp
Source/storm/storm_net.cpp
test/inv_test.cpp

Synchronizes changes to the player's inventory to remote clients. There are definitely some missing edge cases, but this can get us started on resolving many of the sources of desync discussed in #4074.
Here is a video demonstration of how the synchronization looks when testing in conjunction with https://github.com/StephenCWills/devilutionX/commit/5df65ff54f6ee6fef6d13cb23e01d9710f4a0060:
https://user-images.githubusercontent.com/9203145/183315099-ff6d09f9-d43a-4304-bc2a-72db5a11a4b3.mp4

Synchronize player inventories

---

Source/msg.cpp

Fixes a crash due to data alignment on 3DS when attempting to create a Multiplayer game.
Some relevant notes from @glebm on Discord.
> Sounds like `DLevel` has a broken copy constructor
> may have something to do with `#pragma pack(push, 1)`
> older ARM CPUs crash on unaligned writes (and reads sometimes)

Avoid DLevel copy constructor in GetDeltaLevel()

---

Source/msg.cpp

This actually fixes the crash due to data alignment on 3DS when attempting to create a Multiplayer game. I tested with and without debug code this time, so I'm pretty confident this will fix it for good.
The previous fix worked when I had my debug log statements in, but not when I removed them. Probably, the data alignment just happened to be valid for that `DLevel` instance with those specific changes and the debug statements in.
I also removed pragma pack from `DObjectStr` since object deltas don't use `memcpy()` to import/export the data.

Remove pragma pack from DLevel struct

---

Source/levels/gendung.cpp

- Use the save from #4384
- move one tile to the right
- shoot straight upwards (with any missile)
- you can shoot through the corner
Screenshot (with `tiledata dPiece`):
This is due dPiece 27 is incorrectly not marked as blocking missiles.
Thanks @FitzRoyX for reporting 🙂

Fix incorrect SOLData for L1 Piece 27 (BlockMissile is missing)

---

Source/cursor.cpp

This implements issue 5104 : https://github.com/diasurgical/devilutionX/issues/5104
Tested locally, seems to work alright.

Turn off monster highlighting with Heal Other and Resurrect cursors

---

Source/menu.cpp

The game was attempting to load Nest and Crypt music in the menu when playing DevilutionX Diablo, causing silence in the menus because the assets failed to load.

Only load Hellfire music when Hellfire is active

---

Source/engine/trn.cpp

Fixes an issue where class TRNs could not be loaded directly from assets placed on the filesystem, causing the colorless sprite seen below.
The TRN used here was infra.trn copied directly from diabdat.mpq to my assets folder. Attempting to load the TRN with `trn infra` will result in the following error messages, indicating that there are errors preventing it from reading the data.
```
DEBUG: Error reading from datastream
DEBUG: Error reading from datastream
DEBUG: Error reading from datastream
DEBUG: Error reading from datastream
DEBUG: Error reading from datastream
INFO: DebugCmd: trn infra Result: I am a pretty butterfly. 
(Loading TRN: infra.trn)
```
The issue is caused by the data type of the `trn` variable used on the line modified by this PR. `&trn` produces a value of type …

Fix template data type when loading class TRN

---

Source/control.cpp
Source/items.cpp

Fixes #5255
Issue was introduced by #5235
First commit ensures that we don't write out of bounds.
Second commit fixes that staffs have a scroll panel info and that flash scrolls doesn't have any panel info.
In the second commit please take a additional look at `printItemMiscVirtualGamepad` and `printItemMiscGamepad`, cause I didn't test them.

Ensure AddPanelString doesn't get out of bounds

---

Source/inv.cpp
Source/items.cpp
Source/items.h
Source/msg.cpp
Source/pack.cpp
Source/pack.h
test/pack_test.cpp

Fixes loading save games in hero selection.
Background:
When loading a save game for hero selection, `MyPlayer` was not yet initialized.
But `UnPackItem` used `MyPlayer`.
Was introduced with #4754.
This pr changes `UnPackItem` (and the function that `UnPackItem` uses) to not use `MyPlayer` anymore. Instead `Player` is passed per reference.
I hope I got all uses of `MyPlayer` but perhaps I missed some special item powers (perhaps none of my save game contains them 😉 ).

Don't use MyPlayer in UnPackItem and dependend methods

---

Packaging/nix/devilutionx.metainfo.xml

Since the project now has a new custom license, reference it in metainfo

Add new license to Appstream metainfo file

---

3rdParty/SDL2/CMakeLists.txt

The fully-vendored source distribution removes all test files to reduce the size, which causes a CMake configuration error if `SDL_TEST` is on.

3rdParty/SDL2: Disable SDL_TEST

---

3rdParty/SDL2/CMakeLists.txt

I poked around a bit after https://github.com/diasurgical/devilutionX/pull/5306#issuecomment-1230342956, and it seems they're doing something a bit odd with that `SDL_TEST` variable.
https://github.com/libsdl-org/SDL/blob/cb46e1b3f06a08d57b4ccd83127d1ec3139e1c0f/CMakeLists.txt#L510

3rdParty/SDL2: Use SDL_TEST_ENABLED_BY_DEFAULT

---

CMakeLists.txt

Also cleans up how the policies are set and ensures all the NEW policies also have `CMAKE_POLICY_DEFAULT_CMP<NNNN>` set to `NEW`.
Eliminates the warning in CMake v3.24+ https://cmake.org/cmake/help/latest/policy/CMP0135.html

CMake: Set CMP0135 to NEW

---

Source/automap.cpp
Source/engine/direction.hpp
Source/engine/displacement.hpp
Source/missiles.cpp
Source/monster.cpp

This PR supersedes PR #4011 which was opened by @Sergentfox234.  This is a solution for issue #2260. @AJenbo suggested a number of changes to PR #4011 on January 29th, and since these changes have not been implemented yet, I opted to do it myself. 
Besides implementing the suggested changes, I have also made an additional change. I've added a direction called `NoDirection` to `enum class Direction`, and added this direction to the Displacement switch statement in `displacement.hpp` so that displacement `{ 0, 0 }` can be labelled in the code. To prevent warnings during compilation, I've added a case for `Direction::NoDirection` to switch statements in `monster.cpp` and `automap.cpp` (the case does nothing, just breaks).

Refactor missiles.cpp to use Direction enum instead of magic Point/Displacement constants.

---

3rdParty/discord/CMakeLists.txt
Source/automap.cpp

CMake's built-in FindPatch will look in the Git installation directory on Windows, eliminating the need for Windows users to modify PATH.
See https://github.com/Kitware/CMake/blob/master/Modules/FindPatch.cmake

CMake: Use FindPatch

---

Source/main.cpp

Fixes building MinGW after updating SDL version with #5322.
Removes workaround for static building SDL with MinGW. No longer needed after updating 2.24.0.

Fix SDL MinGW build

---

Source/items.cpp
Source/msg.cpp
Source/multi.cpp
Source/player.cpp
Source/player.h

Fixes #5046
The cause of #5046 was that the `AnimationInfo` and player mode got out of sync.
With this change we fix the out of sync. We can now change gear dynamically for all player graphics.
For this `Player::getAnimationFramesAndTicksPerFrame` was introduced, so the frames and ticks per frames can be managed at one location (reduces use of `_pXYZFrames`). It's used when starting a new player animation (`NewPlrAnim`) and when swapping gear.

Introduce Player::getAnimationFramesAndTicksPerFrame and use it when swapping gear

---

Source/engine/animationinfo.h
Source/engine/render/scrollrt.cpp
Source/items.cpp
Source/monster.cpp
Source/player.cpp
Source/player.h

Fixes #5046
The cause of #5046 was that the `AnimationInfo` and player mode got out of sync.
This is mostly not problematic, but in some actions (for example `DoAttack`), we don't use `AnimationInfo::numberOfFrames` to check if an animation ends but instead the original value (for example `_pAFrames`). This can result in problems (see #5046).
With this pr a new helper (`AnimationInfo::isLastFrame`) is introduced to check for the last frame (inspired by #4818).
And this helper is used instead of `_pXYZFrames` (first commit; fixes the issue) and where we previous used `numberOfFrames` (second commit; makes the code more readable).
This pr makes the game more stable and is additional to #5324 (Both pr's fixes #5046 but #5324 is the cleaner way).

Introduce AnimationInfo::isLastFrame and use it instead of _pXYZFrames

---

Source/controls/game_controls.cpp
Source/controls/plrctrls.cpp

It is currently not possible to skip the logo or intro videos using the gamepad because `MyPlayer == nullptr` until you enter the `Single Player` or `Multi Player` menus. The issue was introduced by 188dc79f6e19645b282567612c6166eb63662b27 due to changes in `MyPlayer` initialization.
It seems like `InGameMenu()` is the only function making use of `MyPlayer` in the input event handler. I tried to test all the button combinations to make sure nothing crashes so I'm pretty confident.

Fix skipping intro using gamepad

---

Source/control.cpp
Source/inv.cpp
Source/inv.h
Source/items.cpp
Source/items.h
Source/msg.cpp
Source/msg.h
Source/pack.cpp
test/inv_test.cpp

Continuation of #5217
* Introduce a struct to differentiate ears from other items in the network code
* Expand `TCmdChItem` to include the same level of item information as `TCmdGItem` and `TCmdPItem`
* Send network messages when adding gold to and removing gold from the player's inventory
* Fix an error that used the wrong inventory grid index when a remote player swaps items
While testing, I noticed that moving ears around in a player's inventory will cause remote clients to crash due to the inventory synchronization. This PR should fix that as well.

Synchronize ears and gold in player inventories

---

Source/levels/setmaps.cpp
Source/missiles.cpp

Fixes #5185
I also changed skeleton kings lair's players spawn position to match the position of normal cathedral stairs.
That way it's consistent with normal cathedral and no special in `AddWarp` is needed. 😁

Fix warp position offset and leorics lair spawn position

---

Source/DiabloUI/settingsmenu.cpp

Fixes an error where key bindings would not be assigned when typing a letter key unless the player entered an uppercase character.
Introduced in #5018

Fix error mapping keys when typing lowercase characters

---

Source/monster.cpp

SkeletonTypes is std::array so we can use size (it's constexpr too)

use SkeletonTypes array size

---

Source/levels/themes.cpp
test/random_test.cpp

Was looking at adding a helper for checking if a point matches a given regionId however I don't really want to introduce an unavoidable function call by using the same pattern as IsTileSolid and defining it in path.cpp. Probably move all that into a new header for dungeon tile checks?
This was the intent for CheckThemeObj5 but omitted for now:
```cpp
bool IsTileInRegion(Point position, int8_t regionId)
{
return InDungeonBounds(position) && dTransVal[position.x][position.y] == regionId;
}
```

Move theme internals into anonymous namespace, misc cleanups

---

Source/items.cpp
Source/loadsave.cpp
Source/missiles.cpp
Source/monster.cpp
Source/monster.h

Replace `level` member in `Monster` with member function. This is done to reduce the size of a monster and to make reasoning about the code easier, since all of the `level` calculation is now done in one place. 
This replacement was discussed in #4986.

Replace level member with a member function in monster

---

.github/workflows/Android.yml
3rdParty/libpng/CMakeLists.txt

I'm pretty sure that https://github.com/diasurgical/libpng/commit/838a5dc474b896fec83f5a42508f739f23f66176 was originally necessary to get the Android build to work, but I didn't encounter any errors in my tests today so we're just going to try without it. 🤞

Upgrade libpng to 1.6.38

---

Packaging/nix/org.diasurgical.DevilutionX.yml

Changes: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/tags/freedesktop-sdk-22.08.0
Built and play tested on Arch Linux, everything looks good

Update flatpak SDK and runtime to latest version

---

Source/levels/drlg_l1.cpp
Source/levels/drlg_l4.cpp
Source/levels/setmaps.cpp
Source/missiles.cpp
Source/quests.cpp
test/drlg_l1_test.cpp
test/drlg_l4_test.cpp

Fixes #5185 (second try 😉)
This PR fixes the warp positions (hopefully) and changes some spawn positions (for examples see bottom).
Please review the changed spawn positions especially. I think the most controversial could be hellgate and hell downstairs. 😉 
<details><summary>Banner Quest</summary>
</details>
<details><summary>Chamber of Bone</summary>
</details>
<details><summary>Lazarus Portal</summary>
</details>
<details><summary>Warlord of Blood</summary>
</details>
<details><summary>Hell downstairs</summary>
</details>
<details><summary>Hell gate</summary>
</details>
@Chance4us It would be great if you could test this pr. 🙂 
I didn't change
>  upstairs: The warp and hero position is the same, but the hero stands displaced in the entrance (unclear if vanilla behavior)

Fix warp position offset and adjust some spawn positions

---

Source/DiabloUI/credits.cpp

It seems the CLX renderer which is now used for rendering font symbols uses `memcpy()` and `memset()` operations against the UI surface, bypassing `SDL_SetClipRect()`. However, it does honor the bounds specified by the rectangle passed into the `Surface` constructor so we can use that instead.
This resolves #5368

Fix rolling text in Support and Show Credits

---

Source/items.cpp

Fixes "Activate to use" showing up on all items when using a virtual gamepad.

Fix activate to use showing up on all items

---

Source/items.cpp

Actually fixes #5373
Still was showing on virtual controller devices. This makes it so only the specific items have the text show up instead of all items.

Fix Activate to use showing on all items

---

Source/items.cpp

per discussion in #development on 30/Sep/2022 (could hypothetically use gloomy shrine, in single player, to subtract 1 max damage each time you use an oil of death and eventually, after much effort, exceed max value for damage)

Prevent oil damage wrap around

---

android-project/app/build.gradle

I discovered today that all my Intellisense-related performance problems had to do with Visual Studio indiscriminately scanning all files in every folder beneath the root folder where `CMakeLists.txt` resides. This behavior doesn't play nice with the massive number of intermediate files produced by Android Studio builds in the `...\devilutionX\android-project\app\.cxx` folder. The change in this PR simply allows me to override the location of the Android build's intermediate files by setting the `DevilutionX_Android_StagingDirectory` environment variable. That way I can put it in an entirely different location that Visual Studio doesn't care about. It seems to do nothing if the environment variable isn't set so this hopefully shouldn't affect anyone else.

Enable override for the externalNativeBuild's buildStagingDirectory

---

Source/levels/themes.cpp

Fixes #5360
The bug was introduced with #5117 / 08acd4aac05158e09655a54ee60fd5e15014993a
Previous `TFit_Obj5` only returned false when [no place for the (first candidate) theme room was found (`r == rs`)](https://github.com/diasurgical/devilutionX/commit/08acd4aac05158e09655a54ee60fd5e15014993a#diff-b22a42607df3745a75d7085a9f065fbd0be5b4522c3d24527480312e4e7a3bf5L128). In this case searching for a second candidate/position is not necessary, cause the entire dungeon can't fit any.
Else the function [returned true and used the coordinates for the last candidate](https://github.com/diasurgical/devilutionX/commit/08acd4aac05158e09655a54ee60fd5e15014993a#diff-b22a42607df3745a75d7085a9f065fbd0be5b4522c3d24527480312e4e7a3bf5L139-L142).
@ephphatha Could you take a look? That would be great. 🙂

TFit_Obj5: Fix theme room generation when only last skipped candidate was valid

---

Source/gamemenu.cpp
Source/gmenu.cpp
Source/gmenu.h

Previously, clicking on the slider close to the end or near the start did nothing -- you'd have to actually drag it to set the value to min or max.
Also cleans up the in-game menu code overall.

In-game menu: Fix slider click handling

---

Source/levels/themes.cpp

Based on #5394, slight simplification of the logic involved.
I was going to add a test case but it seems that the theme array isn't initialised in headless mode? The seed in #5360 ends up with 5 themes on floor 1, THEME_SKELROOM, THEME_TREASURE, THEME_SKELROOM, THEME_MONSTPIT, THEME_SKELROOM. The bugged logic in #5117 fails to place all skeleton rooms which results in the skeleton tomes/banners not being loaded as the themes aren't marked as used. They exist in the save game objects list though which causes the crash when the game attempts to render them.

Use a counter to track the number of candidates considered in TFit_Obj5

---

Source/items.cpp

Fixes #5296
`MI_Infra` calls `CalcPlrItemVals` when infravision is removed. `CalcPlrItemVals` is expect to reset `_pInfraFlag`.
Line [was removed](https://github.com/diasurgical/devilutionX/commit/58ae9169f1df10a59319c145d517a27dbc4bf03b#diff-be3ecbe1ead4062ccd317dfeb0428b38adf3d54377059e602229c75bfc052da8L2616-L2617) in #5229 / 58ae9169f1df10a59319c145d517a27dbc4bf03b
Thanks @Chance4us for reporting and finding the correct commit. 🙂

Fix infravision lasts forever

---

Source/missiles.cpp
Source/objects.cpp

Items are initialised using either `GetItemAttrs` (which copies values from `AllItemAttrs` over whatever memory values were already present) or `InitializeItems` (which re-initialises the item struct explicitly then copies values from `AllItemAttrs` over the default/zero-init values).
We can be confident that potions have been spawned in a way that initialises their seed to some random value, so reusing the seed is not harmful.
Out of interest, the only items I saw which have a fixed seed are uniques spawned via `SpawnUnique` (seeds are either 0 from the earlier call to `AllocItem` or set to the `uid` inside `GetUniqueItem`) and the quest items Magic Rock/the combined note which both use a zero-initialised seed.

Restore item seed when converting potions to rejuvenation potions

---

3rdParty/SDL2/CMakeLists.txt

VCPKG already updated
Release notes: https://github.com/libsdl-org/SDL/releases/tag/release-2.24.1

Update SDL2 used from source to v2.24.1

---

3rdParty/zlib/CMakeLists.txt

The link to the 1.2.12 source is now gone.

Update zlib to 1.2.13

---

Source/controls/controller.cpp
Source/controls/controller.h
Source/controls/controller_buttons.h
Source/controls/controller_motion.cpp
Source/controls/controller_motion.h
Source/controls/game_controls.cpp
Source/controls/game_controls.h
Source/controls/menu_controls.cpp
Source/controls/modifier_hints.cpp
Source/controls/plrctrls.cpp
Source/controls/plrctrls.h
Source/cursor.cpp
Source/diablo.cpp
Source/gmenu.cpp
Source/items.cpp
Source/miniwin/misc_msg.cpp
Source/movie.cpp
Source/options.cpp
Source/options.h
Source/track.cpp
Source/utils/display.cpp

Adds a padmapper for customizing actions associated with gamepad buttons. The controls basically feel the same, as far as I've been able to tell. Hopefully the code is easier to follow now as well.
* Enables mappings for two-button combos
* Introduces gamepad actions for nearly all of the keyboard actions
* Introduces actions for "stand ground" and "toggle stand ground" to enable Shift+Click functionality for gamepad
* Implements the currently hardcoded control scheme as the padmapper defaults
* Swaps A/B and X/Y menu actions for non-Nintendo controllers based on the `GamepadLayout` (note, this may have a somewhat adverse effect on the Quest Log and Spellbook screens that should be addressed at some point)
* Removes settings for d-pad hotkeys and swap shoulder button mode as it should now …

Add padmapper for gamepad customization

---

Source/inv.cpp

Fixes an issue where the player simply cannot use runes.
https://user-images.githubusercontent.com/9203145/196257264-db3721f5-4f62-4180-860a-8d6fa98bf579.mp4

Include runes in CanUseScroll() validation

---

Source/msg.cpp

Fixes #4566
- Game logic
- `ProcessPlayers` is called -> Player gets next to item tile / on the portal tile -> `CMD_REQUESTAGITEM` is send
- `ProcessMissiles` is called -> `MI_Town` is called -> CMD_WARP is send and `PM_NEWLVL` is set
- Messages gets handled
- `OnRequestAutoGetItem` is called -> No space for item is found -> `CMD_RESPAWNITEM` is send
- `OnWarp` is called -> Player level is changed
- `OnRespawnItem` is called -> Item is placed not in the original level but in the warped level. That means the item is not really destroyed only placed very badly. 😜 
Bugfix is that the player stops owning the level when he starts to warp (`PM_NEWLVL` is set).
Side effect: When started warping item is not tried to pick up In single- and multiplayer.

Don't process get request item commands after start changing level

---

Source/controls/plrctrls.cpp
Source/diablo.cpp
Source/inv.cpp
Source/inv.h
Source/msg.cpp

Fixes #4124
When syncing dropped items `SyncPutItem` is used on the remote client.
`SyncPutItem` used `FindAdjacentPositionForItem` and the player position to get the coordinates of the new item.
`FindAdjacentPositionForItem` use only the adjacent positions relative to the player.
If no space is free the item is not placed on the remote client.
This is okay for normal player drops, cause the same check is done in `LeftMouseDown` or `TryDropItem`.
But when items are dropped on death `FindAdjacentPositionForItem` is not used (see `DeadItem`).
That allows dropping on death to occupy more tiles then `FindAdjacentPositionForItem`.
But when syncing with other clients the remote client uses `SyncPutItem` and `SyncPutItem` only allows adjacent tiles.
That can result in desyncs.
The bugfix is that …

Network drop Items: Always use passed coordinates for item position

---

Source/misdat.h
Source/missiles.cpp
Source/missiles.h
Source/spells.cpp

Moves the invocation of `ConsumeSpell()` to the `CastSpell()` function. This ensures that the mana, scroll, or staff charge is only consumed when a player casts a spell, and avoids all the tricky logic in the `AddMissile()` functions to ensure that a player did indeed cast the spell (as opposed to a monster, trap, Guardian, etc). For missiles that would conditionally fail, such as Stone Curse when it can't find a target, I added the `Missile::_miSpellFizzle` variable to indicate that the spell should not consume mana. This works out well for `AddJester()` which previously relied on the call to `ConsumeSpell()` in the `AddMissile()` function for the random missile that it generated to consume the staff charge. Now it more appropriately invokes `ConsumeSpell(player, SPL_JESTER)` if the …

Remove ConsumeSpell() from AddMissile() functions

---

Source/diablo.cpp
Source/diablo.h

Fixes #5282
When a lag occurs the game tries to run `game_loop`. But fails to do so (cause of the lag).
Then the game is drawn and in the next main loop it tires to run `game_loop` again (and fails).
The problem is that at every try it executes `diablo_color_cyc_logic`. That's why the animations updates very fast/go crazy.
Solution: Only call `diablo_color_cyc_logic` when the game loop is successfully executed. If not don't update the animations (similar to game pause).

Only color cycle animations if game logic is processed

---

Source/diablo.cpp

Contributes to #4491 (or fixes it? 🤔)
How to reproduce #4491 in master
- Try to pick up a item as a remote client (OnRequestItem).
- Add a sleep in OnRequestItem.
- Lag => `TimeoutCursor(true)` is called. It stores current hand cursor in `sgnTimeoutCurs` and sets hourglass cursor.
- Lag is gone => Messages gets handled => `OnGetItem` is called => `OnGetItem` sets item cursor => `TimeoutCursor(false)` is called and calls NewCursor with the stored cursor (`sgnTimeoutCurs` with the stored hand cursor) => `NewCursor` clears `HoldItem` => Item is gone.

TimeoutCursor: Only restore previous cursor when cursor is not already changed

---

Source/controls/plrctrls.cpp
Source/diablo.cpp
Source/inv.cpp
Source/items.cpp
Source/items.h
Source/levels/town.cpp
Source/levels/town.h
Source/msg.cpp
Source/msg.h

Previously, dropping the Rune Bomb or Cathedral Map would generate a `CMD_PUTITEM` message, triggering `InvPutItem()` on the local client or `SyncDropItem()` on remote clients. The local client would then proceed to generate `CMD_OPENHIVE` or `CMD_OPENCRYPT` as appropriate and skip the rest of the `InvPutItem()` logic. Remote clients would literally just ignore the `CMD_PUTITEM` message. The idea here is to skip the unnecessary `CMD_PUTITEM` command when it would be more appropriate to just generate `CMD_OPENHIVE` or `CMD_OPENCRYPT` instead.
I also went ahead and renamed functions/enums to use the term "Grave" instead of "Crypt" more consistently.
This resolves #5433

Fix opening Hive/Crypt with mouse

---

Source/options.cpp
Source/options.h

Padmapper actions which use format args to generate their key produce garbage data in the INI file. This happens because the `std::forward_list::push_front()` function uses the copy constructor of `PadmapperOptions::Action` which copies the reference in the `OptionEntryBase::key` variable instead of updating the reference to point to the copy. Once the copied action is deallocated, the copy points to the deallocated memory.
Special thanks to @obligaron for noticing the issue and identifying the cause.

Avoid copy construction of PadmapperOptions::Action

---

Source/controls/controller_motion.cpp
Source/controls/game_controls.cpp
Source/controls/plrctrls.cpp
Source/controls/plrctrls.h
Source/diablo.cpp
Source/miniwin/misc_msg.cpp
Source/options.cpp
Source/options.h

The interactions here are so complex that it's difficult to summarize this. I hope, when paired with the commit messages, that the following bullet points should suffice.
* `PadmapperOptions::ActionNameTriggeredByButtonEvent()` is intended for use by mouse simulation functions because these run during input detection, before `PadmapperOptions::ButtonPressed()`
* `PadmapperOptions::IsActive()` is intended for basically anything else that runs after the `PadmapperOptions::ButtonPressed()`
* `SimulateRightStickWithDpad()` returned a value to indicate whether the pad button input represents a gamepad movement event in order to shortcut further processing. That return value was removed from `SimulateRightStickWithPadmapper()` because it now uses `PadmapperOptions::IsActive()` to determine …

Fix mouse simulation

---

Source/controls/controller_motion.cpp
Source/controls/game_controls.cpp
Source/controls/menu_controls.cpp
Source/controls/plrctrls.cpp

Fixes the issue mentioned in https://github.com/diasurgical/devilutionX/pull/5455#issuecomment-1297991823.
* Shortcut processing for `ControllerButton_IGNORE` ASAP because the intent is clear: this is a gamepad button but we intend to ignore it
* Allow `ControllerButton_NONE` to be processed because it may represent an unrecognized gamepad button or another event entirely, like a touchscreen event

Clean up handling for gamepad IGNORE/NONE buttons

---

Source/panels/charpanel.cpp

In the hit calculation for a monster hitting a player, the player level is used, which equates to the player always having a 2 * clvl increase to what is displayed in the character panel. This adds it in.

Display correct Armor Class in Char Panel

---

Source/DiabloUI/diabloui.cpp
Source/DiabloUI/diabloui.h
Source/DiabloUI/settingsmenu.cpp
Source/engine/path.cpp
Source/engine/path.h
Source/missiles.cpp
Source/monster.cpp
Source/monster.h
Source/panels/charpanel.cpp
Source/platform/vita/CMakeLists.txt
Source/utils/language.cpp

`function_ref` is a lightweight function pointer, whereas `std::function` always involves a heap allocation.

Use `function_ref` instead of `function`

---

Source/controls/game_controls.cpp

It looks like most of these mappings were just plain wrong. There's still a bit of confusion on non-Nintendo gamepads because there are a few menus (inventory, char panel, speedbook, etc) that depend on `PrimaryAction` and `CancelAction` instead of these hardcoded mappings. In the long term, I'm aiming to have a separate `ConfirmAction` to help resolve that discrepancy.
This resolves #5448

Reverse A and B in pad button to key translation functions

---

Source/engine/animationinfo.cpp
Source/engine/animationinfo.h
Source/engine/demomode.cpp
Source/engine/render/scrollrt.cpp
Source/nthread.cpp
Source/nthread.h
Source/player.cpp
Source/player.h
test/animationinfo_test.cpp

Addressed glebm's [comment](https://github.com/diasurgical/devilutionX/issues/4849#issuecomment-1173046136).
Uses fixed point math for fractions (game ticks, animations, ...).
The pros:
- reduces size of `AnimationInfo` in 32bit builds (from 20 to 16 bytes)
- better performance for devices that don't have hardware float support
The cons:
- a little bit harder to read
- a fraction can only contain 128 distinct values. That means if you have a device that can show more than 2560fps you could see a difference. 😜

AnimationInfo: Use fixed point math for fractions

---

Source/controls/controller_buttons.h
Source/options.cpp
Source/options.h

Use an `std::array` instead of `std::unordered_map`.

Padmapper: Simplify `buttonTo*` data structures

---

Source/engine/render/scrollrt.cpp

Fixes #5477
`getAnimationProgress` returns a `uint8_t` but `GetOffsetForWalking` used `int8_t`.
Only if the walk animation is completed the value gets wrapped from 128 to -128 => glitch 😉 
@glebm Thanks for spotting the issue 🙂

GetOffsetForWalking: use uint8_t for animation fraction

---

Source/help.cpp

This is my attempt at adding a scrollbar to the help window. It is heavily inspired by the code for the store sliders in `stores.cpp`.
I had to reduce the width of the text a bit to actually leave enough space for the scrollbar (also explicitly using this width value for the wrapping of the text).
Directly using the code from the stores UI code looks hard because it uses store-specific variables and the way the help window text and scroll works seems different as well.
This PR is for issue #5192

Add scrollbar to help window

---

Source/items.cpp
Source/items.h
Source/objects.cpp
Source/quests.cpp
Source/towners.cpp

Fixes #4188
Quest items can be dropped cause of a interaction (click on a object => `sendmsg`=true) pregenerated on the dungeon (is placed on the dungeon floor => `sendmsg`=false).

Sync SpawnQuestItem (multiplayer quest items)

---

Source/items.cpp
Source/items.h

First commit refactors `SpawnItem` to make the behavior of `T_UNIQ` more clear.
Second commit allows to pick up unique quest reward items for all multiplayer clients (for example bovine plate).

Sync SpawnUnique (multiplayer unique quest rewards)

---

CMake/finders/FindSDL2_image.cmake

In case of vcpkg, pkg-config may not be available but a CMake config is. Prefer CMake config to pkg-config when looking for SDL2_image.

CMake: Fix FindSDL2_image.cmake with vcpkg

---

Source/diablo.cpp
Source/levels/drlg_l1.cpp
Source/levels/setmaps.cpp
Source/missiles.cpp
Source/monster.cpp
Source/msg.cpp
Source/objects.cpp
Source/objects.h
Source/player.cpp

When singleplayer quests are activated in multiplayer use singleplayer skeleton king's quest including his lair.
- DeltaLoadLevel: Item's check that they are not placed on a solid tiles. But objects can change the dungeon layout. That's why objects need to be synced/loaded before items else items could get placed on a wrong tile.
- Break crux wasn't synced in multiplayer (cause they were only used in skeleton king's lair).
- Ensures that entering skeleton king's lair plays skeleton kings speech in multiplayer. For this the already existing `PlayDungMsgs`/`sfxdelay` is used (normal `PlaySFX` don't work in the first 10 game ticks in multiplayer).
- For single- and multiplayer: Changed that skeleton kings speech is only played once when entering skeleton king's lair (not …

Multiplayer: Enable skeleton king's lair

---

docs/building.md

Otherwise the project cannot compile:
```
*** No rule to make target '/usr/lib64/libSDL2_image.so', needed by 'test/liblibdevilutionx_so.so'.  Stop.
```

Add SDL2_image-devel as Fedora dependency

---

Source/engine/render/scrollrt.cpp

Fixes chat input at 640x480.
Also fixes the other rects, they were slightly off.

DoBlitScreen: Fix update rects

---

3rdParty/zlib/CMake/FindZLIB.cmake
3rdParty/zlib/CMakeLists.txt
CMake/platforms/amiga.cmake
uwp-project/devilutionx.vcxproj

We're not using the system zlib on Amiga

amiga.cmake: Remove `find_package(ZLIB)`

---

.circleci/config.yml

Fixes a warning in the CircleCI logs for amiga builds.

[amiga] Fix build warning `Ignoring extra path from command line: ".."`

---

.github/workflows/PS4.yml

pacbrew-pacman is updated for Ubuntu 22.04 (the new version works on 22.04 but not on 20.04, the old version does not work on 20.04)

PS4: Update SDK (1.0 -> 1.1)

---

CMakeLists.txt
docs/building.md

`-Wl,--gc-sections,--as-needed` only needs to be passed to the linker. Fixes an unused linker flags warning with clang.

CMake: Clean up dead code removal flags

---

docs/installing.md

Huge fan of the game and the project; awesome job!
While installing it for Ubuntu 22.04 I got an error of a missing library _libSDL2 image-2.0.s0.0_.
Anyways, I added this library to the installing instructions for Linux/Ubuntu, just in case it could help future linux gamers.

added missing Ubuntu library

---

Source/controls/modifier_hints.cpp
Source/panels/spell_book.cpp
Source/panels/spell_book.hpp
Source/panels/spell_icons.cpp
Source/panels/spell_icons.hpp

Corresponding devilutionx-mpq-tools PR: https://github.com/diasurgical/devilutionx-mpq-tools/pull/4
Should be merged at the same time
Saves 120 KiB of RAM in Hellfire
Total size: 200 KiB -> 81 KiB
Images without backgrounds:
Large: ![spelicon_fg_clx](https://user-images.githubusercontent.com/216339/200957687-008693b8-3bb3-4bba-aa01-b883f0956cd5.png)
Small: ![spelli2_fg_clx](https://user-images.githubusercontent.com/216339/200957693-0956e798-3920-497c-aacf-d02236a92694.png)
Fixes #5470

Use no-background spell icons with UNPACKED_MPQS

---

Source/monster.cpp
Source/monster.h
Source/objects.cpp
Source/player.cpp
Source/quests.cpp
Source/towners.cpp

- Sign chest was not synced
- Ogden now also talk about the quest when you only entered lvl 4 and skipped 3 (for example cause you just joined the game and other player made a portal for you)
- `TalktoMonster` now uses the player that talks to the monster to check behavior not the player that is the current target of the monster
- When a player talks to a monster this is currently played back for all players on the same level
- A player can still enter catacombs even if the quest is not completed

Multiplayer: Enable Ogden's Sign Quest

---

CMake/platforms/rg99.cmake
Packaging/OpenDingux/build.sh

`-O2` increases the binary size by 0.5 MiB which we can now afford. Increasing audio buffer size to `768` improves performance (seems to be the sweet spot).
15-20 FPS in dungeon on the max-mem OD fork.

rg99: Build with -O2 and tune buffer size

---

Source/control.cpp

These printable ASCII characters will result in a text input event and should not be handled further.
Fixes #5505

control_presskeys: "Handle" some ASCII chars

---

Source/msg.cpp

Steps to reproduce the bug in master:
- Player 1 enter level 1 and don't move
- Player 2 enter level 1
- Player 1 leaves the game
- Player 2 crashes when trying to render player 1, cause his graphics are already unloaded
When player leaves the game his position is removed from `dPlayer`. This is done with `FixPlrWalkTags` functions. But `FixPlrWalkTags` uses `player.position.old`. And if `player.position.old` has incorrect/old data it doesn't clear `dPlayer`.
In previous version this doesn't result in a crash, cause `DrawPlayer` only logged a error when the graphics were not present.

Set player old position on level join to prevent a crash when leaving the game

---

Translations/es.po

I noticed some inconsistencies in the Spanish translation of _town_. In some text it was translated to _ciudad_ and in other text it was translated to _pueblo_. I am a native Spanish speaker and I think the most accurate translation is _pueblo_, so I removed all instances of _ciudad_ and changed them to _pueblo_.

fixed some spanish translation inconsistencies

---

tools/measure_timedemo_performance.py

Example:
```
$ tools/measure_timedemo_performance.py -n 32 --binary build-reld-sdl1-nonet-nosound-unpk/devilutionx
Run  1 of 32: 	 6.02 seconds	170.8 FPS
Run  2 of 32: 	 6.22 seconds	165.5 FPS
Run  3 of 32: 	 6.01 seconds	171.1 FPS
Run  4 of 32: 	 6.03 seconds	170.6 FPS
Run  5 of 32: 	 6.05 seconds	170.2 FPS
Run  6 of 32: 	 6.04 seconds	170.3 FPS
Run  7 of 32: 	 6.03 seconds	170.5 FPS
Run  8 of 32: 	 6.03 seconds	170.5 FPS
Run  9 of 32: 	 6.01 seconds	171.1 FPS
Run 10 of 32: 	 6.04 seconds	170.3 FPS
Run 11 of 32: 	 6.03 seconds	170.7 FPS
Run 12 of 32: 	 6.03 seconds	170.7 FPS
Run 13 of 32: 	 6.04 seconds	170.3 FPS
Run 14 of 32: 	 6.03 seconds	170.6 FPS
Run 15 of 32: 	 6.04 seconds	170.3 FPS
Run 16 of 32: 	 6.04 seconds	170.4 FPS
Run 17 of 32: 	 6.03 seconds	170.6 FPS
Run 18 of 32: 	 6.03 …
```

A tool to measure performance using the time demo

---

Source/engine/palette.cpp
Source/interfac.cpp

Disables FadeIn/FadeOut and progress bar updates in demo mode. This makes the demo run much faster (6s -> 2s).

Disable fade-in/out in demomode

---

Source/inv.cpp
Source/towners.cpp

- Quest is only activated when player was on level 9 or 10
- Removed checks for magic rock, cause in vanilla both quests (magic rock and anvil of fury) can't be present at the same time.

Multiplayer: Enable Anvil of Fury Quest

---

Source/sync.cpp

This one is a nasty one.
Got this sporadic when testing the multiplayer quests changes (but can also happen when these are disabled).
The game can sync monsters from a different level to the current level.
This only happens when the local player changes levels.
Result:
The game can crash when rendering invalid monsters (similar to #5527).
(In previous version this doesn't result in a crash, cause `DrawPlayer` only logged a error when the graphics were not present.)
or
Accessing undefined memory (and perhaps crash here).
How to reproduce:
- Player 1 needs to be in a dungeon level
- Player 1 opens a portal
- Player 1 needs to stay next to a monster that uses some coords that are next to portal in town
- Player 2 uses the portal to the dungeon
Perhaps multiple tires (go down and up from …

Don't sync monsters while level changing

---

Source/diablo.cpp
Source/miniwin/misc_msg.cpp
Source/utils/display.cpp
Source/utils/sdl2_to_1_2_backports.h

1. Unifies SDL1 and SDL2 text input handling.
2. Moves game-specific text input handling out of misc_msg.
3. Disables Unicode processing when not inputting text in SDL1.
This fixes gold withdrawal in SDL1.

Fix gold withdrawal in SDL1

---

Source/DiabloUI/settingsmenu.cpp
Source/control.cpp
Source/engine/render/text_render.cpp
Source/utils/display.cpp

1. Fixes the return value (bytes rendered).
2. Fixes line wrapping / end-of-rendering based on the given rectangle:
1. Accounts for `BaseLineOffset`.
2. Fixes an off-by-one error for the y coordinate.
3. Wraps the cursor when needed.
3. Fix chat input box dimensions (height is 3 * line height).
4. Set the hint that indicates that we do not render the current  IME suggestion (SDL_TEXTEDITING). This indicates to IME that it should render the suggestion instead.
5. Also fixes the settings description dimensions for CJK.

Text rendering and chat input fixes

---

Source/DiabloUI/diabloui.cpp
Source/DiabloUI/diabloui.h
Source/DiabloUI/dialogs.cpp
Source/DiabloUI/selhero.cpp

A popup-like error dialog in selhero resulted in a heap-use-after-free:
https://gist.github.com/glebm/f014bd87f066d2b79965b7c48bd8f6d7
This is because the popup's `Deinit()` freed the background art.
The fix is simply to not free the background art.
This is OK because the popup never has a background.
It used to load an empty background in the past just to load the palette but luckily it no longer does (otherwise this would require more work).
Also, fixes dialog rendering:
1. Fixes what is rendered behind the dialog.
2. Draws the mouse (if possible) regardless of whether the background is
present.
3. Clears the screen if the background doesn't cover it completely.
Fixes #4195

selhero: Fix heap-use-after-free

---

.circleci/config.yml

Apparently docker image bug build bad executables is fixed now and this patch actually makes it faulty again.

Hopefully fix Amiga build.

---

Source/engine/render/scrollrt.cpp

If FPS < 100, print it with 1 decimal point.
Useful for measuring performance impact on low-end devices.

Show FPS up to 1 decimal point

---

Source/engine/render/dun_render.cpp
Source/engine/render/dun_render.hpp
Source/engine/render/scrollrt.cpp
Source/utils/attributes.h

We notice that masks can be described by 2 parameters:
1. Whether they have 0 or 1 as their high bits.
2. Whether they shift to the left or to the right on the next line.
Describing masks this way allows us to lift them to template variables and simplify the code.
We also avoid handling the mask in the `RenderLine` loop entirely.
We also note that some masks are only valid for certain tile types:
The `Left` mask can only be applied to `LeftTrapezoid` and `TransparentSquare`.
The `Right` mask can only be applied to `RightTrapezoid` and `TransparentSquare`.
The `Left/RightFoliage` masks can only be applied to `TransparentSquare`.
We now only instantiate the render function templates for the valid tile type / mask combinations.
Also fixes a foliage rendering bug: Transparent foliage pixels …

dun_render: Overhaul mask handling

---

Source/engine/render/dun_render.cpp

As we recently confirmed, Square and Left/RightTriangle primitives never use masks other than Transparent and Solid.
Simplify the code to take advantage of that.

dun_render: Simplify non-masked primitives

---

test/pack_test.cpp

Packed items are supposed to be little-endian even on big-endian systems. Makes all test fixtures little-endian.
Refs #5573

pack_test: Make fixtures little-endian on BE

---

Source/engine/render/scrollrt.cpp

Switching between software and hardware cursor could cause a glitch as described in #5560.
Fixes #5560

Remove software cursor state for hardware cursor

---

.github/workflows/s390x_qemu_big_endian_tests.yml

Run tests on a big-endian platform (s390x) via qemu.
The test suite takes ~50m to run so we only trigger it manually.
There are a few failing tests: https://github.com/diasurgical/devilutionX/actions/runs/3646395402/jobs/6157431868
Refs #5573

GitHub Actions: Test on a big-endian platform

---

.gitignore
Source/CMakeLists.txt
Source/effects.cpp
Source/effects.h
Source/effects_stubs.cpp
Source/engine/sound_position.cpp
Source/engine/sound_position.hpp
Source/monster.cpp
test/effects_test.cpp
tools/Dockerfile.s390x
tools/run_big_endian_tests.sh

Fixes `effects_test` on big-endian, which currently builds with `-DNOSOUND` (to reduce build time).
Also adds a tool to run tests on a big-endian system using an Alpine s390x Docker container.
Fixes #5588

Use real `CalculateSoundPosition` with NOSOUND

---

Source/utils/language.cpp
Source/utils/sdl2_to_1_2_backports.h

Fixes very slow translation loading from MPQs.
Compressed MPQs files are very slow to seek in.
If the RWops is and MPQ, load the whole file first.

language.cpp: Fix slow translation loading when using MPQ

---

Source/diablo.cpp
Source/init.cpp
Source/utils/language.cpp
Source/utils/language.h
tools/measure_timedemo_performance.py

This allows forcing the locale without changing the settings.
The `forceLocale` option also lets us avoid changing the locale in settings if fonts.mpq is missing, fixing the following scenario:
1. System locale is ja
2. Launch the game -- fonts are missing
3. Close the game, download fonts.mpq
4. Launch the game again -- it is now in English because the settings have changed

Add a `--lang` command line argument

---

Source/items.cpp

Introduced in 1.4.0, and reported by user Exocet on Discord.
> how about observed issue with spellbooks on ground (sometimes, not always, but eventually) morphing into different spellbooks when i repeatedly leave/enter town? I don't see any other open issues which seem related.
> 
> windows hellfire multiplayer/loopback 1.4.1
> 
> it can be replicated easily enough ... go into cata, open a tp, then keep entering/exiting hell shortcut in town ... each visit to town buy whatever books adria sells and dump on ground in a big pile ... eventually you'll come back to town and see one or several books have changed
In the case of pinned books, the random number which would normally have determined the `_item_indexes` in `RndWitchItem()` needs to be burned because the book types are hardcoded.

[Hellfire] Prevent morphing of books from Adria's shop

---

Source/engine/render/dun_render.cpp
Source/engine/render/dun_render.hpp
Source/engine/render/scrollrt.cpp
Source/engine/surface.hpp

1. Now that we pass the mask into `RenderTile`, we no longer need to pass `levelPieceId`.
2. Make `dstPitch` a `uint16_t` instead of `int`.

dun_render: Remove unused argument from `RenderTile`

---

Source/engine/animationinfo.cpp
Source/engine/animationinfo.h

Fixes #5608
When the preview frame was shown the (nearly) the entire previous game tick `int8_t` can overflow.
@glebm it would be nice if you could check this again, cause this doesn't often occur on my machine. I verified and tested it with the timedemo.

Fix preview frame shown fragment overflow

---

Source/movie.cpp

Clears backbuffer state after a movie has been played.
Fixes #5611

Fix cursor glitch after playing an in-game movie

---

3rdParty/SDL2/CMakeLists.txt
android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
android-project/app/src/main/java/org/libsdl/app/SDL.java
android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
android-project/app/src/main/java/org/libsdl/app/SDLAudioManager.java
android-project/app/src/main/java/org/libsdl/app/SDLSurface.java

The previous SDL2 update in #5601 did not include the updated Android code.
This one does and should hopefully fix the Android startup issue pointed out by @Trihedraf in #5601.
With this new version, we get further improved gamepad support and audio device selection on Android.

Update SDL2 and SDL2 Android code

---

CMake/platforms/rg99.cmake
CMakeLists.txt
Packaging/OpenDingux/build.sh
Packaging/OpenDingux/package-opk.sh
Packaging/OpenDingux/profile-generate.sh

A PGO'd binary can be built as follows:
1. Build with `-DDEVILUTIONX_PROFILE_GENERATE=ON`.
3. Run the timedemo.
4. Build with `-DDEVILUTIONX_PROFILE_USE=ON`.
By default, the profile directory is at `${HOME}/devilutionx-profile`
Example for the RG99:
```bash
TOOLCHAIN=/opt/rs90-toolchain Packaging/OpenDingux/build.sh rg99 --profile-generate
scp -O build-rg99/devilutionx-rg99.opk rg99:/media/sdcard/apps
scp -r -O rg99:/media/data/local/home/devilutionx-profile /tmp/devilutionx-profile
TOOLCHAIN=/opt/rs90-toolchain Packaging/OpenDingux/build.sh rg99 --profile-use --profile-dir /tmp/devilutionx-profile
scp -O build-rg99/devilutionx-rg99.opk rg99:/media/sdcard/apps
```
Profile data for RG99 (takes hours to collect because it runs very slowly, even on a max-mem firmware): …

CMake: Add options for profile guided optimization

---

Source/debug.cpp
Source/msg.cpp
Source/msg.h

In singleplayer reseting `_pLvlVisited` is good enough, but in multiplayer the delta levels are used.
This pr changes the `restart` debug command to also reset the delta level.

Make debug command restart compatible with multiplayer

---

3rdParty/zlib/CMakeLists.txt

1. Hopefully this will make the Xbox One build less flaky. Refs #5616.
2. The second URL will work even when zlib releases a new version.

zlib: Add an alternative URL

---

Source/engine/animationinfo.cpp

Fixes issue #5624.
Issue stems from #5469. The `setNewAnimation` function divides by 0 when processing hit recovery animations for Balrog type monsters. Previously, floats were used and dividing by 0 did not cause a crash. With integers, we are unable to divide by 0 since an exception is thrown.

Bugfix: AnimationInfo integer division by 0

---

CMakeLists.txt

The --strip-all argument to the strip command breaks the build on BSD strip. Removing it altogether for now so it doesn't break non GNU builds. Possibly can be improved with selecting the proper argument depending on the implementation of strip.

Remove GNU style strip args

---

Source/utils/language.cpp

The locale code used the `forceLocale = "en"` fallback when the locale was set to English, so switching from English did not actually change the language.

Fix switching locale from English

---

Source/missiles.cpp
Source/monster.cpp
Source/monster.h

This PR is meant to correct an alleged bug as a result of an alleged oversight in the development of Diablo.
The evidence:
To preface, the item power `ISPL_NOHEALMON` was originally used for the suffix "vileness" as shown here: https://gitlab.com/moralbacteria/diablo-prdemo-decomp/-/blob/main/src/itemdat.cpp on line 295. The intent was for this item power to set `MFLAG_NOHEAL`, preventing monsters from regenerating life.
This bug was corrected in Hellfire (https://github.com/diasurgical/devilution/blob/master/Source/missiles.cpp on line 753). 
Per Blighthorn and staphen, there is some evidence that this was an oversight. It appears that it's entirely possible that `plr[pnum]._pIFlags & MFLAG_NOHEAL` may have been used rather than `plr[pnum]._pIFlags & ISPL_NOHEALMON`. Since `_pIFlags` is …

Remove No Monster Heal from Fire Arrows

---

Source/engine/random.hpp
Source/monster.cpp

Instead of modifying the damage value by reference
This does introduce a slight behaviour change, it was previously possible for reflect to only apply 12% of the incoming damage (`GenerateRnd(10)` returns `-8`, adding 20 gives 12). Now it'll always be between 20% and 29% inclusive.

Update CheckReflect to return applied damage

---

Source/msg.cpp

Even in vanilla, `DMonsterStr::_mdir` was only being written, and wasn't used for anything. Removing it eliminates the bug described on line 2666 of msg.cpp, although the bug probably wasn't affecting anything.

Remove unused _mdir variable from monster deltas

---

Source/DiabloUI/settingsmenu.cpp

The number of settings did grow and make the settings menu also very large.
This pr tires to address this with adding a submenu for each category.
Example Video:
https://user-images.githubusercontent.com/25415264/210664850-2a898bb8-7f1e-4ae6-9e88-e79b056dca24.mp4

Settingsmenu: Create submenus for each category

---

CMake/platforms/rg99.cmake
Packaging/OpenDingux/build.sh

From GCC documentation:
> Perform interprocedural pointer analysis and interprocedural modification and reference analysis.
> This option can cause excessive memory and compile-time usage on large compilation units.
> It is not enabled by default at any optimization level.
Also forces the CMake generation to `make` because `ninja` gets into an infinite loop for some reason on my laptop.

rg99: Enable `-fipa-pta`

---

Source/DiabloUI/ui_flags.hpp
Source/engine/render/text_render.cpp
Source/panels/spell_list.cpp

Looks closer to the original and much simpler. Will be used in floating numbers as well

Use outline for spell icon texts

---

.circleci/config.yml
.github/workflows/Linux_x86.yml
.github/workflows/Linux_x86_64_SDL1.yml
.github/workflows/Linux_x86_64_test.yml

Ubuntu 22.04 for all GitHub CI builds and Debian Buster for the CircleCI build.
Fixes #5655

 Update Linux builds to more recent OS versions 

---

CMakeLists.txt

DevilutionX already does not build on 3.13 because of libzt.
libzt uses the `TARGET_OBJECTS` generator expression with non-OBJECT libraries. This is only supported in CMake 3.15+:
https://gitlab.kitware.com/cmake/cmake/-/merge_requests/3178

Bump `cmake_minimum_required` to 3.15

---

Source/DiabloUI/selgame.cpp

While the panel said the public game was incompatible, you could still try and join the game, which then caused the game you were trying to join to "hourglass" for the players in it. This only allows SNetJoinGame to be called for public games if host and client have compatible game versions.
Also fixed what may have been a bug with using *m_game_data (found by @StephenCWills), since it does not look like this was referring to the Gamelist gameData, but what is created locally.

Removed ability to try and join incompatible ZeroTier games

---

.github/workflows/Linux_x86_64_test.yml

@glebm looks like there is still an issue with coverage not working on Ubuntu 22.04

Fix code coverage

---

Source/spelldat.h

56 bytes -> 40 bytes
Can be optimized further by reordering the fields and merging some flags.

Reduce the size of SpellData

---

Source/storm/storm_svid.cpp
Source/utils/aulib.hpp
Source/utils/soundsample.cpp

Each resampler allocates an input buffer and an output buffer.
Since we create ~100 audio stream objects (1 per `sfx_MISC` effect), the memory cost of these buffers adds up.
Avoids creating a resampler when the audio sampler rate matches the output sample rate. This is mostly the case when the output sample rate is 22050.
/cc @realnc

Audio: Avoid creating same-rate resamplers

---

3rdParty/libzt/CMakeLists.txt

Related to #5689. I don't know if this should resolve it, but I should mention it at least.

Update libzt to include compile-time detection for ARMv8a crypto extensions

---

Source/options.cpp
Source/options.h
Source/stores.cpp
Source/stores.h
Source/utils/sdl_bilinear_scale.cpp
Source/utils/sdl_bilinear_scale.hpp

Adds item graphics to the store menu, based on mockups posted in #1359.
Graphics are downscaled by half to fit in the available space to the left of the item description. The `BilinearDownscaleByHalf8()` function was provided courtesy of @glebm. I had to modify it a bit to handle transparency.
This resolves #1359.

Add item graphics to store menus

---

Source/stores.cpp

A couple Discord users expressed support for shifting item graphics up so that the vertical center of the graphic is aligned with the center of the text next to it.
Before:
After:

Align item graphics with the center of the store text

---

Source/effects.cpp
Source/effects.h

Reintroduce `LS_ACIDS`/`acids2.wav` that was removed in #5692.
When `LS_ACID` is called [`RndSFX`](https://github.com/diasurgical/devilutionX/blob/55dc2315bc195928cddc8fc13f144e6adc7742f2/Source/effects.cpp#L1033) can increase it's index by 1.
Before #5692 it was `LS_ACIDS` after it is `LS_APOC`.
That means `LS_ACIDS` is still used but it wasn't quite obvious.

Add used acids2.wav back to game

---

Source/diablo.cpp
Source/qol/itemlabels.cpp
Source/qol/itemlabels.h

Fixes #5571
How does the bug happen:
1. Player initializes level transition
2. Player clicks right mouse button
3. New level is loaded. First game loop is processed.
4. `HandleMessage` is called. It sees the right mouse click sdl event and adds `CMD_SPELLXY` Message. Here are the old coordinates used (`cursPosition`). The coordinates get updated in `ProcessInput` that is called after `HandleMessage`.
With this pr `CheckCursMove` is called after every level change/load and before the normal game loop runs.
This ensures that that all cursor related information are initialized correctly.
`ResetItemlabelHighlighted` and `sgbMouseDown` must be called so that `CheckCursMove` always calculates a new value (even if previous a item was selected or the player locked on a target).
Alternative fixes: …

Recalculate cursor position after level change

---

Source/cursor.cpp
Source/cursor.h
Source/stores.cpp

Prepare downscaled sprites once instead of doing it on every frame.
Note that we do this lazily in `StartStore` rather than `SetupTownStores` because we need the palette blending table to be available when downscaling.

Store graphics: Scale sprites only once

---

Source/engine/render/scrollrt.cpp
Source/qol/itemlabels.cpp

Before:
After:
Also disable ground item outlines on hover when in store.

Disable item labels when in store

---

Source/utils/static_vector.hpp

`std::aligned_*` types are deprecated in C++23 per https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p1413r3.pdf

`StaticVector`: Replace `std::aligned_storage_t`

---

Source/cursor.cpp
Source/cursor.h
Source/stores.cpp

We generate separate downscaled sprites for the red versions because simply applying TRN after downscaling leads to some non-red pixels (because of blending during downscaling).

Store items: Draw unusable items in red

---

Source/stores.cpp

Based on top of #5703
Previously it looked like this:

 Store items: Render 1x1 items at full size 

---

Source/options.cpp
Source/options.h

Corrected a spelling error in the "Show Item Graphics in Stores" description (desription -> description)

Fixed spelling errors

---

Source/cursor.cpp
Source/utils/sdl_bilinear_scale.cpp
Source/utils/sdl_bilinear_scale.hpp

Rather than allocating surfaces on every loop iteration, reuse the same 2 surfaces.
Also skips creating half-size sprites for 1x1 items.
All of the half-sprite data takes about 140 KiB (not a big deal in town, which uses less memory to begin with).

`CreateHalfSizeItemSprites`: Reuse surfaces

---

CMake/functions/devilutionx_library.cmake

Assuming CI passes, this should help modders who want to change their project name in `CMakeLists.txt`.

Use PROJECT_SOURCE_DIR instead of referencing the project name

---

CMake/platforms/rg99.cmake

Another option that improves performance. From GCC documentation:
> Stream extra information needed for aggressive devirtualization when running the link-time optimizer in local transformation mode. This option enables more devirtualization but significantly increases the size of streamed data. For this reason it is disabled by default.

rg99: add -fdevirtualize-at-ltrans

---

Source/msg.cpp
Source/panels/spell_list.cpp
Source/spelldat.h

LAST was set to SpellType::Invalid instead of SpellType::Charges
#5674

Fix bug in ef3a57b7

---

Source/player.cpp

`AddPlrExperience()` is called whenever the player performs an action that would give them more experience points. This is unncessary when the player is at the hardcoded maximum already. `return` added near beginning of function, as well as some magic numbers replaced.

Optimize AddPlrExperience()

---

Source/player.cpp
test/animationinfo_test.cpp
test/player_test.cpp

I have always perceived this mechanic to be a bug or an oversight that Blizzard simply didn't need to care about.  Gameplay wise it makes no perceivable difference.  My reasoning is that the description of Harmony says "Fastest", clearly implying that this is the fastest recovery bonus that is attainable for a given character and also an indication that the bonus from these affixes is not cumulative.

Remove "Zen" hit recovery

---

Source/missiles.cpp

With #5731 pulled in, we can now set the firebolt damage on creation. This lets the damage of each guardian firebolt be randomized, rather than randomizing the damage once upon creation of the guardian.

Move damage formula for guardian firebolt to GuardianTryFireAt so each firebolt damage is randomized.

---

Source/missiles.cpp

@kphoenix137 pointed out on Discord that the Mana Shield spell didn't consume mana in Diablo 1.09 if Mana Shield was already active. This seems to have originally been implemented as a special case in `AddMissile()` which would completely skip initialization of the Mana Shield missile.
https://github.com/diasurgical/devilution/blob/50c9b533cf949e7a8e7cc61bdc539a8d60c19a4c/Source/missiles.cpp#L3598-L3609
The fact that this code was not present in Hellfire suggests that Blizzard probably added this logic in one of their patches. The 1.07 patch notes suggest that this code could have been their solution to an entirely different issue.
> Prevented repeated castings (128 or more) of Mana Shield from disabling the casting of any more spells.
Even so, it seems reasonable to have the spell fizzle …

Don't consume mana when Mana Shield is already active

---

Source/monster.cpp

Recently saw a recording on Discord where a Barbarian with 50% resist in Hell/Hell was consistently receiving exactly 2 damage from every Blood Star missile. Testing reveals this was a bug, introduced by #5731. That PR interprets non-zero damage as a custom amount provided to the missile, like in the case of the Guardian spell. This PR uses zero to indicate that there is no custom damage amount for missiles produced by monsters, apart from Diablo's Apocalypse attack.
I checked all the missile types returned by `GetMissileType(MonsterAIID)`, and I wasn't able to determine why 4 was being used as the default missile damage for monsters. Maybe the original developers used it for testing at some point during development. 🤷

Change default monster missile damage to zero

---

Source/items.cpp

Uses the Staff Spell level instead of Book Level. Using Book level results in some spells using -1 in the RNG, resulting in staves losing 50% of charges when recharged at 0 charges consistently, when the spell does not have a book counterpart. Performed testing with a clvl 50 Sorcerer. The results were very similar between changed and unchanged, however recharging a Staff of Resurrect was far less penalizing, and recharging a Staff of Apocalypse was slightly less penalizing. Tests were done in Diablo not Hellfire.

Use Staff Spell level for Staff Recharge

---

Packaging/windows/CMakePresets.json

It seems the tests aren't running in the MSVC CI jobs since we made the switch to `RelWithDebInfo`.
https://github.com/diasurgical/devilutionX/blob/25e9b7320d7a265dfec1cc9de81d55bb3dd25716/CMakeLists.txt#L161-L166

Reenable tests on MSVC build

---

Source/options.cpp
Source/options.h

Based on comments in #5749. If `Fit to Screen` is on, display resolutions using only the height of the resolution (for example, 480p or 720p).
* Force the resolutions list to refresh when the `Fit to Screen` setting is changed.
* If `Fit to Screen` is on, force all resolutions with the same height to also have the same width. This way, the call to `std::unique()` will filter the list to one resolution per height.
* Nintendo 3DS enables the `Fit to Screen` setting even though it uses SDL1. However, the setting works differently on that platform so it is intentionally excluded from this new logic.

Display resolution height when FitToScreen is on

---

Source/effects.cpp
Source/effects.h
Source/items.cpp

Tavern Sign was set to use the inventory placement sound, rather than the flip sound.
What it sounds like with the fix:
https://user-images.githubusercontent.com/68359262/216803557-320a096b-4676-4c1a-b700-1a5addcbd4ad.mp4

Fix wrong flip sound: Tavern Sign

---

Source/misdat.cpp

Fixes an issue introduced by #5747 where Guardian appears to be rather twitchy during its idle animation. Reported by @kphoenix137 on Discord. Appears to have been just a typo (4 frames instead of 14 frames).
https://user-images.githubusercontent.com/9203145/216851041-97ae5603-4f4a-4261-a009-35420fb9d3b6.mp4

Fix length of Guardian idle animation

---

Source/missiles.cpp

Discord user Silmaril (possibly better known as FireIceTalon) reported an issue where the Flame Wave spell was not rendering when aimed along diagonals. This can be observed in the following video around 5:50.
https://youtu.be/SL1uSZxrxII?t=350
It seems that Flame Wave missiles have a bit of a quirk where the position of the missile is adjusted one tile to the south and then readjusted one tile north only while the game logic is processing the missile. DevX preserved the logic to adjust the tile's position south, but not the northward readjustment during processing. I assume it was probably removed because `missile.position.start` is used when updating the missile's position so the move-missile logic was correcting the southward adjustment. However, DevilutionX's missile collision …

Adjust position of Flame Wave missiles before processing

---

Source/items.cpp

Fixes #5757
After #5196 `currlevel` is always identically with `setlvlnum` for set/quest-maps.
But `currlevel` is used in [`ItemsGetCurrlevel`](https://github.com/diasurgical/devilutionX/blob/98294e0ad57865331202b916e2f71cd7fa6c82ae/Source/items.cpp#L388-L397) to determinate the value of the item.
With this pr we always use the entry level of the set/quest-map for determinating the value of a item.
Note:
This can also happen in vanilla if you open a town portal in the set/quest-map, go to town, go back and open a chest/kill a monster.
See #5196 for further analysis. :wink:
Thanks @Chance4us for reporting the issue. 🙂

Fix item levels for set/quest-maps

---

Source/engine/events.cpp
Source/options.cpp
Source/options.h

When the game swaps from the `GameEventHandler` to the `DisableInputEventHandler` during loading screens, the event handler will no longer forward input events to the padmapper. This causes any buttons which are pressed before entering a loading screen and then released during the loading screen to be stuck in the "pressed" state after the loading screen completes, until they are pressed and released again. This PR forces padmapper to trigger release actions and clear "pressed" state for all buttons whenever the event handler is swapped to ensure that padmapper state gets reset whenever one of these transitions occurs.
Incidentally, this is also a problem for keymapper, but keymapper doesn't save "pressed" state so there's no convenient way to clear it. The only keymapper action affected …

Clear padmapper state when changing event handlers

---

.github/workflows/Windows_MinGW_x64.yml

This swaps the order of exe/data commits for https://github.com/artifacts-storage/devilutionx-artifacts (Already changed it in storage repo)
If data comes first, then we can easily access up to date (for exe commit) devilutionx.mpq by doing "View at this point in history" on github and going to data folder

reverse data/exe order for artifacts storage

---

Source/engine/assets.hpp
Source/engine/load_cl2.hpp
Source/engine/load_file.hpp

For `MultiFileLoader` and `LoadMultipleCl2Sheet`, we now open one file at a time.
This can help on platforms that limit the number of concurrently open files, such as the PS2.

Open fewer files concurrently at load time

---

Source/DiabloUI/settingsmenu.cpp
Source/engine/render/text_render.cpp
Source/engine/render/text_render.hpp

For center or right alignment, the lines past the first line were aligned incorrectly. The alignment after the first line was based on the width of the format string.
We do not currently render any such strings, the bug was discovered by @kphoenix137 while working on a feature.

Fix multiline `DrawStringWithColors` alignment

---

Source/dvlnet/base.cpp
Source/dvlnet/base.h

The short explanation for this is that it relaxes the tolerance for how long the client will wait for a remote client's response before displaying the hourglass to the user. Turns are processed by every client on 400-millisecond intervals, and the hourglass will be displayed to the user if the local client hasn't received all of the remote clients' turns when that 400-millisecond timer comes up. By increasing the `defaultturnsintransit` to `2`, clients will have an extra turn in the queue to process while waiting on the second turn in transit.
I haven't done any latency testing yet to see what the new limits are compared to the old ones, but I did notice that I no longer see the hourglass when a client warps to another dungeon level. I suppose it may still happen when playing with others …

Relax latency requirements for online games

---

Source/capture.cpp
Source/debug.cpp
Source/dvlnet/tcp_client.cpp
Source/engine/assets.hpp
Source/engine/demomode.cpp
Source/mpq/mpq_writer.cpp
Source/mpq/mpq_writer.hpp
Source/options.cpp
Source/pfile.cpp
Source/utils/endian_stream.hpp
Source/utils/file_util.cpp
Source/utils/file_util.h
Source/utils/logged_fstream.cpp
Source/utils/logged_fstream.hpp
test/file_util_test.cpp
test/writehero_test.cpp

1. Replaces `fstream` with `FILE *`.
2. Replaces `sstream` and `istream_buf` with `SplitByChar`.
Reduces binary size by ~2 KiB and may improve compatibility with oddball systems (e.g. PS2).

Use C FILE instead of C++ streams throughout

---

Source/msg.cpp

Note that in a few places it is always being set to 0.
This is probably wrong and should instead be passed in the network message as a parameter.
For now, this at least fixes the crash observed in #5791.
/cc @obligaron

msg.cpp: Always set `spellFrom`

---

CMake/platforms/rg99.cmake
CMakeLists.txt

Enable these options for all platforms that use GCC.
They do not seem to significantly affect build times on our codebase, while resulting in a slight 2-3% performance increase on low-end devices, such as RG-99.

gcc: -fipa-pta -fdevirtualize-at-ltrans

---

android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java

On Android, this enables the game to use secondary external storage if the user moves all their data/config/save files to it.

[Android] Select the external files directory judiciously

---

Source/qol/stash.cpp

Prevents overflow of the stash gold that happens around 2B gold.  The solution was provided during a discussion on discord.  Currently this change causes the game to crash when accessing the stash in a debug build as outlined here https://github.com/diasurgical/devilutionX/issues/5474.  I was able to test building a release version as well as implementing https://github.com/diasurgical/devilutionX/pull/5475 in debug (and setting a lower limit for the test).  Both placing gold above the limit as well as Ctrl + clicking gold to move it caused no issues and the game behaved as expected, limiting placing gold above the limit.

Stash Gold Limit

---

android-project/app/src/main/java/org/diasurgical/devilutionx/DataActivity.java
android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java
android-project/app/src/main/java/org/diasurgical/devilutionx/ExternalFilesManager.java
android-project/app/src/main/java/org/diasurgical/devilutionx/ImportActivity.java

It seems that the various activities weren't sharing their `externalDir` state. This extracts the logic for managing files in external storage to the `ExternalFilesManager` class so that all activities can share the same logic.

[Android] Use correct external files dir in all activities

---

Source/diablo.cpp
Source/nthread.cpp
Source/nthread.h

Check if we missed a game tick.
This can happen when we run a low-end device that can't render fast enough (typically 20fps).
If this happens, try to speed-up the game by skipping the rendering.
This avoids desyncs and hourglasses when running multiplayer and slowdowns in singleplayer.
Edge-case:
If the game runs so slow, that we can't calculate the gamelogic in 50ms (one game tick) no frames will be rendered.
But if this happens the game should be unplayable anyway.
<details><summary>Comparison video</summary>
Comparison video with a ~10 fps (for testing I added a `_sleep(100);` in `DrawAndBlit`).
https://user-images.githubusercontent.com/25415264/219756349-01cbef34-8cf7-41b7-8748-116a8f994ed3.mp4
https://user-images.githubusercontent.com/25415264/219756458-23f09e44-0cd6-41ff-95fb-41d1aec …

Skip rendering on low-end devices

---

Source/inv.cpp

Fix alignment for 2x2 armor sprite in the chest slot

---

Source/diablo.cpp

Some of the initialization steps in `DiabloInit()` did not require the game data to be loaded in order to perform them. This moves those steps earlier in the startup process, providing a couple benefits.
* Errors that occur while loading game data couldn't display the proper error dialog because the main window hadn't been created yet. This change prioritizes window creation so the error dialog can be displayed for those errors.
* `SaveOptions()` can be called after calling `ReadOnlyTest()` and before attempting to load game archives, allowing for #5796 to be resolved.
Here is some proof that the error dialog still works properly for `ReadOnlyTest()` despite changing the order of events.
Also, here is an error dialog that didn't previously show up properly because the main window was …

Perform some basic initialization before loading game data

---

Source/utils/language.cpp

After clicking OK on the error message, the game proceeded to try to display the main menu in Japanese, resulting in a crash. Fixes #5818.

Fix crash with locale=ja and missing fonts.mpq

---

Source/monster.cpp
Source/quests.cpp
Source/quests.h

Monster `talkmsg` and `flags` is not synced in multiplayer.
In multiplayer `_qvar1` is used to sync Gharbad's state.
Remaining quests:
- Zhar the Mad
- Warlord of Blood
- Lachdanan

Multiplayer: Enable Gharbad the Week Quest

---

Source/monster.cpp
Source/quests.cpp
Source/quests.h

Monster `talkmsg` and `flags` is not synced in multiplayer.
In multiplayer `_qvar1` is used to sync Zhar's state.
Remaining quests:
- Warlord of Blood
- Lachdanan

Multiplayer: Enable Zhar the Mad Quest

---

Source/diablo.cpp

`gbIsHellfire` and `gbIsSpawn` are initialized to `true` in `LoadGameArchives()` based on the set of MPQs the game client detects in the data directory. This enables us to select appropriate defaults based on the existence of specific MPQs and then override them with the INI settings in `DiabloInit()` if necessary. Therefore, these statements that initialize `gbIsHellfire` and `gbIsSpawn` from startup options and INI settings need to be executed after `LoadGameArchives()`.
Also, in hindsight, it just seems appropriate to initialize these Diablo-specific variables in `DiabloInit()` rather than `ApplicationInit()`.
This resolves #5824

Move initialization of gbIsHellfire back to DiabloInit()

---

Source/levels/drlg_l4.cpp
Source/monster.cpp
Source/objects.cpp
Source/quests.cpp
Source/quests.h

Monster `talkmsg` and `goal` is not synced in multiplayer.
In multiplayer `_qvar1` is used to sync Warlord's attacking state.
This additional `_qvar1` should not interfere with vanilla/old saves.
I added a enum for all quest states.
Remaining quest:
- Lachdanan

Multiplayer: Enable Warlord of Blood Quest

---

Source/items.cpp
Source/monster.cpp
Source/quests.cpp
Source/quests.h

Monster `talkmsg` and `goal` is not synced in multiplayer.
In multiplayer `_qvar2` is used to sync Lachdanan's state.
I changed where the unique is spawned (from `MonsterTalk` to `TalktoMonster`), so I can check that only one player (that talks to lachdanan) spawns the Veil of Steel.
Remaining quest:
- None 🚀🎉
... but many bugs. 😁 
Next step after this pr is adding a toggle for switching between classic multiplayer quests and singleplayer quests in multiplayer.

Multiplayer: Enable Lachdanan Quest

---

Source/engine/sound.cpp

When streaming mp3, the logic used the path to the wav file and passed `true` for `isMp3`. This explains why the mp3 decoder didn't recognize it as an mp3 file, because it wasn't one.
This resolves #5832

Fix the path used for streaming in LoadAudioFile()

---

Source/multi.cpp
Source/multi.h
Source/options.cpp
Source/options.h
Source/quests.cpp
test/drlg_l1_test.cpp
test/drlg_l2_test.cpp
test/drlg_l3_test.cpp
test/drlg_l4_test.cpp
test/drlg_test.hpp

Fixes #926
Now all quests should be implemented and (not much tested) working.
This pr adds a option that allows to specify how quests are handled in multiplayer (currently in the settings menu under gameplay).
The default is the vanilla behavior (full quests off).
The server decides how the quests are handled (same behavior as friendly fire or town jogging).
Many bugs are expected and some fine tuning is still needed (quest rewards discussion, how to handle some quests stats, ...).
But when this pr is merged everyone can start playing & testing the quests. 🙂

Add option to enable singleplayer quests in multiplayer

---

Source/msg.cpp
Source/objects.cpp
Source/objects.h

Fixes #5184
Now `CMD_DOORCLOSE` is stored in delta messages.
When we found this message we set `_oTrapFlag`.
And when `_oTrapFlag` is not set the trap will not activate.

Multiplayer: Prevent trapped doors to fire twice

---

Source/diablo.cpp
Source/inv.cpp
Source/items.cpp
Source/items.h
Source/levels/drlg_l1.cpp

Fixes #4193
First commit adds helper function for all places that check for the corner stone.
Second commit removes it for multiplayer.

Disable corner stone of the world in multiplayer

---

Source/sync.cpp

Related to #5541, but in this case the client attempts to send a sync packet immediately after updating `player.plrlevel` using the monster data from the previous level. This causes some weird issues in Multiplayer games if you leave active monsters on a level before using the stairs, like monsters warping to the stairs out of nowhere with incorrect HP values.

Don't send monster data while warping

---

Packaging/windows/CMakePresets.json
Source/mpq/mpq_writer.cpp
Source/options.cpp
Source/utils/file_util.cpp
Source/utils/file_util.h
Source/utils/paths.h
test/file_util_test.cpp

With this, we no longer require `std::filesystem` support to create the save file directory when it does not exist.
Note that by default the save file directory exists because it is created by SDL, so this is mostly useful on platforms that override the save directory or use `UNPACKED_SAVES`.

file_util: Implement `RecursivelyCreateDir`

---

Source/objects.cpp

`InfoString` is a `StringOrView` and libfmt master does not know how to print that. Pass it a `string_view` instead.

Fix a libfmt compilation error on master

---

Source/missiles.cpp

Fixes #5872
Flash did not hit north east direction but instead hit north direction twice. 😉 
Was introduced with #5311

Fix Flash hits north east direction

---

Source/engine/palette.cpp
Source/engine/render/text_render.cpp
Source/items.cpp
Source/loadsave.cpp
Source/monster.cpp
Source/pfile.cpp
Source/player.cpp
Source/utils/format_int.cpp

Removes most `FMT_COMPILE` calls.
`FMT_COMPILE` results in better performance but larger code size.
Removes `FMT_COMPILE` calls for places that are called infrequently, i.e. not on every frame.
RG-99 binary size reduced by ~4 KiB.

Remove `FMT_COMPILE` in "cold" places

---

Source/capture.cpp

We only used it in one place and it doesn't work on Amiga GCC-6 with the latest libfmt master (https://github.com/fmtlib/fmt/issues/3344)
Also handles the case where `localtime` returns `nullptr`.
As a bonus, this reduces RG-99 binary size by 32 KiB (chrono formatting is a bit heavy it seems).

Avoid dependency on fmt/chrono

---

3rdParty/libfmt/CMakeLists.txt
Source/capture.cpp

At first I tried to bump it to v9.1.0 but that had some issues.
Based on top of #5879

Bump libfmt to the latest master

---

Source/engine/render/scrollrt.cpp

In PvP duels infravision is always used/wanted.
Currently there are scrolls of infravision or murky pools needed.
With this pr both are not needed, cause the game always uses infravision logic in pvp areans (only for players).
Noticed when watching pvp stream and infravision from murky pools always runs out (and sometimes was forgotten to get again).

Always use infravision in Arenas

---

Source/qol/floatingnumbers.cpp
Source/utils/str_cat.cpp
Source/utils/str_cat.hpp
test/CMakeLists.txt
test/str_cat_test.cpp

1. Use `fmt::format_int` directly instead of parsing a format string.
2. Use `AppendStrView`.
3. Define the varargs versions using fold expressions when available.
4. Add tests.

StrCat improvements

---

.github/workflows/Android.yml
.github/workflows/Linux_x86.yml
.github/workflows/Linux_x86_64_SDL1.yml
.github/workflows/Linux_x86_64_test.yml
.github/workflows/MacOSX.yml
.github/workflows/iOS.yml

We're hitting the GitHub cache limit because we create a new cache for every commit.
Reuse the same cache instead.

GitHub CI: Remove git SHA from cache key

---

Source/items.cpp
Translations/bg.po
Translations/cs.po
Translations/da.po
Translations/de.po
Translations/devilutionx.pot
Translations/el.po
Translations/es.po
Translations/fr.po
Translations/hr.po
Translations/it.po
Translations/ja.po
Translations/ko.po
Translations/pl.po
Translations/pt_BR.po
Translations/ro.po
Translations/ru.po
Translations/sv.po
Translations/uk.po
Translations/zh_CN.po
Translations/zh_TW.po

* For some reason, in `items.cpp`, `"Select from spell book, then\ncast spell to read"` was at some point changed to `"Select from spell book, then\ncast to read"`, breaking most of the translations.
* Update translations to be a single string when expected

items.cpp: fix inconsistent localization for miscellanous items

---

CMake/Dependencies.cmake
CMakeLists.txt
Source/CMakeLists.txt

Introduce a `SUPPORTS_MPQ` variable and use it throughout. Also disables fetching bzip2 when MPQ support is disabled.

CMake: Cleanup no-mpq config

---

.github/workflows/Android.yml
.github/workflows/Linux_x86.yml
.github/workflows/Linux_x86_64_SDL1.yml
.github/workflows/Linux_x86_64_test.yml
.github/workflows/MacOSX.yml
.github/workflows/cache-cleanup.yml
.github/workflows/iOS.yml
.github/workflows/s390x_qemu_big_endian_tests.yml

GitHub caches are immutable, so #5883 was wrong (caches were never updated).
Goes back to the previous caching strategy but with a cleanup workflow to delete caches for merged/closed PRs.
The cleanup code comes from the example in GitHub docs: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries

GitHub CI: Fix cache strategy

---

Packaging/OpenDingux/README.md
Packaging/OpenDingux/build.sh
docs/building.md

1. Creates the missing `shared-dl` directory.
2. Unsets some environment variables that interfere with buildroot.
3. Disables `BR2_PER_PACKAGE_DIRECTORIES`, which prevented us
from using the partial sysroot build.
Also documents the `TOOLCHAIN=...` option in docs/building.md.
/cc @TmDobbin you will need to `rm -rf ~/devilutionx-buildroots` for this to work once it's been merged

Fix OpenDingux/build.sh buildroot prep

---

Source/capture.cpp

The standard defines `tm_year` to be the number of years since 1900.
This resolves #5905

Fix year in screenshot file names

---

Source/engine/demomode.cpp

Otherwise it can end up as `-1`, triggering the `VirtualGamepad` input type (-1 is `SDL_TOUCH_MOUSEID`).

demomode.cpp: Set `mouse.*.which` to 0

---

Source/control.cpp
Source/controls/plrctrls.cpp
Source/controls/touch/renderers.cpp
Source/cursor.cpp
Source/diablo.cpp
Source/qol/stash.cpp

Small refactoring.
Replaces all `uint16_t(-1)` with `StashStruct::EmptyCell` to describe empty cell behavior better.

Use StashStruct::EmptyCell instead for empty stash item check

---

Source/engine/render/blit_impl.hpp

`src < end - 3` results in one more instruction than `src + 3 < end`.
Godbolt: https://godbolt.org/z/PPfhYYWG8
RG-99 binary becomes 224 bytes smaller.

Blitter: Minor optimization

---

Source/controls/plrctrls.cpp
Source/inv.cpp
Source/inv.h

Controller movement should be working as normal now but I still haven't tested in depth, this was a quick proof of concept for a comment on #5917 
`inv_xy_slot` and `inv_item` can be deduplicated, haven't done that yet either.
Pretty much all the rectangles were defined as the coordinate of the bottom left corner, not the top left as would be normal for the way the UI coordinates work. This seems to have been to avoid adding an offset when rendering, but there was a -1 y offset anyway... changing that to the top left corner makes the inventory code way simpler.

Use rectangles for inventory/belt hit areas

---

Source/engine/render/scrollrt.cpp

Draw item labels before the monster health bar

---

Source/multi.cpp

Small improvement:
When a remotes player position is updated and it's too far away, the game places/warps the player to the new tile.
This ensures that the desyncs are minimized.
But currently the game only checks if the tile doesn't have a player on it.
It doesn't check if a monster is on the tile or if there is a closed door.
This pr ensures that the game checks this facts before the player gets warped to his new position.
<details><summary>Old content with a possible desync fix for PvP szenarios</summary>
In a PvP match it's possible that the position of a player can desync between clients.
Normally this is no big deal and in some way a interesting aspect of PvP.
But there are cases where this is problematic:
- Player A walks to a new tile
- On Player A's client he finished the walk
- …

Multiplayer: When updating remote player tile ensures that it's free

---

Packaging/nix/LinuxReleasePackaging.sh

Change location of devilutionx.mpq to the build folder instead of the packaging/resources folder since it is now built at compile.

Update Linux Packaging Script

---

Source/controls/plrctrls.cpp
Source/diablo.cpp

Gamepad "stand ground" logic wasn't being checked by `WalkInDir()`. I fixed things up so that the logic for stand ground would be encapsulated by a function and called by both `Interact()` and `WalkInDir()` so there'd be no discrepancies. And the game now also checks gamepad stand ground logic on SDL1 platforms.
Lastly, the `Toggle stand ground` option was implemented incorrectly so I fixed that too.

Fix stand ground for gamepad controls

---

Source/missiles.cpp

`missile._misource` is -1 when the source of the missile is a trap.
Introduced by #4863

Fix OOB when triggering a Nova chest

---

Source/objects.cpp

Fixes #5955
Note:
To avoid desync for the spawned loot `_oRndSeed` is used (similar to chests).
Due to the additional `AdvanceRndSeed` in `AddObject` this PR can result in a different object layout even in singleplayer.
As far as I know we have multiple reasons why monster and object layout can differ from vanilla, so it shouldn't be a problem.
For existing singleplayer saves the layout is stored in the save.

Multiplayer: Enable Slain Hero

---

Source/diablo.cpp
Source/levels/drlg_l1.cpp

Fixes #5954
When a quest/set-map is loaded, the monsters gets added with `SetMapMonsters` -> `PlaceMonster` -> `InitMonster`.
`InitMonster` initializes the max monster hitpoints [randomly](https://github.com/diasurgical/devilutionX/blob/957bd03b987fbef49f0448d862078f27295a3120/Source/monster.cpp#L135).
That means the monster hitpoints depend on a reproducible set/quest-map loading (seed stay the same).
For singleplayer this is irrelevant, cause the monsters hp/maxhp are loaded from the save when reentering the level.
But now with multiplayer quests this can result in a desync where one client thinks the monsters have more hp then the other.
The desynced hp are synced to the other clients so they think the monsters have > 100% hp (seen in monster health bar).
This PR makes loading …

Multiplayer: Ensure monster hitpoints are calculated reproducable in quest/set-maps

---

CMake/platforms/ctr/asio_defs.cmake
CMake/platforms/switch/asio_defs.cmake

Enables these scripts to find the right include directory in mods that change the project name.

Use PROJECT_SOURCE_DIR in asio_defs.cmake

---

Source/objects.cpp

Fixes #5963
Notes:
- Check circle state independent of `MyPlayer` (also makes the circle red for remote players)
- In `OperateBook` only check if the player stands on the circle if it's the local client, cause on remote clients this can desync
- Call `OperateBook` also in `SyncOpObject` without the position check

Multiplayer: Sync circles in Lazarus' Lair

---

Source/engine/render/clx_render.cpp
Source/engine/render/clx_render.hpp

Example output (also demonstrates a bug in our encoder):
CLX sprite: 16x20 pixelDataSize=97b
command | width | bytes | color(s)
--------|------:|------:|---------
Transp. |    80 |     1 |
Pixels  |     2 |     3 | 203 199
Fill    |     3 |     2 | 202
Pixels  |     2 |     3 | 199 201
Fill    |     1 |     2 | 205
Transp. |     8 |     1 |
Pixels  |     3 |     4 | 205 199 196
Fill    |     4 |     2 | 197
Fill    |     1 |     2 | 202
Transp. |     9 |     1 |
Pixels  |     6 |     7 | 206 199 197 203 206 202
Fill    |     1 |     2 | 204
Transp. |    10 |     1 |
Pixels  |     4 |     5 | 206 199 197 205
Fill    |     1 |     2 | 207
Transp. |    12 |     1 |
Pixels  |     3 |     4 | 206 197 197
Fill    |     1 |     2 | 205
Transp. |     9 |     1 |
Pixels  |     7 |     8 | 207 205 …

Add a debug function that describes a CLX

---

Source/items.cpp
Source/player.cpp

While testing #5975 I could reproduce a crash when dying that is currently in master and was mentioned in discord before.
How to reproduce the crash:
- Have two players in the game on the same dungeon level
- Player 2 dies
- Player 2 respawns in town
- Player 2 changes gear (for example removes weapon or armor)
Background:
- When the player respawns in town, he still haves the "old" player mode `PM_NEWLVL` set (cause `RestartTownLvl` doesn't set a new one)
- Normally player graphics are not loaded for remote players that aren't on the same level
- When changing gear the new inventory synchronization sends a `CMD_CHANGEINVITEMS`
- `CMD_CHANGEINVITEMS` calls `CheckInvSwap` and then `CalcPlrInv` with `loadgfx` true
- The game tries to load the changed animations for the current player mode …

Fix crash after dying and changing gear

---

Source/options.cpp
Source/options.h
Source/panels/spell_list.cpp

Had to limit button names to two characters so they'd fit in the spell icons. Here's a couple screenshots.
Generic gamepad:
PlayStation:

Use padmapper bindings on spell icons

---

Source/DiabloUI/settingsmenu.cpp
Source/controls/controller_motion.cpp
Source/controls/controller_motion.h
Source/controls/devices/kbcontroller.cpp
Source/controls/devices/kbcontroller.h
Source/controls/game_controls.cpp
Source/controls/input.h
Source/controls/menu_controls.cpp

This PR splits `ProcessControllerMotion()` up so that gamepad thumbstick state can be updated consistently in `PollEvent()` regardless of the event handler currently in use by the game.
* Reduce `ProcessControllerMotion()` to only updating thumbstick state based on an SDL event
* Remove unimplemented function `ProcessKbCtrlAxisMotion()`
* Introduce `IsControllerMotion()` to indicate whether an SDL event represents controller motion, taking the place of the bool previously returned by `ProcessControllerMotion()`
* Call `SimulateRightStickWithPadmapper()` directly in the game event handler
This resolves #5946

Update gamepad motion state regardless of the active event handler
