diasurgical/DevilutionX

Translations/uk.po
* TL'd new options, AFAIK no untranslated options remain
* Shortened "Speed" word in "Options" menu to fit UI
* Added some more monster names
=> UK TL: New options, more monster names

Source/DiabloUI/selgame.cpp, Source/diablo.h, Source/dvlnet/abstract_net.h, Source/dvlnet/base_protocol.h, Source/dvlnet/cdwrap.h, Source/multi.h, Source/storm/storm_net.cpp, Source/storm/storm_net.hpp
Notes:
- Show difficulty, speed and players for public games
- Enhances incompatibility messages (game mode is shown)
=> public game browsing: show difficulty, speed, players and possible incompatibility

Source/missiles.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/4078
Thanks @obligaron :)
=> add a check for trap missiles for TRNs

Source/debug.cpp
=> Fix format strings in PrintDebugMonster()

.github/workflows/Windows_x64.yml, .github/workflows/Windows_x86.yml
=> Build translations on Windows CI runner

CMake/Assets.cmake, Source/options.cpp
-added greek to the cmake assets build
-added greek to the options menu
=> Greek translation

Source/inv.cpp, Source/items.cpp, Source/player.h
Resolves https://github.com/diasurgical/devilutionX/issues/4113
Resolves https://github.com/diasurgical/devilutionX/issues/4059
=> barb 2h cleanup

Source/items.cpp, Source/loadsave.cpp, Source/missiles.cpp, Source/monster.cpp, Source/player.cpp, Source/player.h, test/player_test.cpp, test/writehero_test.cpp
Added enums for the spell flags that are used. Used class format as discussed in comments.
=> _pSpellFlag enums

Source/player.cpp
This lets us use `std::move` to indicate that the data is discarded after use in these functions, the one time we reuse the variable (when dropping equipped items in `StartPlayerKill`) it's "reinitialised" by setting `_itype` to indicate an empty item.
=> Dedupe network call when dropping items on death

Source/missiles.cpp
AddHeal spell function converted to use GenerateRndSum as the other spells
=> AddHeal converted to use GenerateRndSum

Source/scrollrt.cpp
Regression introduced in f4bce388754948927a010f483bbf643e69019847
Fixes #4132
=> Fix reflect icon offset

android-project/build.gradle
Yet another point update, this time to 7.1.2
=> Update Gradle plugin

Source/qol/chatlog.cpp
Now uses the same translation as SendPlrMsg
=> fix chatlog translation entry

Translations/uk.po
To be clear and avoid further questions: I am in Ukraine, I am safe for now
Finally, got some off time to update some strings, including for Chat log feature
Added a little more TL's for Monster names
Also, decided to change Shareware to "demo version" since it's the closest equivalent
Safe skies, everyone!
=> UK TL: Minor updates

Source/items.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/4150
=> ignore auric amulet of other players in MP

Source/items.cpp, Source/items.h, Source/monster.cpp, Source/msg.cpp, Source/msg.h, Source/towners.cpp
=> Only spawn loot once

CMakeSettings.json
Saves me ignoring CMakeSettings.json when I'm testing translations 😂
=> Add config for building translations in visual studio

Source/control.cpp, Source/control.h, Source/controls/plrctrls.cpp, Source/cursor.cpp, Source/inv.cpp, Source/items.cpp, Source/objects.cpp, Source/panels/spell_list.cpp, Source/qol/stash.cpp, Source/quests.cpp, Source/trigs.cpp
I decided to do one last update to string handling before 1.4.0. @obligaron hope you like `std::string` as much as `CopyUtf8()` :)
=> Change infostr from char[128] to std::string

Source/DiabloUI/diabloui.cpp, Source/DiabloUI/ui_item.h, Source/platform/ctr/keyboard.cpp, Source/platform/ctr/keyboard.h, Source/platform/switch/keyboard.cpp, Source/platform/switch/keyboard.h, Source/platform/vita/keyboard.cpp, Source/platform/vita/keyboard.h
This is a bit of an experiment, hoping the automated builds flag any problems.
=> Use string_view for UiEdit (and platform specific code)

Source/DiabloUI/selgame.cpp, Source/DiabloUI/selhero.cpp
=> Remove unessesery .c_str() from UiEdit

Source/control.cpp, Source/debug.cpp, Source/inv.cpp, Source/inv.h, Source/items.cpp, Source/items.h, Source/objects.cpp, Source/player.cpp, Source/player.h, Source/qol/stash.cpp, Source/stores.cpp, Source/stores.h
- Always create gold from template
- Allow withdrawing any amount from stash
- Fill inventory in the same pattern when getting gold from ground/shop/stash
=> Unify gold handling (withdraw any amount from stash)

Source/control.cpp, Source/control.h
Was borken when unifying the gold managment code. Thanks to @mewmew for reporting it.
https://github.com/diasurgical/devilutionX/commit/1ba817ca5381b6872ee970b09e2c11435f819844#diff-d59ae24c872d55375ef9c864346e2841b9075ceca2b2d24f95836c67a31669f8L376
=> Fix splitting gold

Translations/uk.po
Man, is POEdit Pro useful!
I don't look forward to those last 15% as they have dumb portmanteau monster names like Warpskull or Goretongue…
=> UK TL: Reach 85% of translated content

Source/DiabloUI/diabloui.cpp, Source/utils/sdl_bilinear_scale.cpp
=> Fix hardware cursor initialization and outline

Source/options.cpp
Fixes #4235
Regressed in #3617 (settings menu).
=> Change default value for "Show FPS" to off

Source/controls/plrctrls.cpp
=> [gamepad] Fix managing belt

Source/misdat.cpp
swap mlSFX and miSFX to match structure definition.
=> fix comment labels in misdat.cpp

Source/DiabloUI/selgame.cpp, Source/options.cpp, Source/options.h
=> Zerotier join game

3rdParty/zlib/CMakeLists.txt, Packaging/amiga/prep.sh, docs/building.md
They deleted the 1.2.11 src from there site, a bit agressive. Let's hope noting major changed :/
=> Update zlib dependency to 1.2.12

Translations/uk.po
It also contains a bunch of monster names and some dialogues
=> UK TL: Finish translating weapon names

Source/stores.cpp
=> Wirt: Ensure _iStatFlag is updated before getTextColorWithStatCheck is called

Translations/ru.po
This PR translates some of the new stuff introduced recently in the codebase and fixes most broken strings.
_NOTE: Some strings are still untranslated (I haven't played any translated games for more than 15 years, IIRC), so I hope someone else could translate the rest in another PR._
=> Russian translation update/fix

Translations/uk.po
This update completes TL of:
* Book titles
* Shrines
* Monster names
While also adding a bunch of Gossip TL
@AJenbo your stunt with https://github.com/diasurgical/devilutionX/commit/0fb430ebd5785d06cec259800ee2b917878b967b made me learn how to resolve git conflicts. So, _that was fun_. Eh, had to learn one way or another 😂
=> UK TL: Another update

Source/inv.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/4278
=> refresh stats when sending an item to stash by ctrl + click

Translations/de.po
Just opening this, so my progress is shown. There are still 55 translations to go.
=> German Translation

Source/controls/touch/event_handlers.cpp
=> Touchscreen navigation for stash

Source/objects.cpp
I was lazy with the review and didn't flag both cases.
=> set statflag after recreating potion

Translations/zh_CN.po, Translations/zh_TW.po, tools/segmenter/README.md
pip install --upgrade -r tools/segmenter/requirements.txt
tools/segmenter/segment_all.py
Following an update to the Chinese translations in https://github.com/diasurgical/devilutionX/pull/3861
=> Resegment translations

Translations/uk.po
Incorporated fixes suggested by @SourceCodeDeleted in #4280
=> UK TL: Fixes

Source/diablo.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/4329
=> allow remapping P for pause and always treat pause button as pause

Source/controls/plrctrls.cpp, Source/items.cpp, Source/spells.cpp, Source/spells.h
=> [Gamepad] Allow casting Town Portal, Teleport, and Guardian scrolls from inventory

Source/qol/stash.cpp
I feel if I don't do it, nobody will 😅  50 is a weird number to have as a max especially considering we can handle more than that. 100 is a nice round number :)
=> increase max stash pages from 50 to 100

Source/loadsave.cpp
Viewing a stash page results in an entry being created in the stashGrids map. If the player flicks through the entire stash without actually storing an item they end up with ~20kb of unnecessary data in the stash file when they next save.
=> Only save stash pages containing items

Source/discord/discord.cpp
- Fixed so that Class is translated
=> Fix: #4285 Discord incomplete translation

Translations/pt_BR.po
@julealgon or @altiereslima if you have some free time, I would really appreciate it.
What to you think about `Stash -> Armazém`?
=> Add missing pt_br translations

3rdParty/SDL_audiolib/CMakeLists.txt, Source/mpq/mpq_sdl_rwops.cpp, Source/sound.cpp, Source/utils/soundsample.cpp, Source/utils/soundsample.h
May help with #4365 in conjunction with https://github.com/diasurgical/devilutionx-assets/pull/1
=> Support MP3 playback

Source/items.cpp
Adds stash items to the list of items updated in the `CalcPlrBookVals()` function.
This resolves #4360
=> Update magic requirement for stashed books

3rdParty/SDL_audiolib/CMakeLists.txt
Includes updates of drwav and drmp3 to the latest versions
=> Update SDL_audiolib from upstream 

Source/controls/controller.cpp, Source/controls/devices/game_controller.cpp
Similar to https://github.com/diasurgical/devilutionX/pull/4374
=> Only query cbutton state for button events

Source/controls/touch/event_handlers.cpp
=> [touch] Spend stat points when clicking the buttons

Source/controls/touch/event_handlers.cpp
=> [touch] Allow interacting with the spell book

Source/utils/soundsample.h
Fixes #4392
Fixes https://github.com/diasurgical/devilutionx-assets/issues/5
Tested with recompressed spawn.mpq
=> Fix `SoundSample::DuplicateFrom` mp3

Translations/sv.po
@AJenbo Thank you for the reminder!
=> update swedish lines

Source/controls/controller_motion.cpp, Source/controls/plrctrls.cpp, Source/engine/assets.cpp, Source/miniwin/misc_msg.cpp, Source/mpq/mpq_writer.cpp, Source/options.cpp
Many of the debug messages are no longer relevant as they come from a fairly stable modules.
Reduces the priority level of these messages from Debug to Verbose.
=> Reduce debug log output (changed to verbose)

Translations/uk.po
I wanted to make a PR when I got to 100%, but seeing that 1.4.0 is releasing soon, decided to just **DO IT** now
@SourceCodeDeleted please review this when you have the time
=> UK TL: 95% translated

Source/stores.cpp
=> Restore durability to items in stores

Source/effects.cpp, Source/sound.cpp, Source/sound.h, Source/sound_defs.hpp, Source/utils/soundsample.cpp, Source/utils/soundsample.h
Unifies audio handling between sound effects and music.
Fixes #4396
=> Use SoundSample for music

Source/scrollrt.cpp
=> Use zero-based arch indexes

Source/control.cpp
This needs to be adjusted after #4221.
=> Fix frame index of Level Up icon

Source/panels/spell_book.cpp
Follow-up to https://github.com/diasurgical/devilutionX/pull/4221
=> Fix SPLICONLAST for zero-based frame indexing

Source/player.cpp
Uses cast animation in town and unify casting in town and dungeon.
<details><summary>Original Description (outdated)</summary>
Since #1939 casting in Town is buggy.
We don't use `NewPlrAnim` for casts in town but still check `AnimationInfo.CurrentFrame`.
Possible Solutions
1. Bring back `actionFrame` only for the special case of casting in town.
2. Start explicit Stand Animation for the cast.
3. Use the cast animation in town
This pr uses solution 3, but if the cast animation in town is not desired I would open a new pr with solution 2.
_The original bug was fixed with #2025._
</details>
<details>
<summary>Example Videos</summary>
https://user-images.githubusercontent.com/25415264/118359759-4b16df00-b585-11eb-823a-dd9946be456d.mp4 …
=> Use cast animation in town

Source/controls/plrctrls.cpp, Source/qol/stash.cpp, Source/qol/stash.h
Most uses of Stash::GetPage are purely to access a cell on the current grid, so this PR introduces some helpers to get the data directly.
=> Add helpers for accessing cells on the current stash grid

Source/options.cpp
=> Default to 48kHz on Windows

Source/DiabloUI/art.cpp
SDL_RWsize is documented as returning any negative value on error (even though in practice errors are always indicated by a value of -1) so allow for that instead of only checking for unknown size.
There were also a few unnecessary arithmetic operations being done to calculate the size to read, straightforward to simplify.
SDL_CreateRGBSurfaceWithFormat expects width and height to be positive values < 2^16. Could get away with using unsigned if the SDL API did but it doesn't so stick with signed types even when it doesn't really fit the use.
bufferPitch is an oddity, ultimately it's only used to determine a pointer offset so making the param ptrdiff_t as it's more appropriate than size_t.
=> Address type conversion/truncation warnings in LoadPcxPixelsAndPalette

Source/control.cpp
Fix durability icon indexing #4474
=> Fix Durability Icons

.github/workflows/src_dist_release.yml
=> GitHub CI: Add a `--fully_vendored` source dist

Translations/pl.po
All the English strings are translated, it should be a good base for spelling/gramma checks. I will iterate through it some time more after I will play the game more and catch some weird sounding phrases/words.
=> Updated Polish translation to 100% string coverage

Source/inv.cpp
Missed this one in #4487, which ended up introducing a dupe
=> Clear held item when putting in an empty belt slot

Source/inv.cpp, Source/items.cpp, Source/items.h, Source/qol/stash.cpp
fixes #4499 
There was a fair bit of duplication in other areas which I've cleaned up in the second commit.
=> Update spell book requirements when refreshing stash items

Source/msg.cpp, Source/player.cpp
Found by [stephen](https://github.com/diasurgical/devilutionX/pull/4479#issuecomment-1104522786) in #4479. Thanks again. 🙂
=> ADL: Fix PreviewFrame for some spells

Source/control.cpp, Source/scrollrt.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/4537
=> fix refreshing/drawing bottom description part

3rdParty/libzt/CMakeLists.txt
Includes https://github.com/diasurgical/libzt/pull/8
=> Bump libzt

Source/monster.cpp, Source/objects.cpp, Source/quests.cpp
Also cleanup object update code
=> Fix missing lamp fire in Lazarus' chambers

.circleci/config.yml, .github/workflows/Linux_x86_64_test.yml
...not entirely sure how to actually trigger this without merging it...
=> Use github workflow for Codecov.io report

Translations/uk.po
You know what they say, the last 20% of work takes 80% of the time. For me, it was last 5%
But now, after 196 days (from initial commit on Oct 28th 2021), and 29 days from my last update, of keeping my nose in dictionaries, I present to you: 2042 out of 2042 strings translated!
And just in time for my birthday!
@SourceCodeDeleted please review when you have the time
Ignore first commit
Converting to draft until review is complete
=> Ukrainian Translation 100% complete

Packaging/nix/devilutionx-hellfire.desktop, Packaging/nix/devilutionx.desktop
Removed mention of "Linux" because the game runs on BSD systems as well
Add Russian and Ukrainian tips
=> Removed mention of "Linux" because the game runs on BSD systems as well. Add Russian and Ukrainian tips

Source/missiles.cpp, Source/monster.cpp, Source/monster.h, Source/player.cpp
This is part 1 of split of #4570
This is to lower complexity of change for review, especially of first original commit there.
In this part I chose only changes around the main function merge. Usually function extracts and convoluted code unwindling.
Please review this first.
Soon part 2 will be available to review - with main change.
Or alternatively, if this would get merge before - I will rebase original PR, to make left changes easier to see.
=> MonsterMHit and MonsterTrapHit split 1

Source/controls/touch/event_handlers.cpp
=> Fix crash when skipping cutscene with touchscreen

Source/objects.cpp
All three shrines do the same, expect they use a different spell and show a different messages.
This pr unifies them in one function.
=> Unify cost of wisdom shrines (Fascinating, Sacred and Ornate)

Source/missiles.cpp
=> CheckMissileCol cognitive compexity reduction

Source/engine/displacement.hpp, Source/lighting.cpp, Source/lighting.h, Source/loadsave.cpp, Source/missiles.cpp, Source/player.cpp, Source/scrollrt.cpp, test/CMakeLists.txt, test/math_test.cpp
Quick proof of concept while I worked out what the fuck missiles were actually doing. Turns out it's simply a negated world transformation. There is a rounding error that I initially fixed but reintroduced because it was making it harder to determine if I was changing behaviour.
=> Simplify logic of UpdateMissilePos using helpers from 4620

test/drlg_l1_test.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/4643
=> fix dungeon test

Source/utils/language.cpp
=> Fix crash when switching to English

Translations/zh_CN.po, Translations/zh_TW.po
Following the recent translation updates
tools/segmenter/segment_all.py
=> Resegment Chinese translations

Source/diablo.cpp, Source/diablo.h, Source/gendung.cpp, Source/gendung.h, Source/interfac.cpp, Source/loadsave.cpp, Source/multi.cpp, Source/trigs.cpp, test/drlg_l1_test.cpp, test/drlg_l2_test.cpp, test/drlg_l3_test.cpp, test/drlg_l4_test.cpp, test/drlg_test.hpp
In preparation for testing dungeons with quest elements
=> Clean up drlg tests

android-project/build.gradle
See title.
Play tested on my device (Google Pixel 2, Android 10)
=> Update Gradle Android plugin version to 7.2.1

Source/objects.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/1874
=> fix shrine rng

Source/debug.cpp, Source/drlg_l4.cpp, Source/engine/point.hpp, Source/quests.cpp
Will rebase after #4696 (picked the same name so that'll be easy :D)
=> Point mega <-> world conversion helpers

Source/engine/render/pcx_render.cpp, Source/engine/render/text_render.cpp
Reduces peak memory consuption in game by ~420 KiB.
This is because the PCX renderer applies the palette on the fly while rendering, meaning we do not need to duplicate the font for different palettes.
This approach is also a bit slower than precomposed palettes (still plenty fast).
=> Render fonts as PCX (-420 KiB RAM)

Source/platform/locale.cpp
follow up to #4716
Removed logging as it was only intended to handle errors thrown by c++ `std::locale`.
Keep the same fallback behaviour, but if LANGUAGE is defined then parse it as a colon separated list of POSIX codes. This makes Unix platforms with multiples preferences defined in LANGUAGE behave similar to MacOS and Windows, fallback is now actually possible 🎉
=> Use LANGUAGE as a preference list if available

Translations/uk.po
Keeping Ukrainian translation up-to-date with new options from https://github.com/diasurgical/devilutionX/pull/4638 and https://github.com/diasurgical/devilutionX/pull/4544
=> UK TL: Translate new audio options

Source/gendung.h
=> Fix building unit tests with msvc (SOLData needs DVL_API_FOR_TEST)

Source/DiabloUI/diabloui.cpp, Source/control.cpp, Source/controls/touch/renderers.cpp, Source/cursor.cpp, Source/doom.cpp, Source/engine/cel_sprite.hpp, Source/engine/render/text_render.cpp, Source/error.cpp, Source/gmenu.cpp, Source/interfac.cpp, Source/inv.cpp, Source/items.cpp, Source/minitext.cpp, Source/panels/charpanel.cpp, Source/panels/spell_book.cpp, Source/panels/spell_icons.cpp, Source/qol/stash.cpp, Source/quests.cpp, Source/scrollrt.cpp, Source/stores.cpp
`OwnedCelSpriteWithFrameHeight`: 40 -> 32
=> Reduced the size of `OwnedCelSprite(WithFrameHeight)` by 8 bytes

test/path_test.cpp
was using this to test #4755 but it seems useful in general
=> Add tests for path length edge case

Source/platform/locale.cpp
included in both #4757 and #4755
=> Remove duplicate defines

3rdParty/simpleini/CMakeLists.txt, CMake/finders/Findsimpleini.cmake, Source/CMakeLists.txt
=> CMake: Fix SimpleIni on vcpkg

Source/control.cpp, Source/controls/plrctrls.cpp, Source/controls/touch/event_handlers.cpp, Source/controls/touch/gamepad.cpp, Source/controls/touch/gamepad.h, Source/controls/touch/renderers.cpp, Source/cursor.cpp, Source/diablo.cpp, Source/engine/circle.hpp, Source/engine/rectangle.hpp, Source/items.cpp, Source/levels/drlg_l2.cpp, Source/levels/gendung.cpp, Source/levels/trigs.cpp, Source/panels/spell_book.cpp, Source/player.cpp, Source/qol/itemlabels.cpp, Source/qol/stash.cpp, Source/quests.cpp
Also included Circle and VirtualButton classes due to the shared use.
(Splitting a bunch of cleanups into dedicated PRs to make #4711 more focused)
=> Apply MethodCase config to Rectangle

Source/monster.cpp
=> AiRanged refactors

Source/monster.cpp
Refactor AiRangedAvoidance changes.
=> AiRangedAvoidance rafactor

Source/monster.cpp
=> redundant GoatAi removal

Source/monster.cpp
a bug found in Devilution
https://github.com/diasurgical/devilution/pull/2262
=> Fallen warcry dungeon inbound fix for vanilla bug

Source/monster.cpp
fix for bug introduced in https://github.com/diasurgical/devilutionX/pull/4779
=> lazarus minion missile fix

Source/monster.cpp
fallen fear absolute dMonster id
fix for bug introduced in (https://github.com/diasurgical/devilutionX/pull/4785)
=> Fallen fear absolute dMonster id fix

3rdParty/libmpq/CMakeLists.txt
Includes https://github.com/diasurgical/libmpq/commit/b9daa8ec7a277b1e1f235173642d2aed51309ccf
=> Bump libmpq

Source/missiles.cpp
Since I was looking at it anyway for #4834 :D
=> Avoid unnecessary iterations in missile routines

Source/engine/actor_position.hpp, Source/engine/displacement.hpp, Source/engine/point.hpp, Source/engine/world_tile.hpp, Source/lighting.cpp, Source/lighting.h, Source/missiles.cpp, Source/monster.cpp, Source/monster.h, Source/msg.cpp, Source/multi.cpp, Source/player.cpp, Source/player.h, Source/utils/static_vector.hpp
This will allow us to make some structs, such as `ActorPosition`, much smaller.
`sizeof(Monsters)`: 56K -> 40K
=> Non-int versions of `Point` and `Displacement`

Source/appfat.cpp, Source/appfat.h, Source/diablo.cpp, Source/engine/demomode.cpp, Source/engine/load_file.hpp, Source/engine/render/scrollrt.cpp, Source/init.cpp, Source/inv.cpp, Source/items.cpp, Source/levels/themes.cpp, Source/monster.cpp, Source/mpq/mpq_writer.cpp, Source/msg.cpp, Source/multi.cpp, Source/nthread.cpp, Source/player.cpp, Source/qol/monhealthbar.cpp, Source/stores.cpp, test/appfat_test.cpp
=> Migrate snprintf to fmt

Source/missiles.cpp, Source/spells.cpp, Source/spells.h
@ephphatha already had this one ready when the other was merged, but decided to look for possible cases of missing `const` before sending it your way ;)
This leaves just 3 files with 47 lines to look through to se if we can reduce the diff for https://github.com/diasurgical/devilutionX/pull/4754
=> Take player by reference in UseMana

Source/objects.cpp, Translations/hr.po
=> Fix extra bracket in (disabled) translation

Packaging/xbox-one/build.bat, appveyor.yml
let's see if this speeds up appveyor at all
=> appveyor: enable parallel build

Source/control.cpp, Source/diablo.cpp, Source/missiles.cpp, Source/missiles.h, Source/panels/spell_book.cpp, Source/panels/spell_list.cpp, Source/player.cpp, Source/player.h, Source/spells.cpp
Remove the buggy `GetSpellLevel` implementation and use `Player#GetSpellLevel` throughout instead.
=> Clean up `GetSpellLevel`

Source/monster.cpp
Renames `StartWalk`, `StartWalk2` and `StartWalk3` to more meaningful names
=> Improve StartWalkX functions naming

Source/monster.cpp, Source/msg.cpp, Source/msg.h
I play-tested on both single-player and multiplayer (loopback). Nothings seem to be broken.
=> :recycle: change delta_monster_hp to receive a Monster reference

Source/missiles.cpp, Source/monster.cpp, Source/monster.h, Source/msg.cpp, Source/player.cpp
Also: 
- renamed `MonsterMHit` m parameter to `monsterId`
- Renamed `PlrHitMonst` m parameter to `monsterId`
=> Remove monsterId from M_GetKnockback

Source/DiabloUI/diabloui.cpp, Source/controls/plrctrls.cpp, Source/dvlnet/base_protocol.h, Source/inv.cpp, Source/items.cpp, Source/loadsave.cpp, Source/missiles.cpp, Source/msg.cpp, Source/multi.cpp, Source/objects.cpp, Source/pack.cpp, Source/pack.h, Source/panels/charpanel.cpp, Source/pfile.cpp, Source/player.cpp, Source/player.h, Source/qol/xpbar.cpp, Source/stores.cpp, test/inv_test.cpp, test/player_test.cpp, test/writehero_test.cpp
Remove #defines in player.h and add constexpr where applicable in player.h/cpp. 
This is done to bring the code closer to modern C++
=> Remove #defines in player.h and add constexpr where applicable 

Source/engine/random.cpp, Source/engine/random.hpp, Source/items.cpp, Source/levels/drlg_l1.cpp, Source/levels/drlg_l3.cpp, Source/missiles.cpp, Source/monster.cpp, Source/objects.cpp, Source/quests.cpp
`GenerateRnd(2) != 0` and `GenerateRnd(2) == 0` were being used everwhere so I created a new function specifically for that.
The `flipCoin` name is debatable but I think that it shows a better intent than `randomBoolean`
=> :sparkles: Introduces flipCoin()

Translations/uk.po
Also fix #4807 while I'm at it
If anyone bothers to review this - do just the last commit
=> Update Ukrainian translation

Source/control.cpp, Source/controls/modifier_hints.cpp, Source/items.cpp, Source/msg.cpp, Source/panels/spell_book.cpp, Source/panels/spell_list.cpp, Source/player.cpp, Source/player.h, Source/spells.cpp, Source/spells.h, Source/stores.cpp
=> Validate spell IDs

Source/items.cpp
The only difference already has a check that makes it only happen in the specific cases that it needs to.
=> Deduplicate using spells

Source/levels/drlg_l1.cpp
Just a simple clean up of the remaining attributes that could use Point and a few better variable names. Using IsAnyOf() will allow for using the tile enums in a later change.
=> Clean up DRLG1 parameters

Source/CMakeLists.txt, Source/levels/crypt.cpp, Source/levels/crypt.h, Source/levels/drlg_l1.cpp, Source/levels/drlg_l1.h, Source/monster.cpp, Source/msg.cpp, Source/objects.cpp
This is needed for mapping all the tile enums, and also just makes sens. I have done it in a bit of a minimalistisk way here, let me know if there is a way you think would make better sens.
On a side note there is about 900 lines of shared code and 400 lines of Cathedral specific code.
=> Split Crypt from Cathedral

Source/engine/render/cel_render.cpp
This was used for stippled transparency which we no longer support.
=> cel_render: Remove unused `LineEndFn`

3rdParty/tl/CMakeLists.txt, 3rdParty/tl/function_ref.hpp, CMake/Dependencies.cmake, Source/CMakeLists.txt, Source/debug.cpp, Source/engine/path.cpp, Source/lighting.cpp, Source/lighting.h, Source/missiles.cpp, test/lighting_test.cpp
=> Crawl: Move implementation from header to cpp

Source/engine/random.cpp, Source/engine/random.hpp, Source/items.cpp, Source/levels/drlg_l1.cpp, Source/levels/drlg_l2.cpp, Source/levels/drlg_l3.cpp, Source/levels/drlg_l4.cpp, Source/levels/gendung.cpp, Source/levels/themes.cpp, Source/missiles.cpp, Source/monster.cpp, Source/objects.cpp, Source/player.cpp, Source/quests.cpp
Opening as a draft till I finish going through the non-50/50 rolls.
=> Expand use of FlipCoin for unfair choices

Source/levels/crypt.cpp
=> Extract crypt 1x1 patterns in to arrays

Source/loadsave.cpp, Source/monster.cpp, Source/monster.h, Source/objects.cpp
As a follow up to https://github.com/diasurgical/devilutionX/pull/4949 to make sure that there aren't any cases where this is still broken and prevent it from happening in the future. Also it found a few cases in HorkAI where the enum hadn't been applied.
=> Convert monster_goal in to a scoped enum

.github/workflows/xbox_one.yml
Follow-up to #4956, which produced an archive with too many files
=> CI: Fix Xbox One/Series archive

Source/control.cpp, Source/dead.cpp, Source/debug.cpp, Source/engine/render/scrollrt.cpp, Source/items.cpp, Source/loadsave.cpp, Source/missiles.cpp, Source/monster.cpp, Source/monster.h, Source/msg.cpp, Source/objects.cpp, Source/player.cpp, Source/qol/monhealthbar.cpp, Source/quests.cpp
Precursor to updating DirOk to take a reference
=> Add getLeader helper for monsters in a pack

Source/debug.cpp, Source/items.cpp, Source/objects.cpp
Duplicates some effort from #4571 but hoping smaller chunks makes it easier to review.
=> Use references for some object initialisation functions

Source/monster.cpp, Source/monster.h, Source/sync.cpp
=> Take const reference in DirOK

Source/monster.cpp
=> Fix a HeadlessMode typo in monster.cpp

3rdParty/simpleini/CMakeLists.txt, CMake/platforms/rg99.cmake
Includes brofield/simpleini@56499b5 which fixes a warning
=> Bump simpleini

Source/loadsave.cpp, Source/monster.cpp, Source/monster.h
sizeof(Monster): 168 -> 144
Also reorders fields of `CMonster` (600 -> 592)
=> Reduce sizes of Monster (goal)Vars

Source/miniwin/miniwin.h, Source/multi.cpp, Source/storm/storm_net.hpp
Anyone willing to try and get rid of `strcasecmp` and `MAX_PATH` :)
=> Remove last usage of DWORD

Source/levels/gendung.cpp
=> Restore legacy behaviour

Source/levels/gendung.cpp
A conservative cleanup of GetSizeForThemeRoom. I just went about it robotically so I don't understand more then a couple of lines and not the full function so someone with a level head can probably make this even nicer :D
Big thanks to @ephphatha for documenting a couple of bugs in the original as well as writing a useful test for messing with the code :+1:
=> Cleanup GetSizeForThemeRoom

Source/diablo.cpp, Source/miniwin/misc_msg.h
These events were no longer used
=> Remove `DVL_WM_SYSKEYDOWN`, `DVL_WM_SYSKEYCOMMAND`

Source/engine/render/blit_impl.hpp, Source/engine/render/cel_render.cpp, Source/engine/render/cl2_render.cpp, Source/engine/render/common_impl.h, Source/engine/render/pcx_render.cpp
Does not unify outline rendering yet.
Performance is the same as on master. It's amazing how good the optimizers are these days.
Refs #4924
=> Unify CEL/PCX/CL2 render functions

Source/DiabloUI/diabloui.cpp, Source/diablo.cpp, Source/discord/discord.cpp, Source/engine/demomode.cpp, Source/mpq/mpq_writer.cpp
Now `fmt` is only used for more complex formatting and for translations.
=> Use `StrCat` in a few more places

Source/discord/discord.cpp
Accidentally broken in #5029
Let's wait for the macOS build to finish before merging
=> Fix discord.cpp on macOS

Source/engine/render/cl2_render.cpp, Source/engine/render/cl2_render.hpp, Source/engine/render/scrollrt.cpp
Bring the CL2 API closer to CEL and PCX.
=> CL2 render: `Point` position argument

Source/diablo.cpp
=> Fix `DVL_WM_RBUTTONUP`

.github/workflows/xbox_nxdk.yml
Everything that DevilutionX needs has been merged 🎉
=> Xbox NXDK: Switch to upstream NXDK

.github/workflows/xbox_nxdk.yml, docs/manual/platforms/xbox.md
Also renames `NXDK` to `nxdk` where applicable. /cc @JayFoxRox
=> Xbox nxdk: Add documentation

Source/missiles.cpp, Source/missiles.h, test/missiles_test.cpp
Just a simple test for RotateBlockedMissile
=> :white_check_mark: Add test for RotateBlockedMissile

Source/levels/drlg_l1.cpp, Source/levels/drlg_l4.cpp, Source/utils/bitset2d.hpp
from https://github.com/diasurgical/devilutionX/pull/5080#discussion_r926908430
=> Add Bitset2d::count() and use it when counting set Dungeonmask tiles

Source/utils/bitset2d.hpp
Should've read what I was typing...
=> use correct attribute for Bitset2d::count

Source/objects.cpp
OperateChest was an incidental inclusion... I can split that into a different PR if it helps
=> Use object references in OperateLever/Chest

Source/controls/plrctrls.cpp
Same as https://github.com/diasurgical/devilutionX/pull/5105 but for 1.5.0
=> [gamepad/touch] Fix targeting berserked

Source/loadsave.cpp, Source/player.cpp, Source/player.h
Also now writes the correct sprite width to the save file in `HeadlessMode`.
=> Clean up player graphic loading

Source/monster.cpp, Source/monster.h, Source/msg.cpp
These were the last functions still using monsterId on monsters.cpp 🥳
=> :recycle: Send the monster reference to the monster AI functions

CMake/platforms/rg350.cmake
=> OpenDingux rg350: Actually disable LTO

Source/player.cpp
Used BaseStr instead of BaseMag
=> Fix ModifyPlrMag

Source/objects.cpp
- Passing objects by reference
- Renamed a few functions
=> :recycle: Pass objects by reference

Source/missiles.cpp, Source/monster.cpp, Source/monster.h, Source/msg.cpp
Cleanup in preparation for the fix described in #5109.
You can see from the commits that I tackled this piecemeal in the hopes that it would help me to avoid making mistakes. I'm leaving this unsquashed in case it helps with the review. Feel free to squash when merging.
=> HitMonster() cleanup

Source/objects.cpp
Just the most basic change to make it simpler to understand the door logic later when refactoring it
=> Clean up door sync

Source/diablo.cpp
=> Fix specific quantity gold drop

Source/engine/render/scrollrt.cpp
=> Only draw towners on their base tile

android-project/app/src/main/java/org/diasurgical/devilutionx/DataActivity.java, android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java, android-project/app/src/main/java/org/diasurgical/devilutionx/ImportActivity.java
Mostly minor issues. But the issue with accessing internal files have about 5 crashes related to it. Though I'm curious how you can end up with a device where the app doesn't have it's internal files folder... but hey we do not rely on it anyway.
=> [android] Handle null pointers in Java

Source/DiabloUI/dialogs.cpp
=> fix error messages

Source/objects.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/5187
Basically reverts part of https://github.com/diasurgical/devilutionX/commit/56915974d60eded7d7199a915cb7ddb904ef842d
=> fix interacting with lazarus books while not on circles

Source/objects.cpp
=> Do not count closed doors as blocked

Translations/ja.po
- Corrected some translations
- Translate the added wording
=> Update japanese translations.

Source/debug.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/5205
No idea why :D (Thanks @obligaron )
=> fix debug questmap command

Source/player.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/5208
=> close help panel while talking to NPCs

Source/controls/modifier_hints.cpp, Source/qol/monhealthbar.cpp
Follow-up to https://github.com/diasurgical/devilutionX/commit/c351acbf7eea47fc579754014f9fa0c243cdac96
=> Remove more redundant `devilutionx.mpq` checks

Source/debug.cpp, Source/debug.h, Source/engine/load_file.hpp, Source/engine/trn.cpp, Source/engine/trn.hpp, Source/player.cpp
Created a way to add TRNs for classes + debug command to test TRNs
Made loading TRNs optional so we can just add TRN files later to make it work
=> TRNs for different classes  + TRN debug command

Source/DiabloUI/settingsmenu.cpp, Source/DiabloUI/ui_flags.hpp, Source/DiabloUI/ui_item.h, Source/control.cpp, Source/controls/touch/renderers.h, Source/diablo.h, Source/effects.h, Source/engine/actor_position.cpp, Source/engine/demomode.cpp, Source/engine/render/automap_render.cpp, Source/engine/render/dun_render.cpp, Source/engine/render/text_render.hpp, Source/hwcursor.cpp, Source/hwcursor.hpp, Source/itemdat.h, Source/misdat.h, Source/missiles.h, Source/monstdat.h, Source/monster.h, Source/options.h, Source/panels/ui_panels.hpp, Source/pfile.h, Source/platform/switch/docking.cpp, Source/platform/vita/touch.cpp
Reduces rg99 binary size by 3 KiB.
=> Set underlying type for all the enums

Source/cursor.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/5248
=> fix cursor item being overwritten by cursor changing spells

Source/monster.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/5250
Imo looks better than corpses just suddenly appearing after death animation has ended, duh.
=> break hidden invis on death

Packaging/nix/org.diasurgical.DevilutionX.yml
Finally decided to return to flatpak support
First, some basic fixes I found during smoke testing
* Base flatpak on 1.4.1 tarball download
* Fix ipc permission
More flatpak progress soon
=> Flatpak fixes

docs/building.md
Update the 64-Bit Haiku Build Dependencies
=> Update the 64-Bit Haiku Build Dependencies

Source/engine/render/scrollrt.cpp, Source/missiles.cpp
Uses the new introduced helpers from #4632 in more places. 🙂
=> Use missile helpers in MoveMissile/UpdateMissileRendererData

Source/loadsave.cpp, Source/loadsave.h, Source/pfile.cpp
Fixes a crash in character creation. Inspired heavily by #5288.
=> Don't use MyPlayer in SaveHotkeys()

Translations/uk.po
* Added my credit for translation to credits roll
* Translated new and updated strings
@SourceCodeDeleted please take a look when you get the chance
=> Ukrainian translation updates

Source/init.cpp, Source/utils/str_split.hpp
=> Add `XDG_DATA_DIRS` to MPQ search paths

Source/monster.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/5340
=> fix golem detection

Source/inv.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/5348
=> fix oob access in inv.cpp

android-project/build.gradle, android-project/gradle/wrapper/gradle-wrapper.properties
Another harmless upgrade of build tools
Play tested on my Google Pixel 2, no issues
=> Upgrade Android build tools

Source/levels/drlg_l1.cpp, test/drlg_l1_test.cpp
Fixes #5370
@Chance4us would be great if you took take a look. 🙂
=> Fix poison water entrace position

Source/monster.cpp, Source/monster.h
1. Extract some common code into functions.
2. Avoid some overly long lines.
=> monster.{h,cpp}: Minor refactor

.github/workflows/opendingux_release.yml
The new toolchains result in slightly faster code thanks to using some XBurst-specific instructions.
=> OpenDingux: Update toolchain versions

Source/miniwin/misc_msg.cpp
=> Forward touch events from FetchMessage_Real()

Source/nthread.cpp
Fixes speed up on android when doing solo multiplayer and switching apps (see [comment](https://github.com/diasurgical/devilutionX/pull/5426#issuecomment-1287829778)).
=> Avoid dramatically speed up in solo multiplayer

Source/control.cpp, Source/control.h
=> Fix InfoString-related stack-use-after-free

Source/diablo.cpp, Source/interfac.cpp
=> Fix loading screen glitches

Source/diablo.cpp, Source/options.cpp, Source/options.h
Similar to how we do this for Padmapper.
=> KeyMapper: Use forward_list instead of vector

Source/help.cpp
Also fixes a warning in the same function
=> Fix compilation error in help.cpp

Source/engine/backbuffer_state.cpp
A vector is a lot more efficient here as we generally only have a handful (1-3) backbuffers.
Additionally, this avoids a lot of temporary allocations every frame, which were apparently triggered by `emplace` even if the element already existed.
=> BackBufferState: `unordered_map` -> `vector`

Source/towners.cpp
With this pr it's possible to access the stash even if the cathedral map is in the inventory.
=> Gillian: play grave quest text only once

Source/inv.cpp, Source/towners.cpp
With the already done changes for multiplayer sync this one was pretty easy. 😄
=> Multiplayer: Enable Magic Rock Quest

Source/diablo.cpp, Source/qol/stash.cpp
=> Only load stash graphics in town

Source/qol/itemlabels.cpp
The set only contains a handful of elements.
It is faster and more space-efficient to store it as a vector.
=> qol/itemlabels: Use a flat set for used X coords

Source/control.cpp, Source/controls/modifier_hints.cpp, Source/controls/plrctrls.cpp, Source/engine.cpp, Source/engine.h, Source/panels/spell_book.cpp, Source/panels/spell_book.hpp, Source/panels/spell_icons.cpp, Source/panels/spell_icons.hpp, Source/panels/spell_list.cpp
Hide the internals of spell icon rendering behind simple functions.
=> Simplify spell icon handling

Source/engine/render/text_render.cpp
Previously, we only clipped to the given surface, without clipping to the given rect.
We do not actually need this for anything, I was just taken by surprise when this did not work as I'd expected.
=> Text rendering: Clip text to the given rect

Source/msg.cpp, Source/portal.cpp, Source/portal.h
When a player is in town and a new portal of another player opens the portal opening animation is now shown.
Example video:
https://user-images.githubusercontent.com/25415264/203418430-72bd198a-ba8c-4a27-aa3d-032b286a3271.mp4
=> Show portal opening animation in town

Source/items.cpp
=> simplify monk damage calculation

Source/engine/demomode.cpp
Useful for measuring performance in SDL1.
The demomode test now passes in SDL1 as well.
=> Support demo playback in SDL1

Source/engine/render/dun_render.cpp, Source/engine/render/dun_render.hpp, Source/engine/render/scrollrt.cpp, Source/engine/render/scrollrt.h, Source/inv.cpp
Now `dun_render.cpp` no longer uses any global flags.
=> dun_render: Remove the remaining global flags

Source/inv.cpp, Source/msg.cpp, Source/objects.cpp
- The pedestal of blood (stone) can be used multiple times (multiple stones get added). But in multiplayer only one operate object is stored/synced. That's why qvar2 is used to store the added stones (not in singleplayer).
=> Multiplayer: Enable Arkaine's Valor Quest

CMake/functions/devilutionx_library.cmake, Source/levels/gendung.cpp, Source/levels/gendung.h, Source/monster.cpp, Source/nthread.cpp, Source/stores.cpp, Source/stores.h, test/utf8_test.cpp
Fixes warnings/errors with `-funsigned-char` and removes `-fsigned-char`.
Fixes #5566
=> Remove `-fsigned-char`

test/drlg_test.hpp
=> drlg_test: fix LoadExpectedLevelData on BE

Source/pack.cpp, test/pack_test.cpp
=> More item packing fixes on big-endian

Source/levels/gendung.h, Source/missiles.cpp, Source/monster.cpp
Add dungeon flags for Fire/Lightning Wall and use them to check if the monster considers the tile safe.
=> Optimize IsTileSafe

Source/engine/demomode.cpp, Source/msg.cpp, Source/multi.cpp, Source/sync.cpp, Source/utils/endian.hpp
Not sure if this works but it's a start -- needs testing.
The implementation can be improved in the future by moving byte-swapping into accessor methods, 
per https://github.com/diasurgical/devilutionX/pull/1416
Based on top of #5605
=> Big-endian support for multiplayer

Source/engine/demomode.cpp, Source/msg.cpp
Commits cherry-picked from #5604
=> Various fixes extracted from the big-endian network PR

Source/msg.cpp
Fixes a regression introduced in ca69237d59aff013e1da17157627b2b4e7eb5aed.
Fixes #5609
=> Fix disappearing portal

Source/inv.cpp, test/inv_test.cpp
=>   Fix ConsumeScroll

Source/inv.cpp, Source/objects.cpp
=> Multiplayer: Enable Halls of the Blind Quest

Source/quests.cpp
Fixes that the water doesn't get purified for remote players.
The issue was that the kill count was checked on one client and the quest update message gets send and proceed on the remote client (and sets the new quest state) before the kill gets recognized on the remote client.
Thanks for reporting @kphoenix137 🙂
=> Multiplayer: Fix Poisoned Water Supply purify

Source/diablo.cpp
Add key for using potions from belt like controller and virtual controller
=> Add key for using potions from belt

CMakeLists.txt, Packaging/OpenDingux/build.sh, Source/engine/demomode.cpp, Source/init.cpp, Source/utils/display.cpp, Source/utils/display.h, test/timedemo_test.cpp, tools/build_pgo.sh
With this, everyone except MSVC users can build DevilutionX with profile-guided optimization with just 1 command.
On my fairly powerful PC, this improves FPS by ~4% but the impact should be larger on slower machines.
=> Add a script for building a PGO'd binary

.github/workflows/xbox_one.yml
Temporarily disabled due to https://github.com/diasurgical/devilutionX/issues/5661
=> Disable Xbox One CI build

3rdParty/zlib/CMakeLists.txt
=> zlib: Add the GitHub mirror

Packaging/OpenDingux/build.sh, Packaging/OpenDingux/profile-generate.sh, Packaging/OpenDingux/rg99-pgo.md
Updates the script for compatibility with `UNPACKED_SAVES` and adds an instructions document.
Latest PGO'd build: 
[devilutionx-rg99.opk.zip](https://github.com/diasurgical/devilutionX/files/10465405/devilutionx-rg99.opk.zip)
=> Update RG99 PGO script and add instructions

Source/utils/aulib.hpp
The requested sample rate is merely preferred and the actual rate may be different.
=> `CreateAulibResampler`: Check the real sample rate

CMake/Dependencies.cmake, Source/CMakeLists.txt, Source/msg.cpp
Reduces RG99 binary size by 12 KiB
=> Do not use PKWare with no MPQs + NONET

Source/cursor.cpp
=> Do not try to create Hellfire sprites in Diablo

Source/spells.cpp
=> Fix Resurrect Crash

Translations/uk.po
Blackouts suck, but now I got enough time to look at new and updated strings
@SourceCodeDeleted your review will be appreciated, as always
=> Ukrainian translation update

Source/player.cpp
Based on information from #839, recent testing reveals that attacks in vanilla Diablo can sometimes include the first frame of animation while the current logic for skipping attack frames in DevilutionX did not account for these cases. This PR attempts to match the vanilla behavior, including some bad interactions for Bard between Readiness/Swiftness and Haste.
=> Update frame skip logic for attacks after movement to match vanilla behavior

Source/control.cpp, Source/controls/modifier_hints.cpp, Source/controls/plrctrls.cpp, Source/items.cpp, Source/loadsave.cpp, Source/msg.cpp, Source/panels/spell_book.cpp, Source/panels/spell_icons.cpp, Source/panels/spell_icons.hpp, Source/panels/spell_list.cpp, Source/panels/spell_list.hpp, Source/player.cpp, Source/player.h, Source/spelldat.h, Source/spells.cpp, Source/spells.h, test/player_test.cpp, test/writehero_test.cpp
Changes enum spell_type to enum class SpellType
=> `enum spell_type` -> `enum class SpellType`

Source/panels/spell_list.cpp
Fixes speed book crash introduced under #5674
=> fix speedbook crash

Source/engine/render/scrollrt.cpp
Basically, issue #1498 occurs because the logic in `CalcViewportGeometry()` selects the wrong tile from which to start rendering. Given that `CalcTileOffset()` was effectively producing the wrong offset, and that the logic for this function was already attempting to make a few adjustments to fix it, I decided to take a more straightforward approach and just compute all the values from scratch. I'm hoping this change should make the code in this function easier to understand and less error prone.
This resolves #1498
=> Derive viewport geometry from player position

docs/installing.md, docs/manual/platforms/xbox-one.md
Added instructions for Retail Mode as it is quite different than Dev Mode
=> added instructions for Xbox Retail Mode

Source/inv.cpp, Source/items.cpp, Source/items.h, Source/player.h, Source/qol/stash.cpp, Source/towners.cpp
Fixes #5781 
- Adds missing quest dialog back
- Doesn't show spectral elixir in red when quest is not finished
Thanks @Chance4us for reporting 🙂
=> Black Mushroom Quest: Fix missing quest dialog

Source/objects.cpp
Remaining quests:
- Gharbad The Weak
- Zhar the Mad
- Warlord of Blood
- Lachdanan
... and many bugs 😄
=> Multiplayer: Enable The Chamber of Bone Quest

Source/options.cpp
This PR provides the following options for my 2280x1080 Pixel 4 device.
This resolves #5723
=> Provide default selections for resolution on systems with only one display mode

Source/misdat.cpp
Companion PR: https://github.com/diasurgical/devilutionx-mpq-tools/pull/8
=> Load combined missile CLX in UNPACKED_MPQS mode

Source/misdat.cpp, Source/misdat.h, Source/missiles.cpp, Source/missiles.h, Source/monster.cpp, Source/monster.h, Source/objects.cpp, Source/portal.cpp
Instead of temporarily modifying `MissileData` around certain calls, pass the arguments from the outside.
=> Make `MissilesData` const

docs/installing.md
Based on #5796 method 1 may not work.
=> Strikeout iOS installation method 1

Source/qol/stash.cpp
=> Fix OOB access when accessing stash

Packaging/cpi-gamesh/__init__.py, Packaging/cpi-gamesh/build.sh, Packaging/cpi-gamesh/readme.md
recent changes made it necessary to add new packages to be installed and build options to be adapted
=> updated gameshell buildscripts

Source/automap.cpp, Source/debug.cpp, Source/debug.h, Source/objects.cpp, Source/objects.h
This helps if you want to search for a specific monster, item or object.
I used a hard-coded version when working on multiplayer quest support.
Example video:
https://user-images.githubusercontent.com/25415264/221380868-84f72b69-a534-45b8-a00c-4527adc7c01d.mp4
=> Add search monster/item/object debug commands

Source/inv.cpp
=> Telekenisis respects Disable Crippling Shrines Setting

Source/monster.cpp
Fixes #5858
Let Lachdanan rest in peace🙏
=> MP: Send delta message for lachdanans death

Source/objects.cpp
The player who operates the pedestal will invoke `OperatePedestal()` from `OperateObject()`. This will remove the Blood Stone from their inventory and send `CMD_OPERATEOBJ`, `CMD_SYNCQUEST`, and `CMD_SPAWNITEM` commands to remote clients.
Remote players who receive the `CMD_OPERATEOBJ` command for the pedestal will invoke `OperatePedestal()` from `SyncOpObject()` and blindly accept that the quest state has advanced. This will only play the sound effect and update the dungeon layout without sending any additional commands to remote clients.
The `CMD_OPERATEOBJ` command was moved up in `OperateObject()` so that it arrives to remote clients before `CMD_SPAWNITEM`. Otherwise, the Blood Stones and Arkaine's Valor will spawn before the dungeon layout changes and they'll end up dropping outside …
=> Arkaine's Valor: Don't check player inventory when processing CMD_OPERATEOBJ

Source/items.cpp, Source/stores.cpp
=> Sync staff charges after recharging

Translations/uk.po
* TL new settings
* Fix mistakes I found during gameplay
Also, for some reason there are two entries for Warlord of Blood book narration, weird
=> UK TL fixes

Translations/uk.po
* Removes duplicate Warlord of Blood monologue (see #5868)
* Purges previously deleted strings
=> [skip ci] Purge Ukrainian PO file

Source/DiabloUI/settingsmenu.cpp, Source/items.cpp, Source/minitext.cpp, Source/mpq/mpq_writer.cpp, Source/options.cpp
also removes a couple of unused filesystem includes
=> Fix some compilation warnings

docs/installing.md
add note to 3DS install instructions regarding lowercase letters.
=> installing.md update - 3DS install note 

CMake/Assets.cmake
=> Add cutttw.clx to Assets.cmake

Source/controls/devices/game_controller.cpp
=> Add support for new SDL 2.24.0 gamepad types

Source/msg.cpp
This resolves an issue where clients with different `Randomize Quests` settings do not agree on which quests are active in the same game.
The idea here is that the `randomizeQuests` setting does not need to be synced in game init info because `DeltaSyncJunk()` is always called shortly after `InitQuests()` to sync quest state between clients. However, `sgbDeltaChanged` was being used to skip `CMD_DLEVEL_JUNK` if dlvl or quest state hadn't changed since the game was created. The optimization is only relevant if a player joins a game that was newly created, which must have seemed sensible in 1996 to speed up load time and reduce bandwidth for cases where players coordinate their play session in advance or use a game session solely to trade items. However, it has negligible impact on …
=> Remove optimization that skips quest sync at game start

Source/diablo.cpp
I don't consider this a particularly good way of using a gamepad, but it was easy to fix.
This resolves #5971
=> Simulate Shift key for simulated mouse interaction

Source/control.cpp, Source/control.h, Source/controls/plrctrls.cpp, Source/controls/touch/renderers.cpp, Source/cursor.cpp, Source/diablo.cpp, Source/inv.cpp, Source/inv.h, Source/multi.cpp, Source/panels/charpanel.cpp, Source/panels/spell_book.cpp, Source/player.cpp, Source/player.h, Source/qol/chatlog.cpp, Source/stores.cpp
Automatically deactivates after opening stash or entering dungeon
::update
doesn't deactivate after entering dungeon anymore since there's a command for it now so don't have to worry about having to run back to farnham = whatever ;)
=> Check equipment/stats of other players

Source/debug.cpp, Source/missiles.cpp, Source/missiles.h, Source/msg.cpp, Source/objects.cpp, Source/player.cpp, Source/player.h
Replaces `earflag` with a new enum `DeathReason` and refactor `StartPlayerKill`.
Also added some comments to make the behavior hopefully clearer.
=> Refactor earflag

Source/items.cpp
Small improvements to great debug(u) command
- Use `CMD_SPAWNITEM` instead of `CMD_DROPITEM` to make other clients recognize the items
- Support quest uniques (butcher's cleaver etc)
- Don't drop random items on generation failures
=> Improve debug drop(u) command

Source/monster.cpp
=> Fix monster health to +100 for NM and +200 for Hell instead of +1 and +3

Source/controls/controller_motion.cpp
The following in-game menus have their own custom movement handlers for which the player movement actions in padmapper do not apply.
* Stash
* Inventory
* Char panel stat distribution
* Speedbook
* Spellbook
* Quest log
* NPC menus
Since the `GetLeftStickOrDpadDirection()` function only considered whether a d-pad button was pressed in these menus, certain padmapper configurations would cause padmapper actions to trigger at the same time as movement actions in these menus. This code makes some guesses about the intent of the user when d-pad buttons are pressed in these menus to help improve behavior for some of these edge cases.
* If the pad menu navigator is open, the user is likely trying to open or close menus.
* If the d-pad button triggered a padmapper action as part of a button …
=> Improve d-pad handling for in-game menus

Source/objects.cpp
=> Multiplayer: Sync Lazarus stand

Source/dvlnet/zerotier_native.cpp
In cases where players on Windows OS have chosen a username with non-ASCII characters, attempts to create or join games on ZeroTier fail with the error message `Unknown network error`. This PR resolves that error by working around limitations in the ZeroTier library for Windows.
On Windows systems, the default config path resides in `C:\Users\[username]\AppData\Roaming\diasurgical\devilution` which is a path that could have non-ASCII characters based on the player's username. DevilutionX encodes the path as UTF-8 and then passes it to ZeroTier which proceeds to interpret it as an ANSI-encoded path. For paths with non-ASCII characters, this resolves to an entirely different directory under `C:\Users` which does not exist and must therefore be created in order for ZeroTier to store its …
=> Use symlinks to work around lack of Unicode support for paths in ZeroTier

Source/multi.cpp
Motivated by the discussion in https://github.com/diasurgical/devilutionX/pull/6027#discussion_r1175495541.
=> Clean up logic for PT_MESSAGE prioritization

3rdParty/SDL2/CMakeLists.txt, android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java, android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java, android-project/gradlew
Went with this rather than the 2.26.5 release because there are a few fixes there that are not in any release branch.
For example, the SDL2 branch supports audio device selection on Android, while 2.26.5 does not.
Fixes #5810
=> CMake: Update SDL2 to the latest version

.github/workflows/Android.yml, android-project/build.gradle, android-project/gradle.properties, android-project/gradle/wrapper/gradle-wrapper.properties
=> Update to gradle 8.0.0

.github/workflows/Linux_aarch64.yml, .github/workflows/Linux_x86.yml, CMake/platforms/i386-linux-gnu-pkg-config, CMake/platforms/linux_i386.toolchain.cmake, Packaging/nix/debian-cross-i386-prep.sh
Also updates aarch64 to be basically the same as the i386 one.
=> GitHub actions: Automate i386-linux-gnu release

Translations/uk.po
This PR translates new strings for player inspection and arena pots
=> Update Ukrainian TL

Source/DiabloUI/diabloui.cpp, Source/diablo.cpp, Source/diablo.h
#6057 
I think this should also let you take a screenshot while in the drop gold menu, but I didn't test that specifically.
=> Add print screen to event handler for UI

Source/drlg_l4.cpp
Backport for 1.0.x
Note: builds fails cause the build infrastructure is gone...
=> Backport: Correct OOB check in PrepareInnerBorders()

docs/building.md
Add more instructions to detail the whole process further.
=> Add more instructions for Windows MinGW

.circleci/config.yml, .github/workflows/Linux_x86_64.yml, 3rdParty/discord/CMakeLists.txt, CMakeLists.txt, Packaging/nix/AppImage.sh, Packaging/nix/LinuxReleasePackaging.sh, Packaging/nix/debian-host-prep.sh, README.md
Also adds `discord_game_sdk.so` to the Linux release builds.
=> Automate Linux x86_64 release

Source/debug.cpp, Source/debug.h, Source/engine/render/dun_render.cpp, Source/engine/render/dun_render.hpp, Source/engine/render/scrollrt.cpp, Source/player.cpp, Source/player.h
=> debug path command

Source/quests.cpp
=> Multiplayer: Sync Lazarus death correctly

.github/workflows/retrofw_release.yml
Release action run: https://github.com/diasurgical/devilutionX/actions/runs/5008166874
=> Update RetroFW SDK

.github/workflows/Android.yml, 3rdParty/libfmt/CMakeLists.txt
=> Bump libfmt to 10.0.0

Source/player.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/4668
Walking seems to work fine, can't get it stuck anymore, would appreciate if someone else looked at it too
Looks like StartStand does **everything** that StartWalkStand did and more.
=> fix walking animation getting stuck

Source/DiabloUI/hero/selhero.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/5851
=> fix displaying difficulty indicator on hero selection

Source/hwcursor.cpp, Source/hwcursor.hpp
To help debug hardware cursor issues
=> Add optional debug logging for hwcursor

3rdParty/libfmt/CMakeLists.txt
https://github.com/diasurgical/fmt/commit/e421e854efcb21ee641349bab604d91b34af26b8
=> nxdk: Bump libfmt to our port of fmt-10.0.0

3rdParty/asio/CMakeLists.txt
Fixes https://github.com/diasurgical/devilutionX/issues/6074
=> Update to latest ASIO (1.28.0)

Source/stores.cpp, Source/towners.cpp, Source/towners.h
Backwards compatible fix for #6132
=> Map from _talker_id to towner pointer when using gossip option

Source/DiabloUI/diabloui.cpp, Source/diablo.cpp, Source/options.cpp, Source/options.h
Fixes issue with #6058 
Also allows for print screen while in chat.
=> Fix print screen for different print screen key bindings

Translations/es.po
- Corrections in some text strings.
- Simplification of pnj interactions to approach diablo 2 style.
=> Translation spanish - Improvement and simplification of town strings

Source/quests.cpp
=> Always spawn at Farnham when returning from an arena level

Source/loadsave.cpp
=> Sync monster animation data after loading Stone Curse missiles

Source/loadsave.cpp
@obligaron pointed out that attempting to sync the monster animation of a petrified monster before the missiles are loaded will reset the monster's current animation frame to zero. The reset occurs to avoid OOB access to animation data, but if the Stone Curse missile is found later after the missiles are loaded, we may discover that the animation frame should not have been reset. This PR moves the calls to `SyncMonsterAnim()` into their own loop after both monsters and missiles are loaded so that we don't make any mistakes due to incomplete information. This also better matches the pattern for `SyncObjectAnim()`.
=> Only sync monster animations after both monsters and missiles are loaded

.circleci/config.yml
This reverts commit 5ca22170f5317a239bd289134da7bb527f83eb26.
=> Revert "Fix Amiga build to known good container image"

Source/interfac.cpp
=> Clear screen before drawing the loading background

Source/monster.cpp, Source/objects.cpp, Source/towners.cpp
Fixes #5854
Dialogs for:
- The Chamber of Bone
- Gharbad The Weak
- Ogden's Sign
- Lachdanan
- Zhar the Mad
Now only plays for the initiating player
=> Only play the dialogs for the initating player

Source/DiabloUI/diabloui.cpp, Source/init.cpp
=> React to SDL_WINDOWEVENT_RESTORED

android-project/app/src/main/java/org/diasurgical/devilutionx/ExternalFilesManager.java
=> Perform additional null checks in ExternalFilesManager

Source/dvlnet/tcp_client.cpp
=> Fix TCP join crash when entering password for public game

Translations/uk.po
Only 3 new strings, `/seedinfo` and "No room for item" message
=> Update Ukrainian translation for 1.5.1

Source/engine/render/text_render.cpp
Fixes #6247
Fall back to the original PCX fonts was broken as it looked for `file.pcx.pcx` instead of `file.pcx`. This may have resulted in a crash instead of showing the error message about upgrading if the user also had translations enabled.
If a symbol is not available it will now instead fall back to `?`. Only in case that is also unavailable do we terminate with a `Missing fonts` (missing devilutionx.mpq or application assets).
`LoadFont()` now returns a reference instead of a pointer so that we can be sure it's not null once we pass that point and can safely dereference it, as well as use `LoadFont()` direction.
=> Do not crash on missing fonts

Source/loadsave.cpp, Source/missiles.cpp, Source/player.h, test/player_test.cpp, test/writehero_test.cpp
=> Remove unused player property _pISplDur

Source/DiabloUI/multi/selconn.cpp, Source/automap.cpp, Source/dvlnet/loopback.cpp, Source/multi.cpp, Source/multi.h, Translations/bg.po, Translations/cs.po, Translations/da.po, Translations/de.po, Translations/devilutionx.pot, Translations/el.po, Translations/es.po, Translations/fr.po, Translations/hr.po, Translations/it.po, Translations/ja.po, Translations/ko.po, Translations/pl.po, Translations/pt_BR.po, Translations/ro.po, Translations/ru.po, Translations/sv.po, Translations/uk.po, Translations/zh_CN.po, Translations/zh_TW.po
Change Loopback to Offline (visually for end-user) and revise Automap text
Credit goes to @ikonomov for this suggestion
=> Rename: Loopback -> Offline

CMakeLists.txt
=> Add libsdl2-image-2.0-0 as dependency for deb package

Source/diablo.cpp
=> Stop streaming sfx when exiting the game

Source/controls/game_controls.cpp
=> Invoke padmap release handler in menus

Source/engine/render/clx_render.cpp
The actual fix is the diff in `RenderClxOutlineRowClipped`. The rest is refactorings that make the code easier to follow.
Fixes #6199
=> Fix CLX outline clipped rendering on the right

Translations/pt_BR.po
=> Update pt_BR translation

docs/CHANGELOG.md
With this we are finally caught up to the current commits and can start adding changes directly to the change log as they get merged.
=> Update CHANGELOG.md with unreleased changes

Translations/ja.po, docs/CHANGELOG.md
=> Updated Japanese translation.

Packaging/nix/devilutionx.metainfo.xml
* Use GitHub URLs for screenshots, currently all screenshots are the same due to naming mismatch
* Add highlights changelog for 1.5.0 (please review)
* Add categories
=> Metainfo improvements

Source/items.cpp
Fixes my save from vanilla Spawn.
[spawn_0.sv.zip](https://github.com/diasurgical/devilutionX/files/12114950/spawn_0.sv.zip)
=> Make Bucklers available in shareware

android-project/build.gradle
My technical situation allows me to test Android code again!
Being stuck with 128 GB of storage sucks
This is done on recommendation of Android Studio, and has some good bugfixes
https://developer.android.com/build/releases/gradle-plugin#agp-8-0-2
=> Upgrade gradle Android plugin

Source/missiles.cpp
Fixes #6338
Notes
- Warp didn't check target position is not free. This includes solid objects (source of #6338) but also true for monsters and players. So with warp you could place yourself on the same tile as a monster. :wink:
- Warp can only be casted by a player-"source". So simplified `AddWarp`. `ProcessTeleport` also doesn't check missile source, so it should be fine.
- Teleport (and phasing) position is checked on cast (`AddTeleport`, `AddPhasing`) but not validated again when the teleport is executed (`ProcessTeleport`). Normally this is not a problem, because `AddTeleport` and `ProcessTeleport` happens in the same game tick. But in multiplayer with two players both casting simultaneous on the same target tile this initial check is not sufficient. So another check in …
=> Ensure warp and teleport target position is free

Translations/glossary.md
lint markdown and fix some markdown grammar errors.
=> lint markdown

Translations/uk.po
* Accommodate "Loopback" to "Offline" change
* Properly translate CLI parameters for arena
=> Update Ukrainian TL for 1.5.1

Source/DiabloUI/diabloui.cpp, Source/DiabloUI/title.cpp, Source/control.cpp, Source/debug.cpp, Source/dvlnet/zerotier_native.cpp, Source/engine/render/text_render.cpp, Source/inv.h, Source/levels/themes.cpp, Source/levels/trigs.cpp, Source/loadsave.cpp, Source/options.cpp, Source/panels/charpanel.cpp, Source/panels/spell_list.cpp, Source/plrmsg.cpp, Source/qol/autopickup.cpp, Source/qol/autopickup.h, Source/utils/algorithm/container.hpp, Source/utils/language.cpp
Adds handy helpers for performing algorithms on the entire container. They're prefixed with `c_` for container.
This naming convention is identical to some popular C++ libraries, such as Abseil.
=> Add `c_any_of` and friends

Source/engine/render/text_render.cpp, Source/options.cpp
=> Support language-specific font variants

Source/engine/path.cpp, Source/levels/drlg_l3.cpp, Source/msg.cpp, Source/pfile.cpp, Source/portal.cpp, Source/portal.h, Source/stores.cpp
Some typos cleanup and renaming stuff to make more sense
=> Code typos cleanup

Source/player.cpp
https://github.com/diasurgical/devilutionX/assets/68359262/a981e9d8-ef46-4317-9060-111846162eba
Sound closely resembles the sound used in Diablo 2 for level ups. Specifically chosen due to that, because it will be familiar for D2 players trying out D1, and the fact that it's a canon Brevik design choice.
=> D2 Style Level Up Sound

Source/engine.h, Source/utils/static_vector.hpp, Source/utils/stdcompat/abs.hpp, Source/utils/stdcompat/algorithm.hpp, Source/utils/stdcompat/cstddef.hpp, Source/utils/stdcompat/invoke_result_t.hpp, Source/utils/stdcompat/optional.hpp, Source/utils/stdcompat/string_view.hpp, Source/utils/str_cat.hpp
With this, we will require C++17 at the minimum (except for std::filesystem which is still optional)
Let's see if anything other than Amiga breaks
=> Remove C++11 compatibility code

Source/player.cpp
=> Don't use walk animation as preview frame for standing attack

.circleci/config.yml
Reverts diasurgical/devilutionX#6056
=> Revert "Test GCC 13 for Amiga builds"

Source/objects.cpp
=> Clean up `IsAreaOk`

android-project/app/build.gradle, android-project/build.gradle, android-project/gradle/wrapper/gradle-wrapper.properties
* Upgrade Gradle and Android plugin
* Change `compileSdkVersion` since it's deprecated
* Change `task` to `tasks.register` on Android Studio suggestion
Relates to #6479
=> Android upgrades

Source/utils/stdcompat/shared_ptr_array.hpp, android-project/app/build.gradle, android-project/gradle/wrapper/gradle-wrapper.properties
Latest Gradle
Latest Android SDK
latest Android NDK
Fixes:
=> Bump Android build chain to the latest from Google

Source/stores.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/6120
https://github.com/diasurgical/devilutionX/assets/68359262/3bd723c8-c595-424b-bb18-e4cbcf53b38f
=> Close Towner window when clicking outside

Source/diablo.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/6307
Right click now exits dialogue window.
=> Fix right click during dialogue

Source/error.cpp, Source/error.h, Source/gamemenu.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/6259
=> Add Save Game confirmation

Source/cursor.cpp, Source/inv.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/846
=> Fix cursor jitter when clicking inv items

.github/workflows/Android.yml
See if this fixes the Android CI build errors.
=> Change cache version in Android CI script

Source/cursor.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/6525
=> Fix selecting monsters that are out of vision range

Source/debug.cpp, Source/dvlnet/base_protocol.h, Source/dvlnet/cdwrap.h, Source/dvlnet/protocol_zt.cpp, Source/engine/point.hpp, Source/engine/render/dun_render.cpp, Source/engine/render/scrollrt.cpp, Source/loadsave.cpp, Source/msg.cpp, Source/objects.cpp, Source/options.cpp, Source/options.h, Source/panels/charpanel.cpp, Source/pfile.cpp, Source/qol/itemlabels.cpp, Source/qol/stash.cpp
=> Use structured bindings

Translations/sv.po
=> Small changes to swedish translation

Source/player.cpp, Source/player.h
added in player methods, one to determine if character can cleave and the other to determine if an item is equipped.
=> Refactor cleaving

.github/workflows/Linux_aarch64.yml
No idea why specifying these dependencies explicitly fixes the issue but oh well
=> Fix Linux_aarch64 build

Packaging/OpenDingux/profile-generate.sh, Packaging/OpenDingux/rg99-pgo.md, Source/engine/demomode.cpp, Source/pfile.cpp
This entirely eliminates the demo memory overhead.
=> Stream demo messages

Packaging/nix/LinuxReleasePackaging.sh
=> Add "$@" to devilutionx.sh to pass arguments to devilutionx executable

Source/control.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/6565
=> fix inspect on players where one name is a substring of another

.github/workflows/s390x_qemu_big_endian_tests.yml, 3rdParty/libmpq/CMakeLists.txt, Source/CMakeLists.txt, Source/encrypt.cpp, Source/encrypt.h, Source/engine/assets.cpp, Source/init.cpp, Source/mpq/mpq_common.cpp, Source/mpq/mpq_common.hpp, Source/mpq/mpq_reader.cpp, Source/mpq/mpq_reader.hpp, Source/mpq/mpq_writer.cpp, Source/mpq/mpq_writer.hpp, tools/run_big_endian_tests.sh
Reuse libmpq functions where possible instead of our own.
=> Deduplicate some of the MPQ handling

Source/engine/render/clx_render.cpp, Source/engine/render/dun_render.cpp
=> Use `if constexpr` in clx/dun_render

Source/debug.cpp
=> Fix spawn and spawnu

Source/debug.cpp
Also fixes clang format - had a extra line in there.
=> add missing continue from #6594

Source/dvlnet/base_protocol.h, Source/engine.h, Source/levels/gendung.cpp
Structs are more readable because the fields have names.
=> Replace tuples with structs

Source/automap.cpp
=> Add `AutomapTile#hasAnyFlag`

Source/automap.cpp
Adds lava to the automap that was originally added to https://github.com/diasurgical/devilutionX/pull/6555 but removed to reduce the PR scope.
=> Automap: Add Lava

Source/automap.cpp, Source/automap.h, Source/engine/render/automap_render.cpp, Source/engine/render/automap_render.hpp
=> Automap: Pentagram

Source/automap.cpp
Fixes a change made in https://github.com/diasurgical/devilutionX/pull/6604 that broke lava rivers
=> Automap: Fix DrawLavaRiver()

.github/workflows/Windows_MSVC_x64.yml, vcpkg.json
This is to upgrade SDL2 to 2.28.3 in MSVC builds
=> Upgrade vcpkg baseline commit

Source/debug.cpp
https://github.com/diasurgical/devilutionX/assets/68359262/a7ba3ea1-fd13-42a7-acd6-dd9a0adf611d
=> Debug: Convert DiabloMsg to EventPlrMsg

Source/engine/render/scrollrt.cpp, Source/levels/gendung.cpp, Source/levels/gendung.h, Source/utils/enum_traits.h
This appears to be a very hot function.
Makes it fully inlineable (even in Debug mode).
=> Make `IsWall` easier for the compiler to inline

Source/engine/render/scrollrt.cpp
Avoids calling `FindObjectAtPosition` and similar pre-checks twice.
=> `DrawDungeon`: Move checks out of `DrawObject/Item`

Source/utils/file_util.cpp
`SetFilePointerEx` returns 0 on failure but `SetFilePointer` returns `INVALID_SET_FILE_POINTER`.
Also now closes the handle in `GetFileSize` (fixes #6637)
=> `ResizeFile`: Fix `SetFilePointer` return type check

Source/utils/sdl2_to_1_2_backports.cpp
Reduces noisy logging in stderr.txt.
On Windows9x there is no such thing as PrefPath, so there is no point in trying to get/create one.
Also fixes `SDL_GetBasePath()` to return the directory path rather than
the exe path.
=> Windows 9x: Return "" from `SDL_GetPrefPath`

Source/engine/render/scrollrt.cpp
This check was only needed when the tile to the east was drawn first. Checks for this with a single bool rather than a whole bitset.
=> `DrawDungeon`: Remove `dRendered` check

3rdParty/libfmt/CMakeLists.txt
Brings in some slight optimizations from upstream
=> Bump libfmt

Source/player.cpp
Demonstration of what's being fixed:
https://github.com/diasurgical/devilutionX/assets/68359262/0ca5688b-0ca3-4e5a-ad9b-c72f21fe0a57
=> Bugfix: Speed spell on item swap

.github/workflows/Windows_MSVC_x64.yml
MS requested some feedback regarding some new integrations they are working on with VCPKG
> The Microsoft C++ team has been working with our partners at GitHub to improve the C and C++ user experience on their platform. As a part of that effort, we have added vcpkg support for the GitHub dependency graph feature. We are looking for feedback from GitHub repositories, like diasurgical/devilutionX, that are using vcpkg so we can identify improvements to this new feature.
>
> Enabling this feature for your repositories brings a number of benefits, now and in the future:
>- Visibility – Users can easily see which packages you depend on and their versions. This includes transitive dependencies not listed in your vcpkg.json manifest file.
>- Compliance – Generate an SBOM from GitHub that …
=> Enable VCPKG dependency graph

Source/player.cpp
=> Prevent softlock when removing Auric Amulet

Source/engine/render/text_render.cpp
=> Insert newline for words longer than width in WordWrapString()

Source/objects.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/6668
=> add trap sound to trapped chests

Source/.clang-tidy
These are very noisy and not particularly helpful.
=> Disable a couple of clang-tidy checks

Source/plrmsg.cpp
Tested with some unlikely extremes.
=> Use DrawStringWithColors() in plrmsg

Source/qol/chatlog.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/6651
=> chatlog refactor

Source/automap.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/6694
=> Fix automap

Source/DiabloUI/text_input.cpp, Source/DiabloUI/text_input.hpp, Source/control.cpp, Source/control.h, Source/diablo.cpp, Source/engine/render/scrollrt.cpp, Source/engine/render/text_render.hpp, Source/inv.cpp, Source/objects.cpp, Source/qol/stash.cpp, Source/qol/stash.h
With this, all text input is handled in a unified way.
=> Migrate gold drop/withdrawal to `text_input`

Packaging/switch/README.txt
PR was created as per the comments here:
https://github.com/diasurgical/devilutionX/issues/6740
=> Update Switch README.txt

.github/workflows/xbox_nxdk.yml
Flags from https://github.com/XboxDev/nxdk/blob/ed21e83da43b8b8da14a9a78cf2528d9b5df86a7/.github/workflows/build_docker_image.yml#L14-L23
=> nxdk: Build in optimized mode

Source/DiabloUI/diabloui.cpp, Source/DiabloUI/text_input.cpp, Source/DiabloUI/text_input.hpp, Source/DiabloUI/ui_item.h, Source/control.cpp, Source/control.h, Source/engine.cpp, Source/engine.h, Source/engine/render/text_render.cpp, Source/engine/render/text_render.hpp, Source/qol/itemlabels.cpp, Source/qol/stash.cpp
Adds shift selection, Ctrl+C and Ctrl+X handling, and Ctrl/Alt word navigation.
Also fixes left-right movement for non-ASCII characters.
=> Text inputs: Selection, copy, cut

docs/github-codespaces.md
=> fix: typo error in github-codespaces.md

docs/CHANGELOG.md
There are a few typing errors in the changelog.md in docs folder. This PR fixes those mistakes.
=> fixed typos in changelog.md

docs/CHANGELOG.md
#6751 
pretty sure it was supposed to be "charges" when referring to staves, not "changes"
=> Fix incorrect word from typo fix PR

docs/BACKGROUND.md, docs/CHANGELOG.md, docs/building.md
There are a couple of spelling mistakes in the changelog.md file. This PR fixed these errors.
=> Corrected Typos

CMake/Assets.cmake, Packaging/resources/assets/lua/inspect.lua, Source/lua/lua.cpp
Adds `inspect` from https://github.com/kikito/inspect.lua This will be part of the console prelude.
=> Lua: Add `inspect` package

Source/CMakeLists.txt, Source/engine/render/text_render.cpp, Source/engine/render/text_render.hpp, Source/lua/autocomplete.cpp, Source/lua/autocomplete.hpp, Source/lua/lua.hpp, Source/lua/repl.cpp, Source/lua/repl.hpp, Source/panels/console.cpp
https://github.com/diasurgical/devilutionX/assets/216339/fc322f33-75fc-49f8-9949-9a4dc39ba81e
=> Lua: Add basic autocomplete in the console

android-project/app/src/main/java/org/diasurgical/devilutionx/ImportActivity.java, android-project/app/src/main/res/values/strings.xml
=> Add info popup to the Import Data activity

Packaging/resources/assets/lua/init.lua, Source/lua/lua.cpp, Source/lua/lua.hpp, Source/lua/repl.cpp, Source/panels/console.cpp
1. Every script runs in its own sandbox.
2. `Events` is the only global shared state.
3. `os` datetime functions are now available.
=> Lua: Implement sandbox

Source/levels/drlg_l4.cpp, Source/portal.cpp, Source/utils/soundsample.cpp, test/missiles_test.cpp
I added different commits so that is easier to see what the relation change to warning is.
Feel free to squash.
Remaining warnings in debug build with tests: 401 (mostly narrowing warnings)
=>  Fix a few MSVC warnings

Source/levels/gendung.h, Source/levels/themes.cpp, Source/levels/themes.h
This reduces warnings by 15 (from 401 to 386)
=> Fix MSVC warnings in themes.cpp

Source/DiabloUI/text_input.hpp
Fixes out of bounds writing while exceeding max allowed length
=> fix calculating length remaining till hitting limit

Source/lighting.cpp, Source/lighting.h, Source/multi.cpp, Source/multi.h
Seeing this one pop up a lot in the GitHub UI as of late, maybe this will fix part of it.
=> Fix warning when calling NetSendHiPri() wiht MyPlayerId

Source/automap.cpp, Source/control.cpp, Source/controls/plrctrls.cpp, Source/cursor.cpp, Source/cursor.h, Source/diablo.cpp, Source/engine/render/scrollrt.cpp, Source/player.cpp, Source/track.cpp
Removes some uses of the player id in the context of an array index (where size_t is more appropriate), trading for a few extra uses in a network context (where plr_t is more appropriate).
=> Use pointers/references for highlighting players/automap markers

Source/lua/modules/dev/level.cpp
=> Add `dev.level.seed()` debug command

Source/control.cpp, Translations/pl.po
Changes contained:
* reusing `Command ` and ` is unknown.` strings by concatenating more strings instead of introducing new ones ([b728df4](https://github.com/diasurgical/devilutionX/pull/6814/commits/b728df41687d1df60be61e3c47f8dc796034e1c5))
* syncing `pl.po` with the source code -- there are no manual changes in this commit ([c9fbea3](https://github.com/diasurgical/devilutionX/pull/6814/commits/c9fbea3c3ca0de850b911600415074b1ba9b2d1e))
* update or add several Polish translations ([935e993](https://github.com/diasurgical/devilutionX/pull/6814/commits/935e993328f44b4030aab4e8090146c4f753d889))
=> Update polish translation

Translations/uk.po
Syncs PO with current state of code and translates some new strings
=> Update Ukrainian translation for 1.6.0

Source/dvlnet/abstract_net.h, Source/dvlnet/base_protocol.h, Source/dvlnet/protocol_zt.cpp, Source/dvlnet/protocol_zt.h
=> Get rid of protocol_exception

Translations/pl.po
Updating a bunch of translations and adding new ones for Polish language.
=> Update Polish translation.

Source/msg.cpp, Source/pack.cpp, Source/pack.h, test/pack_test.cpp
Cherry-picked #6679 into master
=> Validation: Item Drop Packets

Source/DiabloUI/credits.cpp, Source/DiabloUI/diabloui.cpp, Source/DiabloUI/diabloui.h, Source/DiabloUI/hero/selhero.cpp, Source/DiabloUI/mainmenu.cpp, Source/DiabloUI/multi/selconn.cpp, Source/DiabloUI/multi/selgame.cpp, Source/DiabloUI/multi/selgame.h, Source/DiabloUI/selok.cpp, Source/DiabloUI/selstart.cpp, Source/DiabloUI/selyesno.cpp, Source/DiabloUI/settingsmenu.cpp
This PR reduces warnings by 11 (from 232 to 221).
The main change is a small refactoring (Change DiabloUI list callbacks indexes from int to size_t).
=> Fix warnings in DiabloUI

Translations/es.po
Correct some translations and complete with new ones
=> Correct and complete

Source/objects.cpp
This PR reduces warnings by 10 (from 84 to 74)
=> Fix MSVC warnings in objects.cpp

Source/dvlnet/base.cpp, Source/dvlnet/frame_queue.cpp, Source/dvlnet/protocol_zt.cpp, Source/storm/storm_net.hpp
This PR reduces warnings by 8 (from 40 to 32)
=> Fix remaining MSVC warnings in network code

Source/DiabloUI/hero/selhero.cpp, Source/DiabloUI/multi/selconn.cpp
=> DiabloUI: Fix Japanese text clipping

Source/DiabloUI/hero/selhero.cpp, Source/DiabloUI/multi/selconn.cpp
=> DiabloUI: Fix Japanese text clipping (cherry-pick for 1.5)

.github/workflows/s390x_qemu_big_endian_tests.yml
Seems to be needed for SDL2_image https://github.com/diasurgical/devilutionX/actions/runs/7781145615/job/21215031007
=> s390x_qemu_big_endian_tests.yml: Add jpeg-dev package

.circleci/config.yml
This reverts commit ff57b6be07d1c3b269746caa00baf55cf11f61b8.
=> Revert "Lock Switch build image to known good version"

docs/installing.md
=> Update installing.md - add note about long press to android instructions

Source/controls/plrctrls.cpp, Source/towners.h
Fixes: https://github.com/diasurgical/devilutionX/issues/7004
Haven't been able to test since I'm on M&K, please confirm.
=> Bugfix: Celia Infostring displaying after quest

Source/loadsave.cpp
Moved these functions to the anonymous namespace and then remembered to call them this time. 😅
=> Call the functions to save/load level seeds in the SP save files

.editorconfig, Packaging/nix/devilutionx.metainfo.xml
* Added custom rule for XML to use LF
* Converted metainfo to LF
=> Fix metainfo XML for future patching

Source/diablo.cpp, Source/inv.cpp, Source/inv.h
We can add stash sorting later
=> Sort inventory

CMake/Assets.cmake, Source/options.cpp, Translations/hu.po, android-project/app/src/main/res/values-hu/strings.xml
Dear devilutionX team!
I have seen no Hungarian translation yet, so I made one last week.
I've found a way to make unique item names seem not too strange and wrote some rhymes as shrine texts for flavor. There was a half a playthrough worth of proofreading and playtesting involved that caught many errors and oddities, but there may be many more yet. Any potential feedback is more than welcome, as some things were not thoroughly tested yet and not everyone may agree on every new name.
There are two commits. cda79e9 is based on devilutionx.pot as it is, f8ef261 is the same after updating it from the code in poedit. I'm not sure if translations may be updated from the code this way without breaking things, so I put them in separate commits.
=> Add Hungarian translation

Source/engine/render/scrollrt.cpp
Remove unused function parameter
=> Clean up: DrawMain()

Source/missiles.cpp
Removed unused function parameter
=> Clean up: ProjectileTrapDamage()

Source/engine/render/scrollrt.cpp
Uses safer methods and removes compiler warnings.
=> Clean up: DrawDungeon()

Source/debug.cpp, Source/engine/path.cpp, Source/engine/render/scrollrt.cpp, Source/levels/gendung.h, Source/levels/themes.cpp, Source/lighting.cpp, Source/missiles.cpp, Source/monster.cpp, Source/objects.cpp
=> Refactor TileHasAny()

Source/lighting.cpp
Clear compiler warnings with explicit type casting and correct case for constexpr
=> Clean up: MakeLightTable()

.github/workflows/iOS.yml, .github/workflows/macOS_x86_64.yml, 3rdParty/SDL2/CMakeLists.txt, android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java, android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java, android-project/build.gradle, android-project/gradle/wrapper/gradle-wrapper.properties
* SDL2 to 2.30.2 bugfix
* Gradle to 8.7
* Android Gradle plugin to 8.3.2
Playtested to my Google Pixel 2, Android 11
@AJenbo worth cherry-picking into 1.5.3?
=> General Android upgrades

Source/loadsave.cpp, Source/missiles.cpp, Source/missiles.h
=> Fix crash loading game with Search missile

Packaging/windows/mingw-prep.sh, Packaging/windows/mingw9x-prep.sh
SDL2 2.26.1 -> 2.30.3
Sodium 1.0.18 -> 1.0.20
=> Update mingw scripts to latest dependency releases

Source/CMakeLists.txt, Source/utils/language.cpp, Source/utils/language.h, test/CMakeLists.txt, test/language_for_testing.cpp
=> Make a few more libraries standalone

.github/workflows/iOS.yml, .github/workflows/macOS_x86_64.yml
No sense leaving this on macos-11 at this point.
=> Update CI to macos-12

.editorconfig, .github/workflows/Windows_MSVC_x64.yml, 3rdParty/SDL2/CMakeLists.txt, Packaging/windows/mingw-prep.sh, android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java, android-project/app/src/main/java/org/libsdl/app/SDL.java, android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, tools/update_sdl_android_project.sh, vcpkg.json
Also adds a script for updating the android-project Java files (`tools/update_sdl_android_project.sh`)
=> Bump SDL to v2.30.5

Translations/zh_CN.po
1. Update translation file from source code.
2. Complete missing translations.
3. Fix wrong translations such as "骷髅帽" (Skull Cap). The word "骷髅帽" means a cap made of skull or with a skull on it. New translation is "颅顶盔". It means a cap that covers the top of the skull.
=> update zh_CN translation

README.md
replaced link to circleci with link to readme section for test builds
=> Remove link to circleci latest builds

Source/player.cpp
Look up `player.position.tile` only once.
=> Optimize DeadItem()

Translations/bg.po, Translations/cs.po, Translations/da.po, Translations/de.po, Translations/devilutionx.pot, Translations/el.po, Translations/es.po, Translations/fr.po, Translations/hr.po, Translations/hu.po, Translations/it.po, Translations/ja.po, Translations/ko.po, Translations/pl.po, Translations/pt_BR.po, Translations/ro.po, Translations/ru.po, Translations/sv.po, Translations/tr.po, Translations/uk.po, Translations/zh_CN.po, Translations/zh_TW.po
Follow-up to https://github.com/diasurgical/devilutionX/pull/7175
=> Fix "Book of" translations

Translations/devilutionx.pot, tools/update_translations_pot.py
Updates Translations/devilutionx.pot using xgettext
=> Add tools/update_translations_pot.py

Source/effects.cpp, Source/effects.h, Source/effects_stubs.cpp, assets/txtdata/sound/effects-unused.tsv, assets/txtdata/sound/effects.tsv
Follow-up to #7310
Also removes 1 more unused sound
=> Remove missing SfxID

Source/utils/utf8.hpp
A few more operations but the "lookup table" is now an immediate constant.
https://godbolt.org/z/7YG3ohWT6
=> Slightly optimize `Utf8CodePointLen`

Source/inv.cpp
0.4% of the timedemo profile -> 0.2%
=> Optimize InvDrawSlotBack

Source/engine/render/blit_impl.hpp, Source/engine/render/clx_render.cpp, Source/engine/render/clx_render.hpp, Source/engine/render/scrollrt.cpp, Source/engine/render/scrollrt.h, Source/gmenu.cpp, Source/inv.cpp
Also removes the redundant `DrawPlayerHelper` function.
=> Remove `LightTableIndex` global and add `ClxDrawBlended`

Source/player.cpp
Prevents multiple lookups to the Items array.
=> Optimize RespawnDeadItem()

Source/engine/render/clx_render.cpp
Follow-up to https://github.com/diasurgical/devilutionX/pull/7157
=> Further increase outline pixels to 2048

test/animationinfo_test.cpp
=> animationinfo_test.cpp: Add missing include

Source/engine/render/dun_render.cpp
=> dun_render: Fix dark triangle rendering

Source/engine/render/dun_render.cpp
Previously, there were 2 loops to render all the lines of a diamond. This changes it to call `RenderLeftTriangle` + `RenderRightTriangle`. That's 4 loops + some extra clipping calculations
Yet, this version is ~28% faster.
I don't understand why it's faster at all.
Perhaps it's only faster on some hardware?
Modern computers are magic.
Anyway, here are the (very surprising) results on my Ryzen 3950x:
```
BASELINE=master
BENCHMARK=dun_render_benchmark
git checkout "$BASELINE"
tools/build_and_run_benchmark.py -B "build-reld-${BASELINE}" --no-run "$BENCHMARK"
git checkout -
tools/build_and_run_benchmark.py --no-run "$BENCHMARK"
tools/linux_reduced_cpu_variance_run.sh ~/google-benchmark/tools/compare.py -a benchmarks \
"build-reld-${BASELINE}/${BENCHMARK}" "build-reld/${BENCHMARK}" \ …
```
=> Speed up `world_draw_black_tile`

Source/engine/render/dun_render.cpp
Follow-up to https://github.com/diasurgical/devilutionX/pull/7357
=> dun_render: Fix OOB in `world_draw_black_tile`

Source/stores.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/7350 and also fixes recharge - identify didn't have this bug because money was being taken after the item was identified
=> fix repair and recharge

Source/engine/render/dun_render.cpp, Source/engine/render/scrollrt.cpp, Source/utils/attributes.h
Extracted from various open PRs, for ease of reviewing.
=> Minor rendering cleanups

Source/engine/render/clx_render.cpp
Fixes: https://github.com/diasurgical/devilutionX/issues/7385
=> Increase MaxOutlinePixels

Source/engine/render/scrollrt.cpp
Floor tiles always come in pairs. If the left triangle (mt[0]) exists, so does the right one.
=> DrawFloor: Remove a redundant check

Source/engine/render/dun_render.cpp, test/dun_render_benchmark.cpp
Removes the last remnants of foliage masks support from `dun_render`.
=> dun_render: Clean up foliage masks code

Source/engine/render/scrollrt.cpp
This reverts commit a75f77bfa87b6960a9853281b6ab3cc2048a2a61.
Revert the commit while we investigate the issue
Refs #7404
=> Revert "DrawFloor: Remove a redundant check"

.github/workflows/Windows_MSVC_x64.yml, 3rdParty/SDL2/CMakeLists.txt, android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, vcpkg.json
This SDL release fixes some Linux bugs
Release notes: https://github.com/libsdl-org/SDL/releases/tag/release-2.30.7
I have tested Windows MSVC, Android and Linux builds
=> Upgrade SDL to 2.30.7

README.md
Minor fixes to formatting and grammar.
=> Revise Readme

README.md
Can't figure out how to get a good url for this. :(
Anyway, this is intended to showcase the current state of the game (The font and XP bar have changed), as well as showcasing as many QOL features in one shot as possible.
=> New Readme Graphic

Source/stores.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/7422
=> fix being able to repair equipped items for free

CMake/Assets.cmake, Source/options.cpp, Translations/et.po
Dear Maintainer, thank you for providing this piece of gaming history in an approachable format. I'm submitting an Estonian translation patch in the hopes that it will be accepted to the main branch.
Contents:
- First iteration of Estonian translations 🇪🇪 
- Added "Eesti" to Language options as well as included the strings to the Asset file.
- Some playtesting has been completed already to accommodate and change longer strings to shorter ones to ensure proper UI renderings without overlap.
Waiting for your feedback and hoping this patch gets accepted. A small boy is eager to cleanse Sanctuary from the evil devilish forces 🎸 
Cheers! 🍻
=> 🇪🇪 ET Translation patch

Translations/ja.po
- Untranslated text has been translated.
- Hellfire translation adjusted.
=> Update ja_JP translations

Source/utils/paths.cpp
A small tweak to the previous patch for better Haiku support to ensure the path provided by the function is fine for that usecase
=> A small tweak to the Haiku patch

Source/utils/paths.cpp
=> Fix clang-format violation

android-project/build.gradle, android-project/gradle/wrapper/gradle-wrapper.properties
Upgrades Gradle to 8.9 and Gradle Android plugin to 8.7.1
There are more upgrades I could do, like NDK or CMake, I will do those in another PR
=> Upgrade some Android stuff

Source/monster.cpp
See https://github.com/diasurgical/devilutionX/pull/7449#issuecomment-2445647224
=> [1.5] Tweak logic to wake up the whole pack of Gargoyles when disturbed

Source/init.cpp, Source/utils/file_util.cpp, Source/utils/logged_fstream.hpp
=> [1.5] `LoggedFstream`: Fix `OpenFile` error check

Source/controls/plrctrls.cpp, Source/engine/path.cpp, Source/engine/path.h, test/path_test.cpp
Rename functions to better reflect what they do.
=> Pathfinding: Rename functions

docs/building.md
Small PR - adjusts the references in `docs/building.md`.
=> Update building references

README.md
=> Fix link to mods wiki page

.github/workflows/Windows_XP_32bit.yml
Automatically Creates a Windows XP build on a new Release being created.
=> Build for Windows XP on release

CMake/Platforms.cmake
=> Add missed windowsXP string for TARGET_PLATFORM cache

Source/DiabloUI/multi/selgame.cpp, Source/dvlnet/base.cpp, Source/dvlnet/base_protocol.h, Source/dvlnet/frame_queue.cpp, Source/dvlnet/packet.h, Source/dvlnet/tcp_server.cpp, Source/multi.cpp, Source/multi.h, Source/storm/storm_net.hpp
Forward port of #7594 to master
=> Big-endian networking fixes

Source/items/validation.cpp
Backport of #7612 on the 1.5 branch
=> [1.5] Don't apply dungeon item validation to town items

Translations/ru.po
Russian localisation update - translated new settings, text and names of quest items are adapted to the voice acting from "Stream"
=> ru.po update

Translations/uk.po
Just translating new strings, seeing there are some for 1.6
If anyone bothers to review this, go the second commit
=> UK.po - translate new strings

Source/CMakeLists.txt, Source/control.cpp, Source/diablo.cpp, Source/diablo.h, Source/options.cpp, Source/options.h, Source/quick_messages.cpp, Source/quick_messages.hpp
Eliminates an options->diablo dependency.
=> Move QuickMessages to its own library

Translations/ru.po
=> Correct 9 and add 2 new translations

Translations/uk.po
Backport of #7657 to 1.5 + translating some new strings that were missed there
=> [1.5] Ukrainian TL fixes

Source/DiabloUI/settingsmenu.cpp, Source/options.cpp
Compiled with x64/x86 and debug/release combinations.
=> Fix MSVC warnings

Translations/ru.po
all last updates from the master in 1.5
=> [1.5] Update ru.po 

Source/diablo.cpp, Source/options.cpp, Translations/devilutionx.pot, Translations/es.po, Translations/it.po, Translations/ja.po, Translations/pl.po, Translations/ru.po, Translations/uk.po, Translations/zh_CN.po
=> [1.5] Hotkeys: Support more keybindings

Source/levels/drlg_l3.h
=> remove empty line

.github/workflows/Android.yml, .github/workflows/Linux_aarch64.yml, .github/workflows/Linux_x86.yml, .github/workflows/Linux_x86_64.yml, .github/workflows/Linux_x86_64_SDL1.yml, .github/workflows/PS4.yml, .github/workflows/Windows_MSVC_x64.yml, .github/workflows/Windows_MinGW_x64.yml, .github/workflows/Windows_MinGW_x86.yml, .github/workflows/iOS.yml, .github/workflows/macOS_x86_64.yml, .github/workflows/miyoo_mini_release.yml, .github/workflows/opendingux_release.yml, .github/workflows/retrofw_release.yml, .github/workflows/src_dist_release.yml, .github/workflows/xbox_nxdk.yml, .github/workflows/xbox_one.yml, Source/mpq/mpq_writer.cpp
Backports #7694 into the 1.5 branch
=> [1.5] Avoid write mode when opening save files

Source/mpq/mpq_writer.cpp
Backports #7696 into the 1.5 branch
=> Do not depend on FileExists() when opening save files for writing

.github/workflows/Windows_MSVC_x64.yml, vcpkg.json
=> Upgrade SDL2 for MSVC

Source/controls/plrctrls.cpp
Backports #7722 into the 1.5 branch
=> [1.5] Don't delete items during lag spike

Source/controls/plrctrls.cpp
=> Don't delete items during lag spike

Packaging/nix/devilutionx.metainfo.xml
* Add branding colours
* Rewrite summary, previous one failed as too technical
Progresses #7746
=> Improve metainfo

Source/diablo.cpp
=> Enable CTRL + Mouse scroll wheel for map zoom

.github/workflows/Windows_MSVC_x64.yml, vcpkg.json
This catches up SDL version for MSVC
=> Upgrade VCPKG commit for SDL2 2.32.0

Translations/it.po
=> Update Italian localization (close #7783)

.github/workflows/3ds.yml, 3rdParty/SheenBidi/CMakeLists.txt, CMakeLists.txt, Source/utils/utf8.cpp
Use the `SBCodepointDecodeNextFromUTF8` function introduced in https://github.com/Tehreer/SheenBidi/pull/33
=> Update SheenBidi and use the new decoding function

Packaging/nix/devilutionx.metainfo.xml
#7802 for 1.5 branch
Thank you to @bbhtt for the suggestion
=> [1.5] Fix license for Flatpak

Packaging/nix/devilutionx.metainfo.xml
Thank you to @bbhtt for the suggestion
=> Fix license for Flatpak

Source/engine/render/light_render.cpp
Fixes the light rendering issue you can see below the player in the following screenshot.
=> Fix light rendering issue in case 13 of marching squares

Source/engine/render/light_render.cpp
=> Extend edge lights to infinity when rendering per-pixel light buffer

assets/txtdata/items/itemdat.tsv
- "Heart" changed to "Ear"
- Changed "Quest" to "Misc"
- Removed cursor graphic (the game assigns one based on hero class)
- "Non Item" changed to ""
- Removed cursor graphic
- "Scroll of None" changed to ""
- Zeroed/nulled data to match "Non Item"
=> Cleanup itemdat.tsv

Source/monster.cpp
Backport #7841 to the 1.5 branch
=> [1.5] Check for MonsterMode::Death in isPossibleToHit()

Source/control.cpp, Source/controls/game_controls.cpp, Source/controls/plrctrls.cpp, Source/controls/touch/event_handlers.cpp, Source/controls/touch/renderers.cpp, Source/diablo.cpp, Source/engine/render/scrollrt.cpp, Source/inv.cpp, Source/qol/chatlog.cpp, Source/qol/itemlabels.cpp, Source/qol/stash.cpp, Source/stores.cpp, Source/stores.h, Source/track.cpp
Adds helper function as prerequisite to https://github.com/diasurgical/DevilutionX/pull/7424
=> Stores - IsPlayerInStore()

Source/control.cpp, Source/gamemenu.cpp
Fix warnings introduced by #3902
=> Fix warnings from menu text revision

3rdParty/SDL2/CMakeLists.txt, android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, android-project/build.gradle, android-project/gradle/wrapper/gradle-wrapper.properties
* Gradle plugin to 8.8.0
* Gradle to 8.10.2 (latest compatible)
* SDL2 to 2.32.2
Playtested on my device and emulator, everything works
=> Upgrade dependencies in Android build

Source/utils/paths.cpp
Well, turns out that bunch of code is not really needed, lmao.
=> Scrap Haiku-specific code, unneeded

Source/loadsave.cpp
This PR implements basic file size validation for the stash.
=> Validate stash size to avoid in-game corruption of stashed items

Source/loadsave.cpp
Backport of #7934 into the 1.5 branch
=> [1.5] Validate stash size to avoid in-game corruption of stashed items

Source/diablo.cpp
=> Ignore held mouse button when pressing keymapper mouse buttons

vcpkg.json
=> Actualize version in vcpkg

Translations/es.po
Correct changed. Add missing translations
=> Update Spanish translation

Source/monster.cpp
=> Load the correct number of monsters

Source/msg.cpp, Source/multi.cpp, Source/sync.h
This resolves the issue mentioned in https://github.com/diasurgical/DevilutionX/pull/7986#discussion_r2083104231. For what it's worth, I also added a few includes in the files that include `sync.h`.
=> Fix includes in sync.h

.github/workflows/Windows9x_MinGW.yml, .github/workflows/Windows_MinGW_x64.yml, .github/workflows/Windows_MinGW_x86.yml, .github/workflows/Windows_XP_32bit.yml, docs/building.md
MinGW builds finally just work on 24.04.
=> MinGW Ubuntu 22.04 -> 24.04 for GitHub Actions and build instructions

test/timedemo_test.cpp
=> Call LuaShutdown() in timedemo test

android-project/build.gradle
* Upgrade Gradle addon to latest version
* Replace deprecated syntax for "Clean" task
=> Android stuff

Source/interfac.cpp
Based on https://github.com/diasurgical/DevilutionX/pull/8013#issuecomment-2906971159, there is a good chance this workaround is no longer necessary on Tiger PPC as well.
=> Remove Tiger PPC workaround for SDL_PushEvent() bg threads

3rdParty/SheenBidi/CMakeLists.txt, CMake/Dependencies.cmake, Source/CMakeLists.txt, Source/utils/utf8.cpp
Released today! :tada:  https://github.com/Tehreer/SheenBidi/releases/tag/v2.9.0
/cc @mta452
=> Update to SheenBidi v2.9.0

Source/utils/palette_kd_tree.hpp
When populating the pivots, only keep the element counts instead of the actual elements. This removes the need to compute the counts in `getMedian`.
```
Benchmark                                              Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------
BM_GenerateBlendedLookupTable_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
BM_GenerateBlendedLookupTable_mean                  -0.0224         -0.0225       2154569       2106218       2154215       2105837
BM_GenerateBlendedLookupTable_median                -0.0224         -0.0225       2154463       2106143       2154147       2105729 …
```
=> Faster k-d tree construction

Source/CMakeLists.txt
This will help with making the benchmark standalone.
=> Extract light_render into a separate library

Source/engine/render/light_render.cpp
1. Extracts duplicate expressions into functions.
2. Adds `const` throughout to make it more obvious what's being modified in the loop.
3. Add early return on out of bounds.
4. Extract `minx +` out of the `std::min({...})`.
3+4 lead to a nice perf increase
Before:
```
---------------------------------------------------------------------------
Benchmark                 Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------
BM_BuildLightmap      77181 ns        77152 ns         9092 bytes_per_second=2.7194Gi/s items_per_second=3.24034M/s
```
After:
```
---------------------------------------------------------------------------
Benchmark                 Time             CPU   Iterations UserCounters... …
```
=> light_render: Clean up and optimize RenderTriangle

.github/workflows/Windows_MSVC_x64.yml, 3rdParty/SDL2/CMakeLists.txt, android-project/app/src/main/java/org/libsdl/app/SDLActivity.java, android-project/build.gradle, android-project/gradle/wrapper/gradle-wrapper.properties, vcpkg.json
* Upgrade SDL2 to 2.32.8
* Upgrade VCPKG commit which upgrades some dependencies
* Upgrade Gradle and Gradle plugin
=> General upgrades

CMake/Mods.cmake, Source/DiabloUI/diabloui.cpp, Source/gmenu.cpp, Source/items.cpp, Source/levels/gendung.cpp, Source/loadsave.cpp, Source/lua/modules/dev/player/spells.cpp, Source/objects.cpp, Source/pack.cpp, Source/pack.h, Source/panels/spell_list.cpp, Source/player.cpp, Source/spelldat.h, Source/spells.cpp, mods/Hellfire/txtdata/spells/spelldat.tsv, test/pack_test.cpp
This leaves just effects.cpp, items.cpp and loadsave.cpp to go over for making Hellfire logic data driven. After that there are still a large set of Hellfire logic that could be turn in to Lua scripting.
=> Extract more Hellfire into data

CMake/Mods.cmake
=> Hellfire: Add effects.tsv to the MPQ

Source/control.cpp, Source/control.h, Source/engine/render/primitive_render.cpp, Source/engine/render/primitive_render.hpp, Source/engine/render/scrollrt.cpp, Source/inv.cpp, Source/items.cpp, Source/options.cpp, Source/options.h, Source/qol/stash.cpp, Source/qol/stash.h
https://github.com/user-attachments/assets/e5a3e7b8-a3c1-46dd-9eee-2a19bee5b0a1
Introduces the option to display panel information in a floating info box. This implementation currently only covers Stash/Inventory/Belt items.
=> Floating Item Info Box

Translations/es.po
Texts adapted to fit well in different menu options where the space is limited.
Some changes are made to be consistent with the rest of the translation.
=> Spanish terms adapted to fit well in menu options

Source/itemdat.cpp
@Andrettin I think we both missed this before I merged your latest PR
=> Remove unused header charconv

.github/workflows/3ds.yml
This should hopefully fix the 3DS build
=> 3DS workflow: Run `apt-get update`

tools/extract_translation_data.py
Helps the script generate valid code (or at least something that is more likely to pass clang-format checks).
=> remove single quotes in dummy identifiers

Translations/uk.po
Mostly new options and CMD flags
'Lightforge' translation will need someone else to take a look
cc: @MaderatorCreator @SourceCodeDeleted
=> Update Ukrainian TL for 1.6

Source/panels/partypanel.cpp
Add a mana bar to the Party Panel display.
Change the health bar to show yellowish/gold for mana shield and keep health level, instead of blue with mana level.
Before
With Mana Shield
After
With Mana Shield
=> Add Mana Bar to Party Panel
