- Source/multi.cpp
- Source/player.cpp
Could fix #5981
`FixPlrWalkTags` uses `player.position.old` but in some cases the old position is not updated correctly:
- when joining a game
- when desyncs happen and the remote player position is instant updated/"teleported"
- when player is not on the same level (this is relevant when another player joins the level)
This PR resolves the desyncs from above and add's a debug routine to help diagnostic this kind of problems earlier.
Steps to reproduce #5981 in master:
- In StartSpell change NewPlrAnim to: `NewPlrAnim(player, GetPlayerGraphicForSpell(player.queuedSpell.spellId), d, animationFlags, -100, player._pSFNum);` note: this change is only needed to have enough time for the cast between the two clients 😉
- Player 1 goes to dungeon
- Player 1 walks 5 tiles away from upstairs entry
- …
> When player position desyncs ensure position.old is also updated

- Source/diablo.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
- Source/msg.cpp
- Source/msg.h
- Source/player.cpp
- Source/player.h
- Source/qol/stash.cpp
- Source/spells.cpp
- Source/spells.h
- test/player_test.cpp
- test/writehero_test.cpp
Fixes #5809
Notes
- `spellFrom` is validated when loading from save game
- `CMD_TSPELL*` (Casting from inventory/Teleport cursor spells) is removed and combined with normal `CMD_SPELL*`
- `CMD_SPELL*` now also includes `spellFrom`
- This PR also fixes three vanilla issues related to casting scrolls/runes from inventory
- Spell level is correctly initialized (not remains from last spell)
- Scrolls without target (no teleport cursor) are synced/visible to other clients (for example healing)
- Fire/lightning walls scrolls direction is correctly initialized (not remains from last spell)
- This PR reintroduces `Player::spellFrom`. This variable contains the selected scroll (prior to casting) but `SpellCastInfo::spellFrom` contains the executed/queued scroll.
- Verifies direction for …
> Sync and validate spellFrom and unify normal casting and casting from inventory

- android-project/app/build.gradle
- android-project/app/src/main/AndroidManifest.xml
- android-project/build.gradle
I also took their recommendation to move the namespace declaration from the `AndroidManifest.xml` file to the `build.gradle` file. Apparently, Google deprecated the `AndroidManifest.xml` declaration. 🤷
> Update Gradle to version 7.4.2

- Source/loadsave.cpp
> Fix dimming lights in Leorics chamber

- Source/loadsave.cpp
With #3292 dynamic lights _oVar1 are reset, so that they can be recreated after changing the level.
But it also changed _oVar1 for static lights (they have _oVar1 = -1).
Because of this after going back to a already visited level (_oVar1 was saved with 0) a additional light source was added.
This also manifests in the timedemo test shown difference.
> Only reset _oVar1 for dynamic lights

- Source/loadsave.cpp
This applies the fix from https://github.com/diasurgical/devilutionX/pull/3292 to save games as well as level changes (which requires the object to be unchanged since they are not freed after the process).
> Do not manipulate lights when saving and also correct save state

- Translations/es.po
- Trapped containers/doors description fixed.
Before
After
- Fixed missaligned skill description.
Before
After
- Fixed missaligned spell description + simplification in level to avoid repetition of "spell".
Before
After
> Spanish translation - Fixes in some descriptions

- Translations/es.po
Important clarification:
The terms used until now to translate "staff/staves" was "vara/varas" and is perfectly valid.
BUT this generates inconsistencies between Diablo and Diablo II. 
Here's the explanation:
- In spanish version of Diablo II, "vara" is used to translate "wand", the necromancer's main **one-handed** weapon.
- In spanish version of Diablo II, "bastón" is used to translate "staff", the sorceress main **two-handed** weapon.
Therefore, as in Diablo **the staffs are two-handed weapons** and are used to **cast spells**, I think it is more accurate to change it for more consistency and a better context between the two games. 
And as an exception I have left unchanged the translation of the unique staff "Rod of Onan" as "Vara de Onan".
At the same time, I have retouched the Adria …
> Spanish translation - Improved terms "staff/staves"

- Translations/es.po
- Simplification to three characters of the terms "Fuerza"->"Fue", "Magia"->"Mag", "Destreza"->"Des". The reason for the change is that on objects with long descriptions there is a possibility that the String exceeds the width of the frame, giving sometimes an ugly and unintelligible result. It also resembles the original English version.
- "armadura" replaced by "defensa". Fewer characters and better approach to the Diablo II object description system. And, in my opinion, less repetitive and more elegant.
- Fixed blank spaces.
Examples:
Before (store descriptions)
After
Before (item description)
After
> Spanish translation - Little adjustments in object descriptions

- Source/controls/plrctrls.cpp
- Source/controls/plrctrls.h
- Source/options.cpp
- Source/options.h
Sort of a continuation of #5986
In this case, we want to ignore padmapper actions in favor of movement in menus when the action would have been triggered by the d-pad alone. The only exception to the rule is quick spell actions when the speedbook is open, so that d-pad buttons can still be mapped to spells.
> Defer d-pad inputs to movement handlers

- Source/engine/load_pcx.cpp
- Source/engine/render/clx_render.hpp
- Source/engine/render/dun_render.cpp
- Source/engine/render/dun_render.hpp
- Source/engine/trn.cpp
- Source/lighting.cpp
- Source/lighting.h
There is a slight inefficiency compared to the previous code since it will litterat over all shades because of the range loops, where the old for loop skipped the last shade. However this is during game loading so won't affect performance.
Regarding the fix to the Hell animated blood light table:
> Cleanup lighttable generation

- Source/diablo.cpp
- Source/items.cpp
- Source/levels/gendung.cpp
- Source/levels/gendung.h
- Source/lighting.cpp
- Source/lighting.h
- Source/loadsave.cpp
- Source/missiles.cpp
- Source/msg.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/player.h
- test/fixtures/memory_map/lightning.txt
- test/fixtures/memory_map/player.txt
Vision will never grow to more then 4, since there is only 4 players... so why have a list of 32 of them.
Also optimize the Light struct.
All the changes to data structures should save us about 3KB ram, but there should also be some savings in terms of runtime processing and less code generation.
Use `Rectangle` logic in `DoUnLight()` and `DoUnVision()`, and take a `Point` as an input.
Use early return to avoid indentation of the function body (so probably view with "ignore white-space").
Remove `DisableLighting` from release builds.
> Clean up Light structure properties

- Translations/es.po
First step to fix the Spanish affix system, now the final result is pretty decent.
Perhaps in the future a more optimal solution will be found for:
- Connector "of the" (4 variants in Spanish)
- Gender sensitive adjectives ("o/a" terminations)
Many of the prefixes and suffixes have the same translation as in Diablo II, but further fine tuning is still possible.
In the second object of this screenshot you can clearly see the improvement:
> Spanish translation - Affixes system improved

- Source/utils/file_util.cpp
Resolves an issue where multi-byte code points in file paths were being misinterpreted on Windows in functions that made use of the `std::filesystem` API. I went ahead and applied this to all paths passed into `std::filesystem` API calls regardless of whether they are used on Windows since it seems like the correct way to use the API.
> Apply u8path() to paths passed into std::filesystem API calls

- Source/levels/drlg_l3.cpp
- Source/lighting.cpp
- Source/lighting.h
- Source/objects.cpp
This should be the last of the lighting cleanups. This merges the updating of lights in to a single loop that both frees expired lights reapplies the rest.
Use Displacements by reference instead of int pointers in `RotateRadius()`.
Remove use of the `Lights` global from inside `DoLighting()` which makes the call to it less confusing.
> Clean up ProcessLightsList()

- Source/lighting.cpp
- Source/objects.cpp
Light radios for 3 objects did not match between `addObject` and `updateObject`. This caused some lights (especially in the cathedral) to fade in with the lower brightness on level loading, then pop to full brightness once the transition is over.
> Fix light brightness pop on load

- Source/lighting.cpp
Helfire makes various modifications to the lighting system. One of them is to calculate a new falloff table for lights.
Unfortunately this table isn't adhering to the radius bound which results in several visual artifacts (some can be seen here: https://github.com/diasurgical/devilutionX/issues/3601) and light smearing.
On clear destination form the normal lighting is that it allows for dim lights which is used for the lava candles.
It's possible that the overshot lighting was somewhat intentional in order to apply a glow to the floor, but since it will vary in intensity based on the players light radius this isn't very consistent. A much better way to handle it is to apply illumination to the lave tiles in the same way as for caves (but with a lower intensity). I intent to do so in a …
> Hellfire: Fix light fall off not within its radius

- Source/levels/crypt.cpp
- Source/levels/crypt.h
- Source/levels/drlg_l1.cpp
- Source/lighting.cpp
The visual artifacts caused by https://github.com/diasurgical/devilutionX/issues/3601 lead to the appearance of lava tiles glowing. In order to instead achieve this in a deliberate and stable manner the proper solution is to add a faint glow in the same way as with lava tiles in caves. A value of 3 for lighting radius is chosen to match that of the lava touchs around story books, lower values are very faint, and higher values would be odd as it would out shine the touchs.
Additionally i have adjusted the over exposure to better match the original lighting now that everything is in place.
Hellfire when first entering the level:
Hellfire after trying to smear lighting all over the leve:
PR:
> Add glow to Crypt lava tiles

- Source/levels/themes.cpp
- Source/lighting.cpp
- Source/lighting.h
- Source/objects.cpp
- Source/objects.h
- Source/quests.cpp
This fixes lights being visibly off at a distance and turning on when getting closer.
(If you resolution is high enough to see past the normal render distance)
It also provides a performance boost since these lights no longer have to be updated each frame.
This removes the need for `ApplyObjectLighting` as lighting should always be applied to objects.
Also applies a fix for Lazarus and his minions glowing inside the wall:
fixes https://github.com/diasurgical/devilutionX/issues/6028
> Fix lighting on quest maps

- Source/diablo.cpp
- Source/loadsave.cpp
[single_30.zip](https://github.com/diasurgical/devilutionX/files/6581292/single_30.zip)
That's how it looks without the fix. At this point I really don't know what's causing these weird light artifacts but it's not something I'd worry about considering we support all these vanilla/hellfire conversions and we fixed some light bugs.
Resetting all lights on loading/entering a level solves this issue once and for all.
> Fix stray lights on some saves

- Source/engine/render/scrollrt.cpp
Center of lights in Hellfire can go darker then full bright. This is already have special cases in a few places to make sure that it's rendered correctly by disabling this optimization for Hellfire levels. This applies the same exception for the local hero graphics.
Example while having -40% light radius
Before
After
> Hellfire: let light affect the player

- Source/debug.cpp
- Source/items.cpp
- Source/loadsave.cpp
- Source/msg.cpp
- Source/msg.h
- Source/objects.cpp
- Source/pack.h
- Source/player.cpp
- Source/player.h
- Source/stores.cpp
- test/player_test.cpp
- test/player_test.h
- test/writehero_test.cpp
Fixes #5980
When changing a spell level a new command `CMD_CHANGE_SPELL_LEVEL` is used.
This is a similar approach to adding stat points (`CMD_ADDSTR`).
> Sync learned/changed spells

- Source/dead.cpp
- Source/dead.h
- Source/loadsave.cpp
- Source/monster.cpp
When a monster is killed while petrified via Stone Curse, they don't leave behind a corpse. It stands to reason that an empty tile should not be illuminated. This also resolves the issue where the light would move to the monster's initial spawn position after entering and leaving the dungeon level, since there's no corpse to move it to.
The matter of whether corpses should be illuminated at all is also up for discussion.
> Remove unique monster's light when no corpse is left behind

- Source/player.cpp
Related to #6041
To not delay 1.5.0 any further lets move back to fully remove the player from the current level. We can revert this an try to solve the underlying issue after the release.
> Move back to an exhaustive clearing of players from the current level

- Source/loadsave.cpp
Besides Stone Curse, the other reason a monster might not have a corpse is that they are still alive. 😓
> Reenable lights for active monsters when loading level

- Source/movie.cpp
The bisected commit mentioned in #5931 moved the handling of these events from `FetchMessage_Real()` to `MainWndProc()`. Therefore, these were no longer being handled by the movie's event loop.
I settled on `diablo_focus_pause()`/`diablo_focus_unpause()` rather than calling `SVidMute()`/`SVidUnmute()` after some testing against Lazarus' video.
This resolves #5931
> Handle window focus events when svid movie is playing

- Source/diablo.cpp
- Source/multi.cpp
- Source/player.cpp
- Source/player.h
- Source/spells.cpp
Fixes #1492
Fixes #2838
- Deduplicate `PlacePlayer()` -> `SyncInitPlrPos()`
- Don't try to find the player spawn twice `InitPlayer()` -> `SyncInitPlrPos()`
- Don't spawn on the level trigger (instant warp back to previous level)
- Use the same spawn rules in MP and SP (do not spawn where `!PosOkPlayer()`)
- Convert `plrxoff`/`plrxoff` and `plrxoff2`/`plryoff2` to cordinates
For 1.5.0 this will also avoid spawning in a pitch black level in cases where you would have spawned inside a solid spike (light no longer cast light from inside solid objects)
> Always spawn players in a valid location

- Source/engine/displacement.hpp
- Source/lighting.cpp
- Source/lighting.h
- Source/monster.cpp
- Source/player.cpp
Finding this out was a complete coincidence. I was just cleaning up `PmChangeLightOff()` because it was using pointers instead of references, which I noticed while searching for something else :D
- No need to add `(light.position * 8)` to both values before comparing
- Conversion to negative isn't needed (this is already  handled in `DoLighting()`)
- Remove light update throttling (only updated 1/3 as often for players as other things)
- Move change check to `ChangeLightOffset()` so it applies to monsters and missiles as well
- Don't calculate the offset for monsters that do not have lights
Old:
New:
> High FPS player light update

- Source/loadsave.cpp
Fixes #5298
Fixes #2267
Previously correction of dLight and automap data was only corrected when loading a non-town level, not when loading a save state or town.
This also fully skips loading of dLight data for a bit faster loading.
> Sync loading of dLight and automap data

- Source/quests.cpp
- Source/towners.cpp
If the player discovers and enters the poison water set level before talking to Pepin the poison water quest does not appear in the quest log and his first set of dialog doesn't play. Handle this case specifically to ensure the player gets the message and can see progress.
> Play Pepin's quest intro dialog if the player skips the intro

- Source/DiabloUI/settingsmenu.cpp
- Source/utils/display.cpp
If you use `Alt+Enter` to toggle fullscreen while browsing any settings menu type besides `ShownMenuType::Settings`, the `FullscreenChanged()` handler will attempt to access an item in the empty `vecOptions` vector. The first commit fixes that.
As for the rest, it seems that `SDL_SetWindowDisplayMode()` is the appropriate function to call when resizing a window with the `SDL_WINDOW_FULLSCREEN` flag set. This required some additional logic in both `ResizeWindow()` and `SetFullscreenMode()`. Hopefully the comments help to explain a lot of the nuance better than I can here.
Fair warning: I only tested this on Windows.
This resolves #6059
> Use SDL_SetWindowDisplayMode() to resize fullscreen windows

- Source/objects.cpp
This PR blocks operating book-levers based on `sendmsg`. It also borrows logic from `DeltaSyncOpObject()` to sync booklevers when activated by another player. This allows the book animation frame and map state to sync up without actually operating the book-lever and quest text when a remote client operates the book-lever.
The change to `SyncQSTLever()` is meant to better match the logic in `OperateBookLever()`. It seems that attempting to call `ObjChangeMap()` on the Arkaine's Valor book-lever will open the first closed-off section that is supposed to be opened by placing the first Bloodstone on the pedestal. This change actually fixes an error where leaving dlvl 5 after operating the book-lever and coming back will open the first closed-off section prematurely.
This resolves #6023
> Fixes for book lever synchronization

- Source/control.cpp
calling this with a full inventory would write past the end of InvList, potentially causing a crash or data corruption.
> Fix OOB array access when spawning arena pots

- Source/playerdat.cpp
Fixes an issue where Monk's sprite would deform when performing an attack with a bow.
> Fix width of Monk bow animation

- Source/diablo.cpp
- Source/loadsave.cpp
Fixes #6075
Introduced by #6065
Thanks @FitzRoyX for reporting and finding the bad commit.
When loading a save game `LoadGame` is called and this does
- Call `LoadGameLevel`
- `LoadGameLevel` generate the level
- `LoadGameLevel` don't load the monsters from save game. Instead its generates the monsters as they are first spawned.
- Calls `SyncInitPlrPos` to ensure that the player position is valid
- `SyncInitPlrPos` see that the player is on a tile where a monster initial spawns
- Player Position is reset, but `Player::position::temp` still contains the old destination position of the walk
- `SyncInitPlr` calls `SyncInitPlrPos` again
- Saved monsters are loaded in `LoadGame` and this overrides the generated/initial monsters
The saved player position should be valid (else the saved game …
> Don't recalculate player position when loading a game

- Source/stores.cpp
- Source/towners.cpp
- Source/towners.h
Replace this with a direct reference to the chosen gossip topic when towners are init.
> Remove global gossip variables and Towner::seed

- Source/inv.cpp
- Source/inv.h
- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
- Source/msg.cpp
- Source/msg.h
In practice doesn't make a difference, it just matches the purpose better given the underlying engine seed is unsigned (and we already did this cleanup for objects :D)
> use unsigned types for item seeds

- Source/DiabloUI/diabloui.cpp
- Source/init.cpp
Fixes a crash when the game is in fullscreen mode (with upscaling=1) and minimizing the window (win+m or win+d).
- When the game is minimized on windows only `SDL_WINDOWEVENT_MINIMIZED` is send. But `SDL_WINDOWEVENT_HIDDEN` isn't. This PR handles `SDL_WINDOWEVENT_MINIMIZED` like `SDL_WINDOWEVENT_HIDDEN`: assume game is not active and don't render.
- When the game is activated again on windows only `SDL_WINDOWEVENT_EXPOSED` is send. But `SDL_WINDOWEVENT_SHOWN` isn't. This PR handles `SDL_WINDOWEVENT_EXPOSED` like `SDL_WINDOWEVENT_SHOWN`: assume game is active and render everything again.
- Prevents rendering when the game is minimized (saves some cpu cylcles)
- Also fixes that the intro is played when the game is minimized
Tested only on windows. It would be great if someone else could …
> Update gbActive correctly when minimizing the app

- Source/objects.cpp
When the Book of the Blind is first used, `ObjChangeMap()` will update the `dPiece` values for the setpiece using the values in `pMegaTiles`. For doors, this assigned the `dPiece` value the door would have if it were open. This normally gets corrected by `AddL2Objs()` which creates all new doors to replace the existing doors, forcing the new doors into a closed state and updating the `dPiece` values.
If the level has no more space for new doors, the door won't be replaced and the door state won't be forced into the closed state. Also, when loading the delta for the Book of the Blind object, the code would instead call `ObjChangeMapResync()` which doesn't call `AddL2Objs()`. In both of these cases, the `dPiece` would be forced to the open state regardless of the existing door's state.
This …
> Fix state of doors after ObjChangeMapResync

- Source/objects.cpp
This ensures that clients who did not operate the Pedestal of Blood or Book of the Blind will see the change in door state due to `ObjChangeMap()`.
> Sync multiplayer door state in ObjChangeMap

- Source/diablo.cpp
`DeltaLoadLevel()` calls `DeltaSyncOpObject()` for the pedestal, leading to `UpdatePedestalState()`, `SyncPedestal()`, and finally `LoadMapObjects()`. This last function appropriately sets `LoadingMapObjects = true` to indicate that any new light objects should be working directly with `dPreLight` instead of `dLight`. The only caveat is that `DeltaLoadLevel()` is called before `SavePreLighting()`, which is what initially copies light data from `dLight` to `dPreLight` during level generation.
This PR swaps the order of those function calls to match the order they are called on setlevels. Lighting changes for monsters and portals are handled later in `LoadGameLevel()` so changing the function call order here shouldn't cause any problems with other light sources.
Special thanks to AJenbo for …
> Load deltas after saving pre-lighting data

- Source/inv.cpp
- Source/msg.cpp
- Source/msg.h
- Source/player.cpp
Both methods were exactly the same apart from the use of temporaries for swapped message params.
> Dedupe OnRespawnItem/OnSpawnItem

- Source/engine/random.cpp
- Source/engine/random.hpp
- Source/items.cpp
- Source/levels/drlg_l1.cpp
- Source/levels/drlg_l3.cpp
- Source/levels/drlg_l4.cpp
- Source/levels/themes.cpp
- Source/objects.cpp
- test/random_test.cpp
Extracted from #6079 since this is a no impact change that hopefully makes the code easier to reason about. The helper to discard items gets rid of about half the uses of `AdvanceRndSeed()` as well.
> Cleanup random.cpp and add function for cases where random values are discarded

- test/CMakeLists.txt
- test/missiles_test.cpp
Avoids relying on a specific seed for test cases, hopefully 100 samples is enough to avoid long runs of a single direction? Normal runs seem to be 60/40 at worst. The tests fail when the rotation ends up 100% preferencing a single direction at least which is a pretty good indicator something broke.
> Use sampling for testing missiles rotate evenly

- Source/engine/render/dun_render.cpp
It looks like this was mistakenly using LightTableIndex instead of lightTableIndex. Found by @qndel
> Correct use of local instead of global lightTableIndex

- Source/inv.cpp
- Source/inv.h
- Source/items.cpp
- Source/items.h
- Source/msg.cpp
Specifically the cases which consider whether the item was placed on the CornerStone. There are many other uses of AllocateItem which skip that check, but it might be possible to get some commonality between them as well in the future...
> Deduplicate logic for placing an item in the current level

- Source/monster.cpp
Looks like, before 2493f06, `monster.position.offset` was used to determine the offset for the light. A few functions such as `M_StartStand()` and `MonsterDeath()` would set `monster.position.offset = { 0, 0 }` to prevent stale values from offsetting the position of the monster's light. After that commit, we just always calculate the walking offset based on the current animation info, regardless of the type of animation is being used. This means that calling `M_StartStand()` at the end of the walking animation followed by `SyncLightOffset()` would result in the light being placed as if the start of the stand animation was actually the start of the walking animation, causing the light to be placed at the wrong offset.
This resolves #6102
> Fix monster light offset after walk animation ends

- Source/diablo.cpp
- Source/qol/itemlabels.cpp
- Source/qol/itemlabels.h
Didn't really make sense after we allowed rebinding keys
> get rid of hardcoded ALT in variable/function name

- Source/hwcursor.cpp
- Source/hwcursor.hpp
We previously reinitialized the hardware cursor during fade in even if it was not visible (e.g. fading into the credits screen).
> Delay hardware cursor reinit until it is visible

- Source/towners.cpp
Just realised VS didn't apply the correct formatting to this function in the previous PR.
> apply clang-format to GetTowner

- Source/DiabloUI/diabloui.cpp
- Source/engine/palette.cpp
- Source/engine/palette.h
- Source/interfac.cpp
With fade 0 the cursor is never visible because everything is black.
While this is a very minor optimization, it works around
one of the instances of a bug in certain drivers as seen in https://github.com/diasurgical/devilutionX/issues/5618.
> Delay reinitializing hwcursor until fade 1

- Source/objects.cpp
Fixes #6022
Notes:
- SyncBreakObj was missing handling for crux
- Simplified logic for breaking crux. Now all missiles will sync breaking cruxes, but multiple events (from different clients) will be ignored
- Would be great if someone else could test it, because it's hard to get a small desync alone 😉
> Sync break crux correctly

- Source/items.cpp
- Source/items.h
- Source/monster.cpp
Fixes #5979
Notes
- In master spawning logic for both happens in `MonsterTalk` and this runs for both clients
- But the spawning logic uses `CMD_DROPITEM` that should only be send by one player (the "source" of the action)
- Also the used seed for the spawned items can differ between clients (and therefore also the item)
- This PR uses only `CMD_SPAWNITEM` that doesn't depend on the same logic (and same seed) is executed on both clients
- `CMD_SPAWNITEM` is only send by the player that talks to the quest monster
- The item spawning logic should be refactored at some point (we currently have `sendmsg`, `delta` and now `spawn`)
> Fixes spawned items from Zhar and Gharbard

- .circleci/config.yml
Something brok in the latest update to the Amiga build chain, so fixing the version to the last known good one.
> Fix Amiga build to known good container image

- Source/inv.cpp
- Source/items.cpp
- Source/items.h
- Source/monster.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/quests.cpp
- Source/towners.cpp
- Source/towners.h
Fixes #4192
When looking at #4192 I found multiple other syncing issue for hellfire quests (see notes)
This PR fixes most of them and #4192 but there are still likely some edge-cases missing.
- Defiler Quest is now synced when the first player enters nest level 1
- Little Girl Quest animation is now synced correctly #4192 
- Little Girl Quest quest reward (Amulet) is now synced (can be seen and taken by other players)
- Jersey's Jersey Quest animation is now synced correctly #4192
- Jersey's Jersey Quest is now correctly activated and complete on remote players quest log
- Grave Matters Quest is now synced when talking to gillian and having the cathedral map
- Na-Krul Quest is now activated for all clients (when reading the story book)
- Na-Krul Quest story books are now loaded correctly …
> Multiplayer: Sync Hellfire Quests

- Source/loadsave.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
Fixes #6125
- stone curse changes monster mode to petrified to prevent monster ai take action
- stone curse "missile" holds the old/previous monster mode
- In vanilla/master it's possible to create multiple stone curses "missiles" for a monster
- Use the monster mode stored in the stone curse "missile" to decide which graphics are used to visualize the monster
- Prevent multiple stone curse "missiles" for one monster, else `RemovePlrMissiles` could restore the wrong monster mode (petrified) for a missile
> Fix stone curse shows the wrong animation & infinite petrify

- Source/objects.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/6141
CalcPlrInv was called in all other cases where staff charges were changed
> refresh staff after using stone shrine

- Source/inv.cpp
- Source/msg.cpp
- Source/msg.h
- Source/player.cpp
- Source/player.h
Fixes https://github.com/diasurgical/devilutionX/issues/6143
cases when active spell can be changed because of a staff: 
recharging staff - player's skill
recharging staff - adria
recharging staff - shrine
reequipping staff
I made all of them change the spell if you have no other spell selected but only reequipping staff always forces the change
> dont always force staff recharge to change spell

- Source/loadsave.cpp
This PR adds some rudimentary validation to Multiplayer items when loading data from the heroitems file. The primary goal is to prevent the effects of specific Hellfire mechanics from making their way back into Diablo with a secondary goal of filtering out potentially hacked items that can technically be generated but could never actually be found due to price limits.
> Validate item prices and revert oil effects in Diablo

- Source/monster.cpp
Fixes #6160
Was introduced by #6139
Previous `TalktoMonster` didn't handle gharbad and snotspill.
Thanks @Chance4us for finding the bug 🙂
> Always check for uniqueType in TalktoMonster

- Source/monster.cpp
If an attack puts a petrified monster into hit recovery, the logic will change the direction the monster is facing. This causes the animation logic to recompute the monster's tile offset based on the new direction the monster is facing, causing the sprite to move when it shouldn't.
In the following video, the damage number shows up as zero because it was hardcoded for testing, but the attack would have put the monster into hit recovery.
https://github.com/diasurgical/devilutionX/assets/9203145/f12bdfc2-a756-42f7-a8bd-c11133c850b5
It makes more sense to assume that a petrified monster cannot change the direction it's facing so that's what this PR does.
> Don't turn monster towards player during hit recovery if monster is petrified

- Source/items.cpp
When singleplayer quests are activated in multiplayer butcher and skeleton kings drops their unique items (butcher's cleaver and undead crown).
- Only one item is dropped regardless how many player are present in the game.
- Currently the items drops every time you kill butcher/skeleton king (no limit per character).
- I checked that the items don't morph when loading the save game or dropping the item on the ground and pick them up with another character.
This change can be a bit controversial that's why it was separated from #5485
> Multiplayer: Spawn butcher's cleaver and undead crown

- Source/inv.cpp
- Source/items.cpp
- Source/items.h
- Source/objects.cpp
Fixes #6165
- In master the position of Optic Amulet and Arkaine's Valor is slightly randomized (+/- 1 Tile). This PR changes that so both items gets always spawned at the same (relative) location.
- In Multiplayer to complete Halls of Blind and Arkaine's Valor Quests also checks these exact drop positions.
- The old check (for quest item type) could be removed and always the new logic can be used (check position). But I tried to minimize the changes (and risks) so close to release of 1.5.0 version.
> Spawn Optic Amulet and Arkaine's Valor always at the same tile

- Source/debug.cpp
Includes all the info that might be necessary to recreate a level for testing, hopefully.
> [Debug] Add more data to seedinfo

- vcpkg.json
This field is now required, otherwise we get this error:
> error: this vcpkg instance requires a manifest with a specified baseline in order to interact with ports.
> Please add 'builtin-baseline' to the manifest or add a 'vcpkg-configuration.json' that redefines the default registry.
The hash here is a commit hash from https://github.com/microsoft/vcpkg/commits/master
https://learn.microsoft.com/en-us/vcpkg/users/examples/versioning.getting-started#builtin-baseline
> vcpkg.json: Add builtin-baseline

- Source/control.cpp
- Source/controls/plrctrls.cpp
- Source/diablo.cpp
- Source/inv.cpp
- Source/inv.h
Fixes #4205
An alternative to #4226
When closing the stash while an item is held we now first try to drop it, place it in the belt, or inventory.
If that fails we assume that we can stick it in the stash since it's huge.
The item put sound is played to let the player know what happened.
> Empty cursor when closing inventory

- Source/control.cpp
- Source/debug.cpp
- Source/debug.h
Moves the `seedinfo` debug command to text commands so it can be used in release builds. The extra information about mid/end seeds is still only included in debug builds. Here's how it looks in a release build.
Thought I might slip this in as an option for 1.5.0 in case we want to be able to ask players of release builds to share seed info, but it does add some new strings for translation so may be better to defer. 🤷 
I considered attempting to translate some of the output strings, but devs are ultimately the ones who need to be able to read it so probably not a great idea.
> Move seedinfo to text commands

- Source/control.cpp
Since we depend on `DeltaLoadJunk()` to sync quest state between clients in Multiplayer, `sgOptions.Gameplay.randomizeQuests` cannot be used to accurately determine which quests are enabled for the game. Furthermore, the seed by itself isn't good enough to determine Hellfire quest state for Cowquest and Theoquest, though the latter may not matter much. Anyway, given these edge cases, I think that the most straightforward way to capture quest state is by packing it up as a set of flags and displaying it as a number. It's a bit unwieldy at the moment, but it should be easy to add a debug command to consume this number.
> [Seedinfo] Display flags for quest state instead of seed

- Source/items.cpp
Because of the fallthrough...
https://github.com/diasurgical/devilutionX/blob/555dac5d22bf4cd0e1d672c526f94b3e0db62c77/Source/items.cpp#L735-L742
Doppelganger's should discard the same amount of random numbers as `IPL_TOHIT_DAMP` when computing the translated name of the item.
This resolves #6185
> Fix Item::getName() for Doppelganger's prefix

- Source/levels/trigs.cpp
Fixes #110 and #4436
This is a vanilla issue.
The entry to chamber of bone reuses the dungeon pieces for going upwards.
That's why `InitL2Triggers` checks that this is not the entry to chamber of bone before placing a upwards-trigger on it.
And this check is faulty, because it's missing a dungeon level check.
The saves in #110 and #4436 were unlucky to have the same position for entry to chamber and the upwards pieces in dungeon level 7.
This PR adds the missing dungeon level check.
> When checking chamber of bone entry also check the current dungeon level

- android-project/app/src/main/java/org/diasurgical/devilutionx/DataActivity.java
- android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java
- android-project/app/src/main/java/org/diasurgical/devilutionx/ExternalFilesManager.java
The logic here is to also report that the fonts.mpq needs to be downloaded if v2 of it has been manually added along with the game files.
From what I can tell our previous check was only activated if we where missing other data files, since we would then no go to the DataActivity activity and there for not invoke it.
The chnages will also cause it to detect and update the old file is the system default is cjk which was not the case before.
fileSize() will return 0 if the file doesn't exist
> Update existing fonts.mpq

- CMakeLists.txt
For versions without a suffix, e.g. "1.5.0" rather than "1.5.0-dev", only include the build type if it is a debug build.
> CMakeLists.txt: Adjust version string

- docs/installing.md
Indicate that moving mpq's is not required with a gog installation under windows, I didn't see this noted anywhere else.
> Add note about GoG installation on Windows

- Source/inv.cpp
I looked a bit closer at #6222, and the `RecreateItem()` function only applies to inventory synchronization and item deltas. We also need to modify `SyncDropItem()` to correct items dropped from players' inventories.
> Also disallow boosted stats for ground items

- Source/controls/controller.cpp
- Source/controls/controller_motion.cpp
- Source/engine/demomode.cpp
The advantage of having a specific list rather than storing the whole `diablo.ini` file is that non-gameplay options, such as floating numbers, can still be changed in the config and visually affect the demo.
> Demomode: Store/override gameplay options

- Packaging/nix/LinuxReleasePackaging.sh
Also adds a `devilutionx.sh` launcher which sets `LD_LIBRARY_PATH` so that `discord_game_sdk.so` can be loaded from the same directory.
Fixes #6234
/cc @michaelneverwins
> LinuxReleasePackaging.sh: Copy discord_game_sdk

- Source/items.cpp
Since we are explicitly using `CMD_SPELLXY` here, I didn't simply call `UpdateSpellTarget()` because that function doesn't may not set cursor position if the player is targeting another player or a monster. That should be irrelevant when casting from the inventory, but is relevant when casting from the belt using the "heal" button as described in the linked issue.
This resolves #6231
> Find valid target when casting scroll from inventory

- Source/CMakeLists.txt
- Source/control.cpp
- Source/debug.cpp
- Source/items.cpp
- Source/towners.cpp
- Source/utils/str_case.cpp
- Source/utils/str_case.hpp
`std::tolower` relies on the C locale, which we try to avoid.
> Remove uses of `std::tolower`

- Source/inv.cpp
- Source/inv.h
- Source/msg.cpp
Potions, scrolls, books, etc do not have durability and would therefore cause an error because the max value is smaller than the min value in the call to `clamp()`. I introduced a new function, following the pattern for validation of CTH and max damage.
> Fix net validation of durability for items without durability

- Packaging/nix/devilutionx.metainfo.xml
- Packaging/nix/org.diasurgical.DevilutionX.yml
* Base flatpak on version 1.5.0
* Bundle CJK fonts
* Bundle Diablo demo
I am bundling fonts to ensure easy onboarding for CJK users, so that they should to copy only the data files
IMO, bundling demo version is good to make sure that program was installed correctly, and it's freeware anyway
Refs #4469, IMO this will be a good MVP to submit to Flathub after merging
> Flatpak install improvements

- .github/workflows/Windows_MSVC_x64.yml
Updates the vcpkg commit ID to the one currently listed in...
https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
Permalink, for posterity.
https://github.com/actions/runner-images/blob/c26258168863fb6f3f15307411be1665edfac90c/images/win/Windows2022-Readme.md?plain=1#L37
> Update vcpkg commit ID for MSVC CI

- Source/loadsave.cpp
- Source/msg.cpp
- Source/msg.h
- Source/multi.cpp
- Source/pack.cpp
- Source/pack.h
- Source/pfile.cpp
- Source/player.cpp
- Source/player.h
- test/player_test.cpp
- test/writehero_test.cpp
This should fix items not appearing correct when inspecting a player wearing oiled items after they joined (and didn't change gear).
> Split network player sync and hero save file

- .github/workflows/macOS_x86_64.yml
fixes #6230
Since the host system has consequences for the resulting binary's comparability level we will unfortunately still need to build the macOS version manually until we figure out how to set the target version for each library and build them from src.
> Remove macOS release builds from CI

- Source/utils/sdl_bilinear_scale.cpp
The previous comment was incorrect and had a typo in the formula.
> sdl_bilinear_scale.cpp: Fix `MixColorsWithAlpha` comment

- Source/objdat.cpp
Fixes #3810
Without the Trap-Flag the game doesn't try to place a trap on the chest.
Alternative fix would be handling the placed trap correctly in `OperateInnSignChest`.
> Remove Trap-Flag from OBJ_SIGNCHEST

- CMakeSettings.json
I used `RelWithDebInfo` when doing some performance profiling and this ensures the pdb's are generated.
> MSVC: Create config for building release with debug info in visual studio

- Source/levels/drlg_l3.cpp
Fixes #3130
In masster `PoolFix()` checks if a ceiling/dirt tile is surrounded by lava ground tiles (id 25 to 41).
This doesn't work when two ceiling/dirt tiles are needed to be filled with lava.
This PR simplify the algorithm on the following basis:
A ground lava tile can never be directly connected to a ceiling tile.
There must always be a kind of transition tile between (from ground to ceiling).
That means a ceiling/dirt tile is part of a lava pool (and was missed to fill in `River()`), when it's adjacent to a ground lava tile.
In this case we change the tile to a ground lava tile.
> Fix PoolFix() to always replace dirt ceiling tiles if they are adjacent to a ground lava tile

- Source/control.cpp
This has the added (and very intentional) benefit of not causing translation validation to fail when the part inside the curly braces is being translated.
> Change syntax for optional and required arguments to match various CLI tools

- Source/multi.cpp
- Source/pack.cpp
- Source/pack.h
FYI, because `TItem` can't handle ears, they get filtered out in `PackNetItem()` and `UnPackNetItem()`.
> Add fields to PlayerNetPack for validation

- Source/items.cpp
When you read a Book, it attempts to update the Spell Level by sending a network command, and then attempts to recalculate the Magic requirement. The network command doesn't resolve the Spell Level before the function calls `updateRequiredStatsCacheForPlayer()`, resulting in the incorrect requirement being displayed until this function gets called again at a later time, observed by the call to `CheckInvCut()` in the attached issue report. To solve this, I added a line to locally change the Spell Level to `newSpellLevel`, which will be overwritten anyway when the network command resolves.
Fixes: https://github.com/diasurgical/devilutionX/issues/6271
> Fix Book requirements not updating

- Source/objects.cpp
Fixes: https://github.com/diasurgical/devilutionX/issues/6315
Applies the same fix as https://github.com/diasurgical/devilutionX/pull/6312 but for Shrines and the Chamber of Bone Tome.
> Fix Book requirements not updating from Objects

- Source/objects.cpp
Builds upon https://github.com/diasurgical/devilutionX/pull/6316 where I mistakenly forgot to refresh item requirements. The other PR updates the player's Spell Level immediately which is necessary for updating magic requirements, but then we need to iterate all inventory and stash items to update requirements.
> Fix Book requirements not updating from Objects (Part 2)

- Source/player.cpp
> player.cpp: Avoid redundant copies of `PlayerData`

- Source/engine/load_cl2.hpp
- Source/engine/render/clx_render.cpp
- Source/monster.cpp
- Source/utils/cel_to_clx.cpp
- Source/utils/cl2_to_clx.cpp
- Source/utils/cl2_to_clx.hpp
- Source/utils/clx_decode.hpp
- Source/utils/clx_encode.hpp
- Source/utils/pcx_to_clx.cpp
- Source/utils/surface_to_clx.cpp
Original Blizzard encoder is slightly less optimal than our encoder.
While size in RAM in less of a concern for the non-`UNPACKED_MPQS` build,
it is still a benefit because smaller files are faster to render.
Savings for unpacked and minified MPQs:
* diabdat.mpq: 918,311 bytes.
* hellfire.mpq: 313,882 bytes.
Example player graphics (note that only a few are loaded at any given time for single player):
* diabdat/plrgfx/warrior/: 366,564 bytes.
Example monster graphics savings:
* diabdat/monsters/skelbow: 5,391 bytes.
Based on the implementation from https://github.com/diasurgical/devilutionx-graphics-tools/pull/6
> Re-encode CL2 on load

- Source/engine/render/scrollrt.cpp
- Source/options.cpp
- Source/options.h
- Source/stores.cpp
Experience bar, enemy health bar, floating numbers, etc. are all under gameplay, these options should be as well.
> Move hp/mana display and item graphics to gameplay options

- Source/pack.cpp
Implementation for the `ValidateField()` and `ValidateFields()` macros was heavily inspired by the implementation for the `assert()` macro.
**Example log message:**
```
DEBUG: Remote player validation failed: ValidateFields(player._pStrength: 15, SDL_SwapLE32(packed.pStrength): 250, player._pStrength == SDL_SwapLE32(packed.pStrength))
```
**Example player notification:**
One additional thought I had just before submitting this PR was to move `CopyUtf8(player._pName, packed.pName, sizeof(player._pName))` to the top of the `UnPackNetPlayer()` function so it can be used in `EventFailedJoinAttempt()` in an attempt to show the name of the player that transmitted invalid data. Does anyone else think that might be a good idea?
> Log validation errors in UnPackNetPlayer()

- Source/inv.cpp
Simpler than I thought. #6169 was done after #6167 so the position-based condition for completion was only applied to multiplayer since it was originally only relevant there. But quest item position was de-randomized for both SP and MP so this change should be all we need.
This resolves #6347
> Apply position-based quest completion logic to Single Player

- Source/panels/charpanel.cpp
We fixed clipping in text rendering between 1.4 and 1.5. This surfaced a bug in the char panel label height (regression from how it was in https://github.com/diasurgical/devilutionX/pull/3623).
Before | After
-----|------
> Fix character panel label for CJK

- Packaging/nix/devilutionx.metainfo.xml
This info will be displayed in Flathub and stores like KDE Discover and Gnome Software Center
> [ci skip] Add install instructions to metainfo

- Source/loadsave.cpp
Fixes #6277
Hellfire reuses the level types from Diablo for nest and crypt.
This was confusing and it was changed in devilutionX. 👍 
To stay compatible with vanilla hellfire the level types where converted In loading and saving.
But town portals level type was missed.
This PR adds the missing conversion for town portal level types.
> Convert town portal level type to vanilla hellfire logic

- Source/pack.cpp
This is a valid case that happens when validating empty equipment/belt slots.
> Fix empty item slot validation in UnPackNetItem()

- Source/multi.cpp
If the new validation catches invalid player data, it would inevitably lead to a timeout in `CheckPlayerInfoTimeouts()` due to the empty player data in that slot failing the `IsNetPlayerValid()` check. However, we can speed this whole process up by dropping the player immediately since we know they will be dropped after the timeout interval anyway.
> Immediately drop player who sends invalid player data

- Translations/zh_CN.po
Original translators translate "brew" as “啤酒” which means "beer" in Chinese.
> fix Chinese translation

- Source/monster.cpp
This doesn't fix the save file where the value is already negative, but it does prevent the overflow from occurring in the first place.
This resolves #6016
---
Suggested changelog entry under `Bugfixes > Gameplay`:
> Overlords remain idle while the player is in sight
> Add bounds check to MonsterIdle() to prevent var2 overflow

- uwp-project/devilutionx.vcxproj
Fixes an error with the UWP build that was shared on the Discord today.
> [Xbox One] Use recursive wildcard to reference assets in subfolders

- .circleci/config.yml
These platforms don't need `smpq` since they set `BUILD_ASSETS_MPQ` off and package the assets directly in romfs.
> Don't install smpq on Switch/3DS CI runners

- Source/missiles.cpp
This resolves an issue where slvl 18 Fireball was sometimes disappearing partway across the player's screen.
Demonstration of the issue (right around 10 seconds):
https://github.com/diasurgical/devilutionX/assets/9203145/6865ebe1-3309-4655-ad38-07d83815b0e1
> It looks like, if you count 9 tiles SE of the player and then 1 tile SW from there, casting Fireball will get a path for the missile that, after traversing 5 half-tiles south of its starting position, will have traversed almost exactly 4 half-tiles east as well. It's like 0.002 pixels away from the corner between four tiles.
> 
> At the velocity of an slvl 18 Fireball, this causes a rounding error right around that point where the missile thinks it's occupying the tile SW of fourth tile SE of the player, but the missile collision …
> Don't extrapolate missile position in collision interpolation logic

- Source/missiles.cpp
In this case, at the speed of an slvl 17 Firebolt or Fireball, the missile would skip over the tile at a distance of 5 from the player. Interpolation logic should kick in and detect the collision in the skipped tile, but in this particular case it did not.
Demonstration of the bug:
https://github.com/diasurgical/devilutionX/assets/9203145/74a5e799-85a8-41f6-ba8e-34a543fc45ed
The analysis is much simpler this time. The logic to determine if the missile is on a corner between tiles checks to see if the missile has moved by an odd number of half-tiles. The logic uses mod 2 on both the x and y components of the missile's displacement to compare them. But if the missile's displacement is negative, the remainder is also negative so the comparison isn't valid when the two components of …
> Fix missiles passing through enemies on SW/NE diagonal

- Source/qol/monhealthbar.cpp
No reason to show it when there's only 1 player in game - if you kill the monster, we know you will get xp :D
Before:
After:
Diff with hidden whitespaces:
> dont show hit indicator for 1 player

- .github/workflows/Linux_x86_64_SDL1.yml
- Source/engine/point.hpp
- Source/engine/sound_position.cpp
- Source/missiles.cpp
1. Require both operands to have the same signedness to avoid surprises.
2. Only allow unary negation on signed points.
Fixes #6409
Also fixes a potential bug in the sound position calculation.
This is a forward port of some of the changes in #4881
> Point: Safer `operator-`

- Translations/es.po
Some cases of "a el" should be contracted into "al". Blood Knight's translation of "deSangre" should separate "de" and "Sangre".
I am not a native speaker of Spanish, so a native speaker should also review these changes, if necessary.
> Fix Spanish "al" cases and Blood Knight name

- 3rdParty/libzt/CMakeLists.txt
- Source/dvlnet/protocol_zt.cpp
- Source/dvlnet/protocol_zt.h
- Source/dvlnet/zerotier_native.cpp
- Source/dvlnet/zerotier_native.h
Step 3 for retrieving route information for players in your game session. The NDP protocol is used to look up the virtual MAC address of the peer based on their virtual IPv6 address. That MAC address is passed into the ZT core function we added in https://github.com/diasurgical/libzt/pull/12 to get their peer info. The peer ID can then be cross-checked against the ZT event messages we receive in our callback function to determine the status of the connection between peers.
Based on some of the testing I've done so far, the connection is typically relayed for the first few seconds after you join someone's game, after which it gets updated to a direct route. I had been hoping it would be good enough to just display a message when the player joins a game regarding whether the connection to …
> Introduce function to determine if ZT comms channel to peer is relayed

- Source/cursor.cpp
- Source/engine/point.hpp
- Source/engine/render/clx_render.cpp
- Source/engine/render/clx_render.hpp
- Source/engine/render/scrollrt.cpp
- Source/engine/render/scrollrt.h
- Source/items.h
- Source/monster.h
- Source/objects.h
- Source/player.h
- Source/towners.h
Fixes #2227
Fixes #2158
- Based on the idea of qndel's #3013 PR. Thanks @qndel 🙂 
- The cursor selection is now divided in two steps
- First try to select an game entity with pixel perfect selection
- This ensures that the player selects what he sees
- This also ensures that the player can access objects that are visible but the tile is "occupied" with something else (for example a monster, see #2158)
- Second try the old/vanilla tile based selection when pixel perfect selection find nothing
- This ensures that the player can select small objects (for example a ring)
- This ensures that the player doesn't get "less" selections in general then vanilla
- The first commit is a refactoring to make `CheckCursMove()` smaller and see the behavior better
- The second commit is a refactoring to …
> Pixel based selection

- Source/objects.cpp
Syncs the potion drops from Divine shrines using the `spawn` flag to trigger `CMD_SPAWNITEM`, instead of using the `delta` flag. `CMD_SPAWNITEM` takes the necessary steps to ensure the item gets dropped on the ground and added to deltas on remote clients.
The `delta` flag only ensures that the item is added to the deltas on the local client. This flag should be used exclusively for items that are placed on the ground during dungeon generation, such as treasure rooms and monster pits.
This resolves #6446
_Note: One might be tempted to use the `delta` flag and instead rely on `SyncOpObject()` to invoke `CreateTypeItem()` on every client, using the object seed to keep things in sync. But this would only work if all players are on the same dungeon level. Players on other dungeon levels would …
> Sync potion drops from Divine shrine

- .github/workflows/xbox_one.yml
- Packaging/xbox-one/build.bat
Also updates SDL2 version to the latest SDL2 branch commit.
We may want this for 1.5.1 as well.
> Xbox One: Fix SDL2 checkout command

- .github/workflows/Windows_MSVC_x64.yml
- vcpkg.json
This is the version that is currently installed on GitHub Actions.
We may want this for 1.5.1 as well.
> vcpkg.json: Update builtin-baseline

- Source/control.cpp
- Source/debug.cpp
- Source/diablo.cpp
- Source/pfile.cpp
- Source/utils/parse_int.hpp
Adds a `ParseInt` function which uses `std::from_chars`.
From `std::from_chars` documentation:
> Unlike other parsing functions in C++ and C libraries,
> std::from_chars is locale-independent, non-allocating, and non-throwing.
> Use `std::from_chars` instead of `std::stoi`

- Source/control.cpp
- Source/controls/plrctrls.cpp
- Source/diablo.cpp
- Source/panels/spell_list.cpp
- Source/utils/string_or_view.hpp
We also add a direct string move-assignment (`operator=(std::string &&)`), which results in better codegen.
As a consequence, we have to replace `= {}` assignments with `= StringOrView {}` because `= {}` is now ambiguous.
> Use `std::variant` in `StringOrView`

- Source/utils/push_aulib_decoder.cpp
- Source/utils/push_aulib_decoder.h
Previously, we converted 8-bit audio to 16-bit, and then to float. Eliminates the 8->16 conversion step.
Also optimizes the 16-bit conversion a bit.
This also fixes the following compiler warning on 32-bit systems:
```
In member function ‘PushSamples’,
inlined from ‘SVidPlayContinue’ at Source/storm/storm_svid.cpp:343:33,
inlined from ‘SVidPlayContinue’ at Source/storm/storm_svid.cpp:326:6,
inlined from ‘_ZN10devilution10play_movieEPKcb.part.0’ at Source/movie.cpp:82:25:
Source/utils/push_aulib_decoder.cpp:29:46: warning: argument 1 value ‘4294967295’ exceeds maximum object size 2147483647 [-Walloc-size-larger-than=]
29 |         item.data.reset(new std::int16_t[size]);
|                                              ^
```
> PushAulibDecoder: Support 8-bit samples directly

- Source/control.cpp
- Source/inv.h
- Source/inv_iterators.hpp
- Source/panels/spell_list.cpp
Previously, inventory iterators could only be used with non-const objects, leading to suboptimal const correctness.
Adds support for `const` objects to inventory iterators via C++17 CTAD.
> Support `const` inventory iterators

- Source/engine/actor_position.cpp
- Source/engine/actor_position.hpp
- Source/engine/animationinfo.cpp
- Source/player.cpp
This fixes some bugs in the logic to calculate the walking offset that often caused the light's position to flicker when starting a new walk animation.
* Remove `pendingProcessAnimation` parameter from `CalculateWalkingOffset()` functions because it is not used by any caller.
* Use `getAnimationProgress()` in `CalculateWalkingOffset()` instead of `currentFrame` as it provides a more accurate sense of progress based on skipped frames and ticks per frame.
* Don't allow negative values for `ticksSinceSequenceStarted` in `getAnimationProgress()` since it is now used in `CalculateWalkingOffset()` which means it could be invoked before the call to `processAnimation()`.
* Move `_pdir` assignment up in `HandleWalkMode()` so that the direction of the new walking animation is passed into …
> Fix issues with light offset calculation

- 3rdParty/tl/expected.hpp
- Source/control.cpp
- Source/debug.cpp
- Source/diablo.cpp
- Source/pfile.cpp
- Source/utils/parse_int.hpp
`std::expected` has been standardized for C++23.
This will also be used in #6399 
/cc @ephphatha
> Add `tl::expected` and use it in `ParseInt`

- Source/engine/points_in_rectangle_range.hpp
- Source/objects.cpp
- Source/qol/stash.cpp
These are no longer needed in C++17 thanks to CTAD.
> Remove `PointsInRectangle` factory functions

- 3rdParty/libmpq/CMakeLists.txt
- Source/engine/assets.cpp
- Source/engine/assets.hpp
- Source/mpq/mpq_reader.cpp
- Source/mpq/mpq_reader.hpp
- Source/mpq/mpq_sdl_rwops.cpp
- Source/mpq/mpq_sdl_rwops.hpp
Changes asset lookup functions to use `std::string_view` instead of `const char *`.
This required new APIs in libmpq, added in https://github.com/diasurgical/libmpq/pull/13.
> `string_view`-based asset lookup

- Packaging/nix/debian-cross-aarch64-prep.sh
These `file` paths are used to define mirrors on the GitHub Runner Image for Ubuntu 20.04 and 22.04.
This should fix the flaky aarch64 build.
Please also cherry-pick this into `development`.
> debian-cross-aarch64-prep.sh: Support `file` paths

- test/pack_test.cpp
Currently builds on the development branch fails, this should fix it
Removing UnPackNetPlayer_invalid_pLevel should be ok as ValidatePlayer() makes the case pretty hard to hit, and _pLevel being private makes it hard to setup the test.
> Adjust tests to work with data driven levels

- Source/utils/endian_stream.hpp
Usually we call fread in a loop until reaching EOF. Reaching EOF is not an error, so we should not log it as such.
The error message was previously seen when loading demo files.
> LoggedFread: Do not log EOF as an error

- Source/qol/stash.cpp
As Stephen pointed out in #6519 the stash code copied the half-cell shift and part of the bounds detection logic from the original inventory code, meaning it was affected by the same quirks. This updates the paste logic to handle pasting items on the edge of the grid better (so if you can pick up an item you can always put it back without having to move the cursor).
> Find the closest point when pasting items on the edge of the stash

- Source/inv.cpp
- Source/inv.h
In vanilla Diablo/Hellfire the hit detection for pasting an item into an inventory cell has a couple of flaws.
* Pasting an item taller than one cell into the first row works as expected as the code adjusts the target slot to prevent underflow, but when trying to paste in the last row it just returns early instead of attempting to prevent overflow.
* Pasting an item with an even dimension (2 cells wide and/or 2 cells high) also shifted the hot pixel before testing if it overlaps an inventory cell which made for odd behaviour when pasting these items in the first or last column/row of the inventory.
This PR changes the hit detection logic to determine if the hot pixel is in the inventory first, then adjust the target slot to the top left cell of the item while also clamping to the …
> Clean up hit detection for inventory slots when pasting large items

- Source/pack.cpp
Adds validation to make sure that the item in a specific inventory location is meant to be in that location.
> Validate Item Locations

- .github/workflows/Windows_MSVC_x64.yml
- vcpkg.json
The main purpose of this is for MSVC builds to use SDL2 v2.28.2 (from v2.26.5) and fmt v10.1.0 (from v10.0.0) which the project uses already in source-download builds
vcpkg didn't update from 2.26.5 to 2.28 until yesterday (2023-08-28), even though I filed a port update request in July and two bugfix releases happened before the upgrade: https://github.com/microsoft/vcpkg/issues/32186
IMO, this is good to merge into `master` for 1.5.1, but I can retarget to `development` if needed
> Upgrade vcpkg baseline commit

- Source/CMakeLists.txt
- Source/engine/demomode.cpp
- Source/engine/demomode.h
- Source/error.cpp
- Source/minitext.cpp
- Source/utils/timer.cpp
- Source/utils/timer.hpp
Solves one of the issues listed in #2745.
> Dialogs playback is realtime, if the player did not interrupt it (or playback is slower then playtime) the dialog will stay open for a different duration
When recording a demo or playing it back, the game simulates `SDL_GetTicks()` based on the number of game ticks that have elapsed since the start of the demo, assuming 20 fps. When recording or playing back at faster speeds, this means that shrine messages will disappear faster and dialog will move faster than the corresponding audio.
> Deterministic timer simulation for shrine messages in demo mode

- Packaging/nix/devilutionx.metainfo.xml
- docs/CHANGELOG.md
Release date and changelog URL will be added on 1.5.1 release
Please review the notes for items missing or unneeded
> Add draft for 1.5.1 release notes in metainfo

- Source/error.cpp
- Source/error.h
- Source/gamemenu.cpp
Allows each DiabloMsg to have a set duration. Modified the `Game Saved` duration to 1 second (from default 3.5 seconds) as proof of concept and to quell a complaint. I'd like to make another PR to adjust various other messages that either last too long or not long enough (i.e. Debug Help menu is too short, various debug command messages last too long)
https://github.com/diasurgical/devilutionX/pull/6506
> Add duration parameter to InitDiabloMsg()

- Source/controls/plrctrls.cpp
Part of the fix for #6532, this addresses the cursor position when opening the inventory, movement within the inventory (both when empty handed and when holding an item), applying oils to items, using skills on items, picking up/putting down/swapping items. e: and makes it more consistent when moving a wide item like a shield or large weapon from the left hand to the inventory
I did notice swap auto-equipping items of the same size doesn't actually put them in the same place but I think this is deliberate and doesn't appear to be related to the cursor hotpoint changes.
The cursor offset when navigating the stash and holding an item still needs to be fixed, that uses different behaviour when empty handed that makes it a bit too much for me to do tonight. Hoping someone else can fix that …
> Fix handling of gamepad cursor movement in inventory following item cursor change

- .github/workflows/Linux_aarch64.yml
- .github/workflows/Linux_x86.yml
- .github/workflows/Linux_x86_64.yml
- .github/workflows/Linux_x86_64_test.yml
- CMake/platforms/aarch64-linux-gnu-clang-static-libc++.toolchain.cmake
- CMake/platforms/debian-cross-pkg-config.sh
- CMakeLists.txt
- Packaging/nix/debian-cross-aarch64-prep.sh
- Packaging/nix/debian-cross-i386-prep.sh
- Packaging/nix/debian-host-prep.sh
- Source/towners.cpp
- Source/towners.h
For x86 and x86_64 builds, we use GCC 13 from ppa:ubuntu-toolchain-r/test (glibc requirement remains the same).
For aarch64, we use Ubuntu 22.04 (which also comes with GCC 13) because aarch64 cross compilers are not available in ppa:ubuntu-toolchain-r/test.
Aarch64 Linux is the only platform that requires a newer glibc with this PR.
We expect that Raspberry Pi OS based on Debian 12 Bookworm will be released within a month or so, well before the 1.6.0 release. 
Note that the PS Vita SDK still uses GCC 10.3.0 which doesn't have full C++20 support (but it's still pretty decent https://gcc.gnu.org/projects/cxx-status.html).
> Switch to C++20

- Packaging/OpenDingux/build.sh
- Packaging/OpenDingux/devilutionx-from-disk.sh
- Packaging/OpenDingux/devilutionx-umount-opk-and-run.sh
- Packaging/OpenDingux/profile-generate.sh
Turns out the squashfs mount has some non-trivial RAM overhead.
Copy the game to local storage and run from there to avoid the overhead. This completely eliminates long 0 FPS periods when running the demo for PGO.
It may be possible to reduce the overhead by setting CONFIG_SQUASHFS_FRAGMENT_CACHE_SIZE kernel setting to 1.
> RG99: Run from disk rather than from /opk squashfs

- Source/data/file.hpp
1. Default comparison allows us to use the default implementation of `operator==`: https://en.cppreference.com/w/cpp/language/default_comparisons
2. Parentheses initialization for aggregate types allows us to remove all the constructors
> Simplify `ColumnDefinition` using C++20 features

- Source/pack.cpp
- test/pack_test.cpp
In vanilla, `LoadGameLevel()` calls `InitItems()`. This calls `GetItemAttrs()` on `item[0]`, passing in `IDI_GOLD` and ilvl 1. You'd think that would set the creation flags to 1, but it seems this ilvl only gets used for books and oils. It doesn't modify creation flags at all. After that, `item[0]` gets copied into a `golditem` global variable. So whenever Blizzard wanted to place gold from a vendor into the player's inventory, they can just set the seed of `golditem` and then copy it into the player's inventory.
So the case in #6559 was probably gold from a vendor that had the creation flags of some pregen item that was generated in `item[0]` on whatever dlvl they were previously on before returning to town to shop. DevX doesn't have this problem because we don't use a `golditem` global …
> Don't validate creation flags on gold

- Source/diablo.cpp
> Load stash data based on gbIsHellfire, not gbIsHellfireSaveGame

- Source/CMakeLists.txt
These files are responsible for most of the runtime in Debug mode. Apply some optimizations to them even in Debug mode to get reasonable performance.
Timedemo on my machine goes from 40s down to 25s.
> Compile some files with -O2 even in Debug mode

- Source/engine.h
- Source/engine/direction.hpp
- Source/engine/displacement.hpp
- Source/engine/point.hpp
- Source/engine/points_in_rectangle_range.hpp
- Source/engine/rectangle.hpp
- Source/engine/size.hpp
- Source/levels/gendung.h
- Source/lighting.cpp
- Source/monster.cpp
This has little or no effect on the optimized build but significantly improves performance of the headless debug build
`timedemo_test` on my machine goes from 3s to 2s.
> Force-inline methods to improve debug build perf

- Source/CMakeLists.txt
Fixes: '/RTC1' and '/O2' command-line options are incompatible
Follow-up to #6580
> Remove Debug /O2 for MSVC

- Source/CMakeLists.txt
- test/data_file_test.cpp
```
data_file_test.cpp:37:20: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wdangling-else]
37 |                 if (!result.endOfFile())
|                    ^
```
```
Source/engine/render/dun_render.cpp:1126:6: note: variable tracking size limit exceeded with ‘-fvar-tracking-assignments’, retrying without
1126 | void RenderTile(const Surface &out, Point position,
```
> Fix some compilation warnings

- Source/engine.cpp
- Source/engine/palette.cpp
- Source/engine/palette.h
- Source/engine/render/blit_impl.hpp
- Source/utils/sdl_bilinear_scale.cpp
- Source/utils/sdl_bilinear_scale.hpp
In a debug build, `std::array` accesses are function calls. This mostly does not matter but this particular array is read from a lot on every frame.
Timedemo on my machine:
* Before: 45.39 seconds	141.3 FPS
* After:  40.20 seconds	159.5 FPS
> Use a C array for transparency LUT for debug perf

- 3rdParty/libfmt/CMakeLists.txt
- Source/dvlnet/tcp_client.h
- Source/dvlnet/tcp_server.h
- Source/platform/ctr/sockets.cpp
Hopefully we'll be able to get rid of the custom nxdk fork soon.
Disabling `FMT_OS` is the first step towards that. I've also asked the fmt author about handling Windows-like platforms without Unicode support in https://github.com/fmtlib/fmt/issues/3631.
The 3ds build was initially failing due to the 3ds SDK defining a macro (`PACKED`) with the same name as an fmt template argument. Now fixed (worked around). https://github.com/fmtlib/fmt/issues/3632.
> Bump libfmt

- Source/automap.cpp
- test/automap_test.cpp
Changes automap scaling to adjust by 25, rather than 5. This corrects strange behavior with lines drawn on the automap when the scale level is not a multiple of 25.
Also changes the max zoom out from 50 to 25. The previous change is necessary for this, as scale levels 30, 35, 40, and 45 are quite ugly. This change helps players to see more of the automap when playing at lower resolutions.
> Change Automap Scale and Max Zoom Out

- Source/dvlnet/abstract_net.cpp
- Source/dvlnet/abstract_net.h
- Source/dvlnet/base.h
- Source/dvlnet/cdwrap.cpp
- Source/dvlnet/cdwrap.h
- Source/dvlnet/loopback.cpp
- Source/dvlnet/loopback.h
- Source/dvlnet/tcp_client.cpp
- Source/dvlnet/tcp_client.h
1. There is no reason for cdwrap to be templated, it can simply store the factory function reference instead.
2. Marks overriden virtual functions as `override` instead of `virtual`.
> net: Remove template parameter for cdwrap

- Source/automap.cpp
- Source/automap.h
- Source/monster.cpp
- test/automap_test.cpp
This is a hefty one. The automap has some issues:
* Automap scales that aren't multiples of 25 can produce misaligned pixels and lines
* Automap functions draw lines beyond the boundaries of their respective megatile, making it problematic to correctly align Catacombs doors
* Caves automap incorrectly draws A LOT
* `AmLine()` split into `AmOffset()` and `AmLine()`
- `AmLine()` was used for both offsetting `Point` as well as providing the length for drawn lines.
* Enumerators for `AmOffset()` arguments: `AmWidthOffset` and `AmHeightOffset`
- This way of using enumerators allows us to intuitively adjust offsets without needing to reference `TILE_WIDTH` and `TILE_HEIGHT`, and also softcodes these values. The enumerators are set to values that are friendly with the original `assert` found in …
> Refactor Automap

- Source/dvlnet/base.cpp
- Source/dvlnet/base.h
- Source/dvlnet/base_protocol.h
- Source/dvlnet/packet.cpp
- Source/dvlnet/packet.h
- Source/dvlnet/tcp_client.cpp
- Source/dvlnet/tcp_server.cpp
- Source/dvlnet/tcp_server.h
- Source/init.cpp
The network code still has ways to go to get rid of exceptions, this is but a small first step.
Refs #6602
> net: Replace `packet_exception` with `tl::expected`

- Source/options.cpp
If a resampler was not enabled, we'd get an unused variable warning:
warning: unused variable 'ResamplerSpeex' [-Wunused-const-variable]
constexpr char ResamplerSpeex[] = "Speex";
> Fix unused variable warnings for resampler name

- Source/data/file.cpp
- Source/data/file.hpp
- Source/data/iterators.hpp
- Source/playerdat.cpp
- Source/utils/parse_int.hpp
- test/CMakeLists.txt
- test/data_file_test.cpp
- test/fixtures/txtdata/sample.tsv
- test/parse_int_test.cpp
Intended for use loading fixed point decimals from strings (e.g. player attributes from text files). Found a few error conditions that I wasn't handling properly so made the code a bit more robust at the expense of added lines :( e: and of course I found another failure case after opening the PR...
Split from #6530
> Add ParseFixed6 equivalent of ParseInt

- Source/CMakeLists.txt
- Source/utils/parse_int.cpp
- Source/utils/parse_int.hpp
- test/data_file_test.cpp
As suggested in https://github.com/diasurgical/devilutionX/pull/6618#discussion_r1328068071
Also fixed a couple of typos.
> move definition of non-templated function to cpp file

- Source/items.cpp
This particular case where a staff that allows spells rolls with a regular suffix gets its `minlvl` reset to `maxlvl / 2` because `GetStaffSpell()` doesn't receive `minlvl` as a parameter.
https://github.com/diasurgical/devilutionX/blob/c4d25187415c81b12750828e000617867f8a430b/Source/items.cpp#L1264-L1267
> Fix minlvl when generating translated names for staves

- Translations/fr.po
"shank" is also English slang for an improvised knife, which is probably the meaning here. The word "shank" can also mean a kind of rod, which is more of what "tringle" is, but I don't think that's the correct context.
I suggest instead "surin".
> French translation of "Ice Shank": "Tringle de Glace" -> "Surin de Glace"

- Source/dvlnet/tcp_client.cpp
- Source/dvlnet/tcp_server.cpp
- Source/dvlnet/tcp_server.h
Just a few simple changes without going so far as fixing the message queue or turning on `ASIO_NO_EXCEPTIONS`. The commits should be pretty self-explanatory. A couple additional notes...
* By eliminating `server_exception`, we no longer use `dvlnet_exception` anywhere on the TCP side so I removed those catch clauses as well.
* Failing to set TCP no-delay shouldn't be a catastrophic error so I just log those and continue.
> Reduce use of exceptions in TCP

- Source/automap.cpp
- Source/debug.cpp
- Source/items.cpp
This change will make more sense with https://github.com/diasurgical/devilutionX/pull/6624
This adds a label to the output text for debug commands. (Example: `[changemana] Enter a value not equal to 0 to change mana!`)
Also adds text to the automap underneath the rest of the text to show you when any of the following booleans are set to true:
`DebugGodMode`
`DisableLighting`
`DebugVision`
`DebugPath`
`DebugGrid`
`DebugScrollViewEnabled`
Revises all the output text for debug commands so they make more sense and are less fun. If you view the following:
This doesn't really communicate anything useful to the programmer.
> Debug: Revise Text

- Source/dvlnet/packet.cpp
- Source/dvlnet/packet.h
- Source/dvlnet/tcp_server.h
I started to have my doubts about using inheritance with `tl::expected` so I ran a little test. The following prints out `DEBUG: Incorrect package size`.
```c++
tl::expected<void, PacketError> test = tl::make_unexpected(PacketTypeError(240));
LogDebug("{}", test.error().what());
```
And this prints out `DEBUG: Unknown packet type 240`.
```c++
tl::expected<void, PacketTypeError> test = tl::make_unexpected(PacketTypeError(240));
LogDebug("{}", test.error().what());
```
This PR fixes it by replacing inheritance with factory functions.
> Don't use inheritance with tl::expected

- Source/engine/render/dun_render.cpp
- Source/engine/render/dun_render.hpp
Adds a function that can be used to implement the baked light cache
Refs #6631
> dun_render: Add `DunTileColorMap` for baked light

- Source/utils/paths.cpp
Avoids search paths duplication (`"./"` vs `""`)
> Use an empty path for ini-based path detection

- Source/utils/stdcompat/shared_ptr_array.hpp
- android-project/app/build.gradle
This version of NDK finally comes with updated libc++.
The last update to libc++ in NDK was in early 2020.
This update brings lots of improvements and bugfixes from upstream
libc++.
NDK 26 only support SDK 21+, so we bump `minSdkVersion` as well.
GitHub Actions runner images update to this NDK version is tracked in https://github.com/actions/runner-images/issues/8327
> Update NDK to v26

- Source/automap.cpp
- Source/automap.h
- Source/control.cpp
- Source/control.h
- Source/controls/game_controls.cpp
- Source/diablo.cpp
Makes cycling the automap type separate from toggling it on/off.
The TAB key can still be used for quick on/off as usual, while the new Cycle key ("m" by default) can be used to switch between available display types.
`Get/NextDebugMonster` debug keybind changed to "v" to avoid a conflict.
The actual implementation for these automap features is in #6607 and #6612
> Add automap type cycling controls

- Source/init.cpp
- Source/utils/file_util.cpp
- Source/utils/logged_fstream.hpp
Fixes #6626
Now shows the error dialog correctly and we get a sensible log as well:
> `LoggedFstream`: Fix `OpenFile` error check

- 3rdParty/asio/CMakeLists.txt
- 3rdParty/asio/asio_handle_exception.cpp
- 3rdParty/asio/asio_handle_exception.hpp
- Source/dvlnet/base.h
- Source/dvlnet/base_protocol.h
- Source/dvlnet/packet.h
- Source/dvlnet/tcp_client.cpp
- Source/dvlnet/tcp_client.h
- Source/dvlnet/tcp_server.cpp
- Source/dvlnet/tcp_server.h
- uwp-project/devilutionx.vcxproj
Overall, this was more complicated than I anticipated.
It seems that although ASIO enables us to handle exceptions using the `throw_exception()` function, it also frequently relies on the fact that a thrown exception will unwind the stack without the need to explicitly return from the caller. This means that it's frequently unsafe to log-and-continue, like in the case of a failed memory allocation where ASIO would proceed to attempt to access a bad memory address. Thanks to the changes in #6621, I believe ASIO should only attempt to throw exceptions for errors we can treat as fatal. Therefore, this implementation of `throw_exception()` uses appfat.
The rest of the PR was mostly just attempting to handle errors in `tcp_client::poll()` without relying on exceptions. I was thinking the TCP …
> Build ASIO without exceptions

- Source/pack.cpp
This fixes an issue where unequipping items from your character will cause validation to fail when someone joins your game.
I think `UnPackItem()` was working correctly because the underlying type for `_item_indexes` is signed. The -1 would be sign-extended when implicitly cast to an `int`, and `-1` wouldn't be adjusted by `RemapItemIdxFromSpawn()` or `RemapItemIdxFromDiablo()`. Regardless, I don't think we should be attempting to remap sentinel values as though they are valid `_item_indexes` values.
> Fix edge cases for packing empty items

- Source/automap.cpp
Adds DrawVision to the automap so it's easier to see vision that might be obscured by walls or offscreen
> Debug: Add DrawVision to automap

- Source/automap.cpp
- Source/automap.h
- Source/control.cpp
- Source/engine.cpp
- Source/engine.h
- Source/engine/render/automap_render.cpp
- Source/engine/render/automap_render.hpp
Transparent automap.
Usage: Press Tab or Map button to open automap (opaque), press again to make automap transparent, press again to close automap
The reason that the automap looks so patchy with transparency is because the line drawing functions are horrible about not drawing over each other, causing doubling of drawn pixels, which makes them less transparent. I think it looks kinda cool though, as the lines look more like the golden borders in the game.
> Automap: Transparency

- 3rdParty/libzt/CMakeLists.txt
- Source/dvlnet/base.cpp
- Source/dvlnet/base.h
- Source/dvlnet/base_protocol.h
- Source/dvlnet/frame_queue.cpp
- Source/dvlnet/frame_queue.h
- Source/dvlnet/protocol_zt.cpp
- Source/dvlnet/protocol_zt.h
- Source/dvlnet/tcp_client.cpp
- Source/dvlnet/tcp_client.h
- Source/dvlnet/tcp_server.cpp
- Source/dvlnet/tcp_server.h
Another step on the journey to solving #6602. This eliminates the last of the exceptions used on the TCP side, and eliminates one call to `ABORT()`, albeit one that I don't think we've ever actually encountered. ZT still has `protocol_exception`, but that appears to be all that's left after this.
> Remove frame queue exceptions from the network layer

- Source/automap.cpp
- Source/automap.h
- Source/control.cpp
- Source/engine/render/automap_render.cpp
Built on: https://github.com/diasurgical/devilutionX/pull/6607
Adds a minimap to the top right part of the screen. Accessed by toggling automap twice. Minimap scaling is completely separate from automap scaling, so the game will remember which scale you have both at, even when the respective one is disabled. Minimap scale is not saved with the save file.
The size of the minimap is proportional to the display resolution, so it will appear the relative same size regardless of what resolution you're using. The default starting zoom level is also based on your resolution.
https://github.com/diasurgical/devilutionX/assets/68359262/012bfe72-610f-40f4-a46e-93ed59477609
> Automap: Minimap

- Source/multi.cpp
I checked into a stack trace AJenbo captured from ASAN when running wkdmod. It seems that any time the `CopyBufferedPackets()` function copies fewer bytes than it has left over after the copy, you'll get an overlap in the call to `memcpy()`.
Here's the stack trace.
```
==835379==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x55b1e161ede4,0x55b1e161f43f) and [0x55b1e161f00c, 0x55b1e161f667) overlap
#0 0x7f6bcb470d15 in __interceptor_memcpy ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:899
#1 0x55b1de334558 in CopyBufferedPackets /home/ajenbo/code/diablo/wkdmod/Source/multi.cpp:124
#2 0x55b1de33c4c3 in devilution::NetSendHiPri(int, std::byte const*, unsigned long) /home/ajenbo/code/diablo/wkdmod/Source/multi.cpp:519
#3 0x55b1de33d55f in …
```
> Use memmove when shifting data in high/low priority buffers

- Source/stores.cpp
Indestructible items are eligible for repair if the current durability is less than the max durability, which can occur in cases where the player uses methods to make a non-indestructible item into an indestructible item. This fixes that.
> Bugfix: Indestructible Items at Smith Repair

- Source/automap.cpp
Automap grates weren't using `SetMapPixel()`, so they never got rendered as transparent with transparent automap, and were getting rendered outside the bounds of the minimap in minimap mode.
> Bugfix: Automap Grates not rendering correctly

- Source/debug.cpp
Currently, in givelvl command user can type lvl above 50, which is a level cap. This patch clips it to 50, so we can prevent an accidential freeze of the game caused by NetSendCmd loop if user types a really big number.
> Clip parsed level from debug console to 50

- Source/items.h
Currently some of the "isItem" functions add an unnecessary check of isEmpty which is redundant, because a few lines lower they also check for item type inside the same object.
This patch removes those unnecessary checks.
> Refactor: simplify logic in items.h

- Source/options.cpp
If a key is not bound, do not log "no name found for key".
> Keymapper: Reduce log spam in verbose mode

- Source/diablo.cpp
- Source/diablo.h
- Source/options.cpp
Resolves: https://github.com/diasurgical/devilutionX/issues/6542
Currently we only have 4 quick message slots - this patch adds more of them, resizing the total amount to 10.
Issue #6542 also mentioned number pad setup, so this PR also adds support to bind hotkeys to numbers on keypad (0-9).
> HotkeyMessages: Add more quick message slots

- Source/debug.cpp
- Source/utils/lua.cpp
- Source/utils/lua.hpp
- Source/utils/sdl2_to_1_2_backports.h
1. Adds a `lua` debug command:
Example:
```
lua return 1 + 2
```
Ideally we should have a better UI for this in the future.
2. Adds DevilutionX log functions.
> Add a lua debug command

- Source/diablo.cpp
- Source/options.cpp
Resolves: https://github.com/diasurgical/devilutionX/issues/6229
Closes: https://github.com/diasurgical/devilutionX/pull/6407
This PR is a continuation of PR#6407, spoke with @StephenCWills so I could continue it, but I had to create a new PR since I'm not a maintainer of DevilutionX. Added appropriate co-authors, did cleanup of the previous PR and applied comments from last review. Rebased it and adjusted new mappings that we already had with those from the previous PR.
This patch adds more keybindings, so we can map multiple new keys, and it also adds a possibility to bind an alternate key to pause game (currently mapped to P and Pause key by default).
> Hotkeys: Support more keybindings

- Source/plrmsg.cpp
I wasn't familiar with string_view but using message.text.data() there was confusing, {} better shows it's actually empty (thx @ephphatha)
> simplify message.from initialization

- Source/DiabloUI/diabloui.cpp
Per https://wiki.libsdl.org/SDL2/SDL_GetClipboardText
Caller must call [SDL_free](https://wiki.libsdl.org/SDL2/SDL_free)() on the returned pointer when done with it (even if there was an error).
Also added checking if clipboard isn't empty
> fix mem leak in pasting name

- Source/plrmsg.cpp
Fixes an issue where sender's name in chat history would print garbage from memory instead
Shortest way to reproduce:
Create a character named "A"
Write on chat:
A
AAAAA
> fix sender's name getting trashed in chat history

- Source/debug.cpp
- Source/items.h
Currently in GiveGold and TakeGold commands in debug.cpp we only have a possibility to flood our inventory with gold (or remove all of it), this patch adds a possibility to either specify amount of gold to be added or just write "max" which will preserve native functionality of those commands, by clearing all gold or giving max gold possible (depending on the amount of free slots in inventory).
> Debug: Add possibility to specify amount of gold in give/take cmds

- Source/DiabloUI/multi/selgame.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/6319
On going back from speed selection and while not meeting difficulty level requirements, selgame_selectedGame was being set to 0 which indicated a private game, that's why it asked for a password
Also added resetting selgame_Label or it'd keep the last value there on IP screen:
> fix menu bugs

- Source/CMakeLists.txt
- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/diabloui.h
- Source/DiabloUI/text_input.cpp
- Source/DiabloUI/text_input.hpp
- Source/DiabloUI/ui_flags.hpp
- Source/DiabloUI/ui_item.h
- Source/control.cpp
- Source/control.h
- Source/controls/menu_controls.cpp
- Source/diablo.cpp
- Source/engine/render/text_render.cpp
- Source/engine/render/text_render.hpp
- Source/utils/utf8.cpp
- Source/utils/utf8.hpp
Supports move left/right/home/end, backspace, delete, and Ctrl+V.
https://github.com/diasurgical/devilutionX/assets/216339/312542fb-d2e9-4251-85ae-8921aad0b0cd
> Add cursor support to DiabloUI and chat 

- Source/DiabloUI/button.cpp
- Source/DiabloUI/credits.cpp
- Source/DiabloUI/diabloui.cpp
- Source/automap.cpp
- Source/control.cpp
- Source/diablo_msg.cpp
- Source/engine/render/dun_render.cpp
- Source/engine/render/scrollrt.cpp
- Source/engine/render/text_render.cpp
- Source/engine/render/text_render.hpp
- Source/gmenu.cpp
- Source/help.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/minitext.cpp
- Source/panels/charpanel.cpp
- Source/panels/mainpanel.cpp
- Source/panels/spell_book.cpp
- Source/panels/spell_list.cpp
- Source/plrmsg.cpp
- Source/qol/chatlog.cpp
- Source/qol/floatingnumbers.cpp
- Source/qol/itemlabels.cpp
- Source/qol/monhealthbar.cpp
- Source/qol/stash.cpp
- Source/quests.cpp
- Source/stores.cpp
4 optional args are a bit unwieldy, especially when you want to pass only the first and the last one.
With a struct, there is no need to specify the default values for the args in between.
> `text_render`: Replace optional args with struct

- Source/diablo.cpp
- Source/gamemenu.cpp
- Source/gamemenu.h
Resolves: https://github.com/diasurgical/devilutionX/issues/2622
Currently if we open a lot of windows and have automap enabled, and we press space - all of the windows along with automap get closed. This patch removes that, and allows to close automap with spacebar, but only if every window is closed.
> Automap: Don't close automap when pressing spacebar with other windows open

- Source/DiabloUI/text_input.cpp
- Source/DiabloUI/text_input.hpp
1. Fixes `erase`.
2. Marks some events that will also produce a TextInput event as handled.
3. Adds Ctrl+A.
> TextInput: A couple of fixes

- Source/engine/events.cpp
- Source/lua/repl.cpp
- Source/panels/console.cpp
- Source/panels/console.hpp
Scrolling: PageUp/Down and mouse wheel.
History navigation:
* Up/Down navigates the input history.
* Shift+Up/Down navigates the output history (allowing us to copy/paste the outputs, I imagine this will be very handy).
* Duplicates are skipped.
Also adds a Ctrl+L binding to clear the console.
> Console: Scrolling and history navigation

- .github/workflows/xbox_nxdk.yml
Apparently compiling with LTO breaks USB
@StephenCWills
> xbox_nxdk.yml: Remove LTO=y from SDK flags

- Source/lua/lua.cpp
Previously we failed silently if something went wrong.
@StephenCWills
> Require lua/init.lua to succeed

- .github/workflows/xbox_nxdk.yml
Back port of the master build flags change to 1.5
We might want to update the xbox release once the SDK is updated with the `hypot`  implementation. Would be nice to have higher FPS then.
> nxdk: Build in optimized mode

- Source/engine/displacement.hpp
`std::hypot` is much slower than a naive implementation. It has the advantage of extra precision but we don't need that at all.
Conveniently, this also works around the nxdk issue. We can also cherry-pick this for 1.5.
> `Displacement#distance`: Use a naive hypot impl

- Source/engine/assets.cpp
- Source/engine/assets.hpp
- Source/lua/lua.cpp
- Source/lua/lua.hpp
- Source/lua/repl.cpp
Implements a `require` function that supports built-in modules like so:
```lua
local log = require('devilutionx.log')
```
It falls back to reading from assets, so this loads `lua/user.lua`:
```lua
local user = require('lua.user')
```
The bytecode for the asset scripts is cached, in case we want to later support multiple isolated environments.
There may be a simpler or better way to do this.
It's good enough for now until someone more knowledgeable about Lua comes along.
> Lua: `require` supports loads from assets

- Source/discord/discord.cpp
- Source/engine/displacement.hpp
These asserts should be able to catch overflow and loss of precision in the intermediate stages of the computation.
> Add asserts to Displacement::magnitude()

- CMake/Assets.cmake
- Packaging/resources/assets/lua/repl_prelude.lua
- Source/panels/console.cpp
Runs lua/repl_prelude.lua at console initialization.
The default prelude contains global assignments for all devilutionx modules. This should save us on typing.
The console has its own environment so this doesn't affect other Lua scripts.
> Lua console: Add a prelude file

- 3rdParty/libzt/CMakeLists.txt
Fixes MSVC warning LNK4006 see https://github.com/diasurgical/libzt/pull/15.
When compiling devilutionX with MSVC and this PR the warnings gets reduced by 256 (from 691 to 435).
> Bump libzt

- Packaging/resources/assets/lua/repl_prelude.lua
- Source/CMakeLists.txt
- Source/debug.cpp
- Source/lua/autocomplete.cpp
- Source/lua/lua.cpp
- Source/lua/metadoc.hpp
- Source/lua/modules/audio.cpp
- Source/lua/modules/dev.cpp
- Source/lua/modules/dev.hpp
- Source/lua/modules/dev/quests.cpp
- Source/lua/modules/dev/quests.hpp
- Source/panels/console.cpp
Introduces a new `devilutionx.dev` Lua module, automatically loaded in the console prelude.
Arguments and basic help are shown in autocompletion.
We can now also group commands, as seen here with `quests`:
Signatures and docstrings are implemented as a bit of a hack:
```lua
> inspect(dev.quests)
{
__doc_activate = "Activates the given quest.",
__doc_activateAll = "Activates all available quests.",
__doc_all = "Information on all available quest.",
__doc_info = "Information on the given quest.",
__sig_activate = "(id: number)",
__sig_activateAll = "()",
__sig_all = "()",
__sig_info = "(id: number)",
activate = <function 1>,
activateAll = <function 2>,
all = <function 3>,
info = <function 4>
}
```
We simply put them on the same table as the functions. Autocomplete doesn't show the keys …
> Migrate some debug.cpp commands to Lua

- Source/lua/lua.cpp
- Source/lua/modules/dev/quests.cpp
- Source/lua/repl.cpp
- Source/lua/repl.hpp
MSVC debugger was stopping on an access violation whenever I quit game after opening the Lua console so I decided to track it down. Turns out it was because we were explicitly destroying the Lua state in `LuaShutdown()`, but letting the `replEnv` get reclaimed automatically later. `replEnv` naturally depends on the Lua state, hence the access violation.
I also fixed the following warnings from the Linux build. The second one only happens in debug builds.
```
/home/runner/work/devilutionX/devilutionX/Source/lua/modules/dev/quests.cpp:1:9: warning: #pragma once in main file
1 | #pragma once
|         ^~~~
```
```
/home/runner/work/devilutionX/devilutionX/Source/lua/repl.cpp:51:21: warning: unused variable ‘lua’ [-Wunused-variable]
51 |         sol::state &lua = GetLuaState();
| …
```
> Clean up warnings and debugger errors related to the Lua console

- CMake/Assets.cmake
- Packaging/resources/assets/lua_internal/get_lua_function_signature.lua
- Source/lua/autocomplete.cpp
- Source/lua/lua.cpp
- Source/lua/lua.hpp
This way we at least get something even if the function is not explicitly documented:
> Lua: Show signatures of native (non-C) functions

- Source/engine/render/text_render.cpp
- Source/engine/render/text_render.hpp
- Source/panels/console.cpp
1. Handle word breaks in the prompt, e.g. `"> " -> ">\n"`.
2. Handle word breaks in the original newline for all whitespace, not just `"\n"`.
> Console input: Word-wrap-related cursor fixes

- Source/DiabloUI/settingsmenu.cpp
- Source/engine/actor_position.cpp
- Source/engine/displacement.hpp
- Source/engine/load_file.hpp
- Source/utils/clx_encode.hpp
- Source/utils/str_cat.cpp
- Source/utils/str_cat.hpp
- test/player_test.h
This PR removes all warnings that originate from header files (.h/.hpp) or are related to them.
Reduces warnings by 31 (from 386 to 355).
> Fix MSVC warnings from headers

- Source/engine/render/clx_render.cpp
- Source/engine/render/scrollrt.cpp
- Source/engine/render/text_render.cpp
Reduces warnings by 7 (from 355 to 348)
> Fix MSVC warnings in engine\render\*

- Source/utils/cel_to_clx.cpp
- Source/utils/cl2_to_clx.cpp
- Source/utils/clx_encode.hpp
- Source/utils/file_util.cpp
- Source/utils/language.cpp
- Source/utils/push_aulib_decoder.cpp
- Source/utils/soundsample.cpp
This reduces warnings by 14 (from 297 to 283)
There are some remaining warnings in utils left.
I'm not sure how to handle them the best way:
```
[446/650] Building CXX object Source\CMakeFiles\libdevilutionx.dir\utils\console.cpp.obj
devilutionX\Source\utils\console.cpp(33): warning C4267: 'argument': conversion from 'size_t' to 'DWORD', possible loss of data
[560/650] Building CXX object Source\CMakeFiles\libdevilutionx.dir\utils\file_util.cpp.obj
devilutionX\Source\utils\file_util.cpp(236): warning C4996: 'std::filesystem::u8path': warning STL4021: The std::filesystem::u8path() overloads are deprecated in C++20. The constructors of std::filesystem::path provide equivalent functionality via construction from u8string, u8string_view, or iterators with value_type char8_t. You can define …
```
> Fix MSVC warnings in utils\*

- test/missiles_test.cpp
The code that the gmock macros end up generating appears to obscure the type mismatch so there's no warning (in msvc on my system anyway) no matter what types are involved. For clarity the comparison ends up being between `std::pair<int, unsigned int>` and `testing::Pair<int, testing::AllOf<testing::Matchers<unsigned int>...>>`
> Go back to using int for missile frame comparison values

- Source/msg.cpp
- Source/msg.h
- Source/multi.cpp
- Source/multi.h
- Source/portal.cpp
- Source/portal.h
- Source/spells.cpp
- Source/spells.h
Contributes to #2435 by removing access to `Players` and uses Player reference instead of player indexes in Msg.cpp and some related functions.
This PR reduces warnings by 48 (from 294 to 246).
> Msg: Change OnXYZ to get a Player reference instead of a player index

- Source/menu.cpp
- Source/msg.cpp
- Source/multi.cpp
- Source/nthread.cpp
- Source/storm/storm_net.cpp
- Source/storm/storm_net.hpp
The only named code that was ever set is `STORM_ERROR_NO_MESSAGES_WAITING`. There was also a call in `menu.cpp` which as far as I can tell is not needed (if it is, it should be replaced by something else).
> Remove SNetGet/SetLastError

- Source/control.cpp
- Translations/pl.po
See discussion in #6814 for more information.
> Do not translate chat box commands.

- Translations/pl.po
Changing Polish translation:
* `ON` -> `TAK`, was `WŁ.`
* `OFF` -> `NIE`, was `WYŁ.`
While "wł." and "wył." are shortened correct translations for "on" and "off" using "tak" and "nie" (literally "yes" and "no") makes the menus slightly prettier.
Before:
After:
@qndel tagging you as you also speak the language, I would love to hear your opinion on this!
> Update on/off for Polish translation.

- Source/qol/chatlog.cpp
- Source/qol/floatingnumbers.cpp
- Source/qol/xpbar.cpp
Reduces warnings by 9 (from 241 to 232).
> Fix MSVC warnings in qol\*

- Source/loadsave.cpp
- Source/pack.cpp
- Source/pfile.cpp
Mirrors the logic in `UnPackItem()` to restore and validate the values of fields that would have been restored during unpacking if the item didn't need to be regenerated in `LoadHeroItems()`.
https://github.com/diasurgical/devilutionX/blob/49c5aea845e32cb217a1ccf41eb4bd35674cacad/Source/pack.cpp#L405-L411
This resolves #6561
Introduced in 1.5.1 (#6258)
Unrelated to #5580
> Restore packed item state when regenerating an item using heroitem data

- Source/dvlnet/base.cpp
- Source/dvlnet/tcp_client.cpp
- Source/dvlnet/tcp_client.h
- Source/dvlnet/tcp_server.cpp
- Source/dvlnet/tcp_server.h
Since the abort suggests that the owner should not be sending `PT_DISCONNECT` packets to the player being dropped, the first commit avoids that possibility in the TCP server by disconnecting the client socket before sending the packet.
The second commit treats the error as non-fatal to avoid the possibility of a malicious client triggering a crash in remote clients.
> Handle PT_DISCONNECT packets more gracefully

- Source/effects.cpp
Fixes a crash in timedemo when running the test on an MSVC Debug build. Now that the `sgSFX` collection gets populated by a TSV file, it is not guaranteed to be populated and will in fact remain empty when running timedemo headless. I added some guards to prevent OOB access in two of the affected functions, but I find it's unclear what to do about `GetSFXLength()`. It makes me wonder if we should go ahead and load the TSV so we can have the option of testing towner dialogs with timedemo recordings.
> Don't access sgSFX if sound is not initialized

- CMakeLists.txt
- Source/dvlnet/abstract_net.cpp
- Source/dvlnet/base_protocol.h
> Only enable exceptions for builds with ZeroTier

- Source/missiles.cpp
- Source/missiles.h
- Source/monster.cpp
- Source/msg.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/portal.cpp
- Source/quests.cpp
- Source/spells.cpp
- test/missiles_test.cpp
This PR reduces the number of warnings by 30 (from 221 to 191; less than 200 🎉).
With the new overloads, there is also less id logic scattered throughout the code.
> Introduce AddMissile overloads specific for player and monster

- .github/workflows/Android.yml
- .github/workflows/iOS.yml
- 3rdParty/SDL2/CMakeLists.txt
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- android-project/app/src/main/java/org/libsdl/app/SDLAudioManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLSurface.java
Looks like this is all that was needed for Android to build, let's see how other platforms will react
**WARNING:** I play tested the build on my Google Pixel 2 with Android 11, but I would recommend to play test the CI build on couple more devices before this is merged
P.S. I don't know why Android Studio had to change the **_whole file_** when I committed 2 lines, so look at [SDLActivity.java](https://github.com/diasurgical/devilutionX/compare/master...tsunamistate:devilutionX:SDL-update?expand=1#diff-c171a1bdd421190fd5b4effb33cf09c5e17062fa6cbbabbe8e3ddb1702cf0a5b) changes with "Hide whitespace" ON
> Upgrade source-download SDL to 2.28.5

- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
- Source/msg.cpp
- Source/sync.cpp
- Source/towners.cpp
Monsters are only updated `dMonster` with a non-zero value in `Monster::occupyTile`.
This PR reduces warnings by 23 (from 191 to 168).
> Introduce Monster::occupyTile

- Source/levels/crypt.cpp
- Source/levels/drlg_l1.cpp
- Source/levels/drlg_l2.cpp
- Source/levels/drlg_l3.cpp
- Source/levels/drlg_l4.cpp
- Source/levels/gendung.cpp
- Source/levels/gendung.h
- Source/levels/town.cpp
- Source/monster.cpp
- Source/objects.cpp
- Source/quests.cpp
- test/drlg_test.hpp
This PR includes three refactorings
- Introduce a helper method `GetDunSize` to get the ".dun"-size. Use this in every place a `WorldTileSize` is needed. (first commit)
- Use the new `GetDunSize` also in loops. I'm not 100% of this, that's also why this is a separate commit. (second commit)
- Replace global `pSetPiece` and it's related helper functions (`SetSetPieceRoom` and `FreeQuestSetPieces`) with a anonymous function in each level generator (`InitSetPiece`). Less global variables. 😁 (third commit)
This PR also reduces warnings by 16 (from 153 to 137).
> Introduce GetDunSize and remove global SetPiece Handling

- Source/monstdat.cpp
- Source/monster.cpp
This PR reduces warnings by 20 (from 137 to 117)
> Fix MSVC warnings in monster.cpp/monsterdat.cpp

- Source/monster.cpp
Fixed a bug reported by @FitzRoyX on discord
It happens when entering a new level and monsters are visible.
@StephenCWills has a good description:
> It's calling InitAllMonsterGFX() at the end of InitMonsters().
> It means that all calls to InitMonster() are already complete, and have copied animation data from CMonster structs before the animations have even been loaded into CMonster structs.
> It doesn't completely break the game because monsters change state when they are activated. But if a monster is visible from the stairs, it hasn't had a chance to change states before the first time it's drawn.
This PR fixes the issue by updating the animations after the new sprites are loaded.
This happens for all Monsters that don't have a sprite loaded yet.
Alternative fixes, could be
- Change …
> Update existing monsters after loading monster gfx

- Source/lua/modules/dev/monsters.cpp
- Source/monster.cpp
- Source/monster.h
`dev.monsters.spawn[unique]` didn't work correctly.
Mainly cause this was missing:
```cpp
const size_t numAnims = GetNumAnims(monsterData);
for (size_t i = 0; i < numAnims; ++i) {
AnimStruct &anim = monsterType.anims[i];
anim.frames = monsterData.frames[i];
if (monsterData.hasAnim(i)) {
anim.rate = monsterData.rate[i];
anim.width = monsterData.width;
}
}
```
But instead of cloning this code this PR make `AddMonsterType` public and uses it instead.
> Fix debug spawning monsters

- Source/controls/plrctrls.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/items.h
- Source/missiles.cpp
- Source/missiles.h
- Source/monster.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/player.h
- Source/qol/stash.cpp
Small refactoring.
Done by using more `Player` references and `PlayerAtPosition`.
Btw: it's nice to see that `dPlayer` is relatively rarely used in the current codebase.
> Reduce usage of dPlayer

- android-project/app/build.gradle
- android-project/build.gradle
- android-project/gradle.properties
- android-project/gradle/wrapper/gradle-wrapper.properties
* Upgrade Gradle plugin to 8.2.0
* Upgrade Gradle to 8.5
* Upgrade NDK to 26.1
* Move `buildFeatures` to Gradle build file, since using flag in `gradle.properties` is deprecated
Playtested on my Google Pixel 2, Android 11, but with NDK change, it wouldn't hurt to test CI build on couple more devices before merging
> Android build system upgrades

- Source/DiabloUI/settingsmenu.cpp
- Source/control.h
- Source/controls/game_controls.cpp
- Source/controls/touch/event_handlers.cpp
- Source/diablo.cpp
- Source/engine/events.cpp
- Source/engine/render/scrollrt.cpp
- Source/options.cpp
- Source/options.h
- Source/panels/spell_list.cpp
- Source/panels/spell_list.hpp
Fixes #6858
Notes
- This PR implements unsetting quick spells (try to bind the same spell as currently assigned to quick spell removes the binding).
- Keymapper supports now mouse wheel up/down/left/right. This can also be rebind to different targets.
- My mouse don't support mouse wheel left/right, so I couldn't test mouse wheel left/right.
> Implement quick spell cycling

- Source/dvlnet/abstract_net.h
- Source/dvlnet/base.cpp
- Source/dvlnet/base.h
- Source/dvlnet/cdwrap.cpp
- Source/dvlnet/cdwrap.h
- Source/dvlnet/loopback.cpp
- Source/dvlnet/loopback.h
- Source/msg.cpp
- Source/msg.h
- Source/multi.cpp
- Source/multi.h
- Source/storm/storm_net.cpp
- Source/storm/storm_net.hpp
- Source/sync.cpp
- Source/sync.h
This PR reduces warnings by 33 (from 74 to 41).
One of the big changes is the use of `uint8_t` instead of `size_t` for player id in msg/multi/sync/network code (see also discussion in #6849).
I noticed that `SNPLAYER_ALL` was not being used (now removed).
Another thing is that `size_t` is now mostly used to pass memory sizes around in msg/multi/sync.
The rest are just minor MSVC warning fixes.
Sorry this PR is a bit bigger, but I tried to make different commits to make the review process easier.
> Use uint8_t in msg/multi/sync and fix MSVC warnings

- Packaging/nix/devilutionx.metainfo.xml
TODO: Release date was put as a stopgap to avoid tripping Flatpak validator, change it before actual release date
> Add 1.5.2 release to metainfo

- Source/controls/controller_motion.cpp
- Source/controls/devices/joystick.cpp
- Source/controls/touch/gamepad.cpp
This PR reduces warnings by 15 (from 32 to 17)
Changes are
- when using `round` cast to int
- avoid switches with only default-case (warning C4065; `switch statement contains 'default' but no 'case' labels`)
The C4065 warning was a bit annoying, as I think the old syntax is fine.
This PR will wrap each switch with another `#ifdef' to see if there is a case present.
An alternative fix would be to ignore the warning. So if we think this is better, we can change the PR.
Note: I haven't been able to test this PR because I don't own a joystick, let alone a device which enables the defines.
> Fix MSVC warnings in controls\*

- Source/stores.cpp
This PR reduces warnings by 4 (from 17 to 13).
I thought about doing more refactoring... but stores.cpp needs a more general approach.
Now only `mpq_writer` and `mpq_sdl_rwops` is missing. And there I'm unsure if I should change everything size related to `size_t`, `uint32_t` or `uintmax_t`. 😁
> Fix MSVC warnings in stores.cpp

- Source/engine.cpp
- Source/engine/palette.cpp
I think I see two issues. First, here is where we draw the half-transparent rectangle.
https://github.com/diasurgical/devilutionX/blob/6648f080bae31c67bb554372c233d555b42392b7/Source/engine.cpp#L54-L59
When we make use of this lookup table on big-endian systems, we swap the 16-bit values we pass into the lookup, but the 16-bit values themselves are in the system's native endian order. However, since we are interpreting the original pixel as a native-endian 32-bit value and also assigning `*pix` as a native-endian 32-bit value, I think it would be easiest to use native-endian order throughout. The little-endian logic doesn't swap any bytes so we can just remove the special case for big-endian systems.
And that just leaves us with making sure that we build the lookup table using …
> Remove byte order logic from half-transparency lookups

- Source/mpq/mpq_reader.cpp
- Source/mpq/mpq_reader.hpp
- Source/mpq/mpq_sdl_rwops.cpp
- Source/mpq/mpq_writer.cpp
- Source/mpq/mpq_writer.hpp
This PR fixes all remaining MSVC warnings for x64 (debug and release) on SDL2.
I tried to stay close to the original/existing code.
For SDL_RWops/Reading `size_t` is used for size.
For MpqWriter `uint32_t` is used for size.
It was a long way from 703 warnings to 0.
I hope that the cleanups will not only help to reduce the warnings, but also make the code more consistent. Especially with the types used.
> Fix remaining MSVC x64 SDL2 warnings

- Source/engine/assets.hpp
- Source/interfac.cpp
- Source/interfac.h
- Source/mpq/mpq_reader.cpp
- Source/pfile.cpp
- Source/stores.cpp
- test/writehero_test.cpp
As a bonus this PR fixes the warnings for the remaining MSVC configurations (x86 (debug and release) and x64 SDL1 (debug)).
> Fix MSVC x86 and x64 SDL1 warnings

- Source/control.cpp
Singleplayer chat was been enabled to support debug commands.
We now have a proper console for debugging commands, so this workaround is no longer needed.
> Disable chat in singleplayer also for debug builds

- 3rdParty/discord/CMakeLists.txt
This PR fixes the Discord integration on MSVC on x86.
In devilutionX we are applying some patches to the Discord sdk to fix various issues:
```
1. Replaces `#include <Windows.h>` with `#include <windows.h>`
for compatibility with case-sensitive file systems (e.g. MinGW
cross-compilation on a Linux host).
2. Adds missing `#include <cstdint>` to `cpp/types.h`.
3. Fixes calling convention for callback lambdas.
```
The last point (fixing calling convention) breaks MSVC x86 builds.
> error C2760: syntax error: '__stdcall' was unexpected here; expected '{'
The applied fix adds `DISCORD_CALLBACK` to [lambdas](https://github.com/diasurgical/devilutionX/blob/b32cc11ad9b6008d7b31d74e43184829dc39a2cd/3rdParty/discord/fixes.patch#L77-L78).
`DISCORD_CALLBACK` is defined as
```
#ifdef _WIN32
#ifdef …
```
> Fix windows x86 discord integration

- Source/qol/itemlabels.cpp
Refs #6889
Let's cherry-pick this for 1.5.2 as well.
> Fix item label height for CJK

- Source/control.cpp
- Source/control.h
- Source/engine/render/scrollrt.cpp
It still isn't perfect (there just isn't enough space) but we now cut off fewer pixels at the bottom.
Refs #6889
Let's cherry-pick this for 1.5.2 as well
> Slightly improve CJK infobox rendering

- Source/lua/modules/dev/monsters.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
- Source/msg.cpp
- Source/msg.h
- Source/player.cpp
- Source/player.h
Fixes #1682
This PR synchronises dynamically spawned monsters between clients (monsters not spawned during level loading).
Doppelganger and Hork demon spawns should now synchronise between clients.
This PR would also allow Leoric to dynamically spawn skeletons in multiplayer (not part of this PR).
Logic
- Only one player is the dungeon levelmaster (similar to items).
- This player's game logic decides whether new monsters spawn or not (see the `SpawnMonster` function).
- This ensures that the dynamically spawned monsters have the same monsterId on all clients (necessary for correct synchronisation).
- Other clients are informed about the new monster with the new network command `CMD_SPAWNMONSTER`.
- Information about dynamically spawned monsters is stored in `DLevel`.
This may also be …
> Support dynamically spawned monsters in multiplayer

- Source/.clang-format
- Source/control.cpp
- Source/control.h
- Source/engine/render/scrollrt.cpp
- Source/qol/itemlabels.cpp
- test/.clang-format
Cherry-picks of #6894 and #6895 for 1.5
> CJK fixes for 1.5

- .github/workflows/Linux_aarch64.yml
`llvm-toolchain-focal` now provides clang 19 instead of 18. Changes the repo to `llvm-toolchain-focal-18`.
> Fix Linux aarch64 CI

- .circleci/config.yml
- 3rdParty/SDL2/CMakeLists.txt
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- android-project/app/src/main/java/org/libsdl/app/SDLAudioManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLSurface.java
- android-project/build.gradle
This fixes the game locking up on Android when receiving a phone call or (dis)connecting headphones.
> Upgrade SDL to 2.30.0 for 1.5

- .circleci/config.yml
- 3rdParty/SDL2/CMakeLists.txt
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- android-project/build.gradle
- DevkitPro's latest switch image broke our bulid so I locked it to the previous version.
- Upgrading SDL to 2.30.0 fixes a lockup on Android when the OS switching audio output.
> Upgrade SDL to 2.30.0 and fix Switch build

- Source/mpq/mpq_sdl_rwops.cpp
Was introduced in #6928 and only happens in MSVC SDL1.
Sorry I wanted to check #6928 before but wasn't fast enough.
> Fix MSVC warning in SDL1

- Source/msg.cpp
When killing an existing monster and spawning a new monster on the same monster index, the delta wasn't always overridden/initialised correctly.
Found during testing #6934
> SpawnMonster: Override old monster delta information

- Packaging/nix/devilutionx.metainfo.xml
It's not relevant to flatpak anyway
> Remove offending line from metainfo

- Packaging/nix/devilutionx.metainfo.xml
Same thing as https://github.com/diasurgical/devilutionX/pull/6944 rebased onto `master`
> Remove offending line from metainfo (master version)

- CMakeLists.txt
It seems that `nx_create_nro()` requires the romfs directory to exist at configure time, and `Assets.cmake` only creates it if `gettext` is installed. The following error occurs when `gettext` is not installed (as reported by WinterMute on the devkitPro forums). This PR resolves the error.
```
-- Could NOT find Gettext (missing: GETTEXT_MSGMERGE_EXECUTABLE GETTEXT_MSGFMT_EXECUTABLE) 
CMake Error at /opt/devkitpro/cmake/Platform/NintendoSwitch.cmake:135 (message):
nx_create_nro: cannot find romfs dir:
/projects/switch/devilutionX/_switch/assets
Call Stack (most recent call first):
CMakeLists.txt:424 (nx_create_nro)
-- Configuring incomplete, errors occurred!
```
> [Switch] Ensure romfs directory exists during CMake configure

- .github/workflows/Linux_aarch64.yml
- docs/CHANGELOG.md
> Statically link BZIP2 and libsodium on AArch64

- Source/msg.cpp
- Source/pack.cpp
- Source/pack.h
It's basically #6723, but applied to #6679.
> Apply Hellfire spellbook validation to PItem packet handling

- Source/engine/random.hpp
- Source/objects.cpp
- Source/quests.cpp
This PR begins the process of isolating seeded random number generators from the global RNG state. I expect that item generation and dungeon generation will each need a fairly sizeable set of changes to ensure RNG instances are being passed around appropriately to avoid compatibility issues so I plan to do the same for each of them in separate PRs. After those are out of the way, we can look into potentially scrubbing out the remaining calls to `SetRndSeed()` and changing up how various seeds get generated.
> Isolate shrine/quest pool RNG from global RNG state

- Packaging/xbox-one/build.bat
Right now, CI is producing a file called `devilutionX_1.5.1.0_x64.appx` because it's based on `git describe --tags`. `Select-String` pulls the version number out of the `VERSION` file using a regex to produce `devilutionX_1.6.0.0_x64.appx`.
> Get version from version file in UWP build

- uwp-project/src/SDL_winrt_main_NonXAML.cpp
See https://github.com/diasurgical/devilutionX/issues/6930#issuecomment-1926945631
> I remember now that the Xbox One/Xbox Series build had some custom startup code that attempted to swap the A/B and X/Y buttons using SDL controller mappings.
> 
> https://github.com/diasurgical/devilutionX/blob/9a148ab9909e51e4c33468ec232206e327e934d1/uwp-project/src/SDL_winrt_main_NonXAML.cpp#L65-L82
> 
> Now that we are able to detect controller type, this code should be unnecessary. But it's worse than that because I've found that it's subject to a race condition. Sometimes this code runs before the SDL event that adds the game controller. Discord user Tree reported it on Discord back in August 2022, and I think there was another report even before that so I think that confirms it happens on Xbox …
> Remove hardcoded SDL controller mapping from UWP build

- Source/engine/render/automap_render.cpp
> Fix out-of-bounds mini-map pentagram

- Source/automap.cpp
I can't really take any credit for this. I just copied @glebm's work in #6968.
Fixes #6936
> Fix out-of-bounds mini-map ellipse

- Source/items.cpp
- test/player_test.cpp
- test/writehero_test.cpp
Since the item sizes are no longer hardcoded as of dc59cda, we need to load the cursor graphics when creating starting items or else we can't know if the item fits in a belt slot.
This resolves #6980
> Load objcurs when creating starting items

- .github/workflows/Windows_MSVC_x64.yml
- vcpkg.json
This upgrades libsodium to 1.0.19 and SDL-image to 2.8.2 for MSVC builds
Playtested successfully, unit tests also pass
> Upgrade vcpkg commit

- Source/items.cpp
**Motivation:** With 800x600 and lower resolutions it is not possible to see unique item's info-box in your stash or when both left- and right-side panels are open.
**Solution:** Showing overlapping info-box with a darker background in the cases above.
Before:
After:
**Bonus:** changed alignment of info-box for unique items in the stash.
Before:
After:
> Unique items InfoBox in stash in 800x600 and lower resolutions

- Source/control.cpp
- Source/diablo.cpp
- Source/diablo.h
- Source/levels/drlg_l1.cpp
- Source/levels/drlg_l2.cpp
- Source/levels/drlg_l3.cpp
- Source/levels/drlg_l4.cpp
- Source/loadsave.cpp
- Source/lua/modules/dev/level.cpp
- Source/msg.cpp
- Source/multi.cpp
- Source/objects.cpp
- Source/quests.cpp
- Source/stores.cpp
- test/fixtures/memory_map/levelSeed.txt
Speeds up the loading screen when revisiting a dungeon level.
> Capture the level seed and use it to skip failed dungeon layouts

- Source/levels/themes.cpp
This greatly speeds up level generation as there is no need to search for the fitness of 127 (or 256 as in the original) rooms if only 23 where created.
> Limit theme scan to the number of generated rooms

- Source/player.cpp
the maximum damage is max-1
fixes https://github.com/diasurgical/devilution/issues/64#issuecomment-1646754276
> spectral damage off by 1

- Source/quests.cpp
- test/quests_test.cpp
In order to hit the case that the QuestGroup2 and QuestGroup3 checks were guarding against a player would need to edit their save or modify the game to allow storing a raw seed value instead of the output of `AdvanceRndSeed()`. Since this can't happen in normal gameplay I don't think it's necessary to keep compatibility here. The other mitigating factor is quest availability is saved as part of the game state so there's no issues loading these saves on vanilla diablo or in devX.
It's possible that someone playing on an NT-based windows could set their system time to the 1977 date and start a new game at a time that lands on the seed 988045466 for dlvl 15. To ensure we leave all quests in this group active (as vanilla does) I've checked for that seed explicitly.
Massive props to staphen …
> Replace OOB guards with safe RNG calls when initialising quests

- Source/player.cpp
Fixes: https://github.com/diasurgical/devilutionX/issues/6879
Prevents the speech from playing upon entering dungeon level 16 if Diablo is already dead.
> Bugfix: DLVL 16 speech after Diablo death

- .devcontainer/Dockerfile
Fixes broken curl reference to outdated release URL for D1GraphicsTool in the Dockerfile
Switched to https://github.com/diasurgical/d1-graphics-tool/releases/latest/download/D1GraphicsTool-Linux-Qt5.deb from https://github.com/diasurgical/d1-graphics-tool/releases/latest/download/D1GraphicsTool-Linux-x64.de
Also fixed the package references in the command line inputs after the curl command
> Dockerfile update

- Source/engine/actor_position.cpp
- Source/engine/render/scrollrt.cpp
- Source/player.cpp
Fixes the notorious "South Walk" bug. Due to difficulties in Diablo's development with floor tiles being drawn over the player, Blizzard North's solution was to change the player's tile occupation to the tile the player was moving into in the south direction, and drawing the player using an offset from above the tile, with the player walking from the top down into the newly occupied tile.
This resulted in two prominent problems noticeable by players:
- Monsters attempting to attack a player moving southwards were completely unable to hit the player
- Players entering hit recovery while moving southwards would "snap" into the tile they were moving into
DevilutionX has a fix for render order, rendering all the floor tiles separately before other things are rendered, therefore we're able to …
> Fix South Walk bug

- Source/automap.cpp
- Source/engine/actor_position.cpp
- Source/engine/render/scrollrt.cpp
- Source/monster.cpp
- Source/player.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/7047.
With this change along with https://github.com/diasurgical/devilutionX/pull/7043, walking in any direction uses the same function for walking for players and monsters respectively, regardless of direction.
> Fix broken monster walking offset + unify walking behavior

- Source/engine/render/scrollrt.cpp
- Source/monster.cpp
This resolves a problem with draw order for players and monsters passing through doorways, caused by https://github.com/diasurgical/devilutionX/pull/7043. It's possible there are other situations where draw order was a problem which this should also resolve.
This PR is step 1; step 2 will be fixing draw order problems with sideways walk.
> Fix draw order problems with south walk

- Source/engine/render/scrollrt.cpp
This resolves a problem with draw order for players and monsters unrelated to floors, caused by https://github.com/diasurgical/devilutionX/pull/7043. This PR draws east walking sprites in tiles that contain their negative offset (moving into that tile), and then offsetting them back visually to where they should be drawn on screen, giving them priority.
(Continues https://github.com/diasurgical/devilutionX/pull/7053)
> Fix Sideways Walk Draw Order

- Source/control.cpp
This fixes #7054
I tested to make sure the other buttons and things on the panel still show up properly, but someone might want to double check that this is the correct way to clear the panel.
> Clear Panel so lines don't repeat

- Source/engine/render/scrollrt.cpp
Fixed a bug that caused monsters with a `dMonster` value of over 127 to be invisible.
Removed an unnecessary return in `DrawMonsterHelper()`, because `dMonster` at the tile position passed down will never be negative.
> Fix draw monster

- Source/items.cpp
- Source/player.cpp
Based on #6687.
Clicking on an item called `CalcPlrItemVals`, which reset _pInfraFlag to `false`, which was responsible for allowing unseen monsters to be drawn. As infravision technically is a "missile" that sets this variable to `true` every step (_not_ every frame) that meant that on slower speed there could be a few frames where this variable was `false` before being set to `true` again by this "missile".
As I did not want to change how infravision works, I moved `_pInfraFlag = false` to `ValidatePlayer`, called by `ProcessPlayers`, which is called before `ProcessMissiles`. This solved this issue for me.
> [Bugfix]: Infravision monsters flickering when manipulating inventory (#6687)

- Source/engine/render/scrollrt.cpp
Monsters inside solid tiles, like inside the Arkaine's Valor room before it's opened up, are able to be seen with Infravision. This fixes that.
> Fix rendering monsters in solid tiles

- Source/stores.cpp
Gets rid of the "No required attributes". This provides unnecessary information, as a lack of required attributes signals no required attributes. This also makes it easier to read through shops, as it's less text spam. This could even reduces the amount of lines displayed in the shop by 50%.
> Clean up store inferface

- assets/txtdata/items/itemdat.tsv
4 of the starting items have outdated values that match the values from in the PR demo, meaning they were never updated to match the retail values. This PR sets the correct values which are found in retail on non-starting items. Here's the evidence:
**Short Sword**
New Char Item - Durability (PR): 20
Normal Item - Durability (PR): 20
New Char Item - Durability (Retail): 20
Normal Item - Durability (Retail): 24
New Char Item - Value (PR): 50
Normal Item - Value (PR): 50
New Char Item - Value (Retail): 50
Normal Item - Value (Retail): 120
**Buckler**
New Char Item - Durability (PR): 10
Normal Item - Durability (PR): 10
New Char Item - Durability (Retail): 10
Normal Item - Durability (Retail): 16
New Char Item - Value (PR): 50
Normal Item - Value (PR): 50
New Char Item - Value (Retail): 50 …
> Fix outdated values for starting items

- Source/engine/render/scrollrt.cpp
Change `lastFpsUpdateInMs` to `uint32_t` to harmonize the logic in `DrawFPS()` with `SDL_GetTicks()`. Fixes compiler warnings.
> Clean up: DrawFPS()

- Source/engine/render/scrollrt.cpp
Corrects a bug caused by https://github.com/diasurgical/devilutionX/pull/7075.
New logic:
Tile in vision = draw monster
Tile not in vision + no infravision + (monster either in solid tile or not) = no draw monster
Tile not in vision + (either infravision or no infravision) + monster in solid tile = no draw monster
> Bugfix: Invisible monsters/towners in solid tiles in vision range

- Source/levels/town.cpp
Hi!
This is my first code commit, fixes #6869.
I patched up the offending tiles in town.cpp. I also tried to fix the neighbouring tiles as the Hellfire team did one ugly job there. I hope it's okay. Let me know if the comments are unnecessary, I wanted to keep the original values there.
On a related note, there's another faulty tree above the river fork that has its shadow cut-off, but it probably has no correct tiles.
> Patch up wrong tree tile near Hive entrance (#6869)

- Source/loadsave.cpp
We could have put this data back in the `Monster` struct as mostly-unused fields, but I thought I'd propose this first so we can decide whether it's more complex than it's worth.
This resolves #7078
> Fix level conversion when migrating saves between Diablo and Hellfire

- Source/monster.cpp
From Jarulf's Guide:
> The Hiddens have the ability to disappear. They are always active and can always see you, even with max reduced light radius, regardless of whether or not you have a line of sight to them and regardless of the distance.
From the DSF buglist (https://www.lurkerlounge.com/forums/thread-12422.html):
> Monsters that use Hidden AI are always active. Unless there's a barrier between them and the player (e.g. closed door, barrels completely blocking a path), they'll reach the player without any action on the player's part.
Neither of these descriptions really capture the nuance, and they're both technically wrong. First, I'd like to point out there is a pattern used throughout the AI routines to determine whether a monster is active. Here is one example. …
> Hiddens are no longer omniscient

- Source/debug.cpp
I think creating a new branch will fix the CI cache for iOS and MacOS.
This replaces #7104
> Dungeon coordinates can extend into the 16-tile padding around arrays that use `dungeonCoords` like `dPiece`, but the megatile arrays have no padding. If `dungeonCoords` points to a location in the padded area, it will produce a value for `megaCoords` that is out of bounds. This was causing my game to crash when using `dev.display.tileData("Protected")` near the edge of the dungeon.
> Fix OOB when debugging megatile data near the edge of the dungeon

- Source/engine/demomode.cpp
We were previously not setting it all which was incorrect but did not cause any issues because we had not used it. We do check scancode for the debug console key. This caused a sanitizer warning when running the demo in debug mode.
> Demomode: Set scancode for keyboard events

- Source/lua/modules/dev/player/stats.cpp
Attempting to assign to the parameter on line 19 caused an error when I was debugging. The correct approach would have been `levels.emplace(1)`, but I switched over to `levels.value_or(1)` to be more consistent with the pattern used by other debug functions.
> Don't dereference nullopt in DebugCmdLevelUp()

- Source/loadsave.cpp
- Source/pack.cpp
Fixes: https://github.com/diasurgical/devilutionX/issues/7111
When loading/unpacking player data, spells with a book level of -1 are set to spell level 0, and if the game mode isn't Hellfire, Apocalypse and Nova get set to spell level 0. Additionally, all indices of `_pSplLvl[64]` which do not have a `SpellID` enumerator are automatically loaded/unpacked as spell level 0.
> Fix illegal spell levels

- .github/workflows/Windows_MSVC_x64.yml
- vcpkg.json
When I attempted to build DevilutionX on my laptop for the first time in a long while, I encountered the error described in https://github.com/microsoft/vcpkg/issues/38947.
From what I gathered, the vcpkg port for libsodium 1.0.19 was pointed to the `1.0.19` tag in libsodium which is a moving target. The tag changed, which invalidated their hash. They fixed it by targeting the `1.0.20-RELEASE` tag which is a more stable target, but it does nothing to resolve the 1.0.19 hash.
Anyone who has already downloaded the 1.0.19 package should be unaffected. Anyone who hasn't already downloaded it is going to encounter the error and be unable to build. So we don't have much choice but to update.
> Update vcpkg baseline to get libsodium 1.0.20

- Source/engine/render/blit_impl.hpp
On my desktop with Ryzen 3950x, RTX 4080, Ubuntu 24.04, gcc 13.2.0, I get a consistent performance improvement with this PR, as measured by `tools/measure_timedemo_performance.py`.
Before: 7.722 ± 0.065 seconds, 949.090 ± 7.807 FPS\
After: 6.733 ± 0.057 seconds, 1088.520 ± 8.710 FPS
Binary size is also decreased by ~350 KiB:
Before: 6007752
After: 5652488
RG99 binary size is only decreased by ~16 KiB, still a good thing.
> blit_impl: Use <algorithm> with unseq policy

- Source/dvlnet/abstract_net.h
- Source/dvlnet/base_protocol.h
- Source/dvlnet/cdwrap.cpp
- Source/dvlnet/cdwrap.h
- Source/dvlnet/loopback.cpp
- Source/dvlnet/loopback.h
- Source/dvlnet/tcp_client.cpp
- Source/dvlnet/tcp_client.h
When joining TCP games, instead of using the port setting from the local INI file to determine the port used by the remote host, parse the port from the host string entered by the user. This format resembles the format used for URLs. If the host has changed their port, the guest shouldn't need to modify their INI file to join.
> Parse TCP host using hostname:port format

- Source/CMakeLists.txt
- Source/engine/render/blit_impl.hpp
- Source/utils/attributes.h
We know that length is never 0.
Letting the compiler know that allows it to optimize one instruction away.
Moreover, for Fill runs, we also know that the length is at least 2.
https://godbolt.org/z/aM4zTjeYM
Additionally, switches to using `-O2` even in Release mode:
-O3 tries to vectorize blit loops too aggressively, but our blit calls mostly loop only a few times.
`measure_timedemo_performance` on my machine:
* O1: 6.606 ± 0.060 seconds, 1109.520 ± 9.843 FPS
* O2: 6.484 ± 0.063 seconds, 1130.220 ± 10.909 FPS
* O3: 6.746 ± 0.017 seconds, 1086.260 ± 2.170 FPS
> blit_impl: Add length assumptions and use O2 even in Release

- Source/engine/render/blit_impl.hpp
Turns out we can have fills of length 1
> blit_impl.hpp: Fix incorrect assumption

- Source/diablo.cpp
- Source/engine/render/clx_render.cpp
- Source/engine/render/clx_render.hpp
- Source/utils/static_bit_vector.hpp
- Source/utils/static_vector.hpp
- test/CMakeLists.txt
- test/static_bit_vector_test.cpp
The new algorithm is a lot less code, slightly faster, and results in a smaller binary (-40 KiB on rg99).
The previous algorithm filled all the pixels around every solid pixel. The new algorithm only fills pixels that will be visible.
We first collect the outline pixels into an array (which may contain a small amount of duplicates). Then, we render the entire array in a single loop. This turns out to be slightly faster than rendering inline, at the cost of ~4 KiB of stack (basically free).
To collect the pixels, we go through the CLX sprite, keeping track of the solid runs in the current row, and the filled pixels on the line above and the line below.
To be able to quickly test the pixels above and below, we introduce a new data structure, `StaticBitVector`. It is similar to a bitset, …
> Greatly simplify outline rendering

- Source/controls/plrctrls.cpp
- Source/engine/assets.cpp
- Source/utils/log.hpp
- Source/utils/sdl2_to_1_2_backports.cpp
When we switched to `fmt` for logging, the log functions were implemented in such a way that the strings were always constructed, even if log priority was such that they weren't ever logged.
> Log: Avoid making strings that won't be printed

- Source/dvlnet/base.h
- Source/spelldat.cpp
- Source/utils/attributes.h
- Source/utils/static_vector.hpp
The pure attribute on `StaticVector#empty` is needed so that it can be used in `DVL_ASSUME` without a warning about side-effects in assume.
> Fix a few more warnings

- Source/utils/display.cpp
On Ubuntu 24.04, which uses [sdl12-compat](https://github.com/libsdl-org/sdl12-compat), when running in a window, `SDL_GetVideoInfo` returns the display size rather than the window size, resulting in incorrect scaling.
Using `SDL_GetVideoSurface` instead of `SDL_GetVideoInfo` fixes this.
> SDL1: Fix windowed video mode with sdl12-compat

- Source/CMakeLists.txt
- Source/utils/log.hpp
- test/CMakeLists.txt
- test/app_fatal_for_testing.cpp
This allows the tests for these libraries to be built without linking all of libdevilutionx, improving build times and cache efficiency.
> Make a few libraries standalone

- Source/engine/render/scrollrt.cpp
This resolves an issue when using software cursor where the hourglass is mostly invisible, flickering onto the screen only briefly every 500 ms or so.
The order of events in `scrollrt_draw_game_screen()` was reversed in 680ab5e such that the cursor is removed from the back buffer, the back buffer is drawn to the output surface, and then the cursor is redrawn to the back buffer. The original intent was to draw the cursor onto the back buffer so it can be drawn to the output surface, then restore the back buffer to its previous state. If you do it in reverse order, the cursor doesn't get drawn onto the output surface and remains invisible for most of its duration, flickering onto the screen only when `DrawAndBlit()` is called every 500 ms or so.
However in cb9da2c, the order of events was …
> Fix order of events when drawing timeout cursor

- Source/engine/render/clx_render.cpp
@Trihedraf reported that the game crashed when killing Diablo.
1536 should be enough for Diablo and any custom sprites (if not, we can increase it further).
> Increase OutlinePixels limit from 1024 to 1536

- Source/cursor.cpp
This PR ensures that the cursor is actually an item cursor before attempting to draw it as an item.
When holding an item on the cursor, if the game lags and displays the hourglass, the hourglass cursor would be drawn as an item. This would cause the game to draw an outline around the hourglass and, if the player cannot use the item they are holding, apply the Infravision TRN to the hourglass sprite.
> Don't draw non-item cursors as items

- Source/msg.cpp
I recently received a copy of a Veil of Steel that had been generated in vanilla Hellfire with ilvl 25 and both the `CF_UNIQUE` flag and the `CF_SMITHPREMIUM` flag. Here is a character save with a copy of the item: [single_0.hsv.zip](https://github.com/user-attachments/files/15946593/single_0.hsv.zip).
This is basically the same issue as described in #6560, except in this case the function is `SpawnUnique()` which doesn't use `item[0]` but rather gets an available item using the `itemavail` array.
> In vanilla, `LoadGameLevel()` calls `InitItems()`. This calls `GetItemAttrs()` on `item[0]`, passing in `IDI_GOLD` and ilvl 1. You'd think that would set the creation flags to 1, but it seems this ilvl only gets used for books and oils. It doesn't modify creation flags at all.
Basically, for …
> Don't validate items in Single Player

- Source/engine/render/dun_render.cpp
- Source/lighting.cpp
- Source/lighting.h
Fixes #6535
- The renderer has a optimization for fully lit and fully dark tiles.
- For fully lit tiles (light table index 0) the color map is ignored and a simple copy of the pixels is made
- For fully dark tiles (light table index 15) the color map is ignored and all pixels are filled with black.
- This optimization assumes that the color map always maps to the same color (fully lit) or maps always maps to black (fully dark). This is not true.
- Hell levels have a color map for fully lit tiles to support the ceiling animation.
- Hellfire levels there do not have a fully dark color map.
- In #6535 one ceiling tile has a dLight value of 0 (fully lit).
- This happens more often in devilutionX, because the light is updated more often since b7424a0068f59cfa253c959dd27accbdd317156a.
- The bug …
> Respect hell and hellfire color maps for fully lit and fully dark tiles

- CMakeLists.txt
This adds a CPack Generator for a Windows Installer. To add to cmake command is -DWIN_NSIS=ON.
<details><summary>Install</summary>
<p>
</p>
</details> 
<details><summary>Uninstall</summary>
<p>
</p>
</details>
> Add CPack NSIS Windows Installer

- android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java
Using my Pixel 6a as an example, the display is 2400x1080. When SDL creates the surface on which to display the game, that surface ends up avoiding the "display cutout" region which prevents the app from rendering behind my front-facing camera lens. This means the app only has access to a 2268x1080 region, which causes some problems like the one described in #7172. That is to say, Integer Scaling + Fit to Screen is not supposed to have a letterbox.
Based on the assumption that the screen's obstructions likely won't overlap with anything important at the edge of a widescreen display, this PR just arbitrarily forces the app to use the full screen space.
> [Android] Force app to overlap with the display cutout

- Source/utils/log.hpp
Avoids going through `fmt` for single-argument log calls.
> Add single-argument logging overloads

- Source/items.cpp
This allows the translator to change the order of the inserted string.
Todo: update existing translation
Note that this does make the "Book of " string in the TSV data unused, but that isn't to different from how for example oils work.
> Allow for more flexible translations of "Book of {SpellName}"

- Source/control.cpp
The `TimeoutCursor()` function sets up the info panel to display basic information about why the game is lagging.
https://github.com/diasurgical/devilutionX/blob/15e44a19c3e0d0e80cb6185103e0a4b4286d40a9/Source/diablo.cpp#L1476-L1478
This text was being overwritten by the logic in `DrawInfoBox()` unless the player was highlighting an item or something that would skip that logic. This means the text sometimes shows up and sometimes doesn't. This PR simply adjusts the logic in `DrawInfoBox()` to detect when the game is lagging and avoid clearing the info text, overwriting it with something else, or using the wrong text color.
> Ensure that network timeout info shows up in the info panel

- assets/txtdata/sound/effects-unused.tsv
- assets/txtdata/sound/effects.tsv
Done with the following script:
```ruby
#!/usr/bin/env ruby
tsv = File.read('assets/txtdata/sound/effects.tsv')
all = tsv.lines[1...].map {|l| l.split("\t")[0]}
used = Dir['Source/**/*.{cpp,c,h,hpp}'].flat_map do |path|
File.read(path).scan(/SfxID::[A-Za-z0-9]+/).map {|s| s.split('::')[1]}
end
used.concat(%w[
Warrior69b
Sorceror69b
Rogue69b
Monk69b
Swing2
SpellAcid1
OperateShrine1
Warrior14b
Warrior14c
Warrior15b
Warrior15c
Warrior16b
Warrior16c
Warrior2b
Warrior2c
Rogue14b
Rogue14c
Sorceror14b
Sorceror14c
Monk14b
Monk14c
])
used.sort!
used.uniq!
unused = all - used
unused.sort!
File.open('assets/txtdata/sound/effects.tsv', 'w') do |f|
f.write(tsv.lines[0])
tsv.lines[1...].each do |line|
fields = line.split("\t")
if unused.include?(fields[0])
puts fields[2].tr('\\', '/')
else …
```
> Remove unused sounds

- Source/engine/clx_sprite.hpp
- Source/utils/intrusive_optional.hpp
- Source/utils/language.cpp
- Source/utils/string_view_hash.hpp
- uwp-project/devilutionx.vcxproj
1. Adds `dataSize()` to all the CLX sprite classes.
2. Brings intrusive optional closer to `std::optional`.
3. Adds the `unordered_dense` header to the Xbox One build.
> Minor improvements / fixes extracted from #7191

- test/CMakeLists.txt
- test/clx_render_benchmark.cpp
```
----------------------------------------------------------------------------
Benchmark                  Time             CPU   Iterations UserCounters...
----------------------------------------------------------------------------
BM_RenderSmallClx        868 ns          866 ns       802315 bytes_per_second=2.04538Gi/s items_per_second=6.92446M/s
BM_RenderLargeClx     128208 ns       128032 ns         5434 bytes_per_second=716.703Mi/s items_per_second=7.81057k/s
```
> Add a CLX rendering benchmark

- Source/player.cpp
Previously, the same tiles were rechecked over and over again.
O(k^3) -> O(k^2)
This changes the visitation order but we agreed in #7215 that we don't care.
> Speed up DeadItem

- Source/crawl.cpp
- test/crawl_benchmark.cpp
10x faster for radius 20.
Benchmark:
```
cmake -S. -Bbuild-reld -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTING=ON
cmake --build build-reld --target crawl_benchmark && build-reld/crawl_benchmark
```
Before:
```
------------------------------------------------------
Benchmark            Time             CPU   Iterations
------------------------------------------------------
BM_Crawl/1        3.53 ns         3.53 ns    198384032
BM_Crawl/4        54.3 ns         54.2 ns     12907171
BM_Crawl/16        733 ns          732 ns       955101
BM_Crawl/20       1142 ns         1141 ns       613766
```
After:
```
------------------------------------------------------
Benchmark            Time             CPU   Iterations
------------------------------------------------------
BM_Crawl/1 …
```
> Optimize `DoCrawl`

- Source/monster.cpp
Knockback previously didn't update the monster's light source. Also removed some redundant checks since there's a check within the called functions to return early.
> Fix monster light on knockback

- Source/engine/render/clx_render.cpp
- Source/utils/cl2_to_clx.cpp
- Source/utils/clx_decode.hpp
- docs/benchmarking.md
- docs/profiling-linux.md
- tools/build_and_run_benchmark.py
- tools/linux_reduced_cpu_variance_run.sh
On Linux, you can now run:
```
tools/build_and_run_benchmark.py --gperf devilutionx -- --diablo --spawn --lang en --demo 0 --timedemo
```
and get this:
> Add more profiling and benchmarking documentation

- Source/utils/static_vector.hpp
This is enough to make it usable as a backing storage for a `priority_queue`. Had it in one of my branches and figured it might come in handy in the future.
> StaticVector: Add more container methods

- Source/misdat.cpp
- Source/misdat.h
- Source/missiles.cpp
- assets/txtdata/missiles/misdat.tsv
Follow-up to #7312
Refs #7331
Also renames `MissileData` fields to match the TSV.
> Fix Missile Hit Sound

- .gdbinit
- tools/gdb/pretty_printers/utils/static_vector_pp.py
Previously, printing a `StaticVector` in gdb printer the size and the raw bytes of `data_`.
Example of using this pretty-printer:
```
$ gdb -iex 'add-autoload-safe-path .' build/devilutionx
(gdb) b Source/engine/load_file.hpp:126
(gdb) run
(gdb) p files
$1 = devilution::StaticVector<devilution::AssetRef, 6> of length 5 = {{archive = 0x55555c8d7460 <devilution::diabdat_mpq>, fileNumber = 1420,
filename = "monsters\\zombie\\zombien.cl2", directHandle = 0x0}, {archive = 0x55555c8d7460 <devilution::diabdat_mpq>, fileNumber = 1421,
filename = "monsters\\zombie\\zombiew.cl2", directHandle = 0x0}, {archive = 0x55555c8d7460 <devilution::diabdat_mpq>, fileNumber = 1422,
filename = "monsters\\zombie\\zombiea.cl2", directHandle = 0x0}, {archive = 0x55555c8d7460 <devilution::diabdat_mpq>, fileNumber …
```
> Add a `StaticVector` pretty-printer for GDB

- Source/lua/lua.cpp
Error was misleading and made people think it caused devx to shut down
> change log type on missing optional lua assets from error to info

- .lldbinit
- tools/lldbutils/README.md
- tools/lldbutils/lldbutils/__init__.py
- tools/lldbutils/lldbutils/pretty_printers/utils/static_vector_pp.py
#7335 added a pretty-printer for GDB, this one adds it for LLDB.
Example session:
```
$ lldb build/devilutionx
(lldb) target create "build/devilutionx"
Current executable set to '/home/gleb/devilutionX/build/devilutionx' (x86_64).
(lldb) b Source/engine/load_file.hpp:126
* thread #1, name = 'devilutionx', stop reason = breakpoint 1.1
frame #0: 0x0000555558a8145d devilutionx`devilution::MultiFileLoader<6>::operator(this=0x00007ffff1cd0430, numFiles=5, pathFn=0x00007ffff1cd0540, outOffsets=0x00007ffff1cd01c8, filterFn=(unnamed struct) @ 0x00007ffff1e1b080)<devilution::FileNameWithCharAffixGenerator, devilution::(anonymous namespace)::LoadMonsterSpritesData(const devilution::MonsterData&)::<lambda(size_t)> >(size_t, devilution::FileNameWithCharAffixGenerator &&, uint32_t *, (unnamed struct)) …
```
> Add a `StaticVector` pretty-printer for LLDB

- Source/engine/render/dun_render.cpp
A small performance improvement at the cost of ~1 KiB binary size. 1143 -> 1147 FPS on the timedemo
> dun_render: Optimize triangle rendering

- Source/engine/render/scrollrt.cpp
Makes the connection between `foliage` and floor more obvious, see
https://github.com/diasurgical/devilutionX/pull/7327#issuecomment-2294816131.
> scrollrt: Add `IsFloor` function

- Source/CMakeLists.txt
- Source/diablo.cpp
- Source/engine/render/dun_render.cpp
- Source/levels/dun_tile.hpp
- Source/levels/gendung.cpp
- Source/levels/reencode_dun_cels.cpp
- Source/levels/reencode_dun_cels.hpp
Triangles in the dungeon CEL data have 2 redundant 0x00 pixels in every other row. Re-encodes the dungeon CEL data to remove these pixels in order to save RAM and simplify the rendering code.
Example RAM savings:
```
VERBOSE: Re-encoding dungeon CELs: 1,119 frames, 738,836 bytes
VERBOSE:  Re-encoded dungeon CELs: 1,119 frames, 722,552 bytes
```
Performance remains the same. The rendering code is now a bit simpler.
> Re-encode dungeon tiles to remove bloat

- Source/levels/reencode_dun_cels.cpp
The final line wasn't encoded correctly.
Also removes unnecessary `src` increments at the end of the encoding functions.
Follow-up to #7349
Fixes #7351
> Fix `ReencodeDungeonCelsLeft/RightTriangle`

- Source/diablo.cpp
- Source/levels/gendung.h
- Source/lighting.cpp
- Source/lighting.h
- Source/mpq/mpq_reader.cpp
- docs/benchmarking.md
- test/CMakeLists.txt
- test/dun_render_benchmark.cpp
- tools/build_and_run_benchmark.py
Results from a single run (a bit noisy) on my machine:
```
tools/build_and_run_benchmark.py dun_render_benchmark
```
```
Render<LeftTriangle, Solid, FullyLit>                     19699 ns        19698 ns        35517 items_per_second=15.0775M/s
Render<LeftTriangle, Solid, FullyDark>                    20876 ns        20872 ns        34207 items_per_second=14.2298M/s
Render<LeftTriangle, Solid, PartiallyLit>                103195 ns       103163 ns         6784 items_per_second=2.87894M/s
Render<LeftTriangle, Transparent, FullyLit>              104028 ns       104004 ns         6727 items_per_second=2.85567M/s
Render<LeftTriangle, Transparent, FullyDark>             105041 ns       105018 ns         6666 items_per_second=2.82808M/s
Render<LeftTriangle, Transparent, PartiallyLit> …
```
> Add dun_render_benchmark

- Source/engine/render/dun_render.cpp
Rather than relying on the compiler to do it, which doesn't always happen, we do it by hand.
Previously, very slightly different versions of the code could result in those loops not being unrolled (such as in the current master).
I've run the benchmark like this:
```bash
BASELINE=dun-benchmark
BENCHMARK=dun_render_benchmark
git checkout "$BASELINE"
tools/build_and_run_benchmark.py -B "build-reld-${BASELINE}" --no-run "$BENCHMARK"
git checkout -
tools/build_and_run_benchmark.py --no-run "$BENCHMARK"
tools/linux_reduced_cpu_variance_run.sh ~/google-benchmark/tools/compare.py -a benchmarks \
"build-reld-${BASELINE}/${BENCHMARK}" "build-reld/${BENCHMARK}" \
--benchmark_repetitions=10
```
Benchmark results from the first commit are here: …
> dun_render: Unroll triangle loops

- test/dun_render_benchmark.cpp
```bash
tools/build_and_run_benchmark.py dun_render_benchmark -- \
--benchmark_filter='.*BlackTile.*' \
--benchmark_repetitions=10 \
--benchmark_display_aggregates_only
```
```
------------------------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------
BM_RenderBlackTile_mean          157 ns          157 ns           10 items_per_second=6.37889M/s
BM_RenderBlackTile_median        157 ns          157 ns           10 items_per_second=6.38348M/s
BM_RenderBlackTile_stddev      0.490 ns        0.487 ns           10 items_per_second=19.8345k/s
BM_RenderBlackTile_cv           0.31 %          0.31 %            10 …
```
> dun_render_benchmark: `BM_RenderBlackTile`

- Source/player.cpp
`isValid` can be set to false initially, removing the need for a case for `SpellType::Invalid`, as if all the previous conditions are not met, `isValid` will remain false.
> Optimize StartSpell()

- Packaging/nix/devilutionx.metainfo.xml
This is a backport of ba5a9d698f16e054a04e9943b95df038f0c0dbf0 from [1.5 branch](https://github.com/diasurgical/devilutionX/tree/1.5) into `master`
> Add 1.5.3 release notes to metainfo

- Packaging/miyoo_mini/setup_toolchain.sh
Looks like the 1.5.3 release build failed because smpq was missing (https://github.com/diasurgical/devilutionX/actions/runs/10645902045)
> miyoo_mini/setup_toolchain.sh: Install smpq

- .github/workflows/xbox_one.yml
Looks like GitHub Windows image no longer comes with gettext, so now we install it ourselves.
Fixes #7392
> Xbox One: Install gettext to build translations

- CMake/Assets.cmake
> Assets.cmake: Add the Turkish fonts in all sizes

- Source/misdat.cpp
- Source/missiles.cpp
- Source/missiles.h
- assets/txtdata/missiles/misdat.tsv
Fixes: https://github.com/diasurgical/devilutionX/issues/7205
Fixes the problem where wall spells create visible missiles that overlap in the center of the wall, resulting in double damage.
> Fix visually overlapping sprites for wall spells

- Source/missiles.cpp
Fixes: https://github.com/diasurgical/devilutionX/issues/7323
@NiteKat enjoy
Completely removes the check for objects when attempting to find a valid position for Fire Wall/Lightning Wall. Seems rather absurd that objects force walls to move to another position, but the wall will happily grow over objects.
> Fix Wall Spells on objects

- Source/itemdat.h
- Source/items.cpp
- Source/items.h
- Source/lua/modules/dev/items.cpp
- test/CMakeLists.txt
- test/items_test.cpp
I tried to create some debug items for testing (with `dev.items.spawn`) and sometimes I encountered an infinite loop in `TryRandomUniqueItem`.
After some debugging I found out that it is trying to generate one of the following unqiues
- The Grandfather
- Schaefer's Hammer
- Amulet of Warding
The problem can be reproduced with debug lua commands `dev.items.spawnUnique` command and one of the above uniques.
The cause was that the `uid` offset was not always calculated correctly. There are two reasons why this can happen
1. The valid uniques in `CheckUnique` and `TryRandomUniqueItem` can be different because the check against `UIMinLvl` is different (`CheckUnique` calculates it with `GetItemBLevel` and `TryRandomUniqueItem` has a custom implementation). So the calculated offset can be …
> Fix infinite loop in unique item randomization

- Source/inv.cpp
Builds on #7064, also fixes #5076
> Simplify logic when trying to autoequip a two handed item

- Source/inv.cpp
Trying to unpick the code to the point I can safely allow shift-clicking to do an in-place swap when equipping (by actually removing the item from the inventory when it gets moved to `holdItem`)
> Dedupe/tidy up CheckInvCut

- Source/player.cpp
Removes the logic that mimics the Hellfire oversight that resulted in mixing faster attack speeds giving undesirable or confusing results. Reduces amount of lines in code maintaining vanilla Diablo logic.
> Clean up and revise StartAttack()

- Source/monster.cpp
Gharbad and Zhar the Mad can keep changing their rolls in Single Player by doing anything that advances the random seed, and then talking to them. Exploitable behavior using save/load game. We set the monster seed, and then roll a new seed to avoid situations where killing the monsters drops a dupe of the item they previously gave you.
> Fix undeterministic Item Generation

- Source/items.cpp
Fixes: https://github.com/diasurgical/devilutionX/issues/7304
Bug 1: Magic Rock isn't animated while on the stand
Bug 2: Magic Rock drops to the ground with full inventory upon attempted pickup, rendering behind the stand
Note: We can't cycle back to frame 10 from frame 20 during the elevated frames animation, because `processAnimation` will reset the `currentFrame` to 0 if the `currentFrame` is greater than or equal to the total number of frames (20). This would make the rock appear to be bouncing up and down.
Additionally, I added a enumeration for `_iSelFlag` for disambiguation.
https://github.com/user-attachments/assets/0b66f4b0-bd85-4b3d-9d7b-3e305c1baeb3
> Fix Magic Rock related bugs

- Source/control.cpp
- Source/control.h
- Source/controls/plrctrls.cpp
- Source/controls/touch/renderers.cpp
- Source/engine/render/scrollrt.cpp
- Source/panels/mainpanel.cpp
- Source/player.h
Notes:
- HPPer changed from 80 to 81. The globes have 81 rows of pixels that can be filled.
- Buttons had their positions/sizes scattered around as magic numbers, and resulted in some inconsistencies, so this was resolved, which broke the time demo.
- Fixed flasks always showing an empty row of pixels even with full globes.
- Empty flasks above the panel are slightly larger than the filled flasks, resulting in strange visuals when the globe is changing fill level. I modified them to always draw the empty part entirely, and then draw the filled part, if applicable.
All of this should make it entirely easier to mod the control panel without having to play around with magic numbers in many functions.
> Cleanup panel code (Part 1)

- Source/engine/random.cpp
- Source/engine/random.hpp
- Source/loadsave.cpp
- Source/msg.cpp
- Source/multi.cpp
- Source/multi.h
- Source/stores.cpp
- test/random_test.cpp
Implements the technique for mitigating overlapping random number sequences described in https://github.com/diasurgical/devilutionX/pull/6438#discussion_r1285147193.
Summary of changes:
* Introduce the xoshiro128++ RNG
* Rename `GenerateSeed()` to `GenerateRandomNumber()`
* Use xoshiro128++ to reimplement `GenerateSeed()`
* Rename `GameData::dwSeed` to `GameData::gameSeed`
* Use 64 bits for the game seed and use `std::chrono` to generate it
* Update logic for generating dungeon seeds using xoshiro128++ instead of LCG
The 32-bit overload for `xoshiro128plusplus::seed()` is intended to provide a way to reseed xoshiro128++ using a dungeon seed. This will become necessary to create a deterministic sequence of seeds for monsters, objects, and items during dungeon generation. It feels a bit …
> Introduce xoshiro RNG to generate dungeon seeds

- Source/engine/assets.hpp
Adds a bit of text for the end user to get a bit of context on what the problem is, so that they might be able to solve the problem on their own without additional support.
> Revise FailedToOpenFileError

- Source/engine/render/scrollrt.cpp
- Source/panels/charpanel.cpp
- Source/player.cpp
- Source/spells.cpp
Corruption behaves very strangely, and can result in the player still having mana values greater than 0, and the player is still able to cast spells. This PR fixes that by visually setting mana and max mana to 0 without modifying the actual values. In addition, spells will fail to cast if this item power is active (Fails mana check), and Mana Shields will be forcefully removed. As a failsafe, there is a check to make sure there is no Mana Shield damage reduction if this item power is active.
On a side note, this item power appears to have very inconsistent behavior when it comes to restoration of mana. There are sources that normally restore mana that will no longer (Reading books, leveling up, using potions), and sources that still restore mana (Cryptic shrine, and some other shrines). …
> Bugfix: Corruption item power

- Source/missiles.cpp
- Source/monster.cpp
- Source/player.cpp
Refactors damage calculations from the format:
`damage = min + rnd(max - min + 1)`
to:
`damage = randombetween(min, max)`
Also fixes a bug in some damage calculations, where max damage in the range is 63/64th lower than it should be.
> Bugfix/Refactor: Min-Max Damage Range Calculations

- Source/cursor.cpp
- Source/engine/render/scrollrt.cpp
- Source/engine/render/scrollrt.h
In an effort to address this issue link: https://github.com/diasurgical/devilutionX/issues/1995
Refactored lots of functionality out into helper functions in cursor.cpp, small tweaks, but no big change to logic
This is my first ever pull request, hoping to just get a bit of practice before I make a bigger contribution! (Tips and suggestions would be much appreciated)
> Refactor: Check_Curs_Move (Issue: 1995)

- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
- Source/msg.cpp
- Source/player.cpp
This fixes the problem with knockback. Knockback always pushes monsters in the opposite direction that the monster is facing. This can result in monsters being pushed in the wrong direction if they aren't facing the attacking player/missile.
Melee attacks and Telekinesis will calculate a direction based on the player tile and monster future tile upon initiating knockback.
Missiles will calculate a direction based on the missile start tile and monster future tile upon initiating knockback.
> Fix Knockback

- Source/loadsave.cpp
- Source/missiles.cpp
- Source/missiles.h
- test/fixtures/memory_map/missile.txt
`_mirange` is a bit confusing. `duration` adequately describes what the missile is used for, as the intent is the amount of ticks the missile exists for, often decremented every tick until it hits 0, when the missile is destroyed.
> Rename Missile::_mirange to Missile::duration

- Source/control.cpp
> fix warnings

- Source/hwcursor.cpp
Credit to @StephenCWills
>Maybe we're not drawing the item CEL in the right spot. Actually.. that might be exactly what the problem is.
If the graphic is 84 pixels tall, and you draw it with the top-left corner at (0,0), then you'd expect it to place pixels between y-coordinates 0 and 83 inclusive.
But CELs draw from the bottom-left. So drawing at (1,85) suggests you assume it won't be including y-coordinate 85, but that doesn't make sense. It would probably then occupy y-coordinates between 2 and 85, not 1 and 84.
> Fix RenderClxOutline OOB Draw

- Source/engine/render/clx_render.cpp
Follow-up to #7429 
I noticed yesterday that the bounds check here wasn't including the extra space around the sprite in which the outline would be rendered. That's part of the reason we encountered an OOB instead of falling through to the `else` clause which would have done the bounds check inside the `for` loop.
> Fix bounds check in RenderClxOutline()

- Source/capture.cpp
- Source/utils/surface_to_pcx.cpp
- Source/utils/surface_to_pcx.hpp
- Source/utils/surface_to_png.cpp
- Source/utils/surface_to_png.hpp
Turns out `SDL_RWFromFP` isn't implemented in SDL for mingw.
Follow-up to #7176
> Screenshotting: Use `SDL_RWops` throughout

- Source/engine/render/scrollrt.cpp
`dev.display.grid()` previously tanked the FPS even on my beefy machine. It is now much faster.
I've also noticed that the grid is glitchy when moving up/down but this is also the case before this PR.
Before | After
---|---
> Speed-up debug grid

- Source/inv.cpp
With this change 2x2 items are placed from the right in a similar fashion to 2x3 items (the search progresses across the inventory one column at a time instead of checking even columns then odd columns).
Relates to #7028
> Remove special case when auto-placing 2x2 items

- Source/debug.cpp
- Source/debug.h
- Source/lua/modules/dev/display.cpp
> Add `dev.display.tileData('microTiles')`

- Source/engine/render/scrollrt.cpp
- Source/levels/gendung.cpp
- Source/levels/reencode_dun_cels.hpp
Stairs can have the same `TileProperties` as floors but do not always follor the same graphics layout as floors, so we shouldn't apply optimizations to them.
The only stairs that are affected seem to be:
1. Hell: tile 46 sub-tile 141 frame 386 (TileProperties: BlocksMissile)
2. Caves: tile 48 sub-tile 171 frame 461 (TileProperties: None)
Note that the few broken in pixels in caves are actually incorrectly attributed to the non-Solid tile, really they should be part of the solid tile 49.
As there doesn't seem to be a quick and easy way to check if a frame is part of Stairs, we add a check for BlocksMissile tile property instead.
This fixes Hell but isn't enough to fix Caves.
To fix Caves, we then add a `BlocksMissile` flag to the broken sub-tile.
Fixes #7420
Broken hell tile:
Broken caves …
> Fix stairs rendering in Caves and Hell

- Source/options.cpp
- Source/utils/display.cpp
This is perhaps the easiest option to address the ever-increasing number of platforms that crash when toggling this setting. SDL just doesn't want us to do it.
This resolves #4421
This resolves #5168
This resolves #6387
> Hide Upscale option in Settings menu

- Source/storm/storm_svid.cpp
SMK format actually defines frame durations in units that are 1ms or 0.01ms:
https://github.com/diasurgical/libsmackerdec/blob/91e732bb6953489077430572f43fc802bf2c75b2/src/SmackerDecoder.cpp#L329-L334
That's great because it means we can do everything using integer math.
> Videos: Avoid float math for frame durations

- Source/controls/touch/gamepad.cpp
- Source/engine/palette.cpp
- Source/monster.cpp
- Source/utils/sdl2_to_1_2_backports.cpp
Looks like the KallistiOS Dreamcast SDK disables double support by default: https://github.com/KallistiOS/KallistiOS/blob/495e77fd60d5b09a1ad52a26cd4a7e73cd0d9d51/environ_dreamcast.sh#L16
We don't really need doubles in this code.
The one place where we might have needed them is the SMK video decoder, handled in a separate PR (#7454).
/cc @azihassan I'm not entirely sure but perhaps this will help with https://github.com/azihassan/devilutionX/issues/8
> Replaces uses of doubles with floats

- .github/workflows/Windows_MinGW_x64.yml
failed to get tolk to build/work locally, deleting it seems to be the best way :D
> delete libTolk.dll from artifacts uploaded to artifacts-storage repo

- Source/engine/render/scrollrt.cpp
- Source/items.cpp
- Source/panels/charpanel.cpp
- Source/player.cpp
Fixes: https://github.com/diasurgical/devilutionX/issues/6520
This PR fixes problems related to Life and Mana regarding negative numbers.
- Max Life will never go under 1 (Fixes town death bug)
- Max Mana will never go under 0 (I would have outright removed ALL negative numbers for life and mana, however it's absolutely essential to keep a relative relationship between Current Mana and Max Mana to avoid having Current Mana changed when equipping and unequipping items)
- Current Mana visually appears to never go under 0 to the player (Not able to actually set Current Mana to 0, since this would allow the player to exploit this mechanic and fully restore their Mana.)
- Current Life and Current Mana can no longer exceed Max Life and Max Mana
The fixes to Max Life and Max Mana will not cause …
> Fix Life/Mana bugs

- Source/items.cpp
- Source/player.cpp
This function is an unnecessary burden for the game to keep checking every frame if the current stats are valid. Instead we should clamp them when there's an item change.
This won't prevent players from cheating via memory editing their stats to the degree `CheckCheatStats()` would, however we have validation code for this sort of cheating to prevent cheaters from playing with others.
Life and Mana clamp exists in https://github.com/diasurgical/devilutionX/pull/5777
> Remove CheckCheatStats()

- Source/monster.cpp
Fixes: https://github.com/diasurgical/devilutionX/issues/7463
`PlaceUniqueMonst()` is a function that does what the name suggests, with logic as follows:
1. Find a random valid location to place the unique monster, assigning the chosen valid location to `position`
2. If the monster is a quest unique monster, overwrite `position` with a set location
3. Complete setting up the unique monster data and place it in the map
While this may not be *the* fix for the linked issue report, this does change the order of operations, to prevent running the loop to find a spawn location for monsters that already have a predefined location. Since these quest monsters have a very specific location, typically involving set pieces or set levels, their spawning conditions are predetermined to be valid, and we …
> Prevent PlaceUniqueMonster() loop from finding random location for quest monsters with a set position

- Source/monster.cpp
Fixes: https://github.com/diasurgical/devilutionX/issues/7463
Moves the function calls for placement of Lazarus related quest monsters from within `SetMapMonsters()` to `PlaceQuestMonsters()`
> Move Lazarus spawn code

- Source/diablo.cpp
This PR breaks up `LoadGameLevel()` into several functions, to make it more readable. Originally, this function is obscenely long and hard to follow. I was extremely careful to not rearrange any function calls to avoid introducing any bugs.
> Cleanup LoadGameLevel()

- Source/controls/touch/gamepad.cpp
Fixes these warnings, highlighted by GitHub's nifty beta feature.
> Fix double to float conversion warnings in virtual gamepad logic

- Source/utils/sdl_compat.h
When the display surface is 8-bit, skips a redundant call to `SDL_SetPalette`.
/cc @azihassan https://github.com/azihassan/devilutionX/issues/14
> SDL1: Avoid redundant palette update

- Source/lua/lua.cpp
**user.lua**:
```lua
require('test')
```
---
**test.lua**:
```lua
print(os.date())
```
---
Error:
```
ERROR: Lua error: stack index 2, expected function, received table: value is not a function and does not have overriden metatable (bad argument into 'void(const sol::basic_environment<sol::basic_reference<0> >&, const sol::basic_function<sol::basic_reference<0>,0>&)')
stack traceback:
[C]: in function 'base.setEnvironment'
[string "..."]:7: in global 'require'
[string "lua\user.lua"]:1: in main chunk
```
This happens because the arguments to `setEnvironment()` are backwards. Furthermore, we shouldn't try to call `setEnvironment()` if `loader` is a string, since it expects a function.
> Fix error in Lua require() function

- Source/monster.cpp
Backport for #7449 on the 1.5 branch
> [1.5] Wake up the whole pack of Gargoyles when disturbed

- Source/control.cpp
- Source/engine/point.hpp
- Source/inv.cpp
- Source/inv.h
- Source/items.cpp
- Source/player.cpp
- Source/qol/autopickup.cpp
- Source/qol/stash.cpp
- Source/stores.cpp
Cleanups that I found useful when prepping for in-place swapping.
This shouldn't change any behaviour but I haven't tested further than making sure shift-clicking equipped items still worked.
> Extract logic from CheckInvCut/AutoPlaceItemInInventory

- Source/inv.cpp
New behaviour:
https://github.com/user-attachments/assets/3b7ab495-59f9-4315-a986-18a8b876c40d
Main thing of note is the item that used to be equipped will fill the gap left by the item being equipped if it fits.
Commit 2324108386c74758f20745a932768a2917a12bb5 is some prep that made it easier to reason about the steps required, I tried to keep the same behaviour/sound feedback. What I was attempting to show at about 10 seconds into this clip was trying to equip the short sword when there's no room to remove the two-handed sword would play the "I have no room" speech but the screen recording didn't capture sound :(
This builds on #7494, I've split them to hopefully make things easier to review.
> Allow auto-equipping items when the inventory item frees space for the equipped item

- Source/monster.cpp
~~Not tested, but~~ this looks like the right place to reintroduce the logic.
This resolves #7448
> Wake up the whole pack of Gargoyles when disturbed

- Source/diablo.cpp
- Source/items.cpp
- Source/items.h
Vanilla called `InitItemGFX()` in `LoadGameLevel()` when `firstflag == true`.
https://github.com/diasurgical/devilution/blob/bbda8dd586c65b03028ec75c52f8ea8627eb9ff5/Source/diablo.cpp#L1845
In DevilutionX, this call to `InitItemGFX()` was moved to game client startup, and also when changing various settings.
Startup:
https://github.com/diasurgical/devilutionX/blob/d8dde8d2b119dfbc7973384aa598bd9e9de2c864/Source/diablo.cpp#L1217-L1218
Changing settings:
https://github.com/diasurgical/devilutionX/blob/d8dde8d2b119dfbc7973384aa598bd9e9de2c864/Source/DiabloUI/settingsmenu.cpp#L211-L214
This function had side effects with regard to the unique item drop table. This PR simply moves those side effects to its own function and invokes it in the same place vanilla does.
> Clear unique item flags in LoadGameLevel()

- Source/diablo.cpp
- Source/items.cpp
- Source/items.h
> [1.5] Clear unique item flags in LoadGameLevel()

- .github/workflows/amiga-m68k.yml
- CMake/platforms/amiga.cmake
- Packaging/amiga/Dockerfile
1. Updates the Dockerfile to the same image and flags as the CI.
2. Sets `-O2` as the default CMake Release flag rather than passing it in a custom way.
This fixes building by following the instructions in building.md.
/cc @arczi84
> Update Amiga build configs

- Source/engine/render/scrollrt.cpp
- Source/player.cpp
- Source/player.h
1. Do not draw foliage with the pause trn.
2. Display the number of steps.
3. If the tile is not walkable (allowed for destination tile), display the number of steps in yellow.
> Improve `dev.display.path()`

- Translations/pl.po
- tools/validate_translations.py
👋 Please review the following changes for Polish translations.
Synchronizing the `pl.po` file -- this is the large portion of this pull request:
* 650f3c6e Sync pl.po to source code.
Different small updates here and there:
* f572b243 Update store label translations.
* b82d6c3a Consistent translations for "armor" and "armor class".
* fa29ba97 Chat log translations.
* 642c1743 Quick spell translations.
* f9648a9d Inventory sorting translations.
* ad9fb102 Debug commands translations.
* 7adb2529 Player inspection translations.
* 8ffaf347 Button combo bindings translation.
* 4cf2505d Change "żywotność" to "witalność" so it flows better in character stats screen.
* a3af9495 Fix "U.S. Sales" translation.
* b3fe044d Improve the validate_translations.py script.
* 78a018ba Shorten Experience …
> Update Polish translations.

- .github/workflows/Android.yml
- 3rdParty/SDL2/CMakeLists.txt
- android-project/app/build.gradle
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- android-project/build.gradle
* Use SDL2 2.30.9
* Use Android Gradle plugin 8.7.2
* Use latest NDK 28
* Use latest CMake 3.31.0 for configuration
WARNING! **Testing on real devices needed before merging**, due to NDK upgrades. I have verified everything works on Pixel 8 Pro via emulator, but nothing beats real device testing
> Android major upgrades

- Source/engine/dx.cpp
Fixes the following error that intermittently occurs when exiting the game while debugging with Visual Studio.
> At shutdown, free surfaces and textures allocated for virtual gamepad graphics

- Source/player.cpp
Currently, if the player holds right click with Teleport selected, this causes the game to select a tile as the Teleport target, and then select the same tile as the queued Teleport target, resulting in the player casting every other Teleport with no movement.
This PR does the following:
If the player is casting Teleport and the new target tile is the same as the currently targeted tile (or any nearby tile) by the currently executed Teleport spell, get the relative distance between the player and the new target tile, and add that to the currently executed tile, then Teleport the player there instead.
This allows the player to keep the mouse still and continuously queue Teleport to move in a direction. However, this does not work consistently if the player is moving the mouse around while …
> Revise Teleport Target

- Source/itemdat.cpp
- Source/itemdat.h
- Source/items.cpp
- Source/objects.cpp
- assets/txtdata/items/itemdat.tsv
- test/items_test.cpp
Bit of an experiment, this does include a behaviour change/fix. If the RNG seed lines up that the call to GenerateRnd returned a negative value it previously would've read out-of-bounds and returned that value as an item index, leading to further out-of-bounds reads in GetItemAttrs.
Apart from that behaviour should be exactly the same. The timedemo still passes at least :D
> Allow for item drop rates up to 255

- Source/dvlnet/base_protocol.h
`strnlen` is not available on some platforms, such as macOS 10.4.
> Avoid `strnlen`

- Source/dvlnet/base_protocol.h
`strnlen` is not available on some platforms, such as macOS 10.4.
> Avoid `strnlen` (for 1.5)

- Source/engine/animationinfo.cpp
- Source/engine/animationinfo.h
Fixes: https://github.com/diasurgical/devilutionX/issues/7509
> Fix divide-by-zero crash in `getAnimationProgress()`

- Source/options.cpp
- Source/utils/display.cpp
Backport for #7443 on the 1.5 branch
> [1.5] Hide Upscale option in Settings menu

- .github/workflows/PS4.yml
Switches from `pacbrew-pacman` to vanilla pacman that is now an Ubuntu package (`pacman-package-manager`) starting from Ubuntu 24.04.
pacbrew-pacman from https://github.com/PacBrew/pacbrew-pacman/releases is 2 years old and has the repo URL that no longer works. With the vanilla pacman, we simply add pacbrew as a repo source with the correct URL.
Refs https://github.com/PacBrew/pacbrew-packages/issues/6
@Cpasjuste does this look right to you?
> Fix PS4 workflow

- Source/items/validation.cpp
We can't validate price on Wirt's items or Griswold's premium items in Hellfire because shop manipulation can drive these vendors to sell items above their price limit.
> Revert changes to price validation logic in cfac786

- Source/items/validation.cpp
#7506 introduced calls to item validation into `Player::CanUseItem()` and `CalcSelfItems()` which are functions shared between Single Player and Multiplayer games. The item validation should probably not be applied to Single Player at all because data errors introduced by bugs in vanilla can make their way into DevilutionX via the item data stored in Single Player savegames. Those data errors can cause items to appear invalid when they actually aren't.
Note that the steps to reproduce described in #7561 will no longer work after incorporating this fix.
> Do not apply item validation to Single Player games

- Source/multi.cpp
#7030 removed the logic that combines the town seed with `SDL_GetTicks()` because the `GenerateSeed()` function that uses the xoshiro generator was applied to town seed rotation in `SaveLevel()` and `DeltaLeaveSync()`. However, the initial town seed is still dependent on the game seed, meaning players who join the same Multiplayer game session will have the same initial set of shops. This PR further applies the xoshiro generator to the initial town seed to fix that blind spot.
> Divorce town seed from game seed

- Source/monster.cpp
Backport for both #7464 and #7465 on the 1.5 branch
> [1.5] Clean up PlaceUniqueMonster() position logic

- Source/loadsave.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
For context, refer to https://github.com/diasurgical/devilutionX/discussions/7433#discussioncomment-10766611 and the comments that follow.
Because monster order has changed between vanilla and the current version of DevilutionX, we can't rely on the fact that monster `toHit` was already initialized. Otherwise, we will end up using the wrong monster's `toHit` value if we load a vanilla savegame.
It seems the reason we don't use the value from the save file is because we don't want to inherit erroneous values from vanilla due to the bug that applies difficulty bonuses twice. In that case, it's better to compute the value on the fly, like with `Monster::level()`.
However, we can't entirely do away with the `toHit` variable because a Golem's hit chance depends on the player character's stats …
> Compute monster toHit on the fly

- Source/loadsave.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
Backport for #7567 on the 1.5 branch
> [1.5] Compute monster toHit on the fly

- Source/missiles.cpp
This resolves an issue where Runes could be used to PK another player and have them drop their equipment as if they had been killed by a trap or monster.
---
`TARGET_BOTH` is only used for a handful of missiles:
* Fire Wall
* Lightning Wall
* Ring of Fire
* Runes
* Phasing
For Fire Wall, Lightning Wall, and Ring of Fire, we were already checking `missile.IsTrap()` which is equivalent to `missile.sourceType() == MissileSource::Trap`. Therefore, the behavior after the change should match what we were doing before. Phasing is harmless, so the only real change is that Rune missiles will now also use `DeathReason::Player`.
This logic also just makes more sense compared to the special case for Fire Wall and Lightning Wall.
> Check missile source type to determine death reason

- Source/missiles.cpp
Backport for #7486 on the 1.5 branch
> [1.5] Check missile source type to determine death reason

- Source/DiabloUI/selstart.cpp
- Source/diablo.cpp
- Source/options.cpp
- Source/options.h
Over time, many users have been confused as to how to switch between Diablo and Hellfire. This simplifies it.
> Move Game Mode to own category

- tools/build_and_install_smpq.sh
1. Tiger's tar does not support `--strip-components`.
2. Tiger predates `getconf _NPROCESSORS_ONLN` support.
3. Tiger's default `cc` is too old to build smpq, so we default to `CC=gcc` instead (e.g. from macports).
We also bump stormlib version because the previous one fails to compile with gcc14 on Tiger.
> build_and_install_smpq.sh: Tiger compatibility

- Source/diablo.h
- test/drlg_l1_test.cpp
- test/drlg_test.hpp
- test/main.cpp
- test/timedemo_test.cpp
- test/writehero_test.cpp
1. Load assets from the bundle on Mac.
2. In timedemo_test, load MPQs before overriding pref path, so that they can also be loaded from the user/system location.
3. Fix various double directory separators ("build//assets" etc).
Also fixes running drlg test directly (e.g. `build/drlg_l1_test`, as opposed to via ctest) -- the latter runs an individual process for each test but in the former we weren't resetting `LevelSeeds` so when running multiple tests from the same process the later tests were failing.
> Test paths fixes

- docs/building.md
* `devkitpro-pkgbuild-helpers` no longer exists
* `3ds-bzip2` is a newer requirement
* Steveice10 removed his bannertool repo from existence
> Fix building instructions for Nintendo 3DS

- Source/controls/plrctrls.cpp
Should improve gamepad control in stash, see #7019
First time contribution, so be gentle :)
> improve gamepad stash control, fix #7019

- Source/CMakeLists.txt
- Source/items.cpp
- Source/items.h
- Source/items/validation.cpp
- Source/items/validation.h
- Source/loadsave.cpp
- Source/pack.cpp
- Source/pack.h
- Source/player.cpp
- Source/player.h
- Source/stores.cpp
- test/missiles_test.cpp
- test/player_test.cpp
- test/player_test.h
- test/stores_test.cpp
Backports for #7506, #7560, #7562, and #7565 on the 1.5 branch
> [1.5] Make invalid items unusable

- Source/stores.cpp
The game was already storing the adjusted price of the item in `TempItem` rather than `BoyItem`. All we really need to do is transfer `BoyItem` to the player's inventory instead of `TempItem`.
Note that this does have the very minor effect of diminishing the resale value of Wirt purchases in Diablo while boosting the resale value in Hellfire. That said, you're selling the item back at a loss regardless. Furthermore, even without this change, the resale value of Wirt purchases would go back to normal after regenerating the item anyway.
This resolves #7561
> Fix value of items bought from Wirt's shop

- .gitignore
- Source/controls/plrctrls.cpp
Builds on #7551 to fix the second and third point in #4270. Doesn't fully address that issue as moving into the inventory while holding an item still leaves the cursor overlapping the top edge of the inventory.
> Improve moving to the inventory/body using a gamepad

- Source/storm/storm_svid.cpp
I'm testing it on platform which operates on RGB565 soly (sdl-directfb) and without this patch we get incorrect menu graphics. Moreover if you not define correct DISPLAY_TEXTURE_FORMAT before compiling, then SDL_HINT_RENDER_SCALE_QUALITY have no effect for DirectFB and the default value is picked by render for all scaling options.
BTW: Compiled via `1.5` branch because our older gcc 9.4.0 doesn't support `std::span`, so I've small request to cherry-pick this and c2ad6da733de93f817bc7a66d0c0eb49a5540ed4 commit to stable branch 🙏
> storm_svid: use DISPLAY_TEXTURE_FORMAT also for SVidPlayEnd

- .github/workflows/Windows_MSVC_x64.yml
- vcpkg.json
Since all other platforms upgraded too
@AJenbo should this be backported to 1.5?
> Upgrade vcpkg baseline commit to upgrade SDL to 2.30.10

- test/path_test.cpp
> path_test: Improve failure messages

- Source/DiabloUI/diabloui.cpp
- Source/diablo.cpp
When using HAS_KBCTRL flag, fullscreen hotkey should be avoided IMO (end-user don't expect them to happen on gamepad as well). Generally I wouldn't mind leaving it as it was, but there is weird event happening in DialogUI when only left alone LALT is pressed and game switches between Fullscreen/Windowed mode, so there may be smth more to look in [PressKey()](https://github.com/diasurgical/devilutionX/blob/72d8a56d1be4880a75e00a4a9e4974d3c005ccdb/Source/diablo.cpp#L564).
@AJenbo, compiling it for old OE Miyoo devices with F1C100S (ARMv5, 32MB of RAM). I must congratulate for ppl working on this project, cuz the code is very portable even for such obscure platform with little resources 👍 .
> [1.5] events: ignore ALT modifier if using Keyboard-as-Controller

- Source/items/validation.cpp
This PR fixes up the logic in `IsItemValid()` based on the validation logic located in `UnPackNetItem()`.
https://github.com/diasurgical/devilutionX/blob/a12b5368c381cf1c910e77c506345995a149e717/Source/pack.cpp#L443-L457
Prior to this fix, items bought from Wirt by a clvl 50 character would always be unusable, despite `Net Validation` indicating success.
> Don't apply dungeon item validation to town items

- Source/levels/gendung.cpp
A couple of the fence tiles in Caves are not marked as solid, allowing monsters to step forward and attack the player through the fence.
https://youtu.be/1MXi1IV194M
[lava lords fence mele [1MXi1IV194M].webm](https://github.com/user-attachments/assets/3a52f351-b7c6-4cc2-b533-930a28eb7c64)
> Fix nonsolid fence tiles

- Source/levels/gendung.cpp
> Fix tile incorrectly marked as solid next to crypt stairs down

- Source/diablo.h
- Source/engine/assets.cpp
- Source/engine/assets.hpp
- Source/init.cpp
- Source/init.h
- Source/platform/android/CMakeLists.txt
- Source/platform/vita/CMakeLists.txt
Untangles some of the dependencies.
Extracted from #7554
> Move MPQs from init to engine/assets

- Source/lua/lua.cpp
- Source/lua/lua.hpp
- Source/options.cpp
- Source/options.h
- Source/utils/ini.cpp
- Source/utils/ini.hpp
- assets/lua/devilutionx/events.lua
Reads a list of mods from `diablo.ini` and loads `init.lua` scripts based on that list.
---
Example:
```ini
[Mods]
clockmod=1
helloworld=0
scwmod=1
```
The INI configuration above will attempt to execute the following scripts from assets.
* `lua/mods/clockmod/init.lua`
* `lua/mods/scwmod/init.lua`
The value that comes after the name of the mod is simply an "enabled" flag to indicate whether the mod should be loaded. Hence why it does not attempt to load `lua/mods/helloworld/init.lua`.
---
Notes:
* The `devilutionx.events` script was moved to the `LuaReloadActiveMods()` function in preparation for adding a `Settings` menu page to enable/disable mods.
* The `GameBoot` event was replaced with `LoadModsComplete` for the same reason. It's no longer "Game Boot" if the mods were reloaded by …
> Lua mod INI file configuration

- Source/dvlnet/frame_queue.cpp
- Source/dvlnet/packet.h
- Source/engine/load_cl2.hpp
- Source/levels/reencode_dun_cels.cpp
- Source/utils/cel_to_clx.cpp
- Source/utils/cl2_to_clx.cpp
- Source/utils/endian.hpp
- Source/utils/endian_stream.hpp
- Source/utils/endian_write.hpp
- Source/utils/pcx_to_clx.cpp
- Source/utils/surface_to_clx.cpp
Only `endian_write` functions require SDL, splitting them out will allow us to clean up the dependencies a bit.
Extracted from #7554
> Split endian_write from endian

- Source/CMakeLists.txt
- Source/DiabloUI/hero/selhero.cpp
- Source/DiabloUI/mainmenu.cpp
- Source/DiabloUI/selok.cpp
- Source/diablo.cpp
- Source/engine/assets.cpp
- Source/engine/assets.hpp
- Source/game_mode.cpp
- Source/game_mode.hpp
- Source/init.cpp
- Source/init.h
- Source/levels/trigs.cpp
- Source/lighting.cpp
- Source/menu.cpp
- Source/monster.cpp
- Source/monster.h
- Source/options.cpp
- Source/pack.cpp
- Source/panels/spell_icons.cpp
- Source/pfile.cpp
- Source/player.cpp
- Source/player.h
- Source/quests.cpp
- Source/spells.cpp
- Source/stores.h
- Source/towners.cpp
- test/items_test.cpp
- test/pack_test.cpp
- test/timedemo_test.cpp
- test/writehero_test.cpp
Untangles some dependencies
Extracted from #7554
> Extract game mode out of init.cpp

- Source/CMakeLists.txt
- Source/control.cpp
- Source/cursor.cpp
- Source/data/file.cpp
- Source/dead.cpp
- Source/diablo.cpp
- Source/diablo.h
- Source/engine/assets.hpp
- Source/engine/demomode.cpp
- Source/engine/dx.cpp
- Source/engine/load_file.hpp
- Source/engine/palette.cpp
- Source/engine/render/scrollrt.cpp
- Source/gamemenu.cpp
- Source/gmenu.cpp
- Source/headless_mode.cpp
- Source/headless_mode.hpp
- Source/init.cpp
- Source/interfac.cpp
- Source/items.cpp
- Source/misdat.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/qol/stash.cpp
- Source/storm/storm_net.cpp
- Source/utils/display.cpp
- test/main.cpp
- test/timedemo_test.cpp
Untangles some dependencies.
Many places that use `HeadlessMode` do not need all of `diablo.h` (e.g. `assets`, `load_file`)
Extracted from #7554.
> Extract `HeadlessMode` from `diablo.h`

- Source/options.cpp
- Source/options.h
Looks like the settings menu was already functional after the last PR.
This PR adds the `ValueChangedCallback` to reload the Lua mods when adjusting these settings. Tested using a simple Hello World mod.
```lua
local events = require("devilutionx.events")
events.GameStart.add(function()
print("Hello world!")
end)
```
> Reload Lua mods when enabling/disabling

- Source/CMakeLists.txt
- Source/lua/lua.cpp
- Source/lua/modules/i18n.cpp
- Source/lua/modules/i18n.hpp
- assets/lua/repl_prelude.lua
Adds bindings for i18n functions.
Does not yet add support for loading mod-specific translations.
> Lua: Add i18n module

- CMake/functions/object_libraries.cmake
- Source/CMakeLists.txt
- test/app_fatal_for_testing.cpp
Collects transitive object library dependencies in the topological order and adds cycle detection.
Now transitive dependencies are actually all linked.
> CMake: Topsort object library dependencies

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/diabloui.h
- Source/DiabloUI/settingsmenu.cpp
This makes it easier to navigate sections, such as gameplay and keymapping.
1920x1080:
The 720 width makes all the keymapping options fit on a single line. I also tried 800 max width but that places the focused item markers too far from the item text.
> Settings: Use the full height and up to 720 width

- Source/engine/demomode.cpp
- Source/engine/dx.cpp
- Source/options.cpp
- Source/options.h
- Source/utils/display.cpp
Fixes https://github.com/diasurgical/devilutionX/issues/7170
This merges vSync and limitFPS under a new settings that uses an enum, and hides the option from Android users.
- They should never be used at the same time
- Android will silently enable vSync without us noticing
- Having limitFPS on devices that report a lower frequency then the actual display will cause Android to think the application is lagging and kill it after a few minutes.
The reason not to carry over the setting from previous version is that Android users might have set a bad combination, both were on by default and they changed vsync to off they would likely experience the mentioned crash. So to fix any potentially bad settings we reset it to the new default of vsync only.
> Merge limitFPS and vSync options

- Source/diablo.cpp
- Source/items.cpp
- Source/msg.cpp
- Source/msg.h
- Source/player.cpp
This fixes an inconsistency in `CheckNewPath()`. When casting a spell from a standing animation, the spell would use the spell level that was included in the network message. When casting a queued spell immediately after executing another spell, the spell would use the spell level stored in the `Player` struct.
We sync spell levels with the `CMD_CHANGE_SPELL_LEVEL` command, and the game _never_ casts a spell at a different spell level than what is stored in the `Player` struct. There is no real benefit to including the spell level in the spell casting network messages. All it does is allow a hacker to pass whatever spell level they want, as long as they do it from a standing animation.
> Don't send spell level in spell casting network message

- Source/diablo.cpp
- Source/items.cpp
- Source/msg.cpp
- Source/msg.h
- Source/player.cpp
Backport for #7485 on the 1.5 branch
> [1.5] Don't send spell level in spell casting network message

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/hero/selhero.cpp
- Source/DiabloUI/multi/selconn.cpp
- Source/DiabloUI/multi/selgame.cpp
- Source/DiabloUI/settingsmenu.cpp
- Source/DiabloUI/ui_item.h
- Source/options.cpp
1. The char pointer returned by SDL is only valid temporarily, keeping it around is [not allowed](https://github.com/libsdl-org/SDL/blob/aa9b4ec8944461c9f738652f6fe76ad5550a1c33/include/SDL_audio.h#L472-L475) so we copy the string.
2. Moves the trimming to DiabloUI. It now happens every frame but that's OK here (not performance-sensitive and there is  little else happening on that screen).
> Audio device settings: Fix name handling

- Source/options.cpp
- Source/options.h
See #5437
In this case, `ModEntry` isn't an implementation of `OptionEntryBase`, but `OptionEntryBoolean` does take a parameter of type `std::string_view` and so the copy constructor for `ModEntry` was still pulling the rug out from under it.
> Delete copy constructor in ModEntry

- android-project/app/build.gradle
- android-project/app/src/debug/res/xml/shortcuts.xml
1. Android Studio warned that the `applicationIdSuffix` is supposed to start with a period. This doesn't seem to make any difference except to get rid of the warning.
2. The shortcut requires that the `applicationIdSuffix` should be included in the `targetPackage` field of the intent that invokes the `ImportActivity`. Otherwise, I get a message on my Pixel 6a that states the "App isn't installed" when I try to use the shortcut.
> Fix Import Data shortcut in debug builds

- uwp-project/src/SDL_winrt_main_NonXAML.cpp
Backports #6965 into the 1.5 branch
> [1.5] Remove hardcoded SDL controller mapping from UWP build

- Source/CMakeLists.txt
- Source/controls/padmapper.cpp
- Source/options.cpp
- Source/options.h
- Source/utils/display.cpp
- test/CMakeLists.txt
Untangles the last remaining option dependencies, allowing us to turn `data_file_test` into a standalone test that only depends on a small subset of devilutionx.
> data_file_test: Make it a standalone test

- Source/CMakeLists.txt
- Source/controls/plrctrls.cpp
- Source/engine/path.cpp
- Source/engine/path.h
- Source/engine/render/scrollrt.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/levels/themes.cpp
- Source/levels/tile_properties.cpp
- Source/levels/tile_properties.hpp
- Source/lua/modules/dev/monsters.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/objects.cpp
- Source/player.cpp
- test/CMakeLists.txt
- test/path_test.cpp
- test/tile_properties_test.cpp
1. Makes `path.cpp` concerned solely with the pathfinding algorithm.
2. Turns `path_test` into a standalone test.
> Untangle pathfinding dependencies

- Source/DiabloUI/settingsmenu.cpp
- Source/diablo.cpp
- Source/engine/events.cpp
- Source/options.cpp
- Source/options.h
- Source/panels/spell_list.cpp
Most of #6861 except the actual quick spell cycling feature (can be backported separately in a follow-up PR if we want to) + 41189060ef221b9d560fc5e23fec48e5fd804205 for 1.5
> [1.5] Add scroll wheel support to keymapper

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/diabloui.h
- Source/DiabloUI/settingsmenu.cpp
This makes it easier to navigate sections, such as gameplay and keymapping.
Backport of #7645 for the 1.5 branch
> [1.5] Settings: Use the full height and up to 720 width

- test/CMakeLists.txt
- test/path_benchmark.cpp
Example run:
```
$ tools/build_and_run_benchmark.py path_benchmark
--------------------------------------------------------
Benchmark              Time             CPU   Iterations
--------------------------------------------------------
BM_SinglePath       2905 ns         2905 ns       241038
BM_Bridges         65951 ns        65948 ns         9785
BM_NoPath         131397 ns       131390 ns         5247
```
> Add a pathfinding benchmark

- Source/mpq/mpq_writer.cpp
Lifted from pionere's fork: https://github.com/pionere/devilutionX/commit/7866861cf2a264f8101a51078f10a56048e65c09
He simply adds the `x` flag to indicate that `wb` should not overwrite existing files. This should indeed prevent the issue of save files being wiped out. It might still be a good idea to handle error messages from `PathFileExistsW()` more explicitly, but this change seems like an obvious improvement to me.
This resolves #7672
> prevent the overwrite of existing mpq files

- Source/controls/controller_motion.cpp
The d-pad stopped working in the main menu after 4113805. As far as I can tell, the check for `gbRunGame` in `IsPressedForMovement()` is unnecessary.
> Fix d-pad in main menu

- Source/engine/path.cpp
- test/path_test.cpp
This fixes an issue where items and objects can no longer be interacted with unless the player is on top of them.
In the following conditional statement, the call to `GetDistance()` always returned zero. The reason is that the logic thought that a path of length 1 exceeds the maximum path length of 1 that was passed in via the second argument.
https://github.com/diasurgical/devilutionX/blob/20c0a8dae8b27ac2d5c3e768af2073efa5b18381/Source/controls/plrctrls.cpp#L171-L174
This resolves #7681
> Fix off-by-one in path finding logic

- Source/engine/render/text_render.cpp
- Source/items.cpp
Fixes #7651
The initial issue in the unique item info box was caused by `GetLineStartX` returning a negative value for long strings.
Fixing that made the text fit but the renderer breaks at arbitrary points, so we further use `WordWrapString` to break at word boundaries:
The info box issue was caused by `KerningFitSpacing` only taking the first line into account.
This PR fixes that by recalculating the kerning fit on each new line:
An alternative fix to would be to add a version of `GetLineWidth` that calculates the maximum width across all lines. This would make the kerning the same for all lines.
I went with kerning fit per line here but I don't have a strong preference either way.
/cc @Riccila
> Fix item description rendering issues

- 3rdParty/libzt/CMakeLists.txt
- Source/engine/path.cpp
- Source/items.cpp
gcc:
```
/home/runner/work/devilutionX/devilutionX/Source/items.cpp: In function ‘void devilution::UseItem(Player&, item_misc_id, SpellID, int)’:
/home/runner/work/devilutionX/devilutionX/Source/items.cpp:4274:35: warning: unused variable ‘spellLevel’ [-Wunused-variable]
4274 |                         const int spellLevel = player.GetSpellLevel(spellID);
|                                   ^~~~~~~~~~
```
Also, this doesn't show up in CI, probably because the build folder is cached, but libzt was generating a large number of warnings on my system because we weren't applying the `-w` flag to the `zt_pic` library.
---
MSVC:
> Warning: D:\a\devilutionX\devilutionX\Source\engine\path.cpp(173): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data
> Fix gcc/MSVC compiler warnings

- Source/mpq/mpq_writer.cpp
It seems that MinGW doesn't support opening files in exclusive mode. I'm hoping it supports append mode, at least.
https://sourceforge.net/p/mingw-w64/bugs/493/
The main difference here is that the game client will have to run `GetFileSize()` on newly created files and also open the file twice. The difference should be negligible, especially considering that the vast majority of `MpqWriter` instances will be opening existing files.
This resolves #7693
> Avoid write mode when opening save files

- Source/mpq/mpq_writer.cpp
Because the `ab` file mode doesn't outright fail when the save file already exists, then it turns out a false negative result from `FileExists()` can still wipe out a save file. The good news is that `GetFileSize()` can't retrieve a valid value for `size_` if an error occurs. Since we are querying the file size anyway, we can rely on that result to determine whether the MPQ we opened is a newly created file.
> Do not depend on FileExists() when opening save files for writing

- Source/debug.cpp
- Source/debug.h
- Source/engine/render/scrollrt.cpp
- Source/lua/modules/dev/display.cpp
This adds a new `missiles` data type to the debug lua `tileData` command.
After adding this, it turned out that `debugGridTextBuffer` can be too small (only 10 characters). This can be exceeded if there are many missiles on a tile or if there are many microTiles on a tile (e.g. cathedral levels).
This PR changes `debugGridText` to `std::string` to avoid such situations.
Example video:
https://github.com/user-attachments/assets/7a617a6d-c5e5-4fd4-a748-c94fca56f017
> Add missiles to tile data debug command

- Source/control.cpp
When debugging, it's possible to use quick messages to execute lua scripts.
This is useful when debugging to execute lua commands very quickly.
However, in singleplayer chat is disabled (`IsChatAvailable` returns false) and so no quick messages are processed.
This PR changes that so that `/lua` quick messages will work in singleplayer.
Note: Normal chat functionality is still disabled even in debug singleplayer, as we now have a great lua console with autocomplete.
> Allow lua debug quick messages in singleplayer

- .gitignore
- CMakeLists.txt
PR enables Edit & Continue support for MSVC, see https://learn.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio#edit-and-continue-for-cmake-projects.
This avoids the need to restart a debug session. This is especially useful when debugging multiplayer sessions.
I wasn't sure if we should add a CMake option for this, and if so, whether or not to enable it by default.
> MSVC: Enable Edit & Continue in debug builds

- Source/DiabloUI/diabloui.cpp
- Source/diablo.cpp
- Source/engine/palette.cpp
- Source/engine/palette.h
- Source/gamemenu.cpp
- Source/interfac.cpp
- Source/options.cpp
- Source/options.h
Gamma adjustment is extremely ugly. Replaced it with a more refined system that preserves the look of the game, but makes it less dark and easier to see on low brightness displays.
100% brightness level was configured to closely match the "intensity" of gamma at 100%. This is roughly a 100% brightness increase in the midtones from the vanilla pallette, with varying brightness increases in the low tones and high tones.
> Replace Gamma Adjustment with Brightness Adjustment

- docs/CHANGELOG.md
* Add changelog for 1.5.3
* Prepare template for 1.5.4
* Start Unreleased for 1.6.0 or 1.5.5
> [skip ci] Update changelog

- .github/workflows/Windows_MSVC_x64.yml
- 3rdParty/SDL2/CMakeLists.txt
- Packaging/windows/mingw-prep.sh
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- tools/update_sdl_android_project.sh
- vcpkg.json
> Update SDL2 on master

- Source/options.cpp
I was surprised when I booted up my debug build and was suddenly blinded.
> Use vanilla default brightness as default for brightness setting

- .devcontainer/Dockerfile
D1GraphicsTool-Linux-Qt5.deb no longer exists and causes the container setup to fail
This PR fixes the issue by updating the URL called in the curl and subsequent commands to the correct/actual latest version
(Sorry, didn't mean to close the previous one)
> Update Dockerfile to fix D1GraphicsTool install step

- .github/workflows/Linux_aarch64.yml
- .github/workflows/Linux_x86.yml
- .github/workflows/Linux_x86_64.yml
- .github/workflows/Linux_x86_64_SDL1.yml
- .github/workflows/Linux_x86_64_test.yml
Renaming the repo broke these caches because the Linux filesystem is case sensitive.
> Update cache version of Linux CI build scripts

- Source/lighting.cpp
When the remote player transitions from their current level to the loading screen, the local client...
* Receives `CMD_NEWLVL`
* Calls `player.setLevel()` to update `player.plrlevel`
* Sets `player._pLvlChanging` to true
When the remote player transitions from the loading screen to their new level, the local client...
* Receives `CMD_PLAYER_JOINLEVEL`
* Sets `player._pLvlChanging` to false
* Calls `StartStand()` which calls `FixPlayerLocation()` to update the player's position
* Calls `ActivateVision()` on the remote player instance
When the local player transitions from their current level to the loading screen after processing `CMD_NEWLVL` but before processing `CMD_PLAYER_JOINLEVEL`, the `player.isOnActiveLevel()` function will return true for the remote player because …
> Do not process vision for remote players when they are between dungeon levels

- Packaging/windows/mingw-prep.sh
This PR introduces a command into the MinGW setup script that comments two lines in the SDL2 Makefile, preventing the script from creating the `/usr/cmake` directory and deploying files to it.
Normally, the script deploys these two files:
* `/usr/cmake/sdl2-config.cmake`
* `/usr/cmake/sdl2-config-version.cmake`
These files appear to be unnecessary for compiling using MinGW compilers, but their presence does cause problems when attempting to build using native gcc compilers.
---
I encountered several warnings during CMake configuration when these files were present. This happens during first time configuration after having run the `Packaging/windows/mingw-prep64.sh` script, so you may not encounter this error if you have files already in your build folder or if you haven't tried building …
> [MinGW] Do not deploy files to /usr/cmake

- .github/workflows/Linux_x86_64_SDL1.yml
- .github/workflows/Linux_x86_64_test.yml
- Packaging/windows/mingw-prep.sh
Backports #7759 into the 1.5 branch
So we don't accidentally screw with `/usr/cmake` when testing the 1.5 version, though sadly there's not much we can do if you target the 1.5.4 tag.
> [1.5] [MinGW] Do not deploy files to /usr/cmake

- Source/items.cpp
Updates the logic for gamepad scroll descriptions in `PrintItemMisc()` to match the logic in `CtrlUseInvItem()`.
Based on the following snippet in `CtrlUseInvTime()`, scrolls that target monsters are not usable from the inventory. All other scrolls should be usable.
https://github.com/diasurgical/DevilutionX/blob/a2365c754ec0caf5d58df3a55367568eaf85f9f2/Source/controls/plrctrls.cpp#L2106-L2109
This resolves #7761
> Update gamepad scroll descriptions to match logic in plrctrls

- Source/items.cpp
Fixes an issue where remapping secondary/spell action buttons would cause item descriptions to display the wrong button names.
> Use padmapper input names for item descriptions

- Source/missiles.cpp
The initial frame for the Viper's Rhino/Lunge attack is hardcoded to start the animation at frame 7, giving context that the attack is intended to start at frame 7 and not exceed past the end of the animation. The lunge only occurs when the viper is exactly 2 tiles away from the player. The lunge also does not deal any damage, or cause knockback. This fix consistently stops the viper at the end of the animation length, which by testing has resulted in the desired behavior, where the viper will not stop short of reaching their target, but also will not continuously run into the distance if the target is missed.
Fixes: https://github.com/diasurgical/DevilutionX/issues/7034
> Fix Viper Lunge

- Translations/ru.po
Fixed the display of translations "Dur: {:d}/{:d},  " and "No required attributes"
Fixed the display of the translation of the description of the "Disable Crippling Shrines" setting
Fixed minor issues with the translation of the name of some types of plate armor have been
Other fixes
> Fix ru.po [1.5]

- .github/workflows/3ds.yml
- .github/workflows/Linux_aarch64.yml
- .github/workflows/Linux_x86.yml
- .github/workflows/Linux_x86_64.yml
- .github/workflows/switch.yml
- .github/workflows/xbox_nxdk.yml
- CMake/Dependencies.cmake
- CMake/finders/FindSDL2_image.cmake
- CMakeLists.txt
Ubuntu 20.04 is going EOL in May.
Ubuntu 22.04 CMake is 3.22.
Debian stable CMake is 3.25.
Debian oldstable (EOL in 2026) has CMake 3.25 in bullseye-backports.
> Bump CI to Ubuntu 22.04 and minimum CMake to 3.22

- .github/workflows/Android.yml
- android-project/app/build.gradle
R28 was released 3 weeks ago and is now preinstalled on GitHub CI runners.
https://github.com/android/ndk/releases/tag/r28
> Android: Bump NDK to 28.0.13004108

- Source/interfac.cpp
This resolves an issue where the game doesn't recognize the player letting go of the analog stick while on the loading screen.
There is a simple wrapper function for `SDL_PollEvent()` in `control/input.h` that ensures we clear gamepad state variables before processing each input event. See #3839 and https://github.com/diasurgical/devilutionX/pull/3825#discussion_r774869661 for more info.
> Unlock gamepad state during loading screens

- Source/controls/touch/event_handlers.cpp
- Source/controls/touch/event_handlers.h
- Source/controls/touch/gamepad.cpp
This PR resolves an issue reported by Discord user Ensl:
> So I noticed When I enter a new level on the dev app sometimes there's an issue with the button interface and it causes the directional stick or the spell button to get "stuck" and spam spells or render movement inoperable.
Prior to #7513, the loading screens would call `FetchMessage()` in `interface_msg_pump()` to process events whenever the loading bar updates. `FetchMessage()` would delegate the event to the virtual gamepad event handler, meaning that `SDL_FINGERUP` events that occur during the loading screen would still be handled.
Now, with the async loading implementation, we are explicitly bypassing `FetchMessage()` and calling `SDL_PollEvent()` directly. This means the virtual gamepad event handlers aren't handling those …
> Trigger deactivate event for virtual gamepad

- Source/engine/render/text_render.cpp
When using KerningFitSpacing with centered or right-aligned text, adjust the horizontal start position after changing the spacing.
Supersedes #7705 by @kphoenix137
> Adjust x-start with UiFlags::KerningFitSpacing

- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
- Source/player.cpp
- test/pack_test.cpp
When reviewing #7775, I noticed the code is just blindly assuming that `LoadHelper::NextBytes()` will produce a null-terminated string in `Item::_iName`, `Item::_iIName` and `Player::_pName`, but the function provides no such guarantee.
I was able to observe a buffer overrun with [single_0.sv.zip](https://github.com/user-attachments/files/18933202/single_0.sv.zip), using some debug code to visualize it. The player name is completely full of the `s` character. The debug code writes `i` characters into the item seed for the player's head slot so they can be seen in the output.
```diff
diff --git a/Source/diablo.cpp b/Source/diablo.cpp
index 6664a2199..fbb866c0b 100644
--- a/Source/diablo.cpp
+++ b/Source/diablo.cpp
@@ -1991,6 +1991,11 @@ void InitKeymapActions()
'X',
[] {
DebugToggle = …
```
> Validate player/item names coming from save file

- .github/workflows/Linux_x86_64_test.yml
A token is required to upload coverage for protected branches.
Hopefully fixes #7805 
Note that `gcov: true` argument was unnecessary and isn't actually recognized by codecov-action.
> codecov.yml: Pass CODECOV_TOKEN

- Source/CMakeLists.txt
- Source/engine/render/blit_impl.hpp
- Source/engine/render/clx_render.cpp
- Source/engine/render/clx_render.hpp
- Source/engine/render/dun_render.cpp
- Source/engine/render/dun_render.hpp
- Source/engine/render/light_render.cpp
- Source/engine/render/light_render.hpp
- Source/engine/render/scrollrt.cpp
- Source/levels/gendung.h
- Source/options.cpp
- Source/options.h
- test/dun_render_benchmark.cpp
The idea is to use the marching squares algorithm to create isolines for each of the 16 light levels using the tile-based light data from `dLight`. The contours generated by marching squares are rendered onto a "lightmap" buffer which is used to look up light levels for individual pixels during rendering.
Because this uses the data from `dLight` to generate the isolines, the result should be fundamentally similar to the existing lighting system, just with a more natural gradient. And because the renderer still uses `LightTables` to look up colors in the 8-bit palette, the color banding due to the limited color selection should also be preserved. Furthermore, by hooking into the existing lighting system this way, the code footprint was small enough that I was easily able to provide this as …
> Per-pixel lighting using software renderer

- Source/pack.cpp
Another issue introduced by the complicated hidden requirements of `LoadMatchingItems()`. The unpacked item must get the `CF_HELLFIRE` flag from the item regeneration logic instead of the `dwBuff` field from the packed data. Otherwise, `LoadMatchingItems()` won't be able to tell if it was unpacked as a Diablo item or a Hellfire item.
https://github.com/diasurgical/devilutionX/blob/d92bdd248f9fb5d866b027313ebc88c1dfb2aa97/Source/loadsave.cpp#L997-L999
This resolves #7742
> Fix issue with Hellfire items morphing when transferred to Diablo

- Source/engine/render/light_render.cpp
Fixes aberrations in the light data around the saddle points in cases 5 and 10 of the marching squares algorithm. You can see it most clearly by casting Flame Wave, where the following visual effect will flicker onto the screen.
And in this image, you can see the `dLight` data that causes it. The light data goes a bit crazy around the saddle points (the space between tiles with with values 0 east/west and 5 north/south).
> Use signed integers for interpolation in marching squares algorithm

- Source/engine/render/light_render.cpp
- Source/engine/render/light_render.hpp
- Source/engine/render/scrollrt.cpp
- test/dun_render_benchmark.cpp
This PR bleeds light up from the top edge of the base diamond to the top of wall/ceiling tiles, as described in #7809.
For this to work, we first need to copy light data for the base diamond of the wall tile from the per-pixel lightmap into a new 64x32 buffer. As we do this, we also compute where the top edge of the base diamond is so we can bleed data up from there to the top of the buffer. This new buffer becomes the source for light data used when rendering the base diamond. Then, when rendering the rest of the CEL data above the base diamond, we simply reuse the top row of the 64x32 buffer for every rendering instruction, allowing us to apply the same lighting to the rest of the graphic.
This effect really does make the lighting on walls and ceilings look remarkably similar to the …
> Bleed per-pixel light up when rendering walls

- Source/engine/render/light_render.cpp
- Source/engine/render/light_render.hpp
- Source/engine/render/scrollrt.cpp
Fixes OOB errors that occur at 1146x480 resolution. The pitch of the output surface is 1148, not 1146.
> Don't assume output surface pitch is the same as width

- Source/lighting.cpp
Compare the lighting for the Sarcophagus between these two videos.
Before:
https://github.com/user-attachments/assets/002564c0-0ddb-45c8-9328-edf3f3c3fbc0
After:
https://github.com/user-attachments/assets/5148b890-7e15-4760-b97d-6f6281fd7f71
> Swap offsets in distance formula for light cones

- Source/interfac.cpp
It appears that 3DS has the same issue as Tiger PPC, where `SDL_PushEvent()` does nothing from a background thread.
> [3DS] Fix async loading

- Source/controls/game_controls.cpp
These button translations don't actually do anything useful. Navigation is handled by the `SpellBookMove()` function in `plrctrls.cpp`. We can rely on padmapper to control the automap and trigger the `Cancel` action while the spellbook is open. The only thing this translation function does is cause weird behaviors unrelated to spellbook, like the `Y` button will open the chat or the d-pad will move the automap around.
> Remove translation from pad buttons to keys in spellbook

- Source/lua/modules/dev/towners.cpp
- Source/towners.cpp
- Source/towners.h
`DebugTalkToTowner()` is currently no longer able to find any towners at all. This is because it searches by towner name, but `townerData.init()` doesn't populate `towner.name`. It needs to invoke `InitTownerInfo()`, but it can't do that since that function requires us to pass an index to the `Towners` array.
Incidentally, the `DebugCmdVisitTowner()` function uses a lookup table to find towners not only by name, but also by shortened descriptions such as `smith`, `witch`, or `bmaid`. The only downside is that it's not case-insensitive, but I figure someone can add that if they need it.
This PR splits the `InitTownerInfo()` function in two so that `DebugTalkToTowner()` can pass a `Towner` instance that is not a member of the `Towners` array. It also updates `DebugCmdTalkToTowner()` to use …
> Fix debug command for talking to towners

- Source/missiles.cpp
This PR uses `y = 11 - |x - 11|` to compute the index for the light radius of the Fire Wall, allowing us to both ramp it up when the Fire Wall is growing and also ramp it back down when the Fire Wall is shrinking.
Normal speed:
https://github.com/user-attachments/assets/0218b49c-1452-40dd-98dc-9da88f2e597c
Slow:
https://github.com/user-attachments/assets/98a194b7-800c-4475-8dda-b198f839e031
This resolves #7819 -- Although, technically that is an issue about two separate things. This is just what happens when you don't make two separate issues. :shrug:
> Natural Fire Wall light expansion

- Source/missiles.cpp
This PR fixes the light radius of Flame Wave missiles which was inexplicably hardcoded to 8 despite the missile having already reached a light radius of 12. I also removed the logic that uses `var3` and `var4` to limit the frequency at which Flame Wave lights update their position, since I don't think we need it anymore now that the light jitter was fixed.
The following video, shared by @FitzRoyX on Discord, demonstrates how the wall gets darker in the middle of the spell despite the wall of flame continuously moving closer to the wall.
https://github.com/user-attachments/assets/ddb31cc7-fa72-47de-83fb-31506d6c5bd7
> Don't darken flame wave after it reaches full brightness

- Source/monster.cpp
Recently a team of four reported on Discord there was a Blood Knight in their game that was still alive after Diablo was eliminated.
`DiabloDeath()` only updates the monster's animation and mode, but not hitpoints. The game stops calling `ProcessPlayers()`, but `ProcessMissiles()` should still be active. So my theory is that if a stray missile happens to hit the Blood Knight while Diablo is bleeding out, it could engage hit recovery which would override the animation and mode of the monster.
It seems reasonable to include `MonsterMode::Death` in the `isPossibleToHit()` function to prevent missiles from hitting monsters that were killed by `DiabloDeath()`. Monsters that were killed by other means should probably also not be possible to hit.
> Check for MonsterMode::Death in isPossibleToHit()

- Source/engine/render/text_render.cpp
- Source/panels/charpanel.cpp
Depends on: https://github.com/diasurgical/devilutionX/pull/7705
Fixes: https://github.com/diasurgical/devilutionX/issues/7692
Obsoletes: https://github.com/diasurgical/devilutionX/pull/7688
Removes hardcoding from the Character Panel for spacing numbers, and prevents them from extending too far onto the box edges.
> Character Panel Number spacing

- Source/items.cpp
- Source/stores.cpp
- Source/stores.h
Use constexpr instead of #define, and unhardcode values used in towner stores.
Note: You may notice that the some define's numbers don't match (e.g. 24 instead of 25), however the game used the hardcoded integer values as rules for how many items end up populating for the player, making the values of the respective defines pointless when exceeding the hardcoded values. (Look at how the witch will attempt to spawn a 25th item, but then immediately discard it)
> Stores - Unhardcode shop values

- Source/panels/charpanel.cpp
Changes "To hit" to "Chance To Hit" in the Character Panel to match the terminology used in affix descriptions.
> Character Panel - CTH

- Source/controls/plrctrls.cpp
- Source/diablo.cpp
This PR aligns the order of operations between `GetLeftStickOrDPadGameUIHandler()`, `PerformPrimaryAction()`, `PerformSecondaryAction()`, and `PerformSpellAction()` so that menu interactions work more consistently when multiple menus are open. As an example, if you managed to get the inventory and the speedbook open at the same time, gamepad would interact with the inventory but the info panel would only show the spell from the speedbook you happened to be hovering over. As another example, if you managed to get the char panel and speedbook open at the same time with stat points to distribute, the d-pad and analog stick would prioritize the char panel whereas the primary action button would prioritize the speedbook.
The PR also disables various padmapper actions when game menus are open. …
> More consistent gamepad context sensitivity

- Source/missiles.cpp
Wasn't sure how to write a title for this one. The player's base damage while holding a bow is modified by cutting the base player damage in half if the hero is not a Rogue. This applies to the character panel damage, and against monsters. The code for this is missing in the `Plr2PlrMHit()` function, causing no base damage reduction for non-Rogue heroes. There is no evidence that this is an oversight other than speculation, however I believe this adds consistency. There is also no evidence in favor of no damage reduction for PVP, as this is only a result of missing code, and there is no code that deliberately gives more damage to non-Rogue heroes in PVP.
> Fix PVP Bow damage

- Source/levels/gendung.cpp
- Source/levels/reencode_dun_cels.cpp
- Source/levels/reencode_dun_cels.hpp
This PR adjusts the logic for re-encoding cel blocks to completely remove all traces of unused frame indexes.
This also resolves errors where data will be reencoded incorrectly when frames are not referenced by the tile data. Consider the following example where I replaced tile 393 in the spritesheet...
> Tile 393 originally referenced frames 0x3ff through 0x402, inclusive. By replacing the tile, I added new frames on the end of the spritesheet, 0x460 through 0x463. Because tile 393 was the only tile that referenced 0x401 and 0x402, there are no longer any references to those frames in `l1.min`.
> 
> `ReencodeDungeonCels()` was using `frame * 4` to compute the position for each address in the lookup table, but it used `frames.size()` to compute the size of the lookup table. This means …
> Efficiently pack re-encoded level cel blocks

- Source/levels/gendung.cpp
- Source/levels/reencode_dun_cels.cpp
- Source/levels/reencode_dun_cels.hpp
Follow-up to fix an issue with #7852
It occurred to me that frames may be referenced by multiple tiles, and therefore one pointer per frame is not going to be enough to reindex all the references to that frame in `DPieceMicros`. If the unreferenced frames precede a frame that is referenced more than once in the min file, there will still be at least one reference in `DPieceMicros` that wasn't properly reindexed.
I removed the pointer from `DunFrameInfo`. We can still compute the adjustment values based on the sorted vector of frames, but we need to scan all the active blocks in `DPieceMicros` to find the ones that need to be reindexed. To make it work, I generate a sparse vector of "frame index gaps" that can be used to find the adjustment value for a given frame index using a binary …
> Reindex all level cel blocks

- Source/lua/metadoc.hpp
- Source/lua/modules/player.cpp
- Source/player.h
Adds a minimal Player usertype as an example of how to do usertypes in Lua.
> Lua: Add a player usertype

- Source/inv.cpp
- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
- Source/msg.cpp
- Source/pack.cpp
Hello,
I discussed making these changes on Discord for a little bit, and I think they make sense. This more comprehensively addresses the bug that was fixed by https://github.com/diasurgical/DevilutionX/pull/7859. The changes are as follows:
- items.cpp:RecreateItem() no longer takes an isHellfire argument, but rather the entire dwBuff flag.
- Simplifies and makes the logic in pack.cpp:UnPackItem() for setting the CF_HELLFIRE flag clearer, at @StephenCWills suggestion.
- Assigns dwBuff flag to item.dwBuff within RecreateItem() to prevent any future cases of uninitialised use when calling.
- Removes obsolete assignments to item.dwBuff.
I would like to make this change for the following reasons:
- Uninitialised uses of the dwBuff flag are now very unlikely in RecreateItem().
- Allows dwBuff …
> Make RecreateItem() take whole dwBuff flag as argument

- Source/items.cpp
Hello,
I have had some very inconsistent crashes on the very recent revisions, and I decided to take some time to debug it. I ran git bisect and it pointed me towards commit f5d430fbf, though given the harmless contents of this commit I really have no idea *why* it exposes this problem. In my mind, this commit should not cause any issues at all.
Regardless, the problem is that if a vendor max rolls their itemCount, SortVendor() will not count the item entries correctly anymore, and thus buffer overflow. This then causes memory corruption and a crash within GetItemAttrs() as it tries to read from an invalid pointer on this line:
```item._itype = baseItemData.itype;```
The issue can be reproduced by assigning `iCnt = maxItems;` within SpawnSmith(). This will always produce a crash, at least …
> Fix items.cpp:SortVendor() buffer overflow

- .github/workflows/clang-tidy-check.yml
We've got some checks enabled that contradict current convention, hoping enabling checks in pull requests lets us refine the checks we actually use.
> Add clang-tidy workflow

- Source/inv.cpp
fixes #7831 
Queuing the sound before performing the paste ensures that the correct sound plays even if swapping with an item already in the inv/body (which would change the held item). This matches vanilla behaviour/stash behaviour
> Play the sound of the item we're pasting, not what we picked up

- Source/inv.cpp
- Source/player.cpp
- test/inv_test.cpp
#7876 
Previously commited this to my master branch, I moved it to its own branch
> Rebase of #7876 - Shift item order when selling to keep consistent window order

- Source/player.cpp
`.../Source/player.cpp:1563:53: warning: comparison of integer expressions of different signedness: ‘size_t’ {aka ‘long unsigned int’} and ‘int’ [-Wsign-compare]`
> Fix compiler warning in Player::RemoveInvItem()

- Source/options.cpp
- Source/options.h
- Source/utils/file_util.cpp
- Source/utils/file_util.h
Automatically load mods from the mods directory.
> Lua: Dynamic mod loading

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Building d1 graphics tool from source allows running the container on non-x64 architectures
Building smpq from source works around the arm64 version of smpq distributed in debian 12 repos (which is linked against StormLib 9.22 - released in 2017) failing an assert when packing our assets.
> build smpq and d1 graphics tool from source in devcontainer

- .github/workflows/Windows_MinGW_x64.yml
- .github/workflows/Windows_MinGW_x86.yml
- 3rdParty/Lua/CMakeLists.txt
- 3rdParty/libpng/CMakeLists.txt
- 3rdParty/tolk/CMakeLists.txt
- CMake/platforms/mingw/zt_defs.cmake
See also https://github.com/walterschell/Lua/pull/36
I'm not sure how soon we should expect the maintainer of the Lua repo we're referencing to respond so I'm submitting this to at least get CI working again.
> Workaround for deprecation of old CMake versions

- Source/utils/static_vector.hpp
- test/CMakeLists.txt
- test/staticvector_test.cpp
Hello,
While I was working on using `StaticVector` for vendor item arrays, I noticed that `StaticVector::erase()` doesn't seem to behave as expected. I asked about this on Discord and @glebm concluded it is a bug, and says that it is intended to work exactly like `std::vector`'s erase. 
The following changes have been made to `static_vector.hpp`:
- `std::move` is called before `std::destroy_at`, shifting items left.
- `std::destroy_at()` now destroys the entries at the back of the array after the move.
- `StaticVector::clear()` returns early if there are no member items.
I am not an expert in C++ and am not 100% confident in this PR or the changes made, so feedback is greatly appreciated. 
Regards,
Yggdrasill
> Left shift in StaticVector::erase(), add tests

- .github/workflows/Windows_MSVC_x64.yml
- 3rdParty/SDL2/CMakeLists.txt
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- vcpkg.json
Upgrade includes build-from source, Android and VCPKG
`Fixed controller GUIDs changing randomly on Windows` this fix is important, because it made bindings reset after unplugging and plugging the controller back in: https://github.com/azahar-emu/azahar/issues/391
Don't know if affected us, but good, that it's fixed now!
> Upgrade SDL2 to 2.23.4

- .github/workflows/clang-tidy-check.yml
Without this, clang-tidy-check cannot see any dependencies (such as SDL), resulting in spurious warnings.
> clang-tidy-check: Use a compilation database

- Source/DiabloUI/mainmenu.cpp
- Source/DiabloUI/settingsmenu.cpp
- Source/engine/assets.cpp
- Source/engine/assets.hpp
- Source/engine/sound.cpp
- Source/init.cpp
- Source/init.h
- Source/menu.cpp
- Source/player.h
- test/dun_render_benchmark.cpp
- test/inv_test.cpp
- test/pack_test.cpp
- test/player_test.cpp
- test/timedemo_test.cpp
- test/writehero_test.cpp
This is done as prep work for being able to load and unload mods that are distributed as MPQ files.
The changes here are done in a way that changes as little as possible about how things works.
- bespoke bools are still used to track what was loaded
- Hellfire is always loaded but it's files are skipped if not active
- priority values match the original Diablo/Hellfire
In a follow up to this PR I would like to:
- mods are automatically loaded in to the 1xxxx range (the specific value will depend on what order they appear in the ini).
- 1xxx and 9xxxx stays loaded but changing the mod will reload the 8xxx and 1xxxx range.
- Hellfire is loaded via a lua function
> Handle loaded MPQ files in a map instead of bespoke globals

- Source/utils/static_vector.hpp
Hello
This is just a very small PR and shouldn't require much time to review. https://github.com/diasurgical/DevilutionX/pull/7912 is unable to build on PS4 and Xbox due to the following build errors:
```
/home/runner/work/DevilutionX/DevilutionX/Source/stores.cpp:1034:2: error: no matching function for call to 'ScrollVendorStore'
ScrollVendorStore(HealerItems, static_cast<int>(HealerItems.size()), idx);
^~~~~~~~~~~~~~~~~
/home/runner/work/DevilutionX/DevilutionX/Source/stores.cpp:357:6: note: candidate function not viable: no known conversion from 'StaticVector<devilution::Item, NumHealerItemsHf>' to 'std::span<Item>' for 1st argument
void ScrollVendorStore(std::span<Item> itemData, int storeLimit, int idx, int selling = true)
```
This is because these builds use the `data()` and …
> Add data() method to StaticVector

- Source/utils/format_int.cpp
- Source/utils/format_int.hpp
Adds an overload for `FormatInteger()` that uses `uint32_t` function argument to avoid overflow with large numbers.
Fixes: https://github.com/diasurgical/DevilutionX/issues/7909
> FormatInteger (unsigned)

- Source/inv.cpp
Displays the hotkey for each belt slot on the belt, rather than displaying 1-8 (Since 1-8 is no longer hardcoded as the hotkeys for the belt).
 
Fixes: https://github.com/diasurgical/DevilutionX/issues/7908
> Draw Hotkeys on Belt

- Source/levels/drlg_l4.cpp
In Multiplayer with full quests on, if someone sticks around in-game after Diablo is defeated, the pentagram leading from dlvl 15 to 16 is deactivated. This prevents players from reaching dlvl 16 if there was not already a Town Portal present on the dungeon level.
> Do not deactivate dlvl 15 pentagram

- Source/automap.cpp
In Hellfire, when a character casts the Search spell, they see a blue square denoting the location of the item on their map.  Recently we have added a feature that allows you to toggle between the original map, a more transparent version of that map, and a minimap that sits in the top right corner of the screen.  The blue squares/search effect is missing from the Minimap.  This PR corrects the accidental oversight/bug.
> BUGFIX: Search Effect not working with Minimap

- 3rdParty/bzip2/CMakeLists.txt
Sourceware URL is too unreliable
This downloads source from a tag in experimental 1.1 bzip2 repo
https://gitlab.com/bzip2/bzip2/-/tags/bzip2-1.0.8
New hash is because new source archive is not identical to one from Sourceware for some reason
Proof this is official repo: https://sourceware.org/bzip2/downloads.html
> Add alternative download for bzip2

- Source/utils/paths.cpp
An update to the Haiku patch I made for the asset dir lookup.
The old patch assumed the game would always be installed system-wide, but that lookup (and the game init) would fail if it was installed locally, in the user's home directory.
This new patch ensures DevilutionX will work in both cases. Tested and working on my install.
> Better asset path lookup for Haiku

- Source/lighting.cpp
This commit fixes a very subtle case where players could see through diagonally adjacent tiles. The bug was introduced in the recent commit: 88d0cb749fdc ("lighting: fix long-standing issue with invisible objects (#7901)").
The following 2D grid illustrates the bug:
```
. .                                       . .
. . .                                   . . .
. . .                               . . .
. . .                           . . .
. . .                       . . .
. . .                   . . .
. .                   . .
. .                   . .
. . .                   . . .
. . .                       . . .
. . .                           . . .
. . .                               . . .
. . .                                   . . .
. .                                       . .
``` …
> lighting: fix vision through diagonally adjacent tiles

- .github/workflows/Linux_aarch64.yml
- .github/workflows/Linux_x86.yml
- .github/workflows/Linux_x86_64.yml
- 3rdParty/libzt/CMakeLists.txt
This turned out to be more than just a one-liner:
* Upgrades Linux CI runners to 22.04, 20.04 was deprecated and removed, see: https://github.com/actions/runner-images/issues/11101
* Removes unneeded workaround
* Backports https://github.com/diasurgical/libzt/commit/72a518bcf7d87e32f718ca612ce2c8303ceedd12 since CI updated CMake to 4.0 and CMake 3.5 compatibility was removed
Required for https://github.com/diasurgical/DevilutionX/pull/7936
> [1.5] Fix CI building

- Source/lua/modules/dev/items.cpp
The new logic makes it possible for all unique items to generate so this return statement is no longer accurate or necessary.
> [Debug] Keep trying when unique item fails to generate

- Source/msg.cpp
This debug code hasn't kept up with the changes in `msg.h`.
> Fix CmdIdString() based on changes to the _cmd_id enum

- Source/lighting.cpp
- Source/lighting.h
- test/CMakeLists.txt
- test/vision_test.cpp
PR adds a vision test, which covers a few vision bugs:
1. VisibilityInStraightLineOfSight - test case checks the visibility of objects in a straight line of sight parallel to the X or Y coordinate lines: https://github.com/diasurgical/DevilutionX/pull/7901
2. NoVisibilityThroughAdjacentTiles - test case checks that nothing is visible through the diagonally adjacent tiles: https://github.com/diasurgical/DevilutionX/pull/7920
3. VisibleObjects - generic test, which makes sure some objects are visible, but some - are not.
> Vision test

- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
- Source/msg.cpp
- Source/msg.h
- Source/player.cpp
- Source/sync.cpp
Contributes to #543 and supports #7663
In master and vanilla golems are tied to a specific monster id. This monster id corresponds 1:1 to the player id. This is how the relation player<->golem relationship is maintained and that's also why the game reserves the first 4 monster slots for golems (max player count in multiplayer).
This PR changes that by 
- using `goalVar3` to maintain the golem<->player relationship (should be 0 in singleplayer saves)
- introducing a helper to find golems for a player
- using `SpawnMonster` logic to spawn golems (similar to how monsters are spawned dynamically, see #6890)
- to maintain vanilla compatibility, the first 4 slots are still reserved for golems. In singleplayer, the first monster slot is always used.
Additional notes
- Allows multiple golems to …
> Decouple Golems from Players and use SpawnMonster for Golem

- Source/utils/display.cpp
Fixes (at least on my machine) #7776
I could reproduce #7776 when vsync is enabled and switching resolution or fit to screen.
It looks like SDL2 doesn't like it when the renderer is recreated.
But since #7443 is merged, we don't need to recreate the renderer anymore (it will always stay be there if upscale is true). The only flag we passed to `SDL_CreateRenderer` (vsync) can be replaced by a separate function call (`SDL_RenderSetVSync`).
Tested changing: resolution, fit to screen, vsync, integer scaling.
It would be great if someone else who had errors changing one of the settings and someone else on another device (e.g. linux) could test this PR.
> Fix freezing the screen when changing the resolution by not recreating the renderer

- Source/utils/display.cpp
This PR fixes a warning by removing an unused function.
Note, we are calling `SDL_DestroyRenderer()` directly in `dx_cleanup()` so no need to worry about leaked resources at shutdown.
> Remove unused function FreeRenderer()

- Packaging/nix/devilutionx-hellfire.desktop
- Packaging/nix/devilutionx.6
- Packaging/nix/devilutionx.desktop
1. desktop-entry-lacks-keywords-entry
This .desktop file is either missing a Keywords entry, or it does not contain keywords above and beyond those already present in the Name or GenericName entries.
2. no-manual-page
Each binary in /usr/bin, /usr/sbin, /bin, /sbin or /usr/games should have a manual page.
Could you write a manual for the devilutionx binary? I see the description of the devilutionx --help options, but I don't see a manual. That would be cool!
These tasks from:
https://github.com/diasurgical/DevilutionX/issues/7971
Please check the text from `devilutionx.6` carefully, is it correct?
You can read it:
`$ man ./devilutionx.6 `
> nix/*.desktop: add Keywords fields

- Source/loadsave.cpp
- Source/misdat.h
- Source/missiles.cpp
- Source/missiles.h
- Source/monster.cpp
- Source/portal.cpp
- test/missiles_test.cpp
The `Missile` struct contains a member `_mimfnum`, originally defined as an `int`, which is used inconsistently across the codebase in three distinct ways:
- As a raw `int` (e.g., for animation frame group selection)
- As `Direction` (8-directional enum)
- As `Direction16` (16-directional enum, used for finer visual rotation)
This loose usage made the intent behind `_mimfnum` ambiguous and error-prone, requiring frequent manual casting and encouraging magic numbers.
---
This PR improves encapsulation and usability of `_mimfnum` by:
- Making `_mimfnum` a **private** member of `Missile`
- Introducing **explicit getters and setters** to clarify usage:
- `setDirection(Direction)`
- `setDirection(Direction16)`
- `getDirection()`, `getDirection16()`
- `setFrameGroupRaw(int)`
- …
> Refactor Missile direction/frame group handling

- Source/engine/assets.cpp
Fixes the following ASAN error.
```
==24753==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 54 byte(s) in 1 object(s) allocated from:
#0 0x7fe12c6f3b58 in realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:85
#1 0x7fe12c488c45  (/lib/x86_64-linux-gnu/libSDL2-2.0.so.0+0xa8c45) (BuildId: ba11ec6cc627e78ef7103144630792da02ed18b6)
#2 0x7fe12893bd27  (<unknown module>)
#3 0x7fe12893bedf  (<unknown module>)
#4 0x562c1ec81c7d in devilution::LuaReloadActiveMods() .../DevilutionX/Source/lua/lua.cpp:219
#5 0x562c1ec84657 in devilution::LuaInitialize() .../DevilutionX/Source/lua/lua.cpp:284
#6 0x562c1e566412 in devilution::DiabloMain(int, char**) .../DevilutionX/Source/diablo.cpp:2608
#7 0x562c1dbfef35 in main .../DevilutionX/Source/main.cpp:52
#8 0x7fe12b633ca7 in …
```
> Use paths::GetBasePath() so it can be freed

- Source/CMakeLists.txt
- Source/control.cpp
- Source/encrypt.cpp
- Source/encrypt.h
- Source/items/validation.cpp
- Source/items/validation.h
- Source/levels/setmaps.h
- Source/monsters/validation.cpp
- Source/monsters/validation.hpp
- Source/msg.cpp
- Source/msg.h
- Source/multi.cpp
- Source/portals/validation.cpp
- Source/portals/validation.hpp
- Source/quests/validation.cpp
- Source/quests/validation.hpp
- Source/sync.cpp
- Source/sync.h
- Source/textdat.cpp
- Source/textdat.h
Some of the more noteworthy fixes...
* The use of `reinterpret_cast<uint16_t *>(...)` on unaligned data when exporting and importing spawned monster deltas triggered ASAN errors. Switched to `memcpy()` to resolve them.
* Spawned monster deltas and quest deltas were both using native endian encoding.
* The `CMD_STRING` message was doing absolutely no validation and assuming a well formed null terminated string.
* When receiving `CMD_DLEVEL` messages, bytes are copied to `sgRecvBuf`, which wasn't made large enough to match the sender's buffer size, let alone the largest possible `DLevel` struct.
* Various fatal errors could theoretically be triggered by malformed packets so they were converted to nonfatal errors.
* Most nonfatal errors when decoding packets will result in dropping the …
> Validation of network packet lengths and deltas

- Source/monster.cpp
Fixes: https://github.com/diasurgical/DevilutionX/issues/7979
Removes checking for player/monster occupancy for `AiPlanPath` LoS check.
> Fix Monster Line of Sight

- Source/monster.cpp
This crash occurs if there are no available monsters with the `PLACE_SCATTER` flag. This is unlikely to ever happen, but still a potential crash avenue in the case someone mods the game and intends to have levels without monsters.
> Fix crash related to Monster placement

- Source/panels/spell_book.cpp
Removes hardcoded Spellbook skill by using the hero skill from the starting loadout table.
> Use existing fn for Spell Book Skill

- Source/panels/spell_book.cpp
Use the Starting Loadout table to color a Spell Book spell as a skill if it matches the player's skill
> Use existing fn for Spell Book Trans matching Skill

- Source/control.cpp
- Source/control.h
- Source/engine/render/scrollrt.cpp
The first issue was introduced in #7417 when the code that draws the filled part of the lower portion of each flask was removed from the drawing function for the flasks. Before that, there was a comment introduced in #2291 questioning the need for that code, and I believe the reason it was deemed unnecessary is because `DrawMainPanel()` usually draws the filled part anyway so drawing it again would be largely redundant. However, the issue makes it clear that sometimes the flasks get drawn without calling `DrawMainPanel()`. Instead, I've chosen to pass a boolean value into `DrawLifeFlaskLower()` and `DrawManaFlaskLower()` indicating whether we need to draw the filled part of the flask, based on whether `DrawMainPanel()` was called in the same frame.
The second issue is pretty …
> Fix rendering issues with health/mana flasks

- Source/sync.cpp
Introduced by #7986. It's skipping past way more bytes than intended.
This resolves #7992
> Fix pointer arithmetic in OnSyncData()

- 3rdParty/bzip2/CMakeLists.txt
Turns out CMake doesn't like 2 repos in one FetchContent
> Remove bzip2 backup repo

- 3rdParty/bzip2/CMakeLists.txt
Backports #7925 into 1.5 branch
> [1.5] Add alternative download for bzip2

- Source/DiabloUI/multi/selgame.cpp
Adjusts the MP Tick Rates to being 5 apart instead of 10 apart. Allows for more granular game speed changes rather than huge noticeable changes. Additionally, having a lower maximum provides options to players that are less likely to cause desync hourglass in games.
Current MP Speed options:
100%, 150%, 200%, 250%
Proposed MP Speed options:
100%, 125%, 150%, 175%
> Adjust MP Tick Rates

- CMake/platforms/amiga.cmake
- Packaging/amiga/Dockerfile
- Source/CMakeLists.txt
- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/dialogs.cpp
- Source/controls/touch/renderers.cpp
- Source/diablo.cpp
- Source/engine/assets.cpp
- Source/engine/assets.hpp
- Source/engine/dx.cpp
- Source/engine/render/scrollrt.cpp
- Source/init.cpp
- Source/init.h
- Source/init.hpp
- Source/menu.cpp
- Source/mpq/mpq_reader.cpp
- Source/mpq/mpq_reader.hpp
- Source/options.cpp
- Source/platform/android/android.cpp
- test/player_test.cpp
- test/timedemo_test.cpp
- test/writehero_test.cpp
This unifies a lot of the code between the MPQ and UNPACKED_MPQS versions, so we actually end up with less code as a result.
> Support mods with UNPACKED_MPQS

- Source/monster.cpp
- Source/monster.h
- Source/msg.cpp
- Source/multi.cpp
- Source/player.cpp
When a monster puts a remote player into hit recovery while that player is in the middle of warping between the dungeon and Tristram, it's possible to encounter the following error.
This is possible because `monster.enemy` still has a reference to the ID of a player that uses a town portal. The monster doesn't change targets mid-swing, so it's possible for the monster to hit the player despite the fact that they are no longer referenced in the `dPlayer` array. If the monster puts the player into hit recovery, the remote player will reappear in the `dPlayer` array and eventually crash the local client when their graphics are unloaded.
> Fix errors where Monster::enemy references garbage memory

- Source/monster.cpp
Seems like the `activeForTicks` value shouldn't be dependent on the `enemy` field. This hardly matters in practice because monsters rarely gain the `MFLAG_NO_ENEMY` flag and will quickly and inevitably lose it the next time they enter the idle state, but the logic makes more sense this way.
> Separate logic for enemy position from activeForTicks

- Source/diablo.cpp
- Source/engine/demomode.cpp
- Source/interfac.cpp
- Source/interfac.h
- Source/player.cpp
We use `SDL_UserEvent::code` instead of `SDL_Event::type` to indicate the `interface_mode` of the custom event. This avoids overrunning the number of event types on SDL1, which is limited to just 8 custom events.
Implemented as described in https://github.com/diasurgical/DevilutionX/pull/8011#issuecomment-2905853863.
This also resolves the issue that 3DS had when running `SDL_PushEvent()` from a background thread.
> Fix custom event logic in interfac.cpp

- Source/msg.cpp
I used the following code to simulate slipping a mouse down event into the event queue just before the `WM_DIABWARPLVL` event. If you use this code and enter a Town Portal while holding `Shift`, it will trigger a `CMD_SATTACKXY` packet immediately after `CMD_WARP`, causing a crash when the game attempts to render the attack animation in town. This PR fixes that crash.
```diff
diff --git a/Source/player.cpp b/Source/player.cpp
index ab9e2f965..66ff5e7cb 100644
--- a/Source/player.cpp
+++ b/Source/player.cpp
@@ -2890,6 +2890,16 @@ void RestartTownLvl(Player &player)
}
}
+void PushMouseDown()
+{
+    SDL_Event event;
+    event.type = SDL_MOUSEBUTTONDOWN;
+    event.button.x = 464;
+    event.button.y = 179;
+    event.button.button = SDL_BUTTON_LEFT;
+    SDL_PushEvent(&event);
+}
+
void …
```
> Validate messages that should not be sent in town

- Source/control.cpp
This PR clears the text selection in the chat box when the chat box is dismissed using the `Esc` key.
To reproduce the crash:
1. Build in debug mode (not sure if it crashes in release mode).
2. Start a Multiplayer game.
3. Press `Enter` and type `a` into the chat box.
4. Use `Shift+Left` to select the `a`.
5. Press `Esc` to dismiss the chat box.
6. Press `Enter` and type `a` into the chat box.
The logic will try to replace the selection with the character you typed in step 6, but since the chat box was dismissed in step 5, the text that was selected is no longer there.
> Fix crash due to text selection in chat box

- Source/utils/palette_blending.cpp
- Source/utils/palette_kd_tree.hpp
I forgot to do this in #8025. No performance impact.
The skipFrom/To arguments are used to avoid mapping to colors that get palette-swapped (poison water)
> Implement skipFrom/To for the k-d tree

- Source/DiabloUI/diabloui.cpp
- Source/engine/palette.cpp
- Source/engine/palette.h
- Source/interfac.cpp
Previously, we reapplied tone mapping to up to 31 colors, but that's not necessary, as we only update a single color in  `palette_update_quest_palette`.
> palette_update_quest_palette: tone map 1 color

- Source/utils/static_vector.hpp
A bit less code now that we're C++17 everywhere.
> static_vector.hpp: Use `std::destroy_n` in the destructor

- Source/utils/palette_kd_tree.hpp
Our values are `uint8_t`, so we can get the median somewhat faster than `nth_element`.
```
Comparing build-reld-master/palette_blending_benchmark to build-reld/palette_blending_benchmark
Benchmark                                              Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------
BM_GenerateBlendedLookupTable_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
BM_GenerateBlendedLookupTable_mean                  -0.0198         -0.0198       2272848       2227790       2270291       2225348
BM_GenerateBlendedLookupTable_median                -0.0199         -0.0199       2272884       2227649 …
```
> Palette kd-tree: slightly optimize getMedian

- Source/engine/palette.cpp
PR #8027 exposed a bug in `palette_update`.
The `first` argument in SDL palette functions always refers to the first target index (the first source index is always 0).
Fixes poison water following #8027.
> Fix a bug in `palette_update`

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/diabloui.h
- Source/DiabloUI/progress.cpp
- Source/capture.cpp
- Source/controls/touch/renderers.cpp
- Source/diablo.cpp
- Source/engine/dx.cpp
- Source/engine/dx.h
- Source/engine/palette.cpp
- Source/engine/palette.h
- Source/gamemenu.cpp
- Source/interfac.cpp
- Source/levels/setmaps.cpp
- Source/quests.cpp
- Source/utils/attributes.h
- Source/utils/display.h
- Source/utils/palette_blending.cpp
- Source/utils/palette_blending.hpp
- Source/utils/palette_kd_tree.hpp
- Source/utils/static_vector.hpp
- test/palette_blending_benchmark.cpp
- test/palette_blending_test.cpp
Gets rid of `orig_palette`, we now always have only 2 palettes:
1. `logical_palette` - This palette has color cycling / swapping applied but no global effects such as brightness / fade-in.
2. `system_palette` - This palette is the palette that will be used for rendering.
It is usually `logical_palette` with the global brightness setting and fade-in/out applied.
Additionally, we now keep the k-d tree around and use it to update single colors. The colors that are color-cycled / swapped are never included in the k-d tree, so the tree does not need updating on color cycles/swaps.
> Simplify palette handling

- Source/diablo.cpp
- Source/msg.cpp
- Source/player.cpp
Town spells were already being validated by `InitNewSpell()`. I probably included these messages in #7999 by association with `CMD_ATTACK*` messages without properly thinking about whether casting spells in town actually is valid.
This resolves #8017
> Remove overzealous validation logic in spell message handlers

- test/CMakeLists.txt
text_render_integration_test.cpp is [not included](https://github.com/diasurgical/DevilutionX/blob/82868d5dfbb473909a2f5132bd8699b0defbeb3f/test/CMakeLists.txt#L55-L57) in SDL1 build.
> Fix compling tests with sdl1

- Source/CMakeLists.txt
- Source/utils/palette_kd_tree.hpp
Storing color values directly in leaves improves lookup speed, at the cost of a bit more space and a slightly slower `BuildTree`.
Tree size: 360 bytes -> 1119 bytes.
```
Benchmark                                              Time             CPU      Time Old      Time New       CPU Old       CPU New
-----------------------------------------------------------------------------------------------------------------------------------
BM_GenerateBlendedLookupTable_pvalue                 0.0002          0.0002      U Test, Repetitions: 10 vs 10
BM_GenerateBlendedLookupTable_mean                  +0.0116         +0.0117       2245830       2271969       2245300       2271555
BM_GenerateBlendedLookupTable_median                +0.0115         +0.0116       2245978       2271854       2245441 …
```
> Palette kd-tree: Store color values in leaves

- Source/engine/render/light_render.cpp
Further optimization based on the results of benchmarking the per-pixel lighting implementation. When drawing triangles, instead of visiting each pixel individually in every scanline, we can run a handful of computations to determine where the scanline should start and end. Then we fill it in with memset and move on to the next scanline.
> Compute scanlines for triangles in per-pixel light renderer

- test/clx_render_benchmark.cpp
- test/dun_render_benchmark.cpp
- test/palette_blending_benchmark.cpp
This is a simpler way to calculate items/bytes per second. Also fixes `dun_render_benchmark`.
> Benchmarks: Use `state.iterations()`

- Source/engine/palette.cpp
This resolves an issue reported by FireIceTalon on Discord.
https://github.com/user-attachments/assets/223ff51f-200e-4593-9fa3-25e0f02e01c4
---
A little ways up on line 269, we apply the brightness to `srcPalette` and write the result in the `palette` array.
https://github.com/diasurgical/DevilutionX/blob/87c5b333c99132ff22d19a73f9a61d3411afcc48/Source/engine/palette.cpp#L268-L269
The `UpdateSystemPalette()` function also applies brightness to the palette we pass in and writes the result to `system_palette`. By passing `palette` as the parameter to `UpdateSystemPalette()`, we effectively apply brightness twice to the data in `srcPalette`. So we should use `srcPalette` instead to apply the brightness only once.
> Don't apply brightness twice in PaletteFadeIn()

- Source/engine/assets.cpp
- Source/engine/render/text_render.cpp
This PR fixes an issue where changing the `Language` setting doesn't reload SFX. So following these steps would cause the game to end up with the wrong audio.
1. Install `pl.mpq` in the data folder.
2. Start the game client and switch to Polish.
3. Enter a game and trigger an audio cue. The game should be using Polish audio.
4. Go back to the main menu without exiting the game client.
5. Switch language back to English.
6. Enter a game and trigger an audio cue. The game should still be using Polish audio.
The issue here was twofold. First, the `sgSFX` vector caches sound effects in memory, and `OptionLanguageCodeChanged()` didn't flush/reload them. Second, the `pl.mpq` archive would only be removed if there was another audio pack to replace it. English doesn't have an explicit audio pack, …
> Reload SFX when changing language setting

- .github/workflows/3ds.yml
- .github/workflows/switch.yml
1. Debian has been updated to bookworm.
2. gettext is now part of the image, no need to install it.
> GitHub CI: Update 3DS and Switch configs

- Source/CMakeLists.txt
- Source/diablo.cpp
- Source/engine/render/dun_render.cpp
- Source/engine/render/dun_render.hpp
- Source/engine/render/light_render.cpp
- Source/engine/render/light_render.hpp
- Source/engine/render/scrollrt.cpp
- Source/levels/gendung.cpp
- Source/levels/gendung.h
- test/CMakeLists.txt
- test/dun_render_benchmark.cpp
- test/light_render_benchmark.cpp
Does not make `dun_render_benchmark` standalone yet as that will require more untangling.
Benchmark is neutral (small diffs are I think due to noise, e.g. lack of core pinning and background processes on my machine):
```
Benchmark                                                                     Time             CPU      Time Old      Time New       CPU Old       CPU New
----------------------------------------------------------------------------------------------------------------------------------------------------------
Render<LeftTriangle, Solid, FullyLit>_pvalue                                0.0002          0.0002      U Test, Repetitions: 10 vs 10
Render<LeftTriangle, Solid, FullyLit>_mean                                 +0.0119         +0.0120          8377          8477 …
```
> Make `dun_render` a standalone library

- Source/options.cpp
When trying to initialize unpacked mods, the path separator was missing between the "mods" folder and the folder for the specific mod. This led to the strings being concatenated incorrectly, and the mod not being found. With this fix, unpacked mod initialization now works properly.
> Added missing directory separator for unpacked mod initialization

- README.md
Previous link "https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide" doesn't exist.
Updating to "https://github.com/diasurgical/DevilutionX/wiki/Config-File".
> Update 'game settings' link in README

- Source/control.cpp
- Source/panels/partypanel.cpp
- Source/player.cpp
These popped up on my system after the recent merges.
```
.../DevilutionX/Source/player.cpp: In function ‘devilution::ClxSprite devilution::GetPlayerPortraitSprite(Player&)’:
.../DevilutionX/Source/player.cpp:2060:13: warning: unused variable ‘spriteIndex’ [-Wunused-variable]
2060 |         int spriteIndex = 0;
|             ^~~~~~~~~~~
```
```
.../DevilutionX/Source/control.cpp: In function ‘void devilution::{anonymous}::PrintFloatingInfo(const devilution::Surface&)’:
.../DevilutionX/Source/control.cpp:527:13: warning: unused variable ‘yAbove’ [-Wunused-variable]
527 |         int yAbove = anchorY - spriteH - boxH - vPadding;
|             ^~~~~~
.../DevilutionX/Source/control.cpp:528:13: warning: unused variable ‘yBelow’ [-Wunused-variable]
528 |         int yBelow = anchorY + …
```
> Fix compiler warnings

- Source/effects.cpp
The number of loaded SFXs id different for Diablo and Hellfire, not to mention mods.
> Do not assert SFX count as it's not fixed size

- Source/items.cpp
This PR does a small refactor for the code which conditionally writes item info to the floating or non-floating infobox (depending on the settings), along the lines of what was suggested here:
https://github.com/diasurgical/DevilutionX/pull/8103#issuecomment-3178927787
> Small Refactor for the Item Floating/Non-Floating Infobox Writing Code

- Source/diablo.cpp
This is a small PR that removes spaces from the remaining ini indicators in the game/pad mapping area of the code as per the projects preferred standardization here.
> CLEANUP: Standardizing more ini indicators

- Source/controls/plrctrls.cpp
Fixed an issue with the inventory when using a controller that was making 1x1 items clip to an invalid -1 location when picking them up if they are in the last inventory slot.
> Resolved Controller Inventory Issue

- CMake/Assets.cmake
- CMake/functions/trim_retired_files.cmake
Turns out, `add_custom_target()` enables you to specify a command that always runs without depending on a `SYMBOLIC` file as output. So I changed `add_trim_command()` to `add_trim_target()` in addition to adding the dependencies.
> Add dependency to prevent trim from deleting intermediate lang files

- docs/building.md
Turns out, the version of the Windows SDK isn't that important so long as it's high enough to support the features we're using. We don't need to install both Win 10 and Win 11 SDKs in order to build our source code, nor should we need any particular version for the build to support both operating systems. Therefore, I simply modified the documentation to match the version we're targeting in our build scripts.
For the record, here are the versions currently available from Visual Studio Installer (on my system, at least).
* Windows 10 SDK (10.0.19041.0)
* Windows 11 SDK (10.0.22621.0)
* Windows 11 SDK (10.0.26100.4188)
> Adjust build documentation to target current Windows SDK version

- Source/lua/modules/monsters.cpp
- Source/monstdat.cpp
- Source/monstdat.h
This PR reworks the Lua bindings for adding new unique monsters to load from a TSV file, instead of defining the unique monster directly in Lua.
I also removed the ParseMonsterIdIfNotEmpty() function, which is unused, and which I had mistakenly added in a previous PR related to monster-adding Lua bindings.
> Reworked the Lua Bindings for Adding New Unique Monsters to Load from a TSV File

- Source/monstdat.cpp
This PR simplifies the enum parsing for the MonsterAIID, MonsterClass and monster_resistance enums by using the magic_enum library.
> More monstdat Enum Parsing Simplification

- Source/itemdat.cpp
- Source/itemdat.h
- Source/items.cpp
- Source/loadsave.cpp
- Source/lua/modules/dev/items.cpp
- Source/lua/modules/items.cpp
- Source/pack.cpp
- assets/lua/devilutionx/events.lua
- test/items_test.cpp
This PR adds Lua bindings for adding new item types via TSV file loading, similar to the Lua bindings for e.g. adding new monsters or unique items.
As with the add unique item Lua bindings, it also uses mapping IDs when saving/loading the item type, to make it easier to combine different item-adding mods without issue. This only affects added item types: for the default ones, the mapping ID equals their index.
Item type TSV definitions can now add new "uniqueBaseItem" entries as well. The way this is done is the following:
```
reader.read("uniqueBaseItem", item.iItemId, ParseOrAddUniqueBaseItem);
```
When parsing item types, if the unique base item is already present, its ID is just obtained. Otherwise, if it is not present, it will be added to the new …
> Added Lua Bindings for Adding New Items

- CMake/Assets.cmake
- Source/diablo.cpp
- Source/levels/gendung.cpp
- Source/levels/gendung.h
- Source/lua/lua_global.cpp
- Source/monstdat.cpp
- Source/quests.cpp
- Source/quests.h
- Source/textdat.cpp
- Source/textdat.h
- assets/txtdata/quests/questdat.tsv
- test/drlg_l2_test.cpp
- test/drlg_test.hpp
- tools/extract_translation_data.py
This commit moves quest data from the C++ code to a TSV file.
The data is exactly the same as the one previously contained in the `QuestsData` array, but in TSV format.
> Parse Quest Data from TSV

- Source/utils/log.hpp
When compiling with clang, the compiler warns about the lack of return statement in the non-void function fmt::format:
```
/home/csix/diablo/devilutionX-ironman/Source/utils/log.hpp:63:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
/home/csix/diablo/devilutionX-ironman/Source/utils/log.hpp:88:21: note: in instantiation of function template specialization 'devilution::detail::format<unsigned long &>' requested here
auto str = detail::format(fmt, std::forward<Args>(args)...);
^
/home/csix/diablo/devilutionX-ironman/Source/utils/logged_fstream.hpp:74:4: note: in instantiation of function template specialization 'devilution::LogVerbose<unsigned long &>' requested here
LogVerbose(LogCategory::System, fmt, args...);
^ …
```
> log.hpp: fix lack of return when FMT_EXCEPTIONS is disabled

- Packaging/windows/mingw-prep.sh
When running mingw-prep without sudo it would not load the env variables into the sdl2 make.
> Fix mingw-prep.sh sdl2 not working for non-sudo

- .github/workflows/Windows_MinGW_x64.yml
- .github/workflows/Windows_MinGW_x86.yml
- Packaging/windows/mingw-prep.sh
- docs/building.md
- mingw-w64 installs gcc and g++ in i686 and x86-64, so have that simpler instruction instead of breaking it out separately.
- pkg-config-mingw-w64-(i686|x86-64) both select mingw-w64-tools to install, so just preselect to simplify.
- cmake --target package no longer works without smpq.
- move mv libz.dll.a command from an instruction to a command in mingw-prep
- reorganize for a simple read and default to opening 64-bit when opening the mingw heading
> Simplifying MinGW instructions

- Source/CMakeLists.txt
- Source/effects.cpp
- Source/monstdat.cpp
- Source/monstdat.h
- Source/sound_effect_enums.h
- Source/textdat.cpp
- Source/textdat.h
This necessitates dependencies on `magic_enum` in more places but avoids obscure hard-to-debug errors, such as the one seen in the DOS port PR.
> magic_enum: Customize enums where they're declared

- .gitignore
- Source/diablo.cpp
Useful for platforms like DOS where it's not necessarily easy to redirect the log output.
> Add a `--log-to-file` flag

- Source/itemdat.cpp
This PR makes it so that for the item cursor column of item types and unique items, frame numbers can be used instead of item cursor ID strings. This allows them to use the item cursor graphics which are available in Diablo, but have no ID for their frame in the source code (as occurs with a lot of the unused cursor graphics).
> Allow Providing the Item Cursor Frame Number instead of ID in itemdat

- Source/data/value_reader.hpp
- Source/inv.cpp
- Source/items.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/playerdat.cpp
- Source/playerdat.hpp
- assets/txtdata/classes/barbarian/attributes.tsv
- assets/txtdata/classes/bard/attributes.tsv
- assets/txtdata/classes/monk/attributes.tsv
- assets/txtdata/classes/rogue/attributes.tsv
- assets/txtdata/classes/sorcerer/attributes.tsv
- assets/txtdata/classes/warrior/attributes.tsv
This PR adds support for player classes having flags to determine their properties. I made the following player class features which were previously hardcoded into player class flags:
1. Critical Strike (the double damage which Warriors and Barbarians have a chance to deal)
2. Dual Wield (originally hardcoded for the bard)
3. Iron Skin (the Barbarian bonus to AC based on character level)
4. Natural Resistance (the Barbarian bonus to resistance based on character level).
5. Trap Sense (the Rogue property which tells the player whether an object is trapped)
The PlayerClassFlag enum is a uint8_t right now because more bits weren't necessary so far, but if more player class features are dehardcoded into player class flags, then I think it would make sense to make the enum be based on a type …
> Player Class Flags

- Source/CMakeLists.txt
- Source/capture.cpp
- Source/engine/assets.cpp
- Source/engine/demomode.cpp
- Source/engine/palette.cpp
- Source/items.cpp
- Source/loadsave.cpp
- Source/pfile.cpp
- Source/player.cpp
- Source/qol/chatlog.cpp
- Source/utils/sdl2_to_1_2_backports.cpp
- Source/utils/str_cat.cpp
- Source/utils/str_cat.hpp
- test/str_cat_test.cpp
`fmt::format_to` is overkill for our simple formatting needs.
> Replace fmt with utils/str_cat in a few places

- Source/automap.cpp
- Source/engine/render/scrollrt.cpp
- Source/panels/partypanel.cpp
Moves FPS to the top
Map text overlay will change it's height based if the FPS display is on
Party panel is shifted to line up with the text
Party panel will move with the other texts instead of sitting behind it.
> Overlay Text and Party Panel Realignment
