diasurgical/DevilutionX

- README.md
FreeType and HarfBuzz installed from Homebrew cause build issues for 32-bit builds.
> Clarify macOS 32-bit build edge case

- Packaging/fedora/devilutionx.desktop
- Packaging/fedora/devilutionx.spec
This commit provides the necessary files to build DevilutionX for Fedora (and compatible).
I suppose that package maintainers (generally speaking) know how to build for different archs, but if necessary I can also add a note on how to build for 32bit target.
Also it would be nice if we could have a command line switch with which we could specify in which directory the data assets are located.
Like:
`./devilutionx --datadir=/usr/share/devilutionx`
> Packaging files for Fedora

- CMakeLists.txt
By setting -DO_LARGEFILE on the cmake command line, it is actually the same as
setting -DO_LARGEFILE=1. Since this constant is used inside code to set flags,
a file would be opened with both READ_ONLY and READ_WRITE flag set.
This of course will not be allowed by the kernel
> Fixed unforeseen definition of O_LARGEFILE=1

- Packaging/fedora/devilutionx.spec
Currently binary was placed in /usr dir as "bindevilutionx". This pull fix it and place "devilutionx" under /usr/bin/ dir.
Also build was done on latest 0.4.0 source code on Fedora 30.
> Fixed binary location in Fedora's SPEC file and updated version.

- SourceX/miniwin/thread.cpp
An assertion blew up while running a debug build. I've no idea what this does, bit it appears that there is unreachable code. This fix seems reasonable.
> Fix a bad iterator check

- CMakeLists.txt
Visual Studio builds warn about gcc options that the MSVC compiler does not understand.
> Do not pass GCC options to the MSVC compiler/linker

- Brewfile-32bit.rb
Fixes #143 
`cmake` is missing as a dependency in the 32-bit Brewfile.  This PR adds `cmake` to the 32-bit Brewfile.
> Adds cmake to Brewfile-32bit.rb as a dependency

- SourceX/miniwin/dsound.cpp
Fixes #59.
The original DirectSound [volume](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mt708939(v%3Dvs.85)) and [panning](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/mt708938(v=vs.85)) methods both take decibel-based values, in hundredths of a dB (-10000 to 0), but SDL_mixer's methods expect linear values (0 to 128 for [volume](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_27.html), 255 for [panning](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer_80.html)).
Since ["a change in amplitude by a factor of 10 corresponds to a 20 dB change in level"](https://en.wikipedia.org/wiki/Decibel), the conversion can be done like so: `SDLMixerVolume = 10^(DirectSoundVolume / (20 * 100)) * 128`; same goes for the panning, just `* 255` …
> Fix volume scaling

- SourceX/miniwin/dsound.cpp
I accidentally put the `abs()` on the wrong side in #142, so I fixed that, and rearranged the ternary expressions to (hopefully) make the intent more clear.
I also noticed that if `lPan` was 0, then `pan` would be set to 255 instead of 0. I originally added a condition for it, but after thinking for a bit... It shouldn't really matter in practice, since left/right would both end up at 255 anyway. I can add the condition back in if I'm overlooking something.
> Fix panning

- SourceX/DiabloUI/credits.cpp
Hi! 
I've noticed that the credits in this reverse-engineered code was missing the black text shadow behind the white credit text (see video: https://www.youtube.com/watch?v=g-xZeCDXJH4).
It seems for me that the black text shadow behind the white credit text is drawn by first calling
`SGdiTextOut(credit_back_img, v3 + 2, i + 2, 0x1000000, v1, v4);`
which draws black text at the +2-added (x,y)-coordinates that acts as "text shadow", then
`SGdiTextOut(credit_back_img, v3, i, 16777440, v1, v4);`
gets called, which draws the white text. See code at _line 198-199_ in **DiabloUI/credits.cpp**.
This PR fixes this issue according to my guess above :).
> Implemented text shadow at the credits.

- SourceX/miniwin/misc_msg.cpp
Automap zoom-in wasn't working because `SDLK_PLUS` has [no corresponding physical key](https://wiki.libsdl.org/SDL_Keycode). Changing it to `SDLK_EQUALS` fixes the issue.
> Fix automap zoom

- SourceX/dvlnet/tcp_client.cpp
- SourceX/dvlnet/tcp_server.cpp
Just happened to find this problem Visual Studio debug iterator checks while creating new tcp/ip game. I'm no expert on asio but what happens here is essentially:
1. `asio::buffer` is basically pointer + size, so lifetime guarantees for used buffer should be provided by the user.
2. `async_write` is asynchronous so it returns immediately and the actual work is done somewhat later.
3. If `frame` is defined locally it gets freed almost immediately and invalid to use when async work needs to be done.
4. Seems like `send` can be called before other `send` is finished its work, thus storing this buffer as class field is also unsuitable
5. Attaching buffer's lifetime to handler's seems to viable approach in such case.
6. It's not entirely obvious should it be wrapped into `std::shared_ptr` or …
> Fix lifetime of 'frame' buffer in tcp server/client.

- Source/loadsave.cpp
Buffer padding increment for loading and saving MonsterStruct was off by one byte, causing silly values for monster XP 
Fixes #176
> Fix load/save monster padding

- makefile
This PR 
- fixes the "Unknown Author" display on Switch Homebrew Menu (now set to "Devilution Team").
- It also cleans up the Switch Makefile a bit without changing functionality, by removing unused rules and variables and re-arranging things a bit better.
> Clean up Switch makefile, fix Unknown Author on Switch hbmenu

- SourceX/DiabloUI/selhero.cpp
- makefile
- switch/readme-switch.md
This PR
- fixes compilation on Switch (recently broke because selyesno.o was missing)
- adds a readme-switch document (can always be edited later)
> Fix compilation on Switch, add readme for Switch

- Source/loadsave.cpp
LoadMonster and SaveMonster were not skipping some pointers at the end of the struct. I'm not even sure why it works as well as it does - without the fix, I'm still able to load and save monsters correctly, but it looks like other people had situations where this problem comes to light.
> Fix MonstStruct load/save

- Source/diablo.cpp
- Source/dx.cpp
- Source/engine.cpp
- Source/inv.cpp
- Source/palette.cpp
- Source/scrollrt.cpp
- Source/towners.cpp
- SourceX/dx.cpp
- SourceX/sound.cpp
- defs.h
Fixing call sites which were lying about both the current file and line number. The line number specifically was annoying since it is not immediately obvious what it is when skimming function calls.
> Fix invalid file and line constants

- Source/multi.cpp
Makes no sense on non-Windows OSes. Fixes #208
> Fix drive-letter relative path log path

- SourceS/miniwin.h
The following build error was observed when compiling with Clang:
In file included from Source/appfat.cpp:1:
In file included from ./Source/diablo.h:5:
In file included from ./Source/../types.h:52:
In file included from ./SourceS/miniwin.h:19:
In file included from /usr/lib/clang/8.0.1/include/x86intrin.h:29:
In file included from /usr/lib/clang/8.0.1/include/immintrin.h:28:
/usr/lib/clang/8.0.1/include/mmintrin.h:81:40: error: cannot initialize a parameter of type
'__attribute__((__vector_size__(2 * sizeof(int)))) int' (vector of 2 'int' values) with an rvalue of type
'__v2si' (aka 'int')
return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);
^~~~~~~~~~~
Clang version:
$ clang -v
clang version 8.0.1 (tags/RELEASE_801/final)
First I tried to replace the x86intrin.h include with:
static …
> fix Clang build

- Source/interfac.cpp
- Source/pack.cpp
- Source/player.cpp
- Source/scrollrt.cpp
- Source/track.cpp
While no storm functions are called from these source files
it is determined that they included storm in the original
source files as made visible by the inclusion of infinity
in the data segments of the respective source files.
ref: diasurgical/devilution#1695.
> all: remove unused storm imports

- .circleci/config.yml
- .editorconfig
- CMakeLists.txt
- README.md
- SourceS/devilution.h
- SourceS/sdl2_to_1_2_backports.h
- SourceX/DiabloUI/diabloui.cpp
- SourceX/dx.cpp
- SourceX/miniwin/ddraw.cpp
- SourceX/miniwin/ddraw.h
- SourceX/miniwin/misc.cpp
- SourceX/miniwin/misc_dx.cpp
- SourceX/miniwin/misc_msg.cpp
- SourceX/miniwin/thread.cpp
- SourceX/sound.cpp
- SourceX/storm/storm.cpp
- SourceX/storm/storm_dx.cpp
Adds a `USE_SDL1` build option to use SDL v1 instead of v2.
This is useful for porting Diablo onto devices that don't support SDL2,
such as the RetroFW / OpenDingux devices (e.g. RG300 Retro Gaming Handheld)
Not yet supported:
* Fullscreen
* Upscaling
* Audio
Achieved by backporting some functions from SDL2 and scattering a few ifdefs.
I understand if you don't want to merge this.
> Optionally use SDL1 instead of SDL2

- SourceS/sdl2_to_1_2_backports.h
1. Adds RGB888 format support (not used at the moment).
2. Set the alpha mask to 0 for indexed format to fix SRCCOLOR blitting.
(also not used at the moment).
Cherry-picked from #273
> SDL1 Backport header: Color format fix

- .editorconfig
- SourceX/DiabloUI/credits.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/diabloui.h
- SourceX/DiabloUI/mainmenu.cpp
- SourceX/DiabloUI/progress.cpp
- SourceX/DiabloUI/selconn.cpp
- SourceX/DiabloUI/selgame.cpp
- SourceX/DiabloUI/selhero.cpp
- SourceX/DiabloUI/selyesno.cpp
- SourceX/DiabloUI/title.cpp
- SourceX/miniwin/ddraw.cpp
- SourceX/miniwin/ddraw.h
- SourceX/storm/storm.cpp
- SourceX/storm/storm_dx.cpp
Use SDL instead of direct pixel manipulation for menu rendering.
This is a massive performance improvement. The menu animations finally full run speed on my RG300!
Implementation notes:
1. We now load `Art` directly as an `SDL_Surface`.
`SBmpLoadImage` has been modified to assume scanline padding if the input buffer is larger than necessary.
2. We maintain a global `surface_pal_palette_version` to know when to update the palette for an Art before blitting (updating the palette on every `DrawArt` call turned out to be expensive).
3. Masked textures are handled with `SDL_SetColorKey`.
4. credits.cpp has a minor improvement that reduces the size of the destination rect.
~~Unfortunately, it is much slower on a real device than the previous implementation (thus the DO NOT MERGE tag). Any idea …
> Use SDL instead of direct pixel manipulation for menu rendering

- SourceX/dvlnet/tcp_client.cpp
- SourceX/dvlnet/tcp_server.cpp
Fixes the following warnings:
```
SourceX/dvlnet/tcp_client.cpp:104:38:
warning: lambda capture initializers only available with -std=c++14 or -std=gnu++14
SourceX/dvlnet/tcp_server.cpp:142:15:
warning: lambda capture initializers only available with -std=c++14 or -std=gnu++14
```
> dvlnet: More C++11 compatibility

- SourceS/sdl2_to_1_2_backports.h
- SourceX/DiabloUI/credits.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/progress.cpp
- SourceX/dx.cpp
- SourceX/storm/storm.cpp
```
SourceX/storm/storm.cpp:27:10: note: ‘snprintf’ output between 11 and 270 bytes into a destination of size 260
snprintf(file_path, DVL_MAX_PATH, "%sdiablo.ini", path);
```
SDL1 warnings:
```
devilutionX/SourceX/dx.cpp:199:24: warning: narrowing conversion of ‘(int)dwX’ from ‘int’ to ‘Sint16’ {aka ‘short int’} inside { } [-Wnarrowing]
SDL_Rect dst_rect = { (int)dwX, (int)dwY, w, h };
SourceS/sdl2_to_1_2_backports.h:616:18: warning: comparison is always false due to limited range of data type [-Wtype-limits]
if (final_dst.w < 0)
SourceS/sdl2_to_1_2_backports.h:777:24: warning: comparison of integer expressions of different signedness: ‘const int’ and ‘long unsigned int’ [-Wsign-compare]
if ((rc > 0) && (rc < sizeof(path))) {
~~~^~~~~~~~~~~~~~
SourceX/storm/storm.cpp:479:16: warning: …
```
> Fix more compilation warnings

- CMakeLists.txt
- README.md
- Source/drlg_l4.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/diabloui.h
- SourceX/DiabloUI/title.cpp
- SourceX/sound.cpp
This also fixes a couple of issues caused by bad merges
None of the UI parts are implemented, so you can crash the game by trying to create a rouge or sorcerer.
> Add option to compile shareware version

- CMakeLists.txt
- SourceX/.clang-format
- SourceX/DiabloUI/art.cpp
- SourceX/DiabloUI/art.h
- SourceX/DiabloUI/art_draw.cpp
- SourceX/DiabloUI/art_draw.h
- SourceX/DiabloUI/credits.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/diabloui.h
- SourceX/DiabloUI/fonts.cpp
- SourceX/DiabloUI/fonts.h
- SourceX/DiabloUI/progress.cpp
- SourceX/DiabloUI/selconn.cpp
- SourceX/DiabloUI/selgame.cpp
- SourceX/DiabloUI/selyesno.cpp
- SourceX/DiabloUI/text.cpp
- SourceX/DiabloUI/text.h
- SourceX/DiabloUI/text_draw.cpp
- SourceX/DiabloUI/text_draw.h
- SourceX/DiabloUI/title.cpp
Start moving stuff out of the diabloui.cpp file.
This is a commit on top of scrollbar (#307).
>  DiabloUI: Move art and text code out of diablo.cpp 

- SourceX/DiabloUI/art.cpp
- SourceX/DiabloUI/art.h
- SourceX/DiabloUI/art_draw.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/dialogs.cpp
- SourceX/DiabloUI/dialogs.h
- SourceX/DiabloUI/fonts.cpp
- SourceX/DiabloUI/text_draw.cpp
- SourceX/DiabloUI/ttf_render_wrapped.cpp
- SourceX/dx.cpp
1. TTF no longer crashes on exit.
2. Art failing to load simply isn't rendered instead of crashing in random places.
3. Fixes empty line rendering in ttf_render_wrapped.cpp
4. dx_cleanup is now idempotent.
> Minor cleanup of internal error handling

- Source/appfat.cpp
- Source/init.cpp
- SourceS/sdl2_to_1_2_backports.h
- SourceX/DiabloUI/art.cpp
- SourceX/DiabloUI/art.h
- SourceX/DiabloUI/art_draw.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/diabloui.h
- SourceX/DiabloUI/dialogs.cpp
- SourceX/DiabloUI/dialogs.h
- SourceX/DiabloUI/fonts.cpp
- SourceX/DiabloUI/text_draw.cpp
- SourceX/DiabloUI/ttf_render_wrapped.cpp
- SourceX/dx.cpp
- SourceX/miniwin/misc.cpp
This is a PR on top of #314 
The diabdat.mpq absence error is handled by stubbing the art with solid colors:
Refs #303
> Make Source/ dialogs call DiabloUI/dialogs.cpp

- SourceX/DiabloUI/selhero.cpp
Fixes #311. Feels kind of hacky, I just prepend to `selhero_heros[]` using `memmove()`. As always, I'm open to suggestions if there's a better solution.
> Fix hero order

- Source/render.cpp
> Source/render.cpp:130:47: runtime error: load of misaligned address 0x7fea0df260da for type 'DWORD', which requires 4 byte alignment
> Source/render.cpp:130:26: runtime error: store to misaligned address 0x7fea5796ff62 for type 'DWORD', which requires 4 byte alignment
> Fix UB: load/store of misaligned render.cpp:130

- CMakeLists.txt
This is needed when compiling on non-Linux platforms, such as Amiga,
Switch, etc.
> CMake: Explicitly enable POSIX extensions

- Source/sha.cpp
- Source/sha.h
- structs.h
1. Shifting a negative integer.
2. Signed integer overflow.
> SHA: Fix some implementation-defined behaviour

- Source/player.cpp
- Source/render.cpp
- Source/sha.cpp
We disable these warnings because all compilers implement signed shifts in the same way according to the N2218 proposal to standardize signed shift behaviour:
http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2218.htm
On Clang we can do this globally via a sanitizer blacklist, but that's not supported on GCC (yet):
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61978
> Disable some signed shift UBSAN warnings

- SourceX/dx.cpp
- SourceX/miniwin/misc.cpp
- SourceX/storm/storm.cpp
Massively improves renderer performance.
While benchmarking the credits with scaling on, I realized there was a problem in how we set up the renderer.
It used an RGBA texture internally, causing blits to be *very* slow (RGBA blitting in software is terrible, as it has to blend instead of copy).
This simple change makes rendering ~3-5x faster. Should hopefully fix all performance / energy consumption issues on slower devices.
@AJenbo @vanfanel
> Renderer texture: use RGB888 instead of RGBA8888

- CMake/git.cmake
- CMakeLists.txt
1. Move `project` before `check_ipo_supported`, so that the check knows which languages to check.
2. Better error message if LTO is not supported.
3. Use a separate flag for LTO
4. Enable LTO for the nightly build.
5. Move git commands to a separate file.
>  CMake: LTO improvements 

- SourceX/DiabloUI/credits.cpp
`palette->colors[50]` was the same as `palette->colors[224]` for a few frames.
> credits.cpp: Hard-code a safe mask color

- Source/diablo.h
- SourceS/sdl2_to_1_2_backports.h
- SourceS/sdl_compat.h
- SourceX/DiabloUI/art.cpp
- SourceX/DiabloUI/art_draw.cpp
- SourceX/DiabloUI/credits.cpp
- SourceX/DiabloUI/ttf_render_wrapped.cpp
- SourceX/dx.cpp
- SourceX/storm/storm.cpp
- SourceX/storm/storm_dx.cpp
SDL 1 and 2 handle surface palettes very differently.
This adds a few compatibility functions that do the right thing
depending on the SDL version.
This lets us remove many instances of `#ifdef USE_SDL1`
> Simplify SDL1/2 palette handling

- CMakeLists.txt
- SourceX/dx.cpp
- SourceX/miniwin/ddraw.cpp
- SourceX/miniwin/ddraw.h
- SourceX/storm/storm.cpp
It is possible that a window surface gets invalidated since we initially
obtained it. We need to call GetWindowSurface every time we want one,
instead of keeping a pointer to a possibly stale one.
See https://hg.libsdl.org/SDL/file/369b01006eb2/src/video/SDL_video.c#l2312
Possible fix for a part of #351
> Get a fresh window surface before rendering to it

- SourceX/miniwin/misc.cpp
Turns out this causes flickering when consuming a potion in the belt on RG300.
Since it also doesn't work on Amiga, just remove it for now.
> SDL1: Remove SDL_DOUBLEBUF

- CMakeLists.txt
- SourceX/DiabloUI/selconn.cpp
- SourceX/DiabloUI/selgame.cpp
- SourceX/dvlnet/abstract_net.cpp
- enums.h
This fixes some "multi-character character constant" warnings. See https://github.com/diasurgical/devilutionX/issues/279. I tried to comply with existing naming and coding style, but feedback is always welcome. =)
Tested on Fedora 30 x86_64:
- Single player game is OK
- Multiplayer game with TCP is OK
This contribution is sponsored by my company, [Genymobile](https://github.com/Genymobile), for #hacktoberfest.
> Use an enum for connection type

- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/diabloui.h
- SourceX/DiabloUI/fonts.cpp
- SourceX/DiabloUI/mainmenu.cpp
Declare `const char*` arguments to get proper string conversion. Some of these warnings still remain, as it involves code from Source/ directory. This is why I kept the `-Wno-write-strings`.
According to https://github.com/diasurgical/devilutionX/issues/279, those fixes should not be made outside of SourceX/. But if I have the green light, I will be happy to fix them all. =)
> Fix some write-strings warnings

- Source/control.cpp
The OOB here was in `_pSplLvl[spl]`.
The value of `SPL_INVALID` is defined as `0xFFFFFFFF`, which is `-1` if you're lucky with the `sizeof(int)`.
The fix is 2-fold:
1. Change the type of `spl` to `int` to avoid depending on `sizeof(int)`.
2. Do not access the array when `spl == SPL_INVALID`.
By the way, perhaps `SPL_INVALID` was defined as `-1` in the original game?
> Fix OOB in DrawSpell

- SourceX/DiabloUI/diabloui.cpp
- SourceX/dx.cpp
- SourceX/miniwin/ddraw.cpp
- SourceX/miniwin/ddraw.h
- SourceX/miniwin/dsound.h
- SourceX/miniwin/misc.cpp
- SourceX/miniwin/misc_msg.cpp
- SourceX/storm/storm.cpp
Background: Only some handheld devices support auto-scaling. E.g. the LDK has a screen with 320x480 resolution (non-square pixels!), so we need to scale in software.
If the target surface resolution is smaller than `SCREEN_*`, we need to scale manually.
Hardware auto-scaler check for jz4760 provided by @jbanes and @scooterpsu
NOTE: This doesn't implement upscaling, but rather scaling when output surface size is different from logical size. With this, implementing upscaling is trivial but perhaps unnecessary for SDL1.
> Handle scaling for SDL1

- structs.h
Updates #449.
**Note**: this PR is not yet ready for merge. I just want to see where the build fails on Windows using the CI to build.
> use uint64_t instead of unsigned __int64 in structs.h

- SourceX/miniwin/misc.cpp
Was previously crashing with division-by-zero as refreshRate was not set
> Fix FPS limiting on SDL1

- Source/missiles.cpp
- Source/player.cpp
- Source/scrollrt.cpp
- SourceX/controls/game_controls.cpp
- SourceX/controls/plrctrls.cpp
- SourceX/controls/plrctrls.h
- SourceX/miniwin/misc_msg.cpp
Spells will now target either the appropriate highlighted actor or the
current direction.
Wish list:
- Teleport only lets you jump to the other side of a 1 unit thick wall and only if standing next to it.
- <s>Trap Disarm, Heal Other, Resurrect and Telekinesis should trigger instantly, and do not fire if no target.</s>
- Telekinesis only looks for the item next to you.
This solves multiple point on https://github.com/diasurgical/devilutionX/issues/418
> [controlls] Prioritize spell targets

- SourceX/controls/plrctrls.cpp
On RG300 frame rate drops significantly when doing mele combat in a doorway, this happens as monsters on the inside of the room are not reachable (path blocked by other monsters) and therefor FindPath does 300 steps outside the room trying to find each monster.
This gives between 2x-10x performance improvement to mele only player auto-aim performance.
Further improvements could be made by ordering enemies by minimal distance. Since we will still do slow searches if we start with the unreachable monsters.
Also doing a continue in `while ((next_node = GetNextPath()))` if max distance is exceeded will further improve performance as it will drop futile paths early on.
> Controll Aim performance

- SourceX/controls/touch.cpp
- SourceX/miniwin/misc.cpp
The "clean-up" commit broke touch on Switch. I managed to get it back. Maybe by looking at my changes you can figure out the actual system-independent logic to use. It is certainly above my head. One thing to note is that touch coords go from 0 to 1 and represent the touch surface (not the SDL Viewport). So if the touch coordinate is 0 it means the touch happened on the far left of the touchscreen, regardless what is displayed there. In case of this game, there is a black border there, because game is displayed as 4:3 centered on a 16:9 touchscreen
I removed two ifdefs regarding window and renderer that were indeed unnecesary.
> [SWITCH] Fix touch and remove unneeded ifdefs

- SourceX/DiabloUI/diabloui.cpp
Previously the clipboard contents were limited to
SDL_TEXTINPUTEVENT_TEXT_SIZE-1 (31 characters).
This is not necessary since the contents of the clipboard are written
directly to the UI element's buffer.
This is especially useful when pasting IPv6 addresses.
> Do not limit clipboard paste to 31 characters.

- Packaging/OpenDingux/build.sh
- Packaging/OpenDingux/buildroot_rg350_defconfig
It's basically the same as before but with FMA instruction disabled
(known to be buggy on some (all?) Ingenic CPUs)
This doesn't fix any crashes / have any impact as far as I can tell
> OpenDingux: Use xburst arch for RetroFW builds

- SourceX/miniwin/misc.cpp
RetroFW 2.0 changed the location of the IPU flag from `/proc/jz/ipu_ratio` to `/proc/jz/ipu`.
> RetroFW: IPU detection for RetroFW 2.0

- Packaging/OpenDingux/build.sh
Previously, there was an issue with the RG350 buildroot that necessitated building the entire thing.
That issue has been fixed and we can now build only the minimal set of dependencies (same as we do for RetroFW).
> RG350 buildroot: Only build dependencies

- CMakeLists.txt
- Packaging/OpenDingux/devilutionx-retrofw.man.txt
- Source/control.cpp
- Source/control.h
- Source/scrollrt.cpp
- SourceX/controls/controller_buttons.h
- SourceX/controls/controller_motion.cpp
- SourceX/controls/devices/kbcontroller.cpp
- SourceX/controls/game_controls.cpp
- SourceX/controls/game_controls.h
- SourceX/controls/modifier_hints.cpp
- SourceX/controls/modifier_hints.h
- SourceX/controls/plrctrls.cpp
- SourceX/controls/plrctrls.h
1. Makes START a modifier key.
2. Main modifier actions are now displayed as hints while the modifier is pressed.
3. Mouse simulation now available on all controllers:
SELECT + D-Pad to move mouse
SELECT + Left/Right should button to click
START +    | Action
---------- | ------
SELECT     | Menu
UP         | Menu
DOWN       | Map
LEFT       | Character info
RIGHT      | Inventory
B (Bottom) | Spell book
Y (Left)   | Quest log
This makes all actions available on controllers without sticks and ZL/ZR.
Alternative hint positioning:
[devilutionx-retrofw.ipk.zip](https://github.com/diasurgical/devilutionX/files/4023364/devilutionx-retrofw.ipk.zip)
> Controller improvements: START modifier and hints

- SourceX/dx.cpp
Previously, we were copying the colors onto the surface's own palette
that was then immediately replaced by `palette`.
> dx_create_back_buffer: Minor improvement for SDL2

- Source/mpqapi.cpp
- SourceS/file_util.h
Ideally, we'd avoid needing to resize the file by not writing excessive data to it in the first place but I don't understand this code well-enough to do that.
> mpqapi: Use <fstream> instead of custom functions

- Source/multi.cpp
- enums.h
Previously, single-player games initialized a TCP connection!
Changes this to loopback.
Refs #555
> Single-player: Use loopback instead of TCP

- CMake/Findsodium.cmake
jedisct1/libsodium decided not to maintain this, so rebase on
facebookincubator/fizz as that appears to be the defacto upstream now.
There are still a few differences that we should align and hopfully
upstream.
> Reformat Findsodium.cmake

- enums.h
DiabloUI selconn.cp relies on the enum values to be ordered in the same
way as the UI items (e.g. for keyboard navigation).
This restores the order to what it was prior to:
https://github.com/diasurgical/devilutionX/commit/4e29a4b8aa728c1aa65b0686f82ac441d54af780
> Fix conn_type enum order

- Source/dx.h
- Source/palette.cpp
- SourceX/DiabloUI/art_draw.cpp
- SourceX/DiabloUI/credits.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/progress.cpp
- SourceX/DiabloUI/text_draw.cpp
- SourceX/dx.cpp
This removes the use of the backbuffer (pal_surface) during the menu.
Fixes fades not reset when switching to a new menu before fade had
ended.
Fixes incorrect start position for credits.
Note: We can probably improve performance in a later PR by converting the surfaces at load time, possibly even scaling them as well.
> Render menu directly to the output surface

- SourceS/sdl2_to_1_2_backports.h
- SourceS/sdl_compat.h
- SourceX/DiabloUI/art.cpp
- SourceX/DiabloUI/art_draw.cpp
- SourceX/DiabloUI/credits.cpp
- SourceX/display.cpp
- SourceX/display.h
- SourceX/dx.cpp
Fixes #594
For the menu, we scale the surface at load time and use `SDL_BlitSurface`.
For the game, we use `Blit` where we now scale before blitting if the surface has a color key.
> Blit: Fix scaled output handling

- SourceX/display.cpp
- SourceX/display.h
- SourceX/dx.cpp
- SourceX/storm/storm.cpp
Set the video mode close to the SVid resolution while preserving aspect ratio.
Restore the video mode once the video has finished playing.
> SDL1: Avoid software-scaling SVid when possible

- CMakeLists.txt
- SourceX/display.cpp
RetroFW 2.0 brought IPU scaler support to all devices and we now require RetroFW 2.0+.
> RetroFW: Remove IPU scaler check

- SourceX/DiabloUI/art.cpp
- SourceX/DiabloUI/art.h
- SourceX/DiabloUI/button.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/text_draw.cpp
- SourceX/dx.cpp
Was all kinds of broken previously:
This is a follow-up to #595
> DiabloUI: Fix software scaling along the X axis

- Packaging/amiga/prep.sh
- README.md
1. Build in `build-amiga` to have a separate Amiga cmake cache.
2. Place downloaded/built dependcies into `build-amiga/deps` instead of the root directory.
> Amiga build command fixes

- SourceS/sdl2_to_1_2_backports.h
snprintf was used incorrectly - its arguments cannot overlap
> Fix SDL_PrefPath on SDL1 for non-Amiga

- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/diabloui.h
- SourceX/DiabloUI/mainmenu.cpp
This affects both the B button and the Esc key
Fixes #603
> mainmenu: Focus on the exit item before exiting

- Packaging/amiga/Dockerfile
- README.md
This avoids having to run `prep.sh` every time after starting the container.
The container can be run without arguments to build DevilutionX in release mode.
> Amiga Dockerfile with default build command

- .clang-format
- CMakeLists.txt
- Source/mpqapi.cpp
- Source/mpqapi.h
- SourceS/file_util.h
- SourceT/file_util_test.cpp
1. Do not rely on stream positions for getting the initial file size.
2. Remove most `seek` calls that were unnecessary.
3. Replace magic numbers with constants.
4. A class to manage archive lifetime and all associated data.
5. Works around save issue on Amiga
@Cowcat5150, could you please test this?
> mpqapi cleanup

- .travis.yml
Works around https://github.com/Homebrew/homebrew-bundle/issues/646
This fixes the build but costs 100 seconds.
> Fix macOS travis build

- Source/dx.h
- Source/palette.cpp
- SourceX/dx.cpp
Use CreatePalette_ in a similar fashion as we did with random_ and
SetCursor_ to avoid conflicts
Fixes #641.
> Resolve CreatePalette name conflict

- SourceX/display.cpp
> Default to 60hz if the driver doesn't return a usable value

- Packaging/OpenDingux/gkd350h-manual.txt
- Packaging/OpenDingux/retrofw-manual.txt
- Packaging/OpenDingux/rg350-manual.txt
- README.md
- SourceX/controls/game_controls.cpp
It's common to access char and inventory and this is easier to press than Start + ←/→ on devices that have shoulder buttons
> Map Start + L1/R1 to char/inventory

- Source/gendung.cpp
- Source/render.h
- Source/scrollrt.cpp
This fixes several render issues and removes a hack that prevents us from doing proper transparency:
(eflag double rendering, breaks true transparency, and overwrites items on the other side of walls)
(non-diamond shaped tiles being overwritten by the next tile row)
(player appearing on top of trees in town)
Skeleton on the wrong side of sarcophagous when spawning
> Fix render order

- Source/render.cpp
- Source/scrollrt.cpp
- Source/scrollrt.h
This fixes some minor rendering issues introduced when separating the ground from the rest of the world, reported by @majek 
https://cdn.discordapp.com/attachments/518541192993046562/689494427148091423/unknown.png
> Fix rendering the ground part of foliage

- CMakeLists.txt
The dollar sign that was being used for gcc functions to override the __FILE__ definition is not handled correctly by ninja-build. I couldn't figure out a way to escape it and make it work, so I just replaced the mechanism to not use those functions. Now we iterate through every source file and set the __FILE__ definition manually with CMake. I think this is a bit clearer anyway since we are using CMake functions instead of gcc functions that seem a bit obscure.
Fixes #490
> Fix ninja-build build error

- .travis.yml
Travis MacOS image has been updated but only for Xcode 11:
https://changelog.travis-ci.com/xcode-11-3-1-xcode-11-2-1-xcode-11-1-and-xcode11-images-updated-142286
Removes the workaround and updates the image version to Xcode 11
> .travis.yml: Remove workaround (fixes macOS build)

- .circleci/config.yml
The `cmake` package in `debian-stretch` has recently been updated: https://packages.debian.org/stretch-backports/cmake
This new version of `cmake` depends on a version of `libarchive13` that is only available in `stretch-backports-sloppy`.
To allow `libarchive13` to be installed from `stretch-backports-sloppy` I've added the `debian-stretch-sloppy` "suite" and changed `-t stretch-backports` to `-t 'stretch-backports*'`.
When merging this please squash the commits ("Squash and merge" in GitHub) and copy subject and description from the PR.
> Fix CI Debian Stretch build

- Source/scrollrt.cpp
This fixes the new render issues found by @mewmew and @majek
The fix here mostly involves more accurately calculating when the fixes should be applied.
It also applies the tree-fix more appropriately which fixes trees in the right edge of the screen also:
> Probe for null tiles and arches when applying anit-eflag rendered fix

- CMakeLists.txt
- Packaging/OpenDingux/build.sh
- Packaging/OpenDingux/targets.sh
- Packaging/cpi-gamesh/build.sh
Instead of having a bool option for each target platform,
make it a STRINGS property (basically an enum).
> CMake: Cleanup target platform

- .travis.yml
The `deployment` condition is incorrect which yields following error in the Travis CI console:
```
/home/travis/.travis/job_stages: line 737: expected `)'
/home/travis/.travis/job_stages: line 737: syntax error near `AND'
/home/travis/.travis/job_stages: line 737: `  if [[ ($TRAVIS_OS_NAME = linux AND $TRAVIS_CPU_ARCH = ppc64le) && ("$TRAVIS_TAG" != "") ]]; then'
```
PLEASE DO NOT MERGE YET
> [WIP] Fix travis pipeline

- Source/minitext.cpp
Scrolling texts were abruptly closing while the audio played right. This patch fixes a simple error on the scrolling loop so the correct variable is used to make the scrolling happens
> Fix issue with NPC/Quest text scrolling

- CMake/rg350_defs.cmake
- CMakeLists.txt
- SourceX/controls/menu_controls.cpp
- SourceX/controls/remap_keyboard.h
- SourceX/miniwin/misc_msg.cpp
Adds a `REMAP_KEYBOARD_KEYS` CMake option and uses it to map the "Power"
button to the menu on RG350 and GKD350h.
This remapping applies wherever Game or Menu controls apply.
> Allow re-mapping keyboard keys

- SourceX/DiabloUI/selgame.cpp
Right now we update heroLevel only on "CreateGame" code. This
means you can't enter nightmare/hell game at all - unless you
do createGame first. Let's set the heroLevel global variable in both
create and join game cases.
> Bugfix: allow players of level 20 to enter nightmare game

- 3rdParty/Storm/Source/storm.h
- Source/diablo.cpp
- SourceX/storm/storm.cpp
This implements support for `--save-dir` (as described in #720).
Unfortunately `ini` file is initialized as static variable, before we can change `prefPath`: https://github.com/diasurgical/devilutionX/blob/0fddb655e3ef855b43166e720252ba1736197ccb/SourceX/storm/storm.cpp#L39
`SourceX/storm/storm.cpp` and/or `3rdParty/radon/File` may need to be modified to workaround that (i was thinking about initializing `radon::File` only at first access to ini file, but i am not sure if that would be ok).
@AJenbo would further modifications to SourceX/storm/storm.cpp` be OK?
> Implement `--save-dir` CLI option (#720)

- SourceX/DiabloUI/selgame.cpp
Just noticed that i did not update description text with #741 changes.
This adds "or a hostname" to the text.
> Fix description text for "join game" option

- SourceX/storm/storm.cpp
This does not check why `SFileFreeChunk` and/or `SFileDdaDestroy` were called for the same chunk of data. It simply makes sure that once the chunk is freed it's set to `NULL`, so next call will not trigger `Mix_FreeChunk` and error.
This fixes cleanup crash i could reproduce every time by simply starting/loading game, gossiping with NPC/Townsfolk and quitting game (as described at https://github.com/diasurgical/devilutionX/issues/717#issuecomment-634628920).
This may fix both #717 and #725.
> Prevent double free of sound chunk in storm

- SourceX/display.cpp
This PR introduces the option to enable integer scaling in DevilutionX. It can be enabled by setting a new `diablo.ini` flag called `integer scaling`, which can have both a `0` (disabled) and `1` (enabled) values. The default is `0` to maintain current behavior.
This results in optimal scaling of 2D assets by ensuring that every pixel is stable during scaling: each pixel will always end up being N times bigger in the scaled image, no matter its position. i.e. a single pixel in the original 640x480 frame becomes 4 pixels (2x2) on 1280x960 or 9 pixels (3x3) on 1440p.
On a normal non-integer scaling, each column and row on the screen will have to fit a wider area that is not a perfect multiple of the original image. This introduces rounding differences resulting in variable pixel widths …
> Add integer scaling support. Disabled by default.

- Source/objects.cpp
The AddBarrel function was not checking the type of the barrel when
generating the oVar2. This led to skeletons being pre-spawned in
explosive barrels; except that explosive barrels do not trigger the
spawn, resulting in unreachable monsters sitting at (0, 0) even after a
full clear.
While this does not affect functionality of regular Diablo gameplay, it
potentially affects modders who would like to use the nummonsters
global variable to check for full clears.
> Fixing explosive barrels prespawning skeletons

- .circleci/config.yml
download.libsodium.org is apparently sunning an untrusted version of SSL
> Fix nightly Windows x86 builds

- SourceX/display.cpp
- SourceX/display.h
- SourceX/dx.cpp
This PR softcodes the 'VSYNC' option when creating the SDL renderer, allowing one to change the vsync setting through standard `diablo.ini` configuration.
The new setting is called `vsync` and can have values `0` (disabled) or `1` (enabled). As with other settings, if the flag is not found, it will be defaulted (to `1` in this case to retain old behavior) and saved back to configuration.
This resolves #782 .
> Softcode VSYNC setting. Enabled by default.

- .circleci/config.yml
As of 20200730 the latest devkitpro/devkita64 image has been failing to start because of UID issues.
https://github.com/devkitPro/docker/issues/9
> Use older devkitpro/devkita64 image

- CMakeLists.txt
- SourceX/devilutionx.exe.manifest
This PR adds a new flag into the games `.exe`'s manifest to indicate that the application is DPI aware. The setting we are using is "Per Monitor", which causes Windows to publish full monitor pixel range to our application even if the DPI settings in Windows are not set to 100% scale, and instructs it to not perform any further scaling of it's own.
This is equivalent to setting the DPI override flag on the `exe`'s properties to `Application`:
This change results in correct image scaling regardless of external Windows scaling settings.
We are using the "Per Monitor v1" flag along with the `<dpiAware>` setting because they are compatible with older versions of Windows. The more modern, v2 flag and `<dpiAwareness>` setting only works with Windows 10 and doesn't provide anything in particular …
> Mark executable as DPI aware (per monitor)

- Source/monster.cpp
This PR fixes a small formatting inconsistency between how monster data is presented compared to how item data is presented in the information panel, by removing an extra white space character before the colon `:` character on all labelled monster data.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/461579/92979887-6e274700-f46a-11ea-8bc5-c2685384ad67.png) | ![image](https://user-images.githubusercontent.com/461579/92980054-0c1b1180-f46b-11ea-9cd8-b370f892fb49.png) |
| ![image](https://user-images.githubusercontent.com/461579/92979901-7c756300-f46a-11ea-840b-a969e991bce1.png) | ![image](https://user-images.githubusercontent.com/461579/92979901-7c756300-f46a-11ea-840b-a969e991bce1.png) |
This resolves #803
> Remove blank space before ':' on monster info

- Source/inv.cpp
Change Inventory cell table so that cells line up consistently. Previously Cells would drift out of X alignment from left to right, with right most cells being 2-3 pixels out. Y alignment on the 4th inventory row was also 1 pixel out of alignment, resulting in the dividing line above the 4th row being red when occupied instead of while like the other rows.
> align inventory cell backgrounds with sprite

- Source/setmaps.cpp
This PR renames the "Chamber of Bone" level to match all other references to it in the game for consistency.
This resolves #842
> Rename "Bone Chamber" level to "Chamber of Bone"

- CMakeLists.txt
- SourceS/sdl2_to_1_2_backports.cpp
- SourceS/sdl2_to_1_2_backports.h
The static bool means there's one copy of the variable per compilation
unit using the header. So changing its value in one compilation unit
doesn't affect the other compilation units. This is clearly not what is
wanted here.
Fixing this requires adding a CPP in SourceS. This is the first one
there, I hope it's not an issue. The sdl2_to_1_2_backports should only
be used with SDL1 so I only include it in the list of sources for SDL1
builds. I'm not familiar with cmake so I hope I don't do anything stupid
there!
> Fix entering player's name with SDL 1.

- SourceX/DiabloUI/diabloui.cpp
Fixes #869
This was missed when backporting Switch Keyboard fix in
3ef2228d859ef26c0b4a9f14ae8b0c97516e2260
> Fix keyboard not working for non-Switch in menu

- CMakeLists.txt
Using Ravenports, devilutionX has been available on DragonFly BSD, too, for a while now. This proposed change would allow us to drop one local compatibility patch.
> Handle DragonFly BSD in CMakeLists.txt

- 3rdParty/Storm/Source/storm.h
- 3rdParty/StormLib/src/SFileOpenArchive.cpp
- 3rdParty/StormLib/src/StormPort.h
- CMakeLists.txt
- Source/capture.cpp
- Source/diablo.cpp
- Source/init.cpp
- Source/init.h
- Source/pfile.cpp
- Source/pfile.h
- Source/restrict.cpp
- SourceS/file_util.h
- SourceS/paths.cpp
- SourceS/paths.h
- SourceS/storm_full.h
- SourceX/storm/storm.cpp
- structs.h
Do not limit filesystem path lengths for MPQs, save files, and `diablo.ini`.
Re-implementation of #299
The `MAX_PATH` constant remains but now only limits path lengths within the MPQs.
The functions `pfile_strcpy` and `pfile_get_save_path` are no longer used.
Tested with:
```
build/devilutionx --save-dir /home/gleb/tmp/veryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPath/veryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPath/veryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPath --data-dir /home/gleb/tmp/veryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLongPathveryLo …
```
> Remove MAX_PATH restriction

- Source/render.cpp
This PR improves the performance of the RenderLine function. Here are my measurements using `perf`:
- Old version:
```
Samples: 79K of event 'cycles:u', Event count (approx.): 48250454190
Overhead  Command         Shared Object               Symbol
45.27%  devilutionx     devilutionx                 [.] RenderTile
21.95%  devilutionx     libc-2.31.so                [.] __memmove_avx_unaligned_erms
2.03%  devilutionx     libSDL2-2.0.so.0.12.0       [.] 0x000000000008cc02
1.99%  devilutionx     libSDL2-2.0.so.0.12.0       [.] 0x000000000008cbe0
1.74%  devilutionx     devilutionx                 [.] dvl::scrollrt_draw_dungeon
1.64%  devilutionx     libSDL2-2.0.so.0.12.0       [.] 0x000000000008cbf1
```
- New version:
```
Samples: 59K of event 'cycles:u', Event count (approx.): 35819475280 …
```
> Improvements to the `RenderLine()` function

- Source/sha.cpp
Fixes saves in x64-Release in visual studio 2017 (and older?) - it worked properly in vs2019, hopefully this fix makes it work in the cases where it didn't and doesn't affect when it did xD
> fix saves in x64-release

- SourceX/controls/controller.h
- SourceX/controls/controller_motion.cpp
- SourceX/controls/controller_motion.h
- SourceX/controls/game_controls.cpp
- SourceX/controls/game_controls.h
- SourceX/miniwin/misc_msg.cpp
Broken in https://github.com/diasurgical/devilutionX/commit/01401a16c70213db7a9a84196dee354a2ebc11a3
`ToControllerButtonEvent` must only be called once per SDL event because of how it handles L2/R2
> Controller: Fix L2/R2 handling

- Source/inv.cpp
- Source/items.cpp
- Source/player.cpp
- Source/spells.cpp
- Source/spells.h
This includes a few changes related to how the player's readied spell is validated. It extracts common logic into `spells.cpp`, simplifies the logic a little bit and adds some documentation around the behavior.
> Extract valid readied spell logic

- CMakeLists.txt
FreeBSD specific # Enable POSIX extensions such as `readlink` and `ftruncate`.
Without it doesn't build:
https://termbin.com/duv8
Right now, this is the only patch needed to build devilutionX successfully on FBSD (rest of patches are just cmake tweaks, install paths, etc)
Thanks,
Nuno Teixeira
> Update CMakeLists.txt: FreeBSD specific POSIX extensions

- Source/render.cpp
This should fix issue #941, and introduce compile-time and runtime checks for corner cases. The fallback for `count_leading_zeros` when the compiler is not gcc or clang has also been improved using binary search.
> `RenderLine()` function fix for issue #941

- Source/diablo.cpp
- Source/quests.cpp
- Source/quests.h
This would add a switch --allquests which would enable all the quests to spawn in Singleplayer. Multiplayer would be unaffected.
> Add --allquests debug switch for Singleplayer

- Source/drlg_l4.cpp
Sometimes on level 15 the player can teleport to lazarus' lair by walking on a "random" tile because that tile hasn't been converted to a mini tile yet. This ports the fix from the PSX version of Diablo. Since the dungeon is generated each time, it only sets the coordinates when the portal is active.
ref: https://github.com/diabpsx/skeleton/blob/master/JAP_1998_05_29/DIABPSX/SOURCE/DRLG_L4.CPP#L2683
Bug found by @NiteKat
> Fix lazarus staff skip bug

- Source/inv.cpp
- enums.h
If you held quest items over from a previous game, such as Arkaine's Valor, then bring them to a new game where that quest didn't spawn, it can erroneously set the quest status from not available to completed. If you spawn the dungeon, go to a different level, pick the item up, then come back, the dungeon will be messed up as it will spawn the quest set pieces.
As a good side effect "May the spirit of Arkaine protect me" will only play once now and then the quest finishes so never again. Whew, thank god ^^
Can't remember who found this bug, @Nitekat ?
> [bugfix] Quest items from previous games breaking dungeon

- Source/objects.cpp
Three new fixes here. First and foremost, I'd like to credit @qndel for finding the Valor bug. It took awhile to finally track down the actual cause.
This is caused by the fact the number of stones in the pedestal are stored in `_oVar6`. This variable is never initialized and only used by books and pedestals. Let's say you read a book on level 4 and it sets Var6 to 3, now this book is in object slot `50`. You go down to level 5 and the pedestal also happens to spawn in slot 50. This means it will think there are 3 stones despite the fact there are none.
Now they only spawn one at a time, which prevents people from being able to telekinesis them (sorry speedrunners!). This also as a side effect fixes the accidental deletion if you drop one.
If you try to click on the mushroom patch for …
> Quest bug fixes including Valor [proper]

- Source/player.cpp
This fixes a vanilla bug where you level up but your damage only gets updated after you spend a stat point or equip/unequip any item - leveling up itself didn't call updating damage despite being one of the factors in the damage formula
How to reproduce:
Level up from 3 to 4 with rogue, unequip an item, notice dmg +1 jump.
With this fix it will update automatically
> update damage after leveling up

- Source/inv.cpp
- Source/inv.h
- Source/stores.cpp
The 'saveFlag' argument used for persisting the changes into the
inventory is never leveraged on this function: all existing consumers
provide 'FALSE'. It was probably a copy-paste leftover from the
standard 'AutoPlace'.
> Remove item persistence from 'inv.SpecialAutoPlace'

- Source/items.cpp
check the stats of the given player, since it might not be the same as the mc
> correct stat checks when calculating the item bonuses

- Source/inv.cpp
prevent the possible negative-indexing of plr[pnum].InvList
> fixed memory corruption when using an item

- Source/portal.cpp
To reproduce before fix:
Go to leoric's tomb, cast town portal, go back to dlvl 1, you can see your portal there.
That's because leoric's setlvlnum is 1
> Fix portals appearing on wrong levels

- Source/inv.cpp
- Source/player.cpp
- We fixed the normal way of duplicating items.
- Legit items can be seen as duplicates in some instances.
- It doesn't fix the issue since the player has to drop both for it to
trigger.
> Remove checks for duplicate items

- Source/control.cpp
- Source/engine.cpp
- Source/engine.h
- Source/inv.cpp
- Source/minitext.cpp
- Source/scrollrt.cpp
Refactor the rendering functions to allow rendering to any output buffer.
New functions that accept a buffer have the `To` suffix.
The functions that render to the global buffer now always accept coordinates.
/cc @viciious
> Engine: Functions to render to any buffer

- Source/control.cpp
- Source/items.cpp
- Source/stores.cpp
This PR standardizes all occurrences of `:` in the game to never have an empty space before it.
In other words, `this : a` becomes `this: a`.
This is a continuation of https://github.com/diasurgical/devilutionX/pull/804 which fixed this for monster details, now applied to all other possible uses including shortcut details, stores, and item modifiers.
Store strings have been adjusted to keep the exact same length for UI alignment purposes (compare in inline mode to see).
Related to #803 (already closed)
> Standardize colon alignment on text

- Source/inv.cpp
- Source/inv.h
- Source/stores.cpp
This fixes a problem that causes items to vanish after being bought from Adria by ensuring the inventory space verification logic uses consistent logic between checking for space before buying, and checking for space when adding the item to the player after purchase.
Right before confirming a purchase, the game performs a thorough check on the player's inventory and belt to see if there is any space left to house the item that will be bought. However, due to a poor guard in the belt verification logic, items that the player cannot currently use due to unmet requirements are still considered as valid candidates for putting the item in the belt: the store then allows the player to purchase the item, but fails when actually adding the item to the player as items with unmet requirements …
> Block buying "red" consumables with full inventory

- Source/init.cpp
- SourceX/dx.cpp
Initialization of `gpBufEnd` was done in a convoluted way
that only happened to work.
Cleans up initialization and moves it to dx.cpp.
> Clean up gpBufEnd initialization

- Source/automap.cpp
- Source/engine.cpp
- Source/engine.h
Migrating away from using these globals will simplify transition to using SDL in rendering, rendering UI to a separate buffer, etc.
> automap: Migrate away from gpBuffer/gpBufEnd

- SourceX/DiabloUI/diabloui.cpp
The original version of UI List accepted a contiguous min/max range of item (enum) values, so `SelectedItem` could be compared to `m_value`.
With the recent changes, `SelectedItem` now refers to an index in the array.
This means the function that draws the list must now know about the potential existence of the scrollbar and consider its `ListOffset` into account.
Fixes #1006
> DiabloUI: Consider ListOffset for focus selector

- Source/diablo.cpp
- Source/inv.cpp
- Source/inv.h
- Source/msg.cpp
- Source/towners.cpp
- Source/trigs.cpp
This makes the item stay put in the cursor when entering a new level/portal. It also keeps items from dropping when talking to towners. Overall the dropping items thing was pointless and hacky.
> Remove items dropping before entering level

- Source/diablo.cpp
- Source/diablo.h
- Source/engine.cpp
- Source/gamemenu.cpp
- Source/inv.cpp
- Source/mainmenu.cpp
- Source/multi.cpp
- Source/palette.cpp
- Source/player.cpp
- Source/render.cpp
- Source/stores.cpp
- SourceX/DiabloUI/selgame.cpp
- SourceX/DiabloUI/selhero.cpp
- SourceX/display.cpp
- SourceX/dx.cpp
- SourceX/qol.cpp
- SourceX/sound.cpp
- SourceX/storm/storm_net.cpp
This PR splits up the `Options` model into several smaller models, one for each configurable section, mimicking the structure of the ini file sections.
This makes each model a bit more manageable in code and improves readability.
> :recycle: Make options struct hierarchical

- README.md
The md for the ftp link was backwards! Correct markdown syntax is [text](url), but I understand why it would happen, it's like connecting USB, you never get it right the first time! 🙂
> Corrected Markdown syntax on FAQ section of README

- Source/diablo.cpp
- Source/diablo.h
- Source/inv.cpp
Adds item equip sound to when the item is automatically equipped on pickup. Sound is disabled by default and can be turned on via ini toggle.
> Add item sounds to auto-equip

- Source/capture.cpp
- Source/control.cpp
- Source/control.h
- Source/engine.h
- Source/error.cpp
- Source/gmenu.cpp
- Source/help.cpp
- Source/interfac.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/minitext.cpp
- Source/render.cpp
- Source/render.h
- Source/scrollrt.cpp
- Source/stores.cpp
- Source/stores.h
- SourceX/qol.cpp
- SourceX/qol.h
- defs.h
After this PR, only a few instances of `gpBuf*` remain :rocket: 
```
$ rg gpBuf              
Source/scrollrt.h
20:extern BYTE *gpBufEnd;
SourceX/dx.cpp
18:BYTE *gpBuffer;
35:/** 8-bit surface wrapper around #gpBuffer */
45:	gpBuffer = (BYTE *)pal_surface->pixels;
46:	gpBufEnd = gpBuffer;
95:	gpBuffer = (BYTE *)pal_surface->pixels;
96:	gpBufEnd = (BYTE *)pal_surface->pixels + pal_surface->pitch * pal_surface->h;
112:	if (gpBuffer == NULL)
117:		gpBufEnd = gpBuffer;
138:	gpBuffer = NULL;
Source/scrollrt.cpp
20:BYTE *gpBufEnd;
Source/dx.h
15:extern BYTE *gpBuffer;
Source/engine.h
87:	extern BYTE *gpBuffer;
88:	extern BYTE *gpBufEnd;
89:	return CelOutputBuffer { gpBuffer, gpBufEnd, BUFFER_WIDTH };
```
Next step after this PR is to change `CelOutputBuffer` to store an `SDL_Surface *`. Then we …
> Migrate most rendering away from gpBuffer / gpBufEnd

- Source/capture.cpp
- Source/control.cpp
- Source/dx.h
- Source/engine.cpp
- Source/engine.h
- Source/error.cpp
- Source/gmenu.cpp
- Source/interfac.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/minitext.cpp
- Source/render.cpp
- Source/scrollrt.cpp
- Source/scrollrt.h
- Source/stores.cpp
- SourceX/dx.cpp
- SourceX/qol.cpp
- defs.h
`CelOutputBuffer` now contains an `SDL_Surface` and an `SDL_Rect`.
We now have access to SDL surface manipulation functions.
`gpBuffer` and `gpBufEnd` are completely gone 🧹
> Completely replace gpBuffer with CelOutputBuffer

- .editorconfig
- Packaging/OpenDingux/gkd350h-manual.txt
- Packaging/OpenDingux/retrofw-manual.txt
- Packaging/OpenDingux/rg350-manual.txt
- Packaging/cpi-gamesh/readme.md
- Packaging/nix/README.txt
- Packaging/pi/README.txt
- Packaging/switch/README.txt
- README.md
- Source/init.cpp
- docs/manual/platforms/gkd350h.md
- docs/manual/platforms/retrofw.md
- docs/manual/platforms/rg350.md
- docs/manual/platforms/switch.md
- docs/manual/platforms/vita.md
It's uppercase in GOG and on the retail CD.
Other MPQs are not known to be uppercase.
> Try uppercase DIABDAT.MPQ

- Source/engine.h
The headers don't actually work with C as they're now.
A better long-term solution should be able to use idiomatic C++ throughout
and expose things to other languages via a separate C API layer.
Fixes #1178
> Remove extern C from engine.h

- Source/effects.cpp
- Source/sound.h
- SourceS/miniwin/misc.h
- SourceS/soundsample.h
- SourceX/sound.cpp
- SourceX/soundsample.cpp
- SourceX/storm_sdl_rw.cpp
- structs.h
Changes audio playback of sounds with the `sfx_STREAM` flag, such as towner lines, to stream.
> Respect sfx_STREAM in PlaySFX

- Packaging/OpenDingux/build.sh
Accidentally nuked my `~/devilutionx-buildroots` cache and discovered this bug
> OpenDingux/build.sh: Minor fix

- 3rdParty/libsodium/CMakeLists.txt
- CMakeLists.txt
Adds an option to build libsodium from source instead of using the system-provided one.
This is useful on systems that do not provide libsodium, or for testing changes to libsodium along with devilutionx (by specifying `-DFETCHCONTENT_SOURCE_DIR_LIBSODIUM`).
This also allows us to configure sodium to our liking when building it from source, such as `SODIUM_MINIMAL`, which reduces the x64 release binary size from 4.3 MiB to 4.1 MiB.
> CMake: An option to build libsodium from source

- Source/init.cpp
> Hellfire: Better error if some MPQs are missing

- 3rdParty/Radon/Radon/include/Key.hpp
- 3rdParty/Radon/Radon/source/Key.cpp
- CMakeLists.txt
- Source/automap.cpp
- Source/control.cpp
- Source/debug.cpp
- Source/drlg_l1.cpp
- Source/drlg_l3.cpp
- Source/drlg_l4.cpp
- Source/inv.cpp
- Source/itemdat.h
- Source/items.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/multi.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/plrmsg.cpp
- Source/spells.cpp
- Source/spells.h
- Source/stores.cpp
- SourceS/miniwin.h
- SourceT/writehero_test.cpp
- SourceX/qol.cpp
- defs.h
Fixes https://github.com/diasurgical/devilutionX/issues/1201 (except for 4 warnings about switches not covering all enum values). Sorry that this is all in one chunk, but if you ignore whitespace changes (can be done in github) then it's only 150 lines changed in total.
> Fix majority of the Clang warnings

- CMakeLists.txt
- Source/gmenu.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/controls/axis_direction.cpp
- SourceX/controls/axis_direction.h
- SourceX/controls/controller.h
- SourceX/controls/controller_buttons.h
- SourceX/controls/controller_motion.cpp
- SourceX/controls/controller_motion.h
- SourceX/controls/devices/game_controller.cpp
- SourceX/controls/devices/joystick.cpp
- SourceX/controls/game_controls.cpp
- SourceX/controls/game_controls.h
- SourceX/controls/menu_controls.cpp
- SourceX/controls/menu_controls.h
- SourceX/controls/plrctrls.cpp
Implements thumb stick / dpad navigation and repeat-on-hold in DiabloUI, gmenu, and quest log.
1. Allows DiabloUI, gmenu, and quest log navigation with the left thumb stick.
2. De-duplicates repetition / throttling logic throughout.
3. Menus have separate repetition frequencies (inventory at 100ms, everything else at 200ms).
4. Movement mostly decoupled from menu navigation: the `dpad_hotkeys` setting used on the Vita no longer prevents dpad from navigating in menus.
> Thumb stick / DPad repeating navigation in DiabloUI, gmenu, and quest log

- 3rdParty/libsodium/CMakeLists.txt
- CMake/FetchContent_MakeAvailableExcludeFromAll.cmake
This commit serves 2 purposes:
1. Fixes CMake 3.13 compatibility when using
` -DDEVILUTIONX_SYSTEM_LIBSODIUM=OFF` (fixes #1222).
2. Ensures we do not build targets that are not depended on by us,
by passing `EXCLUDE_FROM_ALL` to `add_subdirectory`.
> CMake: libsodium FetchContent CMake 3.13 compat

- Source/diablo.cpp
- SourceX/controls/game_controls.cpp
- SourceX/controls/plrctrls.cpp
- SourceX/controls/plrctrls.h
Previously this was handled as part of `game_logic`, reducing responsiveness and making it impossible to run where `game_logic` isn't running, e.g. stores.
Bonus: Enables D-Pad / Left stick navigation in stores because the above makes it trivial
> Handle D-Pad / Left stick in UI every frame

- Source/diablo.cpp
- Source/diablo.h
- Source/monster.cpp
- SourceX/qol.cpp
This PR introduces one extra information when displaying monster details in the bottom info panel: the monster type.
| | Disabled | Enabled |
| --- | --- | --- |
| Normal (on-screen bar) | ![image](https://user-images.githubusercontent.com/461579/111918457-e72fd880-8a63-11eb-9852-ed205a6ba9cb.png) | ![image](https://user-images.githubusercontent.com/461579/111918492-0fb7d280-8a64-11eb-8c4b-59b819afc810.png) |
| Normal (info panel) | ![image](https://user-images.githubusercontent.com/461579/92981945-7edbbb00-f472-11ea-96a0-70bad26de376.png) | ![image](https://user-images.githubusercontent.com/461579/92981165-1808d280-f46f-11ea-8ab8-057af2f7e595.png) | ![image](https://user-images.githubusercontent.com/461579/111918457-e72fd880-8a63-11eb-9852-ed205a6ba9cb.png) |
| Unique (on-screen bar) | …
> Expose monster type on monster info

- CMakeLists.txt
The 4th argument to `cmake_dependent_option` is when to enable the option, not when to disable it like I'd thought.
https://cmake.org/cmake/help/latest/module/CMakeDependentOption.html
> CMake: Fix sodium static build

- .circleci/config.yml
Adds the building of AppImages for Linux x86 and x64 on the automated CircleCi builds.
> Build AppImages for Linux on CircleCi

- .clang-tidy
Turns out clang-tidy comes with a Python script that makes running it very easy and parallelizes the checks.
https://github.com/llvm/llvm-project/blob/main/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
> .clang-tidy: Document run-clang-tidy

- SourceX/storm_sdl_rw.cpp
Should really be using `calloc` but there is too many layers to these allocation wrappers.
This shouldn't make any difference but is good practice, e.g. if a field is added in a future version of SDL
> storm_sdl_rw: Zero rwops after allocating

- SourceX/DiabloUI/selgame.cpp
- SourceX/DiabloUI/selhero.cpp
Single-player difficulty selection was implemented in a very hacky way.
Documents what's going on there and fixes a memory leak.
Memory leaks that this fixes looked like this:
```
Direct leak of 64 byte(s) in 1 object(s) allocated from:
#0 0x7f435b789f17 in operator new(unsigned long) (/lib/x86_64-linux-gnu/libasan.so.6+0xb1f17)
#1 0x5567766c62b8 in dvl::selgame_GameSelection_Select(int) ../SourceX/DiabloUI/selgame.cpp:163
#2 0x5567766d8ee8 in dvl::selhero_Load_Select(int) ../SourceX/DiabloUI/selhero.cpp:464
#3 0x5567766d6ed1 in dvl::selhero_List_Select(int) ../SourceX/DiabloUI/selhero.cpp:325
#4 0x556776692683 in dvl::UiFocusNavigationSelect() ../SourceX/DiabloUI/diabloui.cpp:396
#5 0x55677669158e in HandleMenuAction ../SourceX/DiabloUI/diabloui.cpp:223
#6 0x5567766917b9 in …
```
> Fix memory leak in single-player difficulty selection

- .circleci/config.yml
- Packaging/nix/AppImage.sh
- Packaging/nix/AppRun
- Packaging/nix/LinuxReleasePackaging.sh
Update Linux AppImage to use devilutionx.mpq and charissilb.ttf. Depends on #1253
> Update Linux AppImage to use devilutionx.mpq and charissilb.ttf

- 3rdParty/Storm/Source/storm.h
- SourceX/sound.cpp
- SourceX/storm/storm.cpp
It is only used in one place and does not actually control the volume of any specific file.
> Remove SFileDdaSetVolume

- CMake/ctr/n3ds_defs.cmake
- CMake/switch/switch_defs.cmake
- CMakeLists.txt
- Source/effects.cpp
- SourceX/sound.cpp
Works around https://github.com/devkitPro/SDL/issues/72 at the cost of ~50 MiB extra RAM usage.
> Disable streaming music and sound for 3DS / Switch

- Source/options.h
This PR standardizes all options structs by removing unnecessary C `typedef`s
> Standardize Options structs

- Source/items.cpp
To make my life a bit easier, I privately changed *GOLD_MAX_LIMIT* to 50000.
This yielded the unexpected result that when picking up gold, the stacks were still capped at 5000 gold, and I needed to merge stacks manually.
items.cpp first sets *MaxGold* to *GOLD_MAX_LIMIT* in line 55, but this gets overridden by *auricGold / 2* in line 1076.
This patch fixes this unintended behavior without impacting the original gameplay.
> Bugfix: auricGold shouldn\'t determine MaxGold.

- CMakeLists.txt
- Packaging/windows/mingw-prep.sh
- Packaging/windows/mingw-prep64.sh
- README.md
This PR does two things. Brings the SDL2 version from 2.0.9 to 2.0.14 for Windows MinGW builds. Removes the note in the readme for SDL2 2.0.12 as it is no longer the latest and whatever issue there was has been fixed as it now builds successfully with 2.0.12.
> Update SDL2 version to 2.0.14 for Windows MinGW builds. And remove note for SDL2 2.0.12 in readme

- 3rdParty/Storm/Source/storm.h
- 3rdParty/StormLib/src/SFileReadFile.cpp
- SourceX/storm/storm.cpp
- SourceX/storm_sdl_rw.cpp
SBmpLoadImage tried to get the size of the rest of the file incorrectly
by subtracting the current file position from the total size.
This was incorrect because file positions do not always begin at 0.
The only semi-portable way to get a size from file positions is to
subtract two file positions.
> Fix Storm local file seeking (also fixes `SBmpLoadImage`)

- Source/engine.cpp
- Source/engine.h
- Source/inv.cpp
- Source/scrollrt.cpp
Default outline drawing:
Fixed outline drawing:
Colour in index 0 in the palette is typically used for shadows. When drawing outlines, the game skips this colour so it avoids making outlines around shadows, but since the colour is also sometimes used on the object itself as the colour black this makes the outline not properly follow the shape of many CEL frames.
Inventory icons never have any shadows, so for those, we could make sure to always draw outlines for #0 pixels.
> :cow: Draw outline for color in index 0 for inventory icons.

- Source/control.cpp
It was probably caused by https://github.com/diasurgical/devilutionX/commit/70d1d633bd1745f803ffbc0a5be9e3a76479a08e
and I subtracted 64 from hardcoded numbers (that's what SCREEN_X was), now gold spinner aligns properly
Found by Nitekat
> fix gold spinner

- Packaging/nix/AppRun
Any arguments passed to the AppImage were being ignored this allows them to be passed through the AppImage to devilutionx.
> pass AppImage Arguments

- Source/control.cpp
- Source/player.cpp
- Source/player.h
This PR fixes a bug that caused extra remaining stats to vanish when shift+click was used to assign all remaining stat points to a near-capped attribute.
Fixes #1342
> Fix shift+clicking stats behavior with capped stats

- SourceX/qol.cpp
This PR fixes a problem that caused the auto-pickup gold functionality to not work under a few circumstances when the inventory was full or near full due to a off-by-one mistake in indexing into the list of items.
Fixes #1348
> Fix auto-pickup gold behavior when inventory is full

- CMakeSettings.json
- SourceX/controls/controller.cpp
Hi all,
I noticed that a recent change to controller.cpp broke the Gameshell support as `ToControllerButtonEvent` no longer reacts to key presses in the menu and later. With this commit, it is fixed.
Looking at the history, this change might have been forgotten when df56d6a03bdf1f148beafa8cbc8612eac4f6c34b was done.
Hope this fixes the issue also for other devices which need the `HAS_KBCTRL == 1` define.
Happy coding!
> Fix broken KeySupport for Gameshell (and others)

- Source/inv.cpp
- Source/inv.h
- Source/stores.cpp
This PR fixes a bug that caused the shift+click to equip weapons to not work when playing with the Monk class, due to the way we were evaluating the monk exception for auto-equipping weapons.
The exception has been moved to a more appropriate place now, where it is checked on every auto-equip attempt but no on explicit user equip attempts.
Fixes #1330
> :bug: Allow shift+click to equip weapons on monk

- SourceX/storm/storm.cpp
I encountered crashes at startup in a VS2019 release build that didn't occur in the debug build. The compiler optimizations used a different ordering for evaluation of the operands in the subtraction, causing it to seek to `DVL_FILE_END` before attempting to load the image data.
> Fixed order of evaluation in SBmpLoadImage size allocation.

- SourceX/DiabloUI/art_draw.cpp
- SourceX/DiabloUI/credits.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/diabloui.h
- SourceX/DiabloUI/dialogs.cpp
- SourceX/DiabloUI/progress.cpp
- SourceX/DiabloUI/text_draw.cpp
Use that instead of using `GetOutputSurface()` directly.
For the rg99 port, we'll want to render this to the `pal_surface`
instead of output surface directly.
Might also be useful for 3ds, perhaps to render to the bottom screen.
> DiabloUI: Render to DiabloUiSurface()

- 3rdParty/Storm/Source/storm.h
- Source/engine.cpp
- Source/engine.h
- SourceX/storm/storm.cpp
1. Removes a lock around allocation. `malloc` is required to be thread-safe in C11.
2. Defines it as a macro so that:
1. We provide the correct location for the OOM error.
2. We get better attribution from memory profilers.
> Cleanup DiabloAllocPtr

- SourceX/DiabloUI/ttf_render_wrapped.cpp
Some SDL ports, such as the 3DS one and the PSP one, are missing these SDL functions.
> ttf_render_wrapped: std functions instead of SDL

- Source/diablo.cpp
Running with a memory profiler revealed that we were keeping main menu UI resources around while the game was running:
> Save 1.3 MiB RAM in-game by freeing menu resources

- CMake/FindGperftools.cmake
- CMakeLists.txt
This option links the tcmalloc and gperf memory profiler.
It can then be used to memory-profile individual sections of the app.
On Ubuntu, the package that provides the profiler is `libgoogle-perftools-dev`.
Here is how the profiler can be used:
```diff
--- a/Source/diablo.cpp
+++ b/Source/diablo.cpp
@@ -11,6 +11,8 @@
#include "../DiabloUI/diabloui.h"
#include <config.h>
+#include <gperftools/heap-profiler.h>
+
DEVILUTION_BEGIN_NAMESPACE
SDL_Window *ghMainWnd;
@@ -300,6 +302,8 @@ static void run_game_loop(interface_mode uMsg)
WNDPROC saveProc;
MSG msg;
+	HeapProfilerStart("run_game_loop");
+
nthread_ignore_mutex(TRUE);
start_game(uMsg);
assert(ghMainWnd);
@@ -342,6 +346,9 @@ static void run_game_loop(interface_mode uMsg)
DrawAndBlit();
}
+	HeapProfilerDump("gbRunGame_false");
+ …
```
> CMake: Add GPERF option

- Source/cursor.cpp
- Source/diablo.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
- Source/msg.cpp
- Source/pack.cpp
- Source/player.cpp
- Source/scrollrt.cpp
- Source/sync.cpp
- Source/themes.cpp
- SourceX/controls/plrctrls.cpp
- SourceX/qol.cpp
This PR renames the global `item` array to `items`. This improves its semantics (it is a list of items) and avoids conflicts with other local `item` variables in methods.
> :recycle: Pluralize global 'item' array variable

- Source/diablo.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/diabloui.h
Heap state of an SDL1 build with no audio
Before:
After:
> Save 1.5 MiB RAM in-game by freeing more DiabloUI art

- Source/diablo.cpp
- Source/msg.cpp
- Source/multi.cpp
- Source/player.cpp
- Source/player.h
Previously, the allocation size was the maximum size over all the classes.
RAM usage per player:
* Before: 2.2 MiB (any class)
* After:
* Warrior: 2.0 MiB
* Rogue: 1.5 MiB
* Sorcerer: 1.6 MiB
* Monk: 1.7 MiB
We now also only allocate memory in multi-player as needed.
This means the game will only use as much RAM for player graphics as there are players currently in the game. Also the RAM used for each player is lower because it now takes class into account.
Follow-up to #1393
> InitPlrGfx: Only alloc enough for the class

- 3rdParty/Storm/Source/storm.h
1. StormLib now uses `bool` instead of `BOOL`
2. `WINAPI` was missing on `SFileSetFilePointer` (also the return type was incorrect)
3. There was a `WINAPI` on `SFileOpenFile` but that's not a StormLib function
Refs #1399
> Fixup storm.h signatures

- Source/control.cpp
- Source/items.cpp
- Source/player.cpp
- Source/player.h
- SourceX/miniwin/misc_msg.cpp
This PR refactors all places that access maximum player stats to rely on the same function in `PlayerStruct` to do it.
> :recycle: Reuse 'player.GetMaximumAttributeValue' for max stats

- README.md
Sanity checked and applied the suggestions by the grammar checking tool Grammarly.
I really wanted to change "U.S." into "USA" or "United States of America" for greater clarity of my own accord, but I presume that the specific wording and spelling used is the original from the Diablo box or website or something.
> Fix typos as suggested by a grammar tool

- 3rdParty/StormLib/src/StormPort.h
Do not assume mmap by default for the fallback platform, unless it's in a list of platforms that we know have mmap
Upstream commit: https://github.com/ladislav-zezula/StormLib/commit/062868dcdfd8616c55405d42a065c7504fdcaf7a
> StormPort.h: Do not assume mmap support

- 3rdParty/Storm/Source/storm.h
- Source/diablo.cpp
- Source/options.h
- SourceX/controls/controller_motion.cpp
- SourceX/storm/storm.cpp
This adds an ini option under Controller.deadzone, read as a float.
I had some drift on my Xbox gamepads that made the use of the emulate pointer feature on the gamepad very inpractical.
So I figured, why not make this a user configurable value?
My C++ is very rusty so I'm very eager to hear your reviews.
Here are some things I am unsure about:
- Saving the deadzone in the ini file: I opted for 2 point float precision for this. This can be changed easily if you think it is necessary.
- Default deadzone value of 0.07 is untouched but this seems very low and it is likely that other xbox gamepad users are affected. Maybe we should consider making this a bit bigger, e.g: 0.15
- Maybe we should consider splitting joysticks left and right deadzones instead of having a single value?
> add an ini option to configure gamepad deadzone

- Source/loadsave.cpp
Refs #1367
I'm not sure how this function works but this fixes the following ASAN error for me on VS2019:
Yes, VS finally has ASAN. A decade late but still welcome: https://devblogs.microsoft.com/cppblog/addresssanitizer-asan-for-windows-with-msvc/
> loadsave: Fix off-by-one in RemoveEmptyLevelItems

- Source/mainmenu.cpp
When you click on singleplayer in the main menu, this function gets called: `mainmenu_single_player()`
That loads several gameplay variables from the config.
However, as you progress through the character selection menus and before going ingame, this function gets called: `NetInit()`
That loads the same gameplay variables from the config, which makes the actions in `mainmenu_single_player()` unnecessary. I should note that the `NetInit()` function gets called in both singleplayer and multiplayer modes (when I first saw its name, I was thinking it was run only in network mode).
In order to remove redundant code (and to make it less confusing as to when important variables are actually initialized), I think it would be a good change to remove these lines from `mainmenu_single_player()`
> Removal of redundant updating of gameplay variables

- CMakeLists.txt
BIN_TARGET is devilutionx by default but is devilutionx.elf on Switch and 3DS
> CMake: Link libzt to ${BIN_TARGET}

- CMakeLists.txt
- SourceX/DiabloUI/diabloui.cpp
- SourceX/platform/vita/keyboard.cpp
- SourceX/platform/vita/keyboard.h
Fixes #1414 
As per discussion, this implements strategy 1 (SDL_TEXTINPUT event should replace name, not append to it) and somewhat strategy 4 (except instead of SDL, setting text for IME implemented in custom handler instead).
> Use custom IME handler on Vita

- SourceX/DiabloUI/art.cpp
- SourceX/DiabloUI/art.h
- SourceX/DiabloUI/art_draw.cpp
- SourceX/DiabloUI/credits.cpp
- SourceX/DiabloUI/diabloui.cpp
- SourceX/DiabloUI/text_draw.cpp
- SourceX/DiabloUI/text_draw.h
- SourceX/controls/devices/game_controller.cpp
- SourceX/display.cpp
- SourceX/display.h
- SourceX/sdl_ptrs.h
Adds `SDLSurfaceUniquePtr` that simplifies handling of SDL surfaces (so we don't have to free them manually).
Migrates a few places to this new type as an example.
> Add std::unique_ptr specializations for SDL types

- Source/cursor.cpp
- Source/diablo.cpp
- Source/drlg_l3.cpp
- Source/drlg_l4.cpp
- Source/mainmenu.cpp
- Source/missiles.cpp
- Source/msg.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/scrollrt.cpp
- SourceX/DiabloUI/diabloui.cpp
Should try and tackle more the warnings that we silence, or enable more compiler checks next?
> :rotating_light: Fix remaning clang warnings

- defs.h
> Remove top and bottom buffer borders

- Source/loadsave.cpp
This resolves #1463
FYI, the savegame attached to the issue works in the original game. This must be because the original game is reading _qmsg as a `Uint8` regardless of how DevilutionX saves it. After making this change, the same savegame works fine in DevilutionX as well.
> Fixed data type of quest _qmsg in save files.

- CMakeLists.txt
As per (non) issue #1472  - devilutionx.mpq was not automatically copied across when performing 'cmake ..' in the build folder.
This just adds the copy of devilutionx.mpq when performing a cmake.
> Copy devilutionx.mpq to the build directory when performing CMake. #1472

- CMakeLists.txt
- Source/diablo.cpp
- Source/mpqapi.cpp
- SourceS/console.cpp
- SourceS/console.h
- SourceS/sdl2_to_1_2_backports.cpp
- SourceS/sdl2_to_1_2_backports.h
- SourceX/miniwin/misc_msg.cpp
1. Backports SDL2 logging.
2. Adds a `--verbose` flag.
3. As an example, adds logging priority and category to a few log calls.
> SDL1: Backport SDL2 logging

- Source/inv.cpp
- Source/stores.cpp
Equipping the Auric Amulet increases the amount gold can stack in your inventory from 5k to 10k. This works when picking gold up off the ground, but not when gaining gold through sales or attempting to drag and drop to create a stack. I've fixed this here by simply ensuring that the MaxGold variable is used when checking gold stack size instead of GOLD_MAX_LIMIT.
> Fix gold stacking when gold stack limit is modified

- Source/render.cpp
- Source/render.h
No performance difference (measured by rendering a screen full of black tiles at 640x480)
> `world_draw_black_tile`: Stop relying on buffer padding

- Source/missiles.cpp
If cast by traps flash would look in memory a bit before the monster
array for what value to use as damage, no one knows what might have been
there waiting so could deal anything form -254 to 254 damage.
Fixes #1500
> :bug: [hellfire] Sparkling Shrine deals a random amount of damage

- Source/control.cpp
- Source/enum_traits.h
- Source/items.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/player.h
- SourceX/miniwin/misc_msg.cpp
This PR converts the `attribute_id` enum to a scoped enumeration and renames both the enum itself as well as its members.
Adjustments are made to ensure every place accessing the enum for indexing into arrays, converting into other values and iterating over all the attributes are handled appropriately.
> 'attribute_id' enum cleanup

- Packaging/OpenDingux/build.sh
> OpenDingux: Fix path to the `strip` binary

- SourceX/miniwin/misc_msg.cpp
No longer necessary as of [`dae4cc8` (#1484)](https://github.com/diasurgical/devilutionX/pull/1484/commits/dae4cc8c50a41f173f1432b5f81a0023fa23d45b)
The default minimum priority log level in release builds is INFO
/cc @isage
> false_avail: Remove `__vita__` workaround

- Source/inv.cpp
A lot of stuff can be cleaned up and rewritten in CheckInvPaste() (well, besides the rest of the Diablo code, that is), but I figured this is maybe a small step towards that. I rewrote 2 identical code snippets into one function.
I'm not happy about not rewriting how this craziness is calculated:
```
yy = 10 * (ii / 10 - ((sy - 1) >> 1));
xx = (ii % 10 - ((sx - 1) >> 1));
```
I'm not sure how to re-write it (it calculates the topleft position of an item using mouse position and item size), and also, it has to be calculated the exact same as other code earlier in the same function.
> Rewrote two identical code snippets in inv.cpp into one function.

- Source/diablo.cpp
- Source/items.cpp
- Source/msg.cpp
- Source/msg.h
- Source/multi.cpp
- Source/multi.h
- Source/track.cpp
- Source/trigs.cpp
- SourceX/controls/plrctrls.cpp
Exposes player number from multi_send_packet.
It also adds playerNumbers for functions:
- NetSendCmdLoc
- NetSendLoPri
- NetSendHiPri
- Movement
With this PR, is possible to move a specific player (or more than one) using the gamepad logic (after a few tweaks).
You will notice that some functions are using playerId and others are using myplr, it was done on purpose. I am trying to create a convention here, myplr is the default value for player one so if the call chain is not complete, myplr is being used. When all calls were changed to expose playerId, myplr will/should be replaced.
> Exposes player number from multi_send_packet

- Source/loadsave.cpp
Was it just an oversight that the values were limited to signed char while the variable is unsigned char? My golem had problems while having 133 cth :D 
Fixes https://github.com/diasurgical/devilutionX/issues/1071
> fix loading golem

- Source/items.cpp
Fixes #1545
Introduced with #1468
Some [careless mistake](https://github.com/obligaron/devilutionX/commit/c7b9ffec1f1ddd95d92fc1bc0bac8258bf7ebfe4#diff-be3ecbe1ead4062ccd317dfeb0428b38adf3d54377059e602229c75bfc052da8R1078) from replacing redundant sourcecode with a function call (passed wrong delay).
Now I hope the character can relax and is less nervous if a weapon is swapped 😄
> bugfix idle animation after equipping/unequipping

- Source/inv.cpp
If a player tries to swap sword+shield with a two-handed weapon without sufficient inventory space it leads to a network desync (what's in the right hand gets de-equipped on other clients, but not for local client).
Video example: https://www.youtube.com/watch?v=2GtUv-m8FoI
The cause was the game always sending a network packet for de-equipping the right-hand item before even checking if the local player has space to do the weapon swap.
(Uh, never mind the shield position looking weird. That's an unrelated issue caused by another commit.)
> Fix for a rare legacy bug causing network desync

- Source/miniwin/miniwin.h
- Source/storm/storm.cpp
- Source/storm/storm_full.h
SErrGet/SetLastError were not propagating errors from 3rdParty/StormLib because StormLib uses native Windows functions on Windows and defines its own on Linux.
Also removes `storm_full.h`
> Fix SErrGet/SetLastError

- Source/miniwin/miniwin.h
- Source/storm/storm.h
- Source/storm/storm_sdl_rw.cpp
`DVL_ERROR_HANDLE_EOF` was defined incorrectly on Windows.
These error codes are used and returned by Storm. Moves them from `miniwin.h` to `storm.h`.
> Fix Storm error code on Windows

- Source/inv.cpp
This PR fixes an issue introduced in commit https://github.com/diasurgical/devilutionX/commit/01606ea4df8150367d6401e49921b8d21b133eae that caused picked up items to remain visible on the group in some situations.
Relying on HoldItem is incorrect as it points to a different copy of the item than the global item array, so even if the item is assigned earlier, we cannot use that value.
This fixes #1519
> 🐛 Ensure picked up items on the ground are removed

- Source/diablo.cpp
- Source/init.cpp
- Source/loadsave.cpp
- Source/pfile.cpp
- Source/pfile.h
In multiplayer, the hash and block tables are kept around between the saves (presumably to improve performance).
When leaving the game, they should be cleared.
Clearing of the tables is handled by `Archive::Close` in `mpqapi.cpp`.
After #1426, which moved the archive closing inside `pfile_write_hero`, the tables were no longer cleared on `pfile_flush_W` (because the archive was already closed when it was called).
To fix the issue, this commit adds a `clear_tables` argument to `pfile_write_hero` and removes the `pfile_flush_W` function.
Bug reported and root cause found by @Eider-McDuck:
> Example to reproduce: Have 2 vanilla savegames, join a game with the first,
> then leave, then join a game with the second, then drop an item on the floor.
Initial proposed fix by @Eider-McDuck: #1555
> 🐞 pfile: Fix stale tables after leaving a game

- CMakeLists.txt
- Source/utils/file_util.cpp
- Source/utils/file_util.h
There is no reason for these functions to be in the header (inlining
won't benefit them one bit).
I put them in the header originally only because of the weird state
SourceS was in back then.
> Move file_util.h implementations to file_util.cpp

- Source/dx.cpp
- Source/init.cpp
- Source/utils/sdl2_to_1_2_backports.h
- Source/utils/stubs.h
Guard around SDL version at call site instead.
> 🧹 SDL1.2: Remove unimplemented SDL_*Window backports

- Source/items.cpp
- Source/misdat.cpp
- Source/missiles.cpp
- Source/missiles.h
- Source/monster.cpp
- Source/msg.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/player.h
This resolves #1353
This resolves #1111
Based on my testing, the hit-recovery bug does not affect PvP.
I edited a character's stats to make testing easier. Here is a save file.
[single_0.sv.zip](https://github.com/diasurgical/devilutionX/files/6301584/single_0.sv.zip)
Missles can be tested against skeleton archers on dlvl 2. Head northwest to reach the stairs.
> Consolidate logic for Mana Shield and player damage.

- Source/objects.cpp
- Times were off by 1 hour because of > instead of >=
- For the same reason, there was a hole between 4:00 and 4:59 where using the shrine would produce no effect
> Fix for Solar Shrine

- docs/building.md
1. chown the whole directory including dotfile
2. Fix the "copy resources" command (must be chowned first)
> Docs: Amiga: Better "building" command [ci skip]

- Source/init.cpp
- Source/storm/storm.h
`MPQ_FLAG_READ_ONLY` -> `MPQ_OPEN_READ_ONLY`.
The former is a flag that is set on an MPQ that was open in read-only
mode. To request opening in read-only mode, `MPQ_OPEN_READ_ONLY` should
be used instead.
> Fix init_test_access MPQ flag

- Source/DiabloUI/button.cpp
- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/text_draw.cpp
- Source/DiabloUI/text_draw.h
- Source/DiabloUI/ui_item.h
Cleans up the handling of text render cache for `UiText` and `UiButton`.
This also happens to fix a memory leak (`FreeCache` was never called).
> 🧹 DiabloUI: Clean up text render cache

- Source/DiabloUI/diabloui.cpp
The type is known here so we do not need to pay the overhead of a `dynamic_cast`.
Follow-up to https://github.com/diasurgical/devilutionX/commit/94f385a46b3c15fd0f5b2cf3ceb8e66df6e75bd5
> 🎨 DiabloUI: Replace `dynamic_cast` with `static_cast`

- Source/qol/xpbar.cpp
For low XP characters, integer truncation of onePx could lead to an index into the color gradient that accessed one past the last element.
> Fixing OOB error when drawing partially filled XP bar pixels.

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/selhero.cpp
- Source/effects.cpp
We've discovered that `Mix_LoadWAV_RW` actually loads the whole file in memory so this does not fix the streaming but is good to fix anyway
> GetSFXLength: Respect streaming flag

- Source/utils/soundsample.cpp
This fixes exclusively the panning bug, where after a certain distance is exceeded, sound samples get played without panning.
Fixes https://github.com/diasurgical/devilutionX/issues/1657
> Fix for "Distant sound sources aren't panned correctly"

- Source/player.cpp
The use of `unordered_set` here is a bit gratuitous and doesn't do much for readability.
> 🧹 GetPlrGFXSize: unordered_set -> direct test

- CMakeLists.txt
- Source/player.cpp
- Source/player.h
- test/animationinformation_test.cpp
This is the successor of #1468
Content:
- Adds correct logic, if delay is specified (fixes fast blocking bug)
- Small refactoring of Calculation, so that the calculation is only done when `NewPlrAnim` is called and not needed every time we render. This also reduces the number of variables we need in `PlayerStruct`.
- Extra comments that explain the logic further
- UnitTests for the Animation Distribution Logic
Notes:
- I wasn't sure if the new flags enum "AnimationFlags" should be `enum class` or normal `enum`.
- If #1507 is commited first, I will add __attribute__((flag_enum)) to the new enum.
- I named the test `AnimationInformation` cause this would be the name of the class when I refactor the logic out of player.h/cpp. if you have a better name, I will change. Other names I had in …
> adl: fix animations with delay (block animations), refactoring and unittests

- Source/utils/language.cpp
- Source/utils/language.h
This pull request adds language metadata lookup capabilities, e.g., to check which character set a translation is encoded in. There is also a fix that ensures translations are null-terminated.
> Parse language metadata

- Source/dead.cpp
- Source/dead.h
- Source/engine.cpp
- Source/engine.h
- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
- Source/objects.cpp
- Source/objects.h
- Source/player.cpp
- Source/player.h
- Source/scrollrt.cpp
- Source/towners.cpp
- Source/towners.h
- test/writehero_test.cpp
I looked in generalization the animation distribution logic and I asked myself "what is Width2 and should I care?".
Mostly the answer is we shouldn't care.
AnimWidth2 seems to be only needed for rendering and can be calculated only there, so the GameLogic don't need to care about.
This reduces complexity and memory size.
But there is a exception to this rule.
it's not possible for missiles, cause in hellfire there are some missiles that have not the normal offset (for example MFILE_REFLECT, MFILE_ARCHLICH or MFILE_BONEDEMON).
But I didn't looked into this in detail.
I submitted this as draft to discuss if we should take this, even if missiles are handled differently.
> Remove "AnimWidth2" expect for missiles

- CMakeLists.txt
- Source/DiabloUI/fonts.cpp
- Source/capture.cpp
- Source/diablo.cpp
- Source/dvlnet/zerotier_native.cpp
- Source/init.cpp
- Source/pfile.cpp
- Source/restrict.cpp
- Source/storm/storm.cpp
- Source/utils/language.cpp
- Source/utils/paths.cpp
- Source/utils/paths.h
- Source/utils/stdcompat/optional.hpp
- test/writehero_test.cpp
This removes globals and pointers from `paths.h`. It introduces a static class to do so.
Multiple options/alternatives here:
- skip the static, use an instantiable class and pass it around (my preferred option, as we will certainly use more and more classes this will allow us to see what class depends on what; plus the singleton pattern is usually not seen as a good practice) -- the issue here is that some static functions need those paths, so implementing this would imply removing their static status (which would probably be a good thing, but is a bit more involved so I'd rather hear your opinions on that).
- only use static variables and static functions (not a fan, as it's not much better than using globals)
- use `Get` instead of `Instance` to access the instance, shorter but less …
> Remove globals/pointers from paths.h

- appveyor.yml
SDL_audiolib uses some C++17 features not supported in VS2017
> 🔨 AppVeyor: Switch to Visual Studio 2019

- CMakeLists.txt
See https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance
Background: https://github.com/realnc/SDL_audiolib/issues/15
> 🔨 MSVC: Enable standards mode (/permissive-)

- Source/player.cpp
A small cleanup.
`AnimLenFromClass` was a constant (always 8) and defines the same as the values in `PlrGFXAnimLens` (Animation Length).
`_pWFrames` is initialized with `PlrGFXAnimLens`, so just use this.
> Remove AnimLenFromClass

- CMakeLists.txt
Older Debian and derivatives come with sdl2-config.cmake file that does
not define any targets.
One such sdl2-config.cmake looks like this:
```cmake
set(prefix "/usr")
set(exec_prefix "${prefix}")
set(libdir "${prefix}/lib/x86_64-linux-gnu")
set(SDL2_PREFIX "/usr")
set(SDL2_EXEC_PREFIX "/usr")
set(SDL2_INCLUDE_DIRS "${prefix}/include/SDL2")
set(SDL2_LIBRARIES " -lSDL2")
string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)
```
Works around this by defining an `SDL2::SDL2` target ourselves.
Removes SDL2::SDLmain because we do not use the SDL_main function and do not need it.
> 🔨 CMake: Fix SDL2 on older Debian derivates

- Source/diablo.cpp
- Source/options.h
On some platforms, editing command-line flags is difficult.
This adds a `Show FPS` option to the ini file.
If set, FPS is shown even without the `-f` flag.
> ⚙️ Show FPS option

- Source/items.cpp
- Source/utils/math.h
This one is described in Jarulf's guide, page 24 bottom: 
> There is a minimum increase of 1 in AC. That is, even if the percentage will give an increase to AC less than one, it will be increased by at least one. Due to a bug, any decrease in AC less than 1 will be transformed into a positive increase by 1.
The code just checked if (due to rounding) the AC bonus would be == 0, and if it was, it would increase it to 1. This change makes sure that a negative bonus results in -1 for that case.
It also adds a math::Sign helper for calculating the signum of a value, without branching.
> Fix for small AC malus of less than 1 resulting in a bonus of 1 AC

- Source/mpqapi.cpp
Single-argument version is allegedly not supported by GCC < 9.1, though
it seemed to work fine.
https://www.gnu.org/software/gnulib/manual/html_node/assert_002eh.html
> Add messages to `static_assert`

- CMakeLists.txt
Now that we use SDL2 cmake target for linking, we can drop some libs from link list, because they are automatically linked by SDL2 target import.
> Remove libs linked by SDL2 target from lib list

- CMakeLists.txt
- Source/utils/paths.cpp
That should properly load font and datafile packaged inside app.
There's no need to distribute devilutionx.mpq or CharisSILB.ttf in vita zip file along with .vpk anymore.
> Vita fixes

- Source/objdat.cpp
- Source/objects.cpp
Fixes #1515
- Crypt candles (braziers) around the story book were occasionally missing
- Marked OFILE_CANDLE2 to load for all levels 1 through 12, so it is always loaded for crypt as well
- Made search for object graphics a bit more secure, as in the bugged case it would run off past the end of an array
> Fix for rare level generation bug on Crypt 1 that causes missing story book braziers

- CMakeLists.txt
- Source/engine/animationinfo.cpp
- Source/engine/animationinfo.h
- Source/loadsave.cpp
- Source/msg.cpp
- Source/multi.cpp
- Source/player.cpp
- Source/player.h
- Source/scrollrt.cpp
- test/animationinfo_test.cpp
- test/player_test.cpp
- test/writehero_test.cpp
This pr doesn't change any logic (including if conditions).
Content:
- Move Fields and Logic to new `AnimationInfos` class (every move is in a separate commit and not coupled with other changes)
- Rename Variables (in separate commits)
- Remove not needed local variables (in separate commit)
Notes:
- In the future AnimationInfos should be included in other Types (Monsters, Object, Missiles). But this is outside the scope of this pr.
- `Width` is not included cause in other types (Monsters) `Width` doesn't exist as member. That's also the reason why NewPlrAnim still exists.
> Refactor Animation Informations

- Source/utils/soundsample.cpp
When playing the same sound twice with in a short duration then the
sound it self, the secound request would go unfulfilled. The solution is
to simply rewind the stream pointer before requesting a playback.
> Fix missing sounds

- CMakeLists.txt
- Source/diablo.cpp
- Source/effects.h
- Source/effects_stubs.cpp
- Source/gamemenu.cpp
- Source/minitext.cpp
- Source/monster.h
- Source/movie.cpp
- Source/sound.h
- Source/sound_stubs.cpp
- Source/storm/storm_svid.cpp
- Source/utils/display.cpp
This option completely disables all audio handling, including audio loading code and dependencies.
Dialog text length is estimated to be somewhere between Cain and Griswold speed.
This option will likely be needed for the RG-99 port and was also requested by @pgielda in 
https://github.com/diasurgical/devilutionX/pull/1651#issuecomment-825595102
> 🔨 ⚙️  CMake: Add NOSOUND option

- Source/capture.cpp
- Source/engine.h
If there's some error when writing the screenshot to the file, the buffer does not get freed.
(As a fun fact, this is literally the first hit that my IDE yielded when searching for DiabloAllocPtr.)
I was conservative with this commit, and used the DiabloAllocPtr and mem_free_dbg macros. Going forward, should we still use them in cases where we can make memory management automatic? (The network code, for example, does not use them.)
> Fix memleak in CapturePix

- Source/player.cpp
https://github.com/diasurgical/devilution/blob/2bf6eeb125a540e83ec838d6ab9181f2b26d0983/Source/player.cpp#L3206-3221
For Bard it's possible to wield two weapons.
That mean's it's also possible that two attack modifiers are present at the same time.
In this case the skipped frame calculation doesn't calculate the skipped frames correctly, cause the combined skipping of two attack modifiers can skip the frame that triggers the next skipping.
This is the same behavior as the combined hit recovery modifiers (zen mode).
Example:
- Bard with two swords, one with fast the other with faster attack modifier
- `PM_DoAttack` at Frame 3 advances two Frames (one for Fast Attack and one for Faster Attack.) So the Frame is 5.
- Then ProcessAnimation advances the Frame again. So now the Frame is 6.
- In …
> ADL: Fix calculation of fast/faster/fastest combination (Bard)

- Source/inv.cpp
if _iIdentified is true, the first strcpy was not usefull
> Avoid a strcpy

- Source/controls/modifier_hints.cpp
- Source/items.cpp
- Translations/devilutionx.pot
c-format string are checked by poedit
"hit steals 5% life" could be translated into "vole 5% de vie". and poedit would like to make sure that %d would be filled with a int
> Translation quickfix

- CMakeLists.txt
- Source/movie.cpp
- Source/storm/storm_file_wrapper.cpp
- Source/storm/storm_file_wrapper.h
- Source/storm/storm_svid.cpp
- Source/storm/storm_svid.h
Previously, we always loaded entire videos in memory before playing them.
`libsmacker` does not provide a streaming API but it does provide a `FILE *` file pointer API.
We now take advantage of the `FILE *` API by streaming the videos on platforms that support `fopencookie`.
This means faster startup and less memory usage on these platforms.
---
Of BSD flavours, only FreeBSD is documented to support `fopencookie`. BSD folks are welcome to add an `funopen` implementation to support more BSD flavours.
> 🎉 Stream videos on Linux and FreeBSD

- Source/DiabloUI/art.cpp
- Source/storm/storm.cpp
- Source/storm/storm.h
The new approach only makes 2 read calls and does not do any seeks.
It is also less general and is internal to `art.cpp`, allowing us to simplify it somewhat.
> ♻️  Replace `SBmpLoadImage` with a simpler method

- Source/items.cpp
A better fix would probably be to not call this function in the first place before the graphics are loaded. @thebigMuh
> 🐞 items.cpp: Fix nullopt access

- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
No longer needed as of #1796
We could probably go further and not expose `ItemAnimWidth`,
but it'd be dangerous because sometimes `_iAnimData` is null.
> ♻️  Remove `_iAnimWidth`

- Source/sound.cpp
- Source/storm/storm_sdl_rw.cpp
- Source/storm/storm_sdl_rw.h
- Source/utils/soundsample.cpp
- Source/utils/soundsample.h
All of our use-cases for `SDL_RWops` Storm file require closing the file when closing the `SDL_RWops` -- doing this automatically simplifies the code.
> ♻️  Make `SFileRw` own the Storm file handle

- Source/DiabloUI/art.cpp
- Source/capture.cpp
- Source/encrypt.cpp
- Source/engine.cpp
- Source/loadsave.cpp
- Source/mpqapi.cpp
- Source/pfile.cpp
- Source/storm/storm_svid.cpp
- Source/utils/language.cpp
`std::make_unique<T[]>(size)` always zero-initalizes the array.
C++20 has `std::make_unique_for_overwrite` to avoid that, while older C++ versions can use the approach applied here.
> 💨 Do not zero-initalize arrays that we write to

- Source/utils/log.hpp
This catches any format exception thrown by `fmt::format` so that the program doesn't crash, and logs an error message with some information on what the error is.
We try to insert nullptr char* into a format string at some point in the code, which is not great. This PR should help debugging that issue.
Fixes #1734.
> Don't crash on string formatting errors, and be more verbose

- Source/effects.cpp
- Source/engine.h
- Source/gamemenu.cpp
- Source/sound.cpp
- Source/sound.h
- Source/utils/math.h
- Source/utils/soundsample.cpp
- Source/utils/soundsample.h
- test/effects_test.cpp
Fixes #1632 
The panning and distance attenuation calculations were very strange and nonsensical.
- Volume doesn't abruptly change from 'sorta half quiet' to 'muted on the last notch of the slider.
- Volume sliders are logarithmic, which feels way nicer than linear attenuation.
- Panning was completely hosed, and caused strange cutoff issues. You could hear only about 25 tiles left/right of your character before the sound volume snapped to zero, but about 100 tiles directly up/down.
- Volume sliders now have 64 steps (instead of 16), so you can actually have some reasonably fine control over volume. Each notch equals a bit more than 1.5 dB.
> Fix sound volume/panning attenuation

- CMake/ctr/n3ds_defs.cmake
- CMake/switch/switch_defs.cmake
- CMake/vita_defs.cmake
- Source/DiabloUI/art.cpp
- Source/engine.cpp
- Source/palette.cpp
- Source/pfile.cpp
- Source/sound.cpp
- Source/storm/storm.cpp
- Source/storm/storm.h
- Source/storm/storm_file_wrapper.cpp
- Source/storm/storm_sdl_rw.cpp
- Source/storm/storm_svid.cpp
StormLib read function is not thread-safe: https://github.com/ladislav-zezula/StormLib/issues/175
This fixes static in the streaming audio on the 3DS, and probably everywhere else
Thanks @StephenCWills for the investigation!
> 🐞 Synchronize SFileReadFile access

- Source/control.cpp
Fixes a bug introduced in #1796
Frame numbers are 1-based and there are 6, not 5 frames there.
> 🐞 Fix spellbook rendering crash in hellfire

- CMakeLists.txt
- Source/control.cpp
- Source/controls/keymapper.cpp
- Source/controls/keymapper.hpp
- Source/diablo.cpp
- Source/gamemenu.cpp
- Source/gamemenu.h
- Source/miniwin/miniwin.h
This adds a keymapper that allows players to change the default key used to trigger various actions. The config file now has a new section called `Controller.Keymapping` that will be automatically filled with all defined actions and their default value.
Limitations:
* no support for having multiple keys bound to the same action (not sure if that's needed, but the original code does accept two different keys for the belt actions for instance, like '&' or '1'. '&' is on the same key as '1' on the French keyboard layout at least, and pressing this key without shift does produce '&' in most applications and not '1'. The SDL seem to have solved this though, as pressing this key on my keyboard produces '1' in the DevilutionX code. All of that to say that those alternative keys might not be …
> Add a keymapper

- CMakeLists.txt
- Source/controls/keymapper.cpp
Remove libm from linked libs list. It's already linked in by sdl2 import target, and having it not-last-in-list leads to link problems with duplicate symbols.
This also makes vita keymapper hack unnecessary.
> Vita link fix

- Translations/it.po
Hereby I submit a lot of enhancements in particular:
* Menu entries
* Accented vowels (such a pity that accents are not supported in textdat strings, so I'm forced to replace `à` with `a'`)
* Tristram experience (Shops in particular)
Another issue that I encountered is related to items qualities. An example is more than thousand words
In English I say `Silver Sword` and the piece of code that concatenate strings displays  `Silver Sword`.
In Italian I say `Sword` (Spada) `of` (di) `Silver` (Argento) and strings are concatenated as `Argento Spada` (a sort of `Sword Silver`).
That's because adjective and nouns are naturally swapped between Italian and English. Use of `of` could be avoided playing on grammar, but the swapping make the text not so delightful
At a first glance seems to be …
> 🌐 Lot of enhancements on Italian localization

- Source/.clang-tidy
- Source/render.cpp
- Source/render.h
This is part of the work to allow us to eliminate buffer padding.
As this is a hotspot, we have 4 separate functions for each non-square primitive, resulting in quite a bit of code:
1. Unclipped ("Full")
2. Vertical-only clip
3. Vertical + Left clip
4. Vertical + Right clip
FPS:
* 640x480: 1420 -> 1530
* 1280x960: 365 -> 380
> 🎉 render.cpp: Do not render out-of-bounds

- Source/diablo.cpp
- Source/items.cpp
- Source/missiles.cpp
- Source/msg.cpp
- Source/objects.cpp
- Source/pack.cpp
- Source/player.cpp
- Source/player.h
- Source/spells.cpp
This PR introduces a new action that the player can now perform by pressing an assigned key (not set by default):
- Stops any walking after the current tile
- Cancels any queued up/buffered action, like attacking, talking, interacting with objects, etc
This allows for more fine grained control of the character without having to resort to things like attacking in-place or casting a skill to stop the current action/stop walking.
> Add key to stop walking and cancel pending actions

- Packaging/ctr/README.txt
- Packaging/ctr/build.sh
- docs/building.md
- docs/installing.md
- docs/manual/platforms/n3ds.md
Just cleaning up the docs to reflect more up-to-date instructions for building and installing on 3DS.
Styled Markdown can be reviewed by visiting the following pages.
* https://github.com/StephenCWills/devilutionX/blob/3ds-docs/docs/installing.md
* https://github.com/StephenCWills/devilutionX/blob/3ds-docs/docs/building.md
* https://github.com/StephenCWills/devilutionX/blob/3ds-docs/docs/manual/platforms/n3ds.md
> Fix up documentation for building and installing on 3DS

- docs/manual/platforms/n3ds.md
The download links for the "latest release" seems backwards, as compared to the ones for individual releases. But it seems to work this way.
> Fixed download link for devilutionx-n3ds.zip

- Source/player.cpp
Fixes #1755
Before the fix:
Class | Weapon | Hitframe | Number of Frames
-- | -- | -- | --
Bard | Sword | 10 | 10
Bard | Bow | 11 | 12
Warrior | Sword | 9 | 16
Warrior | Bow | 11 | 16
Rogue | Sword | 10 | 18
Rogue | Bow | 7 | 12
You can see that the Number of Frames differ for Bard and Rogue but not the Hitframe (the Frame where the Attack hits and after that the Animation can be canceled or next Attack can be executed).
So it's not overpowered but the animation is cropped.
The fix is to restore the original 18 Number of Frames for Sword Attacks.
Notes:
- The thing that I don't understand is why this didn't occur in vanilla Hellfire. It could mean it was fixed in another way or the source in [devilution](https://github.com/diasurgical/devilution/blob/2bf6eeb125a540e83ec838d6ab9181f2b26d098 …
> Fix Bard incorrect number of sword animation frames

- Source/engine/animationinfo.h
- Source/player.h
- test/animationinfo_test.cpp
Content:
- Cleaned-up all comments with fixed Doxygen Style
- run clang-format on animationinfo.h/.cpp and animationinfo_test.cpp
@AJenbo I'm not sure how to correctly check the line ending.
Is it enough if I run clang-format / check in Visual Studio or Notepad++ the Line-Ending settings before I commit?
Sorry for this perhaps silly question. I just don't want to repeat this error anymore. :pensive:
> ADL: Cleanup comments & clang-format

- CMake/ctr/n3ds_defs.cmake
Based on comments from @glebm. https://github.com/diasurgical/devilutionX/issues/1865#issuecomment-833866115
> Instead of setting `CMAKE_CXX_FLAGS_RELEASE`, simply `set(TTF_FONT_DIR \"romfs:/\")` and add `TTF_FONT_DIR` to the `# Defines with value` list in CMakeLists.txt
`TTF_FONT_DIR` is already listed in the `# Defines with value` list so this should be all that's necessary.
> Simplify TTF_FONT_DIR definition in 3DS cmake file

- Source/DiabloUI/art.cpp
- Source/engine.cpp
- Source/init.cpp
- Source/pfile.cpp
- Source/player.cpp
- Source/sound.cpp
- Source/storm/storm.cpp
- Source/storm/storm.h
- Source/storm/storm_file_wrapper.cpp
- Source/storm/storm_sdl_rw.cpp
- Source/storm/storm_svid.cpp
Fixes more crashes on the 3DS by applying the `SFileReadFile()` mutex to `SFileCloseFile()` as well.
> Synchronize SFileCloseFile() access

- Source/scrollrt.cpp
There was no reason for this clipping from what I can tell
Now that we actually have working clipping, this just looks odd
> Remove clipping from `scrollrt_draw_cursor_item`

- CMakeLists.txt
- Packaging/ctr/README.txt
- Source/init.cpp
- docs/installing.md
- docs/manual/platforms/n3ds.md
Adds devilutionx.mpq to romfs for the 3DS build so it does not have to be deployed to the SD card separately. This includes updates to the readme to reflect this change. I also spotted a couple errors with the installation instructions for 1.2.1 and updated those accordingly.
> 3DS: Add devilutionx.mpq to romfs

- Source/engine/render/cel_render.cpp
- Source/scrollrt.cpp
Clips `CelBlitOutlineTo` and `CelBlitLightTransSafeTo` to the output buffer.
The templated implementation of the outline clipping means that this compiles to many case-specific functions with near-branchless inner loops. This increases x64 binary size by 92 KiB. We may lower some of these template parameters to values in the future (this is easier to do than the other way around) after benchmarking.
No performance difference from the outline clipping, with stippled transparency 1400 -> 1420 in this scene:
> 🎉 CEL rendering: Clip outline and stippled transparency

- Source/engine/render/cl2_render.cpp
Clips all the drawing functions except the outline one.
Example FPS gain in this location in a dungeon (CL2 sprites highlighted for reference):
1403 -> 1426
> 🎉 cl2_render.cpp: Clip the drawing functions

- Source/inv.cpp
- Source/inv.h
I've seen some discussions about auto-sorting/packing the inventory, which seems a bit contentious. This PR just ~~adds an option to tweak~~ tweaks the slot placement for picked up items, without making deeper changes.
The big differences are in the gold, which goes like this:
And other 1x1 items, which go like this:
In other words, they try to fill the bottom row from opposite ends, and once it's full they then both start working up in columns starting from the right.
2-height item placement is also changed slightly - the details for that are in the commit log. 3-height item placement is unchanged.
Not sure if anyone else is interested in this and perhaps it might be impossible to reach a consensus on the "best" filling algorithm, but this is how I want it to work so I thought it would …
> Improve inventory filling algorithm

- Source/engine/animationinfo.cpp
- Source/player.cpp
- test/animationinfo_test.cpp
- test/player_test.cpp
Before the game tried to distribute the skipped Frames across the game ticks/frames.
This resulted in checks like `if (plr[pnum]._pIFlags & ISPL_FASTRECOVER && frame == 3) {`.
This job is now done by the Animation Distribution Logic.
But ADL needs to know in advance how long an animation is shown (time represented as game ticks).
Simplified example with an Animation with 8 Frames and GameTick = 50ms:
- Animation with 8 Frames takes 8 * 50 ms = 400ms
- Same Animation with 2 skipped Frames takes 6 * 50ms = 300ms
- The original logic removed 2 frames (we missed you nice content). The resulted in the 300ms shown Animation. So each Frame was constantly shown 50 ms (with or without skipping).
- ADL also skips the 2 game ticks but it doesn't remove the frames. It shortens the frame. The …
> ADL: Advance skipped Frames in SetNewAnimation and remove logic from PM_XYZ

- Source/towners.cpp
- Source/towners.h
There is no need for `animOrder` to be a vector -- it's static data.
We don't have `std::span` yet, so opted for pointer + size.
> 🧹 towners.cpp: Avoid allocations for animOrder

- Source/nthread.cpp
Fixes #1893
Thanks @Chance4us for reporting and savegame 🙂 
I killed a him 3 times with apocalypse and didn't saw any flickering.
Without this pr, I got the flickering at the first time.
> ADL: Bugfix hero flicker when Diablo is killed

- CMakeLists.txt
Instead of having a global list of include directories, have each
library define its own.
> 🧹🔨 CMake: Move include dirs to library definitions

- Source/missiles.cpp
Fixex #1642
If we break something, we should break and don't continue if nothing happens 🤣 
Thanks @Chance4us for the nice save and reporting 🙂
> Fix breaking glass sound is missing for small life/mana potions

- Source/monster.cpp
...instead of actual unique monster transformation.
Fixes #1868 which made all uniques look positively sunburnt:
> Fix loading of infravision palette transformation

- Source/DiabloUI/dialogs.cpp
This turned out to be much simpler than I anticipated. The routine that displays the error dialog was already designed to fall back on the OS GUI if an error occurs while displaying the dialog so all I had to do was call it recursively.
On platforms using SDL1, it uses `SDL_Log()` instead of displaying the error message.
https://github.com/diasurgical/devilutionX/blob/73a90502de8bab62f55b9ebe5ce3a615dcb32f22/Source/utils/sdl2_to_1_2_backports.h#L126-L133
This presents opportunities for platform-specific improvements.
> Use OS GUI to display error message if font fails to load

- CMakeLists.txt
- Source/init.cpp
- Source/mpqapi.cpp
- Source/pfile.cpp
- Source/restrict.cpp
- Source/storm/storm.h
- Source/utils/file_util.cpp
- Source/utils/file_util.h
- Source/utils/log.hpp
Contributes to #747
Windows can per default only access UTF8-Paths with wchar_t function overloads.
References:
- https://stackoverflow.com/questions/396567/is-there-a-standard-way-to-do-an-fopen-with-a-unicode-string-file-path
- https://stackoverflow.com/questions/821873/how-to-open-an-stdfstream-ofstream-or-ifstream-with-a-unicode-filename
- Use `fstream`-Constructor with `wchar_t*` overload
- Definie Unicode for StormLib so that a `wchar_t*` (`TCHAR*`)  `SFileOpenArchive` is present
Currently config-dir is not supported, cause it's not possible to pass a File-Handle or Stream to `Radon`.
But the game will start anyway, only the ini file is ignored (not read from or written to).
- Open Game
- Play Intro
- Create Hero
- Save Hero
- Load Hero
- Delete Hero
- Read only check
An alternative …
> Allow non-ASCII symbols in data/save-directory

- Source/restrict.cpp
The same check (`FileStream`) that was introduces #1920 seems to [not work](https://github.com/diasurgical/devilutionX/pull/1920#issuecomment-836388494) under Linux/Mac.
So instead of `FileStream` use FOpen that was introduces with 6a27b37d
@AJenbo Could you try this fix?
> Fix ReadOnlyTest for Linux/Mac

- Source/DiabloUI/art_draw.cpp
- Source/capture.cpp
- Source/dx.cpp
- Source/engine.h
- Source/engine/render/cel_render.cpp
- Source/engine/render/cl2_render.cpp
- Source/palette.cpp
- Source/scrollrt.cpp
- Source/utils/display.cpp
- Source/utils/ui_fwd.h
CL2 outline is now clipped. As this is the final clipping fix, we remove the buffer padding.
After this we can start work on switching to hardware surfaces + double-buffering on platforms where we want to use 8-bit surfaces.
> 🎉 Final clipping fix + buffer padding removal

- Source/engine/render/dun_render.cpp
Turns RenderLine line branches into template parameters, helping the compiler to eliminate the branches.
Example FPS change:
* In town: 1655 -> 1700
* In dungeon: 1450 -> 1530
> 💨 dun_render.cpp: Faster RenderLine

- .gitignore
- CMakeLists.txt
- Source/diablo.cpp
- Source/main.cpp
If `GPERF` and `GPERF_HEAP_FIRST_GAME_ITERATION` are set,
start tracking allocation in `main` and save the heap state of the first game iteration.
Here is a part of the current heap state of the first game iteration for SDL1 and no audio that this produces:
> GPERF: Dump heap profile of the first game iteration

- CMakeLists.txt
- Source/platform/ctr/messagebox.cpp
- Source/utils/sdl2_to_1_2_backports.h
Custom implementation of `SDL_ShowSimpleMessageBox()` using features to display console output. Thanks to the romfs changes, it would be extremely unlikely for an error dialog to ever fall back on this function, but I feel it's still good to have a fallback that doesn't just silently "crash to desktop".
> Custom message box for 3DS

- Source/palette.cpp
Because of the frequent palette changes that change the color of water at the end of Poisoned Water Supply, the blended lookup table get regenerated every frame for 32 frames. This logic wasn't checking the `bBlendedTransparancy` flag, which caused the framerate to plummet at the end of this quest on 3DS.
> End of Poisoned Water Supply no longer ignores Blended Transparency setting

- Source/loadsave.cpp
- Source/msg.cpp
- Source/multi.cpp
- Source/player.cpp
- Source/player.h
- Source/track.cpp
- Removes `PlayerStruct.actionFrame`
- Adjusts Walking Animation to start correctly with frame 1 and ends with frame 8
- Shows skipped frames for running Animation
<Details>
<Summary>Example Videos</Summary>
https://user-images.githubusercontent.com/25415264/117880996-018a7380-b2a9-11eb-8d07-d1376664902b.mp4
https://user-images.githubusercontent.com/25415264/117880970-fa636580-b2a8-11eb-92cd-1e0f6ecca901.mp4
https://user-images.githubusercontent.com/25415264/117881533-9d1be400-b2a9-11eb-9e6d-ba74dcadf939.mp4
https://user-images.githubusercontent.com/25415264/117881304-647c0a80-b2a9-11eb-8ca1-13e33d2f56b4.mp4
</Details>
- Similar to #1781 this introduces a minor breaking change (one animation)
- It would be good if someone checks the change in tracks.cpp. I tested walking with held left …
> Remove PlayerStruct.actionFrame and enable ADL for Walking/Run

- .circleci/config.yml
The image was updated from Debian Stretch to Debian Buster in https://github.com/devkitPro/docker/commit/491845c3c3a2c9deff5ff1ad05152732bebb2d49
> 🔨 Fix Switch CI build

- Source/appfat.h
- Source/engine/render/dun_render.cpp
- Source/miniwin/miniwin.h
- Source/sha.cpp
- Source/utils/attributes.h
- Source/utils/console.h
- Source/utils/sdl2_to_1_2_backports.h
1. Moves attribute macros out of miniwin into a new header.
2. Adds `DVL_ALWAYS_INLINE` and `DVL_ATTRIBUTE_HOT`, and uses them in dun_render.cpp
> 🧹 Cleanup function attributes

- Source/diablo.cpp
- Source/palette.cpp
- Source/palette.h
- Source/quests.cpp
- Source/quests.h
This significantly reduces the amount of work that has to be done when updating the blended transparency lookup at the end of the Poisoned Water Supply quest. Here is a summary of the changes that were made.
* Refactor part of `GenerateBlendedLookupTable()` into `FindBestMatchForColor()`. This way, we can pick and choose which blended pixel combinations we update in `palette_update_quest_palette()`.
* Disable call to `GenerateBlendedLookupTable()` in `LoadPalette()` when loading the clean water palette at the end of the quest. This prevents the blended transparency lookup from immediately turning blue. This was being overwritten in `palette_update_quest_palette()` anyway.
* Disable color cycling while water color is changing. With color cycling disabled, we can copy colors from the clean …
> Optimize blended transparency calculations at the end of Poisoned Water Supply

- Source/inv.cpp
One pixel was not being calculated on the X axis when trying to find for an inventory slot to put the item.
Closes #1962 and should fix controller not being able to equip when on low resolutions.
@AJenbo @glebm
> "Dead Pixels" when trying to equip item

- Translations/ru.po
Some fixes, more "е"->"ё" changes.
It's probably the last one until the game start showing intl. symbols instead of question marks.
In other news, there is good RU translation: https://opennota2.duckdns.org/book/78016/455179?Orig_page=1 
But there is no gettext infrastructure, just eng+rus quest texts side by side.
> RU translation, part 3

- Source/cursor.cpp
- Source/engine.h
- Source/engine/animationinfo.cpp
- Source/engine/animationinfo.h
- Source/player.cpp
- Source/player.h
- Source/scrollrt.cpp
- Source/scrollrt.h
- Source/track.cpp
With this change the position of the player is now calculated independent from the game logic.
The already present information from `AnimationInfo` (ADL) is used for this.
Before this pr the player and camera position was updated 8 times for each walked tile.
With ADL we can calculate the offset relative to the animation fraction (0.0 to 1.0).
As this is a floating variable this can calculate many small steps and so positions updates.
But currently the rendering logic restricts this.
The current game logic operates on the pixel definitions of the original resolution.
For example the walking offset from one tile to another (to the east) are 64 pixels in x-axis.
As the current rendering logic is based on the game logic it's interface is also based on pixel basis.
That mean's currently we …
> ADL: Decouple positioning while walking from game logic

- Source/items.cpp
> When changing items hot-swap the hero animation data and don't start a new animation

- Source/sound.cpp
- Source/storm/storm.cpp
- Source/utils/push_aulib_decoder.cpp
- Source/utils/push_aulib_decoder.h
- Source/utils/sdl_mutex.h
Rather than rolling our own lock guard, implement the requirements for using `std::lock_guard` et al, and use that.
> ♻️ Implement std's Lockable for SDL mutex wrapper

- Source/track.cpp
Fixes #1993
Condition before my changes:
[`if (plr[myplr].actionFrame <= 6 && plr[myplr]._pmode != PM_STAND)`](https://github.com/diasurgical/devilutionX/blob/23cec61f155961918460fe5d896e686ed4249e0c/Source/track.cpp#L29)
Note: `actionFrame` was only used for walking and spell casting. In all other cases it was 0.
Buggy condition:
`if (plr[myplr].AnimInfo.GetFrameToUseForRendering() <= 6 || (!plr[myplr].IsWalking() && plr[myplr]._pmode != PM_STAND))`
This returns also if we are at the first 6 frames of the stand animation (the delay mentioned in #1993). So we don't track the changed mouse cursor in that case => Bug. 😉 
This is the new condition:
`if (player._pmode != PM_STAND && !(player.IsWalking() && player.AnimInfo.GetFrameToUseForRendering() >= 6))`
We check if we don't stand or are …
> Fix movement with hold mouse button and stand animation

- Source/controls/plrctrls.cpp
Applies the special cases for `_pInvincible` and `DoomFlag` that are present in `CheckCursMove()` logic to `plrctrls_after_check_curs_move()` as well. With the check for `_pInvincible`, the player will lose their target just before the loading screen when moving between dungeon floors or entering a Town Portal. The `DoomFlag` check simply causes the player to lose their target when the Cathedral Map is up.
This resolves #2001
> Fix crash when using Town Portal on controller

- Source/controls/game_controls.cpp
Closes the Cathedral Map when pressing the B button on the controller. Prior to this, the only way to close the Cathedral Map with controller was to attempt to open the game menu with Start+DPadUp or Start+Select.
> Close Cathedral Map when B button is pressed on the controller

- CMake/gkd350h_defs.cmake
- Source/engine.h
Works around a GCC bug on some platforms:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=97044
> Fix gkd350h build

- CMake/amiga_defs.cmake
The compiler is currently stock at GCC 6.5 which doesn't know about some of the attributes we use.
> Do not show attribute warnings for Amiga builds

- Source/scrollrt.cpp
Fix #2013
Long live the copy&past errors! :no_mouth:
> DrawPlayerHelper: Use correct player offset

- Source/engine/animationinfo.cpp
- Source/engine/animationinfo.h
- Source/items.cpp
Follow up to #1988
The number of frames for the standing animation of a [warrior with bow](https://github.com/diasurgical/devilutionX/blob/23cec61f155961918460fe5d896e686ed4249e0c/Source/player.cpp#L611) (and babarian) differs from the normal standing animation.
The following statement from #1985 was wrong:
> This is elegant but would require that all animations have the same length. **This is currently the case** but could differ if we supported loading this animation info's dynamic and a mod would change them. Example mod change: walking with heavy armor takes longer.
With the new changes even mods future should be supported.
> Support changing animation data on-the-fly even if the number of frames differ

- Source/controls/plrctrls.cpp
Digging into past commits, I found the reason why the logic for gamepad controls was fiddling with the player's direction. It allows the player to change the direction their character is facing even if their movement is blocked. This is especially important because it's what enables the player to change targets when their character can't otherwise move.
I considered allowing players to change direction at any time so long as they aren't walking. Some additional testing revealed there were situations where the player can change targets in the middle of an attack. It seems reasonable to want to change the character's target in the middle of a series of queued attacks, but it's important to wait for the hit frame so the player doesn't end up hitting an enemy they didn't swing at. …
> Fix camera jerking when changing direction on controller

- Source/DiabloUI/selconn.cpp
- Source/DiabloUI/selgame.cpp
- Source/DiabloUI/selhero.cpp
- Source/appfat.cpp
- Source/automap.cpp
- Source/control.cpp
- Source/cursor.cpp
- Source/diablo.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/monster.cpp
- Source/msg.cpp
- Source/multi.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/plrmsg.cpp
- Source/qol/xpbar.cpp
- Source/quests.cpp
- Source/stores.cpp
- Source/trigs.cpp
- Translations/da.po
- Translations/devilutionx.pot
- Translations/es.po
- Translations/fr.po
- Translations/hr.po
- Translations/it.po
- Translations/pt_BR.po
- Translations/ru.po
- Translations/zh_CN.po
This adds `fmt`'s format support for translated texts.
In its current state this is very experimental, it does compile but some texts are corrupted. The main issue lies with the menus.
> Add fmt format for translations

- Source/engine/render/cl2_render.cpp
A minor cleanup that replaces the for-loop rendering for a fill run with memsets.
> cl2_render: Use memset when rendering outline

- CMakeLists.txt
- Source/sound.cpp
- Source/utils/soundsample.cpp
- Source/utils/soundsample.h
For extremely memory-constrained devices. Gets into town on RG99 (18 FPS -> 14 FPS).
> 🔨 Add `STREAM_ALL_AUDIO` build setting

- Source/effects.h
- Source/towners.cpp
This PR fixes a few typos/spelling issues in the newly renamed `HeroSpeech` entries.
> ✏️ Fix typos and spelling mistakes on 'HeroSpeech' members

- Source/player.cpp
This PR improves the `PlrDirOK` function by passing a typed `Direction` instead of handling it as `int`.
> ♻️ Replace 'int' with 'Direction' parameter on 'PlrDirOK'

- 3rdParty/asio/CMakeLists.txt
- 3rdParty/simpleini/CMakeLists.txt
This is much faster than using git. HTTP should be used when possible (i.e. when there are no submodules).
> 🔨 CMake: simpleini, asio: Use HTTP for downloading

- Source/items.cpp
@AJenbo I know you wanted to get rid of the whole searching for items on the ground by seed, but since you haven't done that yet, it's a simple fix we can remove later and makes picking bloodstones less annoying
> assign seed to quest items + rng cleanup

- SourceX/DiabloUI/fonts.cpp
Hello,
I noticed that simply the pathing is hard coded for many things including the paths of preferred directories. The font which you are wanting to load to android - because it is located in the assets directory it will the path can be referenced form there . 
Another thing to mention, I tried to use #elif for preprocessor and it wasn't recognized .  So I made another #ifdef __ANDROID__ statement.
> added path for CharisSILB.ttf on android

- Source/controls/plrctrls.cpp
- Source/controls/plrctrls.h
- Source/engine.h
- Source/inv.cpp
- Source/inv.h
This PR introduces a new `Size` struct to represent actual sizes instead of points, and uses it where appropriate in inventory-related code, while leaving `Point`s to represent actual coordinates. The `coord` struct has also been dropped in favor of a unified representation with `Point`.
> ♻️ Cleanup 'InvXY' and 'coords' usages in favor of 'Point' and 'Size'

- Source/engine.h
- Source/inv.cpp
This PR introduces the `==` (and for symetry the `!=`) operator to `Size` struct and uses them where appropriate for now.
> ♻️ Add '==' and '!=' operators to 'Size' struct

- .circleci/config.yml
This adjusts the cmake commands for the CircleCI build for 3DS to match some of the other builds that didn't fail after `.gitkeep` was removed from the build folder. This makes the 3DS build a bit more robust and works around a CircleCI issue where restoring `.gitkeep` does not fix the build.
> Fix 3DS CircleCI build

- Source/interfac.cpp
I guess currlevel gets updated at a later point, so during transitions between levels, currlevel holds old level and plr[myplr].plrlevel has new
Resolves https://github.com/diasurgical/devilutionX/issues/2097
> fix loading screens:

- Source/missiles.cpp
- Source/multi.cpp
+ sounds for nonphysical damage were using attacker's class, not the player being hit
> fix wrong sound/message

- Source/objects.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2126
Looks like there are 2 sets of chests and thaumaturgic only handled one
> fix thaumaturgic

- .circleci/config.yml
I haven't seen a failure on master yet, but I have a feeling this will be necessary starting with the next commit.
This is based on the fix for the Switch build in #1945.
> Fix 3DS CI build

- Source/dvlnet/tcp_client.cpp
This is just something that's been bugging me while ironing out the networking on the 3DS. The game never explicitly cleans up client sockets and so connections tend to remain open until the user enters a new game, the connection times out, or the user quits the game. This calls close on the client socket explicitly when the player leaves their game to clean up the connection as soon as it's no longer needed.
> Close TCP client socket when leaving game

- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
- Source/qol/itemlabels.cpp
- Source/scrollrt.cpp
Contributes to #838
This uses `AnimationInfo` in `ItemStruct`.
Notes:
- This change shows the first Frame of Flipping that wasn't shown previous.
- Magic Rock uses normal/old Logic cause it's the only item that didn't stop the Animation with the last Frame, so ADL doesn't help here anyway.
<details><summary>Example Video (5% game speed)</summary>
https://user-images.githubusercontent.com/25415264/119418493-6bb70580-bcf8-11eb-86c6-5a45696df657.mp4
https://user-images.githubusercontent.com/25415264/119418507-71145000-bcf8-11eb-9362-23cae37c8c6f.mp4
</details>
> Enable ADL for Items

- Source/engine.h
- Source/inv.cpp
This PR renames both `Size.Height` and `Size.Width` to `Size.height` and `Size.width` respectively as we are setting our standard for field naming.
This will help later as well with fields having the same name as their types.
> 🎨 Make 'Size' fields camelCase

- Source/inv.cpp
- Source/monster.cpp
- Source/msg.cpp
- Source/multi.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/player.h
- Source/towners.cpp
- test/animationinfo_test.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2140
From what I understand, you cannot just save the indexes of 3 items like this and then remove them one by one, as removing an item might affect other indexes, so you have to perform the check again to obtain a valid index
Actually this was a good opportunity to rewrite that ugly HasItem / RemoveInvItem combo, the code looks much cleaner imo
I moved `TryRemoveInvItemById` to separate conditions to make it more visible that this check actually performs an action so it has to be last. Otherwise an if could fail but you'd remove an item!
> fix reconstructed note + HasItem/RemoveInvItem combo rewritten into TryRemoveInvItemById

- Source/objects.cpp
- Source/objects.h
This function is relatively isolated, only being used in a single check inside OperateStoryBook(). Hopefully the comment and names make sense. The choice of UpperCamelCase for both variable and function names is to match other globals.
> Add descriptive name and comments for the Na-Krul spell tome check

- Source/itemdat.h
- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
- Source/loadsave.h
- Source/pack.cpp
This PR is an initial change to allow us to use the `_item_indexes` enum directly in a few places instead of relying on raw 'int' values.
It replaces the raw int in the `ItemStruct` and then makes a few changes to ensure places that populate and read that value (packing and unpacking for now) are updated to handle the value as a proper enum.
> Use '_item_indexes' in the 'ItemStruct' model and make item conversion code typesafe

- Source/loadsave.cpp
Fixes #2149
When loading a game not all members of AnimationInfo gets set explicitly.
But we should ensure they are all set to the default.
> Ensure AnimationInfo is reset when a game is loaded

- Source/scrollrt.cpp
The correct size is +2px for the outline, because the outline is on both sides.
Fixes #2179
> 🐞 Fix off-by-one in `DrawCursor`

- docs/building.md
Updates build instructions for Nintendo 3DS based on recent changes in devkitPro.
> Update 3DS build instructions

- CMakeLists.txt
- Source/DiabloUI/credits.cpp
- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/dialogs.cpp
- Source/DiabloUI/progress.cpp
- Source/cursor.cpp
- Source/cursor.h
- Source/diablo.cpp
- Source/engine.cpp
- Source/gamemenu.cpp
- Source/hwcursor.cpp
- Source/hwcursor.hpp
- Source/interfac.cpp
- Source/miniwin/misc_msg.cpp
- Source/movie.cpp
- Source/options.h
- Source/palette.cpp
- Source/scrollrt.cpp
- Source/scrollrt.h
- Source/utils/sdl_ptrs.h
Disabled by default because of these issues:
1. When clicking on inventory item, it briefly appears a bit shifted (in the wrong coordinates).
This issue can happen with software cursor as well, but is a lot more obvious with the hardware cursor.
2. Cursor is scaled with nearest-neighbour scaling, which may look a bit different from how the rest of the graphics are scaled.
See also previous attempt: https://github.com/diasurgical/devilutionX/pull/955 by @viciious
> 🎉 Hardware cursor (SDL2-only)

- Source/DiabloUI/credits.cpp
- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/dialogs.cpp
- Source/hwcursor.cpp
- Source/hwcursor.hpp
- Source/interfac.cpp
- Source/inv.cpp
- Source/palette.cpp
- Source/scrollrt.cpp
1. Use the native hotpoint capability of the hardware item cursor instead of doing it ourselves.
2. Fall back to software cursor if the hardware one fails to initialize.
> Hardware Cursor: A couple of improvements

- Source/engine/render/text_render.cpp
- Source/engine/render/text_render.hpp
Given the program already lets the destructors get called naturally there's no need to explicitly call this function. Even if it was desirable to re-init the font data the old instances will be destroyed when the new instance is assigned to the optional.
> Remove dead code, FreeText() is never called

- Source/engine.cpp
It was documented as if this stored a seed in the previous LCG cycle but it actually stored the initial seed for the current cycle. This value is never used.
> Remove unused variable.

- CMakeLists.txt
- Source/engine.cpp
- Source/engine.h
- test/random_test.cpp
This documents the chosen LCG parameters and the default mapping function used in random number generation.
GetLCGEngineState() is a helper needed for testing because AdvanceRndSeed combines a distribution with a call to progress the engine. I'll split those eventually but this at least shows the current behaviour and should flag any bugs introduced by future changes.
> Add tests for LCG random engine

- CMake/ctr/asio/include/errno.h
- CMake/ctr/asio/include/net/if.h
- CMake/ctr/asio/include/netdb.h
- CMake/ctr/asio/include/netinet/in.h
- CMake/ctr/asio/include/sys/ioctl.h
- CMake/ctr/asio/include/sys/poll.h
- CMake/ctr/asio/include/sys/socket.h
- CMake/ctr/asio/include/sys/uio.h
- CMake/ctr/asio/include/sys/un.h
- CMake/ctr/n3ds_defs.cmake
- CMakeLists.txt
- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/selgame.cpp
- Source/DiabloUI/selhero.cpp
- Source/DiabloUI/ui_item.h
- Source/dvlnet/packet.cpp
- Source/nthread.cpp
- Source/platform/ctr/asio/net/if.c
- Source/platform/ctr/asio/sys/socket.c
- Source/platform/ctr/asio/sys/uio.c
- Source/platform/ctr/keyboard.cpp
- Source/platform/ctr/keyboard.h
- Source/platform/ctr/random.cpp
- Source/platform/ctr/random.hpp
- Source/platform/ctr/sockets.cpp
- Source/platform/ctr/sockets.hpp
- Source/platform/ctr/system.cpp
- Source/storm/storm.h
- Source/storm/storm_net.cpp
FINALLY, I have a version that can play Multiplayer with a Windows client, and presumably other clients.
Notes:
* Initializing the SOC service requires allocation of a 1 MB memory-aligned buffer. I'm currently doing this at startup, but it isn't necessary for Single Player games so it might be nice if this could be done as-needed.
* This PR includes a modification to the `opslimit` and `memlimit` parameters used in the libsodium algorithm for key derivation. That makes this version incompatible with prior versions so this version cannot join games hosted on older versions and vice-versa.
* Hosting games is noticeably slower than joining games on o3DS. In cross-play situations, it would probably be best if the 3DS does not host the game.
> Compiling ASIO for 3DS

- Source/inv.cpp
Fixes a giant non-exhaustive switch warning in `UseInvItem`:
```
../Source/inv.cpp: In function ‘bool devilution::UseInvItem(int, int)’:
../Source/inv.cpp:2131:9: warning: enumeration value ‘IDI_GOLD’ not handled in switch [-Wswitch]
2131 |  switch (item->IDidx) {
|         ^
../Source/inv.cpp:2131:9: warning: enumeration value ‘IDI_WARRIOR’ not handled in switch [-Wswitch]
../Source/inv.cpp:2131:9: warning: enumeration value ‘IDI_WARRSHLD’ not handled in switch [-Wswitch]
../Source/inv.cpp:2131:9: warning: enumeration value ‘IDI_WARRCLUB’ not handled in switch [-Wswitch]
...
```
> Fix `-Wswitch` in `UseInvItem`

- test/random_test.cpp
These tests cases cover all instances of undefined behaviour and implementation defined behaviour that I could see in the current `AdvanceRngSeed()` and `GenerateRnd(int)` functions. I've added/updated comments to refer to the relevant sections in the spec (based off the latest working drafts since I'm too cheap to pay for the official standards 😂 ).
> Expand test cases for Diablo RNG to cover UB/IB

- Source/items.cpp
This PR rewrites all health/mana/rejuvenation potion effect descriptions so that the message is consistently conveyed for all potion types, using more adequate and concise terminology.
| Potion | Old Description | New Description |
| --- | --- | --- |
| Healing | "Recover partial life" | "Restore some life" |
| Full Healing | "Fully recover life" | "Restore all life" |
| Mana | "Recover mana" | "Restore some mana" |
| Full Mana | "Fully recover mana" | "Restore all mana" |
| Rejuvenation | "Recover life and mana" |  "Restore some life and mana" |
| Full Rejuvenation | "Fully recover life and mana" | "Restore all life and mana" |
This resolves #807
> Reword potion effect descriptions for consistency

- Source/player.cpp
Refactored the `StartWalk(...)` function into different functions and templated some with the `Direction` enum.
As I've noticed, most of the params of the old `StartWalk(...)` functions were tightly coupled with the `Direction` parameter. For this reason, I added the `std::array<DirectionSettings, N>` to hold those tightly coupled dependencies and resolve them at compile time. Hopefully, we have gained some runtime efficiency there.
I understand I may not have named the functions correctly, so please feel free to suggest better names for them. These functions are:
- HandleWalkMode
- WalkDownwards
- WalkUpwards
- WalkSides
> Refactored "StartWalk(...)" 

- Source/engine/cel_header.hpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/player.cpp
- Source/towners.cpp
- Source/utils/endian.hpp
1. Rename `CelGetFrameStart` to `CelGetFrame`, in line with the other 2 functions with the same name and load the `uint32_t` safely.
2. Remove redundant `FrameHeader`, simply use `LoadLE16`.
3. Document all the functions.
> ♻️ Clean up `cel_header.hpp`

- Source/missiles.cpp
* use static_cast
* fix bad math that yielded same result as correct math
> Direction16: nits

- test/random_test.cpp
This could be isolated due to a potentially faulty implementation, the upper bound is higher than the max possible value.
> Expand test cases to cover ShiftDistribution function

- Source/automap.cpp
- Source/control.cpp
- Source/controls/modifier_hints.cpp
- Source/engine/render/text_render.cpp
- Source/engine/render/text_render.hpp
- Source/gmenu.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/scrollrt.cpp
- Source/stores.cpp
This function calls through to DrawString which is effectively a wrapper around SDL drawing functions, so that function is currently taking an SDL_Rect. I've used devilutionx::Point instead of SDL_Point as the operator overloads allow calculating the specific points used for each hint position. Using the project class also let me add an explicit conversion function to go from Point to SDL_Rect in a way that suits the needs of this function. This probably could be done as a friend function for SDL_Point but I wasn't sure if adding to third party library classes is encouraged or avoided for this project.
This is part of a bunch of refactoring I've done for issue #1684, I'm splitting them into separate pull requests to minimise conflicts with other refactoring efforts such as pull requests …
> Refactor DrawCircleMenuHint, DrawString to use devilutionX::Point

- Source/engine/animationinfo.cpp
- Source/engine/animationinfo.h
- Source/loadsave.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
- Source/player.cpp
- Source/scrollrt.cpp
Contributes to #838
https://user-images.githubusercontent.com/25415264/122987556-04e14680-d3a1-11eb-99ac-87ad25775cc7.mp4
https://user-images.githubusercontent.com/25415264/122987578-0b6fbe00-d3a1-11eb-81ff-359493dbb465.mp4
</details>
Notes:
- This PR introduces ADL to Monsters
- Currently it's used for
- Attacks
- Range-Attacks
- Spell-Attacks
- The other animations are not included to make the size of the pr manageable.
- This pr lays the groundwork for future followup PRs. Similar to what was done for players:
- Walking
- Decouple positioning while walking from game logic
- Blocking
- MA_SPECIAL (for example gargoyle heal)
- Death
> Enable ADL for Monsters

- Source/loadsave.cpp
- Source/monster.cpp
- Source/monster.h
- Source/scrollrt.cpp
Beware! The monsters are getting faster! 👹 
Contributes to #838
https://user-images.githubusercontent.com/25415264/123510936-8de8ce00-d67e-11eb-8397-fe39538104d1.mp4
https://user-images.githubusercontent.com/25415264/123510939-950fdc00-d67e-11eb-9854-fbb0638937b8.mp4
</details>
Notes:
- No behavior changes
- Similar to #1939 this introduces a minor breaking change (one animation)
> Enable ADL for Monster walking and decouple positioning while walking from game logic

- Source/controls/plrctrls.cpp
- Source/engine/point.hpp
As part of this I moved the toPoint lambda to a class function on Point (and renamed it since Point::toPoint read a little off 😂 ). Ideally this would be an explicit conversion function on Direction but as that's an enum as far as I know it's not supported in c++.
I've skipped over GetItemSizeOnSlot as this is being updated in pull request #2130.
> Refactor plrctrls functions to use Point and Direction types

- Source/effects.cpp
- Source/effects.h
- Source/effects_stubs.cpp
- Source/items.cpp
- Source/missiles.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/quests.cpp
- Source/towners.cpp
- test/effects_test.cpp
This is used in quite a few places in objects.cpp and had some very confusing invocations in the various Operate*Door functions due to the inconsistent use of temporary/alias variables. I've included some refactoring of these functions to try and make it clearer while I was in the area.
This may conflict with pull request #2115, would be worth approving that request before this one so I can fix any conflicts I cause.
I plan to open a separate pull request for ObjSetMicro and other related functions in objects.cpp, I've picked these changes out to try keep the diffs manageable.
> Refactor sound related functions to use Point

- Source/engine/animationinfo.cpp
- Source/engine/animationinfo.h
Notes:
- No behavior or animation changes
- `TicksSinceSequenceStarted` should never be < 0 when `GetFrameToUseForRendering` is called. Else it's a bug. But if we get a bug, this information should help a little bit.
> ADL: Minor Cleanup

- Source/diablo.cpp
- Source/engine.cpp
- Source/engine.h
- Source/items.h
- Source/loadsave.cpp
- Source/monster.h
- Source/msg.h
- Source/multi.h
- Source/objects.h
- Source/towners.cpp
- Source/towners.h
- test/random_test.cpp
Most calls to set seed were using uint32_t already, there were a few variables which were better served by having their type changed from signed to unsigned. The one exception is ItemStruct::_iSeed. This is an identifier that also happens to be used as a seed occasionally, ~so when that is passed to SetLCGEngineState I cast to uint32_t manually~. I have left this doing an implicit conversion to avoid excessive changes in this PR.
~As part of this change some functions were renamed to better indicate their use. This is deliberately awkward naming as this random engine needs to maintain compatibility with the base game.~
> Update random number functions to avoid IB

- Source/diablo.cpp
- Source/diablo.h
- Source/monster.cpp
Contributes to #838
<details><summary>Example Video Death Animation</summary>
https://user-images.githubusercontent.com/25415264/123561175-35612000-d7a7-11eb-86c4-cee3d5036e06.mp4
https://user-images.githubusercontent.com/25415264/123561179-3d20c480-d7a7-11eb-81f0-dfcf6200f707.mp4
</details>
<details><summary>Example Video Got Hit Animation</summary>
https://user-images.githubusercontent.com/25415264/123561188-4ad64a00-d7a7-11eb-94ea-03a2e4206e15.mp4
https://user-images.githubusercontent.com/25415264/123561191-4f026780-d7a7-11eb-9744-b5450c4083c9.mp4
</details>
Notes:
- The death and got hit animation can be truncated if the attack is executed in `ProcessPlayer` (cause `ProcessPlayer` runs for `ProcessMonsters`). This doesn't happen if the hit comes from a missile (cause `ProcessMissiles` …
> Enable ADL for Monster Death and Got-Hit Animation

- Source/control.cpp
- Source/engine/displacement.hpp
- Source/engine/point.hpp
- Source/player.h
The player HP/Mana percentage calculations are doing conversions that are unnecessary with the operands and the expected values during gameplay. Refactoring the life flask upper section for now, I'll have a go at the rest when I get more time.
This also includes explicit casts for Point/Displacement operator/ because I was planning on doing a bunch of small changes then I almost immediately hit the code in DrawLifeFlask 😂 . I can break it out if desired.
> Clean-up uneccesary type conversions in player hpPer calculations

- Source/monster.cpp
- Source/monster.h
- Source/player.cpp
This was broken during a previous refactoring.
https://github.com/diasurgical/devilutionX/commit/21fdb0dcd951ab5adee57b5a212e2d86e6ac036f#diff-d46585089d315b53630b1035442b3d490d7b422cb05ceee76cf9041de3e39179L1251-L1252
The name is taken from the cleanup that was done to Devilution but hasn't been merged yet: https://github.com/diasurgical/devilution/blob/master/Source/monster.cpp#L1323
I noticed this while doing a general clean up so it's a bit tangled with with the clean up of the function it self.
> Fix AddDoppelganger

- Source/loadsave.cpp
Instead of writing uninitialized memory to the file, which can lead to
issues with older game versions, we now write zeroes.
One alternative would be to have separate `skip` and `blank` functions
but I think we want the save files from the same state to be
byte-identical, so we always write zeroes.
Fixes #2281
> SaveHelper: Write zeroes on `skip`

- Source/control.cpp
- Source/engine/render/text_render.hpp
- Source/error.cpp
- Source/help.cpp
- Source/items.cpp
- Source/minitext.cpp
- Source/plrmsg.cpp
- Source/qol/monhealthbar.cpp
- Source/quests.cpp
- Source/stores.cpp
Fixes warnings such as this one:
```
Source/engine/render/text_render.hpp:83:33: warning: suggest braces around initialization of subobject [-Wmissing-braces]
return DrawString(out, text, { position.x, position.y, out.w() - position.x, 0 }, flags, spacing, lineHeight, drawTextCursor);
^~~~~~~~~~~~~~~~~~~~~~
```
> Fix `-Wmissing-braces`

- Source/scrollrt.cpp
Fixes #2286 
Hey @ephphatha, how does this look?
let me know if this needs any changes! Thanks
> fix: DrawMissile code doesn't handle cases where dMissile[x][y] == 0

- Source/loadsave.cpp
Also ensuring that size_t is used consistently for size/offset types.
> Introduce template form of skip to represent deprecated variables

- Source/missiles.cpp
58cddd6e changed MI_Rhino (Charging monsters) so that the old dMonster variable aren't reset correctly.
That means the game thinks the tile is occupied with the monsters.
This results in players and monsters can't move to them. If the cursor hovers over this not updated tiles, the monster information is (incorrectly) shown.
> Fix MI_Rhino don't update dMonster correctly

- Source/monster.cpp
After 9ffafdfc `PlaceUniques` in monster.cpp calculates wrong monster type.
The check for `done` was [moved](https://github.com/diasurgical/devilutionX/commit/9ffafdfcc6d4aa0d1717e8df8a89d52298e6c4aa#diff-d46585089d315b53630b1035442b3d490d7b422cb05ceee76cf9041de3e39179R930).
That means that `m` was one less then before the commit.
Possible fixes:
- Move check back up
- Remove the extra decrementation.
This pr does the later.
I noted the bug cause my save game tried to load a golem as unique enemy monster. And a golem has no default stand animation, so i got a assert while loading a animation. 😉
> Fix PlaceUniques calculates wrong monster type

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/ttf_render_wrapped.cpp
- Source/controls/controller_motion.cpp
- Source/controls/devices/game_controller.cpp
- Source/controls/plrctrls.cpp
- Source/controls/touch.cpp
- Source/engine/animationinfo.cpp
- Source/hwcursor.cpp
- Source/items.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/objects.cpp
- Source/options.cpp
- Source/palette.cpp
- Source/player.cpp
- Source/storm/storm_svid.cpp
- Source/utils/display.h
- Source/utils/file_util.cpp
- Source/utils/push_aulib_decoder.cpp
- Source/utils/soundsample.cpp
Some of the c-style casts appeared to be unnecessary, they were either casting variables to the same type or forcing a narrower conversion than numeric conversion rules would have defaulted to. I've only checked this on MSVC, not sure if this was needed for a specific compiler.
> Fix C4244 - type conversion warnings in MSVC

- Source/hwcursor.cpp
- Source/options.cpp
- Source/options.h
Enables safe parts of the hardware cursor by default:
1. Disabled for items due to the jumping glitch.
2. Limited to 128px size due to buggy large cursors on some systems.
> 🎉 Hardware cursor: Enable safe parts by default

- Source/hwcursor.cpp
- Source/lighting.cpp
- Source/missiles.cpp
Addresses the last remaining C4244 warnings (ignoring third party code).
missiles.cpp is doing a lot of conversion between screen space and world space which really shouldn't be necessary, but I couldn't be bothered trying to unpick it now. That'll be a later job unless someone else wants to take it on.
> Add explicit casts/replace c-style casts for type conversions

- Source/utils/display.h
This reverts commit d3c36166dfd53532af9fbe8b3754c269d4db632a.
Caused cursor to jump to bottom of the screen after picking an item up
> Revert "Add explicit cast for LogicalToOutput"

- Source/DiabloUI/diabloui.cpp
- Source/diablo.cpp
- Source/diablo.h
- Source/miniwin/misc_msg.cpp
- Source/sound.cpp
- Source/sound.h
When playing singleplayer, when the game window loses focus, I thought it would be nice to mute the music and pause the game.
This is very useful when you're playing for 10-15 at home and a pesky Teams meeting springs up and you just want to answer without having the music playing in the back.
> Pause game and mute music when game window loses focus

- Source/loadsave.cpp
- Source/objects.cpp
- Source/objects.h
- Source/quests.cpp
Trying to minimise the direct references to Objects so it can eventually be treated like a vector of active objects.
I suspect SyncQSTLever would be appropriately renamed SyncQuestLever but I wasn't sure so I left it as is. SyncPedistal looked like a typo given the string used is "Pedestal of Blood".
> Object by reference in SyncObjectAnimation functions

- Source/engine/displacement.hpp
- Source/objects.cpp
- Source/objects.h
- Source/setmaps.cpp
- Source/setmaps.h
Due to the way this function is used it was easiest to also change ObjIndex to return a reference to the object instead of the index. Also added an explicit conversion from Size to Displacement to make one of the uses slightly cleaner to express.
> Move SetObjMapRange to a member function

- Source/monster.cpp
Diablo is the only monster that contains skipped frames, only for the got-hit animation and only in hellfire.
Now we get the missing frames back.
<details><summary>Example Video (10% game speed)</summary>
https://user-images.githubusercontent.com/25415264/125210759-192eaa00-e2a2-11eb-984e-184e0a36d348.mp4
https://user-images.githubusercontent.com/25415264/125210761-1df35e00-e2a2-11eb-937e-4075d0490ab8.mp4
</details>
Notes:
- No behavior changes, only animations
- Golem has no Got-Hit animation, so `NewMonsterAnim` shouldn't be called with Golem and Got-Hit. That's why I think that the path that previous didn't checked for `MT_GOLEM` should be fine.
> ADL: Handle skipped Frames for Diablo Got-Hit Animation

- Source/monster.cpp
Fixes #2338
- This slightly breaks save game compatibility, cause vanilla doesn't use `_mgoalvar2`. But it's only when a fallen is retreating.
- The bug is also present in vanilla. Just with a different manifestation. When you save a game with a fallen that retreated and load it again it shows the wrong animation. This is cause `SyncMonsterAnim` uses `_mdir` to load the animation. And so `_mmode` and the animation doesn't match. 😉 
- Introduce new Variable `RealMonsterDirection` to `MonsterStruct` 😛
- Calculate the direction from used `CelSprite` (comparing pointers) :open_mouth:
But both wouldn't fix the vanilla bug and the way `SyncMonsterAnim` is used it seams that the game expects that `_mdir` and animation always matches (this should also be the case for players etc.).
@Chance4us …
> Fallen fear: Use _mgoalvar2 for new direction instead of _mdir

- Source/monster.cpp
- Source/monster.h
Fixes #2359
Similar to #2354 animation and `_mdir` doesn't match.
In this case cause the unique monsters call the normal monster AI.
These monster AIs can start a new animation (for example walk).
But the unique monster AI overrides `_mdir` and so `_mdir` and animation get out of sync.
The fix is that `CheckStandAnimationIsLoaded` also sets `_mdir` and only in stand.
> MAI Garbud/Zhar/SnotSpill/Lazurus/Lachdanan/Warlord Change _mdir in CheckStandAnimationIsLoaded (and only in stand).

- Source/dead.cpp
- Source/engine/animationinfo.cpp
- Source/engine/animationinfo.h
- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
- Source/scrollrt.cpp
After #2354 and #2361 I thought about refactoring monster animation logic a little bit.
Content:
- Less locations where `_mdir` is set
- Less locations that directly work with `AnimStruct`
- Scoped enum `MonsterGraphic`
... and there is much more to refactor but step for step 😉
> Refactor NewMonsterAnim and MonsterGraphic enum

- Source/gendung.cpp
Broken in 1.0.0 a1b7b8522a528cc5fd309b4295bbb3aa255bea30
Fixes https://github.com/diasurgical/devilutionX/issues/2340
Additionally this now does proper bounds check before accessing the `dungeon` array.
> :bug: WillThemeRoomFit is failing to place rooms near edge of map

- Source/monster.cpp
This fixes the bug mentioned here: https://github.com/diasurgical/devilutionX/discussions/2280#discussioncomment-996030
The cause was the refactor to DeleteMonster() here: https://github.com/diasurgical/devilutionX/pull/2283/commits/71241d1a31b1e2e9e4e491fe22787557a754b708#diff-d46585089d315b53630b1035442b3d490d7b422cb05ceee76cf9041de3e39179R1235
With the two values not swapped, then values in ActiveMonsters after ActiveMonsterCount could have the same id as alive monsters, thus monsters being spawned (ie, by the skeleton king) could overwrite alive monsters and all kinds of funky stuff happened.
> Bug fix related to monster spawning

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/selgame.cpp
- Source/DiabloUI/selhero.cpp
- Source/DiabloUI/ui_item.h
There are two instances where a UiArtText of the title is created before setting the title.
The title used to be a char[], so updating the title before the UiArtText is draws used to be sufficient. After a change introduced in https://github.com/diasurgical/devilutionX/pull/2303, the UiArtText retains the contents of title at the time of its instantiation.
This fixes https://github.com/diasurgical/devilutionX/issues/2373 as well as something similar happening for Create/Join TCP Game.
> DiabloUI: make UiArtText follow mutating char*

- Source/player.cpp
Fixes #2377
Was introduced with 5ee7edbde1fcb92daac41b58f5bdac4942261a67 
> 5ee7edbde1fcb92daac41b58f5bdac4942261a67 is the first bad commit
> commit 5ee7edbde1fcb92daac41b58f5bdac4942261a67
> Date:   Wed Jun 16 21:30:39 2021 +0100
> 
>     Refactored "StartWalk(...)" into different functions and moved tightly coupled "Direction" parameters into an array.
> 
>  Source/player.cpp | 352 +++++++++++++++++++++++++++++-------------------------
>  1 file changed, 189 insertions(+), 163 deletions(-)
Before 5ee7edbde1fcb92daac41b58f5bdac4942261a67 `ScrollViewPort` was called [before](https://github.com/diasurgical/devilutionX/commit/5ee7edbde1fcb92daac41b58f5bdac4942261a67#diff-71461699ae2f94f652e6cba2136d3c696151ba3a6c0e357eaf55438a5c212ad3L1325-L1328) the `player.position.tile` was updated. …
> Fix ScrollViewPort

- Source/misdat.cpp
- Source/missiles.cpp
- Source/missiles.h
- Source/scrollrt.cpp
Fixes #2371
Now when a missile hits, the velocity is set to zero.
So ADL doesn't calculate a new position.
In some cases also the offset is copied (for example firebolt).
This should be okay, cause the offset isn't used (apart from rendering) for the game logic.
> Introduce MissilePosition.StopMissile

- Source/DiabloUI/diabloui.h
- Source/DiabloUI/selgame.cpp
- Source/DiabloUI/selhero.cpp
- Source/mainmenu.cpp
- Source/mainmenu.h
- Source/multi.cpp
- Source/pfile.cpp
- Source/pfile.h
- Replaces all usages of hero name to load/save games with save number
- Allows creation of a hero with same name
- In debug shows save number as information
<details><summary>Debug Sample</summary>
</details>
I did this cause it was sometimes frustrating to debug reported issues.
I copy the save game into my save folder and sometimes there is already a hero with the same name.
Before this PR it was impossible to select them correctly. It was always the first one loaded.
It would be good if someone else could test this PR before it get merged.
> Allow heros with same name

- Source/dthread.cpp
- Source/msg.cpp
- Source/tmsg.cpp
- Source/utils/thread.cpp
When malloc fails, it does so silently and returns NULL. Not checking the returned value causes the program to segfault sometime later.
Such calls were replaced with new, which fails right away with bad_alloc.
> Get rid of unchecked calls to malloc

- Source/inv.cpp
This reverts this part of the code to before my cleanup, 
I added some log
INFO: r == slotxy_chest_last
INFO: itemSize.width & 1
INFO: itemSize.height & 1
INFO: DONE WITH SLOT: 24
INFO: r == slotxy_chest_last
INFO: itemSize.width & 1
INFO: itemSize.height & 1
INFO: GOING OUT WITH SLOT: 25
so it seems the "working" code actually hits that if twice, I have no clue how inventory works at this point so just leaving it alone
Resolves https://github.com/diasurgical/devilutionX/issues/2366
> fix upper left inventory corner

- .circleci/config.yml
- CMakeLists.txt
- Source/quests.cpp
- Source/quests.h
- test/quests_test.cpp
Required splitting the code to a separate function so it can be tested in isolation
> Add tests for quest randomisation code

- 3rdParty/libzt/CMakeLists.txt
- CMakeLists.txt
`-fpermissive` is not supported in MSVC (and I think in clang too?).
So we get a warning that it's unknown:
`Command line warning D9002: ignoring unknown option '-fpermissive'`
Solution: Don't set `-fpermissive` if MSVC is used.
Set [`_CRT_SECURE_NO_WARNINGS`](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996) this disables warnings like:
`warning C4996: 'strcpy': This function or variable may be unsafe. Consider using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.`
Alternative solutions: use `strcpy_s` and friends. But I don't know if this is desired and if it is supported on all platforms that devilutionX is running.
That's why I think it would be a good idea to disable the warning …
> Fix MSVC specific warnings

- Packaging/ctr/README.txt
- docs/manual/platforms/gkd350h.md
- docs/manual/platforms/n3ds.md
- docs/manual/platforms/retrofw.md
- docs/manual/platforms/rg350.md
- docs/manual/platforms/switch.md
Since I made a small fuss in the Discord, I thought I might as well do what I can to make sure the Discord links are all up to date.
> Fix Discord links in platform manuals

- Source/DiabloUI/ui_item.h
- Source/controls/controller_motion.cpp
- Source/utils/soundsample.cpp
With this changes warnings are reduced from 166 to 51.
Especially the warning in `ui_item.h` was often reported cause it was included in multiple places.
Now there are only warnings in `.cpp` files left.
> Fix some warnings

- Source/dthread.cpp
- Source/dthread.h
- Source/msg.cpp
- Source/multi.cpp
dthread.cpp had various issues, the biggest of which is that it erroneously used TMegaPkt for its internal data structures. This patch also eliminates some needless memory copies.
> dthread.cpp revamp

- Source/DiabloUI/scrollbar.h
- Source/DiabloUI/ui_item.h
- Source/control.cpp
- Source/engine/surface.hpp
The 64bit build has more warnings then the 32bit build, cause `size_t` is defined differently.
This PR fixes the 64bit specific warnings in header files caused by `size_t`.
With this changes the warnings for 64bit builds are reduced from 381 to 120.
All numbers for MSVC. 😉
> Fix some 64bit warnings

- Source/dthread.cpp
- Source/utils/sdl_cond.h
- Source/utils/sdl_mutex.h
Dthread had some convoluted synchronization logic, and made use of 2 mutexes and 1 condition variable. It lends itself to a more standard producer-consumer approach.
On the consumer: Drain the message queue in a loop. Once empty, wait for a signal.
On the producer: Signal whenever something new is placed in the queue. If this occurs during `multi_send_zero_packet`, the signal is lost, but the consumer checks the queue again.
When killing the thread: if this happens during `multi_send_zero_packet`, `DthreadRunning = false` is sufficient to kill the thread. Otherwise, the thread is signaled again and eventually dies.
> dthread: simplify synchronization logic

- Source/loadsave.cpp
- Source/monster.cpp
- Source/monster.h
Fixes #2413
Bug was introduced in #2379 commit a44781bd73d440628a096f4e79e4dbc27cbcc590
`packsize` got a negative overflow.
This is cause the [new check](https://github.com/diasurgical/devilutionX/pull/2379/commits/a44781bd73d440628a096f4e79e4dbc27cbcc590#diff-d46585089d315b53630b1035442b3d490d7b422cb05ceee76cf9041de3e39179R1966) can [subtract separated minions](https://github.com/diasurgical/devilutionX/pull/2379/commits/a44781bd73d440628a096f4e79e4dbc27cbcc590#diff-d46585089d315b53630b1035442b3d490d7b422cb05ceee76cf9041de3e39179R1972-R1973) multiple times from `packsize`.
First I reverted to the original logic (first commit), refactored the logic again (second commit) and last did some renaming to reduce future misunderstandings (third commit).
Notes:
- Existing saves can't be fixed by …
> Fix separated monster pack handling

- Source/automap.cpp
Fixes player arrow jiggling in automap.
<details><summary>Sample video 5% game speed</summary>
https://user-images.githubusercontent.com/25415264/126181509-bdf28587-b58d-4746-af30-ea577dae2872.mp4
https://user-images.githubusercontent.com/25415264/126181546-74554463-9be5-41cf-b7ff-ec80bf6fc855.mp4
</details>
Integer precision/rounding issue:
5 * 50 / 100 / 2 = 1
27 * 50 / 100 / 2 = 6
but
(5+27)  * 50 / 100 / 2 = 8
😉 
Note:
The jiggling is also present in vanilla.
> Fix automap jiggling for player arrow

- Source/controls/devices/joystick.cpp
I assume this return statement was removed by mistake because most platforms do not define these `JOY_AXIS_*` variables.
This resolves #2442
> Fix 3DS crash at startup

- Source/engine/animationinfo.cpp
- Source/engine/animationinfo.h
- Source/items.cpp
Fixes #2455 
Notes:
- Main problem was that we [changed](https://github.com/diasurgical/devilutionX/pull/2244) from `delayLen` to `ticksPerFrame` but the call in `items.cpp` wasn't adjusted.
- Secondary problem was that we could end up with a currentframe=0 if we swap animations in `ChangeAnimationData`. But this only surfaced cause we passed the wrong parameter (see main problem). Fixed anyway. 😉 
- I also found the issue while working at #2457 😄
> Fix item swapping and AnimationInfo::ChangeAnimationData

- android-project/app/build.gradle
- android-project/app/src/main/AndroidManifest.xml
- android-project/app/src/main/java/org/diasurgical/devilutionx/DataActivity.java
- android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- android-project/app/src/main/res/layout/activity_data.xml
- android-project/app/src/main/res/values-bg/strings.xml
- android-project/app/src/main/res/values-da-rDK/strings.xml
- android-project/app/src/main/res/values-es/strings.xml
- android-project/app/src/main/res/values-fr/strings.xml
- android-project/app/src/main/res/values-hr/strings.xml
- android-project/app/src/main/res/values-it/strings.xml
- android-project/app/src/main/res/values-ko-rKR/strings.xml
- android-project/app/src/main/res/values-pt-rBR/strings.xml
- android-project/app/src/main/res/values-ru/strings.xml
- android-project/app/src/main/res/values-sv/strings.xml
- android-project/app/src/main/res/values-zh-rCN/strings.xml
- android-project/app/src/main/res/values/colors.xml
- android-project/app/src/main/res/values/strings.xml
- android-project/app/src/main/res/values/themes.xml
This covers 98.4% of devices. This is mostly done by simply reverting the changes to the libsdl java portion.
Previously 5.0 was required, which covers 94.1% of devices.
**Data managment:**
On start the game will check if the diabdat.mpq/spawn.mpq is present. If not it will redirect to the GameData screen:
Here the user is given (hopefully) clear instruction on how to install the needed game data, where to get the game data and where to get more help.
When clicking the "download shareware" button the data will be scheduled for download via the Android download manager, a progress will be shown in the notifications and the user is free to do other things while the shareware is downloaded (or cancel the download). Once the data is fully downloaded the game will automatically start (it will …
> Android 4.3 support and data managment

- Source/diablo.cpp
- Source/diablo.h
- Source/interfac.cpp
- Source/miniwin/miniwin.h
- Source/miniwin/misc_msg.cpp
- Source/movie.cpp
- Source/nthread.cpp
https://user-images.githubusercontent.com/25415264/127667604-53ef7f87-6d82-475a-a77a-e10b0fd9c37c.mp4
</details>
Previous the replay only calculated game ticks and never called the [only rendering part](https://github.com/diasurgical/devilutionX/compare/timedemo...obligaron:timedemo?expand=1#diff-84e63ba430a13546a287665b7640118b2f9d66fb9586056bfbab8215bab319c0L842-L847) (game tick is not due). Cause `nthread_has_500ms_passed` returned always true.
That skipped the additional [call](https://github.com/diasurgical/devilutionX/compare/timedemo...obligaron:timedemo?expand=1#diff-84e63ba430a13546a287665b7640118b2f9d66fb9586056bfbab8215bab319c0L843) to `ProcessInput`.
But that changes the replay.
Cause `ProcessInput` sends new _network_ message (for …
> Timedemo: Regard ProcessInput and gfProgressToNextGameTick

- Source/diablo.cpp
- Source/miniwin/miniwin.h
- Source/miniwin/misc_msg.cpp
The new demomode will attract many new customers.
This way we can enhance our profit around 370%!
Also everyone working on the project will get a pay rise of 200% !!!
In my case that means going from 0 straight to 0 * 200% = 0 ! Magnificent! 🤣 
This PR allows playing the demomode at different speeds then recording (first commit).
After that I separated rendering from recording and replay.
That means the demomode can render more frames and that the rendering frames (between two game ticks) are time-wise correct distributed.
> Timedemo: Support demomode with different speed and decouple fps from recording and replay

- Source/diablo.cpp
- Source/diablo.h
- Source/dx.cpp
- Source/menu.cpp
- Source/miniwin/miniwin.h
- Source/miniwin/misc_msg.cpp
- Source/movie.cpp
- Source/nthread.cpp
- Source/nthread.h
- Source/options.cpp
- Source/utils/display.cpp
This allows you to record a session and then replay it later as fast as the system CPU will allow
This can be used to benchmark the game, as well as do automatic testing of the game after changing parts of the code to verify that it behaves identically before and after the change.
Attached is a save game and recording that can be used for testing
[demo0.zip](https://github.com/diasurgical/devilutionX/files/5470234/demo0.zip)
`./devilutionx --demo 0 --timedemo -f`
> Implement timedemo

- Source/DiabloUI/art.cpp
PCX files always have an even number of bytes on each uncompressed source line, which means there is an unused byte of each compressed line if the width is odd.
References:
1. https://kaba.hilvi.org/pastel-1.5.0/pastel/gfx/image_file/pcx/pcx_file.htm
2. https://www.moon-soft.com/program/FORMAT/graphics/pcx.htm#decoding%20.pcx%20files
> 🐞 Fix reading PCX files with odd widths

- Source/control.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/player.cpp
- Source/player.h
This finally makes the to hit value shown in character panel useful - I had no idea how broken it was before.
It was basically always showing melee hit chance formula, which gains 1% per 2 dex while ranged gains 1% per 1 dex, which is a huge difference! I also made it include class bonuses and character level = it finally shows the real value that gets used in actual hit chance calculating
> Unify character formulas

- Source/control.cpp
- Source/engine/render/text_render.cpp
- Source/engine/render/text_render.hpp
- Source/qol/itemlabels.cpp
str::string and char * are converted to this implicitly.
> Use string_view in DrawString and friends

- Source/options.cpp
> Hardware Cursor: Default to ON only on SDL 2.0.12+

- Source/control.cpp
- Source/control.h
- Source/controls/plrctrls.cpp
- Source/cursor.cpp
- Source/diablo.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/player.cpp
- Source/qol/itemlabels.cpp
- Source/quests.cpp
- Source/scrollrt.cpp
According to screen resolution to center the sub-panels
[1440x900]
[800x600]
[640x480]
> Center the sub-panels (Quest, Character, Spell and Inventory)

- Source/.clang-tidy
- android-project/app/src/main/AndroidManifest.xml
- android-project/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
- android-project/app/src/main/java/org/libsdl/app/SDLActivity.java
- android-project/gradle/wrapper/gradle-wrapper.properties
We can now againn use the NoTitleBar theme since we are not using alert
messagse from the main activity
fixes #2503
> [android] Fix default app theme, and backport SDL Androd support updates from 2.0.16

- Source/diablo.cpp
Every mouse interaction in [`LeftMouseCmd`](https://github.com/diasurgical/devilutionX/blob/cfa3c8fa4e08e19a1976fd64cbc1472762e9d150/Source/diablo.cpp#L225) calls `NetSendCmdXYZ` expect walking.
In most cases this results in no problems and is not necessary cause `RepeatWalk` will send the message.
But if
- the player does some action (walking, attacking ,.. )
- and you click only once
- and release the button fast enough
then `RepeatWalk` will see [`CanChangeAction`](https://github.com/diasurgical/devilutionX/blob/cfa3c8fa4e08e19a1976fd64cbc1472762e9d150/Source/track.cpp#L49) = false and does nothing.
And cause you released the button fast enough, `RepeatWalk` will never be called with `CanChangeAction` = false.
This results in ignored input (user click).
This PR simply handles Walking …
> Fix walking command gets ignored

- Source/track.cpp
`RepeatMouseAction` didn't regard `stextflag` (Store Talk Flag) like [LeftMouseDown](https://github.com/diasurgical/devilutionX/blob/cfa3c8fa4e08e19a1976fd64cbc1472762e9d150/Source/diablo.cpp#L321) do.
Contributes to #2475
> Fix floating Dialogs (Walking while in store)

- Source/controls/keymapper.cpp
Discovered while working at #2490
> Fix Keymapper doesn't set any default keys if no diablo.ini is present (after installation)

- 3rdParty/libzt/CMakeLists.txt
Fixes an issue identified by @ropufu in #2472 where placing the DevilutionX source code on a case-insensitive file system and running a MinGW build will lead to a recursive include causing the build to fail.
> Update libzt to fix MinGW build on case-insensitive file systems

- Source/codec.cpp
- Source/sha.cpp
- Source/sha.h
Nerd sniped by #2516. If you do want to build the key at runtime the following initial state gets the right sequence:
```cpp
std::linear_congruential_engine<uint32_t, 214013, 2531011, 0> engine(3193970784);
for (auto &notch: key)
key = static_cast<byte>(engine() >> 16);
```
(This will need rebasing after #2516 is merged to use the correct type for the `key` array)
> Refactor Diablo-SHA to attempt to document behaviour through code

- Source/items.cpp
this is a pretty serious one, devilutionx made armor piercing have 2x larger stat range than the original
(example bashing 8-24, devx 16-48)
> fix armor piercing affix range

- CMake/ctr/n3ds_defs.cmake
- CMakeLists.txt
* Move romfs deployment from configure step to build step
* Add *.gmo files to the list of romfs files
* Add `MO_LANG_DIR` to the list of defines with values
* Set `MO_LANG_DIR` to `romfs:/` for 3DS build
> 3DS: Add translations

- .circleci/config.yml
Adds gettext to the list of packages installed via apt in the 3DS CI build script. This should allow the build to produce the gmo files for translations.
> Install gettext in 3DS CI

- CMake/vita_defs.cmake
- CMakeLists.txt
- Source/options.cpp
Sadly, vitasdk locale() always returns "C".
Luckily, there's not that many supported locales on vita, so we can just provide our own mapping.
> Auto-detect locale on PSVita.

- Source/missiles.cpp
fixes https://github.com/diasurgical/devilutionX/issues/2550
the negative index was written to `_miVar2` and used later on in missile update in `MI_Stone`
> fixes stone curse forever bug caused by negative monster index

- CMakeLists.txt
- Source/options.cpp
- Source/platform/ctr/locale.cpp
- Source/platform/ctr/locale.hpp
I can only select English, French, Spanish, and Portuguese on my console, but here's the full list of supported languages according to libctru:
* Japanese (ja)
* English (en)
* French (fr)
* German (de)
* Italian (it)
* Spanish (es)
* Simplified Chinese (zh_CN)
* Korean (ko_KR)
* Dutch (nl)
* Portuguese (pt_BR)
* Russian (ru)
* Traditional Chinese (zh_TW)
The language codes I listed aren't provided by the OS, but rather are the ones I selected based on the OS language setting. I did my best to select language codes based on the translations we have so far (e.g., `ko_KR` instead of just `ko`).
> 3DS: Detect system language and select the appropriate translation

- Source/spells.cpp
related to #1666 
cleanup manual value clamping in `spells.cpp` `GetManaAmount()`
https://github.com/diasurgical/devilutionX/blob/bcd60ea0b44a9a2588746c749f7a101b1bf6621a/Source/spells.cpp#L109L156
> cleanup manual value clamping: spells.cpp GetManaAmount()

- Source/inv.cpp
- Source/msg.cpp
- Source/player.h
This PR fixes a problem that caused auto-equipping staves from the groud or equipping them with shift+click in the inventory to not automatically ready the staff's charge spell when charges are available.
We are now making sure that the same logic that sets the readied spell applies on every equipment change situation by moving the processing logic directly into the command processing method for "equipment change", which is broadcast everytime an item is equipped or updated.
Resolves #2509
> Ensure shift+click and auto-equip properly update readied spell from staff

- Source/diablo.cpp
Fixes #2220 (at least on my pc) 🙂 
Notes:
- Sound was still playing, that was the cause of the exception (at least on my pc)
- `FreeGameMem` stops music and sound
- `FreeGameMem` is called if you exit a running game normally (in `RunGameLoop`).
- In menu only `music_stop` is called, but `FreeGameMem` includes `music_stop`.
- `FreeGameMem` can be called multiple times
- Alternative Solution would be to only stop music & sound.
> diablo_quit also frees game state (and with this sound objects)

- Source/msg.cpp
If it's executed before CheckInvSwap. then itype is -1, as we are at a point where we only know the other player unequipped something, we haven't received the data about the stuff that got equipped (CheckInvSwap)
> make ReadySpellFromEquipment have correct item data

- Source/control.cpp
- Source/player.cpp
- Source/spells.cpp
- Source/spells.h
fixes https://github.com/diasurgical/devilutionX/issues/1610
fixes casting level 0 spell says "not enough mana"-> changed return value of `CheckSpell` to enum to reflect the fail reason
Iam not sure about the Busy-Case - Could not reproduce it. If the cursor is not "Hand" (e.g. on using town portal or oil) its impossible to cast without first aborting the other spell/task.
> fixes casting level 0 spell says "not enough mana"

- Source/loadsave.cpp
- Source/objects.cpp
- Source/pack.h
- Source/player.cpp
- Source/player.h
- Source/qol/xpbar.cpp
Noticed this while reviewing #2572 but it got merged before I could finish the review 😅 
It may be clearer to write out the std::min call using two separate checks instead of an initialiser list. Happy to change that (or have it edited on my behalf :)).
Future cleanups are possible in this area. player._pExperience is pretty much always positive so could be an unsigned value. As far as I can tell players never lose experience (and exp is clamped to 0 at the lowest) so the addition can prevent overflows. This function is also only ever called with pnum = MyPlayerId so the first two checks are redundant.
> Clean up multiplayer XP cap clamping

- Source/misdat.cpp
From discussion in #2593:
> FYI, the last entry in the `MissileSpriteData` array gives me a couple run-time errors at startup in Visual Studio.
> `Run-Time Check Failure #3 - The variable 'ret' is being used without being initialized.`
> 
> The exception occurs at the return statement in the `maybeAutofill()` function. Presumably, the reason this occurs is that it's operating on a list of size 0 and so no value ever gets assigned to the contents of the array. As far as I can tell, it's not actually causing any issues at runtime apart from the debugger stopping on the thrown exception.
This change merely pacifies Visual Studio by explicitly assigning to the variable at declaration.
> Fix uninitialized variable exception raised in Visual Studio debugger

- Source/miniwin/misc_msg.cpp
- Use `+/-` to control playback speed
- Don't warp mouse while demo is playing
Besides that I recommend disabling hardware cursor for now when playing back demos to be able to see mouse moments.
> Demo playback improvmentts

- Source/DiabloUI/selconn.cpp
- Source/DiabloUI/selgame.cpp
- Source/DiabloUI/selhero.cpp
In this commit:
- Select Connection Menu
- Create or Join Game Menu
- Choose Class for new hero menu
-> Did not change Select Hero Menu, seems to be deliberately not wrapping around
> make menus wrap around. fixes #2605

- CMake/Findsodium.cmake
- docs/building.md
Our previous processing would throw away all but the last
entry in the found STATIC_LIBRARIES, which in newer versions
of libsodium, might be "pthread" -- hence not trying to link
against libsodium at all.
We now generate a temporary list, mangle it, then return that.
Bug: https://bugs.gentoo.org/791031
Fixes: https://github.com/diasurgical/devilutionX/issues/2615
Signed-off-by: Sam James <sam@gentoo.org>
> CMake: fix linking against libsodium statically

- Source/DiabloUI/selhero.cpp
- Source/pfile.cpp
- Source/pfile.h
Displays actual save number the new created character is going to have instead of 99
> fix displayed save number

- Source/controls/plrctrls.cpp
- Source/msg.cpp
- Source/quests.cpp
- Source/stores.cpp
Use range-based for-loop for Quests based on @AJenbo 's comment https://github.com/diasurgical/devilutionX/pull/2602#issuecomment-899109164
> Also it seams to be possible to use a range-loop in `ForceQuests()`, which would make it more robust :
> 
> ```c++
> bool ForceQuests()
> {
> ...
> 
> 	for (int i = 0; i < MAXQUESTS; i++) {
> 		if (i != Q_BETRAYER && currlevel == Quests[i]._qlevel && Quests[i]._qslvl != 0) {
> 			int ql = Quests[Quests[i]._qidx]._qslvl - 1;
> 			int qx = Quests[i].position.x;
> 			int qy = Quests[i].position.y;
> ...
> 		}
> 	}
> ...
> }
> ```
> 
> ->
> 
> ```c++
> bool ForceQuests()
> {
> ...
> 	for (auto &quest : Quests) {
> 		if (quest._qidx != Q_BETRAYER && currlevel == quest._qlevel && quest._qslvl != 0) {
> 			int ql = quest._qslvl - 1;
> 			int qx = …
```
> 2602 Use range-based for-loop for Quests

- Source/control.cpp
- Source/control.h
- Source/debug.cpp
- Source/debug.h
- Source/diablo.cpp
- Source/interfac.cpp
This PR introduces something like a debug `console`.
In debug mode you can write chat text and this will be analyzed by `CheckDebugTextCommand`.
For this change it was necessary to allow chat in singleplayer (only in debug).
Change is inspired by @qndel #2128. 🙂 
<details><summary>Example Usage Video</summary>
https://user-images.githubusercontent.com/25415264/129446094-1dba7f03-29e8-45f4-a1ce-2e2dfe195ff1.mp4
</details>
- Works only in debug and is not in production/release version.
- This PR lays the groundwork to easily add more debug commands.
- With this PR only some commands are realized. This list can be expanded in followup PRs.
- Many commands that are available per debug text commands have currently hard coded keys (for example `lvl up` command). The discussion if we want to …
> Add debug text commands

- CMake/Findsodium.cmake
Fixes a formatting inconsistency I inadvertently
introduced in a previous change. Apologies!
Fixes: 012f3aa90c9f76517f5d02867b7112c3eb48a59a
Signed-off-by: Sam James <sam@gentoo.org>
> Findsodium.cmake: Fix tabs->spaces

- Source/DiabloUI/art.cpp
- Source/DiabloUI/credits.cpp
- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/text_draw.cpp
- Source/DiabloUI/ttf_render_wrapped.cpp
- Source/DiabloUI/ttf_render_wrapped.h
- Source/appfat.h
- Source/control.cpp
- Source/dx.cpp
- Source/engine/surface.hpp
- Source/hwcursor.cpp
- Source/utils/display.cpp
- Source/utils/sdl_wrap.h
- Source/utils/ttf_wrap.h
This patch introduces wrappers for a few SDL functions. These wrappers perform error checking and return the appropriate type of unique_ptr.
The wrappers introduced are not employed exhaustively yet. It also includes a refactoring of RenderUTF8_Solid_Wrapped.
The rationale is two-fold:
- Automatic error checking: there are multiple instances in the codebase where the function inside one of these wrappers is called, but no error checking is performed. If the function returns NULL, something bad will happen at a later time.
- The programmer no longer has to figure out what kind of unique_ptr to wrap the result in.
Case in point: RenderUTF8_Solid_Wrapped would return an error when the string was empty, or when some SDL-related error occurred. Its caller, DrawTTF, calls it twice, passing the …
> SDL stuff: automatic memory management and error checking, part 1 of N

- Source/debug.cpp
Before you could type "helpXgod" or "give xp12" (that would raise level two times, cause 1 is ignored).
> Debug Commands: Ensure that between command and parameters only a space is allowed

- Source/gendung.cpp
- Source/gendung.h
- Source/loadsave.cpp
- Source/missiles.cpp
- Source/missiles.h
- Source/monster.cpp
- Source/portal.cpp
This is prep that lets us change most missile functions to use MissileStruct as the input rather then an index in a follow up PR.
@bcko once this is merged you can try and change all the missile add functions if you like :)
> Replace dMissiles with BFLAG_MISSILE

- Source/quests.cpp
- Source/quests.h
- completed quests are displayed
- completely reworked quest log item drawing
- spacing and positioning depends on list size
- fixed missing quest log caption
- selection follows cursor
as recently discussed here https://github.com/diasurgical/devilutionX/pull/2589#discussion_r688705609 
showing completed quests could be nice.
I implemented this as proposal. see the screenshots at the end.
the closed quests are not selectable. and also are skipped while selecting.
Two question that may be have to discussed:
- do we need an ini-option for showing solved quests?
- should we remove the "close quest log" line?
This would bring some additional space and this panel is the only one in the game that does have a close btn
This PRs implementation is based (in termes of implementation style) on the …
> Improved Questlog

- Source/items.cpp
- Source/items.h
The item get record array tracks items being recently looted in an
effort to prevent the same item from being looted more than once.
Prior to this commit, the item get record array (and corresponding
item get record array length) variables were not cleared when
creating a new game. Therefore, the item get record array of a
previous game could remain in between games and prevent an item
from being looted (if it was looted in a previous), even if it was
never looted in the current game. In practice this almost never
shows up, since each item get record is valid for a total of 6
seconds before being cleared. So, you would either have to save
a game, quickly loot an item, when load the game and try to loot
the same item before 6 seconds pass. OR, you could use the demo
replay functionality to …
> items: add BUGFIX, reset item get records when resetting items

- CMake/switch/asio_defs.cmake
- CMakeLists.txt
- Source/platform/switch/asio/pause.c
Apparently, linking in the rdimon library broke the `truncate()` function. Hopefully, ASIO doesn't need the `pause()` function.
This resolves #2702
> Nintendo Switch: Remove link to rdimon library to fix file truncation

- Source/missiles.cpp
- Source/objects.cpp
Phasing could end up attempting to teleport to hunreds of random
location and still fail to find a valid target and send the player in to
a wall or outside the map.
This is fixed by first finding all valid locations within range and then
picking one of them at random.
Valid targets is a 13x13 area around the player minus the inner 7x7
In total there can be no more then 120 valid tiles and on average there
should be 75 avalible.
----------
Previously an improper check was being done to see if the player was
located on the 3 teleporting pads in the level. Even if fixng this the
spell would not work correctly if the layer was standing on the pads
when casting the spell.
Simply use TARGET_BOTH to indicate that it should not be random and send
the player to the given destination
> Fix bugs in AddRndTeleport

- Source/control.cpp
- Source/missiles.cpp
- Source/player.cpp
- Source/player.h
1. Make hit chance displayed in character sheet in vanilla include armor pierce - this gives us an option to somehow check the real value of armor piercing affixes before we get a proper description for them
2. Unify hellfire's melee and ranged pierce.
Hellfire values are pretty low and indicate tiers of % armor that should be ignored
1 = 25%
2 = 50%
3 = 75% armor ignored.
Ofc hellfire didn't do such a thing for ranged, in hellfire ranged pierce even had a wrong sign, so it actually decreased hit chance by these 1/2/3%.
This makes ranged pierce follow the same rules as melee's for hellfire - ofc barbarian's passive 12.5% pierce stays only melee.
> unify ranged and melee pierce

- Source/engine/demomode.cpp
This way you always see the cursor of the player and doesn't have to adjust your `diablo.ini` for that.
> Disable hardware cursor for demo playback

- Source/debug.cpp
- Source/debug.h
- Source/diablo.cpp
Content
- restart can now (optional) set a new seed for a level. This is a replacement for `-r` command line argument.
- new command `seedinfo` that is replacement for `r` and `R` keys
- executed debug commands gets logged to the console (if you want to expect the printed information (for example seed) longer then the info is displayed on screen)
> Level seed related debug commands

- Source/debug.cpp
To avoid undefined behavior, see {comment](https://github.com/diasurgical/devilutionX/pull/2744#discussion_r697986644).
Thanks @ephphatha 🙂
> DebugCmdResetLevel: Use stoul for parameter seed parsing

- Source/DiabloUI/diabloui.cpp
- Source/diablo.cpp
- Source/effects.h
- Source/effects_stubs.cpp
- Source/gamemenu.cpp
- Source/items.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
- Source/movie.cpp
- Source/mpqapi.h
- Source/sound.cpp
- Source/sound.h
- Source/sound_stubs.cpp
- Source/storm/storm_svid.cpp
There where 3 calls to `GenerateRnd()` which would not get triggered if the game was compiled without sound support, which resulted in the game-play diverging from a full build.
> Fix inaccurate gameplay with NOSOUND

- Source/debug.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2764
Setting only one of these values ends up with a black screen because of 
```cpp
for (auto &player : Players) {
if (player.plractive && currlevel == player.plrlevel) {
InitPlayerGFX(player);
if (lvldir != ENTRY_LOAD)
InitPlayer(player, firstflag);
}
}
```
in LoadGameLevel
> fix currlevel in map command

- Source/monster.cpp
Fixes a bug where quest unique monsters were getting the difficulty bonus applied twice to mLevel.
> fix quest unique monster level

- Source/debug.cpp
- Source/interfac.cpp
Could fix #2765 😉 
Background:
We start the level transition with `StartNewLvl`.
But `StartNewLvl` only `PostMessage` a level transition to the message queue.
That means that the level transition happens a lot later.
But we change the `currlevel` direclty after `StartNewLvl`.
This is a problem for the save game logic.
When you transit from level to another following code is executed:
```
IncProgress();
if (!gbIsMultiplayer) {
SaveLevel();
} else {
DeltaSaveLevel();
}
IncProgress();
FreeGameMem();
currlevel--;
leveltype = gnLevelTypeTbl[currlevel];
assert(myPlayer.plrlevel == currlevel);
IncProgress();
LoadGameLevel(false, ENTRY_PREV);
IncProgress();
```
First is the current level saved and `SaveLevel` uses `currlevel`.
That means we set store items, monster etc. in the wrong level. …
> Debug commands: Fix level transitions

- Source/missiles.cpp
Fixes the off-by-one error in the missile blocking logic that was causing Blood Star missiles to disappear with a `NULL Cel Buffer` error after being blocked. For more info, see https://github.com/diasurgical/devilutionX/issues/2770#issuecomment-910369255. Tested using the save from #1531.
This resolves #2770
> Fix NULL Cel Buffer error when blocking missiles

- Source/dead.cpp
- Source/dead.h
- Source/diablo.cpp
- Source/gendung.cpp
- Source/gendung.h
- Source/loadsave.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/msg.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/scrollrt.cpp
- test/dead_test.cpp
This PR renames most members that refer to dead bodies by 'Dead' to 'Corpse'. This includes the methods, variables and associated structs.
> 🚚 Rename 'Dead' concept to 'Corpse' everywhere

- Source/controls/plrctrls.cpp
- Source/engine/displacement.hpp
- Source/engine/point.hpp
- Source/monster.cpp
- Source/player.cpp
- Source/scrollrt.cpp
This PR changes how we usually convert from a `Direction` instance to a `Displacement` by introducing an explicit conversion constructor that is used in place of the old `fromDirection` static method. This leads to simpler and more standardized code since we currently use this approach for other types like `Size` as well.
The old method is kept to simplify the construction logic (leveraging the automatic copy constructor) but is made `private` to encourage the use of the constructor instead.
> ♻️ Standardize 'Direction' to 'Displacement' conversions

- Source/quests.cpp
Avoids crashes if memory layout changes (e.g. #2751 :D)
> Prevent OOB access when initialising quest pools

- Source/items.cpp
This is the most important PR ever - this is the reason why loot was the same on all difficulties, hell, it was even worse than that, despite unique monsters having a custom data table with lvls and level getting increased by 4 for item generating, it was always taking the level of base monster straight from the data table - means no bonus from difficulty, no bonus from being unique xD
I did the math for lazarus (30 lvl) on hell (+30 lvl)
that alone brings him to 60, he has 0 in unique data level, so that's a +5 bonus and there's a flat +4 bonus hardcoded on top of that so final level would be 69.
According to
```cpp
enum icreateinfo_flag {
// clang-format off
CF_LEVEL        = (1 << 6) - 1,
```
Max item level can be 63 (not sure if before or after that hardcoded +4 bonus), so we'd need …
> fix loot - use proper monster level for generating items

- android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java
This just sets up a listener to force the drawing surface to fit in the window's "visible display frame". This causes the SDL window to resize to fit in that available space. The result is that the game window will shrink or grow to fit in whatever space is made available to it.
> [Android] Fix input not being in view for 7.1+

- Source/monster.cpp
This fixes a bug where 4 golems (1 for each player) were added twice when a map contained set pieces (halls of the blind, anvil of fury etc.) - since it doesn't happen for butcher's room or poisoned water supply entrance, I'm assuming this has to be a set piece with enemies. (Means there were 20 golems in monsters array on dlvl 16 ... yay)
```cpp
void InitMonsters()
{
if (!setlevel) {
for (int i = 0; i < MAX_PLRS; i++)
AddMonster(GolemHoldingCell, DIR_S, 0, false);
}
```
since it wasn't a "setlevel", this part would trigger.
```cpp
void SetMapMonsters(const uint16_t *dunData, Point startPosition)
{
AddMonsterType(MT_GOLEM, PLACE_SPECIAL);
for (int i = 0; i < MAX_PLRS; i++)
AddMonster(GolemHoldingCell, DIR_S, 0, false);
```
but this one too = you end up with 2x golems and hitting new fixed …
> fix golems on maps with set pieces

- Source/loadsave.cpp
- Source/missiles.cpp
- Source/missiles.h
Fixes #2826
Fixes #1531
Fixes #2837
Notes:
- First Commit is only refactoring as a base for the following commits
- Check if the missile skipped tiles and do also collision checking for these skipped tiles
- Prevent perform collision detection for a target more then once at a tile (that means you can also avoid a hit by missed hit chance and not only block)
- Tested with missiles 10x faster and 10x slower then normal
> Improve collision detection for moving missiles

- Source/inv.cpp
- test/inv_test.cpp
This PR changes the variable we rely on to match the scroll or staff spell when removing a scroll or a staff charge that was just used via right clicking. 
Instead of picking the spell from the "readied spell" value (the spell currently selected), we pick the spell being cast by the player. This ensures the player cannot change the spell into something else right after casting and either causing wrong scrolls to be removed or no scrolls/charges removed at all.
Fixes #792
> Ensure scrolls and charges are cleared using correct spell after use

- Source/debug.cpp
- Source/debug.h
- Source/diablo.cpp
Adds a `DebugToggle` debug variable and connects it to currently unused X hotkey - this is to make debugging stuff that needs turning on/off easier, up till now I've always had to cook some code for it myself, then remove it knowing I'd need it again soon. NO MORE 🤪
> debug X toggle

- Source/msg.cpp
- Source/msg.h
- Source/player.cpp
This PR changes all spell commands where the spell type was previously being inferred to explicitly pass this value at creation time.
This completely eliminates any possibility of manipulating the spell type between cast and execution and causing undefined behavior (like not consuming scrolls, staff changes, using incorrect mana values, etc).
Fixes #2844
> 🐛 Prevent frame-perfect manipulation of spell being cast

- Source/engine/render/text_render.cpp
See https://github.com/diasurgical/devilutionX/pull/2791#discussion_r705485943
With #2848 having been merged, this fix has become relevant again. I wouldn't worry so much about it except there's a good chance translators will run into issues when trying different words and abbreviations to get things to fit. So here's the fix.
> Fix OOB error in DrawString

- Source/missiles.cpp
Fixes #2864
Was caused by a copy&past error in 7f6e171b4b51e832e3fbbfb1bee46508d24ed212.
Instead of using target x/y the crawling loop variables were used.
> Fix existing missiles check for Guardian/Townportal/Rune

- Source/engine/animationinfo.cpp
- Source/player.cpp
Fixes #1160
<details><summary>Loaded walk in PR</summary>
https://user-images.githubusercontent.com/25415264/133609932-e32de60b-79e4-4654-8ae2-4df4c89c96a1.mp4
</details>
<details><summary>Loaded walk in Master</summary>
https://user-images.githubusercontent.com/25415264/133609956-d9174001-0f46-4bec-b97b-a6929035c6b8.mp4
</details>
<details><summary>Loaded walk in devilutionX 1.21</summary>
https://user-images.githubusercontent.com/25415264/133609978-5fd7149e-a5b3-4f1b-aabe-b269ddf69177.mp4
</details>
Notes:
- Fixed `GetAnimationProgress` return the wrong fraction if ADL wasn't active
- Correctly initialize `ScrollInfo` after load
- In devilutionX 1.21 the walk was incorrect, cause `ScrollStruct.offset` wasn't updated. In master we use `GetOffsetForWalking`.
> Fix camera position when loading a game with currently walking player

- Source/controls/touch/gamepad.h
This function was removed during the cleanup for the precompiler checks, but I left the declaration in the struct.
> Remove unused function declaration from VirtualGamepad

- Source/diablo.cpp
Fixes stuck chargers when you enter the level. In multiplayer it triggers only when you are the only person on the level.
Resolves https://github.com/diasurgical/devilutionX/issues/2463
> fix stuck chargers

- Source/monster.cpp
If you used "spawn" command and spawned a monster type that wasn't originally on the level, saving with this monster wouldn't let you load after restarting the game basically bricking your save. With this "fix" all debug monsters change into zombies anyway, but it's just to allow loading the save at all.
> fix saves bricked by spawn command

- Source/dx.cpp
in
```cpp
bool SpawnWindow(const char *lpWindowName)
```
there's
```cpp
if (sgOptions.Graphics.bUpscale) {
#ifndef USE_SDL1
Uint32 rendererFlags = SDL_RENDERER_ACCELERATED;
if (sgOptions.Graphics.bVSync) {
rendererFlags |= SDL_RENDERER_PRESENTVSYNC;
}
renderer = SDL_CreateRenderer(ghMainWnd, -1, rendererFlags);
```
so renderer is only created if not SDL1 and bUpscale is true, this fix takes that into account when trying to destroy a renderer.
> fix destroying renderer

- Source/loadsave.cpp
- Source/monster.cpp
- Source/player.cpp
- Source/player.h
- Source/scrollrt.cpp
In Master and Vanilla missiles can't hit players/monsters that walk horizontal.
This is cause while horizontal walking the player/monster _disappears_ from `dPlayers`/`dMonster`.
Both arrays contains what player/monster is located at a specific tile.
If a player/monster moves he is between two tiles and both are marked as occupied.
But only one location result in a missile hit. In the game engine this is represented as a positive Id (can be hit) and a negative number (only needed to mark the tile as occupied, so that no other player/monster can walk on this tile).
When the player/monster walks horizontal both tiles get a negative id, so you the player/monster can't be hit by a missile.
This PR changes this that also in horizontal walk one tile is used with a positive id (can be hit).
This …
> Fix missiles don't hit horizontal walking players/monsters

- Source/debug.cpp
- Source/debug.h
- Source/diablo.cpp
- Source/diablo.h
- Source/monster.cpp
- Source/multi.cpp
- Source/player.cpp
- docs/debug.md
- Remove `-m` debug command line parameter. Was used for spawning monsters but now we have `spawn` debug command. 😉 
- Remove `-^` debug command line parameter. Was only used for scrolling with shift. Now on per default in debug (hope that's okay).
- Rename `debug_mode_key_i` to `DebugDisableNetworkTimeout`.
- Introduce `iteminfo` debug command to show item infos. Replaces `ItemInfo` keybinding and now also works for inventory and held items.
- Introduce `questinfo` debug command that replaces `PrintDebugQuest` keybinding and now allows to specify what quest to show instead of needing to iterate all previous quests.
- Remove `-t` debug hotkey. Was used for showing tile related info but now we have `tiledata` debug command. 😉 
- Introduce `playerinfo` debug command to show player infos. …
> Add new debug commands, remove old hotkeys and update debug.md

- Source/player.cpp
#2873 broke the possibility to run the binary when RUN_TESTS is defined, cause no player animation was loaded.
> Fix SetPlayerGPtrs with RUN_TESTS definied

- Source/quests.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2894
Index was -1 when pressing enter on a list that contained only done quests
> fix quest panel

- Source/monster.h
With NOSOUND defined `std::functional` is not included to `monster.h`.
Without NOSOUND it gets included with `Aulib/Stream.h`.
> Fix compiling with NOSOUND defined

- Source/items.cpp
- Source/utils/sdl_geometry.h
1. Use `BlitFrom` instead of a custom loop for drawing the divider line.
2. De-duplicate position calculation.
> Simplify unique info window drawing

- Translations/it.po
As in the title.
I also post some notes here that may be useful, but I think you already know.
Some buttons compress longer words. An example:
The word "CHAR", which stands for character, is immediately translated to "Personaggio". But I don't like the idea of ​​using the abbreviation PG to accomodate the button aspect. I had thought of the Italian equivalent of Profile ("Profilo"). Before disrupting the translation, I'm waiting for your feedback. For the rest, as always, a splendid job. Thanks for supporting accented letters :tada:
> 🌐 Update Italian localization

- docs/building.md
This is the right way to fix the "/usr/bin/ld: cannot find -lstdc++" error on Fedora.
Tested on Fedora 33
This PR can be closed: #1040
Closes #896
> Fix Fedora build command

- Source/DiabloUI/art.h
- Source/controls/touch/renderers.cpp
- Source/controls/touch/renderers.h
- Source/diablo.cpp
- Source/dx.cpp
- Source/scrollrt.cpp
This PR renders the gamepad using the SDL rendering API instead of `SDL_BlitScaled()` to the output surface.
This should solve the following rendering issues...
* Dissatisfactory scaling algorithms in `SDL_BlitScaled()`
* Downscaling to the the game's resolution before upscaling to the display resolution
---
Here is a particularly extreme comparison using the following settings on my 1920x1200 display.
```ini
[Graphics]
Width=640
Height=480
Fullscreen=1
Upscale=1
Fit to Screen=1
Scaling Quality=2
Integer Scaling=0
```
**SDL_BlitScaled:**
**HW render:**
> Hardware rendering for the virtual gamepad

- Translations/pt_BR.po
This PR updates the pt_BR translation
The words on the char panel were all turned into lower case to keep it consistent (some words simply don't fit otherwise).
There is one word that doesn't fit which is the translation for Armor Class (_"Armadura"_).
I tried to improve some weapons and monsters' names, I hope someone better skilled could improve it in the future.
> Update portuguese translation

- Source/debug.cpp
- Source/diablo.cpp
Previously the game would crash when pressing `v` when some translations where loaded because it would overflow the 80 char limit. This is additionally solved by not having the version string in there twice :D
> Fix buffer overflow when sending game messages as chat

- CMakeLists.txt
- appveyor.yml
- docs/building.md
- vcpkg.json
After installing and integrating vcpkg, CMake will use vcpkg.json to automatically determine dependencies for the project and place them in `${CMAKE_CURRENT_BINARY_DIR}/vcpkg_installed` during the configure step.
This behavior requires the `VCPKG_MANIFEST_MODE` CMake variable to be set, which will happen automatically for new builds during the configure step, based on the presence of the vcpkg.json file. In other words, users who already have build directories set up would have to delete their CMakeCache.txt files to make use of this.
By default, packages appear to be cached in `%localappdata%\vcpkg\archives` so packages don't need to be redownloaded or built once installed. This means that Debug and Release builds can share the same packages, and it's safe to delete build directories …
> Add vcpkg.json to the project

- Source/controls/game_controls.cpp
- Source/controls/touch/event_handlers.cpp
- Source/controls/touch/event_handlers.h
- Source/controls/touch/gamepad.cpp
- Source/controls/touch/gamepad.h
- Source/controls/touch/renderers.cpp
- Source/controls/touch/renderers.h
Adds a couple more buttons to match the functionality of L1/R1 on a physical controller.
Thanks to the hardware rendering, it's easier to scale the potion graphics to fit in the gamepad buttons without it looking like trash. Here are some sample screenshots.
> [Virtual Gamepad] Add buttons for using potions from belt

- Source/controls/touch/renderers.cpp
- Source/controls/touch/renderers.h
It seems MSVC was letting me be a bit sloppy.
* Rendering logic for the virtual gamepad was running even when not in a game
* `PotionButtonRenderer::GetPotionType()` had no return value when there was no relevant potion or scroll in the belt
> [Virtual Gamepad] Fix empty potion button rendering

- Source/player.cpp
Fixes #2772
Notes:
- `gbFriendlyMode` toggles friendly mode (the UI button)
- `sgGameInitInfo.bFriendlyFire` added the possibility to also disable missile friendly fire when `gbFriendlyMode` is active.
- This was introduced with #1104 but the check was also (incorrectly) applied to melee attacks. For melee we don't need to check `sgGameInitInfo.bFriendlyFire` cause it's not a missile.
> Fix melee friendly fire when sgOptions.Gameplay.bFriendlyFire is set

- Source/controls/plrctrls.cpp
- Source/cursor.cpp
- Source/diablo.cpp
- Source/player.cpp
- Source/player.h
- Source/track.cpp
Fixes #2695
Fixes #2859
Notes:
- When the mouse is held cursor position only get updated if we previous didn't select an monster/object/item/... This was implemented to track a target. But this target tracking should activate if shift is pressed. So adjust the logic to only track if we want to.
- Shift+Spell needed more adjustment cause `CheckPlrSpell` sets `LastMouseButtonAction`. `CheckPlrSpell` is also used in initial mouse click (`RightMouseDown`) and for repeating mouse actions (`RepeatMouseAction`). Cause of this we must ensure that it regards shift/doesn't override `LastMouseButtonAction` when we are in `RepeatMouseAction`.
- The entire logic of this tracking target should only be performed if we have we want to track any target (is not `MouseActionType::None`). This fixes the …
> Fix: Holding mouse when shift is held shouldn't lock to a target & Trigger Text is incorrectly shown

- Source/cursor.cpp
Fixes #2962
Also noticed that `BFLAG_VISIBLE` was used for checking a monster is visible.
But in [cursor](https://github.com/diasurgical/devilutionX/blob/2c4c277c87801ccbdeabcddafcd484ee7ac810f9/Source/cursor.cpp#L497) and [drawing](https://github.com/diasurgical/devilutionX/blob/2c4c277c87801ccbdeabcddafcd484ee7ac810f9/Source/scrollrt.cpp#L753) we use `BFLAG_LIT`.
> Fix: Don't track hidden monseters

- Source/dvlnet/zerotier_native.cpp
Removes the call to `zts_stop()` based on this excerpt from the libzt project README.
> At the end of your program or when no more network activity is anticipated, the user application can shut down the service with `zts_stop()`. However, it is safe to leave the service running in the background indefinitely as it doesn't consume much memory or CPU while at idle. `zts_stop()` is a non-blocking call and will itself issue a series of events indicating that various aspects of the ZeroTier service have successfully shut down.
This resolves #2197
> Prevent ZeroTier race condition during application shutdown

- Source/msg.cpp
- Source/player.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/2991
OnPlayerJoinLevel was setting light of other players to -1 too late, StartStand happened earlier and it updated light, which was 0 = light stealing.
> fix light stealing in multi

- Source/gendung.cpp
- Source/gendung.h
- Source/missiles.cpp
- Source/monster.cpp
- Source/monster.h
- Source/msg.cpp
- Source/msg.h
- Source/sync.cpp
- Source/sync.h
Checks that the CMD_SYNCDATA message won't cause OOB or CTD. CMD_SYNCDATA looks to be one of the more complicated messages and some of the changes here also lay the ground work for validating more messages so that we can more safely allow password-less games.
There are also some cleanups included since it helped me better understand the code and avoid the need for null pointer checks.
> Validate CMD_SYNCDATA messages

- CMakeLists.txt
- Source/DiabloUI/selconn.cpp
- Source/DiabloUI/selgame.cpp
- Source/DiabloUI/selok.cpp
- Source/DiabloUI/selyesno.cpp
- Source/DiabloUI/ui_item.h
- Source/control.cpp
- Source/engine/displacement.hpp
- Source/engine/render/text_render.cpp
- Source/engine/render/text_render.hpp
- Source/error.cpp
- Source/help.cpp
- Source/minitext.cpp
- Source/panels/charpanel.cpp
- Source/plrmsg.cpp
- Source/utils/utf8.h
Useful for Chinese and Japanese, which do not have spaces between words, nor whitespace after punctuation.
> WordWrapString: Wrap on punctuation

- Source/storm/storm_net.cpp
This explicitly frees the currently active network implementation during application shutdown.
Leaving ZeroTier connections open during application shutdown invites errors related to locking mutexes that have already been freed. Selecting `Quit Game` from the in-game menu in a ZeroTier game with multiple players was enough to reproduce the error on my system.
> Free dvlnet resources when game is shutting down

- Source/automap.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/292
Also  changed drawing order in southeast arrow
So shadow overwrites less
> center automap arrow

- Source/msg.cpp
- Source/msg.h
- Source/multi.cpp
- Source/multi.h
- Source/tmsg.cpp
- Source/tmsg.h
- Mark network messages as `const`
- Validate coordinates for `OnWalk` and `OnGotoGetItem` to avoid OOB
- Use C++ in `OnAddStrength`, `OnAddMagic`, `OnAddDexterity`, and `OnAddVitality`
> Validate more network messages

- docs/building.md
I also have in my personal notes the following:
```
vcpkg install fmt:x64-windows sdl2:x64-windows sdl2-mixer:x64-windows sdl2-ttf:x64-windows libsodium:x64-windows gtest:x64-windows
vcpkg integrate install
```
But I'm not sure if these commands are still needed, so I didn't add them in the markdown.
> url to the vcpkg quickstart guide for windows has (slightly) changed

- CMake/Findsodium.cmake
Code was copied right from stackoverflow as @StephenCWills suggested: https://stackoverflow.com/a/39258832
I tried it with CLion and Visual Studio 2019 and was able to compile without any problems.
Without the change compiling with CLion was not possible.
Fixes #2558
> change way to detect architecture/platform path for libsodium.

- Source/msg.cpp
- Source/player.cpp
`wParam3` is the spell level, not the direction (like in `CMD_SPELLXYD`).
What great network messages. 😛
> Fix OnSpellTile check

- Source/inv.cpp
Ensure people who shift-click items they don't have the stats for don't end up empty-handed.
> Disable shift-clicking of items you don't have stats to wear

- Source/msg.cpp
- Source/objects.cpp
- Source/objects.h
This one does include a couple of cleanups for OperateMushroomPatch and OperateInnSignChest. I couldn't see any reason to play the sound before changing the animation frame (the timing didn't seem that critical) so I rolled that into the conditional a few lines later.
> Update (some) quest object activation functions to use references

- Source/controls/plrctrls.cpp
This restarts the player's idle animation if they attempt to move while the stand button is pressed.
> [Virtual Gamepad] Turn player when stand button is pressed

- Source/control.cpp
- Source/control.h
- Source/controls/plrctrls.cpp
- Source/controls/plrctrls.h
- Source/miniwin/misc_msg.cpp
This fixes gamepad navigation after opening the speedbook with anything other than `GameActionType_TOGGLE_QUICK_SPELL_MENU`.
---
The gamepad code that toggles the speedbook called a function named `StoreSpellCoords()` in order to compute the location of each spell in the speedbook. However, if the speedbook was opened via any other method, such as the `S` key or by clicking on the spell icon in the main panel, the speedbook coordinates would not be updated and gamepad navigation would not work properly. This was most obvious when using touch controls which doesn't make use of `GameActionType_TOGGLE_QUICK_SPELL_MENU` to open the speedbook.
This PR rewrites the `HotSpellMove()` function to use `GetSpellListItems()` instead, which is the function that provides information for rendering the …
> Fix speedbook navigation on gamepad

- Source/dvlnet/packet.h
../Source/dvlnet/packet.h: In member function ‘std::unique_ptr<devilution::net::packet> devilution::net::packet_factory::make_packet(devilution::net::buffer_t)’:
../Source/dvlnet/packet.h:357:9: warning: unused variable ‘size’ [-Wunused-variable]
357 |  size_t size = ret->Data().size();
|         ^~~~
> packet.h: Fix `-Wunused-variable`

- vcpkg.json
Thanks to @glebm's tip (#3387), I surmised that Windows does not need both libpng and sdl2-image.
> Remove libpng from vcpkg dependencies

- Source/utils/png.h
I built the Virtual Gamepad on Linux, and I saw this in the output from ASAN.
> Close SDL_RWops in LoadPNG()

- android-project/app/src/main/AndroidManifest.xml
- android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java
Follow up to #3287
As of November it is no longer possible to perform this migration from a new release.
We could fully remove `migrateSaveGames()`, `migrateFile()`, and `copyFile()` if we decide that it is not relevant to support save games from the troubled Android port of yesteryear.
> :fire: Remove app migration code

- Source/DiabloUI/art_draw.cpp
- Source/DiabloUI/art_draw.h
- Source/engine/render/text_render.cpp
The bounds checks were performed against the global screen dimensions instead of the output buffer dimensions.
Also includes some minor cleanup of DrawArt.
Fixes #3388
> DrawArt: Fix bounds check

- Source/DiabloUI/art_draw.cpp
This fixes the glitch when a line leaves the viewport in quest text.
Refs #3388
> ArtDraw: Bounds-check top and left

- Source/engine.h
- Source/missiles.cpp
- Source/msg.cpp
- Source/objects.cpp
- Source/objects.h
Comments get a bit repetitive, I'm happy to cut them down to a single line.
Also made the IsAnyOf/IsNoneOf helpers constexpr here since they're simple functions, allows making all the helpers constexpr which should minimise the impact of introducing a wrapper.
> Add helpers for checking object type

- Source/objects.cpp
This change removes the need for `SetRndSeed()` by simply calculating the from/to stats for Fountain of Tears from the seed value itself.
I'm submitting this for discussion as a potentially less controversial alternative to #3296.
> I noticed when testing #3219 that spamming the Blood Fountain caused all the randomness in monster attack frequency, hit rate, and block chance to go away. It seems that Fountain of Tears captures a seed to provide predictable behavior when used regardless of the current state of the engine's RNG, but the call to `SetRndSeed()` doesn't discriminate based on the type of fountain.
> Don't set RNG seed when operating fountains

- Source/automap.cpp
- Source/controls/plrctrls.cpp
- Source/cursor.cpp
- Source/debug.cpp
- Source/diablo.cpp
- Source/gendung.cpp
- Source/gendung.h
- Source/items.cpp
- Source/lighting.cpp
- Source/loadsave.cpp
- Source/missiles.cpp
- Source/monster.cpp
- Source/msg.cpp
- Source/multi.cpp
- Source/objects.cpp
- Source/player.cpp
- Source/portal.cpp
- Source/scrollrt.cpp
- Source/themes.cpp
- Source/trigs.cpp
- Source/utils/enum_traits.h
This was an unnamed enum previously with plenty of chances for confusion given it's intended for use with the `dFlags` array but not the `dflags` array.
~~Uses #3124, feel free to ignore the first commit. Can drop the last commit too.~~ Stripped out the irrelevant commits now.
I've pulled InDungeonBounds into the header and made it constexpr as it's a very simple check that gets reused a lot in the if conditions that were then touched by this refactoring. I'm hoping all compilers we target will be clever enough to optimise this check out given it's usually performed at the start of the calling function anyway.
> Use scoped enums for DungeonFlags/BFLAG

- Source/utils/sdl_compat.h
With 1.3.0, we switched from CEL to PCX for fonts.
This resulted in significant performance drops when rendering lots of text, because SDL RLE implementation is not as optimized as our CEL implementation.
Disabling RLE significantly reduces the performance drop.
The font surfaces are fairly small, so we do not lose out much on RAM.
The menu surfaces are also PCX, so the RAM usage there is greater, but the game itself uses a lot more RAM than the menu anyway.
Thanks to @AJenbo for discovering the RLE flag as the root cause of font rendering performance issues!
> Disable RLE compression for PCX surfaces

- Source/inv.cpp
- Source/items.cpp
- Source/missiles.cpp
- Source/path.cpp
- Source/path.h
- Source/player.cpp
- test/path_test.cpp
With the way CrawlTable and CrawlNum are defined callers needed to do some awkward iteration and manually construct displacements. This also meant that the logic performed when a valid target was found was mixed in with the actual search code since often there were two levels of loop to break out of.
I've added a function to abstract this table, using an interface similar to the pathfinding logic. I've also placed it in path.h/cpp as it seemed most appropriate given the existing use.
There are other functions which search for multiple tiles, this could be supported using a custom iterator but I wanted to focus on the simple case for now.
> Introduce a replacement/abstraction for CrawlTable for single tile searches

- Source/engine.cpp
- Source/palette.cpp
- Source/palette.h
`DrawHalfTransparentBlendedRectTo` takes up a significant chunk of time when rendering store and quest dialogs.
Optimizes the function to read 2 blendings at a time and write 4 pixels at a time.
It is a bit of work to measure the exact performance impact of this correctly but it does seem consistently faster on my PC in both debug and release builds.
Example
before
after
Refs #3405
> Optimize `DrawHalfTransparentBlendedRectTo`

- Source/engine/render/text_render.cpp
> Fix crash in `WordWrapString`

- Source/engine/render/text_render.cpp
This fixes cases such as `github.com`.
As we now require a space after Latin punctuation, we can remove
the list of Latin punctuation symbols and break on the space itself.
We still disallow linebreaks between consecutive fullwidth punctuation
symbols.
> WordWrap: Require whitespace to break after Latin punctuation

- Source/missiles.cpp
- Source/msg.cpp
- Source/objects.cpp
- Source/objects.h
- Source/player.cpp
Theoretically we can set the ID as an attribute when the object is spawned but I haven't checked how the Objects array is used yet to confirm it's not getting memset at some point after allocation. The GetId method just uses the index (from the dObject cell value) for now.
> Use object reference (and self-id lookup) for BreakBarrel

- .editorconfig
- CMakeSettings.json
- docs/building.md
This is mainly to help me test code builds under GCC faster than pushing to the remote and letting the build server do it. If someone without WSL installed selects the build target they'll get an error in their IDE, but no harmful impact other than that. The variables should be populated for any WSL2 installation. No idea about WSL1.
The whitespace in this file is showing significant changes because visual studio regenerates the whole file when a change is made, I didn't think it was worth reverting since it'll happen again next time someone makes a change (seems it defaults to spaces...)
> Add VS configuration for building in WSL using GCC

- .editorconfig
- Source/engine/render/text_render.cpp
- Source/minitext.cpp
- Translations/zh_CN.po
- Translations/zh_TW.po
- tools/zh_segmenter/README.md
- tools/zh_segmenter/segment.py
Adds a tool can insert ZWSP between words in Chinese .po files using this model: https://tfhub.dev/google/zh_segmentation/1
We will use this tool to be able to word wrap Chinese translations at runtime without bundling a segmenter.
Doing this offline also allows us to use a segmenter that would otherwise be too slow for runtime.
The tool takes ~15s to run and depends on Python, TensorFlow, and downloads a model file as needed.
It is too heavy to run automatically at build time, so it will only be run manually for now:
tools/zh_segmenter/segment.py --input_path Translations/zh_CN.po
tools/zh_segmenter/segment.py --input_path Translations/zh_TW.po
Refs #3162
/cc @tytannial
> Automatically insert ZWSP between words in Chinese translation files

- CMakeLists.txt
I think I finally figured out what was going on here. The `devilutionx_mpq` target was built after the `romfs_files` target. Also, it seems the `romfs_directory` target was being add as a file dependency of the `romfs_files` target which was probably confusing matters.
> [3DS] Fix dependencies for romfs build targets

- Source/platform/ctr/cfgu_service.hpp
- Source/platform/ctr/locale.cpp
- Source/platform/ctr/system.cpp
I'm unable to test this on o2DS myself, but it should work okay based on the documentation. Eventually, it might be nice to enable toggling of the backlight, but it's probably best to wait until control remapping and/or bottom screen UI can be implemented.
This resolves #3444
*Note: If anyone chooses to attempt to test this build, it is highly recommended that you disable Sound and Music Volume in [diablo.ini](https://github.com/diasurgical/devilutionX/wiki/DevilutionX-diablo.ini-configuration-guide#audio) to avoid system crashes.*
> Do not disable backlight on o2DS

- Source/control.cpp
- Source/control.h
- Source/monster.cpp
- Translations/ja.po
The code previously assumed that there is an ASCII separator after each resistance type.
Different languages may use something else entirely. Relaxes the assumption to any single code point to avoid producing malformed UTF-8.
Also fixes Japanese translations to use a space after the resistance (although I think it should be a fullwidth space or an ideographic comma, I'll leave that to the translators).
I'm not sure whether this is the cause of the crash in #3490 as I cannot reproduce it (hero dies too fast from the save).
> `PrintMonstHistory`: Fix string manipulation

- Translations/uk.po
@SourceCodeDeleted please review when you have the time
Scrolling help screen past Automap hits xstring assert "cannot remove prefix longer than total size" on debug builds
I have changed "Гра з друзями" to "Мережева гра" because it sounds better, and looking at some Ukrainian localizations, this is the precedent.
> UK TL: Status bar, CMD options, Help screen

- Source/scrollrt.cpp
> fix debug display in town

- CMakeLists.txt
- Source/controls/controller_motion.cpp
- Source/controls/game_controls.cpp
- Source/controls/touch/event_handlers.cpp
- Source/controls/touch/event_handlers.h
- Source/controls/touch/gamepad.cpp
- Source/controls/touch/gamepad.h
- Source/controls/touch/renderers.h
- Source/diablo.cpp
- Source/miniwin/misc_msg.cpp
- Source/options.cpp
This PR explicitly activates and deactivates the virtual gamepad in the same functions that load and unload the gamepad art. The `isActive` Boolean value is used to determine whether the game should read virtual gamepad state. This prevents it from interfering in UI menus where you cannot see or interact with the gamepad. Deactivation also resets the state of the d-pad and buttons so they don't retain invalid state upon reactivation.
This resolves #3375
> Implement virtual gamepad activation/deactivation

- Source/help.cpp
- Translations/devilutionx.pot
Gold section name didn't end with a colon
https://github.com/diasurgical/devilutionX/blob/08e4e8c25400f09a7d7194a0cfb86e48550585ae/Source/help.cpp#L68
Speedbook sentence didn't end with a period
https://github.com/diasurgical/devilutionX/blob/08e4e8c25400f09a7d7194a0cfb86e48550585ae/Source/help.cpp#L84
Edit: `Using the Speedbook for Spells`, `Setting Spell Hotkeys` and `Spell Books` sections didn't end with colons either
> Fix missing punctuation in Help screen

- Source/debug.cpp
```
../Source/debug.cpp: In function ‘bool devilution::IsDebugGridInMegatiles()’:
../Source/debug.cpp:837:16: warning: enumeration value ‘None’ not handled in switch [-Wswitch]
837 |         switch (SelectedDebugGridTextItem) {
|                ^
../Source/debug.cpp:837:16: warning: enumeration value ‘dPiece’ not handled in switch [-Wswitch]
../Source/debug.cpp:837:16: warning: enumeration value ‘dTransVal’ not handled in switch [-Wswitch]
../Source/debug.cpp:837:16: warning: enumeration value ‘dLight’ not handled in switch [-Wswitch]
../Source/debug.cpp:837:16: warning: enumeration value ‘dPreLight’ not handled in switch [-Wswitch]
../Source/debug.cpp:837:16: warning: enumeration value ‘dFlags’ not handled in switch [-Wswitch]
../Source/debug.cpp:837:16: warning: enumeration value …
```
> debug.cpp Fix `-Wswitch`

- Source/platform/ctr/system.cpp
[single_0.hsv.zip](https://github.com/diasurgical/devilutionX/files/7568499/single_0.hsv.zip) causes the game to crash on 3DS when entering dungeon level 13, due to the amount of recursion in `FindTransparencyValues()`.
If you're not familiar with the function, it seems to be using a flood fill algorithm to mark contiguous regions of floor, as well as the adjacent and surrounding non-floor spaces, with the same "transparency value". Based on the name of it, I would guess this is used to determine which walls should be rendered transparent when the player enters a room. However, it also seems to be used in a few other places, such as when determining whether a monster is in the same room as another entity.
My testing reveals that the function reached about 470 levels of recursion. If my …
> Increase stack size on 3DS

- Source/control.cpp
- Source/help.cpp
- Source/stores.cpp
- Source/stores.h
- Source/utils/language.cpp
- Source/utils/language.h
We ensure that selectable lines are placed at the same vertical coordinates but space out unselectable text lines at the cost of reduced heigh of empty space between the store items.
The back button in scrollable lists is moved to the lower right.
This is a minimal effort. The text is still a bit cramped and the layout is not ideal, this can definitely be improved further but at least it solves the main problem for now.
| Before | After |
|:--------:|:--------:|
| ![stext-orig-1](https://user-images.githubusercontent.com/216339/141049279-98798db7-a417-4014-b4d6-8dad799f5b17.png) | ![stext-new-1](https://user-images.githubusercontent.com/216339/141062390-7fbc5388-709e-4d9c-919f-384c6f78b19c.png) |
| ![stext-orig-2](https://user-images.githubusercontent.com/216339/141049277-34f63da3-0ce2-45a …
> Fix talk/store/help text overlap for Chinese and Japanese

- Source/control.cpp
- Source/control.h
- Source/controls/touch/event_handlers.cpp
- Source/cursor.cpp
- Source/diablo.cpp
- Source/gmenu.cpp
- Source/interfac.h
- Source/inv.cpp
- Source/items.cpp
- Source/player.cpp
- Source/plrmsg.cpp
- Source/qol/itemlabels.cpp
- Source/quests.cpp
- Source/scrollrt.cpp
- Source/trigs.cpp
- Source/utils/display.cpp
- Source/utils/ui_fwd.h
With this change it is possible to play demos in a different resolution then recorded. 📹 
<details><summary>Example Videos</summary>
https://user-images.githubusercontent.com/25415264/131180804-681dd444-e3ea-4d2a-a628-e418b1f9402d.mp4
https://user-images.githubusercontent.com/25415264/131180840-f0fd01f6-5f59-4c99-8877-f6fc116f8e62.mp4
https://user-images.githubusercontent.com/25415264/131180885-3e85644b-f343-473f-a1c5-0451559c0c4d.mp4
</details>
Notes:
- The difference speed of the example videos is cause I used timedemo mode. And timedemo mode tries to progress the playback as fast as possible. And cause larger resolution needs longer to render, the video is longer (see fps counter).
- This change introduces two different views. One for gameplay (used for click position calculation; uses …
> Demo: Decouple recording and playback resolution

- Translations/pl.po
Previous pl string literally translated to english would say:
"1-3 damage returns to you"
Considering that it is thorns affix, I am guessing
the attacker means the enemy of the player, NOT the player him/herself.
The corrected pl string is equal to english one
and it is almost the same as thorns affix
translation from diablo 2.
> Correct polish translation for thorns

- Source/player.cpp
Prevents players from targeting each other with spells in the same way that players are prevented from targeting each other with weapons when Friendly Mode is enabled
> Prevent Spell Targeting Players with Friendly Mode enabled

- Source/utils/utf8.cpp
Also ensure that len is initialised and set properly, otherwise it leads to a call to remove_prefix with garbage.
It doesn't seem useful or valid to return an incomplete code point from this function. To match the behaviour of `mblen` we could have an "incomplete code point" return value, but this at least handles truncated strings better than before.
> Return Utf8DecodeError when passed an incomplete code point

- Source/player.cpp
- Source/player.h
Don't use three different counters for death (`AnimInfo`, `deathdelay` and `deathFrame`).
Instead use only `AnimInfo` so the counters can't get out of sync.
Fixes #3473
> Remove Player.deathFrame and deathdelay and fix death by object animation

- Source/inv.cpp
- Source/inv.h
- Source/items.cpp
- Source/items.h
- Source/loadsave.cpp
- Source/msg.cpp
- Source/msg.h
- Source/player.cpp
This PR refactors Items to remove the redundant AvailableItems array, essentially splitting the ActiveElements (ActiveItems) array into a section for live entities and a section for "free" memory. (This is prep work for #2586). Edit: I thought this had already been done for Missiles for some reason, the same approach can be used there.
I also updated the save/load from file code to decouple the indexes in the save file from the position in the Items array, this allows us to keep save compatibility with vanilla which uses AvailableItems as a list of free indexes. The only real difficulty there was ensuring that dItems maps from the saved values to the appropriate runtime values.
The Item sync code for DeltaLoadLevel originally tried to delete items based on position in the replay/sync data …
> Remove AvailableItems array, maintain ActiveItems instead

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/diabloui.h
- Source/DiabloUI/mainmenu.cpp
- Source/DiabloUI/selconn.cpp
- Source/DiabloUI/selgame.cpp
- Source/DiabloUI/selhero.cpp
- Source/DiabloUI/selok.cpp
- Source/DiabloUI/selstart.cpp
- Source/DiabloUI/selyesno.cpp
- Source/DiabloUI/settingsmenu.cpp
- Source/DiabloUI/ui_item.h
Fixes #3595
`UiList` constructed it's height from itemcount * `item_height`. With #3437 we now pass more then 6 item to the list and so the height is calculated wrong.
This PR pass `viewportSize` directly to UiList (instead of `UiInitList`) and calculate `UiList` height from it.
Helps also #3567 (scroll bar is still missing)
> Pass viewportSize to UiList constructor and calculate height from it

- Source/inv.cpp
- Source/items.cpp
- Source/pack.cpp
- Source/pack.h
- test/pack_test.cpp
This was a holdover from when the Item creation/initialisation functions operated on an index into the global Items array. Now that they all operate on Item& arguments there was no need to use Items[0] as a temporary space.
As far as I can tell this is every explicit reference to Items[0], but I can't be sure since Visual Studio seems to like breaking its search indexes on my machine...
> Remove uses of Items[] as a temporary for other Item variables

- Source/items.cpp
This should hopefully make it more clear what this function is doing.
Instead of several small loops (some unrolled) that works on part of the `witchitem[]` one big loop that iterates over all items in now used instead. And each body is now an if-block that checks to see if the loop is in the range that it acts on.
There are 2 functional changes to the function:
- The 3 reserved items are now assigned a seed value. This is to simplify how the store works (instead of assigning it on purchase).
- `itemCount` in Diablo mode was 5 higher then it should have been since we added Hellfire.
Note: There might also have been a bug in vanilla where only 18 out of the 20 witch items would be used, or it was lazily reduced to 18 on purpose with out resizing the array.
> Clean up SpawnWitch

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/settingsmenu.cpp
- Source/DiabloUI/ui_item.h
Depends on #3576
Notes:
- Currently can't use `DrawStringFormatArg` directly in `ui_item.h`, cause it's defined in `text_render.hpp` and `text_render.hpp` includes `ui_item.h`. Currently resolved with forward declaration.
- With translations or longer new options the text could be too long and we need to split the entry in two lines. Do we need a new `GetLineWidth` and/or `WordWrapString` overload that supports `DrawStringFormatArg`?
<details><summary>Sample Video</summary>
https://user-images.githubusercontent.com/25415264/143327777-d77741ca-a0be-4400-ac4e-8ff4bc36b4fa.mp4
</details>
> Use DrawStringWithColors in settingsmenu

- .github/workflows/src_dist_release.yml
Seems to default to Python 2 on Ubuntu 20.04, whereas we use Python 3
(previously failed at https://github.com/diasurgical/devilutionX/runs/4337688960?check_suite_focus=true)
> .github/workflows/src_dist_release.yml: Fix python

- Source/engine/render/text_render.cpp
- Source/panels/charpanel.cpp
Improves char panel layout and fixes it for CJK
Chinese:
Before | After
---|---
Japanese:
Before | After
---|---
English:
Before | After
---|---
Fixes #3621 
/cc @bubio @tytannia
> Char panel layout improvements

- tools/build_and_install_smpq.sh
Useful when developing on systems that do not have an SMPQ package.
Should be compatible with Linux, *BSD, Mac.
> A script for building and installing smpq from source

- .github/workflows/Windows_x64.yml
- .github/workflows/Windows_x86.yml
- CMakeLists.txt
- Source/main.cpp
The `SDL_main.h` header defines `main` to be `SDL_main` *when needed by the target platform*. This header must be included before defining `main`.
The `SDL2::SDLmain` library should be linked only to the executable, not to `libdevilutionx`.
> Link `SDL2::SDLmain` correctly

- Source/diablo.cpp
- Source/options.cpp
- Source/options.h
Extend `Intro` option in `diablo.ini` with:
- **2**: No Intro  (equivalent to `-n` command line parameter)
- **3**: Show Title Dialog only (I like the title dialog 😉)
With this another alternative to command line arguments is present. This is relevant for platforms that don't support them (for example android).
Note: existing values (0 = no cinematic and 1 = initial show cinematic once (at first start)) stay the same for compatibility.
> Allow to customize shown intro in diablo.ini

- Source/DiabloUI/settingsmenu.cpp
- Source/init.cpp
- Source/init.h
- Source/options.cpp
- Source/options.h
- Source/utils/language.cpp
- Language list is at the moment hard coded. This could be improved in the future (searching for  *.mo/gmo files).
- No validation is currently applied (could be added later; for example check if language files really exists)
- UI needs to be recreated, cause we need to reload all texts (this will also be needed if we change resolution)
- I'm unsure if the language setting ("Languages") and the languages list ("English", "Spanish", ...) should be translatable. At the moment they aren't
- Didn't test polish voice pack
- UI could be improved (not part of this pr; for example we could show a sub-menu with the list entries)
https://user-images.githubusercontent.com/25415264/143745625-a7269988-b7c7-4a15-ad5f-98d7567d8fee.mp4
> Settings - Add language selection

- 3rdParty/libmpq/CMakeLists.txt
- 3rdParty/libsmackerdec/CMakeLists.txt
These are the only new commits:
https://github.com/diasurgical/libmpq/commit/0f10bd1600f406b13932bf5351ba713361262184
https://github.com/diasurgical/libsmackerdec/commit/792527435722151aff1a5b11f0862b957563d10b
> 3rdParty: Bump versions of libmpq and libsmacker dec

- CMakeLists.txt
Instead of using the `GETTEXT_PROCESS_PO_FILES` function, do it ourselves in a cleaner way.
This fixes a number of issues:
1. Translations and assets are now built whenever the binary is built, without causing the binary to be rebuilt.
2. Translations are only copied to `build/assets` (previously they were also copied to `build/`).
3. This should now be compatible with the new XCode (@bubio who hit this issue).
4. Visual Studio and VS Code now generate the assets when running/debugging the binary (@qndel who hit this issue).
The main new trick we're using is to depend both on the command output file and the associated custom target.
The translation target has no outputs, so the targets that depend on it are not rebuilt when it changes.
Depending on the command output file as well triggers …
> CMake: Improve translation deps handling

- CMake/android_defs.cmake
- CMakeLists.txt
Previously, only the translations were copied for Android at build time. The other assets were copied only at configure time.
Replaces Android-specific handling with a general mechanism to override the build-time assets directory.
> Android: Fix assets copying

- .circleci/config.yml
- CMakeLists.txt
Based on comments from @MrHuu (https://github.com/diasurgical/devilutionX/pull/3458#issuecomment-973223677), it seems the 3dsx build can be used on a 3DS console without CFW if it is first loaded onto a flashcart.
Now that Smacker videos are being streamed from the SD card, o3DS consoles should be able to make it through the intro video with only 64 MB of RAM available. However, additional testing reveals that sometimes dungeon levels may require close to 64 MB of RAM. The game may run out of memory and exit unexpectedly during a loading screen when played for a prolonged period of time. Therefore, o3DS users should be cautious and save their game often if they choose to play using the 3dsx build.
> Add 3dsx back to the 3DS build

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/diabloui.h
- Source/DiabloUI/mainmenu.cpp
- Source/DiabloUI/selhero.cpp
- Source/DiabloUI/selok.cpp
- Source/DiabloUI/selstart.cpp
- Source/DiabloUI/settingsmenu.cpp
- Source/DiabloUI/title.cpp
- Source/diablo.cpp
- Source/options.cpp
- Source/options.h
- Add Game Mode to Settings
- Add Shareware to Settings
- Remove Special Actions `Switch to Diablo/Hellfire` and `Switch to Fullgame/Shareware`
- Unify `gbIsSpawn` and `gbSpawned`
> Settings: Add Game Mode and Shareware and remove specials in settingsmenu

- Translations/uk.po
Wanted to only translate the spell book but went on a roll
@SourceCodeDeleted please take a look
Because of the chaotic TL process, I just squashed everything into one commit, which might make it hard to review. Just ignore the lines where only numbers changed. Split view might make it easier
TL'd sections:
* Spellbook with new UI
* Settings menu
* Shrine names
* Towner names
* Shop UI
* Container names
* Item descriptions
* Book titles
* Character screen
* Quest names
* Spells
* Up to (level) - Down to (level) text
Might've missed something. Like I said, I went on a roll 😊
> UK TL: A lot of stuff

- android-project/app/src/main/java/org/diasurgical/devilutionx/DevilutionXSDLActivity.java
It turns out that #3329 and #3553 are the same issue.
I was completely unable to reproduce these errors on my Pixel 4, but the Pixel 2 AVD running Android 10 reproduced them quite easily.
As @AJenbo pointed out (https://github.com/diasurgical/devilutionX/issues/3553#issuecomment-974666734), `System.exit(0)` does not seem to do anything. The game still shows up in the task switcher and will restart when selected from there. However, it seems that under the covers the OS will reclaim heap data without reclaiming or reinitializing static data if you do not use it. This causes the static `controllers_` vector to maintain a reference to a deleted `GameController` instance on restart.
This change also has the nice added benefit of detaching the Android Studio debugger on exit.
This resolves …
> [Android] Clear memory on exit with System.exit(0)

- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/diabloui.h
- Source/DiabloUI/settingsmenu.cpp
- Source/diablo.cpp
Fixes #3668 (hopefully)
`UiPollAndRender` calls `UiHandleEvents`
`UiHandleEvents` calls `ItemSelected`. We change the language, mark the UI to be recreated.
But after that `UiPollAndRender` calls `UiRenderItems` once. And then we could access freed memory.
This pr avoid this by do the cleanup first (with `UiInitList_clear`), change settings and then recreates the UI and settingsmenu after that.
I don't own a mac, so can't verify it.
@bubio could you test this pr to verify if this fixes your crash on macOS?
> Settingsmenu: Clean up UI-Resources before switching options that require RecreateUI

- CMake/android_defs.cmake
1. Organize and comment on various options that we set.
2. Disable all system dependencies explicitly instead of relying on auto-detection for some of them.
> android_defs.cmake: Cleanup

- CMakeSettings.json
- Source/dx.cpp
- Source/engine/demomode.cpp
- Source/options.cpp
- Source/options.h
- Source/utils/display.cpp
- Source/utils/ui_fwd.h
Notes:
- Add the possibility to resize the game and switch between window and fullscreen mode.
- Add the possibility to recreate upscale renderer (similar to #688 but not exactly the same).
- Added the follow settings to settings menu
- Fullscreen
- Fit to Screen
- Upscale
- Integer Scaling
- Vertical Sync
- Fixed Scaling Quality doesn't instantly update when changed in settingsmenu,
- Settings are only active if supported (for example upscale is not supported in sdl 1).
- Added new VS configuration for SDL 1 on windows (based on the work done in #3392).
- Tested with SDL 2 and SDL 1 on windows.
- Is the groundwork for resolution changes,
> Settings: Add graphic settings that resizes the window

- Source/utils/display.cpp
Some devices may report the screen orientation in portrait mode, but we need it in landscape mode since that is what we will be configuring.
Also simplify the calculations for integer scaling (and flip the case/order).
> Handle screen orientation

- Source/controls/touch/gamepad.cpp
on iOS the windows size is reported in a size that matches the DPI of the original iPhone rather then the actual DPI. Getting the render size should give us the correct scale for all devices.
Hopefully this also works correctly on the iPhone 8+ which adds another layer of craziness by rendering at a higher resolution then the actually pixel count and then reports a fraction of that as it's windows size...
https://www.paintcodeapp.com/news/ultimate-guide-to-iphone-resolutions
> Correct DPI on devices that apply extra scaling

- Source/options.cpp
Addresses [modernize-use-emplace](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-emplace.html)
> Use emplace_back when constructing pairs for language list

- Source/qol/itemlabels.cpp
… (LastMouseButtonAction != None)
Fixes #3232
@qndel 😉
> Item highlighting: don't change cursor when a repeated action is requested

- CMakeLists.txt
- Packaging/apple/Info.plist
- Source/platform/ios/paths.h
- Source/platform/ios/paths.m
- Source/utils/paths.cpp
My changes are to help people transfer their MPQ files to their iDevice so that they are able to run the game. These CLs allow 2 methods to achieve this.
The first step regardless of the method is to launch the app. For now, it will simply give you a messagebox saying it cannot find any MPQ file. This is fine though because it will have created diablo.ini and saved in the Document directory from the app's sandbox. Doing this will now expose the directory to the user.
- The first method is to copy the MPQ using the file browser app in the app's Document directory. There are a multitude of ways that the can get the MPQ file onto their iDevice (Cloud Storage such as iCloud, Dropbox, Google Drive, etc or using a shared network drive for example)
- The second method, is via iTunes on Windows …
> [Ios] load files from file browser

- Source/utils/sdl2_to_1_2_backports.h
As per the documentation (https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlsetvideomode.html), `SDL_Quit` does this for us.
> SDL1: Don't destroy surface in SDL_DestroyWindow

- Source/inv.cpp
I missed this when resolving merge conflicts :/
> fix negated check in SyncGetItem

- Source/dx.cpp
- Source/dx.h
- Source/utils/display.cpp
When the `PalSurface` is smaller than the game window, it causes graphical glitches and buffer overruns. This resolves the issue I found when fiddling with the resolution settings PR (https://github.com/diasurgical/devilutionX/pull/3688#issuecomment-987482770).
> Resize PalSurface when resizing the game window

- Source/engine/demomode.cpp
- Source/options.cpp
- Source/options.h
- Source/utils/display.cpp
This pr allows to change the resolution ingame.
Notes:
- List with resolutions if populated by monitor resolutions (`SDL_ListModes` / `SDL_GetDisplayMode`).
- if `ini` contains a resolution that is not part of the monitor resolutions it is preserved.
- Default resolution (640x480) is always added explicitly.
- Tested with SDL 2 and SDL 1 on windows.
> Settings: add resolution option

- .github/workflows/Windows_x64.yml
- .github/workflows/Windows_x86.yml
- Packaging/windows/mingw-prep.sh
- docs/building.md
Modifies the MinGW build scripts and instructions to use the `libz-mingw-w64-dev` package instead of the zlib dll provided by SDL-ttf. I also added `-DDEVILUTIONX_SYSTEM_BZIP2=OFF` to the build instructions since I couldn't find a package for it.
This resolves #3037
> Use distro zlib package for MinGW instead of SDL-ttf zlib dll

- CMake/platforms/amiga.cmake
- Packaging/amiga/Dockerfile
- Packaging/amiga/prep.sh
- docs/building.md
1. Run Docker as the current user instead of root, removing the need to chown directories.
2. Copy `devilutionx.info` via CMake, removing the need to do it manually.
3. Cleanup `prep.sh` somewhat.
> Amiga: Cleanup build process

- Source/items.cpp
Resolves https://github.com/diasurgical/devilutionX/issues/3707
This PR introduces a situation I'd consider a feature
Helm gives +9 attr, equipping civerb's disables the helmet which makes me not meet the stat requirements for the bow anymore, but since it's in my cursor, I can still equip it. Equipping it will bring the stats back = I can use it.
If stats after equipping would still be insufficient, it'd turn red as before. This just prevents a situation where swapping 2 items could make the one in cursor unusable.
> tweak item stats checking

- Source/DiabloUI/button.cpp
- Source/DiabloUI/diabloui.cpp
- Source/DiabloUI/selhero.cpp
- Source/DiabloUI/ui_item.h
Makes me feel like I'm writing Java code with all these getters and setters 😂 . Most of the members are constant/write once so it makes sense to define only a getter. This allows defining these members as private to address `misc-non-private-member-variables-in-classes`. Then the few members which actually need to be modified get wrappers with (hopefully) more descriptive names where possible.
The classes I haven't fully cleaned up either have platform specific handling or make heavy use of `SDL_Rect`. I'll do those as a separate PR since that'll be another large diff.
> Apply clang-tidy configuration to (some of) ui_item.h

- CMakeSettings.json
It seams that visual studio default selected the first option in the combo-box.
And the combo-box is sorted by name.
That's why the WSL configuration is default selected.
With this PR now `x64-Debug` is now again the default.
I think that's a better default for most developers.
Noticed this cause visual studio switched sometimes to the default back.
Master | PR
-- | --
> VS Configuration: Rename WSL configuration, so that it doesn't get default selected

- Source/monster.cpp
This check was needed back when monsters current position could appear as a negative index. Since it has been fixed this check should no longer be needed.
> Clean up check for borken monster position in DirOK

- Source/mpq/mpq_common.hpp
- Source/mpq/mpq_writer.cpp
- Source/mpq/mpq_writer.hpp
I've spent some time understanding how the `MpqWriter` works and cleaned it up a bit and renamed some variables for clarity.
1. Fixes all signedness and clang-tidy warnings.
2. Renames variables, structs, and methods for clarity.
3. Marks structs used for I/O as packed.
4. Adds comments in a few places.
5. Eliminates recursion from `MpqWriter::AllocBlock` (a clang-tidy warning).
> MpqWriter: Cleanups and renames

- Source/diablo.cpp
- Source/monster.cpp
Fixes #2700
Alternative to #3733
Notes:
- See discussion in #3733 
- Checked both save games in #2700 and the monsters are not spawned in doors 😉
> Check that monsters aren't placed in doors V2

- Source/control.cpp
- Source/inv.cpp
- Source/items.cpp
- Source/player.h
`CheckItemStats`, `ItemMinStats`, and `StoreStatsOk` all did effectively the same thing. The `item.statFlag` variable itself can be replaced by a check against the local player but with the way this check is used it's sometimes hard to define what is the local player (especially when building the save game list). I've done a very limited dedup/cleanup here to avoid breaking things by trying to remove runtime use of `statFlag` completely.
> (Partially) deduplicate code used to check if a player can equip an item

- Source/items.cpp
- Source/pack.cpp
- Source/stores.cpp
More prep work for rewriting stores.cpp
Vendor item stat checks were being performed at some really odd times:
- When reading a hero from a save game (select hero menu etc.)
- When generating the vendor items
- Reparing, identifying, recharging, applying oil, buying, resurrect, changing equipment
- Joining/starting a game, entering town
- Applying stats
Instead of all that craziness simply calculate it when opening the vendor item list.
> Perform item requirement check when entering vendors

- Source/loadsave.cpp
Fixes #3734
Notes:
- `SyncPortals` was called twice (once in `LoadLevel` and once in `LoadGameLevel`)
- That means `AddTown` was also called twice. The first call creates a town portal. The second call sees this town portal (`TileContainsMissile` is true) and places the second town portal near the first town portal. But a player is only allowed to have one town portal. That's why the first town portal gets deleted (in the video in the pr you can see it for a short period).
- Fix is to call `SyncPortals` only once.
- 9964bd9e495314e2d466eeb6a0c11d3c12c963ae only worked, cause the check for existing missiles/town portals was broken before this commit/bugfix.
- Alternative fix could be to check if new to place town portal is on the same location as a existing town portal from the same player …
> Call SyncPortals() only once for a level load

- Source/options.cpp
Likely a much better alternative to #3750.
This resolves #3708
> [Android] Hide the Upscale option in the settings menu

- Source/options.cpp
- Source/utils/language.cpp
This PR looks for all region-specific locales according to user preferences to find a matching translation. The last commit updates the fallback behaviour to look for non-regional translations after the last regional variation of a given language.
For example, a user preference of `en_AU, fr_FR, en_US` will search for translations in the order `en_AU, fr_FR, fr, en_US, en`. `en_AU` is the first preference so will be checked first, but because another english regional variation is in the list to be checked in the future we do not look for non-regional translations yet. `fr_FR` is immediately followed by a check for a non-regional `fr` translation as no other regional variations were specified. Finally `en_US` then `en` are checked being the last regional variation of english in the list of …
> Handle multiple language preferences on windows

- Source/control.cpp
- Source/diablo.cpp
- Source/options.cpp
- Source/options.h
Allows QuickMessages to contain multiple lines that are executed as separated messages.
This is currently useful for two cases:
- Executes multiple debug commands in a batch (requested by @qndel)
- Show rules or other information in public server
```
[NetMsg]
QuickMessage1=Welcome to my server. There are rules you have to follow:
QuickMessage1=1. Be nice to each other.
QuickMessage1=2. Don't run the game in debug mode.
QuickMessage1=3. I'm the only one that is allowed to run debug commands!
QuickMessage2=god
QuickMessage2=changelevel 3
QuickMessage3=Here's something for you.
QuickMessage4=Now you DIE!
```
<details><summary>Video with example ini</summary>
First pressed F9/QuickMessage1 and after that F10/QuickMessage2.
https://user-images.githubusercontent.com/25415264/138610697-772e91b6-5 …
> Allow QuickMessages to contain multiple entries/lines 

- Source/options.cpp
Fixed typo in Reju pickup option 
Changed pickup choices from 0,1,4,8,16 to 0,1,2,4,8,16
> Fixed typo in Reju potion pickup

- CMakeLists.txt
This introduces a `PROJECT_VERSION_WITH_SUFFIX` variable which includes the version suffix only for Debug builds.
* Dash character is no longer prepended to the `VERSION_SUFFIX` variable, but is instead added to the `PROJECT_VERSION_WITH_SUFFIX` variable as needed.
* If `VERSION_NUM` is predefined, but `VERSION_SUFFIX` is not, force a generic value of `debug` as the `VERSION_SUFFIX`. This allows us to append the version suffix to debug builds more consistently, making it clear when a build is a debug build even if we can't get a commit hash.
* Modified the generator expression to apply the version suffix to `CMAKE_BUILD_TYPE=Debug` only. `MinSizeRel` and `RelWithDebInfo` will no longer have a version suffix.
Based on feedback from …
> Improve CMake logic for version suffix

- Packaging/apple/Info.plist
This key is required for over 60hz for the iPhone 13 Pros.
> Add ProMotion support for iPhone 13 Pros

- Source/utils/paths.cpp
- Source/utils/paths.h
Also adds `SetAssetsPath`, for use by tests.
See discussion in #3770
> AssetsPath: Default to exe dir

- test/CMakeLists.txt
- test/main.cpp
This should hopefully fix DLL lookup on Windows (#3778)
@tsunamistate @obligaron Can you please see if this resolves the issue?
> CMake: Place tests where everything else is

- CMake/Assets.cmake
The `target_sources` command was changed in the test overhaul PR but that was incorrect.
Fixes #3784
> Fix asset bundling on Apple systems

- Source/options.cpp
Turns out the issue is the same on MacOS 10.3 (intel GPU), I'm assuming it will be the same for iOS and friends.
> Disable recreation of the rendere on Apple systems

- Source/gendung.cpp
One peculiar thing about the original algorithm was that it traversed megatile coordinates to fill the corresponding tile coordinates. A careful review of that code reveals that the pattern in which it filled the corresponding tiles resulted in the floor being completely filled, plus all the immediately surrounding non-floor tiles. Rather than carrying that strategy over to the rewrite, I concluded that it would be simpler to have the fill algorithm traverse the floor tiles and then fill in the surrounding non-floor tiles as it went.
Additional notes:
* The algorithm as written on Wikipedia scans left but not right. However, tweaking the initial seed is enough to fix it.
* The lambdas help to make the function resemble the Wikipedia pseudocode pretty closely, but I did rename the …
> Use span filling algorithm for FillTransparencyValues

- Source/gendung.cpp
After scrutinizing some of the code I added to this algorithm, I realized the scan-right isn't guaranteed to end on a point inside the shape if the scan starts on the edge of the shape. The diagonal check requires that the point that was passed in is on the inside of the shape to avoid false positives. Since the algorithm has already filled in that tile, I couldn't use `isInside()` to check, but this change should satisfy the precondition.
> Prevent erroneous diagonal traversal in span filling algorithm

- docs/building.md
Add gmock and cpp-static libraries to Fedora build instructions. Otherwise, building on FC35 will not work.
> Update Fedora build dependencies

- Source/platform/ctr/system.cpp
With the resolution of #3543, the attached savegame no longer crashes on 3DS at the default stack size. For that matter, `FindTransparencyValues()` now requires very little stack space as there is no recursion, the stack is heap-allocated, and it only grows to a few dozen seeds at most. So long as there are no more instances of "extreme" recursion (~100 function calls deep) lurking in the codebase, we should be able to drop the stack size back down to its default on 3DS.
> Reduce stack size on 3DS
